table xy
	lineageTag: 0c4e0b2f-b2cb-4c3e-9856-5ecc47037d92

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 06b491d5-049f-4dab-9d1a-23acdff80d56

	partition 'xy-b6599fb0-691d-400d-aa97-70b685354a1e' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				    #"xy Table" = Source{[Schema="dbo", Item="xy"]}[Data],
				    Result = #"xy Table"
				in
				    Result

	annotation PBI_ResultType = Table

