table Extract
	lineageTag: b921e1b3-cab4-477e-ad92-a60f4a6cb054

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 0ce9d744-039c-4d1f-bba0-36ae609714d4

	column 'Number of Records'
		dataType: int64
		lineageTag: 442a98c1-0031-4bad-a529-b503d0df7704
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: 885b957f-dcef-45b0-9581-6308778fd129
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 40ecf63f-cf02-4a7f-9a40-1901e636c605
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 8344e717-7049-429a-a7db-84d2d349e6fd
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-6fda6494-f546-4717-937f-81a7dcad20c5' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("mssql2012.test.tsi.lan", "TestV1")
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

