table Calendar
	lineageTag: 4cc00a78-a76a-4808-affa-22de3373f275

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5ce31628-90a9-4172-af87-44ac6a6b5ab5

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 35aaac12-1a12-4ba7-8703-1457a7a8e54e

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 3f426dac-3ff4-4a18-a035-7f0a105888c6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: baa1b749-92a4-49cd-89d1-9ca79e677001
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d152a237-40f7-4f5d-909b-b544dd195234
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b61a6ebb-5c4b-4079-b601-a6707aee6df5
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a341d912-7500-4d60-a9ad-f30717e5f1a8
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1c825feb-2e03-40e4-9951-b2fff0d8106b
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bf58ac7c-fc43-4726-a0f2-d7b369147422
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 38c019d9-e4ec-4511-af28-b39ed7ab961f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: dc6a69f1-a93b-4cd8-8888-6e464e2ebe64
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 336dd9ac-593e-43ff-8cfe-eb33403a57cf

		level Year
			ordinal: 0
			column: Year
			lineageTag: 09c4200d-72f6-4b32-a247-cf482192e278

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d6e1f2f2-4eaa-41e0-92fb-d511b3e199bd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 23ec985c-66e9-4663-9b8b-97c5bb8f8a1a

		level Day
			ordinal: 3
			column: Day
			lineageTag: 8ad9460f-c03a-43f7-8659-0db4a0c1f5fc


	partition 'Calendar-da36913b-2241-44cb-869a-f53df068407d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

