table Calendar
	lineageTag: 92677734-2fbd-4f08-8fb0-3a6d871f0fad

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 203eb929-b051-4bbf-a09d-fd64531e887b

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 54b95d1a-70d4-4fbd-bd7f-9040df65d3a0

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 62a351f4-d686-4362-bc37-c2ec8560c266

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0b14e0af-cd7f-44dd-a93c-f4b9dfd587b2
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ce356c9f-fbf5-4011-bd86-f7cd6ae098d4
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c977cbf0-691f-46e2-9278-503e1aaac608
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d44a42de-f1e8-47c8-bb5e-8f445b989483
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 02f38b4a-f224-4484-8d29-1768e3f62df1
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3ab475c4-bc98-46da-809d-3b7d80b42481
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c1db1470-09e8-4bc2-9b86-09acc8008268
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 76891a4a-4431-4f4c-8efe-38c78302dca7
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ad778b01-a8d2-4c50-8828-2c22e6c9da86

		level Year
			ordinal: 0
			column: Year
			lineageTag: 3ddc4384-06cc-433b-9b88-4655f063cffd

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: da134ed0-2028-4fcd-932b-c963099e51b9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c275b4a3-78d9-4068-8e3a-8c5321a0749c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4c21d26a-e9ba-4f11-8849-a13b983698dc


	partition 'Calendar-52156db3-6864-4a66-8597-7015193cd3b8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

