table Calendar
	lineageTag: 550f4a04-ae34-44bf-80af-6038f445749f

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 271e1412-5194-4906-9573-480b24dc27fb

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 30beb8a2-e066-4658-bec6-6565e09d7f4a

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 52639297-be7b-4c82-af26-c4279d6b7c93

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6de97851-980c-4474-99b7-92c52905a75f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f0618083-f240-42bb-90b9-db7b53baec9e
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 800a34b4-b538-49ea-a3c7-609fdc95ba2c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ce784f09-4bff-49d6-8de6-9a5c9116cc54
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 7d6ae478-4a73-4f72-98bc-e77655bd2fe0
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 9696b966-5c82-4a9f-b0b0-5c7cbdb8e562
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 10a267b5-c342-43e7-ad5c-6ff5e5ec3ccd
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 35d389c3-d6dd-47be-bfc9-0fe2a8927132
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: dd0c5fbc-ceca-49fa-87ab-df8ab9505353

		level Year
			ordinal: 0
			column: Year
			lineageTag: a91fe4c5-2dba-44c4-b594-d685aa22f7ce

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 80ad54f9-1769-4328-b35e-9dc5696add9d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 65ebfbaa-e6fc-48c8-8db5-08e4e9d8cabb

		level Day
			ordinal: 3
			column: Day
			lineageTag: 43bbaf3a-3947-4534-9684-810932af773d


	partition 'Calendar-3e393e3e-50de-4695-97ab-2145937b3100' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

