table Calendar
	lineageTag: 2707af1f-ab93-459b-8d55-6817f4c82f45

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1c52081a-1ced-4622-9db6-6e7dc787f2c7

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 036e0b40-1e7f-4eb3-aa82-2b930e75a6df

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 799f165a-81e6-491c-9e8e-5ac576cb410d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c2252b54-12e7-4e2f-b831-aae4d45f4259
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 30a45445-8b81-4caf-8526-ded487b7f2b8
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0ab8ea97-7376-4600-bc49-96e5f89dc8cd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f20c8814-1d2d-4c76-983f-e56297aba411
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b7cf29b9-f5a0-47be-8767-05c3a7207818
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0bb2e8a2-5231-42ef-a9ad-90a9148216a5
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e9df04f0-5dd5-436a-b73c-f72c194b8aa7
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 56484a7b-2acb-4fc1-9b5e-c21a94dc9ad0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: fecf3956-77be-4fae-87b5-7a0f98e75ecf

		level Year
			ordinal: 0
			column: Year
			lineageTag: c583c954-ab31-4360-9fa6-048aae9d3837

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 81534c9b-baca-4f9e-9526-c61ea21f4141

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4e68be90-fd75-4c52-a6c4-4732afbcc080

		level Day
			ordinal: 3
			column: Day
			lineageTag: 16b29915-ca62-4a54-aab6-43e3e12855fb


	partition 'Calendar-6e5a0261-351c-4a0c-a12f-92d7683bf69e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

