table Calendar
	lineageTag: 2b463991-da0b-4165-9bc9-2daf943bd0d2

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: bdacd6d2-cb90-4fb7-bba2-4f9a1d60f4d5

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 37b3902c-0583-4257-b2f1-391bcf2e7302

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 7f5d49d0-17f4-4bbf-8b97-7ceca5dabccf

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9919e8c7-a2c1-4987-8533-c41e947849dd
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5dbf82f8-827b-41c4-9b38-e2c4878ad5a2
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7c586fff-49a6-42fa-84bc-6bee8ed14d6b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: dc938c2b-4761-4372-b07a-839c3e257bbb
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f49e96d0-2238-414b-a393-71f9594c3416
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f9c57fb9-0e4a-4462-b551-70dd7efad310
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 3398e0e3-08eb-4616-9169-f41d0c6ad856
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 0ee1a325-8ef7-4f83-9f36-32877bf1001a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f4f41f3e-34aa-45e2-a577-661e228d4dce

		level Year
			ordinal: 0
			column: Year
			lineageTag: f0634472-994b-4e04-9762-aff1de65b7cf

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 7d44baa5-527b-49f1-b32a-2fa8f095f831

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0b1e7b0b-6aa0-4306-aa83-2a1516a62ae7

		level Day
			ordinal: 3
			column: Day
			lineageTag: 13b9471c-e25a-45e5-b38f-50d8dee6c02c


	partition 'Calendar-1559c139-aab4-46a2-a3f9-af1b57159a4f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

