table 'Profit Bin Size'
	lineageTag: d59c813d-60de-4afd-875f-ad607bd0e289

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 670f1e2a-bfc6-4fbf-9c73-5eabcbaac0a0

	column Value
		dataType: int64
		lineageTag: a631c260-c9e3-407a-b910-9769623b9052
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-5578325f-c227-4672-97d5-874ce5654044' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

