table 'Profit Bin Size'
	lineageTag: 73bb902b-017d-4c8f-8034-3496e22670da

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 1a519759-f1c3-4477-a9c6-d8c9e7de3b41

	column Value
		dataType: int64
		lineageTag: 3364f553-d56f-463a-b85c-e9d1eba7b1e2
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-5299d592-e10f-4025-93a7-cbc353c8769a' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

