table 'Profit Bin Size'
	lineageTag: 0c4768a2-6298-4f49-a168-9c276a664fa0

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 20ed742b-29b1-4d32-bac4-e882d99c3246

	column Value
		dataType: int64
		lineageTag: c70a7447-57a9-4da3-a5f9-ba22b2db4108
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-15fb285a-1fe8-4f30-8163-c5f500c5860d' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

