table 'Profit Bin Size'
	lineageTag: 60dfeb12-a73e-49c1-9902-b71f5e4ab674

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 7ef5cab6-9f87-46af-8f11-d1cc25a0591d

	column Value
		dataType: int64
		lineageTag: 705ce238-1efa-4567-8504-d1571edbe9ab
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-d1b2f2f7-360b-4a2f-b0ff-b1433f9075ae' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

