table 'Profit Bin Size'
	lineageTag: d1caf59e-7a0d-472e-ad48-04249d0c8773

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 192f2295-56e0-48b3-9ecc-47b5b2be49b3

	column Value
		dataType: int64
		lineageTag: b98cb93d-e82c-4186-ab03-6c4011554ae3
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-8fbb6fe2-2c3a-4bb9-9c24-fb0067ee18fc' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

