table 'Profit Bin Size'
	lineageTag: 0e610e67-4d84-41d8-a720-097fe8304fd2
	description: Contains 1 columns and 1 measures: Value.

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		description: DAX: SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: a09755db-6ed7-4cb8-8e42-4a17c34a82cf

	column Value
		dataType: int64
		lineageTag: 7435b5ab-dada-49b0-891e-662166bcf107
		summarizeBy: none
		sourceColumn: Value
		description: Int64 column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-a6331926-55be-4df4-bbe4-930e7131ef5a' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

