table 'Top Customers'
	lineageTag: 1f372169-e919-470a-9ef6-78e861ccf35d

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: f9f7c088-2459-420d-97c6-f91115021f59

	column Value
		dataType: int64
		lineageTag: f2ebdb9a-a8d1-47d8-a2f2-b4ea432d1821
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-fb72835e-98b5-4631-9008-58df4fc42898' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

