table 'Top Customers'
	lineageTag: a88a9394-daa1-4df3-ac3d-372caa3167cd
	description: Contains 1 columns and 1 measures: Value.

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		description: DAX: SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 7a9e14e9-3370-447a-a847-a4d84e1d7a09

	column Value
		dataType: int64
		lineageTag: ead74314-b59a-425c-bd69-33b613ccbc47
		summarizeBy: none
		sourceColumn: Value
		description: Int64 column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-08f8177d-3559-4d27-a747-7898d687d508' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

