table 'Top Customers'
	lineageTag: f40b9a9b-35ba-49eb-93e3-96e737558065

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 80f75f3e-6b01-42d6-9b0c-a975a8c2a16d

	column Value
		dataType: int64
		lineageTag: c85417c8-8f22-4dab-8eaa-4bd68a372dd5
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-57c4fb9f-7f3a-40fc-a857-64da3831f888' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

