table 'Top Customers'
	lineageTag: 23ce80b9-fb69-41aa-9394-9902b119b7b2

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: f8af9655-d3c5-4d57-b5f7-86d96b8c848a

	column Value
		dataType: int64
		lineageTag: d1e44cbc-2599-4df2-be51-1243f14027cd
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-eb482c87-35ee-4b0a-b4a0-18db18775a9f' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

