table 'Top Customers'
	lineageTag: 343b12a6-61a9-4b3f-86a4-91ad2def5a81

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 8f60eb94-04cb-4600-ab82-c38616097db7

	column Value
		dataType: int64
		lineageTag: cacec767-af81-414d-8c37-78972161d24f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-fed10f3f-b07b-4cfe-a027-ac87a6d83a2d' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

