table 'Top Customers'
	lineageTag: 4e3551ce-c6d4-4624-a9de-b45c8896ba37

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 28908441-8517-4886-b579-98580c84fb89

	column Value
		dataType: int64
		lineageTag: 3fe50b7c-db3d-4240-845f-c928cbdd347d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-8eaf1bfc-ca39-4123-99c0-2e15e7db4ad4' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

