table Calendar
	lineageTag: 48948c6c-a1f7-40c9-91ac-c90e312e9e06

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ef2f2d1f-3340-404f-a99b-1977cf3b4540

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 493ad23e-0f06-49df-bd44-0f625eccca02

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 2f533a01-8cc3-4007-9979-73c41ba5944d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 97a7b479-e57e-4dfb-9c67-b5c9d2f8bf41
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 876f3146-69ce-4b6e-b02e-c7ea9360dc3b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 2e1a2ad6-8e2a-4bdb-950e-bdb468301f89
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d2e85060-ebd7-4c80-9b5a-fc88fd9cc563
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 300fda82-a477-4984-b200-b8c259a9b548
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 4a953e40-65a9-42c0-ac3b-3a5ac4b1a9c3
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 5ed29977-cf1b-4225-b5fc-ea1b10612b43
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 8d8e176c-d57e-4d41-b85a-d42fb578c221
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 22ab96e6-386d-4272-a783-da399947aef6

		level Year
			ordinal: 0
			column: Year
			lineageTag: 741f4ea4-ffdd-4f12-9165-98063c33d12f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 30a31d21-83d1-4b63-9a2f-52f117b0fa30

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a3a2a42f-29d4-4c7c-8e22-23234c0f9495

		level Day
			ordinal: 3
			column: Day
			lineageTag: adafd83c-9d49-4fcb-b74e-40f6b5e51e09


	partition 'Calendar-4ef5fc22-24a9-49f4-bd0d-be8d7c306a8b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

