table Calendar
	lineageTag: dca8f0b6-15db-4949-8fc7-02ab94b554d7

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 3e43dd34-a21c-4933-8ece-7f3dccaa0d62

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d59e6c36-0493-4b5e-a42a-764bc40c7ac6

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: c42c62a5-66f9-4c51-b0cd-60d8bfbc6e7a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c52f3cda-81b6-4876-9fac-aa26741f4ea8
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 87d6fe00-d213-4428-9b23-c415a0c25a97
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 89f6e767-6ae7-4c05-a4a2-de1de37bf99e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d498081e-5843-4e80-8ee6-571309bfbb7e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 3b852f24-44e8-4567-80da-c00a1b5f817e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e82705d9-80e6-4b37-ab0a-d59c7872a35c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7be00156-89d5-4bbd-8475-d09abe0cdf19
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d2e9287b-ebf2-4439-9327-c0132ba22db9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4fff0f63-ffb3-4879-a6e3-9782a3e2a791

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1ece9c1d-ffa8-4e67-9f3b-332947c3c7f5

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 417ca85e-a8d5-464f-b363-68a1d3e07813

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7ffe004b-9279-4c7c-b69b-7294f56a8e44

		level Day
			ordinal: 3
			column: Day
			lineageTag: 19d683bd-5e63-4457-a970-0a2170c5ca5f


	partition 'Calendar-f35a3d0c-5a21-48e5-957d-3e13bc31d543' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

