table Calendar
	lineageTag: 0e5c46a6-3c9d-42be-b6ef-6c5b5fe705ce

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d2a9795f-6f72-4b84-8c75-769845c7653c

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 76ea8870-0930-47d4-bdd3-1c9d9ba7c4a1

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 8c007a05-550a-4f63-bc96-68c12915e036

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 86c30e7b-d075-45a7-a4ac-1361b70167ce
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 21225888-56a1-4af4-aad0-94e4ffe9595d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c2d06481-b608-4b09-b188-7f842935e105
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e6615978-c811-483b-87c3-178c4c5fe7e1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e889d82e-fc92-47d8-aa3e-fb3883afd3ef
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d94977d2-a83a-4958-9772-2f733ea63fe1
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ea7e13a3-7827-44a7-84d3-f6439a6eaf30
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: dfa59b5d-c3da-40e8-99dc-6148df01478d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1385e296-2b95-408d-9699-79985b7ef0c1

		level Year
			ordinal: 0
			column: Year
			lineageTag: c338815f-8ccd-4e7e-a81c-ce0dbde6e2ed

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 1642a25b-a2f5-4696-8075-86ba5c1841ec

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0cae4a40-0388-48a0-b006-74440aa8abc5

		level Day
			ordinal: 3
			column: Day
			lineageTag: 97fd5ee1-cc6d-40aa-ae05-a5300254480a


	partition 'Calendar-c12906b5-8b49-45d8-b378-0bc3ec356e67' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

