table Calendar
	lineageTag: e28e6823-2022-4087-96dc-2135d24e85d5

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b7cea9c6-0cb4-414d-a50a-96d25956b0c8

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 3b12373d-b73d-4f1d-918b-9b8cb20aa927

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 5945ed11-b7ae-4cac-8886-aa230be243c9

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 16b17b63-df94-4c34-9111-b48c13d02117
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 711394fd-1f52-4e8c-8cd3-a1692df0079b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 91e386db-6d0b-44e5-bbd4-eab827729893
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7d36e0c0-841e-49aa-8547-2ad3dc54b365
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 161266f2-963b-422b-a86f-7399a1deef97
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bbe210a0-cc0e-4298-9220-f9a0d768c108
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7bfd7929-4e06-4a63-aeba-6a1a9ea29b01
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f04750a5-8c40-4ead-b513-e8f802155ce8
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: fa6b7628-bfd2-4d8e-9b55-b42d6b8bb48f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 54c061ff-d93a-4d28-8ffa-e484db2ec05d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: fc25acf7-dfcf-42c0-b5d8-8c77fe150720

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0a030a6a-c7d7-42f3-ac5e-599ac072fe25

		level Day
			ordinal: 3
			column: Day
			lineageTag: 070a5a23-8da4-432b-b55c-d8fd3bcfed25


	partition 'Calendar-ceec6e10-f289-4f4a-8425-f3580b776a16' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

