table Calendar
	lineageTag: 2fba4a74-01ad-412d-a7fe-7a3f153d3e72

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c39cf7f8-4d17-4e47-810d-731d591f0541

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 2d6a7e7d-9840-41d0-b6ef-6607eb6879c2

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 04eb6f44-76a2-41e2-a863-2e52e870aa7d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a5686f99-7d24-4ab4-bbce-8d2d22e32a26
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ef87a506-36ff-4535-99a7-8c3f45aa2b93
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 59e7a72b-8128-4239-aa79-55419fb7e4e0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: fa9410ec-757c-464a-b142-4b4460ff61d6
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b5af0bd4-70dd-47a0-8af6-43374e4011ce
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 284513a4-7925-4f6d-94d3-5cbb5da0b016
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 1970928d-b426-4f99-ba99-47ad3aeb5f10
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 6a464dc1-6a37-40ff-bc67-8532168b93e6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c2fd5d4b-7a80-4f1f-952c-a841fff8fcac

		level Year
			ordinal: 0
			column: Year
			lineageTag: e70f931a-1000-4842-8a85-56bdb31b8068

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 6ad04332-cef9-4f23-8258-0a8e5e52596f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3e612a8b-70ea-46a3-862f-dadc4d8cac9e

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6b979c98-38c2-4d72-8e0b-63e160ddf9a7


	partition 'Calendar-54ce9a95-184c-4b23-9c42-5bfc4e4eed1b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

