table Calendar
	lineageTag: 9921c7a3-4417-4419-a820-79519e307162

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6b09366e-0251-4d70-9346-b70ebc8a4508

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c5a39da9-d160-4313-8d63-dd5004c3efee

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 4b115835-de27-4cc3-a635-165f0bc7428c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2c51f2e7-7be1-4140-8ec2-ddc1eb5c2bed
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0b52fe45-aea0-45c1-b905-84de766c8dfd
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 9fc44c06-3276-4b8b-a070-63227c8ccc9a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: dcffd800-ee71-4301-934e-d39092b54cb1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 009e482a-04df-49fa-b3cd-24347eff4d5e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 171bf9c4-b9f5-4677-8e68-a24612a1acd9
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 3af68c29-6af0-4627-b9e5-d30b8f53b5f0
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 6c081cd0-443e-4fc6-bb33-a6894bee556f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 04e9948b-1c3c-44fa-b028-ce98735ec12d

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1f5944bc-96af-4a9b-8c8e-ca95bf670b74

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 96c103b3-5047-4a05-9e54-8dd6c6a90ca0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 408f0b1b-764c-42db-9a45-7e29885e8301

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6f4e9af2-47cb-45be-a99c-2d226fb43e1d


	partition 'Calendar-a72353ae-2134-4623-9684-7609b1008a13' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

