table Calendar
	lineageTag: 6d5ec362-549c-4d21-a06d-ad72881c949e

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9e414434-817e-4e4c-993a-65eb33fe3d4e

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c2fb62f9-1931-4fed-a5c1-8b92ce553238

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 943ccc70-075c-4f76-ba91-49b998e6a6a1

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 698c7c48-167c-4140-95b7-77728ead14f2
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b6bf3485-78e4-424a-9ef4-68a25a5f0415
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b82ecf8a-de81-4a1b-a59a-e9fc322b9eec
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a58b41fe-392e-4118-843e-2e034ffa3e66
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a49af5c7-4659-4201-b48c-341108453c64
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 9da120f0-acd3-4e54-8e35-4aa570d33fb6
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e1828bd6-231f-4ab8-a29d-4ea301cb3fa9
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 3a563624-3335-4ee2-8424-2b746aada06d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: fb4a654a-c0a4-4fc1-9d57-f965749c3750

		level Year
			ordinal: 0
			column: Year
			lineageTag: 88489736-d390-44ea-b973-49e2a6d856d9

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 413bdacc-1e2e-45de-876e-259ee689cebc

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1b7923b7-080d-44a1-9688-5a5a557599a2

		level Day
			ordinal: 3
			column: Day
			lineageTag: f8a021d2-a994-42f0-bedc-852d1f6f5331


	partition 'Calendar-97234aab-b718-4c57-bcfd-81acdbbd860a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

