table Calendar
	lineageTag: 7e98effe-b664-4815-8034-79c525ff1252

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6d8b1acd-f953-42cb-a531-16791d873cfa

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 3a89fe61-0ed6-4009-aad2-f88bf4345fce

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: c3c85688-a730-4670-b297-b5a6d0647cae

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: af920928-7cc5-46af-a82d-43161be63d39
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: bc19eacd-5620-47b4-92f0-7b8e23e319e5
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5692e7f1-be14-49c8-860d-cb720d310020
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: fe486960-db00-457f-9467-ff4133174fc5
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 3c46dbf8-a33f-411d-ab74-de3788dffe2e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 53b54845-0af8-4400-9dcd-0103b06d6716
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d92668ce-f137-4e4d-8b34-3977e9016b33
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a91b8875-9701-4825-b981-c8fe77261af6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: dd6a528f-18f7-409f-b260-4734bebb2ec3

		level Year
			ordinal: 0
			column: Year
			lineageTag: e76e5999-0880-4af8-aa6c-b3497648e924

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 227734ce-9dd2-4e6e-b31e-3e1dabb1261b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4c11c66f-e0bc-48f9-b60d-03f071cb6738

		level Day
			ordinal: 3
			column: Day
			lineageTag: dfc65ef8-0d4e-4f9e-9354-d090b49f8df6


	partition 'Calendar-ec6365f0-58b1-4d4d-814e-46327af40d71' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

