table Calendar
	lineageTag: c3bc985a-8fa5-4483-b0aa-4b130af3b4da

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: bdf2db38-5053-4c08-b566-6900a2376836

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7273c5e2-ef5e-49a9-a4a1-eb8c65d213f2

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 533a07b0-4240-41d3-aa07-69a9322daf54

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 7b5d5195-3740-452d-95e3-9c77351b7f48
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2c02eb57-3e57-4147-b7db-e049def868b6
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4e0cb077-acf2-4c5a-92cb-253ed8bba7fc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4f1c6736-5a02-46a4-8c06-a5e7e3cb29c3
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1682440f-454e-42fa-af98-5f448be4a055
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0f50a765-a584-4e9b-84c4-2d3e7bdd3250
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b6e782f6-9d31-410a-9ed2-618c1b5c3814
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 276abb58-bcb0-47a0-ba43-5fc504abcc97
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 992a48f2-e9e6-4126-af2d-b0cb13ffebad

		level Year
			ordinal: 0
			column: Year
			lineageTag: 627222fb-eaa9-4010-94ca-c73a49cbe07d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ad55d6f4-c897-49bf-a059-f1987b32d639

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a446f1f6-ff2d-4fae-b648-095a49324710

		level Day
			ordinal: 3
			column: Day
			lineageTag: f7577653-4c81-4b02-9024-cae1903b51aa


	partition 'Calendar-6e852722-ae2c-44ea-9976-a75bd0492451' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

