table Calendar
	lineageTag: 2757f92f-2483-4f30-aace-329630945f65

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c0e28ba3-f945-4e96-a34b-7c8ba6131897

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 3417e826-3988-4f95-803f-83b9fc3e026b

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 34ca458c-8e9e-4342-a5f7-18a83aa43e85

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: dbac2a08-aa8a-409d-be06-78641be4e94d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0456c8e4-b825-4ec2-95db-185d639e9657
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 51cec954-fd58-42c6-930f-ce0da5f16fe5
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 172b00d0-015f-4d7e-bea0-f5fa527d9a42
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 20df04a7-fee5-407a-a64e-2686e25afa73
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a62f3fd6-0938-4ce1-bf59-d62fec6e5650
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 39af6850-740c-4756-9d05-4cf1599b84f1
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 934e3345-114e-40da-a104-5db755d5f8c0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: be1a2a6a-3932-41c7-a200-61974c7466e2

		level Year
			ordinal: 0
			column: Year
			lineageTag: ed6ba631-62ab-4994-be67-109869398420

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e0fd1e75-74cd-4e0b-871f-9f0711e092b4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 640f4f0a-62f6-4ac1-a64b-802b607ab30f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 416be261-3206-4fbc-9c0d-1524bcdebbb1


	partition 'Calendar-ccc18e92-ec75-4bd6-99c7-4099b8af8470' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

