table Orders
	lineageTag: 8b847d19-4e85-48d6-9927-31f5aa25bc55

	measure Margin = SUM('Orders'[Profit])/SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: dfadc56a-d5e9-42f2-a0db-e90a07217493

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 1cde1255-63bf-40ff-a40a-decfebd69c6b

	column 'Row ID'
		dataType: int64
		lineageTag: 2db61294-ba2b-4543-9653-6f28367ccd63
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 0b9a7f38-fbf5-40f1-ae0c-834a55f52193
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: a2e1b8d9-0cca-4753-b654-72d9cb792b16
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: fcab5eb1-9301-49ec-bbc3-234128d46a09
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: e7c259dd-97bf-46f5-9ca2-d76baf7a4ba2
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: dffaeb0f-3b4b-4aa7-9231-f582ebdd0af0
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 804c8883-f2e2-4e7d-aab8-b297a9525f1f
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 25246da2-4b05-4d83-8be5-ded252291a9d
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: bb2b1d81-b3a7-4c4e-b1b2-9a7cfc44bebe
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: c377f71a-5c97-4d99-8f55-49a0f8787716
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: e52dc2a1-8333-4b7a-9dc8-f006316b4918
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 8767455b-e878-41b0-b30d-8da4446427c9
		summarizeBy: none
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: a138f5ee-835d-4f43-a3cd-4d8ffa6ac2ee
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: cbff3b0d-ae0a-4587-905c-a6157108ed13
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 0b2144fa-7f3b-42d1-a92e-0e5c1daea2d1
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 203a4e4b-f83e-4b19-b500-a6931db1d454
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 7a17bc38-d464-46b3-8a3b-2ad975f78147
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 43db16b7-048d-4287-8541-ea53ad3048b6
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: f196a368-ed28-4b02-bb36-86f761cde774
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: fe602f6d-c985-484d-9f3a-0ac63b4d22d6
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 8cac10a3-3e4e-449c-bf5f-b13559c6754c
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 6514f73b-dfe2-4a07-814b-f1b5ccd46a31
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: double
		formatString: #,0.00
		lineageTag: 919c4c2e-1229-468c-8f32-0b7476c89056
		summarizeBy: sum
		sourceColumn: 'Shipping Cost'

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: 464791ca-8224-462c-ba5e-e03c9de40fe9
		summarizeBy: none
		sourceColumn: 'Order Priority'

		annotation SummarizationSetBy = Automatic

	column '[Discount (bin)]'
		dataType: int64
		lineageTag: ad5e132f-dfe4-41f4-84ab-8f54e73148ec
		summarizeBy: none
		sourceColumn: '[Discount (bin)]'

		annotation SummarizationSetBy = Automatic

	column 'Action (Discount (bin))'
		dataType: string
		lineageTag: f9368d0b-96b7-4237-9fc7-2d6d305eedd3
		summarizeBy: none
		sourceColumn: 'Action (Discount (bin))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Segment)'
		dataType: string
		lineageTag: 8a29bc7c-1866-44fd-a8f6-1f650b64faa6
		summarizeBy: none
		sourceColumn: 'Action (Segment)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (State)'
		dataType: string
		lineageTag: a6794717-a415-49ca-bb56-5659a7e1528b
		summarizeBy: none
		sourceColumn: 'Action (State)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Order Date))'
		dataType: string
		lineageTag: 84570666-8a20-41b1-a829-28e043336957
		summarizeBy: none
		sourceColumn: 'Action (YEAR(Order Date))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category (group)'
		dataType: double
		lineageTag: 798e724c-e045-46bd-9f41-1e9b02dba4a1
		summarizeBy: none
		sourceColumn: 'Sub-Category (group)'
		displayFolder: Bins

		annotation SummarizationSetBy = Automatic

	partition 'Orders-c4e36f8d-3208-425d-81fd-11a2706ac135' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/bs/Mac Drive/MSBA/INFO584_01SP21/Datasets/Global Superstore.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\\Users\bs\Mac Drive\MSBA\INFO584_01SP21\Datasets\Global Superstore.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "City", "State", "Country", "Postal Code", "Market", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit", "Shipping Cost", "Order Priority"}, {}),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Country", type text},
				        {"Postal Code", type text},
				        {"Market", type text},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number},
				        {"Shipping Cost", type number},
				        {"Order Priority", type text}
				    }),
				    #"Added [Discount (bin)]" = Table.AddColumn(#"Changed Types", "[Discount (bin)]", each [Discount], Int64.Type),
				    #"Added Action (Discount (bin))" = Table.AddColumn(#"Added [Discount (bin)]", "Action (Discount (bin))", each Text.From([#"[Discount (bin)]"]), type text),
				    #"Added Action (Segment)" = Table.AddColumn(#"Added Action (Discount (bin))", "Action (Segment)", each Text.From([#"Segment"]), type text),
				    #"Added Action (State)" = Table.AddColumn(#"Added Action (Segment)", "Action (State)", each Text.From([#"State"]), type text),
				    #"Added Action (YEAR(Order Date))" = Table.AddColumn(#"Added Action (State)", "Action (YEAR(Order Date))", each Text.From(Date.Year([#"Order Date"])), type text),
				    #"Added Sub-Category (group)" = Table.AddColumn(#"Added Action (YEAR(Order Date))", "Sub-Category (group)", each 0, type number),
				    Result = #"Added Sub-Category (group)"
				in
				    Result

	annotation PBI_ResultType = Table

