table Orders
	lineageTag: 290acfed-283f-441e-afa6-a4592af14ad9
	description: Contains 30 columns and 2 measures: Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, ... (30 columns total).

	measure Margin = SUM('Orders'[Profit])/SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([Profit])/SUM([Sales]) | DAX: SUM('Orders'[Profit])/SUM('Orders'[Sales])
		lineageTag: fe68ccf8-bc5c-49c2-9be3-e2cea7ec78e1

	measure '[Number of Records]' = 1
		displayFolder: Measures
		description: Migrated from Tableau: 1 | DAX: 1
		lineageTag: e70d8116-f93e-4abd-a507-02aebe7d6405

	column 'Row ID'
		dataType: int64
		lineageTag: 79bcb90b-5dfa-4c77-aca8-171135967b20
		summarizeBy: sum
		sourceColumn: 'Row ID'
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: c7507db0-31b8-4c03-945d-3b964a8b85d8
		summarizeBy: none
		sourceColumn: 'Order ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: f0b6bf89-42d6-4918-a366-febed5783408
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: bbbff075-66a4-47ab-b47b-ae4c4caeae84
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 768989b7-943b-4f4b-9d3c-04e32a3f8a87
		summarizeBy: none
		sourceColumn: 'Ship Mode'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 0bbea7f0-885a-4df6-98a5-e2312326e531
		summarizeBy: none
		sourceColumn: 'Customer ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 2c28b606-8982-4a64-9f0d-a616bb2b3b37
		summarizeBy: none
		sourceColumn: 'Customer Name'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 377dfd64-0e3e-439b-8038-227b333d5e42
		summarizeBy: none
		sourceColumn: Segment
		description: String column.

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 5e7dff45-a768-4b77-b005-11ff8aa08858
		summarizeBy: none
		sourceColumn: City
		dataCategory: City
		description: String column. categorized as City.

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 62e561b1-3cfd-4807-a55c-09cb667f8984
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 6078b3e6-7faa-4d14-ab41-f598e443309f
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country
		description: String column. categorized as Country.

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: b78b893f-2749-4a77-ae67-0a98c5392dfa
		summarizeBy: none
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode
		description: String column. categorized as PostalCode.

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 4a6df37d-82d3-4779-90d4-b44a47442659
		summarizeBy: none
		sourceColumn: Market
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 0978f90e-cbcc-44e1-aa4e-4ad1c42307af
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 900b3bee-403d-4667-8bfe-9085217b743d
		summarizeBy: none
		sourceColumn: 'Product ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 0b181e24-1abc-4400-aa62-64313cd15308
		summarizeBy: none
		sourceColumn: Category
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: f122f45b-ff51-47be-a8fd-936b41d7d2fb
		summarizeBy: none
		sourceColumn: 'Sub-Category'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 22373899-eb24-4341-b8d3-1057bca7dc5a
		summarizeBy: none
		sourceColumn: 'Product Name'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 74e9276a-75f6-451e-9ce5-8ada471b22c7
		summarizeBy: sum
		sourceColumn: Sales
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 9412afc0-1d9e-414e-a6c5-6bc6bb3fd762
		summarizeBy: sum
		sourceColumn: Quantity
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 7f88002c-a20e-47b6-b714-4e7ae928189e
		summarizeBy: sum
		sourceColumn: Discount
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 27c918ea-f9a0-4deb-be96-10128f25d06b
		summarizeBy: sum
		sourceColumn: Profit
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: double
		formatString: #,0.00
		lineageTag: 99425c9f-0676-4014-bb30-2205fef4a075
		summarizeBy: sum
		sourceColumn: 'Shipping Cost'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: 9562c9a8-92c7-4c8a-9d52-ebc3aabd874e
		summarizeBy: none
		sourceColumn: 'Order Priority'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column '[Discount (bin)]'
		dataType: int64
		lineageTag: 1e54ad2e-337f-45d2-a100-bcf869cb7484
		summarizeBy: none
		sourceColumn: '[Discount (bin)]'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column 'Action (Discount (bin))'
		dataType: string
		lineageTag: a30af76d-3d12-447f-9aeb-6a23dc947891
		summarizeBy: none
		sourceColumn: 'Action (Discount (bin))'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Segment)'
		dataType: string
		lineageTag: 6aa89cc2-604b-41f2-b774-bdcdbccae9cf
		summarizeBy: none
		sourceColumn: 'Action (Segment)'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (State)'
		dataType: string
		lineageTag: ebf1a60b-f26a-4ab9-bc7c-20f015e3039c
		summarizeBy: none
		sourceColumn: 'Action (State)'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Order Date))'
		dataType: string
		lineageTag: db81ba48-03c4-48de-a1c7-5ca8172c85e4
		summarizeBy: none
		sourceColumn: 'Action (YEAR(Order Date))'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category (group)'
		dataType: string
		lineageTag: 55649765-005e-4626-9627-ec0b934d267a
		summarizeBy: none
		sourceColumn: 'Sub-Category (group)'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Orders-84db55b7-52ae-4d36-a2ca-9f8b064ce633' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/bs/Mac Drive/MSBA/INFO584_01SP21/Datasets/Global Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\\Users\bs\Mac Drive\MSBA\INFO584_01SP21\Datasets\Global Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="Orders",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "City", "State", "Country", "Postal Code", "Market", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit", "Shipping Cost", "Order Priority"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Country", type text},
				        {"Postal Code", type text},
				        {"Market", type text},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number},
				        {"Shipping Cost", type number},
				        {"Order Priority", type text}
				    }),
				    #"Added [Discount (bin)]" = Table.AddColumn(#"Changed Types", "[Discount (bin)]", each [Discount], Int64.Type),
				    #"Added Action (Discount (bin))" = Table.AddColumn(#"Added [Discount (bin)]", "Action (Discount (bin))", each Text.From([#"[Discount (bin)]"]), type text),
				    #"Added Action (Segment)" = Table.AddColumn(#"Added Action (Discount (bin))", "Action (Segment)", each Text.From([#"Segment"]), type text),
				    #"Added Action (State)" = Table.AddColumn(#"Added Action (Segment)", "Action (State)", each Text.From([#"State"]), type text),
				    #"Added Action (YEAR(Order Date))" = Table.AddColumn(#"Added Action (State)", "Action (YEAR(Order Date))", each Text.From(Date.Year([#"Order Date"])), type text),
				    #"Added Sub-Category (group)" = Table.AddColumn(#"Added Action (YEAR(Order Date))", "Sub-Category (group)", each if [Sub-Category] = "Art" then "Miscellaneous_Office_Supplies" else if [Sub-Category] = "Binders" then "Miscellaneous_Office_Supplies" else if [Sub-Category] = "Envelopes" then "Miscellaneous_Office_Supplies" else if [Sub-Category] = "Fasteners" then "Miscellaneous_Office_Supplies" else if [Sub-Category] = "Labels" then "Miscellaneous_Office_Supplies" else if [Sub-Category] = "Paper" then "Miscellaneous_Office_Supplies" else if [Sub-Category] = "Supplies" then "Miscellaneous_Office_Supplies" else "Other", type text),
				    Result = #"Added Sub-Category (group)"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 30 columns and 2 measures: Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, ... (30 columns total).

