table Calendar
	lineageTag: 8b5f098b-0963-434d-9300-687f86e836bd

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8672fa51-e87f-48df-9dbc-0c15fcc011d5

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d5e63cdc-a6d1-4059-896a-cc84e8313481

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 6784cdd6-9479-4412-89f0-3d3745da0ca8

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bf1aefd2-36d2-4807-a371-4f3f45c8cf07
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 037152f8-57a6-4acd-ae2b-2b55a4c945e2
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: cc52a97a-a67c-441c-a115-1f2fe5fffce2
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 658d7631-afab-448a-a0fc-3bc1ca769228
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 55d849ba-bd67-40a4-a623-81d272be3a75
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 98b7078c-fba1-427d-9df3-2bdeef0bffeb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f75bba2c-ed6a-4a1b-b15a-922c52e37b0b
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: cdc2ace1-4e0d-41e0-8793-e9cc82c44f35
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: bf376733-b115-44d8-ab0c-b157b41b767b

		level Year
			ordinal: 0
			column: Year
			lineageTag: fde0d0b1-6564-486f-80e9-c85c30d57df0

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 6c2a737c-00df-4724-ace7-1d037205d65d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3f99ec1f-8374-4d6f-b55d-02d5255273e9

		level Day
			ordinal: 3
			column: Day
			lineageTag: a15cc6c7-1f4b-4c1c-8afe-4eeae98fc207


	partition 'Calendar-e482037a-53fc-490d-821a-e201cacd1bcc' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

