table Calendar
	lineageTag: 3297b01e-d364-48f0-b095-08fd07bc9f46

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c10be802-e202-4b69-bc36-5f094d3d3eff

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9ef03a55-0cca-426c-ba21-3374cf071c04

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: cc3976b4-98f5-435b-b923-50a4df96c1ca

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4547b064-798a-4cee-9685-b17bd3a23b80
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 6a967594-d71d-4f4d-bf64-dba6d5f8c580
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 68f43002-ad8e-434d-b332-3c2ac2c997f3
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 48033f09-9550-4168-91dd-f547a584f620
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a850ea34-d6da-471c-8301-4891b5ae8113
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: be5988c2-969b-481e-8ccc-324afe3fe7b6
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 56b3af05-c8ad-4d90-a525-2d324a030e82
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 3950b962-2444-4610-a1af-a7f821f02cf9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5532ad43-6757-4f45-acbb-7f92afc445e0

		level Year
			ordinal: 0
			column: Year
			lineageTag: 9fa10fd6-611c-483a-8f52-2cf0c9fa79a3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f93e30d7-6eb4-42c6-8c2c-fb7bd19e96d7

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: fc872b52-9939-4bcd-b29e-9126e7332568

		level Day
			ordinal: 3
			column: Day
			lineageTag: ecc8ebd8-cc02-4135-b5a6-14d85b0a835b


	partition 'Calendar-335cc7c7-5e08-4601-becb-749b6fbe4bef' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

