table Calendar
	lineageTag: 86788969-1584-4ec7-9c4f-67c2725766fd

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c6360195-5ee7-433e-b33d-cb45159c82c5

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 32487cf2-3623-49b3-86be-2fc6151e29f9

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: a2d0eaa1-5eae-452d-8a28-e6944843fc96

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 32158c40-2526-4841-a590-c9e31b1db24e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1940cbf4-f5e9-414f-96dc-676e3c19cfed
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 6306ad6c-ae79-4712-b8e5-1c0346d77989
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 3b147be9-727b-4cf6-9f73-9b46eea83a0b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b402cb06-d47b-45a2-95be-f45d3a3b18d0
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 82f71ba7-2971-429b-bbc9-206431ce4628
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: fe64030d-fdbf-4de9-9ef5-13b172f0c2a6
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a21cafa4-0334-4d60-bcc9-4832c258d895
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ac6090db-e0bc-47bd-be3b-c1bd4e7eba03

		level Year
			ordinal: 0
			column: Year
			lineageTag: 3f45161f-035e-4307-b9f9-bf89a5a7f9fe

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 1cf6917d-e1ab-47c1-bd49-c17b0ae7e3b3

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 5f4a05f7-0000-48e4-9c0a-e5c45acb56cc

		level Day
			ordinal: 3
			column: Day
			lineageTag: f2989a01-26b8-47a5-ad4b-9955c0d0b0b9


	partition 'Calendar-21d98f74-38e2-4a98-8980-845e1601cbea' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

