table Employees
	lineageTag: bc6a8d9a-3443-43c1-a70b-87bf93618fe3

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a92249d5-2dc3-47d8-b1d0-634d5ece1f34

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: 2fa92bed-53a3-495e-ad58-50339ed7cb3e

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2fb23981-a9fd-443b-b829-d4f9c25680fa

	column EmployeeID
		dataType: int64
		lineageTag: d9f36ad9-b9e1-49ce-8d68-ead47e62221c
		summarizeBy: sum
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 18acb342-48d5-4057-ae61-0920e8054ee0
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 81346048-3874-40a1-bc10-64fb3993a88f
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 027da9ea-75b9-47f9-9cd7-f2a293fbaec7
		summarizeBy: none
		sourceColumn: HireDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: d6c44296-b4ff-43b4-9c49-9ad53a67913a
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: b1d31796-8028-44d1-b3f3-8717071f65a8
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: 891065b3-66cc-4a2e-a603-fd75036ab193
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: fb04b62e-5d54-40ab-86c5-469a6c463d5c
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: a6a68b88-fc55-4eaf-ae64-c707249a4827
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: fbe07acf-01af-4364-99ee-7e2647efa086
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: 60977db9-b75d-4c57-b663-d706271966d5
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category' = IF('Employees'[YearsOfService] < 2, "New", IF('Employees'[YearsOfService] < 5, "Mid", "Senior"))
		dataType: string
		lineageTag: 48a911f7-472f-43f7-b26d-af04bca8b9ce
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Employees-448a6d95-9ce9-4891-89fd-9c074188e659' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("localhost", "HRDatabase"),
				    #"Employees Table" = Source{[Schema="dbo", Item="Employees"]}[Data],
				    Result = #"Employees Table"
				in
				    Result

	annotation PBI_ResultType = Table

