table Employees
	lineageTag: 38d1d493-47df-4257-9588-7a1473089b22

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b5b041b8-2814-41d9-a271-94c166b64b48

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: 602fce7f-9c69-4669-a79d-420b0fae2d14

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 732ced53-f216-4f38-86e8-747e48a40b41

	column EmployeeID
		dataType: int64
		lineageTag: becd069a-a7bf-45ee-9ab7-1b0260b3c5ad
		summarizeBy: sum
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: ee66e68d-3c03-4f58-94e4-aebbcc1cd5d8
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: b17c20e2-64b3-4d3f-8f97-85aaef78b663
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: a6f1098b-e8e9-4302-b77c-4aac6c0c3a73
		summarizeBy: none
		sourceColumn: HireDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 0817fa15-ac8a-47df-974c-4e69cb8b9e27
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 4f6c2228-71ee-494c-99bf-e06c45aa2483
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: 661f5c12-40e8-470d-a3e3-67e49a4373f1
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 1b773d6d-5141-40b7-bb4e-6e967786f195
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: 4500a02d-bcab-4dc9-b6b7-1e20b7d7d4a3
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: 0feabc3c-cc4a-4bfd-9956-8be4d8177972
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: 6e5f1da2-7f4a-4ba4-90b5-0e9c0b73418c
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category' = IF('Employees'[YearsOfService] < 2, "New", IF('Employees'[YearsOfService] < 5, "Mid", "Senior"))
		dataType: string
		lineageTag: aa60ae0d-653b-4deb-a866-9ac3d9368ac6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Employees-c3c26a59-1212-4106-91d7-ede864408076' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("localhost", "HRDatabase"),
				    #"Employees Table" = Source{[Schema="dbo", Item="Employees"]}[Data],
				    Result = #"Employees Table"
				in
				    Result

	annotation PBI_ResultType = Table

