table Employees
	lineageTag: a3b3a063-1913-4d80-9da2-98eaa3218027

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d52d7139-b6cf-4bf1-aa33-006be1516166

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: 9cdee969-54a1-4c8e-b0eb-4dd880cb3445

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0333f288-82b7-4418-bf93-6de19f691968

	column EmployeeID
		dataType: int64
		lineageTag: d4db7ebe-0205-41b1-a1cb-ca3b0fb38972
		summarizeBy: sum
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 34a71969-bcbc-457d-bb2b-30d38106e58f
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: b674f4eb-07b7-46e8-bd27-c3907f85156e
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 9d984f91-471d-4e21-a6a3-953e17ae013a
		summarizeBy: none
		sourceColumn: HireDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: ea0bcdf0-7759-4466-926b-478202f510b0
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 4ef4f650-e8b2-425a-a763-1bb36e6bf0e0
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: 75998fa4-35db-4a8a-8cc7-b3c3824510e0
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: e8fb4108-0a66-46f8-9ec5-36fdb6502b24
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: a9ebfdbe-3729-4200-85e6-e1f9928ad786
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: 5f57ab0f-a210-4a89-93b9-b4c4c53533bb
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: 0765c2e5-12ba-4ae8-8d23-6b22bd48c846
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category'
		dataType: string
		lineageTag: a614908f-0763-4294-9619-f323ac12f776
		summarizeBy: none
		sourceColumn: 'Tenure Category'

		annotation SummarizationSetBy = Automatic

	partition 'Employees-6376e489-8264-459c-9fbc-9227bf26d56f' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("localhost", "HRDatabase"),
				    #"Employees Table" = Source{[Schema="dbo", Item="Employees"]}[Data],
				    #"Added Tenure Category" = Table.AddColumn(#"Employees Table", "Tenure Category", each if [YearsOfService] < 2 then "New" else if [YearsOfService] < 5 then "Mid" else "Senior", type text),
				    Result = #"Added Tenure Category"
				in
				    Result

	annotation PBI_ResultType = Table

