table 'Alert Threshold'
	lineageTag: bdfed44d-6511-4570-8f2b-4d8f46e1ba84

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 0a3481b9-2313-4107-9411-38c6a19de7eb

	column Value
		dataType: double
		lineageTag: 68329ad3-5229-408d-856c-c7d0f0fb1361
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-bbc85f28-8ec7-49aa-8728-6ea49d3a2872' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

