table Calendar
	lineageTag: 666deed8-5fab-4f68-8659-9b919138302f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d7913ac6-2891-4f17-a5fb-f041798d34be
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d1653b4f-6ca0-4569-8704-5d15d3aa0e30
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 13e1efe7-eef5-4c52-a601-575d77c643cd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 277083c3-54cd-4f97-8703-4d5e4cb30b37
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 7bd2a0bf-e769-4ede-81d7-3b32f0e3d4fd
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: eddba56f-abcd-4c10-af12-96736a3de484
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 5b0685e4-94b8-4095-a6ad-2f4e70450b28
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 07b26014-08c3-47e8-827e-e8094ca3b39f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 86d216e8-8bb8-4378-a9fb-cd791197aba5

		level Year
			ordinal: 0
			column: Year
			lineageTag: a5c81d9e-e36b-4313-849f-26539a695de6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 7d0f3bed-854a-4bcb-b069-f86c15858573

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: b6198dd2-fb84-48b7-8e88-c2be9d07b596

		level Day
			ordinal: 3
			column: Day
			lineageTag: c7f5686b-012b-4c22-b9ae-b975c90f5f3d


	partition 'Calendar-0be03e17-5338-48d4-b578-0414c66588d9' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

