table Calendar
	lineageTag: cb8bb585-662c-47ca-a139-a6ba59066aa4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0c7f6bfa-d303-4aab-9acc-fff620ec4637
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b6ad5a68-94d4-4855-9110-06af11642b85
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 07f1837d-311b-46db-a5c6-0074064463d4
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: fee4ef0d-901b-4282-bcb4-757ef0b04998
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c7d1dcc0-5a8b-43a8-a1db-cdc3fbb89312
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 55b3b0ea-51d9-4136-b92f-24e953593720
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: cbad2cb4-56a5-46e3-8918-dc896d39a543
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 4ce99811-46a2-475c-8720-77f46ecccca0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9aeb771b-7b4b-46eb-90ab-82de015e2291

		level Year
			ordinal: 0
			column: Year
			lineageTag: ac1d9ebb-95e5-4fbd-874f-c0fb04e8192c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 442927b4-e772-4c96-944f-a0d1813492c5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 67fa1231-e076-4336-88fc-df30a9794efe

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1e8a02e0-76e5-40cb-b306-73539ea83519


	partition 'Calendar-abc4e312-e7f7-4b08-8135-38119b1097b0' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

