table Orders
	lineageTag: e6fa8f47-7038-4f2b-97b5-38499abf5ac0

	measure 'Gross Revenue' = SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 558b8bd3-b0ef-4a64-a6f8-24d7fa868745

	measure 'Net Revenue' = SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", 'Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 4add3039-75e0-47b9-a012-aa2adf0088b6

	measure 'Total Discount' = SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price] * 'Orders'[discount])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b7e4dc6e-ee1e-4371-a9ef-e8ddece25afc

	measure Profit = SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", ('Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount])) - 'Orders'[shipping_cost], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0790f635-304c-4529-a26c-31084f0371f5

	measure 'Profit Margin %' = [Profit] / [Net Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 02621427-2129-405c-93f4-875a15546478

	measure 'Revenue per Customer' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[customer_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6e075f4d-810d-41b8-86bd-c1e8afe4bf28

	measure 'Regional Channel Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[region], 'Orders'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9dabb9ef-eb5f-4b80-9dcb-213329e4d8a4

	measure 'Revenue Excl Category' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), REMOVEFILTERS('Orders'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 886d1b8a-c65c-4ba6-85f2-29d38897ef0e

	measure 'Moving Avg Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALL('Orders'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2d5681e5-05ab-4685-be90-59570dfbc0e4

	measure 'Running Total Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 84dfc661-cd6d-4aeb-a873-d4e3f2bf9e69

	measure 'Revenue Rank' = RANKX(ALL('Orders'), SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]))
		displayFolder: Measures
		lineageTag: 584c4329-df1d-4f0c-8e52-2b377d03e43a

	measure 'YTD Revenue' = CALCULATE(SUMX('Orders', IF(YEAR('Orders'[order_date]) = YEAR(TODAY()), 'Orders'[quantity] * 'Orders'[unit_price], 0)), ALL('Orders'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7c5b546f-1837-4cd0-8970-0759478a52ba

	measure 'Customer Tier' = IF([Revenue per Customer] > 10000, "Platinum", IF([Revenue per Customer] > 5000, "Gold", IF([Revenue per Customer] > 1000, "Silver", "Bronze")))
		displayFolder: Dimensions
		lineageTag: 0263b9bd-4fd6-4528-97c1-bff643468f12

	measure 'Unique Customers' = DISTINCTCOUNT('Orders'[customer_id])
		displayFolder: Measures
		lineageTag: 1b2a63bf-aae7-4211-951a-4c104b2744a4

	measure 'AOV Completed' = AVERAGEX('Orders', IF('Orders'[order_status] = "Completed", 'Orders'[quantity] * 'Orders'[unit_price], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ffa6afda-273e-48af-a671-7b65d1c830d0

	measure 'Revenue StdDev' = STDEVX.S('Orders', 'Orders'[quantity] * 'Orders'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c3f439e0-9ca6-4c2a-a0cf-53e5f94831e0

	measure 'Is My Account' = 'Customers'[customer_email] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 5a0b32c9-01c3-45f1-98d0-9a31a2b8ca1a

	measure 'Date Range Start' = DATE(2024, 1, 1)
		lineageTag: 5c8c106d-db95-471f-a8f4-dbb186cc8517

	column order_id
		dataType: int64
		lineageTag: 8ab1ec0c-fb0b-462d-b742-1eaa4412784c
		summarizeBy: sum
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7a149a62-215e-4920-997e-37876ea4a0c7
		summarizeBy: none
		sourceColumn: order_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		lineageTag: e19aa913-1e8a-4e33-92b4-5f1d34058fc5
		summarizeBy: sum
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		lineageTag: d29a3442-3ba1-435a-858b-225c3f462f4f
		summarizeBy: sum
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 68f9dacb-53d7-4a2a-994a-70453a048d8f
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: b753f33a-4cd3-493a-bff1-1b1100f0e2a4
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		formatString: #,0.00
		lineageTag: 063999a7-6d44-4aef-9a2b-04d2327eba5c
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		lineageTag: 33879c51-63c3-44b1-b3d2-35e980380d13
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column discount
		dataType: double
		formatString: #,0.00
		lineageTag: fd6ef4e2-1391-4555-aa79-178347a501f8
		summarizeBy: sum
		sourceColumn: discount

		annotation SummarizationSetBy = Automatic

	column shipping_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 600cf29d-bc08-4b8a-b1b1-71fe09daa627
		summarizeBy: sum
		sourceColumn: shipping_cost

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: 46044fe8-3a7e-4e1a-a547-63e50e6f6be2
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column sales_rep
		dataType: string
		lineageTag: c82aced7-55cd-4370-b7c7-620bff194d69
		summarizeBy: none
		sourceColumn: sales_rep

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: 73c0c627-1314-4efd-9b5a-82cc8eb791a5
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column 'Customer Tenure Days' = DATEDIFF(LOOKUPVALUE(Customers[first_purchase_date], Customers[customer_id], Orders[customer_id]), TODAY(), DAY)
		dataType: int64
		lineageTag: dab8a400-1397-46c7-8e3c-c69518b6fb09
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Safe Discount Rate'
		dataType: double
		formatString: #,0.00
		lineageTag: b806cdfc-d3cf-4832-9be6-4dcca90868ad
		summarizeBy: none
		sourceColumn: 'Safe Discount Rate'

		annotation SummarizationSetBy = Automatic

	column 'Full Location' = UPPER(LOOKUPVALUE(Customers[city], Customers[customer_id], Orders[customer_id])) & ", " & LOOKUPVALUE(Customers[state], Customers[customer_id], Orders[customer_id]) & " (" & LOOKUPVALUE(Customers[country], Customers[customer_id], Orders[customer_id]) & ")"
		dataType: string
		lineageTag: e94dc72f-c887-4c33-8aa7-30cbb01f6253
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment Label' = "Segment: " & LOOKUPVALUE(Customers[segment], Customers[customer_id], Orders[customer_id])
		dataType: string
		lineageTag: 1dd21e84-2b51-4971-909f-54e09054c39d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Discount Category'
		dataType: string
		lineageTag: c921bf34-9d9b-4946-aa80-fbe2b8d02258
		summarizeBy: none
		sourceColumn: 'Discount Category'

		annotation SummarizationSetBy = Automatic

	partition 'Orders-5098fa22-c990-4d13-b8d6-b20357baf19b' = m
		mode: import
		source =
				let
				    // Source Snowflake: acme.snowflakecomputing.com
				    Source = try
				
				        Snowflake.Databases("acme.snowflakecomputing.com", "COMPUTE_WH")
				
				    otherwise
				
				        #table({"order_id", "order_date", "customer_id", "product_id", "region", "channel", "quantity", "unit_price", "discount", "shipping_cost", "order_status", "sales_rep", "territory"}, {}),
				    #"ANALYTICS" = Source{[Name="ANALYTICS"]}[Data],
				    #"PUBLIC" = #"ANALYTICS"{[Name="PUBLIC"]}[Data],
				    #"Orders Table" = #"PUBLIC"{[Name="Orders"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Orders Table", {{"order_id", "Order ID"}, {"order_date", "Order Date"}, {"customer_id", "Customer ID"}, {"product_id", "Product ID"}, {"region", "Region"}, {"channel", "Channel"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"discount", "Discount"}, {"shipping_cost", "Shipping Cost"}, {"order_status", "Order Status"}, {"sales_rep", "Sales Rep"}, {"territory", "Territory"}}),
				    #"Added Safe Discount Rate" = Table.AddColumn(#"Renamed Columns", "Safe Discount Rate", each if ([discount] = null) then 0 else if ([discount] = null) then 0 else [discount], type number),
				    #"Added Discount Category" = Table.AddColumn(#"Added Safe Discount Rate", "Discount Category", each if ([discount] = null) then "No Discount" else if [discount] = 0 then "No Discount" else if [discount] < 0.1 then "Low (<10%)" else if [discount] < 0.25 then "Medium (10-25%)" else "High (>25%)", type text),
				    Result = #"Added Discount Category"
				in
				    Result

	annotation PBI_ResultType = Table

