table 'Target Margin'
	lineageTag: f37cf689-03a1-4a87-b8ab-7fda6a657d13

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 7c63ce42-0870-4440-bea3-cdb83c2e99b1

	column Value
		dataType: double
		lineageTag: f52d2033-22a8-4162-bcce-bea6290cf920
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-8ff01804-1a9b-4ea1-91a3-922d69a989ea' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

