table 'Target Margin'
	lineageTag: 24f56872-d41f-46ca-b7fb-9ce0ea5b8a66

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: cc04b14a-a86f-4eac-919f-df69568f63be

	column Value
		dataType: double
		lineageTag: dbea97a2-2870-40e6-bcf2-9e3ec465c46d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-af682e6c-2e38-461b-8e72-698d7eed983e' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

