table 'Top N'
	lineageTag: cc9aff6c-d64a-48c8-8018-8392f03cbc6f

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: f03c21d9-da06-403b-af5a-b565d0a89197

	column Value
		dataType: int64
		lineageTag: a7485195-7ac1-413f-b93e-9819fb0c36dd
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-a30a4cbe-76f9-4c48-b373-6930f2cc2a1a' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

