table Rebounds
	lineageTag: 7872477c-8771-42c2-a039-3a452ab5e361

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 07f8e8eb-1b0c-4ebb-ad06-81f3fbd60dec

	column Value
		dataType: double
		lineageTag: 87f94171-4cf4-4d1d-9999-896d101c1ec2
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-b3bcf1b2-387c-4f40-ac07-90d76105a511' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

