table Calendar
	lineageTag: 5c4a7bee-fb7d-486b-a985-4fa76a732911

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 25021b42-ae58-4d36-a006-93ff6f2e0666

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 4e01d315-b341-4065-a77f-91f29c29440d

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: c44214ca-34a8-4573-976f-7362a1a187b9

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 09df28c3-afe7-45b4-ae5d-50c76f22eb01
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 10cb9da1-4aa7-4be7-a006-ad1bedce395a
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ab8fe48d-7c9f-4f65-9373-f830b7588258
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 1a4f41aa-64ca-43ea-82da-488327509bf4
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b3277b00-7d09-4cfd-8e50-4874bf6a706d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 4d24656e-a7ac-41da-9ba8-b861b8ddce78
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 63c255e8-5105-434d-a963-d2bcf12751dc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 15cf9a5c-1ce6-4c26-95fc-97b9063d1b08
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4a678b64-d329-478e-91d2-4cd60c6fa5f1

		level Year
			ordinal: 0
			column: Year
			lineageTag: f48bdf54-54ea-415a-b80a-c01e184ae21a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 43f6481c-6e12-47dd-9d63-826ad33a5f00

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: bb8a8644-ba5e-46d0-9b55-324f6cef324c

		level Day
			ordinal: 3
			column: Day
			lineageTag: a708e6c6-7753-4769-86c7-bff1e430c592


	partition 'Calendar-dd5b6c14-b67e-4e55-9d5c-51aa1a66717f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

