table Calendar
	lineageTag: cc3f6021-48d4-4ff7-969c-c6a17ffcf397

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6d96678a-c1a6-409e-826b-bd54915ed4c7

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: f8ccbd7c-5455-4335-ad08-55293d6461bd

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 6d3ab4ce-cb02-4cc9-92a3-8fb669af6074

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 07a148c5-1dc6-47dd-b128-c9492e95399f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 79c6ca4b-241a-40a1-99bd-085ba4282095
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 07596323-31bb-4226-8143-67d9d9a9f9cd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b29f0af9-8b93-4188-8a5a-9054ec74be4b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 7db47fe7-64b5-430f-9e1e-91fa0f3379b0
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 5dd89c93-ac84-48e3-a512-0df1332ce59f
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 89a75ca9-908f-4b32-9b4c-1f112b666a25
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c34d5694-2d80-4278-b61f-21cd9845d7d9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4f5d2b10-c691-4c57-af24-ec6f20d30476

		level Year
			ordinal: 0
			column: Year
			lineageTag: eaa0e774-1b68-41cb-b510-10f77b9cc98b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 490cef29-322f-4d21-ae76-3df02f6be61c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7e4a8b1d-fbe0-4654-bb53-c45b60185eb7

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3390f2aa-dd8c-4f43-88bb-061d1b34669c


	partition 'Calendar-7135288b-8b81-450a-9a06-d73190df719b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

