table sessions
	lineageTag: 1527d1e9-d901-41d5-972d-b05577d501c0

	measure 'Total Sessions' = COUNT('sessions'[session_id])
		displayFolder: Measures
		lineageTag: 61c595a6-4203-4a6e-813e-9b094a23a445

	measure 'Unique Visitors' = DISTINCTCOUNT('sessions'[user_id])
		displayFolder: Measures
		lineageTag: 12785a35-2a81-48b4-b3c8-9bce3beb7e9e

	measure 'Conversion Rate' = SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b81d1aa9-d536-4c57-b4f9-656da867ed9f

	measure 'Avg Session Duration' = AVERAGE('sessions'[session_duration])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c3261688-f8c6-4076-82c0-d4db7e72d1a2

	measure 'Total Revenue' = SUM('sessions'[revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ff704632-5b95-44f3-b396-dc3d38a64205

	measure 'Revenue per Session' = SUM('sessions'[revenue]) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 93d83b80-673f-495a-a06b-c9bfccf92824

	measure 'Revenue by Channel' = CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8b7bf577-4635-4520-8593-430fd16e2cb3

	column session_id
		dataType: string
		lineageTag: 280d7a7e-914c-4e1c-b8d9-81b802cb530e
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column session_date
		dataType: dateTime
		formatString: General Date
		lineageTag: bc1c8edc-4764-4c21-9328-dc2333f57955
		summarizeBy: none
		sourceColumn: session_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: 4fbef260-e12c-42ce-9e51-df1a191be4e1
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: cd7dcd91-3c41-4f2b-b367-cc2ef7fe99bb
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: 7f91f131-4ae6-4cde-b00a-45780446c39b
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 6e31b90d-8e2a-4319-9ec7-cdea4de74bec
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column page_views
		dataType: int64
		lineageTag: a8ee4e8c-fa10-4b3b-88b7-fd2f4f6d90d7
		summarizeBy: sum
		sourceColumn: page_views

		annotation SummarizationSetBy = Automatic

	column session_duration
		dataType: double
		formatString: #,0.00
		lineageTag: 628c3538-e0c2-4099-afcf-b66462e48e09
		summarizeBy: sum
		sourceColumn: session_duration

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: boolean
		lineageTag: 12748dfd-ad5a-4e9c-9689-299392058649
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: cf0a27d0-8501-4493-a09b-cfc25e67e006
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column 'Channel Category' = IF('sessions'[channel] = "Organic Search" || 'sessions'[channel] = "Paid Search", "Search", IF('sessions'[channel] = "Social" || 'sessions'[channel] = "Referral", "Social/Referral", IF('sessions'[channel] = "Direct", "Direct", "Other")))
		dataType: string
		lineageTag: 67fb74d4-c7f1-4c4e-a2ef-e42f3816593c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Engagement Level' = IF('sessions'[page_views] >= 10, "High", IF('sessions'[page_views] >= 5, "Medium", "Low"))
		dataType: string
		lineageTag: e2a75897-7d3b-465f-bac7-083564f0fed4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Days Since Signup' = DATEDIFF(RELATED('users'[signup_date]), TODAY(), DAY)
		dataType: int64
		lineageTag: e2f4687c-5b40-471e-a461-9ce4f3a929fd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'sessions-160b54b9-395a-4920-9ae9-c80a182f072c' = m
		mode: import
		source =
				let
				    // Source Google BigQuery: my-analytics-project.web_data
				    Source = GoogleBigQuery.Database([BillingProject="my-analytics-project"]),
				    #"web_data" = Source{[Name="web_data"]}[Data],
				    #"sessions Table" = #"web_data"{[Name="sessions"]}[Data],
				    Result = #"sessions Table"
				in
				    Result

	annotation PBI_ResultType = Table

