table Calendar
	lineageTag: 9dc12c0c-cdeb-4750-9734-38f0424e8c98

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 47f44c3f-514c-471c-a1bf-94092de6b616

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b53ecc32-3000-4702-8f5b-5bf06071d0c6

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 46018abb-ef1c-4e98-91bc-7ccca061db7d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 54f9c156-4c47-4545-b0af-f5b19a3e1d35
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 27ef6b2d-f959-49f2-b53a-3c54936dd079
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 772f52e1-3dd7-4571-a470-4faec053ea80
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 3353c983-f1c2-4373-9a1c-e760410043a4
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e155e79d-c50d-42b5-88b6-d0e86428f4b8
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1a11e0cf-e3b9-408a-af01-f343a28e8a00
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: effdfbf6-2e39-4048-bd7d-8a52d33e87c7
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2984336c-63c8-4f2c-95f2-7bcda6b6b493
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: d1e3c65f-4ced-4335-91f2-82608cff2b7e

		level Year
			ordinal: 0
			column: Year
			lineageTag: d1d4729a-22c6-435d-9748-5ffb19939801

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 87ec265c-4392-44c8-a3f6-f244c6fc9eeb

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 5fd28fb0-7fa1-4e48-a2fe-9d14a664ab7c

		level Day
			ordinal: 3
			column: Day
			lineageTag: c3ed8d2f-f8de-4450-9cb3-23e2e2362b76


	partition 'Calendar-0e00fc9d-2903-46d0-ac6f-ea1fa418be76' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

