table Calendar
	lineageTag: 5d0d8e64-de3e-4290-8bcc-f955d6b0f61e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0dd94175-4399-4da9-82a4-ddf32126ea40
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 43e7f202-f779-41a4-9914-52698a5e220f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ccafd0fb-3731-4ba7-81ad-803309fb6a14
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 89ee9f49-4b0d-4655-9a7f-31b9e2dcf9b1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 161a777c-7bd2-4e88-9947-2cba1843ddb2
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 696b3828-c4e9-4017-9917-ce3bdb3d7ebf
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e0563d99-5669-4877-b0a1-09972ce0fd26
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d835cd5c-8d09-4e88-92da-8bd33cc86721
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 02ba3300-8f62-4256-ad27-3c2edfe95fc9

		level Year
			ordinal: 0
			column: Year
			lineageTag: 8c82de1f-d609-4184-bbd7-730f5874e8c0

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: a7da76d5-84e7-4e16-b034-630bc299725b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 05fc1343-629c-420c-92e0-657c21c16e37

		level Day
			ordinal: 3
			column: Day
			lineageTag: 01b1381a-2180-4bf5-b9ec-df0c67161c8d


	partition 'Calendar-ac7940d0-afdb-4a1d-b03a-6a3bc9502ed3' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

