table Orders
	lineageTag: f3db2ea6-22dc-458f-b3a6-fa33913b38c3

	measure 'Gross Revenue' = SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b7b2b674-d703-4d72-ade5-b1f3e0104a96

	measure 'Net Revenue' = SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", 'Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 663bd655-30bf-437f-bf7b-1f25a1edccf4

	measure 'Total Discount' = SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price] * 'Orders'[discount])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d13ae9cb-890e-48d3-aa79-5b7f8ed130b0

	measure Profit = SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", ('Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount])) - 'Orders'[shipping_cost], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d03301fb-496c-4620-8e63-8beff75b1da2

	measure 'Profit Margin %' = [Profit] / [Net Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d628cdfd-e3b8-4340-be78-f537f0c4febf

	measure 'Revenue per Customer' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[customer_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6ae0737f-a1ed-4620-b2b1-1e2ecb5342ce

	measure 'Regional Channel Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[region], 'Orders'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: de878427-56ea-41e0-8985-c546619ebc78

	measure 'Revenue Excl Category' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), REMOVEFILTERS('Orders'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 53312ac3-f5ae-49b9-84f7-0981d8cc2fa9

	measure 'Moving Avg Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALL('Orders'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9af48dd9-1555-4fdf-9bfe-fd7e13d62920

	measure 'Running Total Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ea443089-8c8f-4e1b-ab7e-3928901994a9

	measure 'Revenue Rank' = RANKX(ALL('Orders'), SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]))
		displayFolder: Measures
		lineageTag: fc8dd64b-ea2f-4c36-8d6a-d2b7aa5850f0

	measure 'YTD Revenue' = CALCULATE(SUMX('Orders', IF(YEAR('Orders'[order_date]) = YEAR(TODAY()), 'Orders'[quantity] * 'Orders'[unit_price], 0)), ALL('Orders'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 752c9e5f-8787-4134-867a-8ad797e84166

	measure 'Customer Tier' = IF([Revenue per Customer] > 10000, "Platinum", IF([Revenue per Customer] > 5000, "Gold", IF([Revenue per Customer] > 1000, "Silver", "Bronze")))
		displayFolder: Dimensions
		lineageTag: 639d5407-2349-4e76-8b4d-cc057e9b2316

	measure 'Unique Customers' = DISTINCTCOUNT('Orders'[customer_id])
		displayFolder: Measures
		lineageTag: dbfe6e7c-3d9b-4fc3-ace5-fac8fbda942b

	measure 'AOV Completed' = AVERAGEX('Orders', IF('Orders'[order_status] = "Completed", 'Orders'[quantity] * 'Orders'[unit_price], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6dd00e41-eb59-476f-b1bf-f13d27862a04

	measure 'Revenue StdDev' = STDEVX.S('Orders', 'Orders'[quantity] * 'Orders'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6dbb3cf1-1e65-4814-bbd0-932776d7fea9

	measure 'Is My Account' = 'Customers'[customer_email] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 3ae95129-4573-4a79-8966-2776a1a54de6

	measure 'Date Range Start' = DATE(2024, 1, 1)
		lineageTag: 560382ec-8053-46ad-ba21-f5769fe91604

	column order_id
		dataType: int64
		lineageTag: ca3e5df7-4562-41a0-8247-932565fb4273
		summarizeBy: sum
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d4bd6880-7eb9-459b-911a-689fe4525539
		summarizeBy: none
		sourceColumn: order_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		lineageTag: a8a6e109-a799-40fd-8357-46b96a0c11a0
		summarizeBy: sum
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		lineageTag: 9f2cf75a-7a57-4cfe-8201-a0fb45a82764
		summarizeBy: sum
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 14e55d96-750f-4a52-a46b-7b2924e0e43f
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 99d999f1-3f92-4c68-99ab-a6c841d7517e
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		formatString: #,0.00
		lineageTag: 7e52f9d7-5c55-4df4-a3f5-2d547434a6d6
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		lineageTag: 306ee415-744d-49dc-a7cf-6317162d9857
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column discount
		dataType: double
		formatString: #,0.00
		lineageTag: 5918d298-1516-43ae-aab5-109209afdd9c
		summarizeBy: sum
		sourceColumn: discount

		annotation SummarizationSetBy = Automatic

	column shipping_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 810e041c-8401-40d7-a78e-3cdf0457f9e3
		summarizeBy: sum
		sourceColumn: shipping_cost

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: 3549d1eb-5517-45ca-949e-389bbffbf8ef
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column sales_rep
		dataType: string
		lineageTag: 31dc34d0-a6d1-4021-b4f1-58373e29c82b
		summarizeBy: none
		sourceColumn: sales_rep

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: 9143cfe3-8978-4d6f-aea1-5e6c258ec5f6
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column 'Customer Tenure Days' = DATEDIFF(RELATED('Customers'[first_purchase_date]), TODAY(), DAY)
		dataType: int64
		lineageTag: be4fb42b-f25e-4814-91ec-45af0e0d1e29
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Safe Discount Rate'
		dataType: double
		formatString: #,0.00
		lineageTag: 2184f837-69e7-47e5-a92e-4b36a5a2cbf6
		summarizeBy: none
		sourceColumn: 'Safe Discount Rate'

		annotation SummarizationSetBy = Automatic

	column 'Full Location' = UPPER(RELATED('Customers'[city])) & ", " & RELATED('Customers'[state]) & " (" & RELATED('Customers'[country]) & ")"
		dataType: string
		lineageTag: 08176bf5-8f6f-42b7-a98f-3db7b67d7091
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment Label' = "Segment: " & RELATED('Customers'[segment])
		dataType: string
		lineageTag: 82a8de2b-7ff6-4e51-9102-92d6240164e7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Discount Category'
		dataType: string
		lineageTag: 58742630-f632-4a17-a695-fef01a43daf3
		summarizeBy: none
		sourceColumn: 'Discount Category'

		annotation SummarizationSetBy = Automatic

	partition 'Orders-2fb68f10-cd8c-4007-9093-4779e596660c' = m
		mode: import
		source =
				let
				    // Source Snowflake: acme.snowflakecomputing.com
				    Source = Snowflake.Databases("acme.snowflakecomputing.com", "COMPUTE_WH"),
				    #"ANALYTICS" = Source{[Name="ANALYTICS"]}[Data],
				    #"PUBLIC" = #"ANALYTICS"{[Name="PUBLIC"]}[Data],
				    #"Orders Table" = #"PUBLIC"{[Name="Orders"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Orders Table", {{"order_id", "Order ID"}, {"order_date", "Order Date"}, {"customer_id", "Customer ID"}, {"product_id", "Product ID"}, {"region", "Region"}, {"channel", "Channel"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"discount", "Discount"}, {"shipping_cost", "Shipping Cost"}, {"order_status", "Order Status"}, {"sales_rep", "Sales Rep"}, {"territory", "Territory"}}),
				    #"Added Safe Discount Rate" = Table.AddColumn(#"Renamed Columns", "Safe Discount Rate", each if ([discount] = null) then 0 else if ([discount] = null) then 0 else [discount], type number),
				    #"Added Discount Category" = Table.AddColumn(#"Added Safe Discount Rate", "Discount Category", each if ([discount] = null) then "No Discount" else if [discount] = 0 then "No Discount" else if [discount] < 0.1 then "Low (<10%)" else if [discount] < 0.25 then "Medium (10-25%)" else "High (>25%)", type text),
				    Result = #"Added Discount Category"
				in
				    Result

	annotation PBI_ResultType = Table

