table 'Target Margin'
	lineageTag: 5ea7dcd4-e48b-470c-ad36-1fc8c13c4bea

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: d8d5fced-3e44-4b77-ad13-ba5f36d16600

	column Value
		dataType: double
		lineageTag: d7ccc69b-7938-4626-9925-657855dc6b97
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-338d8629-51f1-4cc5-a5c7-7d639f640b5f' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

