table 'Top N'
	lineageTag: 3641a985-b6c3-4b44-be9f-ba629ecb3963

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 7c4658c3-cd08-4847-b0e8-292c0d59bdc5

	column Value
		dataType: int64
		lineageTag: b3bfd6f1-deab-43c5-bec7-00a316032997
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-ebfd69b5-212d-4026-99a5-81433c64b78b' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

