table Calendar
	lineageTag: b3bd9bc6-69b1-4ab0-a859-bb769a00984e

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6ac3256c-a95e-4ce5-9db2-81ce0ba4dd2f

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 416e8c1c-b5b8-4135-b48a-a5f848e684f2

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: b0a060e0-b76b-4fff-ac29-861698d78320

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 55536cbc-f741-4d08-a847-cd2fe5cf598d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c8b6309c-4391-4537-af79-c535c88c2149
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c94d7068-5047-46a8-8ae6-7a565141afd1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: eeb3fea8-77e9-4392-bf12-0258aa7ecdb2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b17725bc-7170-43a4-97c0-118e5c818442
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d5b01f83-5753-4f4c-9573-ed1b4cd0ef09
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 469a4da4-5a0e-42cd-8728-208074c03302
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 54636dbc-25f7-41b6-a7e0-d6cf6274fa48
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4b0d42cc-11c3-448c-b2aa-56b74a773adb

		level Year
			ordinal: 0
			column: Year
			lineageTag: cc9ed4e3-6a02-4ccc-83bd-354d6a9bc17e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b34a370e-6213-43ec-8f8e-9fee92778839

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a62bdc3f-1326-4938-8d96-79cd0ba7f79e

		level Day
			ordinal: 3
			column: Day
			lineageTag: f68ab131-f118-466d-962a-c3be871b1d79


	partition 'Calendar-3a180738-ab6a-40b1-a8e4-8b5e967850bf' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

