table Regions
	lineageTag: 42a83108-f2b9-4a8d-bd0c-94a0770fe608

	column RegionName
		dataType: string
		lineageTag: 1fddcca5-fd0b-4870-98ee-cc56d54fdfe1
		summarizeBy: none
		sourceColumn: RegionName
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: 1f1a4ce4-264e-4351-b98b-832272385a7a
		summarizeBy: none
		sourceColumn: RegionManager
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'Regions-b09c7eb6-33cc-4b02-b858-754dc637d2e7' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("localhost", "SalesDB")
				
				    otherwise
				
				        #table({"RegionName", "RegionManager"}, {}),
				    #"Regions Table" = Source{[Schema="dbo", Item="Regions"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Regions Table", {{"RegionName", "Region Name"}, {"RegionManager", "Region Manager"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

