table Calendar
	lineageTag: 3eef192a-b1fd-4a4c-ab50-fdb3a39c062b

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a4af4159-bf49-4050-ba07-1ad692f9a8d5
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: bb6aaacf-f886-483b-bbe7-a295e0278c4d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 858c0028-1208-4dd7-9421-5808ba9eb29f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 11794782-1279-4204-9866-e4a7cbe03a59
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4408af51-c5aa-4ef6-afe7-1edbcd3daf87
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ffc521db-15e3-45ec-a5d9-f63797509371
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 14172d59-3671-4a8a-89a3-24d2e79d4213
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9348d758-f6c1-4b70-9821-d3f814052db0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: cb57c144-5b3c-4f31-b0f3-8cfcdcd572dd

		level Year
			ordinal: 0
			column: Year
			lineageTag: 956c3cec-8325-475c-93b7-c4199932ad5e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 559d37d0-da6d-48dd-a069-a5d774327ba8

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8f3b3b84-d63f-4c20-89fb-df9de7b05320

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7f80f550-edab-4f5b-98c6-d77c46a504f0


	partition 'Calendar-3f1fde1a-a8f4-4c5b-a3b3-64d8b362c702' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

