table Calendar
	lineageTag: fa44f6c4-cef3-40c6-bec0-2ce0567a47d3

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 371fe00b-bcf5-4c9f-ba70-9baa786eeaf8
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 7973356a-a0e1-4728-a12a-29aff788d551
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e1840129-8434-46c6-8095-fca44a8ffc20
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 09dfc763-a694-4753-aa09-167d876e3653
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: db8cfcf7-693a-4afd-92ca-df815f292d63
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 502d3413-9283-4b3e-91f9-140d23830318
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 52ff1387-958d-4b85-afb2-a1490b7dcba5
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 15b6dd59-29e3-4503-b93f-60427a62ec34
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 754de675-7a2e-4d68-be87-b72c0b447bfc

		level Year
			ordinal: 0
			column: Year
			lineageTag: bf34199b-7bb2-415a-bf16-5b05d636867c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 99f80832-8ad4-47e3-8d70-936c249afd91

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3ffbaf03-75e8-4c73-b1ae-92617bb6dccc

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5806c7e1-80c2-4836-8a0a-c5c6bd487da2


	partition 'Calendar-9b23d4f0-240e-4c8d-8ba4-548cb69a5faf' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

