table 'Min Budget'
	lineageTag: 5d4dab10-a13b-4c86-97f1-56f3b4ee7ce5

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 4edfe4ac-b0a8-485f-9353-0a13e0875c78
		annotation Copilot_Description = DAX: SELECTEDVALUE('Min Budget'[Value], 5000)

	column Value
		dataType: double
		lineageTag: 79e29737-077a-4ccf-a2c4-82b3927fc22a
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-e06131dc-fae8-4135-97b3-994127ae7551' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

