table Regional_Sales_Summary
	lineageTag: c11bd0a6-9fda-4c11-92e0-ffc448d1ad11

	measure 'Target Channel' = "Email"
		lineageTag: 9126e5a9-4a5c-45cf-af4d-91562ba465cb
		annotation Copilot_Description = DAX: "Email"

	column Order_ID
		dataType: string
		lineageTag: 094e215e-8287-4376-9608-ef70ae9f48f1
		summarizeBy: none
		sourceColumn: Order_ID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Order_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 20616fb4-fec6-4fcd-8d88-24b0219c1c88
		summarizeBy: none
		sourceColumn: Order_Date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Customer_ID
		dataType: string
		lineageTag: d3b55052-13e7-4cd5-8355-6c3c9c6b1cc0
		summarizeBy: none
		sourceColumn: Customer_ID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 5e27d6ad-3d7a-4a99-8ec0-a20f02806b2d
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d9df3d1c-72a4-4886-b0cc-7ec64894f5b8
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: 95c54ae7-5308-4fd3-8cea-d9f9c288457f
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: b4bd5154-e486-4e20-9666-421d914b7e52
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 655d4c42-40bb-47eb-96f3-803ea2836914
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: a600e4cc-b6d1-40f5-a144-edd10cc1185d
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 90283890-cd91-4d76-8aba-b2a07ebf468b
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 57ab492b-ee11-43a8-9a40-65452afb7a5a
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column TempCol
		dataType: string
		lineageTag: 7370ca27-52fd-4517-b4fb-ffe1b7b1e301
		summarizeBy: none
		sourceColumn: TempCol

		annotation SummarizationSetBy = Automatic

	partition 'Regional_Sales_Summary-07a3c672-b5a7-453c-b519-c883d36dc9c0' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: textscan
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Order_ID", "Order_Date", "Customer_ID", "Region", "Category", "Product_Name", "Sales", "Quantity", "Discount", "Profit", "Status", "TempCol"},
				            {
				                {"Sample 1", 2, "Sample 3", "Sample 4", "Sample 5", "Sample 6", 7, 8, 9, 10, "Sample 11", "Sample 12"},
				                {"Sample 2", 3, "Sample 4", "Sample 5", "Sample 6", "Sample 7", 8, 9, 10, 11, "Sample 12", "Sample 13"}
				            }
				        )
				    otherwise
				        #table({"Order_ID", "Order_Date", "Customer_ID", "Region", "Category", "Product_Name", "Sales", "Quantity", "Discount", "Profit", "Status", "TempCol"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Order_ID", "Order ID"}, {"Order_Date", "Order Date"}, {"Customer_ID", "Customer ID"}, {"Product_Name", "Product Name"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns", {"TempCol"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each [Status] <> "Cancelled"),
				    #"Trimmed Text" = Table.TransformColumns(#"Filtered Rows", {{"Region", Text.Trim}}),
				    #"Proper Cased" = Table.TransformColumns(#"Trimmed Text", {{"Category", Text.Proper}}),
				    #"Replaced Nulls in Discount" = Table.ReplaceValue(#"Proper Cased", null, "0", Replacer.ReplaceValue, {"Discount"}),
				    #"Added Revenue" = Table.AddColumn(#"Replaced Nulls in Discount", "Revenue", each [Sales] * [Quantity] * (1 - [Discount])),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Revenue", {{"Order Date", type date}}),
				    #"Joined Joined" = Table.NestedJoin(#"Changed Type", "Customer ID", Customers, "Customer_ID", "Joined", JoinKind.LeftOuter),
				    #"Expanded Joined" = Table.ExpandTableColumn(#"Joined Joined", "Joined", {"Customer_Name", "Segment", "City", "State", "Country"}),
				    #"Grouped Rows" = Table.Group(#"Expanded Joined", {"Region", "Category", "Segment"}, {{"Total Revenue", each List.Sum([Revenue]), type number}, {"Total Profit", each List.Sum([Profit]), type number}, {"Distinct Orders", each List.Count(List.Distinct([Order ID])), Int64.Type}, {"Avg Quantity", each List.Average([Quantity]), type number}}),
				    Result = #"Grouped Rows"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns and 1 measures: Order_ID, Order_Date, Customer_ID, Region, Category, Product_Name, Sales, Quantity, ... (12 columns total).

