table Calendar
	lineageTag: 25e3fd13-093f-4713-86bd-fc338a2054ea

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 36fc7f58-83db-4987-a6bd-d0decd80b5ad

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: eb95aa4f-1718-4e64-bb43-bb286de4f94d

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: b40a4d66-3e52-40da-9876-efecc1b4ce1e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b925b6e8-d51f-40ce-887b-906ed219639f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f360385f-4315-48f9-a3ee-cf8b24882e18
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d0daec3b-412c-4004-a46f-32451e786996
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 13a780a6-5f07-415c-81cb-0794f2888dd2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 604c0740-88da-49ad-8b0c-8d97ad65e0c0
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 9f1d241d-3b40-45e9-8888-ad8ddd7e9910
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 9adf8dec-20d0-4596-ad6b-4260901e9114
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 65057b77-a458-45c2-82a9-d0baafbc4ffd
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 79a76cf2-3b5a-456e-a6dc-309b369e9b88

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7ff0d6aa-adb2-4a24-98f2-f64266ef15a3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e4f83592-d60a-432b-aa62-708ad7d42a5c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f1929ae4-1b59-43ce-8e91-0d27331419e0

		level Day
			ordinal: 3
			column: Day
			lineageTag: 8b805a1b-7eee-425a-95a9-ea37c5259c77


	partition 'Calendar-ce3af2a5-e9f3-476d-a655-bd89d08cfd2f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

