table Calendar
	lineageTag: ce2fbf34-c259-40aa-95a9-bacbf94828db

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 838a58a1-eaf6-43e1-be9f-1387b6834003
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 31f19e94-eb0b-4cd7-a577-968cca219cc1
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c22f06fc-2934-42ae-8546-e3a7d9cc1c1d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a87afbe4-3ee5-4a21-9cfb-7c64502594e8
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 83abc014-3334-4509-8926-44a1b4e8f58d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 323d9003-d759-45e2-bc8a-7db191964e08
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 9509f135-ae79-4a9f-988f-2828c8514907
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b8265460-e831-45a3-b3cb-f6d60d04a3b8
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: dfa99d94-d1ff-4719-8004-f3a4bfc466eb

		level Year
			ordinal: 0
			column: Year
			lineageTag: dc04c2ee-5048-442e-9d97-569ad1a1c42b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: cedb6af8-653c-4db1-ba10-101486ad0f43

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 5921073e-96f3-457a-ac5e-54f509f8ca12

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1f99bcd2-eea8-4f5b-bb09-293d7f08970d


	partition 'Calendar-3cbee3e7-1a82-422c-904b-a7dbeeecd312' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

