table Calendar
	lineageTag: 65c733df-c935-434c-8971-ef49d091388d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b685a7c5-e32a-48ac-b5d4-b8ba6c318a06
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 643146df-c72a-4b27-b62a-ed1a6e7d37ee
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: fcf963c9-a4be-43b8-a101-eeb347937c68
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 9f47358e-feca-4ac5-a940-d3b61d414b7f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 7554192b-b427-4779-9af0-dda4fe2a479a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1be2a3d2-c0f3-4b3e-bbe5-dbb596b8eb10
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 98d58235-cf86-4680-983d-6680189ea0cc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f3e3e35d-90b9-4c95-b402-5889de6e5eae
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 71a96b16-7e07-4655-9b06-376b8905cb29

		level Year
			ordinal: 0
			column: Year
			lineageTag: e01c4fae-9ca7-4855-b2ff-4af99add7542

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d17ea6e2-7608-40e5-8769-8545b018fada

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3b5d34d9-841f-4038-b12a-5ea718c6fa4e

		level Day
			ordinal: 3
			column: Day
			lineageTag: 60c0b946-9fe4-4f9a-a0f4-12f483b11439


	partition 'Calendar-133a8853-6903-48d8-b737-d292cc23821f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

