table Calendar
	lineageTag: e15f02fe-9880-406c-8404-548849e28e01

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 67804396-be7b-4522-be7d-d51d59139de1
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b70e011d-cf20-4ff5-b6fd-b3819eb99708
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 98f37506-7c0c-4a82-95bb-8bb3de993c16
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ae4d7060-f2d4-4f76-8cd0-e15e6b733eab
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 93ad4d32-5aaa-4f4c-8ab8-90e5a42a914f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: cf184d5e-b1b4-4721-a025-1f736a881dcc
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: aa0f53d3-e3d7-4312-9738-f7dd8b6f65d8
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 8037953f-5bd4-4f47-b191-f66ca74abce3
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4c732d3f-1a4f-41d8-ae04-c307934034eb

		level Year
			ordinal: 0
			column: Year
			lineageTag: aa5e4925-3cb0-4cbc-b62b-86634b7040a3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ec9f88db-634c-40d4-9f41-e4a6de55c00b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6803705f-ad42-49c9-8251-0e40e7b7934d

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4ed97964-be30-4976-908a-737e74a98955


	partition 'Calendar-8820c22e-3068-4c64-a60b-9d70bae53774' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

