table 'Target Margin'
	lineageTag: d33340bc-26f8-4e40-b4b7-5d3350cf0793

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 92c9283b-fda6-4dc1-b1a0-b063a82bed9b

	column Value
		dataType: double
		lineageTag: 37c51aae-0317-46d0-9cbd-fc1146a7ba36
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-21ae3f19-7d6a-4006-8928-20f60fc84c20' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

