table 'Target Margin'
	lineageTag: 8bed88a2-53bd-496a-9f23-345cfc965cf1

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: a3d11c95-9648-4ac8-bcef-75f4b0b99ec4

	column Value
		dataType: double
		lineageTag: 795dc8c8-d96c-42b0-b93f-42e07e4fa279
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-15551999-cbde-48b3-b45e-1a4d6cc9d4c0' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

