table 'Target Margin'
	lineageTag: 01f590c6-5995-4c13-b22d-de698b28144d

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 0e2ea68c-9854-4d4b-9a94-e933f7aaa01f

	column Value
		dataType: double
		lineageTag: f563974e-926b-4ace-9bde-67dda96d5720
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-4de7fc36-6827-4238-b9ba-1e304ff06862' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

