table 'Top N'
	lineageTag: b5d03401-ba08-4d90-ae14-4ab0065a1a0a

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: caeb6453-17fe-4fb1-9fab-9717123984c5

	column Value
		dataType: int64
		lineageTag: e9cfe907-7b29-4eda-9074-93d87b672998
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-bdff992e-5030-44e2-a342-2069125f5cfb' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

