table 'Top N'
	lineageTag: 70101274-c75e-4f4c-b0bf-e042788be330

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: cec6af56-3327-4389-a34d-ce836255b572

	column Value
		dataType: int64
		lineageTag: f8671d8f-f798-4792-acc5-8f6dc3878b0a
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-25b33b9f-93f7-4661-ba94-3bcf8b7bcd53' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

