table 'Top N'
	lineageTag: fda276c6-67aa-47f1-8295-cd65aadf8298

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 52063110-d7b3-4384-9d26-a20e33af6db9

	column Value
		dataType: int64
		lineageTag: d194dc11-ca84-4c22-9f40-c775473c4042
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-96efde9f-0768-4d49-b584-6b88fa5be3b5' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

