table 'Profit Bin Size'
	lineageTag: 51c82bc0-5e34-4ac2-9174-cb25098eed3a

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 0e876d2f-b11c-4cc0-81f0-7958665b15a7

	column Value
		dataType: int64
		lineageTag: 6bba5e7a-02ee-4301-bacf-ecb01869f86f
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-86597d32-4586-43a5-ada1-f85c203544f4' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

