table Calendar
	lineageTag: 7494d270-f39d-4e57-b1f7-6cc768fdb367

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b9793397-4c00-4e98-bd01-409f70008089

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: f91eceb4-527b-477d-b093-e0df46ee5808

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0281d60e-cf5b-4766-ac76-dbb06976f463

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 312173d1-7f75-44d3-9d4a-20e9d72b942e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 3240b5bd-a881-4d02-aafd-fa1dbf033e3d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: a3369cf8-01b7-4f2d-a64d-795991deb533
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a38aeda6-1b15-4b0d-8ebd-8963ec9f9cdf
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0dc959b9-5e04-448a-a54d-7e132604f955
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 95898846-e469-4c46-9699-13a27cf0c290
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 834fda83-7d00-4a67-bb39-1b4383df9a5c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2c394ffb-64bb-44d3-aa1d-b6a4f82eca74
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c0f1d00a-a2f6-411a-93f9-f9ad545048b2

		level Year
			ordinal: 0
			column: Year
			lineageTag: d7928609-45fe-4bb1-9fce-dc069849363e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ab59871a-7a2d-46d9-a75e-f5e41361a51b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8f7c7c72-a997-4e14-8bd5-299ed9ef5cd3

		level Day
			ordinal: 3
			column: Day
			lineageTag: 331c1813-c51d-4909-9a6d-a1d235e60685


	partition 'Calendar-fb45846a-8c35-4557-b7dc-6ca9b0b880ee' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

