table Calendar
	lineageTag: b39cbaac-10c2-4885-8c68-dc620112d454

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 4580efe6-cfc5-4872-ab30-5bec01c8c364

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d2847473-a07c-48fa-972d-90e465ed7efe

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: f77de4d8-aadf-4c84-b47c-42cbbbb28a4b

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bcb7db1d-37bb-4c9b-9c3c-ad70decbed7d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0b49edba-7b43-4e46-9731-226a6eacd513
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1429ccb3-1d14-4a06-8754-e245bdfbe836
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2a587b66-abb5-4737-897e-ba85d58bd16f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 166a6cc7-3fd8-451c-b6b6-2a1cd3d24ef5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7a183685-9747-409a-84c1-ab13098a3550
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e6635a08-73a0-4005-9903-81976efa64ef
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 41fa911e-904f-4df3-a169-860a7738b647
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3bb96991-78c0-4600-b3b4-8cf08c287256

		level Year
			ordinal: 0
			column: Year
			lineageTag: 90dd049f-60f1-4b22-93a9-3961150ac252

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 21cf8325-d46a-4431-b38d-45340363762f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e427605b-8e3d-4775-a090-e2ebb4470797

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3fe609de-1681-41d0-a502-3bf1126d6f7d


	partition 'Calendar-2c8ba228-f442-4805-b973-e2b78f728d8e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

