table Calendar
	lineageTag: c01388b1-cdf0-4b8b-805f-226574f011b5

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 91bef8b0-09f6-4d29-8d23-1108c3fed463

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7c184866-5f90-434f-87e7-327ecaa9647b

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 41fd18a2-1e56-4303-a341-dd556f0ff566

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 095fde97-85c1-478c-995c-5c4edd490bb5
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d7def09d-b51e-4ece-a000-36a86b5de8a0
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7cae00f6-58d9-4d4b-a014-12f1a64010ac
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 377964ca-ca36-4b0f-a1d8-f8672e40b0ef
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c609d110-eb45-4dd8-a435-19b24e9877eb
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 9ffe100b-074b-4d26-94e9-88ade8c42402
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7a1516af-ae71-45f9-8db0-eb151337d4c6
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 91cbb9c1-91b9-4e50-9581-a4d01dbc6cda
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 614d6178-db87-40a8-a917-ad740e41740f

		level Year
			ordinal: 0
			column: Year
			lineageTag: b776cf17-6e81-4d6a-a582-b2f038079eec

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 84e4154b-ad77-4e01-ac45-d5f6923c8a76

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 22974535-89d3-45a7-aade-a512be05710a

		level Day
			ordinal: 3
			column: Day
			lineageTag: ae7bb6a3-289c-4b00-b696-9a1b5bfa34ae


	partition 'Calendar-b7faa803-3263-4149-b495-2bd80ab28677' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

