table Calendar
	lineageTag: 049be45a-0780-4925-b19a-93948a331ff8

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 083dca8d-b825-4302-9d5b-a102c14ff9ed

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5a790b35-4e5f-4bc8-a395-54fb70c6881f

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 11887042-b3a6-428a-a6eb-4fa694c08a3e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: dea5ad7b-c14c-4118-b2cf-dd5590e3c2d3
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 59346692-594b-4ccb-87ca-0e3d19a99336
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8414e6c0-e17f-409c-aa4e-f351b46e59d9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c60af4ea-c7ef-4b30-ac15-b7201b493536
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 02bea174-926b-41b3-980e-1fd80a0ecd2d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 6ed02883-ac6c-47f7-bc4a-0cc2d8068d4c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 44adbc36-3d21-4133-800d-8350713e54f7
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: af63e246-146e-4c98-a9b7-ffa751355fe1
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 08ef8675-da1a-44bd-9819-6c96af59e9dc

		level Year
			ordinal: 0
			column: Year
			lineageTag: ba7f7cab-add6-4524-beb5-9233547d38c7

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 45869643-afd9-42fe-83b6-5465e7731b38

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 61893bde-155d-437f-bea1-6bc3f911502a

		level Day
			ordinal: 3
			column: Day
			lineageTag: f61a1b58-9a1a-4b18-9de2-349f5a7ad5a1


	partition 'Calendar-3d2a651b-bda9-4173-bf6d-874e5959a9a2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

