table Calendar
	lineageTag: 3a3d27c1-a2ae-485d-99e9-c74bdb8d4129

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d49484f7-6d02-4ed1-bd96-754a38cf67e1

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9133fe6b-3de4-438b-b9b2-b33559c1fb63

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0567eccd-da18-4531-80c9-49ba897741a4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f085be60-0d49-469f-9075-1b7daf778ea7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a2e957e7-7e62-4ea3-8eaa-fbbec00c0b04
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 6fb31fa2-9246-4dce-a277-496a10316c14
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: cc6e923c-484d-49b6-bf29-20295083e311
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b02de10a-ed69-44d3-ad5a-eb07e53644ca
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3e7fe735-d1f2-495a-8a35-e355178446c7
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: fd24595a-db28-4566-8398-247f24c39ffd
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 0bf2cbbf-5e63-49de-88f1-409dcf1c0323
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 710b28e5-50d5-4810-bb7c-456d86184273

		level Year
			ordinal: 0
			column: Year
			lineageTag: cffecd5b-0c1c-48e1-93ab-c3beb09dd16e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b3a486fa-3ef4-42e1-bc87-61741260c42f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ff9821b1-2f87-4e54-8beb-fdd04164607d

		level Day
			ordinal: 3
			column: Day
			lineageTag: 94fb74f9-4cf1-4a2e-bb10-2728a90f1f9f


	partition 'Calendar-f54152aa-ede6-4146-8b99-20205c80e7d4' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

