table Calendar
	lineageTag: 987eb03d-0515-444d-a838-6a317d8c38d4

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: e1112cb6-77c5-422a-a5bc-1afdf0a075bd

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 891b6991-2854-444b-b4df-e056cdcaa395

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: bddb1af4-45dc-4e6c-b30f-b9b73e8e1cba

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c023a6d0-afeb-4d70-80e3-818809954645
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ebc373bc-788d-47c4-9930-886110f24940
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 010386d6-dfcf-4dac-9af3-041b94b35712
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 605428fc-8ea6-40a8-9c7d-8d35745ddfa6
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2613c7f9-93a2-4c58-b090-0c4053386bbc
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 716ed57a-74f0-403d-ae0c-bb7bd8310ad0
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b8692ab5-e3a3-47df-906e-9e060c40c3cb
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 45f95142-30ae-410d-969d-bef41a698b47
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f0a2ef6f-66b5-4c2c-9ecb-cec44050ce37

		level Year
			ordinal: 0
			column: Year
			lineageTag: fecea58c-e507-45e7-8536-bcbd7b9cb49e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 5cb9fedd-1dce-4218-8779-a4053708dda7

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: eaae3e21-6ca1-4bee-90f6-21ea7ed7fa1a

		level Day
			ordinal: 3
			column: Day
			lineageTag: 32f60f5d-09c8-42e8-9286-9b0b114cc865


	partition 'Calendar-d6c44a2e-7cbb-48b0-bf5e-0f065b52728f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

