table Campaigns
	lineageTag: 78a160a7-4385-40d7-91f5-048eb0a736db
	description: Contains 29 columns and 11 measures: campaign_id, campaign_name, channel, start_date, end_date, budget, spend, target_audience, ... (29 columns total).

	measure 'Non-Blank Leads' = COUNTA('Leads'[lead_name])
		displayFolder: Measures
		description: Migrated from Tableau: COUNTA([lead_name]) | DAX: COUNTA('Leads'[lead_name])
		lineageTag: 558f8747-a346-48ef-b8ae-5e80bd0f1014

	measure 'Budget Deal Correlation' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) * ('Leads'[deal_value] - _MeanY)) VAR _StdX = SQRT(SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) ^ 2)) VAR _StdY = SQRT(SUMX(ALL('Campaigns'), ('Leads'[deal_value] - _MeanY) ^ 2)) RETURN DIVIDE(_Cov, _StdX * _StdY, 0)
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: CORR([budget], [deal_value]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]...
		lineageTag: 45926f62-3992-4d23-9cb8-699831357c46

	measure 'Spend Engagement Covar' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Campaigns')) RETURN DIVIDE(SUMX(ALL('Campaigns'), ('Campaigns'[spend] - _MeanX) * ('Leads'[engagement_score] - _MeanY)), _N - 1, 0)
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: COVAR([spend], [engagement_score]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_s...
		lineageTag: 1f2cc57d-c915-4b6f-afef-d20863af4a04

	measure 'Avg Deal by Channel' = CALCULATE(AVERAGE('Leads'[deal_value]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {INCLUDE [channel] : AVG([deal_value])} | DAX: CALCULATE(AVERAGE('Leads'[deal_value]))
		lineageTag: 5de2b28d-e83a-43cb-a1dc-50cbe3dda1b0

	measure 'Campaign ROI' = (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: (SUM([deal_value]) - SUM([spend])) / SUM([spend]) | DAX: (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		lineageTag: c445b05c-c3aa-489b-8c8b-9f61cd26e157

	measure 'Cost Per Lead' = SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([spend]) / COUNTD([lead_id]) | DAX: SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		lineageTag: cf789f4e-bd9d-40e3-bb59-2a0d363c1eb3

	measure 'Window Best ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: WINDOW_MAX((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		lineageTag: 2cd7d428-7be0-400c-98a8-21e39f0dab16

	measure 'Window Worst ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: WINDOW_MIN((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		lineageTag: 26da7b5b-ff67-4b19-bafb-8575fa3b2aff

	measure 'Cumulative Leads' = CALCULATE(DISTINCTCOUNT('Leads'[lead_id]), FILTER(ALLSELECTED("Campaigns"), TRUE())) /* RUNNING_COUNT: converted to cumulative — verify window scope */
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_COUNT(COUNTD([lead_id])) | DAX: CALCULATE(DISTINCTCOUNT('Leads'[lead_id]), FILTER(ALLSELECTED("Campaigns"), TRUE())) /* RUNNING_COUNT: converted to cumu...
		lineageTag: bcfd8054-b5b8-42ba-aea0-a39634a793bd

	measure 'Conversion Rate' = SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM(IF [lead_status] = "Won" THEN 1 ELSE 0 END) / COUNT([lead_id]) | DAX: SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		lineageTag: 2d284533-e4b8-43ef-9d5b-9be00914b561

	measure 'Target Channel' = "Email"
		description: DAX: "Email"
		lineageTag: 8ca03e3d-6b21-4b81-8414-cfd9ef438725

	column campaign_id
		dataType: int64
		lineageTag: ab6acb2d-6325-44d9-a77d-b211e9de615f
		summarizeBy: sum
		sourceColumn: campaign_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 34cb55fb-16dc-4462-8ade-d4bd0081035a
		summarizeBy: none
		sourceColumn: campaign_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 1feab398-b89f-4c73-87b0-221c9ebe3f27
		summarizeBy: none
		sourceColumn: channel
		description: String column.

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a8849148-6b4f-4ff1-9a74-b8b34363e934
		summarizeBy: none
		sourceColumn: start_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b12329d-dac2-4571-9e6c-9d048841cbae
		summarizeBy: none
		sourceColumn: end_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: d778e79c-c363-4e75-b0f9-281a40edb0d0
		summarizeBy: sum
		sourceColumn: budget
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: #,0.00
		lineageTag: c2cdba6b-fb1a-4c33-88bf-8068dbfa34fb
		summarizeBy: sum
		sourceColumn: spend
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column target_audience
		dataType: string
		lineageTag: 0f8732fc-2830-459c-9593-1c91bb36541e
		summarizeBy: none
		sourceColumn: target_audience
		description: String column.

		annotation SummarizationSetBy = Automatic

	column creative_url
		dataType: string
		lineageTag: f8262fa4-db7a-48f3-b8c6-4db4279210d9
		summarizeBy: none
		sourceColumn: creative_url
		description: String column.

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 6c9118dd-ede4-46f7-a2ac-7ebf0ec256e7
		summarizeBy: none
		sourceColumn: utm_source
		description: String column.

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: 2b7bd635-ec2e-408f-98bd-fbf53d99274c
		summarizeBy: none
		sourceColumn: utm_medium
		description: String column.

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: cf3cff5c-36b3-4496-888f-bd89f94ad5fc
		summarizeBy: none
		sourceColumn: utm_campaign
		description: String column.

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 978eab30-b4ff-45b1-aad9-66979f0669c0
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: c137c8c3-649b-4388-a138-8dc16dd105a2
		summarizeBy: none
		sourceColumn: status
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Email Domain' = MID(LOOKUPVALUE(Leads[email], Leads[campaign_id], Campaigns[campaign_id]), FIND("@", LOOKUPVALUE(Leads[email], Leads[campaign_id], Campaigns[campaign_id])) + 1, LEN(LOOKUPVALUE(Leads[email], Leads[campaign_id], Campaigns[campaign_id])))
		dataType: string
		lineageTag: d542f458-cb51-4031-be61-fdf2855cb1a9
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'First Name' = LEFT(LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id]), FIND(" ", LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id])) - 1)
		dataType: string
		lineageTag: 7c467ec3-a9be-42c0-b53c-74abae64491d
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Last Name' = MID(LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id]), FIND(" ", LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id])) + 1, LEN(LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id])))
		dataType: string
		lineageTag: dfc68d8d-4d4b-49ff-b09d-e462495b938d
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Name Length' = LEN(LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id]))
		dataType: int64
		lineageTag: df483499-9a81-404b-a69b-573f9be94ac6
		summarizeBy: none
		description: Calculated column (Int64).

		annotation SummarizationSetBy = Automatic

	column 'Clean Phone' = TRIM(SUBSTITUTE(SUBSTITUTE(LOOKUPVALUE(Leads[phone], Leads[campaign_id], Campaigns[campaign_id]), "-", ""), " ", ""))
		dataType: string
		lineageTag: 594f71e7-c3b9-4033-87b6-14cde7770a47
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Phone Last 4' = RIGHT(LOOKUPVALUE(Leads[phone], Leads[campaign_id], Campaigns[campaign_id]), 4)
		dataType: string
		lineageTag: c568ed78-335d-41d7-8351-4261b1d2db3d
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Campaign Code' = UPPER(LEFT('Campaigns'[channel], 3)) & "-" & FORMAT('Campaigns'[campaign_id], "0") & REPT(" ", 5 - LEN(FORMAT('Campaigns'[campaign_id], "0")))
		dataType: string
		lineageTag: c55f4f8d-7151-4e98-a517-855f23425878
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Is Enterprise'
		dataType: boolean
		lineageTag: 245f1cde-1f10-4ba2-a35f-1aa2b4d88447
		summarizeBy: none
		sourceColumn: 'Is Enterprise'
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column 'Has Valid UTM' = /* REGEXP_MATCH: complex regex "^[a-z0-9_-]+$" — verify manually */ CONTAINSSTRING('Campaigns'[utm_campaign], "^[a-z0-9_-]+$")
		dataType: boolean
		lineageTag: d55f0434-1674-4cb2-937e-23b5d9af37cd
		summarizeBy: none
		description: Calculated column (Boolean).

		annotation SummarizationSetBy = Automatic

	column 'Clean URL' = /* REGEXP_REPLACE("https?://"): complex regex — verify manually */ SUBSTITUTE('Campaigns'[creative_url], "https?://", "")
		dataType: string
		lineageTag: 0150c613-d570-4870-ae20-f686e968e0ca
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Campaign Year'
		dataType: dateTime
		lineageTag: 34247156-c48e-4450-9fdb-dcf195299ffa
		summarizeBy: none
		sourceColumn: 'Campaign Year'
		description: Datetime column.

		annotation SummarizationSetBy = Automatic

	column 'Start Month'
		dataType: int64
		lineageTag: 6468d226-fbb2-44f6-bf76-33b749f6f7e6
		summarizeBy: none
		sourceColumn: 'Start Month'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT('Campaigns'[start_date], "MMMM")
		dataType: string
		lineageTag: d215900d-b56d-4b10-a5d0-7ed647b9bafe
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Campaign Days'
		dataType: int64
		lineageTag: 509b2157-698f-4f37-a084-15c8230d9d15
		summarizeBy: none
		sourceColumn: 'Campaign Days'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column 'Budget Band' = INT('Campaigns'[budget] / 1000) * 1000
		dataType: int64
		lineageTag: a9eb1051-cea8-4b2a-a5ca-bd45e407c495
		summarizeBy: none
		description: Calculated column (Int64).

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns-0d794b2c-fc64-43ab-938b-02fb98f2aa44' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = try
				
				        let
				
				            _src = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				
				            _nav = _src{[Schema="marketing_db", Item="Campaigns"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"campaign_id", "campaign_name", "channel", "start_date", "end_date", "budget", "spend", "target_audience", "creative_url", "utm_source", "utm_medium", "utm_campaign", "region", "status"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"campaign_id", "Campaign ID"}, {"campaign_name", "Campaign Name"}, {"channel", "Channel"}, {"start_date", "Start Date"}, {"end_date", "End Date"}, {"budget", "Budget"}, {"spend", "Spend"}, {"target_audience", "Target Audience"}, {"creative_url", "Creative URL"}, {"utm_source", "UTM Source"}, {"utm_medium", "UTM Medium"}, {"utm_campaign", "UTM Campaign"}, {"region", "Region"}, {"status", "Status"}}),
				    #"Added Is Enterprise" = Table.AddColumn(#"Renamed Columns", "Is Enterprise", each Text.Contains([target_audience], "Enterprise"), type logical),
				    #"Added Campaign Year" = Table.AddColumn(#"Added Is Enterprise", "Campaign Year", each #date(Date.Year([start_date]), 1, 1), type datetime),
				    #"Added Start Month" = Table.AddColumn(#"Added Campaign Year", "Start Month", each Date.Month([start_date]), Int64.Type),
				    #"Added Campaign Days" = Table.AddColumn(#"Added Start Month", "Campaign Days", each Duration.Days([end_date] - [start_date]), Int64.Type),
				    Result = #"Added Campaign Days"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 29 columns and 11 measures: campaign_id, campaign_name, channel, start_date, end_date, budget, spend, target_audience, ... (29 columns total).

