table Campaigns
	lineageTag: b9d35c7a-c306-4647-a130-a9d2730e5d5b
	description: Contains 29 columns and 11 measures: campaign_id, campaign_name, channel, start_date, end_date, budget, spend, target_audience, ... (29 columns total).

	measure 'Non-Blank Leads' = COUNTA('Leads'[lead_name])
		displayFolder: Measures
		description: Migrated from Tableau: COUNTA([lead_name]) | DAX: COUNTA('Leads'[lead_name])
		lineageTag: cbc8f8be-0f21-4e35-8956-df5480efde86

	measure 'Budget Deal Correlation' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) * ('Leads'[deal_value] - _MeanY)) VAR _StdX = SQRT(SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) ^ 2)) VAR _StdY = SQRT(SUMX(ALL('Campaigns'), ('Leads'[deal_value] - _MeanY) ^ 2)) RETURN DIVIDE(_Cov, _StdX * _StdY, 0)
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: CORR([budget], [deal_value]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]...
		lineageTag: 1b9286fe-74ec-4567-b85b-73e6c6bc2cc8

	measure 'Spend Engagement Covar' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Campaigns')) RETURN DIVIDE(SUMX(ALL('Campaigns'), ('Campaigns'[spend] - _MeanX) * ('Leads'[engagement_score] - _MeanY)), _N - 1, 0)
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: COVAR([spend], [engagement_score]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_s...
		lineageTag: a14bee21-505c-453e-add9-8c8211c21fa6

	measure 'Avg Deal by Channel' = CALCULATE(AVERAGE('Leads'[deal_value]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {INCLUDE [channel] : AVG([deal_value])} | DAX: CALCULATE(AVERAGE('Leads'[deal_value]))
		lineageTag: c03381c0-a28f-4e5c-8d40-bbd3dd281a3e

	measure 'Campaign ROI' = (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: (SUM([deal_value]) - SUM([spend])) / SUM([spend]) | DAX: (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		lineageTag: 32518c13-cf5b-4fed-be31-f75a7ca56c09

	measure 'Cost Per Lead' = SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([spend]) / COUNTD([lead_id]) | DAX: SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		lineageTag: cd4e99bd-007e-4f1b-825f-9c8cbab1604c

	measure 'Window Best ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: WINDOW_MAX((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		lineageTag: 06fe0c08-39b4-409b-a1c1-bd170cad9dd2

	measure 'Window Worst ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: WINDOW_MIN((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		lineageTag: b7991c0d-796c-4c88-848d-cf11a823bfb1

	measure 'Cumulative Leads' = CALCULATE(DISTINCTCOUNT('Leads'[lead_id]), FILTER(ALLSELECTED("Campaigns"), TRUE())) /* RUNNING_COUNT: converted to cumulative — verify window scope */
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_COUNT(COUNTD([lead_id])) | DAX: CALCULATE(DISTINCTCOUNT('Leads'[lead_id]), FILTER(ALLSELECTED("Campaigns"), TRUE())) /* RUNNING_COUNT: converted to cumu...
		lineageTag: 5ff461d6-4f2d-4277-992d-3b282353c0d0

	measure 'Conversion Rate' = SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM(IF [lead_status] = "Won" THEN 1 ELSE 0 END) / COUNT([lead_id]) | DAX: SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		lineageTag: 632363a0-7f0a-4657-8391-23c70aa510c6

	measure 'Target Channel' = "Email"
		description: DAX: "Email"
		lineageTag: 4c085338-2ba2-48db-9c48-bbcb48c87abc

	column campaign_id
		dataType: int64
		lineageTag: 38a3436d-ab67-41f1-8d70-f15564f6ab0d
		summarizeBy: sum
		sourceColumn: campaign_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: be043b7c-d5d7-4a75-9003-79724bfd99ea
		summarizeBy: none
		sourceColumn: campaign_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: fc3101f0-22b3-48ac-b9f3-30503c2006bc
		summarizeBy: none
		sourceColumn: channel
		description: String column.

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 09c61c96-bcb5-49c9-9493-a92fb557aec0
		summarizeBy: none
		sourceColumn: start_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a346b033-12a5-41d7-b84d-6cb24c414852
		summarizeBy: none
		sourceColumn: end_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: b049dfc9-a479-4550-b764-d9b755043224
		summarizeBy: sum
		sourceColumn: budget
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: #,0.00
		lineageTag: 339e20c5-e760-4390-8115-9e980005129c
		summarizeBy: sum
		sourceColumn: spend
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column target_audience
		dataType: string
		lineageTag: 4bcdf884-f455-4fd7-8119-8ed4399d0d8f
		summarizeBy: none
		sourceColumn: target_audience
		description: String column.

		annotation SummarizationSetBy = Automatic

	column creative_url
		dataType: string
		lineageTag: 5e29fb38-23e7-4c22-a66e-28f5c614fd48
		summarizeBy: none
		sourceColumn: creative_url
		description: String column.

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 6925082d-a4bf-47a7-8c49-23f0c4a47bec
		summarizeBy: none
		sourceColumn: utm_source
		description: String column.

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: 7b79eee0-bb6d-43c5-8413-3d554a860cd8
		summarizeBy: none
		sourceColumn: utm_medium
		description: String column.

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: 1bfb33d9-8c61-41e0-9e4a-a41a8593fab0
		summarizeBy: none
		sourceColumn: utm_campaign
		description: String column.

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 29978d68-981e-480d-b2bd-506a727ff6ac
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 0ef7645e-5fea-474f-ab35-b957306d5a1d
		summarizeBy: none
		sourceColumn: status
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Email Domain' = MID(LOOKUPVALUE(Leads[email], Leads[campaign_id], Campaigns[campaign_id]), FIND("@", LOOKUPVALUE(Leads[email], Leads[campaign_id], Campaigns[campaign_id])) + 1, LEN(LOOKUPVALUE(Leads[email], Leads[campaign_id], Campaigns[campaign_id])))
		dataType: string
		lineageTag: dc68d342-ca7d-4f41-be19-897b8494db55
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'First Name' = LEFT(LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id]), FIND(" ", LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id])) - 1)
		dataType: string
		lineageTag: 89a7afc9-628d-42a0-840b-e470c516045f
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Last Name' = MID(LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id]), FIND(" ", LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id])) + 1, LEN(LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id])))
		dataType: string
		lineageTag: 432eb66d-498e-497d-b6f0-d522ea681227
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Name Length' = LEN(LOOKUPVALUE(Leads[lead_name], Leads[campaign_id], Campaigns[campaign_id]))
		dataType: int64
		lineageTag: 51625813-6971-481c-a920-dd2d8be6ce47
		summarizeBy: none
		description: Calculated column (Int64).

		annotation SummarizationSetBy = Automatic

	column 'Clean Phone' = TRIM(SUBSTITUTE(SUBSTITUTE(LOOKUPVALUE(Leads[phone], Leads[campaign_id], Campaigns[campaign_id]), "-", ""), " ", ""))
		dataType: string
		lineageTag: 8cada52a-6353-4dbe-8b9c-74e718e2fe29
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Phone Last 4' = RIGHT(LOOKUPVALUE(Leads[phone], Leads[campaign_id], Campaigns[campaign_id]), 4)
		dataType: string
		lineageTag: 67655fc6-e06a-4f1f-86f5-0a10e66d3f93
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Campaign Code' = UPPER(LEFT('Campaigns'[channel], 3)) & "-" & FORMAT('Campaigns'[campaign_id], "0") & REPT(" ", 5 - LEN(FORMAT('Campaigns'[campaign_id], "0")))
		dataType: string
		lineageTag: 6dcf2723-280c-4d36-8148-557905b649c9
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Is Enterprise'
		dataType: boolean
		lineageTag: 634fb41f-1da4-4ab1-afc0-234f6662d7e6
		summarizeBy: none
		sourceColumn: 'Is Enterprise'
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column 'Has Valid UTM' = /* REGEXP_MATCH: complex regex "^[a-z0-9_-]+$" — verify manually */ CONTAINSSTRING('Campaigns'[utm_campaign], "^[a-z0-9_-]+$")
		dataType: boolean
		lineageTag: 2ef09c63-924e-4147-8cc0-c8a4ea31ef79
		summarizeBy: none
		description: Calculated column (Boolean).

		annotation SummarizationSetBy = Automatic

	column 'Clean URL' = /* REGEXP_REPLACE("https?://"): complex regex — verify manually */ SUBSTITUTE('Campaigns'[creative_url], "https?://", "")
		dataType: string
		lineageTag: 6d6c0546-5a98-45b3-b8c3-6b09167e38b2
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Campaign Year'
		dataType: dateTime
		lineageTag: 861ee1dd-f530-457d-81f9-4fcb3ed9bb38
		summarizeBy: none
		sourceColumn: 'Campaign Year'
		description: Datetime column.

		annotation SummarizationSetBy = Automatic

	column 'Start Month'
		dataType: int64
		lineageTag: b82d285e-bac0-4051-a1db-2d444d27d395
		summarizeBy: none
		sourceColumn: 'Start Month'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT('Campaigns'[start_date], "MMMM")
		dataType: string
		lineageTag: 5ca0bc3e-511c-4f40-8bb5-cf5c82cdf148
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Campaign Days'
		dataType: int64
		lineageTag: 2b6c9154-add3-480f-8b0f-a5915ed1e4a6
		summarizeBy: none
		sourceColumn: 'Campaign Days'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column 'Budget Band' = INT('Campaigns'[budget] / 1000) * 1000
		dataType: int64
		lineageTag: fd2809ae-d03a-48d5-99cf-086d7e3a1aff
		summarizeBy: none
		description: Calculated column (Int64).

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns-f142a5d3-395b-4ffa-8204-022a6bbbd764' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = try
				
				        let
				
				            _src = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				
				            _nav = _src{[Schema="marketing_db", Item="Campaigns"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"campaign_id", "campaign_name", "channel", "start_date", "end_date", "budget", "spend", "target_audience", "creative_url", "utm_source", "utm_medium", "utm_campaign", "region", "status"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"campaign_id", "Campaign ID"}, {"campaign_name", "Campaign Name"}, {"channel", "Channel"}, {"start_date", "Start Date"}, {"end_date", "End Date"}, {"budget", "Budget"}, {"spend", "Spend"}, {"target_audience", "Target Audience"}, {"creative_url", "Creative URL"}, {"utm_source", "UTM Source"}, {"utm_medium", "UTM Medium"}, {"utm_campaign", "UTM Campaign"}, {"region", "Region"}, {"status", "Status"}}),
				    #"Added Is Enterprise" = Table.AddColumn(#"Renamed Columns", "Is Enterprise", each Text.Contains([target_audience], "Enterprise"), type logical),
				    #"Added Campaign Year" = Table.AddColumn(#"Added Is Enterprise", "Campaign Year", each #date(Date.Year([start_date]), 1, 1), type datetime),
				    #"Added Start Month" = Table.AddColumn(#"Added Campaign Year", "Start Month", each Date.Month([start_date]), Int64.Type),
				    #"Added Campaign Days" = Table.AddColumn(#"Added Start Month", "Campaign Days", each Duration.Days([end_date] - [start_date]), Int64.Type),
				    Result = #"Added Campaign Days"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 29 columns and 11 measures: campaign_id, campaign_name, channel, start_date, end_date, budget, spend, target_audience, ... (29 columns total).

