table Leads
	lineageTag: dc566606-3890-409b-8afb-97d6fff7e007
	description: Contains 12 columns: lead_id, campaign_id, lead_name, email, phone, company, job_title, created_date, ... (12 columns total).

	column lead_id
		dataType: int64
		lineageTag: be04d6b9-e701-4c91-a50a-8d6a9b9c66ac
		summarizeBy: sum
		sourceColumn: lead_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		lineageTag: 8ab6ef48-fce9-4ccc-bd50-52ccba05ae0d
		summarizeBy: sum
		sourceColumn: campaign_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column lead_name
		dataType: string
		lineageTag: 42708f3e-a7fe-4b14-b0e9-c1d1619252fb
		summarizeBy: none
		sourceColumn: lead_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 0fe20a2c-ddef-458c-a2ef-0839bdce30f4
		summarizeBy: none
		sourceColumn: email
		description: String column.

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 6300e3d8-3a8f-4206-8f42-76e804584093
		summarizeBy: none
		sourceColumn: phone
		description: String column.

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 40c08158-75c6-4e90-a911-0124f2c62863
		summarizeBy: none
		sourceColumn: company
		description: String column.

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: 6c442120-3b94-4234-9575-c58166c3375b
		summarizeBy: none
		sourceColumn: job_title
		description: String column.

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d6aa67d4-76aa-4e64-b72c-dd6117e75001
		summarizeBy: none
		sourceColumn: created_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column deal_value
		dataType: double
		formatString: #,0.00
		lineageTag: 496eb276-cc2a-4ffa-abad-9aa3ed714268
		summarizeBy: sum
		sourceColumn: deal_value
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column lead_source
		dataType: string
		lineageTag: 41f57894-d5d9-42bd-8500-291990003d43
		summarizeBy: none
		sourceColumn: lead_source
		description: String column.

		annotation SummarizationSetBy = Automatic

	column lead_status
		dataType: string
		lineageTag: 89567b0e-e991-4660-bbd2-65782e187aaa
		summarizeBy: none
		sourceColumn: lead_status
		description: String column.

		annotation SummarizationSetBy = Automatic

	column engagement_score
		dataType: double
		formatString: #,0.00
		lineageTag: ebfe6870-64e3-4b4b-97b7-3df9e1afb0ac
		summarizeBy: sum
		sourceColumn: engagement_score
		description: Double column.

		annotation SummarizationSetBy = Automatic

	partition 'Leads-ffda7111-4cfb-494a-861b-a7f5bca407a1' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = try
				
				        let
				
				            _src = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				
				            _nav = _src{[Schema="marketing_db", Item="Leads"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"lead_id", "campaign_id", "lead_name", "email", "phone", "company", "job_title", "created_date", "deal_value", "lead_source", "lead_status", "engagement_score"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"lead_id", "Lead ID"}, {"campaign_id", "Campaign ID"}, {"lead_name", "Lead Name"}, {"email", "Email"}, {"phone", "Phone"}, {"company", "Company"}, {"job_title", "Job Title"}, {"created_date", "Created Date"}, {"deal_value", "Deal Value"}, {"lead_source", "Lead Source"}, {"lead_status", "Lead Status"}, {"engagement_score", "Engagement Score"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: lead_id, campaign_id, lead_name, email, phone, company, job_title, created_date, ... (12 columns total).

