table Leads
	lineageTag: f0435462-c785-4ef8-8da3-77cc9c958939

	column lead_id
		dataType: int64
		lineageTag: f69cbfef-1797-4c47-8ae3-5b791e2f87c8
		summarizeBy: sum
		sourceColumn: lead_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		lineageTag: 7b73e2d7-a3fb-42af-8d1e-d9e4b0ad1046
		summarizeBy: sum
		sourceColumn: campaign_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column lead_name
		dataType: string
		lineageTag: 40ec6fd1-2170-4457-a7ad-c34ba2d7a48d
		summarizeBy: none
		sourceColumn: lead_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 4cb9bd9f-d050-4c49-9913-02d3ec68c639
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: c6da34ad-23dc-429b-8b15-354c9300cf1b
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 2b919954-c62a-4c88-bb8f-4aafed4217ee
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: cbd3507e-bf47-4f00-858e-0f264f1d0e19
		summarizeBy: none
		sourceColumn: job_title

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: General Date
		lineageTag: cd69a896-6eb0-4c93-96e2-86a7dec75e1b
		summarizeBy: none
		sourceColumn: created_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column deal_value
		dataType: double
		formatString: #,0.00
		lineageTag: fcd3db25-b213-4f64-8840-ac28c7ea6765
		summarizeBy: sum
		sourceColumn: deal_value

		annotation SummarizationSetBy = Automatic

	column lead_source
		dataType: string
		lineageTag: 6eaeb66b-8d3b-4283-9276-08c131000717
		summarizeBy: none
		sourceColumn: lead_source

		annotation SummarizationSetBy = Automatic

	column lead_status
		dataType: string
		lineageTag: 327c3dba-83e3-4801-a29f-5ba66aecdd95
		summarizeBy: none
		sourceColumn: lead_status

		annotation SummarizationSetBy = Automatic

	column engagement_score
		dataType: double
		formatString: #,0.00
		lineageTag: 14fa6b18-d935-4ea0-8389-774d8bf1bebf
		summarizeBy: sum
		sourceColumn: engagement_score

		annotation SummarizationSetBy = Automatic

	partition 'Leads-c430bfd1-0e88-4b6b-b9a2-abda288c9a38' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = try
				
				        let
				
				            _src = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				
				            _nav = _src{[Schema="marketing_db", Item="Leads"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"lead_id", "campaign_id", "lead_name", "email", "phone", "company", "job_title", "created_date", "deal_value", "lead_source", "lead_status", "engagement_score"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"lead_id", "Lead ID"}, {"campaign_id", "Campaign ID"}, {"lead_name", "Lead Name"}, {"email", "Email"}, {"phone", "Phone"}, {"company", "Company"}, {"job_title", "Job Title"}, {"created_date", "Created Date"}, {"deal_value", "Deal Value"}, {"lead_source", "Lead Source"}, {"lead_status", "Lead Status"}, {"engagement_score", "Engagement Score"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: lead_id, campaign_id, lead_name, email, phone, company, job_title, created_date, ... (12 columns total).

