table Leads
	lineageTag: 57651199-5a74-4d44-88f9-bb182db88b1d

	column lead_id
		dataType: int64
		lineageTag: 3286fe41-88b9-4078-842e-46d07f24a9d8
		summarizeBy: sum
		sourceColumn: lead_id

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		lineageTag: 3285eb4f-6f4e-4ebf-8c38-d142092c17b7
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column lead_name
		dataType: string
		lineageTag: 93d1688b-748d-4551-a4c3-547a3a645a47
		summarizeBy: none
		sourceColumn: lead_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 9f2ade60-6c4d-44f8-9baa-3db1d204f5cc
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: a234b705-0541-4ccb-ac25-5041f75e5d28
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 9cd893c1-82c4-4c23-8b3e-99e26bfbd47d
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: e0bd0e48-3ab4-4fc9-98f4-fc0912ec36db
		summarizeBy: none
		sourceColumn: job_title

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: General Date
		lineageTag: faffd0d0-e94a-49c7-bd84-2d5cc5d4167e
		summarizeBy: none
		sourceColumn: created_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column deal_value
		dataType: double
		formatString: #,0.00
		lineageTag: 76be6cec-e607-4812-951b-bd9546b517b5
		summarizeBy: sum
		sourceColumn: deal_value

		annotation SummarizationSetBy = Automatic

	column lead_source
		dataType: string
		lineageTag: a370f2be-7c6e-40fb-9529-925027ce037d
		summarizeBy: none
		sourceColumn: lead_source

		annotation SummarizationSetBy = Automatic

	column lead_status
		dataType: string
		lineageTag: 7ae5c716-8b9d-46ab-baea-1267be9b5ee8
		summarizeBy: none
		sourceColumn: lead_status

		annotation SummarizationSetBy = Automatic

	column engagement_score
		dataType: double
		formatString: #,0.00
		lineageTag: f25ad6a8-cb10-48b1-bf5f-a1f00b86ad42
		summarizeBy: sum
		sourceColumn: engagement_score

		annotation SummarizationSetBy = Automatic

	partition 'Leads-ec9d1604-c155-4513-8ea2-f405e7e2d066' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = try
				
				        MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db")
				
				    otherwise
				
				        #table({"lead_id", "campaign_id", "lead_name", "email", "phone", "company", "job_title", "created_date", "deal_value", "lead_source", "lead_status", "engagement_score"}, {}),
				    #"Leads Table" = Source{[Schema="marketing_db", Item="Leads"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Leads Table", {{"lead_id", "Lead ID"}, {"campaign_id", "Campaign ID"}, {"lead_name", "Lead Name"}, {"email", "Email"}, {"phone", "Phone"}, {"company", "Company"}, {"job_title", "Job Title"}, {"created_date", "Created Date"}, {"deal_value", "Deal Value"}, {"lead_source", "Lead Source"}, {"lead_status", "Lead Status"}, {"engagement_score", "Engagement Score"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

