table Leads
	lineageTag: aedb610e-37df-4961-a424-b857bdf7a53b
	description: Contains 12 columns: lead_id, campaign_id, lead_name, email, phone, company, job_title, created_date, ... (12 columns total).

	column lead_id
		dataType: int64
		lineageTag: c1172ae8-8dc7-4e0c-b3e1-67d613f4565f
		summarizeBy: sum
		sourceColumn: lead_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		lineageTag: a48301e7-8e13-4508-a21d-05f9950244b7
		summarizeBy: sum
		sourceColumn: campaign_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column lead_name
		dataType: string
		lineageTag: d790ff7d-f47c-485e-9b2b-4497553c2ef7
		summarizeBy: none
		sourceColumn: lead_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: ac13c292-a9bf-4e43-bdb0-2cdd99921cb9
		summarizeBy: none
		sourceColumn: email
		description: String column.

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: f1ca6763-69a9-4f3a-b007-64e06e47ef20
		summarizeBy: none
		sourceColumn: phone
		description: String column.

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 247eb139-d7ee-4256-a031-5350e90e1d76
		summarizeBy: none
		sourceColumn: company
		description: String column.

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: d417b1f9-b7a9-4ba2-bc37-f6ee4cfa8d77
		summarizeBy: none
		sourceColumn: job_title
		description: String column.

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 59d8b665-c549-4f10-af2e-74a67babe334
		summarizeBy: none
		sourceColumn: created_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column deal_value
		dataType: double
		formatString: #,0.00
		lineageTag: ba461678-d5dc-4f86-a772-908026f9002f
		summarizeBy: sum
		sourceColumn: deal_value
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column lead_source
		dataType: string
		lineageTag: b0c010a6-8637-48da-a41a-4ed718dbedb2
		summarizeBy: none
		sourceColumn: lead_source
		description: String column.

		annotation SummarizationSetBy = Automatic

	column lead_status
		dataType: string
		lineageTag: 780a1ffd-bc32-427c-8b15-e53aec6e8991
		summarizeBy: none
		sourceColumn: lead_status
		description: String column.

		annotation SummarizationSetBy = Automatic

	column engagement_score
		dataType: double
		formatString: #,0.00
		lineageTag: 4959f31e-2d72-41af-860e-a641e75db6d7
		summarizeBy: sum
		sourceColumn: engagement_score
		description: Double column.

		annotation SummarizationSetBy = Automatic

	partition 'Leads-36737144-276f-420f-bceb-2be4a98ba1b1' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = try
				
				        let
				
				            _src = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				
				            _nav = _src{[Schema="marketing_db", Item="Leads"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"lead_id", "campaign_id", "lead_name", "email", "phone", "company", "job_title", "created_date", "deal_value", "lead_source", "lead_status", "engagement_score"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"lead_id", "Lead ID"}, {"campaign_id", "Campaign ID"}, {"lead_name", "Lead Name"}, {"email", "Email"}, {"phone", "Phone"}, {"company", "Company"}, {"job_title", "Job Title"}, {"created_date", "Created Date"}, {"deal_value", "Deal Value"}, {"lead_source", "Lead Source"}, {"lead_status", "Lead Status"}, {"engagement_score", "Engagement Score"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: lead_id, campaign_id, lead_name, email, phone, company, job_title, created_date, ... (12 columns total).

