table 'Min Budget'
	lineageTag: f589bfa2-726f-4269-a647-e95bf8982f46

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: c5d90f29-0b71-4780-869a-302507d02414

	column Value
		dataType: double
		lineageTag: 8fa56729-7053-4d77-93fd-b60f80704809
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-61146ed3-149f-4c54-bdd2-7425ecc742d1' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

