table 'Min Budget'
	lineageTag: 1d11eee2-1fed-405b-9799-9462dac34b94

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 6982e73c-5c4b-4b91-82c9-1e7fe02f3a44

	column Value
		dataType: double
		lineageTag: 5409461d-6aa4-440a-bd73-5162a3b2bfa0
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-9b752cea-ffbd-49aa-b7c2-81b614d4153f' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

