table 'Min Budget'
	lineageTag: 09447183-35ea-4bd1-8c88-6cb5a6e7b740

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 4a4106ca-b124-4fe6-afb5-3329d7da388b

	column Value
		dataType: double
		lineageTag: aeea309d-dda1-4374-827a-ae0faeccaeee
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-ea94411a-de7b-408a-a248-3e2d1b221c9d' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

