table 'Min Budget'
	lineageTag: 50a86410-94c6-48a2-a5c6-d1d0a3b17202

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 30d2ed66-55b2-4772-846b-532a9943a6a6
		annotation Copilot_Description = DAX: SELECTEDVALUE('Min Budget'[Value], 5000)

	column Value
		dataType: double
		lineageTag: 57b933d1-67fa-4f11-8a76-df76dac8b029
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-49594195-5073-40dc-8d17-ecec3650d053' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

