table 'Min Budget'
	lineageTag: e658ecf5-bbd7-4301-9415-4d2d2ef1f33c

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: bc9bd0ed-bdde-4c6b-8984-4851d92850f3

	column Value
		dataType: double
		lineageTag: 88a41002-0d02-4534-8bba-dbca31f437df
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-9b86ca3d-b7c7-408d-bcda-1c7ea9890e69' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

