table 'Min Budget'
	lineageTag: 314f1819-0626-410f-9983-64cbbad70d16

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 3a1c6153-cf9a-4675-9656-31d852f17468

	column Value
		dataType: double
		lineageTag: 360a8767-a4d2-47a8-b676-63b55e315cd4
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-595f0e60-923f-48c9-b570-efbc8d1b2076' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

