table 'Min Budget'
	lineageTag: aef21805-e184-4541-909f-2b75c047ce18
	description: Contains 1 columns and 1 measures: Value.

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		description: DAX: SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 0183689a-4b99-41c6-ac90-aba161408b74

	column Value
		dataType: double
		lineageTag: f437abff-6757-4941-a052-673d350df144
		summarizeBy: none
		sourceColumn: Value
		description: Double column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-4c0fea3d-f81a-4616-8022-d2f68e749b04' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

