table 'Min Budget'
	lineageTag: 134ca9bc-1f7d-4c8b-b9b3-09dea295f5d5

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: a15810c7-907e-4a5d-b675-f189cf0495a4

	column Value
		dataType: double
		lineageTag: 7f371ed5-e2a2-4552-842d-28652d542946
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-c3041ec4-7d2b-46b6-b132-ba57b9ef8cba' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

