table 'Min Budget'
	lineageTag: 2b6dc80a-8d8b-422d-9a6a-6f4e5705d7ff

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 5765c7df-1b72-4e07-9202-71ae53070f6f

	column Value
		dataType: double
		lineageTag: 2fd977a4-4e59-4377-8893-e5cba1647aa1
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-41a5745a-e161-4f67-8734-464a66cc87d1' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

