table Calendar
	lineageTag: 776a2b8e-3195-454c-a96e-9d98b18ca8d4

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9e2f318b-2221-4729-94f5-34c5e5576fd4

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6f0fffda-24e6-45b6-af74-d50aefc674b7

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: b55ae0fb-e9e8-498c-a3d3-cec0bdb5ba4b

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2c792a86-a1ab-4e74-a745-954a2e8a3978
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5eef4b75-85b2-46c3-872d-82ac72557b65
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: daf83ddb-87d2-48a2-878b-42e3f5eb0ea8
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4f7d60a3-fa37-434a-bc47-cd377670615b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2c3d1225-3107-4584-b930-190e0c57fcca
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 40517b42-7d40-474a-a4e8-1108c6f5f817
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d16bd5d9-181e-4389-b8c6-0dc100dae8fd
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d345aa29-ceec-420f-adfd-73754d26b6d9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7e0392d7-76ea-405b-8b6d-128dd38ddbc8

		level Year
			ordinal: 0
			column: Year
			lineageTag: c8cc3ec5-0e47-4dcb-a693-dcf23d8f9b30

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: edadb952-301b-4573-88a5-76a4e9dcf835

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9f999ae5-6d2b-4bc3-8179-129e500b0d04

		level Day
			ordinal: 3
			column: Day
			lineageTag: 09920500-ab63-430a-a130-a4404a6a24e9


	partition 'Calendar-7d723a22-9814-4f11-8faa-543ae89557e1' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

