table 'Base Salary'
	lineageTag: 825dcbf6-baab-40aa-91aa-ed7ccb6d40a3

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: f8bba94d-f40a-4ea1-8a41-615bd4a23391

	column Value
		dataType: int64
		lineageTag: 9143377d-dd6c-4e99-bc88-8145f478ac49
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-a03f6591-43f6-4871-8271-2d2bd91e91b4' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

