table 'Base Salary'
	lineageTag: a8f46d6a-6512-44dd-ace9-1b62106510a3

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: f8d96e9c-c37a-4d3d-bcb4-b3dfb0620554

	column Value
		dataType: int64
		lineageTag: b6fced11-3532-4b5c-b310-0755c3f26e3a
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-9078beaa-c4c3-4399-8bff-cb30a629bfbc' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

