table Calendar
	lineageTag: 15f99f6d-26bd-44d2-a79d-ff118ceb26ef

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8aa9c3ff-6fcc-419b-8d78-af02780e211c
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 32ed1f11-6d93-4de3-b8b7-284bd2728f94
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 6f1da5dc-961d-4895-80a5-b0e85715bc4e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 19348c44-a068-48ad-8c31-86aca6548210
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 33d6de12-0af9-4043-b3d9-93b9ef729ce9
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 254c28c4-fc70-4ede-8afb-67f99387311e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7dea9be3-e664-43ee-8227-b58d272ec8d6
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7456731d-3629-493d-ab72-6bae460373b6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 04089eff-3fb2-43d9-a9e1-f0c2297e0da3

		level Year
			ordinal: 0
			column: Year
			lineageTag: b7b2d540-c44f-4dcc-b339-f277b68c726a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 242ee2d8-b689-4c2f-88a3-1802d156badb

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 82532c4c-f7fd-41fe-bb5f-c4f269bbddd3

		level Day
			ordinal: 3
			column: Day
			lineageTag: b7b701a4-1cdd-4d00-a276-9bb3fab71d4f


	partition 'Calendar-dd818e04-b9b9-4a20-b9bc-ee20bcaa062a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

