table Calendar
	lineageTag: 76ddf026-6fa3-4251-b7fa-3af9e5551695

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: de728563-b55d-4c38-bbe5-827e576d48b2
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 43a2b3f0-041e-4600-a501-da127c63cb58
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 034a8058-19eb-483c-86b4-ee73a6f0df15
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 10fe6a6a-9406-45c2-85d1-44d90681c826
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e711165b-9f8c-4112-a17f-048f8d18383e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: c399ae92-d9a0-4ed4-9683-3c24f89176fc
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 750649ed-5aea-4704-8001-478a635f14e7
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 756d090e-fb72-492a-b38a-fbb361e44df4
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3a52f8ff-6259-406d-af9d-3a09206643c0

		level Year
			ordinal: 0
			column: Year
			lineageTag: a44938bd-cbe2-48bd-9452-8414e77112e7

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 8908d901-979f-42c7-8ace-d74b71df36de

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 5f0b491c-516a-4584-afde-34e5d0003e63

		level Day
			ordinal: 3
			column: Day
			lineageTag: b9521a8d-c77c-4a4f-a68a-84dcacbe7c40


	partition 'Calendar-1b49b0e0-efe0-43bc-ac35-56f62c337877' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

