table 'Churn Rate'
	lineageTag: 2dc1635a-b2dc-4005-a42b-37dd6263e035

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: 17d235b0-3f0a-4e74-b828-e0538ba2136a

	column Value
		dataType: double
		lineageTag: 1dc763fb-e5d5-46f6-8b09-a9aecb63fc12
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-491cbac2-5513-406b-98a3-27d3b3a9592e' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

