table 'Commission Rate'
	lineageTag: 8a49cf14-0373-4393-8449-f9f6d5bb2bc8

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: 5b23e605-df2f-4b20-802f-58574422c1f2

	column Value
		dataType: double
		lineageTag: 3943c231-92b2-4cc9-b400-a7d583916b43
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-92e9eb02-97ef-4f2b-8b7b-8fe74fb95873' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

