table 'New Business Growth'
	lineageTag: 59b474b0-003d-4bb2-86f0-c3497785a01f

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: 403aa49e-4017-4db2-87f0-158b2b8e2789

	column Value
		dataType: double
		lineageTag: a05c000d-0f4c-422f-8cc2-bf7926c02395
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-ae6b902a-dcef-4270-ac38-989276e1bc78' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

