table 'New Quota'
	lineageTag: ce2d2fc7-4fd1-4d19-833d-c839646bf9dc

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: 8bbdb451-d5d1-4227-9183-1785ef3548bc

	column Value
		dataType: int64
		lineageTag: 9179acfc-dba4-441e-95ca-7c05e7fa3f13
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-a47ab5c5-4db9-4634-bd25-186c7e5af10e' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

