table 'Sort by'
	lineageTag: 43d8a244-94a7-4e13-88af-05f7c02c6a19

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: 08be6ddf-2b74-4907-87bc-ec6e12053ad5

	column Value
		dataType: string
		lineageTag: 0efadac5-e15d-4228-b66f-3d7c03f17912
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-d07786de-7454-402d-8ebe-4f602ba85bc3' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

