table State
	lineageTag: 347a377f-aac2-4b51-a04c-b96647c869a8

	measure State = SELECTEDVALUE('State'[Value], "Alabama")
		lineageTag: c874547a-3ed7-4806-b1b7-1a005b9c09e6

	column Value
		dataType: string
		lineageTag: b06f2051-3317-4ff9-a633-2405e31bb848
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'State-1655c39c-33fd-427f-ae6d-d6eeef57f9ed' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""Alabama""}, {""Arizona""}, {""Arkansas""}, {""California""}, {""Colorado""}, {""Connecticut""}, {""Delaware""}, {""District of Columbia""}, {""Florida""}, {""Georgia""}, {""Idaho""}, {""Illinois""}, {""Indiana""}, {""Iowa""}, {""Kansas""}, {""Kentucky""}, {""Louisiana""}, {""Maine""}, {""Maryland""}, {""Massachusetts""}, {""Michigan""}, {""Minnesota""}, {""Mississippi""}, {""Missouri""}, {""Montana""}, {""Nebraska""}, {""Nevada""}, {""New Hampshire""}, {""New Jersey""}, {""New Mexico""}, {""New York""}, {""North Carolina""}, {""North Dakota""}, {""Ohio""}, {""Oklahoma""}, {""Oregon""}, {""Pennsylvania""}, {""Rhode Island""}, {""South Carolina""}, {""South Dakota""}, {""Tennessee""}, {""Texas""}, {""Utah""}, {""Vermont""}, {""Virginia""}, {""Washington""}, {""West Virginia""}, {""Wisconsin""}, {""Wyoming""}})

	annotation PBI_ResultType = Table

