table Calendar
	lineageTag: 6cdfed0e-60bd-4a41-b3df-5d8c72d94294

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b98b34b7-9907-47ee-88bd-6ede6a56c4f2
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9566c4e5-f902-49b3-b0b3-01dca2c518cd
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4983f554-e61b-416d-8e5a-f535432c1b18
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b3890f7b-46c5-41dd-a87d-41fc8cf98c2b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c1c45db4-3784-4713-a5bf-78bbca6554d7
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 2eacbc75-48bf-4c5a-918b-e6cdef8a9ae7
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: bacecb47-d86a-40a5-bd01-b6974515487d
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: cb59c12e-875e-455f-a83d-e3a1a08228fa
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 60da4df2-1aba-4753-bd45-e3cc369b2f6f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 88de240e-6d91-486f-b92d-646153a6a56a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c6c159e3-027a-46b4-b7df-3ff54d60ce0d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 846739cb-b70e-4b99-8f5a-6bf509e47e51

		level Day
			ordinal: 3
			column: Day
			lineageTag: d2b07ffc-e2b3-4d6c-a73e-6aec6c4428c4


	partition 'Calendar-38acdda6-13f1-48b0-b05a-faed28b2411b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

