table 'Base Salary'
	lineageTag: 803bf6af-fc2e-47ca-83dd-06a43f2301bf

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: 5cb37826-7c7f-443e-b9d8-b6f16c163daf

	column Value
		dataType: int64
		lineageTag: 43032888-932f-4b0d-a759-ddae86b382ca
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-cf2ba68b-2be8-45af-86ae-adf9955b2395' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

