table Calendar
	lineageTag: 2194e86a-0d59-4651-b6ea-0c86cdaa4084

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 98acf72a-9925-4512-829c-3341298af0a6
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 960b1493-1b9f-44f1-84a1-4b85d71c6925
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 63ac63ae-4dbc-4859-8f8a-f81a7b88dcb4
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 8592f2a3-6f01-4f63-8dab-05ed90d16202
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2cb0ff6d-656a-4b06-a248-3fd2804639c4
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 84fcd463-b802-479b-a81e-77a0ad26f5d8
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 8995ea0e-0e18-40b9-baa5-0045f868b368
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7279a673-547d-4811-b589-2020fb25f010
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: efceaceb-30d1-4db6-8b1d-a9eec6e8899c

		level Year
			ordinal: 0
			column: Year
			lineageTag: 13be0e7d-d0c6-45a5-92ec-9b3ead8cb5fa

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 7b1ad96f-6171-41fd-8566-f2448636194f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 07705de5-5d9e-4702-9913-0b8fc3512cad

		level Day
			ordinal: 3
			column: Day
			lineageTag: cf58d2ba-0cc5-4775-a4f9-d66930058cdb


	partition 'Calendar-6cdd1305-4477-4838-bfa1-6d4e2dd12ea9' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

