table 'New Quota'
	lineageTag: f645beb0-b743-443b-a5df-95daee31782a

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: 5963c190-55aa-4752-af8b-c6cd192ac7ed

	column Value
		dataType: int64
		lineageTag: 8a7b99a6-4c58-4862-b7b4-2af52731a817
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-46e578df-7a4e-429b-882a-be1cb4d6c62a' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

