table 'New Business Growth'
	lineageTag: 7c2df494-b529-428b-a657-93623d65e8c9

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: 241f2908-47b5-4b42-b0d7-8123975ee4d6

	column Value
		dataType: double
		lineageTag: 075f5ad0-719a-48f9-8f0f-19fc699fe5d8
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-bfd98091-2f0d-4991-a3dc-14293ade9739' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

