table 'Sort by'
	lineageTag: be672e42-28e2-4e08-b448-bbb31a4efe39

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: eed935b7-9f32-4ea7-a4f5-bc6ca974e7ea

	column Value
		dataType: string
		lineageTag: 82560c6a-75cd-490a-841a-1f502bd9e8c5
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-d1586089-86af-499f-a273-ddb800991dcc' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

