table Calendar
	lineageTag: b7b4bca4-67b4-451d-94bd-2d5e37965719

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b8d3d673-6816-4235-bdd6-8f216cb2fe3c

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1d9c2f2b-2ff0-454d-9f91-9983008781b0

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 80c0f70d-7029-4759-a634-d990b81b7bf9

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: feec1bc1-6530-4ba5-9ba0-824da0353a58
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d46ede91-fbca-4cae-a44f-401fe3fa1751
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1b5922a4-7e2c-4c5d-91ab-9f36ccf143d4
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 6064ea88-f22f-483e-9f90-9bbd00cccb33
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 873084c7-260e-46f9-9292-d156bcf75b60
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ca07ab6a-ee84-44f7-9604-c9d47a939d7f
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 6c02fd0f-0635-4403-8433-abab5c6caf4e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f15cb1ee-d7ff-4eb8-978f-287516ff37aa
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 96fc4499-0524-44c9-a7b4-f4c176c62c08

		level Year
			ordinal: 0
			column: Year
			lineageTag: 313554b4-c5b9-49ee-8fb5-fb72bedd305b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 42073ff8-c852-4154-a22e-de4f0528bf00

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ad0f31de-e5d2-4575-bb3c-0d74b63aa7f2

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7635ac46-be83-4aaa-8525-2b249861fa3b


	partition 'Calendar-e999ea39-64ce-43dc-b81d-b15a8ca9357b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

