table 'Base Salary'
	lineageTag: 02294767-e4b8-4efd-b798-c022d21c6706

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: dfa3b218-ad7d-489c-975a-53235f457e5d

	column Value
		dataType: int64
		lineageTag: 7823e64e-8499-4bb5-9ae3-1f226aea15f2
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-8dbbe8ae-9c5b-453d-bcd6-71850345185e' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

