table 'Base Salary'
	lineageTag: b633cc93-e5ad-4d0f-a6b5-3de0b8b7d2cd

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: 7bda9af6-7a85-47f4-90cd-05be7d4b3065

	column Value
		dataType: int64
		lineageTag: 0b0e7cf3-2481-4cb7-be72-33cd7c8355d1
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-bf00adc2-08d0-4f0b-8fa7-7fa1b0824419' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

