table 'Base Salary'
	lineageTag: 25d77dda-7db9-4922-9a8c-59da96d5a5cf

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: 8a285e39-e1c9-45fc-bc8f-635c9f953d07

	column Value
		dataType: int64
		lineageTag: d5467194-dfc5-471b-8bd7-743e447e4629
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-cfb323de-3944-4bab-9391-13f03b3faae3' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

