table Calendar
	lineageTag: 946a2d22-6778-4890-8bdf-c0d83e55a6b2

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c30cba63-bcbc-43b9-93ba-2bf1e28416a7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e360373e-b65a-4c0e-a004-1e8dc60df046
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: afc70bed-81c6-4a90-8b9f-94441834110a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f68e1e10-6e25-4416-86fa-b81b4060563b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8a655ddb-1b88-4c40-818d-0d1e6e2aaa30
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 03157f0c-2dd7-4aec-85b8-f503748484ed
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 0baf10d3-e7cf-47e9-92dd-55ef419a10e6
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 3b02f977-e5e3-453f-972f-c185a2370019
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6a6168a8-6493-479d-9dbf-498a28de22d8

		level Year
			ordinal: 0
			column: Year
			lineageTag: e69208ed-9242-45aa-888a-3d0b7e93b110

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: fa4a3b62-ae3d-4b4b-bb0a-8bf8599789e3

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3d44c365-13c6-414e-9cac-1cc44a1aacb8

		level Day
			ordinal: 3
			column: Day
			lineageTag: 8657f94a-44a9-4fb3-947e-56b399834b18


	partition 'Calendar-0a2e53fe-f9f1-493d-9d9b-0d8cd5d6c78c' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

