table Calendar
	lineageTag: 0bb71ec9-70e7-4864-818c-5d0b8ce604ea

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 98626740-c72f-4b44-9268-034782cd3723
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 3336fda8-05ca-42cf-93c2-ba0cfe6b70c0
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e322e468-b1ce-4f59-911f-70f0bf4ec067
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 42f1aab9-68f2-496d-8066-62fa369f9220
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f66651bb-acd9-49f2-9e82-234b731cd423
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0296a01f-0c5e-4bc6-90de-50949d808724
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e6df250f-4c20-4e0b-8532-88c267abd18b
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 70070bc5-7932-4306-a8ea-51c8b7b7e9b0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f67ef30f-ccfe-4fa9-83e4-4c939fdecd15

		level Year
			ordinal: 0
			column: Year
			lineageTag: e29e1bfe-829a-43bc-b5db-1aafb2df6030

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 8ddee31a-9bfb-4be5-bb70-8228663bed48

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 73465173-f81c-49a8-b23d-97e4305f42ee

		level Day
			ordinal: 3
			column: Day
			lineageTag: 51f4f85c-7f14-40a3-b84e-d174e7301b3e


	partition 'Calendar-f0f41b9c-1d97-4b47-8081-45b6061b2802' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

