table Calendar
	lineageTag: 6d9d7601-97cc-454d-9d47-d5e3d53f1fc8

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2a42615b-f886-4278-a355-ad39f28632b7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 43634663-f2ae-4247-b00b-57fbe058352a
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 9f2fd7b4-9cb3-464b-9adb-4c2b1acd19ed
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 919cca96-6218-49ae-b48b-6c1467da34b3
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0b75f5e3-6f9a-45dc-afb6-94d4a67591f5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: c12c50f3-f678-4386-a454-a42adb1c2f67
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 25181f31-2a09-40c4-a129-20cc2fe6c2c8
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 19be942f-098b-4467-806c-b2deddecfed2
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5f07f068-7d9b-4b24-a783-c69e8b48d811

		level Year
			ordinal: 0
			column: Year
			lineageTag: da02586c-fc0d-4566-9b73-2529bb09d79d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b912d35f-8e6f-4dd0-bd7b-0a37e1e23b89

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1743250a-6176-4f9a-b8ae-b453ef4a7026

		level Day
			ordinal: 3
			column: Day
			lineageTag: 95aaeac2-9e4e-41be-9574-992a71541ac4


	partition 'Calendar-064cccbd-359b-4705-b31a-dd8839eb8e4e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

