table Calendar
	lineageTag: 6e844a38-9617-46c5-9bb8-420d775941fd

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bf49a652-3d94-4f67-b12e-4c3df5fdf978
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f173dffd-3e3b-4001-915a-62ab3cda6706
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c42b3b1b-cccb-43f8-b7a7-9fba954ba8be
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 617c1100-0c99-4947-ac49-3a1c40cac808
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: cabd54cd-7eb5-4ba0-b22a-df1f2866a60e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 6d390423-3193-4a65-855b-d28889011372
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 266eb5b0-748e-4179-ad5f-a775226a52da
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 3b83978f-e0f8-47cb-bb5a-b3abb481c96a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b16552d1-2625-431c-8025-39803d2ced4a

		level Year
			ordinal: 0
			column: Year
			lineageTag: f659e515-dd5d-4e4c-b887-c1b69e11d198

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: a063d458-43c8-49eb-8bd9-f7eab198be35

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c8c842d0-7575-4905-aa31-4c5b701fb2df

		level Day
			ordinal: 3
			column: Day
			lineageTag: edcd7b7e-b5b1-47e0-a3c7-b477e850e262


	partition 'Calendar-421a76ae-0909-42cc-b6ec-70ddd5b5f7cb' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

