table 'Churn Rate'
	lineageTag: b98d9f2c-6755-4a76-9f26-fb44288c02af

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: ce06cac3-ae2c-4b19-b5bc-cd42dbabf283

	column Value
		dataType: double
		lineageTag: 58a03de3-b035-42c3-89b7-60c97b3b1d66
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-3fa0a8b7-1286-43e4-a600-4be2eb81d487' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

