table 'Churn Rate'
	lineageTag: 0f796b90-e979-49d2-9585-9689a7972ff9

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: 70db5bc4-20f8-4a5b-b517-9892884998ed

	column Value
		dataType: double
		lineageTag: 14f9e50c-694e-45c0-a399-341ee8e06fb9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-f2cce408-4420-48f1-b7a8-a176cd77aaf2' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

