table 'Churn Rate'
	lineageTag: 377c69f1-1749-4231-a49f-a6043da5b48f

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: 4cbd3bb6-e45e-41d2-9981-6e3361eaa190

	column Value
		dataType: double
		lineageTag: f71a3910-7b63-400c-9913-cdc13ad46e08
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-877369e9-3702-451b-a547-5069303de8e2' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

