table 'Commission Rate'
	lineageTag: 197fb8f7-f7b7-4c02-9001-1aeca2c4cb71

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: 717b639c-5808-4cbf-ab6d-fadf479e54c1

	column Value
		dataType: double
		lineageTag: e08635c3-7832-40bc-91e3-beff2125b516
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-28c57cfb-79f8-4bcd-9b4b-423235d0613f' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

