table 'Commission Rate'
	lineageTag: 5fd69d15-6521-47fc-8f59-4af158dff06e

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: 9d65abdd-95cd-4187-9967-d98102143797

	column Value
		dataType: double
		lineageTag: 2180b477-c54e-497d-b4fd-3e2a0829f7bd
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-1533b382-be8b-4dec-9859-cffa79760176' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

