table 'Commission Rate'
	lineageTag: 5d0a0fb2-525e-4272-b15c-4046e82dc6ce

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: beda8a9d-c4ed-438a-8ef1-88d8717d5155

	column Value
		dataType: double
		lineageTag: cc817434-57ac-43a2-8d47-26c957c0bb12
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-add97696-2420-4b0c-b603-de499077730e' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

