table 'New Quota'
	lineageTag: 5e2179e8-8179-4742-912e-8b2eabea7894

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: 6ef3ba7e-d46d-4cda-b541-3c018194440b

	column Value
		dataType: int64
		lineageTag: 45e36a82-b6b2-4a01-a3c4-51b130a98265
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-70ef3e45-f962-4663-b7c1-85a249e877ef' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

