table 'New Quota'
	lineageTag: 33c5a1f7-7a43-4040-9792-1604497d2bf1

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: 6ca3c671-8f13-4ca6-9f2f-afe6b7a8c18f

	column Value
		dataType: int64
		lineageTag: f3bd1eaf-c206-42ca-925c-60b693b48070
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-48f7b1c4-547b-4536-a76e-469ed2b5b9e8' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

