table 'New Business Growth'
	lineageTag: a6f9e5f7-582d-42bf-9367-54156a96e456

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: ba8a5ba9-77f2-4e1a-b556-eddb97b7f85e

	column Value
		dataType: double
		lineageTag: 04f37729-4a49-491b-9930-c0aaef4c64d9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-02561aa1-f4cc-402a-9f1d-17440e872737' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

