table 'New Business Growth'
	lineageTag: 4e29c207-d0cd-49ac-aa8e-3c58101ab600

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: f921cebc-7112-44b5-92c8-a738668473b6

	column Value
		dataType: double
		lineageTag: 2eb85d40-33bd-4b20-be28-267e9b7c46c3
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-455a6643-3536-475b-b10f-fb7654672a5b' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

