table 'New Business Growth'
	lineageTag: 60f54fd7-d9b0-41f6-a8ee-08399807b836

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: 1f0831b7-5173-4871-b4fa-abf5cd47df8e

	column Value
		dataType: double
		lineageTag: 237ef3ae-82f3-4d14-875d-1980d1f38ee3
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-1969ae09-c08f-40f7-96f6-e9494e218851' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

