table 'New Quota'
	lineageTag: 7d411035-8f87-4535-9446-ac89e55f88bf

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: 2cc5c2b0-bbf2-4630-9b3b-adb3b7b6aba8

	column Value
		dataType: int64
		lineageTag: b7682989-d042-4e71-8535-2ce234e84b07
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-86af0b16-b332-4f2e-8db8-bbc2fe9e2bec' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

