table 'Sort by'
	lineageTag: 4f32a967-f228-42a4-a1f4-d1293e186b4e

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: 2f9ac919-f3d4-4d72-8901-be07f78f7ba1

	column Value
		dataType: string
		lineageTag: f4cc71ad-7a63-4219-bde5-bd31acf8c83b
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-a9267fdd-7674-41cd-ac4b-7a566c027787' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

