table 'Sort by'
	lineageTag: ae63bf34-3311-43e1-ac2f-8faa770ea9fd

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: d0900c15-15a0-4f67-87ab-3e19113aea12

	column Value
		dataType: string
		lineageTag: c8a272a8-eb2d-4370-8058-b0678f10dd1a
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-c8633463-660d-4908-84f0-a9101f8f1ee9' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

