table Calendar
	lineageTag: 09c8fbec-5c0f-4cf1-99a1-64d2e5b463f7

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 7438ab64-2b69-43cf-b436-6ff9d3fa8d7a
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 349c1cde-4618-45f4-a7d3-ee7f8c8b64b6
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 85829768-1713-4930-abb4-0d95abdbc448
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 447ecb89-a366-44d8-8357-7ffbd094c945
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8951de38-8e9e-42b8-884b-64974970475c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 168a3289-3a34-44eb-a4c0-ebb2951efcc7
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: babade8e-2415-4f94-b787-aaa4270e1c95
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 073b74d1-867f-48b1-a2fd-5fd2491c9812
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 79998cf5-c075-4d05-b095-78ced504d57f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 48d51a15-2d5b-4a69-b926-d7403534f232

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e380076a-a3f2-430b-9289-f3a83a41fbde

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3d9cd301-a59a-4593-8024-f12076dc037c

		level Day
			ordinal: 3
			column: Day
			lineageTag: bc20f7dc-4927-414a-8b9f-a72b5bb5f311


	partition 'Calendar-51205d63-d80a-4e11-a862-037bd0e91908' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

