table Calendar
	lineageTag: 8e64eb90-bd39-4393-863e-b0a3df1f0b2c

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: dcd970de-ff57-4e4f-90cd-7cc1414ef1d3

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ea67e091-2fd0-467f-9c06-555a295f492f

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 5301cb98-aeb0-4c6f-be6d-9ba310c9e7b4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6797033f-c259-4196-bbc5-64ffc5467b62
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ba4d24fe-3ea8-463b-bae8-5b6581b21848
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: bdfa7066-c0c9-4003-a29e-f92adce16092
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 28a494a2-b06b-442b-9438-fad7f1a6f8b2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d65d9f12-da23-4d34-9ba7-912382b23795
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 2bc7b409-069f-472c-961d-8d99809421e3
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 72357e41-7dfc-46fb-a228-54e9ffc7433b
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ad3319a1-e4fe-4458-b0fe-050fce5333b9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9be39334-6d23-4ead-bbc6-8d8ef862c379

		level Year
			ordinal: 0
			column: Year
			lineageTag: bb0b78f3-fd87-4406-babf-37428de75aba

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 23c5b354-a732-4ff3-ad0c-fb08d08c090e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 551a5bbc-6e9d-4028-a7eb-3cec95314245

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7688c960-798d-4c12-9305-9336b93380d7


	partition 'Calendar-a8298620-685f-436e-90e1-fc1dae17644b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

