table Calendar
	lineageTag: 2cff3d2d-12d7-4075-8624-daf45fb2754e

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 2f7f6d7f-9441-460c-9289-57286f13311e

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 93fe9260-5169-4b2f-b419-78bcba0e3bf1

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: f014ac87-43d9-4be7-89f3-bbe8b3571640

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9e571950-2e4f-4819-8a07-06258eee87ea
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 20baadd3-27d0-4772-983b-b56c2d28ed05
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b3665dad-a797-4a4a-a00f-4489ca7f6d5d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 8005b98b-c573-457d-90d3-f25520395077
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b58511b3-900a-45d7-ab65-87c987329973
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ee59063b-1197-420c-8a61-fe7d9e8fbe5d
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 0d74c6fb-3007-4aa9-8260-eee6ee4b0511
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 38190fd7-6861-43cf-9b9a-b8a136790e20
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 24942911-d061-4adb-b533-b76e0491dfcb

		level Year
			ordinal: 0
			column: Year
			lineageTag: acee616f-4da3-48c8-b5c9-6933bd3bcab4

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b3d45743-5189-4d4c-b89c-43721d7bbdff

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0a7fd341-03a1-4e9d-b791-c95c83feff11

		level Day
			ordinal: 3
			column: Day
			lineageTag: f0f60741-96cf-42a9-a95e-c4a31136023a


	partition 'Calendar-232d23f4-4532-4a68-aa1b-a3508bcb918d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

