table Orders
	lineageTag: 4fd64661-c7fe-488e-b8b8-ec52c8870613

	measure 'Profit Ratio' = SUM('Orders'[Profit])/SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2194bec5-05b1-407c-9ea7-669e5cbc14f8

	column 'Row ID'
		dataType: int64
		lineageTag: 99487e03-3441-428d-a8d5-5459afd901fe
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 7c354b49-5cde-4102-8f66-fd5007507dc0
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 52e8d9df-5fda-4dd4-b9ed-574a0efd0701
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: a2d9ed31-3346-49a8-b0da-ae32af9b6f4f
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 9c00a074-7cd6-4adc-b37a-5ec678e25a09
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: f8122c78-2304-4b09-ba17-035a27bfbb68
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: c121c929-ad2b-4b2c-8a60-cff9af89f249
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 16ea8b29-b7cb-4cd3-975e-e98e522e6976
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: bdfaadc2-562a-4663-972d-0fc534d5f4f3
		summarizeBy: none
		sourceColumn: 'Country/Region'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 6b183d7e-53fc-4be1-b816-39012c42caab
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b9555f33-c5cb-45c7-b47a-83292b5adfce
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: 98b6a42d-30c4-4f8d-9079-5cd5741cce15
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 9ac48168-7d49-49b8-b167-24184e62f104
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 2592b928-6e92-46fe-8f1c-d31a266daa2e
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 2184023b-e83f-4cef-9a51-35a4e02ec6bb
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 19cd7297-3780-4a66-83b0-8e88bfed6fa3
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 06558ab5-3314-41f1-bd31-cebe5e6c0d98
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 18e5918c-ef99-4862-b5bf-dd71cf6eec90
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: c0a7b630-9f98-4704-aba7-339d70827859
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: ba29212d-f8e9-42e2-b372-5b1c5464033b
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: eb64efcd-2485-4a0d-827f-1aea07eb9fce
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Profit (bin)'
		dataType: int64
		lineageTag: c9dcf589-6e71-4ad7-89fe-2fa4aad60d53
		summarizeBy: none
		sourceColumn: 'Profit (bin)'

		annotation SummarizationSetBy = Automatic

	column 'Top Customers by Profit'
		dataType: string
		lineageTag: 2aec9470-c194-4907-954c-0d50ddaeaf98
		summarizeBy: none
		sourceColumn: 'Top Customers by Profit'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: double
		lineageTag: 383c2282-aa54-416d-8fdc-6838a6245237
		summarizeBy: none
		sourceColumn: Manufacturer
		displayFolder: Bins

		annotation SummarizationSetBy = Automatic

	partition 'Orders-5120ac96-ccd5-4995-9034-04cae66ee0a6' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true)
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country/Region", "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"}, {}),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country/Region", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    #"Added Profit (bin)" = Table.AddColumn(#"Changed Types", "Profit (bin)", each [Profit], Int64.Type),
				    #"Added Top Customers by Profit" = Table.AddColumn(#"Added Profit (bin)", "Top Customers by Profit", each "", type text),
				    #"Added Manufacturer" = Table.AddColumn(#"Added Top Customers by Profit", "Manufacturer", each 0, type number),
				    Result = #"Added Manufacturer"
				in
				    Result

	annotation PBI_ResultType = Table

