table Rebounds
	lineageTag: b18abd52-aea8-425f-94a1-53d736be8dd1

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 9ca7c529-a8bd-4b55-9683-8e0bd1292e08

	column Value
		dataType: double
		lineageTag: a9adb2df-621f-4b3d-84c3-3bebc7ae1730
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-6a1c3917-d25a-47b6-9905-ad273fc2a0ec' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

