table Extract
	lineageTag: dc105ee8-512a-41ec-a3b3-ee36646f5457

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: abc4fcdc-b1aa-4891-b37e-aeccc5491414

	column 'Number of Records'
		dataType: int64
		lineageTag: e3fc2183-94c0-475e-9733-51a3084a4c26
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: 265bdbb7-9d39-4e3d-879a-011ff43022ba
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 04170a0f-4856-41c5-8581-e79e92ec2b73
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 23079c7e-ea30-4b93-beec-5c4334b71728
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-c10aaa3b-41cd-40dd-908c-e7bb65dbab10' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

