table Extract
	lineageTag: e209b376-c7b9-48d3-94ea-d3e04224bc6e

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: edf9c824-b967-4f7f-ae02-132224694630

	column 'Number of Records'
		dataType: int64
		lineageTag: dfeb79d3-3ad3-469e-9e9b-1d8fefdfafca
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: 3a975737-df4c-414c-9414-4fb7084f7a93
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 40f5db8a-fe1b-4d40-b6a7-951db5165985
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 0df3c2f4-34e5-4272-b905-a9b2a252f33a
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-2d183398-fe30-4b1e-930a-072b469e8c71' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

