table Extract
	lineageTag: 50d7ddff-67e7-4e7b-935a-cf39d2756ccc

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 3304f7c5-9c1b-4541-bf63-20be33c16288

	column 'Number of Records'
		dataType: int64
		lineageTag: 50d7494a-88c0-4065-ab41-9c3de700ecd7
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: 64c18719-51bc-4d94-9e9c-72c99b2d1588
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 34d72dea-b69e-4570-9d34-5a426a346960
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: d0263de0-175e-4c37-b4de-25bb9ed038c2
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-37f3a59d-b57a-45f6-b570-e63aaa18a922' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

