table Extract
	lineageTag: bd6582a6-8054-4111-ac6d-da2d359559d1

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 0b43b15e-94da-49a1-9e20-0426998534c7

	column 'Number of Records'
		dataType: int64
		lineageTag: 0ce9737a-96d1-4ffb-b56a-5244a3ffa156
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: 8347f2d6-38ce-49f1-b0a0-6d9b136a4596
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: af2e5382-fe3e-43d0-ba92-4237daf68e67
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 1f711024-fe24-4a65-881a-c8cc05a5376a
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-47a3b8b6-ccca-4f03-a83c-4bcad529ee13' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("mssql2012.test.tsi.lan", "TestV1")
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

