table xy
	lineageTag: 201e42d0-a946-4ee9-9b8e-f2db7c217c6a

	column a
		dataType: string
		lineageTag: 691424af-957a-4138-81ee-69d36d2bfabb
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: ad101eae-3ac3-435b-91ae-cc5010d50ff8
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 3bf1b5da-9daf-4f17-ae26-912f0f80976d
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-08802820-03fc-4fa2-b63e-ef4add47dac8' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				    #"xy Table" = Source{[Schema="dbo", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

