table xy
	lineageTag: e349a26c-917d-4a37-8268-1c58de2e32bc

	column a
		dataType: string
		lineageTag: ae024dc7-2c8e-48cf-8952-e32192bdc1e8
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: d14f476d-ac32-4b7f-ae0b-d8a05e049cd6
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 89eb09f1-c854-4532-a643-1eb36a6d9fde
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-da6aff0e-2875-4771-893a-5b0acf773914' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				    #"xy Table" = Source{[Schema="dbo", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

