table Calendar
	lineageTag: 5e4438c0-5473-48f1-9e30-3a6901c9beb2

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: fa7bac12-d3c9-47d9-b65f-6a802dafe3b0

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 31233675-eaad-4ae4-a552-85781a7d4625

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 7700a79e-0080-434c-918b-9ba88d18139e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c546fa61-1cf0-4e1a-b833-cc64ca375d3f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: cf382fd8-67e3-4136-859f-fb0e7bff3af7
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f831c2f8-5171-466e-aaf1-53b2ab4ae6f5
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f971c0cf-4648-4495-970b-37d2ed7d1165
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c12b01c9-e737-4829-ba50-ddbe7fe3455c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e9fac03d-cfe5-49d1-a23b-276e4bd92e00
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 504465d9-c986-438e-bebb-f535d2f2a066
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9a107a38-f332-4821-9587-3eff94bcfe43
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3012c65a-39f5-477b-97db-d97e20a66baf

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6c549061-1a0d-43e7-9f60-311e7a393e7a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f06f065f-078b-4d16-965b-8edf3c728dfe

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 07e3b76d-2ff4-4aec-8f46-ba26fef86660

		level Day
			ordinal: 3
			column: Day
			lineageTag: be60eae5-bcf6-4358-b7bd-50f38a95775d


	partition 'Calendar-04d8a9be-c044-4420-94bd-a9b936c18305' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

