table Calendar
	lineageTag: ecc547df-0a24-4859-a87a-565cf3071e61

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d6c5985d-4887-4062-944c-dcf084663ece

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 129beb91-38ae-48de-9171-dc8d66d09810

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: f89b253f-90ec-4700-aaff-86003399e795

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b9cc7c2c-408c-4fac-9f6d-3d3ea6d0febb
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0ad69d36-312b-45d8-8345-941263489226
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 13822532-4eb4-4aec-9aa4-ffb4486ba8cd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b6f1ab6f-8367-4d99-8d74-18e5ce689dbd
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ba5cbfd8-e5b6-4cce-9797-e612f13d4a73
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0d2c8eba-5033-43da-9697-d3ca8681b025
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 92d28e0f-ed85-4f13-bf2c-d0e9f3bcbef7
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 4f444dbf-3fbb-4386-8c69-e7fa5d1d76a3
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7d7670b5-5c08-4651-9d38-e25e6f25e568

		level Year
			ordinal: 0
			column: Year
			lineageTag: b0c6f5cc-91fe-41a6-92ab-6405a416992d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f8c42cb0-221d-4441-8933-4a48551befc1

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f9bde37a-e4a2-47cd-8edf-87a4d562cd3c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 54ab48b4-598d-4d1f-9c0e-51778e229be7


	partition 'Calendar-9ce8fd30-4951-4997-b716-258eb2931d3e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

