table Calendar
	lineageTag: 1b0cfebe-a98a-41dc-87b1-493261af1394

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: f6cab1c9-4cc9-4c71-a3cc-55b72fe59c41

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 0ca04005-0f3f-4d78-ab8b-430641ddceac

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: a7269663-189c-47c9-af70-fbaad1521312

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 7f5a8ed7-7acf-469f-87b9-3055d87019f2
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 23b779b6-f0b4-4ac8-adf6-33d2203a2770
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0d97ce7e-2f3e-47b7-8eaa-fc362ed260aa
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 730eb13b-e073-4758-8923-7186667f0ba3
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f8720a87-3b69-4a6e-9367-d0c555e4b010
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b5ed6847-2402-415b-94e5-c6b701e0c6c3
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ffb61936-0f45-4f2e-b462-450c34aeace2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 8e4aa9dd-9f37-40a2-b90c-17c17be360a6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 979531ce-8550-42a1-81b8-feec805daef8

		level Year
			ordinal: 0
			column: Year
			lineageTag: 0ce947b4-9c22-4727-8fdd-da2e5ffe72a1

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c0a47ab4-5f3b-45e5-ad2c-2f9b0b544eec

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: cee5bad0-7178-4e13-81a5-0ebe3432ee98

		level Day
			ordinal: 3
			column: Day
			lineageTag: a5822e73-e540-4b11-b211-040bd21add69


	partition 'Calendar-179222e6-00e0-4fc1-8c27-ded60141ff9b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

