table 'Fiscal Year'
	lineageTag: 958372ed-bb09-4529-b2b3-b92a1f500c5b

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: e2e82f0d-21bf-416c-92ab-506d0a86c1de

	column Value
		dataType: int64
		lineageTag: 98507d3e-b2c3-4e04-bbf0-5246da6de5fa
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-9d497c49-12d8-4956-8c31-441512068936' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

