table 'Fiscal Year'
	lineageTag: b7482bf9-7987-4e07-95c7-92369c3817e2

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 138fe3bd-f7ac-44df-a958-50dae1b041d3

	column Value
		dataType: int64
		lineageTag: 4c8d36a3-0097-4f51-866b-ef43e2e7befd
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-087929cd-b6f3-42ca-a829-2bd8789794e3' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

