table Calendar
	lineageTag: 4582172f-742d-4167-9364-5afbf0d4e420

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: e5e0711b-9aef-40f8-aa42-f1f51880aceb

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 88219b58-7e6f-4ffc-bcc3-37e299134c3a

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 10530bd9-7851-4a55-98f3-056ad8e6c5f4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c665ecde-eebd-461e-8c44-a7300ed8d006
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ecd28009-a8f4-4120-bd76-208d465ea978
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7e4bda5a-eb77-46e7-8e1a-e94910f5d141
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d04df43b-da03-4c3a-b06f-82292401281c
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2a1a1139-db7a-45ea-9c6e-a8d589ba4018
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f0482786-af19-40f9-8c4e-a73ff6e10971
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 256544b5-6ffe-4f96-b78b-5cefd281e77a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b9a85344-edbe-4fa1-9e66-7d7c1ec5c1a8
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 28e2c8b4-a3ce-49d7-b327-ffc65edc2cde

		level Year
			ordinal: 0
			column: Year
			lineageTag: e4fdfd8b-28b2-4851-bde7-9e39e3d1e255

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 2ab025ad-c1d9-4b8d-9d2f-89cdcbe6c1ae

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: d0df6927-bb94-498b-b655-188ced4ea88f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7f03cd92-5c9d-4e7d-a680-c6639f2ff2e6


	partition 'Calendar-20de7b05-ee51-44a0-ade7-30a94a32cc32' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

