table Calendar
	lineageTag: b47c64bf-e00c-47a5-9ee6-5deac3c7fe5c

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: cfbd054d-fc93-495c-bc02-2d9b616ac8ac

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 15ffd313-5453-45b3-bb4a-9678f05f0c59

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 69ac125e-d6a3-4195-936a-0c09e38b79d5

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: af64d186-1d81-4ca1-829c-3e133b318821
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 4233174e-a8a8-49c6-b1d0-cbd425c4b9df
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 11b24758-451c-475a-909e-5cedb266b727
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4a50db2a-6747-4d2f-b50d-0a8692dd9f07
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8de99cb1-f9f8-44a0-ad49-a5f7010ba765
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 592fe37b-2974-41dc-97f0-2b05a30ef95b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a4a3dd91-94cc-46d4-ad71-e1f64195e293
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e588f2ef-2705-43cb-a676-0bcf9c0991b9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 2b371e83-3fa3-4612-8b9c-cd1207aae1bc

		level Year
			ordinal: 0
			column: Year
			lineageTag: 169b2052-b723-4f53-8655-5c29df70040b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: aa2fcda4-e6c8-454f-b281-4b33f29d2e2f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8aed80c4-5711-403b-9d44-b7fde9d26f31

		level Day
			ordinal: 3
			column: Day
			lineageTag: da7ea67e-8436-437d-8c99-863931d96141


	partition 'Calendar-6c6be610-8c4d-4340-b4fa-f1d195bb0a3e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

