table Calendar
	lineageTag: edfa9ef9-e40a-4810-a615-0ad60247f665

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 714eb973-2eff-4004-a668-21fec124078a

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 254e7b69-0b4b-4768-a81a-690a59255364

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 3d7ecfb1-31bd-4eb9-b7be-a49e88111baf

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0e0fd73f-800a-4304-9037-bca54d87de69
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 8bf3badc-fd2b-4378-92d7-a32c99a94f22
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dbfa3250-37c6-4696-994b-c26ef02fa3b1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a5d5d59b-0733-4811-b08d-d35846a3307a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: da917fdf-fdd1-4b73-b4d4-c95cf44e3114
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 62dcd5e2-54b8-46a0-81e0-fecd98ad7d96
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a6e0cf66-fdf4-4d1d-95ad-1b88368d9b66
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 5029ad34-7314-42e7-87a3-429fbbab863d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 06366829-fd86-44d1-82fc-05e87b387a75

		level Year
			ordinal: 0
			column: Year
			lineageTag: e57b2b05-79aa-43a7-827a-c39f71e8f664

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c5939cef-f867-4080-937c-69ab309d10d3

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 799aaad1-cea2-44f3-befd-f9b1c7a4465b

		level Day
			ordinal: 3
			column: Day
			lineageTag: 67ed9788-45f9-4b1a-b909-9b9f394a5d84


	partition 'Calendar-bfeeb9a6-285d-4ce3-bc19-99b392f1b467' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

