table Calendar
	lineageTag: f81af636-775d-4e67-8780-b6ab43c0df11

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 50e5ac45-948a-4bb0-94b2-385bf1df4203

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: f4680b5d-34d4-4a47-aeae-d63ddf554488

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 087b3506-0add-41f6-a23a-1ac41c3b8055

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: abb74520-68bd-4640-936a-a004f1128d2b
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 541b0a92-3612-47d3-8202-e915d98bdd79
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dada0ac7-bafe-4fd9-9ac6-f47e9c98b67a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: db554940-94a3-41a6-a086-8b2a3c4c8278
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0cfa28ac-8b78-4904-94f6-bc82be128020
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 35fc3b50-09df-4e7f-ac1a-1bab1a103ddf
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 5e0416d9-fb84-46f6-8539-213229d88e4f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 4c554673-699f-431d-b9c4-49e7994f5008
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 86763ef9-7343-4f26-a9d6-e0829b64ece2

		level Year
			ordinal: 0
			column: Year
			lineageTag: 5252aee6-7acf-42a5-9a64-4e06a186b792

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 455fa460-3b7e-4f32-a43c-4ae8b3f24e14

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 533e713b-b52a-44fa-9608-c90b16ea7e25

		level Day
			ordinal: 3
			column: Day
			lineageTag: 939553f3-406d-4dc3-9fd4-d112a9a320bd


	partition 'Calendar-962560d3-0df7-4eb6-a264-91aeb5f4c5a3' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

