table 'Min Budget'
	lineageTag: d2061d41-506d-4e33-9057-c32c6059dc23

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: aee330d6-05be-466d-a4c3-11ac0fd893ea

	column Value
		dataType: double
		lineageTag: b362bb96-c2ff-4d21-b3c2-761d82d9f009
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-ab1facf4-bf2c-4d6b-862f-6f877664d4fd' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

