table Calendar
	lineageTag: 98ac15ac-044f-45c9-a53e-a0810921cd91

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a9fa98b7-e1fa-440c-90ef-5fa2db530a28
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a7ff52a0-c3de-4171-8726-34d0530a6eb1
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: de6d764c-e39a-4975-800e-b12c0868c3ef
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 82a58954-8c17-4e09-ab20-136f5afcf565
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a866505e-3651-4eab-a8f0-1f228277422a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 76afd653-b459-4207-aab2-6a766168daf4
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4e3326af-9ead-48ad-8695-d73d94a47492
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 6b9999ba-69bd-4908-8289-f870cff473a0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8c004f25-e024-4353-8747-3af3ad42bfe5

		level Year
			ordinal: 0
			column: Year
			lineageTag: b483bc20-9b30-424d-9222-75a2d2989338

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 23fc1b86-a5e7-4a37-99b7-b148029d3661

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 94f91bfc-e3b9-4b74-8d79-cc0d79e37ee0

		level Day
			ordinal: 3
			column: Day
			lineageTag: 97e4e25f-81fe-4f03-8fe9-aa7d127d6594


	partition 'Calendar-39d158f7-c67b-4006-9ea2-7582f22b566f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

