table Calendar
	lineageTag: 67b2f525-1a99-455c-a171-f4ad870fdb21

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fa7235fa-20fd-489e-914a-a466da40931b
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ae38270d-297d-40e7-ab92-37f8b8c7f1fa
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 3b713b3b-eaa0-466e-bdee-37897784b061
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b0efc84f-e517-4696-bf37-4c3c2477a168
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8ce75d01-4cac-4c8c-a44c-9e480f6f6c2f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3170c5c5-116e-4b9c-ba0e-208beea9b22a
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 83aeeb74-c97b-4a76-94ae-0feebeb3379e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: dccd2c2f-db5c-440b-bc7b-1081e9d233f8
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5602b131-2dc6-45c0-a8c0-4653d7bb8cc8

		level Year
			ordinal: 0
			column: Year
			lineageTag: a993ec04-28c9-47d1-bd4f-65d419331942

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 239eb84b-b29a-4172-b098-f1df8127cdc5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c66b6411-1044-4a19-81f8-abead6688577

		level Day
			ordinal: 3
			column: Day
			lineageTag: 72adcc3a-d49a-4fcc-948d-af786ca083bf


	partition 'Calendar-c83b3755-6864-4188-82bd-9dac7a24233a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

