table Calendar
	lineageTag: fbdecd39-fb45-4ff5-9a51-fa1485ec17c9

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 58d97138-3163-4b53-8436-6d8b950ba0de
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5f6d0ed2-c07e-4f9c-b825-9f53d7277cea
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: aab1687e-e0b1-417c-99b0-9772fcb700f1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: acb5272b-e75b-47f4-bb62-6b067b4b2f89
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8f824b6b-2284-44b1-9a1a-dd0b4e6d9ae5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: c572f406-2ec7-4b81-aace-4914a1955a56
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4d7f2532-26e0-4bb1-b947-3050060a648e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 1b4d45de-302f-4ad5-9608-0aca123716a8
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: de8d1c8f-c1ac-403f-b62c-d258ac5c2180

		level Year
			ordinal: 0
			column: Year
			lineageTag: 80d2f226-84ec-46e7-b3ff-283dac682b3d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: a8ec73bf-d988-489d-879c-d89abd9385b5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 03d00216-7082-4a60-b7ee-6e3b866921ad

		level Day
			ordinal: 3
			column: Day
			lineageTag: 43665d85-bd09-46ab-94a9-6229a386e325


	partition 'Calendar-7287f7f6-ab95-496b-ac8f-23eff4f1853e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

