table Calendar
	lineageTag: 0603d1c5-0074-48cb-9825-92dbca189c13

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b9306832-e7d2-41e6-b256-ea077ae39bee
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 8d6aa168-7d87-443f-a368-6a1deb87f80b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 63f6af1b-1a50-43ec-9179-ae5560ae1088
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 6959315c-7bc6-4496-918e-3a1ecb859332
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b7ae0e2d-c85f-487e-9d05-a7723040b674
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 64625527-2334-427a-b2a1-e483effc45cf
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 8a3aa560-4e12-43ea-b737-3cb0c1099b49
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 35c7cd3b-e384-457b-8ca9-9a8b70aee3f0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 53a683d0-cf19-4c6f-99f9-89947f05e7ab

		level Year
			ordinal: 0
			column: Year
			lineageTag: f68cfcae-9285-45a9-bd5f-5cd69d25023b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d3f4da04-5a12-45c1-8dad-b41947f48b57

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7f8d11fe-0941-4d94-9f31-70ea876aac7b

		level Day
			ordinal: 3
			column: Day
			lineageTag: aa858022-9e35-4d5e-82a5-28258854e3ad


	partition 'Calendar-1772da96-c63f-431f-8e65-01cf7db28276' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

