table Customers
	lineageTag: 5f96b8c8-2fa1-40c1-9540-15af996535f8

	column customer_id
		dataType: int64
		lineageTag: d0c673a1-e3f9-467a-b933-5c7d82b72e0b
		summarizeBy: sum
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 9125451f-4aff-4259-bb99-7286b9ff918c
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: a6f34d6f-a3ad-4242-834e-ae9e69fc6cd4
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 7bc1e654-2220-458d-a1a5-8b5b8216e1bc
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 57f67165-6840-453f-94f4-db6f8db82bf6
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 65134af9-f4de-46a1-aeb3-6302d0c0a622
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: fd3fbdd6-8206-454f-aedc-f479ce453dbc
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: 1641f4cf-d94c-4afb-9b06-086e3f396c40
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: 32dca7ed-2639-458f-ad80-cb00b34c2730
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column customer_email
		dataType: string
		lineageTag: bc9bfdb5-6159-4e9c-9ac5-6db0c5d54d5b
		summarizeBy: none
		sourceColumn: customer_email

		annotation SummarizationSetBy = Automatic

	column first_purchase_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4c732a5c-183a-4f7e-8d76-ed97c8d6f3c3
		summarizeBy: none
		sourceColumn: first_purchase_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Customers-0fda9a78-c1b4-4810-86f3-3a3708266d81' = m
		mode: import
		source =
				let
				    // Source Snowflake: acme.snowflakecomputing.com
				    Source = Snowflake.Databases("acme.snowflakecomputing.com", "COMPUTE_WH"),
				    #"ANALYTICS" = Source{[Name="ANALYTICS"]}[Data],
				    #"PUBLIC" = #"ANALYTICS"{[Name="PUBLIC"]}[Data],
				    #"Customers Table" = #"PUBLIC"{[Name="Customers"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Customers Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"segment", "Segment"}, {"city", "City"}, {"state", "State"}, {"country", "Country"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"customer_email", "Customer Email"}, {"first_purchase_date", "First Purchase Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

