table Orders
	lineageTag: 80cfe2c0-6d97-4fc3-9654-dfc569a0744f

	measure 'Gross Revenue' = SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 012024f6-95e7-4ad9-acad-56f660bb3010

	measure 'Net Revenue' = SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", 'Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0e8cb3ad-8d7e-4942-8039-e688e0a6029e

	measure 'Total Discount' = SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price] * 'Orders'[discount])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 15eeadcc-6f4c-4061-9fbc-35d681290628

	measure Profit = SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", ('Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount])) - 'Orders'[shipping_cost], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: af7c6752-3742-4680-aa3b-18599f2b650b

	measure 'Profit Margin %' = [Profit] / [Net Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: cf454d71-24f8-43fa-9a75-655539bfaa1e

	measure 'Revenue per Customer' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[customer_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 33ff9d09-20e4-4919-b1fb-4b4b0bd3cac5

	measure 'Regional Channel Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[region], 'Orders'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d093324f-3750-4131-ac64-4ec28cca214b

	measure 'Revenue Excl Category' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), REMOVEFILTERS('Orders'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 05305f4c-b472-452a-a933-68d7d294eabb

	measure 'Moving Avg Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALL('Orders'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b8f44052-b06f-4a6e-b6d5-87a5e237acc9

	measure 'Running Total Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 21ea16b8-4db6-4291-8597-19bf260dbd2e

	measure 'Revenue Rank' = RANKX(ALL('Orders'), SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]))
		displayFolder: Measures
		lineageTag: 4a7943c9-156d-4483-a7b9-8a7c39a2baf8

	measure 'YTD Revenue' = CALCULATE(SUMX('Orders', IF(YEAR('Orders'[order_date]) = YEAR(TODAY()), 'Orders'[quantity] * 'Orders'[unit_price], 0)), ALL('Orders'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2adf0df8-4e3f-44cc-abd1-14448eb8d0c8

	measure 'Customer Tier' = IF([Revenue per Customer] > 10000, "Platinum", IF([Revenue per Customer] > 5000, "Gold", IF([Revenue per Customer] > 1000, "Silver", "Bronze")))
		displayFolder: Dimensions
		lineageTag: 1a84db41-6a3c-405a-be73-248e70c0891f

	measure 'Unique Customers' = DISTINCTCOUNT('Orders'[customer_id])
		displayFolder: Measures
		lineageTag: a09ced49-5e78-44f1-ab2e-61255358205e

	measure 'AOV Completed' = AVERAGEX('Orders', IF('Orders'[order_status] = "Completed", 'Orders'[quantity] * 'Orders'[unit_price], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2dfcd3b1-d559-47ef-8c2e-e32f74d35f4d

	measure 'Revenue StdDev' = STDEVX.S('Orders', 'Orders'[quantity] * 'Orders'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3a6e1c4b-0414-4b60-8461-d8dd0d862474

	measure 'Is My Account' = 'Customers'[customer_email] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 8f6e9337-ec28-4577-9696-d3aa7cb92d38

	measure 'Date Range Start' = DATE(2024, 1, 1)
		lineageTag: d5a408b4-933f-465f-bc56-37ce9b7f438e

	column order_id
		dataType: int64
		lineageTag: 375769fe-8c6c-4287-8d37-4e32f2eb7a8c
		summarizeBy: sum
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 04269094-60c6-49f2-8f0f-e69e4a371d41
		summarizeBy: none
		sourceColumn: order_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		lineageTag: eb0ce2ee-3039-44e5-a773-fc22ab46a73c
		summarizeBy: sum
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		lineageTag: 9d3abbed-1abb-43c3-a880-7c68baf59441
		summarizeBy: sum
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 6cf679fb-6186-4d84-95b3-898cf44fd573
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 0733e500-af37-4620-9e49-27ca44fb9f20
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		formatString: #,0.00
		lineageTag: 47c7cc30-fb98-46af-adae-4e928243b406
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		lineageTag: a00b4b04-817e-4b2d-ace6-c3c40b5f79e3
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column discount
		dataType: double
		formatString: #,0.00
		lineageTag: 436fdd21-e812-4fd3-8b7f-bb7fd4fd1131
		summarizeBy: sum
		sourceColumn: discount

		annotation SummarizationSetBy = Automatic

	column shipping_cost
		dataType: double
		formatString: #,0.00
		lineageTag: cdb9da0b-1b00-4266-b78e-4e0c83fcf067
		summarizeBy: sum
		sourceColumn: shipping_cost

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: a6375f2c-d329-4e8e-a4e1-3ecb8f2a9921
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column sales_rep
		dataType: string
		lineageTag: ee930fd7-fd36-4ef2-952d-ee0f5912207b
		summarizeBy: none
		sourceColumn: sales_rep

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: 6c38bf22-1536-4185-9f77-a2a63291517f
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column 'Customer Tenure Days' = DATEDIFF(RELATED('Customers'[first_purchase_date]), TODAY(), DAY)
		dataType: int64
		lineageTag: 619cb55c-52c0-4651-9953-af2f52b93eef
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Safe Discount Rate' = IF(ISBLANK('Orders'[discount]), 0, IF(ISBLANK('Orders'[discount]), 0, 'Orders'[discount]))
		dataType: double
		formatString: #,0.00
		lineageTag: 0e661258-59f7-466a-b69e-146c4dcc2d13
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Full Location' = UPPER(RELATED('Customers'[city])) & ", " & RELATED('Customers'[state]) & " (" & RELATED('Customers'[country]) & ")"
		dataType: string
		lineageTag: 89381202-5784-447e-9a85-5940398254a1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment Label' = "Segment: " & RELATED('Customers'[segment])
		dataType: string
		lineageTag: cf2c1bfc-88a5-46f2-81f8-c5f2e253e628
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Discount Category' = IF(ISBLANK('Orders'[discount]), "No Discount", IF('Orders'[discount] = 0, "No Discount", IF('Orders'[discount] < 0.1, "Low (<10%)", IF('Orders'[discount] < 0.25, "Medium (10-25%)", "High (>25%)"))))
		dataType: string
		lineageTag: 682d88fc-ee30-4637-bd9f-5cb4e4c992a0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Orders-8ba3be19-fb30-4af1-b2ba-1fdadbcce0af' = m
		mode: import
		source =
				let
				    // Source Snowflake: acme.snowflakecomputing.com
				    Source = Snowflake.Databases("acme.snowflakecomputing.com", "COMPUTE_WH"),
				    #"ANALYTICS" = Source{[Name="ANALYTICS"]}[Data],
				    #"PUBLIC" = #"ANALYTICS"{[Name="PUBLIC"]}[Data],
				    #"Orders Table" = #"PUBLIC"{[Name="Orders"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Orders Table", {{"order_id", "Order ID"}, {"order_date", "Order Date"}, {"customer_id", "Customer ID"}, {"product_id", "Product ID"}, {"region", "Region"}, {"channel", "Channel"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"discount", "Discount"}, {"shipping_cost", "Shipping Cost"}, {"order_status", "Order Status"}, {"sales_rep", "Sales Rep"}, {"territory", "Territory"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

