table 'Target Margin'
	lineageTag: 23efe192-a337-41df-9933-d5dcf67aea03

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 91d45680-abd2-4cce-bf0d-89bcfdeadeb1

	column Value
		dataType: double
		lineageTag: c5e3a998-62c7-4603-95cc-3ca773ddc1da
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-044b9414-30d9-4a05-99ee-cf609ba73b05' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

