table 'Target Margin'
	lineageTag: 976151fd-dcec-4d08-8d5d-de42c300461a

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 23a169fe-83a9-466d-9516-08ecab732fe7

	column Value
		dataType: double
		lineageTag: 5a625587-efe1-4d6f-bb16-cd1b8ed33464
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-34317add-7952-4235-a22c-2fb92195343c' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

