table 'Target Margin'
	lineageTag: 8eb02f5e-9d6f-4ae9-8d64-b30d207b0801

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: a7d4da2b-1199-481b-b157-a3a74cbc7977

	column Value
		dataType: double
		lineageTag: 8eeba6e0-965d-4f01-9d93-13b4fa7a31ef
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-8201cd82-03be-411c-99c9-d7b8a2d2b11c' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

