table 'Target Margin'
	lineageTag: 2d2440ce-cd60-4d2d-95fc-d58369f07f6c

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: e7f59945-11ad-4a0a-b340-96c87f34365a

	column Value
		dataType: double
		lineageTag: 880338fb-bef3-4354-bfd0-988394774317
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-769e5ac6-2147-412c-a2e8-e3b02680c807' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

