table 'Target Margin'
	lineageTag: 56902f83-3388-4d52-a6fb-270f9265b42d

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: fac0635e-7239-404e-8e81-74f6cac7d4ea

	column Value
		dataType: double
		lineageTag: 1cc635fe-f455-4599-aae1-7b26b8485881
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-8a86f5ee-999a-4822-95a2-640ca9d46442' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

