table 'Target Margin'
	lineageTag: 473c737e-3e96-4d2c-8845-83807b6048b5

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 9d695785-04dc-416d-9cdb-2d1e4a0c831d

	column Value
		dataType: double
		lineageTag: ab1766b5-bd98-4732-b517-63ce2bb1ba29
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-1709c094-3682-48c2-9e37-a4f1720f1892' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

