table 'Top N'
	lineageTag: af1fa92c-2fd9-44cc-956c-7f0b89e06a25

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: fee59afd-4d1f-4314-b3f8-08937409b097

	column Value
		dataType: int64
		lineageTag: 2421d93f-5aac-4cdd-884d-bb5a8702d69e
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-fcc76609-0b33-4813-8414-0bd780f5f158' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

