table 'Top N'
	lineageTag: 876919b9-2e3f-420c-a903-57c5f2e50147

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 459dde94-d211-4de3-8090-25c9579ac5dd

	column Value
		dataType: int64
		lineageTag: 2315472e-0245-430e-aaad-af3de9e63a27
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-be877268-3770-4c05-a292-32242c261ce6' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

