table Calendar
	lineageTag: d30194e4-1b86-473c-83ea-7d1365eea0c4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c3876efe-bfa2-4483-ada4-7440da6f5f40
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 735606f4-ecbb-46bc-9b4e-a964a2c95fd6
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: a24fc570-b028-40ae-9bcc-71c8850927bc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ca250b43-7683-4388-af9b-fd2575a7d423
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 300ba064-0ab6-457d-b0fd-1255ef9d1f09
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 9bfe5541-c3c7-4c08-923e-1160e35b47f4
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 6b01472a-c092-4b7f-82a0-779d4a1d12b2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d8e2021b-51c6-4df1-8df3-7ea942ccd418
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f6f9a592-af14-46e1-bcd8-9c6971325f09

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1deb9288-1054-4061-897b-ee220e1b9430

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b106a51e-ba70-4e1a-a96e-fdc45dc4e923

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4f4c47b2-0376-4187-acb4-065e8817f540

		level Day
			ordinal: 3
			column: Day
			lineageTag: d129d8d0-5462-41f2-aaa1-b9d91d132f8b


	partition 'Calendar-b7339e82-1460-41ca-950f-53141dc210e4' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

