table xy
	lineageTag: 667eb82b-1c35-498b-aad6-c040da034845

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 2977df2b-fb69-420c-82fe-cec51ff2ef26

	column a
		dataType: string
		lineageTag: f8ec69c4-3c64-4232-ab2b-1b72733e56a4
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 17f1874a-a65d-40ff-90ec-3c72d62d2d86
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: a4d32de8-c6f0-4945-9cf2-3dc505b7fe0a
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-6a8a34d6-0973-43ce-8983-6285f3c36067' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: Unknown
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"a", "x", "y"},
				            {
				                {"Sample 1", 2, 3},
				                {"Sample 2", 3, 4}
				            }
				        )
				    otherwise
				        #table({"a", "x", "y"}, {})  // Empty table on error,
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

