table xy
	lineageTag: b1540043-a332-4b90-9ede-b5f0201ae77b

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 59000de5-d3d0-4ccd-9736-0011dd400757

	column a
		dataType: string
		lineageTag: 9e03ce3c-aeeb-465f-80fc-498f698954c7
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: fbf3ea3b-6d63-4fa8-90dd-be47195680d8
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 411f4d93-6afd-4c39-903e-1129c3510a22
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-ccc4537c-415c-45f9-ac24-b60a71d410ac' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: Unknown
				    // Replace the sample table below with the actual source expression.
				    Source = try
				
				        try
				        #table(
				            {"a", "x", "y"},
				            {
				                {"Sample 1", 2, 3},
				                {"Sample 2", 3, 4}
				            }
				        )
				    otherwise
				        #table({"a", "x", "y"}, {})
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

