table Calendar
	lineageTag: fe4a2269-557f-4853-b881-1738af47c2f7

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b6b67f0c-7eb5-4e47-8bfa-97b45a094b49

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d4d8c3f3-6b71-49da-8c22-31177ecc4865

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: eaa3a23d-a921-4a73-9706-3219940e9a76

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a94d9821-186f-444f-8993-1debc61d3ab7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 3c97b820-fd08-48c0-8024-f76c53a7941e
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 64f6b445-0668-4304-a3b9-c59fcc9a5b7f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 106164a9-975b-440b-b292-405263192dba
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 602d4019-12a4-488f-a26f-c44497e0fb4c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a0f5f3d0-c774-4cde-b6b8-94404ba9c013
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2feef9ef-8845-4281-bbcb-fb1c4096016c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: cc695ec4-d7d8-45c4-954b-7cfedc28a600
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: da23c8db-3ef0-46ae-a37f-f39fe9db5901

		level Year
			ordinal: 0
			column: Year
			lineageTag: 8b1022bf-60ad-4c91-b5d2-96c3f5d18dbb

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b00b0f0a-e2d3-439f-a606-658f7472dfbc

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: d535fbfb-62e0-4f9d-b748-ab04d25b1391

		level Day
			ordinal: 3
			column: Day
			lineageTag: d0926031-0740-40db-8574-ad4a62e9c0eb


	partition 'Calendar-bed8bf4f-09f4-4353-b3aa-aeb50c594d1f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

