table Calendar
	lineageTag: cedc3525-eb29-4ef0-b499-68df8e161387

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: cc87ad17-83da-4041-a9ff-02fff3565606

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7f8687a3-49dd-4ea8-8238-706162306460

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: d4a438f2-98ff-4d38-b3cc-8296e78480e6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 54cf3c0f-6999-4e19-9b13-6777a5d53ed6
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2c26166c-f7ba-4b42-88fd-d375a5ec94ca
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 33f0c1df-b6fe-43f2-9589-d29ebd481187
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 78868f9d-c581-4ef5-87c9-2ecbd8543d9e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 9868a110-4490-489c-92ea-1e9843ce2265
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f51d880e-4a72-4d6c-b276-ccfa8eea0d50
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 39b4aa83-9b2e-4d61-8140-b7366b18bd66
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 6cc72995-c9d2-49c4-97fe-7e2b07a53855
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 787faf3a-e158-4454-b96b-076d77735559

		level Year
			ordinal: 0
			column: Year
			lineageTag: 0b3790ca-9e9e-43a7-9891-7a0e672b7a1c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 23b85135-15b0-4d2f-97bb-01c6c9c669ed

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7212af4a-c212-416d-88ea-71c8282cafc7

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1091f658-a905-4542-87fe-3bc39edbf02f


	partition 'Calendar-cc5fa28e-7437-40b6-9f65-9a49b08266a1' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

