table Orders
	lineageTag: 311a3338-3991-489b-9c70-96b153d4d04e

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b1e58731-16b2-4da1-8609-1728c8f39be3

	measure 'Total Profit' = SUM('Orders'[Profit])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6893de07-5b05-485e-8934-0ae49e1e578d

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 42fc0510-146c-4476-99e7-09d4548db3e4

	measure 'Number of Orders' = DISTINCTCOUNT('Orders'[Order ID])
		displayFolder: Measures
		lineageTag: 0f69a5be-d9d7-44af-9451-ae70aa3a9846

	column 'Row ID'
		dataType: int64
		lineageTag: 5267be56-b114-4a02-95ce-e7d78c79c413
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 0adde1d2-e6b1-4490-952a-27c6e0e6dff2
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4eb2a05f-c27a-46e6-bb47-bda64316af97
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b79b00f7-aa40-498e-ad64-e9bda70daae1
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: b7ad1152-b032-4363-9471-e72260958508
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: ee6a82a2-b8f8-46fd-8c99-cb3788c0e5c4
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 9f0b6962-d0c7-4a33-922b-9ed0c6bb9f77
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: a269528e-4c93-4d52-9fcd-a5eada837fc0
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: fdbaed62-ff76-43ce-8192-88ee594b909f
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 0472d123-eb5d-4727-a7fd-5d460c8cce9c
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 3bc89950-38b5-4e02-b280-93dca874bcf6
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: 67b37e75-dd46-44c1-ac3d-34dd310ce8cd
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 34d213d5-74c5-448d-bea9-12097e0903c3
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 81f28803-a387-442a-aded-f41c4db339a5
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 0a1c86ff-0a35-47b7-96d3-398644af070a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 8f66bb40-1508-4c95-94b8-8f61fb0cd073
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 9975bb86-33e8-46e0-93ac-6e661cecdbab
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: e341e01d-627e-4efb-9660-160fe24b8899
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: fed9c2b1-96fe-4468-9b7c-99b9b2918eb8
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 169b3cc2-ca67-4bf2-b33d-cfbae210e4d6
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 4ddbf5b7-f41b-43ca-8eaa-7f849ba92f6f
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	partition 'Orders-776962dd-a844-4d99-85a3-79bb589f61c2' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country", "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"}, {}),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

