table Returns
	lineageTag: cc19cb19-c18c-459d-b9a8-a5154516f516

	column Returned
		dataType: string
		lineageTag: f2188c60-1c9f-47e8-ae6a-756a888ff6cd
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: e0233d22-6af1-480f-bd11-5c1b95e022ac
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Returns-4a265fe1-cb1b-4207-9b6a-9117590c6345' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Returns Sheet" = Source{[Item="Returns",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Returns Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

