table Calendar
	lineageTag: 1a6057e4-8a60-4e36-9aeb-43ec6e8c3815

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 76c4398c-fa7c-47a0-84e4-89e8d3f1d753

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 4fb8b8d8-d209-4f6b-964e-789dd3559286

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: dd6d0d69-fa6e-4ae1-b378-265421a490c6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f1f5f690-f9a6-4abe-959f-e5976a30cc6a
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 56e480b8-9edd-4f62-9acf-1ec07c336932
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1f95aafe-dbb5-4ffe-ba06-d20bf2b834ff
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a8304207-5b67-4a06-bfb9-db334c5495ec
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0486385d-8fe0-4ff0-b613-8fea37c3dad9
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 89133cbf-802e-42d9-a8d4-29ef7a9fd18c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: eeaf956c-7764-44fa-9dd0-b3e3f0b26786
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9451a070-cb61-45d4-8d86-ba1d0b21155e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8270f093-e958-4500-8cee-709423655455

		level Year
			ordinal: 0
			column: Year
			lineageTag: b1d83658-ee77-4ea0-aaff-57499a597ace

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 044f11bd-704a-4f47-82e7-dd174db250aa

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 5f442c7d-d459-42c3-8772-7be0a5bb540c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1f5fb5a7-481d-485f-a99a-63900644d94e


	partition 'Calendar-a9e83417-f240-475c-ac5e-e2024af5bc4a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

