table Calendar
	lineageTag: 2f2b22eb-166e-414c-96f3-df34dfaefba1

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a10af994-a4fd-4467-9d8a-20955102ad93
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 14ae10ef-995c-4e5e-881b-3294cbeb1042
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4ffcb0d8-16cd-4e5c-b14f-82dc11bc7fee
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 9117fb82-d516-4e46-8925-a040f3c4c7eb
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ba222b34-6965-4b01-8bdd-796de771a777
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f7f04f5c-810e-4f93-8751-ab650d201e15
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e884800c-2330-4089-9aa6-ee8f8b321621
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d8590624-9494-4698-bada-a600b88b8ca3
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 79ff4a55-c090-4aba-be16-c5a549f168e0

		level Year
			ordinal: 0
			column: Year
			lineageTag: ed820e06-b3e4-444a-a4f8-61d8d5a8f16f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 922632aa-3175-498e-91a6-fe76e4899b25

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3b56647f-2dcb-4392-9920-5270aa471806

		level Day
			ordinal: 3
			column: Day
			lineageTag: e304f467-5d16-4808-9856-a1a3306bc729


	partition 'Calendar-caf9a8eb-84e1-46fa-ae61-1e5e934c9e84' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

