table 'Target Margin'
	lineageTag: 1bc47f3c-187d-442d-840c-6e431ad33a58

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 59d1098f-8fe8-43ee-a2ad-4899e503e0ea

	column Value
		dataType: double
		lineageTag: 5d5da28a-c9df-41ef-beb4-d54f5961a331
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-433a0d43-a54f-437a-89cd-7ec30b2b4f78' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

