table 'Top N'
	lineageTag: a285b0a7-9716-474c-8ddf-2deb05e309fd

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 05c38b35-b1bd-437f-bc3b-181cdbff49af

	column Value
		dataType: int64
		lineageTag: daa08f9e-ac5b-4f34-b578-530c19a97108
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-6b41ef98-c702-49aa-8b91-2450da914ccf' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

