table xy
	lineageTag: 32151618-e829-43b5-84e0-c16d58af1dd2

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 85044d92-7d15-48ca-b02a-93b8edaa500c

	column a
		dataType: string
		lineageTag: 7753c264-6756-4594-9c35-ce53dafa84ea
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 58a89b74-115c-42aa-ad20-f9f903fd9a0c
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 7bd987c6-7597-464d-b56e-17ef93d4c60b
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-d97e2b76-4032-420b-a679-25eef17dc8a2' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

