table xy
	lineageTag: 5f423c14-f764-40e0-8dfa-9c6a6e6d1823

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 475d501c-f9ab-4fb1-ace9-358c9bd8a35f

	column a
		dataType: string
		lineageTag: 66c97e80-80f7-4148-8c30-6ee67a929f92
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: f204b16f-ba0f-48bb-95b6-c273484142b5
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: cf7792ba-e924-4c4b-97f4-ac825a721f64
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-33cb9b7e-5545-4585-bd83-6d8d0072d121' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

