table xy
	lineageTag: 77aecc9d-544b-4668-830f-5190674b9d5a

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 06322e56-3736-4752-96bc-93242552cae7

	column a
		dataType: string
		lineageTag: 38bd17da-191e-47f2-923b-a0c97f4dde6b
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 0ef58d5a-1213-49db-a9e6-e2f06210791e
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 2dab31c9-5d91-4c2c-8b9e-7096106dc7b0
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-87ff926c-3dad-48b6-9a49-5096f76c80ad' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

