table xy
	lineageTag: 01616ad4-46de-49ed-8e1b-96221aed00ab

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 73b79b8b-c02b-4250-a3ce-05e5b643f2b2

	column a
		dataType: string
		lineageTag: ef357e70-b7c3-45db-a03c-678310344d39
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: cedd2306-5c0a-4d11-aefe-281bbac647a3
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: a2ea10f5-1c38-47b7-bdde-a638159d2f4a
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-07462bae-f115-45ad-a125-d49e4f5556f4' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

