table xy
	lineageTag: 958cd922-249b-444c-b23c-3ede11ea481a

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: aa0451f9-9da6-45c3-8e7f-f7f836fa6792

	column a
		dataType: string
		lineageTag: 9c601dff-9523-4f4e-83c0-2adcbf3dec63
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 4baa220f-aec0-4946-a4ae-69db8803fd0e
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 30f0c697-4f92-4b28-b65f-a739d02201c5
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-05065ef8-69c2-4e3c-bb1e-55169822f975' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

