table xy
	lineageTag: e9109cfc-7708-431d-b4db-44977953e367

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 5c783777-bfdf-4149-96ea-31cd0b494b2f

	column a
		dataType: string
		lineageTag: 18b46a48-2b74-4648-ac1e-0cc79a392b32
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: d7f21af6-d538-4e86-8d5f-7fe1fc2f1f3f
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: c290209a-936b-4fa4-b57b-9f47596fd3a1
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-6bf8d9b1-83d3-4928-a5cd-8c47d5f7d6a9' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: Unknown
				    // Replace the sample table below with the actual source expression.
				    Source = try
				
				        try
				        #table(
				            {"a", "x", "y"},
				            {
				                {"Sample 1", 2, 3},
				                {"Sample 2", 3, 4}
				            }
				        )
				    otherwise
				        #table({"a", "x", "y"}, {})
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

