table xy
	lineageTag: 10147937-9dae-4c81-abb3-fde9f856c30b
	description: Contains 3 columns and 1 measures: a, x, y.

	measure '[Number of Records]' = 1
		displayFolder: Measures
		description: Migrated from Tableau: 1 | DAX: 1
		lineageTag: 24961876-7943-4ad1-ac40-2a6758cd7890

	column a
		dataType: string
		lineageTag: 805ec2a5-eeaa-4c5e-ab68-ec7c4800199a
		summarizeBy: none
		sourceColumn: a
		description: String column.

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 27a599b1-f265-47c7-9cec-423df0d9173b
		summarizeBy: sum
		sourceColumn: x
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 9002b5c3-3f6e-4bd7-b3ed-fd79dc9a099c
		summarizeBy: sum
		sourceColumn: y
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	partition 'xy-2e6ffc50-464f-4dfd-82e7-d8b5c2eca2f7' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 3 columns and 1 measures: a, x, y.

