table xy
	lineageTag: 4ddf03ba-a939-48b7-96f5-68a2e4764ee5

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 72fd864b-7164-456a-9b0d-0a6aa3fbfbbb

	column a
		dataType: string
		lineageTag: c149022d-9272-483d-a8d5-069d65867fcb
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: f636751b-04a8-49e0-83fa-a78ebe2ce69f
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: fda60645-17b1-47b1-a5e5-64acd7275118
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-091b4ddc-0a6a-48bb-96fb-cf1f8346cdb8' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

