table xy
	lineageTag: 4adbb506-a025-490b-90bc-f253bf61c2a6

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 5e82a767-5312-4640-900b-c6be5c3bffa5

	column a
		dataType: string
		lineageTag: 8e41998b-484f-4e08-bfa6-a57f87ffa9df
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 844185ae-aa87-491b-9c17-76ce617ef7a3
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 8defd6f6-9b65-4a83-801c-579032c2177c
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-a280b44c-05bd-4809-bb40-391bac2fad31' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

