table xy
	lineageTag: 93bc598f-611e-453d-a7ca-221adcdd149b

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 3aa5547c-bf9e-420b-9256-3eadc45f51f7

	column a
		dataType: string
		lineageTag: 0ad9d6d1-7f8e-4278-884e-34755fae1e43
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 63b5a732-3a28-4b2f-95b6-56a55992f8bd
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 0dda438b-0cb7-4a4a-83af-ddadf88e55f7
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-a824ecf3-d3f7-4df5-9d18-bd59fa3b9727' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: Unknown
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"a", "x", "y"},
				            {
				                {"Sample 1", 2, 3},
				                {"Sample 2", 3, 4}
				            }
				        )
				    otherwise
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

