table xy
	lineageTag: d86b64c2-ea56-454b-ba31-c0d162ab17e5

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: f9119e6b-7a1f-4702-b247-02b1d6b8daa6

	column a
		dataType: string
		lineageTag: 254b55b4-aa3a-4a4c-9413-6736c3fb6b56
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: cb856f2d-03df-434f-9950-2332b7cec2fd
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: cd668d09-b50e-4d2b-a203-7a6360942d8c
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-d48679eb-7f86-4a1c-9328-b294c58af43e' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 3 columns and 1 measures: a, x, y.

