table Calendar
	lineageTag: 397a9d02-d76c-4f27-bd02-b91080b2401d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0a8f2580-be0a-4ddf-8fba-f2a96a7d5fe3
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 89dcba5f-ba20-40c9-a87b-fb9ffee36e93
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 36cd59d8-a19c-4f60-bc7c-ace8f6a32e6f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 834df745-da89-46d2-8c8a-97a7ef21059a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 5767aedf-4bac-4639-87a6-697da4206d8c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7c9d639c-491c-41a2-9d65-efa5e9d1e8bb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 6204f807-491b-49f7-9179-dccd7d08c2d9
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 8e64950f-f0d8-4afd-8284-3696e0b3015f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b2e37272-37cb-4dea-997a-a9103ecb8c0b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 9ca333c5-a3d6-4f9d-9f23-f0c189a5b539

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: df31f719-ea7c-4427-92c1-094b79b54d9e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: bc2e9b33-b4c6-4844-a52f-44fcf591c581

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9bd20af1-c6b8-4a85-b81c-d60efa492295


	partition 'Calendar-1a4753fc-b712-4e5a-a02d-673e5c2789ec' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

