table xy
	lineageTag: 7cfc3179-bcca-40bd-b402-30bc82960ad0

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 7b81b83d-ee23-4dd9-a0da-86b436daa964

	column a
		dataType: string
		lineageTag: c2d6ee9a-e88b-4975-83f2-8d960e350e3c
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 5484bbe6-2472-4132-ad9c-73f7b9801bb1
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: ebf71c90-12f4-4a33-8c2e-2fe9ba944c03
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-2810dae8-6daa-4765-a411-0d0d8ad0b7c1' = m
		mode: import
		source =
				let
				    // TODO: Configure the source for Unknown
				    // Connection type not automatically supported
				    Source = #table(
				        {"a", "x", "y"},
				        {
				            {"Sample 1", 2, 3},
				            {"Sample 2", 3, 4}
				        }
				    ),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

