table Calendar
	lineageTag: 0be1ee4f-10c3-48ff-9fe0-8a0ad39733c0

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8f42e7bc-0a61-4208-bece-ee97c7b03542

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ea8ec6f1-a508-444f-80e2-14812a06c44b

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 765b6b8e-60cc-43ae-a73b-551232a30fcd

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2676edf0-ba14-4998-a7de-ed4adabc81a1
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: cf9cecd1-40a0-43b4-b567-4ab5cc7324a9
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f03ff9ee-738b-480a-a02a-760e2d50d3d0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f6cd192c-2a09-4479-be77-ae6ae284c550
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4d81caa6-a24c-42ed-924c-d7ed86e40064
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 20ff0c90-230f-44ce-af59-c42e56fade0c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 15901a8a-0add-42e7-afc2-2d98b18fdedc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: edeba939-800a-4d90-9fea-d84557bafaae
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3321ae9e-e587-4e19-8cda-346360cc9010

		level Year
			ordinal: 0
			column: Year
			lineageTag: 197080c3-0bfb-48f2-b975-8dea49ba8b11

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 68ef43ba-cfaa-48be-b40d-5d52f42bbd9b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 280d85da-57e1-42cd-aef1-1e7325715990

		level Day
			ordinal: 3
			column: Day
			lineageTag: ffbc0d93-f08e-407f-978d-1c0b70f2faea


	partition 'Calendar-c4faa0da-6c37-47b6-8e23-be0cafa65803' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

