table Calendar
	lineageTag: 45e2bd9c-9cbf-4ec4-b7d8-ff1c86732145

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 666e48c9-0030-491a-9151-f966ba1803fc

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8f1c40c8-1d30-46c1-957d-5a020f28a1f9

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: dbea020c-e81b-4461-ac3d-a04671eb7d20

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 98621148-fcf5-41df-bd17-046af56699fc
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 96619813-8968-4119-adba-6771206fc5fd
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1d5928c3-1e81-4cc5-a96b-08fa41af3798
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: fc96f0bd-9fc0-457b-8da6-a3ac45a82049
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 14b6a3dc-19b7-44c3-9e57-c1d451e7d093
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 954848ff-bc7e-463e-acd5-260fef3993dd
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 51437df4-ffa7-4d52-a8b9-2d4ca0c365af
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d870eb3d-67fc-4fc8-8799-84eb67a5df25
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 39f6eecf-f7a6-4782-9190-17cfd100469f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 5638be6c-919a-49a5-a774-b1ab795d255e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 2a136169-e4e3-4f78-9137-87ca153cab05

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: b92534e9-924d-41b5-bc78-628ddd9004ef

		level Day
			ordinal: 3
			column: Day
			lineageTag: a70d6303-842d-43e5-8bbe-4a558a509cc2


	partition 'Calendar-cb338001-77b8-4e9f-909e-8080a17e4a4a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

