table Calendar
	lineageTag: 32f79bc1-5778-491e-bd75-893c72aea7a7

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 2bfa70bf-b7b1-42e6-8543-a1aa92fcce83

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: de912ccc-7e62-412a-bf7b-a8899ed83244

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 99c4d35e-f647-49c1-9d14-50f11cb2783e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 00405a20-0ac3-4f9b-9e25-52ab0b720594
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 7c4c113e-5f1e-491f-a80a-443469520828
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: aa1cb3ab-3a0d-47bb-8e8c-ea576a612ac3
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d57c51c5-adfe-45e1-94e9-be0695dfbe00
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8c4756fe-7cf9-4645-90d1-b186eb112265
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ea79dd6b-cb0a-481a-912d-cab6aa6d3619
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 33178f55-e624-4381-9f63-12d89a097ea6
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 11727510-be1e-4d9f-ba8b-0483fd224287
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4aefc9b5-72c1-44a0-a80d-96e894dd0861

		level Year
			ordinal: 0
			column: Year
			lineageTag: 93049ed2-d789-47ba-9a38-6ab23aa9584c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 272f6da2-c412-48e3-bd69-b90a42424a9b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 21466448-0029-4364-86a2-f401cdf6b52c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 35e4f2ec-3ae2-4db2-a65b-0470d8f0c347


	partition 'Calendar-774c1c72-62bd-41a0-b059-2482fb46fdad' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

