table Calendar
	lineageTag: d0e426e2-8f2b-4a70-9b37-f089ae2ab5a6

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5cd6d7aa-d16a-4969-bacb-aa8c2e38d852

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 27d38e05-9e59-4eb5-baaf-368125fc05e2

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 47c41d16-a739-4d9f-8772-ffda6755f3c5

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a9bb7dc1-0fba-4957-aad8-851a5c1718e4
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: fa5b4c65-2af2-49c0-be2d-5d671a85f903
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 655c2c69-ebde-4bb3-82cc-fc90add2180d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ec18dd2d-2456-4118-ad63-b6fb271e30ca
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: aa605047-23bf-4295-a18d-ee201fe62412
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ba0b7757-3733-49cf-bc69-f205445be84b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c301c8ff-b92e-48ea-9086-e72502976a7d
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9d584dd7-690e-4215-962c-820caa632b03
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 944e81fd-c597-4e38-87e0-4f98d8cf421e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7c9b5da7-6d4b-4258-b97e-c7483c2aef58

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 8493500e-8c99-4260-a274-f7606298c4a4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 78eb7575-1958-444b-b51e-d188003e2562

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1ee53d5e-346e-4b46-8cf9-0a2e329a0155


	partition 'Calendar-de0195af-ba84-4a40-856c-036f36c0b308' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

