table Calendar
	lineageTag: 204d62b2-2f64-44cd-8f58-797b6bb1599d

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b3140edf-e1a8-4d50-958a-c84946952394

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: a6830042-904d-4d61-adb0-927152f91a8e

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: caa6f1e6-9746-4d63-88fd-e3dae5abdb1c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e6d95fd8-d3fb-490b-9dcd-96b792d738bb
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 4f8cfffa-baac-41dd-8c54-6f906637d860
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e29e3469-7d56-4355-b120-cc403a911e66
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e18ee7b4-3c19-44fc-adf3-1934029682f6
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 27602cd1-13a8-4a7e-a8b6-253d7ca0fe44
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f0506979-3487-4d6e-bbf3-c4858af1ed64
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a7c6c6af-6cbd-41ea-93d7-307dffa68e7e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e0a128a0-33e5-4781-960b-3bba4b92242b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 14a29046-3ff1-4f3e-9081-68df79c276cb

		level Year
			ordinal: 0
			column: Year
			lineageTag: d1094b22-9365-481f-bce8-56b3530fc764

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 338eaa5b-6928-4f7f-8481-ff8a99bfbd60

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9364ff2b-428f-4a54-9936-7163b2491985

		level Day
			ordinal: 3
			column: Day
			lineageTag: 14a07719-750f-4a4f-ba30-441c76583326


	partition 'Calendar-1724e381-4800-484f-a5d9-40ca24493a11' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

