table Employees
	lineageTag: 53ace3f0-b7d2-45fc-93f7-3bcef78de5c5

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d511136d-f1ab-4f90-a4e8-a49149b871ed

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: 5ae8c07c-56e8-4abc-8141-114c78e61b4f

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 75c02e17-0e1b-4ad3-859d-9f31a64216d4

	column EmployeeID
		dataType: int64
		lineageTag: 0bc5d7a2-5026-4724-947d-ff85bbdb24f5
		summarizeBy: sum
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: b8b6a05f-045f-42d7-8918-53047ccb666b
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: b7f9542b-fdbc-4ead-a17f-294ae7d55f99
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 81855ad9-f7c5-4306-83a0-94c0d6032111
		summarizeBy: none
		sourceColumn: HireDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 14d432d4-f4bb-49eb-b653-eea6a0cc7115
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 2d6395f1-006a-4d75-9e5f-eab19f2ef384
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: 853671cb-1177-4a22-b270-8a1fe7ec3d49
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: c8848689-9a08-4c98-ba2b-36961c65b2d6
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: 977275e1-ea4a-4780-a23a-cdb87da978f2
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: a5c8e2e4-b652-428e-8ae0-e4fcf8b8638f
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: 505c85a1-9d08-40ce-b555-21225e0a9929
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category'
		dataType: string
		lineageTag: f1185703-ca59-4faa-affe-0ba5c0cecaf1
		summarizeBy: none
		sourceColumn: 'Tenure Category'

		annotation SummarizationSetBy = Automatic

	partition 'Employees-82a99504-f695-491e-b2d1-8c3ac8e35b16' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("localhost", "HRDatabase")
				
				    otherwise
				
				        #table({"EmployeeID", "FirstName", "LastName", "HireDate", "Department", "JobTitle", "Salary", "Location", "Age", "YearsOfService", "PerformanceRating"}, {}),
				    #"Employees Table" = Source{[Schema="dbo", Item="Employees"]}[Data],
				    #"Added Tenure Category" = Table.AddColumn(#"Employees Table", "Tenure Category", each if [YearsOfService] < 2 then "New" else if [YearsOfService] < 5 then "Mid" else "Senior", type text),
				    Result = #"Added Tenure Category"
				in
				    Result

	annotation PBI_ResultType = Table

