table Employees
	lineageTag: 5eb06737-b496-4f51-8860-1ca64a949651

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8c83c345-e4a1-4b94-a02d-20c555b8a1e5

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: 9dc21fa8-8ca8-4c6c-872d-7fdeff365bb8

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2423586d-2ffb-47f7-b909-c18c6981b31c

	column EmployeeID
		dataType: int64
		lineageTag: ce499a95-81d2-4915-9209-be8c1e5f1473
		summarizeBy: sum
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 7774db0c-81e0-436f-832f-80281426ff69
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: e0030d1c-97b6-4361-a835-66bd1d2eb130
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 738b56d3-49fa-4974-a41f-12a5a3f7fef9
		summarizeBy: none
		sourceColumn: HireDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: fc2f3eb5-c7e3-47e1-8996-dac99d517ebc
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 3dec7385-6491-4517-a694-5fe8b45e5180
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: dec970b9-eb0a-4ddc-a63e-165438629e8e
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 40d5d9bd-69fb-4dda-93bd-045d25cf8445
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: d9bfcbf8-6b5e-489a-9fb2-b188ee9d7029
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: 436b3132-5b4e-4337-a988-c6bacf292b3f
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: e2b39efe-bb43-4997-bee8-c8c452f9b123
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category'
		dataType: string
		lineageTag: 7bac7a9d-c065-4f19-9006-4889b13a26d5
		summarizeBy: none
		sourceColumn: 'Tenure Category'

		annotation SummarizationSetBy = Automatic

	partition 'Employees-f4c04ae6-2acb-47f4-98ee-6f4d3c2dec78' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("localhost", "HRDatabase")
				
				    otherwise
				
				        #table({"EmployeeID", "FirstName", "LastName", "HireDate", "Department", "JobTitle", "Salary", "Location", "Age", "YearsOfService", "PerformanceRating"}, {}),
				    #"Employees Table" = Source{[Schema="dbo", Item="Employees"]}[Data],
				    #"Added Tenure Category" = Table.AddColumn(#"Employees Table", "Tenure Category", each if [YearsOfService] < 2 then "New" else if [YearsOfService] < 5 then "Mid" else "Senior", type text),
				    Result = #"Added Tenure Category"
				in
				    Result

	annotation PBI_ResultType = Table

