table Employees
	lineageTag: 79d04e2e-eb78-4aab-8433-a5b19528cacc
	description: Contains 12 columns and 3 measures: EmployeeID, FirstName, LastName, HireDate, Department, JobTitle, Salary, Location, ... (12 columns total).

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: AVG([Salary]) | DAX: AVERAGE('Employees'[Salary])
		lineageTag: e52bfa0a-ad62-4413-b758-e1db41f8cb67

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		description: Migrated from Tableau: COUNT([EmployeeID]) | DAX: COUNT('Employees'[EmployeeID])
		lineageTag: 8bb84bb0-3e32-47a7-b5b9-a2fb1c75a609

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([Salary]) * 1.25 | DAX: SUM('Employees'[Salary]) * 1.25
		lineageTag: 5e32636b-7275-42a7-b2dc-8fa5da97c80d

	column EmployeeID
		dataType: int64
		lineageTag: 15fd8a15-4ec2-4c02-9aef-8927bef56d34
		summarizeBy: sum
		sourceColumn: EmployeeID
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 9215be5e-6aec-491e-a42b-95b8ac528a15
		summarizeBy: none
		sourceColumn: FirstName
		description: String column.

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: a9ed4214-5754-43d8-86c2-de912f6fabe3
		summarizeBy: none
		sourceColumn: LastName
		description: String column.

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: c3159aab-00d4-4957-a2db-9c0d3b89ed2f
		summarizeBy: none
		sourceColumn: HireDate
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: e18e5bb7-7f96-4dca-8ba3-dd0bbb0409aa
		summarizeBy: none
		sourceColumn: Department
		description: String column.

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 1737dfbb-6b6e-4d41-a58e-7c6a6c5bfb40
		summarizeBy: none
		sourceColumn: JobTitle
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: 9b1b5141-10c4-48e2-ac53-fe8ff7c6982e
		summarizeBy: sum
		sourceColumn: Salary
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 1e4fd36d-0214-4cfc-9c9f-63eb2d492ced
		summarizeBy: none
		sourceColumn: Location
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: 3fa2c25c-935a-44bf-a274-b17bcb540604
		summarizeBy: sum
		sourceColumn: Age
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: ec1b4090-ce89-4fba-b6ce-bbcc7c0a964b
		summarizeBy: sum
		sourceColumn: YearsOfService
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: b99e4be8-7026-4b88-981d-2fd609e10875
		summarizeBy: none
		sourceColumn: PerformanceRating
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category'
		dataType: string
		lineageTag: 7a0b3a40-1271-4803-b534-f3b513aac75d
		summarizeBy: none
		sourceColumn: 'Tenure Category'
		description: String column.

		annotation SummarizationSetBy = Automatic

	partition 'Employees-5700b192-7a13-4b60-961f-2970b5a7db91' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "HRDatabase"),
				
				            _nav = _src{[Schema="dbo", Item="Employees"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"EmployeeID", "FirstName", "LastName", "HireDate", "Department", "JobTitle", "Salary", "Location", "Age", "YearsOfService", "PerformanceRating"}, {}),
				    #"Added Tenure Category" = Table.AddColumn(_nav, "Tenure Category", each if [YearsOfService] < 2 then "New" else if [YearsOfService] < 5 then "Mid" else "Senior", type text),
				    Result = #"Added Tenure Category"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns and 3 measures: EmployeeID, FirstName, LastName, HireDate, Department, JobTitle, Salary, Location, ... (12 columns total).

