table 'Business Unit'
	lineageTag: d931e5df-1dc6-48c6-a621-c8299139c136

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 56236128-a0aa-4cf2-89c9-d651bba9caed

	column Value
		dataType: string
		lineageTag: 02d796c6-da91-47bc-aebe-c9b3aef54e15
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-f56c7cc6-8dd7-4d96-b485-4ff17509bf46' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

