table 'Fiscal Year'
	lineageTag: 13dba092-9e9a-4632-a7f6-5c6aafa611a7

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 22e37b26-01dd-438e-92e5-b3883e4cf6d6

	column Value
		dataType: int64
		lineageTag: 3b857dc0-b641-4b00-8b2a-c0f2d276cdda
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-3c169288-b607-4684-bf38-c71f003b9432' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

