table 'Business Unit'
	lineageTag: ac762f24-1f85-417f-85fa-e453826c906e

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 86c4ddaa-1d38-4d0a-9350-7fde25c1a7d5
		annotation Copilot_Description = DAX: SELECTEDVALUE('Business Unit'[Value], "All")

	column Value
		dataType: string
		lineageTag: a1080b38-6c27-48e9-8279-70b6d3ccd8ba
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-0951f431-3676-4baa-983b-2773a7a720de' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

