table TestData
	lineageTag: 38650edf-f1cd-405c-b254-0495086e33f3

	column 'Account Number'
		dataType: double
		formatString: #,0.00
		lineageTag: d057c44b-fb12-41bf-bd1d-c40bbde325f2
		summarizeBy: sum
		sourceColumn: 'Account Number'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Set list'
		dataType: string
		lineageTag: c98bc3dc-2c72-4e3f-98bf-5f25b7123ca1
		summarizeBy: none
		sourceColumn: 'Burst Out Set list'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: double
		formatString: #,0.00
		lineageTag: cc208566-cca4-4e53-9b27-59dfa259b939
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column show
		dataType: string
		lineageTag: 894c0976-c80b-4181-a433-6b3c510aca3c
		summarizeBy: none
		sourceColumn: show

		annotation SummarizationSetBy = Automatic

	column SHOW = IF('TestData'[BurstoutSet], "Selected", "Not Selected")
		dataType: string
		lineageTag: 1c55df78-5f2e-43aa-942d-1f52cc5ec7fb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column BurstoutSet = ""
		dataType: string
		lineageTag: 70b45785-4789-4d0f-a713-365f1d3d3946
		summarizeBy: none
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'TestData-806208ea-9a90-49fc-bc1c-7d3cc80006a8' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("b5dpm3ihhu.database.windows.net", "EmptyDB"),
				    #"TestData Table" = Source{[Schema="dbo", Item="TestData"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"TestData Table", {{"show", "Show"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

