table Calendar
	lineageTag: 5ec9b85a-2baf-4cbf-b3ea-02f6ae4e4318

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 0ab030a0-736f-455d-b9c5-74faa2e2f4ff

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: afcbb4e2-c783-4835-8847-310a0695ec63

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: dcd7387f-1d03-425c-8548-263526c70d1f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8411c540-eca1-4d36-aabf-b413b278a6bf
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b43d4d95-7818-4bd0-8be2-c76c4010fc4b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b7e78082-1874-4790-a2e1-4988dff03ece
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: cf4c82d1-b9f1-4d20-adde-c2891eeff769
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 48798fca-8a0b-45b1-bdc2-0545136a285d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3b15edcf-2fc3-4349-a6ee-b650f714e704
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4d5c5046-c692-495b-9705-b83229b9133a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: dd3d97b8-92aa-40b1-88a3-9cfd2c45f344
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8ad6910d-db04-4d70-860d-a249f612add6

		level Year
			ordinal: 0
			column: Year
			lineageTag: c6be90b1-dc4a-4991-9a04-297fd79469da

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ca4d7d46-5148-4df5-b8c6-8462ca073c66

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 46e2936a-a2c4-47fd-8c85-f923cd6b8374

		level Day
			ordinal: 3
			column: Day
			lineageTag: c197a5ce-681b-42e8-b0a5-868be4c02ef2


	partition 'Calendar-ee26a518-b505-4466-96a0-2cbf2dd0ab94' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

