table Calendar
	lineageTag: 8987cf9b-8acb-4593-abc1-605ad2439e67

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 4d421300-b4a0-42e0-8f70-ae44e93289e2

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 12eb7300-0231-4c75-be05-708ffa7d0458

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ed5d05ab-2f71-4de4-938b-007774aa92ee

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 434d93bb-13c7-4161-ad9f-5ed12d83246e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 7be2f3d4-c578-4ae6-83c5-1676783d2349
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1f946099-b73b-4f58-a455-264a88641c62
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e1380d90-feb1-4ba7-8954-8e461b7dcb4a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0da145be-b183-4543-b9ae-a2213d8ff1a9
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f021335c-3c37-417d-bf48-dc13dc8e00de
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7fb529eb-3607-4ea5-8428-02e4ccb3c3dd
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a4bd9006-be3f-4124-b6c8-f0f0a5eae7d2
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 93c14a78-cb3d-400e-b677-26ef649eb067

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6a7e3d58-b2aa-486c-8425-266252e63373

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 2e336d03-2f92-4b31-9f29-b65cdeafbefc

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 2a2512cf-7eb9-4aaf-9f1d-1c93cb4052f9

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7182ca69-43c0-4698-a839-04f8376e5b6b


	partition 'Calendar-f786a740-e954-451a-9655-a12af0fc677b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

