table Calendar
	lineageTag: 92a070dd-5ba3-41c7-a4bb-f960f3a2674e
	description: Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		description: DAX: TOTALYTD([Total Sales], 'Calendar'[Date])
		lineageTag: c5f71bc6-e976-4de0-a8b8-25fe0d8e23f1

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		description: DAX: CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		lineageTag: f6e77e44-c467-4ff5-bb83-e8a63979e26b

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		description: DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		lineageTag: cbbda708-18e3-4efd-859c-e54c8b1568c6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 005e5f31-a1a1-483a-b12f-1ab0557af47e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime. (table key).

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 09c54eb4-310b-4cda-b3dd-d52aa883dfb1
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years
		description: Int64 column. categorized as Years.

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e2ac78a5-fd21-4a36-b820-1e4216e69d00
		summarizeBy: none
		sourceColumn: Quarter
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ee0db9e0-31f1-4452-a67b-cf75bacaae4e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months
		description: Int64 column. categorized as Months.

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: dc5cef15-9ee8-4414-8020-c4ad3314cd1a
		summarizeBy: none
		sourceColumn: MonthName
		description: String column.
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 945e85b5-1090-49f0-8798-0eec03a8534b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days
		description: Int64 column. categorized as Days.

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 5649e4ad-1277-46e3-9ec8-876094a8e8cc
		summarizeBy: none
		sourceColumn: DayOfWeek
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 00c188b6-22bc-4eb4-adac-aa81844ccb72
		summarizeBy: none
		sourceColumn: DayName
		description: String column.
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8d72dc6d-a70f-4caa-9557-9cab93d185b7

		level Year
			ordinal: 0
			column: Year
			lineageTag: 370300d3-6423-40eb-922b-79c93783d4cd

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 4ff7d2c8-3f82-49ce-8eba-71d07ff12812

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 36cfa8d6-a056-4dcc-9324-764e174c75ca

		level Day
			ordinal: 3
			column: Day
			lineageTag: ae86ca75-dc81-4aad-b1f5-769c3edaaaee


	partition 'Calendar-968fe258-7c6d-462e-9ffd-1f32efbc0d1d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

