table Calendar
	lineageTag: 9bf6147b-a9cf-415b-97f6-1506c69f4fe6

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8e819be3-6357-4cbb-ae03-47384cf196c2

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5798d51a-326f-4bcb-b563-8024474aab7c

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: d2a9e4c0-3106-43fd-927f-f1408780a0d5

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 03bb9272-f9c3-47a1-a964-f718ad44a931
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ae608f2c-28fb-48c8-b586-fc7c1d786f96
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d794367f-9390-4518-a17f-cb3d137d2ea1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 90e48451-7c7a-4f53-83cb-fa023b2fdb87
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d31385ee-5777-4707-af4c-6cd7920d2337
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ebfd06c9-76f6-4cec-9304-53a513bc2340
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 22667cc7-42c3-488d-8a19-f5ba0a70e8a1
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2771b471-88c2-4a34-8801-12a4a353455a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 63e79211-a5fa-4403-aed5-5d93c2fcfd0b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 5d382c59-076c-4b58-826c-496ec8d3d8e3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 851da178-416d-4e0a-adbd-bd5ab4701eb4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0d33fba0-08cd-4e7c-9383-228aef25bfeb

		level Day
			ordinal: 3
			column: Day
			lineageTag: 719cf588-44ca-4189-b5f0-b6564eddf30c


	partition 'Calendar-2b01e691-dee1-4319-b9e5-73fe421adf50' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

