table Calendar
	lineageTag: f16747e7-29c6-476e-b6a6-2f06e65e80ce

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: bf0de930-6ebd-4caf-ad57-8acb738a5dda

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d42bce1b-2585-4e8c-be05-ffc62a8debaf

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: c566de80-faa4-44e5-ae87-b52a27bb213d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6b158a7f-e432-4baa-9d3b-121ed5903fe7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 4966cdf6-cd0b-4b35-be2c-41f29349f874
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 80b219a1-833c-4a83-a434-a68643eab1d3
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f82a3ce1-c045-4539-98c0-4b63522a73d4
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a853ced6-6d17-4db6-ad12-5ff8b4cc84f5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bc15e773-f69f-41f6-9796-59b1dee40130
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 865a26f5-49ca-486c-9d8c-809fd0c13bda
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: daf77549-cfef-4ef7-a8c9-b3fea007e403
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3ad704f3-9f66-4204-8f80-6256bce42c6e

		level Year
			ordinal: 0
			column: Year
			lineageTag: ff16d8ce-c022-45ae-8dfe-1cb281f4d1a1

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d905171f-fd02-409e-a5c8-293e94297c89

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f62a6efe-dd56-41e5-8de1-6c1cd4eb9453

		level Day
			ordinal: 3
			column: Day
			lineageTag: 611d5c30-0526-4416-bdee-5790e10c201c


	partition 'Calendar-3015932f-988f-40eb-9ec2-f557d72269eb' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

