table Calendar
	lineageTag: 7d088fd9-0c5f-43b0-8255-f0baf79ccdec

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 18036f5a-69f6-4ca8-9b75-34468c7d0048

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7ec336f7-0a4d-4e4f-a990-39f24abad877

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: a209c04d-37a7-4210-ac8f-9b74adf30df3

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 147e6875-b459-4ff7-8bcb-aa1adfc9884e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b166d89a-4f52-4457-994c-777c94454a87
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 159d5737-34c1-416e-ada5-086af9794511
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: afcf299d-083c-43ad-b6dd-fd68e416cf69
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d39fc0a5-1a80-4df5-a983-1aeadb5e153d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: fa6970be-97da-452c-8098-544eee166bb6
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 951aa8e7-f50f-493a-8a1f-ed4655297ddc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f0ec5b69-0077-48b3-8c05-c5ff9cc0da63
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 04d420e8-5787-4c71-8738-d58b48a90fc8

		level Year
			ordinal: 0
			column: Year
			lineageTag: c2c5a1bf-c7f8-4a0f-8f9c-cb2774dee18f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 318f27af-520d-47dd-a6be-ef9c66401fb4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 203e5717-9703-40fd-889e-53e7da6cabe3

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6c7a73e0-2a26-4e9f-a6a7-3381422cd1a6


	partition 'Calendar-9f34c70a-f054-4645-85be-779484aeb46e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

