table Calendar
	lineageTag: 9b18d08b-00f0-4c7f-aaf1-a3e44b0849ed

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 03c454b3-8b45-4fa2-8fe3-387dbb263766

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ae591c98-ce50-4457-9280-7b28a42f24fe

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 123fcd6e-9aec-4fc8-bcf3-adf5d06ed38a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6fe267a2-dfd5-4ff4-98e2-5db6e4a7578e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e14c1604-380b-4042-b9cb-ca22307dd08f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f36313ec-0fba-4cb7-abad-907a574d2e8a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c08ef371-d631-4362-b834-f06254df4b6d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0a21ccfc-aee8-4304-9df1-442244491d2a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 4a1e3847-f8f3-44d4-b1e4-29cff5d1f046
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 3de3c36f-a39a-4580-83ad-5b28d9974cc2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 35631813-29cb-48c1-a8d1-eab5c07eeb7d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6bc876ad-ad4e-4f32-af6b-b5033ba583c6

		level Year
			ordinal: 0
			column: Year
			lineageTag: bdf932b8-87cd-450f-b7a5-77a2e5124e4c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b0c8b654-a5f6-445d-a661-204c76ed008c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c0f06cb9-fab4-48d7-9ddc-a35c22703bd2

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4a3b4d1a-0ad3-492b-a9d6-f6f823404455


	partition 'Calendar-fec2908d-7440-46a3-bd1c-a55342826f66' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

