table Orders
	lineageTag: b4438d14-02b9-4601-809a-5eb5186d87a4

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: aaa50167-03f9-4fac-918d-f9209819c22e

	measure 'Total Profit' = SUM('Orders'[Profit])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b78699d2-2915-49ba-bfac-692d7bc979e9

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1dfae0cc-fd7d-4897-a178-e19cdb64a238

	measure 'Number of Orders' = DISTINCTCOUNT('Orders'[Order ID])
		displayFolder: Measures
		lineageTag: bdaf835a-e0ae-4ad1-a725-81cd7f823f13

	column 'Row ID'
		dataType: int64
		lineageTag: 04dafa34-c63c-43db-adc6-64138f03443f
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 4a81b9e4-6891-423d-b423-64ce6eef175e
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: cb8af313-024f-4286-a4e6-5c901f88fa5f
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4c044698-37bf-4e31-9aa2-db6b274af2ec
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 5d499cdb-b779-46d3-af57-b2b37facd5d1
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: de8096b9-7969-4165-958e-fac5de5c7938
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 0da9fb8f-90d3-4873-b3fe-5e609acb49e4
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 1814bf8b-290c-4a85-8d01-db161675ae17
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: b17e486c-a62b-43b4-82cb-7b6e028f7038
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: afb706e1-6604-4efb-9e29-354d9da73d0a
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 282f789a-e895-4e0c-9aed-c4d0302b5400
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: 3ee6d293-bd69-4524-8ba5-71750ece7c9a
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: df0c9e9c-711a-4555-a6e7-488dde0549d5
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 93b48e15-bc33-44df-b718-869e2fda1d5e
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 26d2c607-f70b-47f2-b0b4-21a54153b3e1
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 940306b8-bd73-4c27-b0ae-c53fff2be1f1
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 61fa1936-ae75-40f7-a67d-9af230a651a8
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 3673ce8f-b6ea-4364-a892-421dfda031f7
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 8f5bdb8d-d09e-4b78-b8c1-0942a4bb0f7b
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: fc020ee4-6962-40bd-9575-14fb677127ec
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 091d19ea-35b0-4d5c-b6a6-0c3ebcb1af81
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	partition 'Orders-d587591d-871b-440e-a4dd-cdddb49c45b5' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country", "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"}, {}),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

