table Orders
	lineageTag: 8bc5fd60-7f7c-422c-aed9-de99881c7ec2
	description: Contains 21 columns and 4 measures: Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, ... (21 columns total).

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([Sales]) | DAX: SUM('Orders'[Sales])
		lineageTag: b935b8e0-b257-4a9d-b63f-03904f93bd16

	measure 'Total Profit' = SUM('Orders'[Profit])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([Profit]) | DAX: SUM('Orders'[Profit])
		lineageTag: 30498ed3-4472-4869-b886-0a938fad77bb

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([Profit]) / SUM([Sales]) | DAX: SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		lineageTag: 6963d9b0-e43b-4e95-a9d1-d6eec776a356

	measure 'Number of Orders' = DISTINCTCOUNT('Orders'[Order ID])
		displayFolder: Measures
		description: Migrated from Tableau: COUNTD([Order ID]) | DAX: DISTINCTCOUNT('Orders'[Order ID])
		lineageTag: 23bc6d1e-b166-48da-80bc-af0e2a88b710

	column 'Row ID'
		dataType: int64
		lineageTag: 813ab1c2-c795-4b85-96b7-b4fd697c9dea
		summarizeBy: sum
		sourceColumn: 'Row ID'
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: f2154ab4-4f1a-4320-aa77-a406084b9b69
		summarizeBy: none
		sourceColumn: 'Order ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 81eadd0e-36ab-4e31-ac72-c05617a96b01
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 87a05c21-ee38-40a7-8025-7394cf0c35da
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 9b725dd0-4633-451c-b387-0d65c83e2856
		summarizeBy: none
		sourceColumn: 'Ship Mode'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: be19d26f-4b1d-44c4-9498-6029c70b9fbe
		summarizeBy: none
		sourceColumn: 'Customer ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 25a8d718-00d3-4e2a-9490-29e1b0ec8003
		summarizeBy: none
		sourceColumn: 'Customer Name'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 03c85c3f-bd99-4ccf-abfc-91763dad22d4
		summarizeBy: none
		sourceColumn: Segment
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 17bb054a-46f4-40d7-a39f-bad7dabd8b6a
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country
		description: String column. categorized as Country.

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 1213938b-f43c-43b6-a34a-d39d28a7a7e0
		summarizeBy: none
		sourceColumn: City
		dataCategory: City
		description: String column. categorized as City.

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 6aa17c4d-8db7-404a-984e-3dd54c6ecad0
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: 5271e860-c8fa-4c04-9006-c279ef1d08d8
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode
		description: Int64 column. categorized as PostalCode.

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 10a477fc-8a06-429c-8397-bf6bef34c7f5
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 96ec6d79-f8e1-49fe-8423-94ef4f028fe9
		summarizeBy: none
		sourceColumn: 'Product ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: f2e61c16-c391-40a9-b9a8-b8dd1aea7504
		summarizeBy: none
		sourceColumn: Category
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 2efd830c-7bbc-439a-a3fb-b789131f62f4
		summarizeBy: none
		sourceColumn: 'Sub-Category'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: a6eee5d5-3841-4c1a-86c2-ae30358b189e
		summarizeBy: none
		sourceColumn: 'Product Name'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: b41e73d3-136b-4ce2-8960-d67feb770e52
		summarizeBy: sum
		sourceColumn: Sales
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 050119f6-f187-4e36-89fc-6eb9fbe4f312
		summarizeBy: sum
		sourceColumn: Quantity
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: f134a257-d4a1-4c29-aa73-5b0f48a31ef0
		summarizeBy: sum
		sourceColumn: Discount
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 5fbc7450-f146-4230-bf6f-81203708c59d
		summarizeBy: sum
		sourceColumn: Profit
		description: Double column.

		annotation SummarizationSetBy = Automatic

	partition 'Orders-4e53bce8-9156-4677-bcc9-055bbb316ca0' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="Orders",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country", "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 21 columns and 4 measures: Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, ... (21 columns total).

