table People
	lineageTag: 5c86590e-1e8c-40fc-a1de-7fd9e5a73d05
	description: Contains 2 columns: Regional Manager, Region.

	column 'Regional Manager'
		dataType: string
		lineageTag: 895b1b91-6538-41fa-8f7d-d3f381acf004
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 9e176050-9400-4125-870c-2d5fdc3f3490
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	partition 'People-96e6cca9-738e-4878-9a21-3f7fdffe0c6f' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="People",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Regional Manager, Region.

