table People
	lineageTag: 839a16ec-3d60-4787-a8a4-ec2562d0c27e

	column 'Regional Manager'
		dataType: string
		lineageTag: d72b792e-7f86-4bb8-b730-d065051b2901
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 8de465eb-9697-4e6e-aff3-b792522dbcc6
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-8f6ada7b-bd70-4e2b-9054-f4c950e55c28' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="People",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Regional Manager, Region.

