table People
	lineageTag: fbcd3b85-692e-403d-8210-9dfae11f495e
	description: Contains 2 columns: Regional Manager, Region.

	column 'Regional Manager'
		dataType: string
		lineageTag: 7b90410e-a6ff-47d3-b9e3-50dd91b3618a
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a71838ee-0a6c-40ad-b7d9-f2039b442786
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	partition 'People-ea7a9a88-cac5-4306-8841-f1a1aba493e5' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="People",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Regional Manager, Region.

