table People
	lineageTag: 8ea64969-6241-4802-8d02-e28c133b91e3

	column 'Regional Manager'
		dataType: string
		lineageTag: 73fa8648-ecc0-4f3d-95ba-ebff649e9e0e
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 46d998de-3722-4f57-bdb9-bff66a969a90
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-63298b8f-0e5f-4ee3-9812-cd0a6070c8fc' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="People",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Regional Manager, Region.

