table People
	lineageTag: 414001c6-6882-4f28-b08c-237b5e6ed2c3

	column 'Regional Manager'
		dataType: string
		lineageTag: b6d9e406-0d92-4f02-aa3d-6479b445fe37
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b0284245-7adc-43fd-b87c-cb655031eaac
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-3e8520e5-ebdd-42a8-9775-47dd4930f858' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="People",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

