table Returns
	lineageTag: eed6702d-7a05-441f-ada1-3b9fd0530177
	description: Contains 2 columns: Returned, Order ID.

	column Returned
		dataType: string
		lineageTag: 37f116d1-cdfb-49a3-bcd4-096f9949769e
		summarizeBy: none
		sourceColumn: Returned
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 02f30ff8-231e-41e2-8d77-940ab500901d
		summarizeBy: none
		sourceColumn: 'Order ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	partition 'Returns-833659a8-926a-4fd9-bbf5-48ba1611c53c' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="Returns",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Returned, Order ID.

