table Returns
	lineageTag: e3a3b510-0be2-4ace-bfc4-a1592b007b60
	description: Contains 2 columns: Returned, Order ID.

	column Returned
		dataType: string
		lineageTag: 2e902246-a2e0-495e-b527-7bb1f52d48b9
		summarizeBy: none
		sourceColumn: Returned
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: be5926f6-1bea-498c-9229-95d4188ca9af
		summarizeBy: none
		sourceColumn: 'Order ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	partition 'Returns-d3fc61ca-96c7-433b-816e-e440ee13070a' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="Returns",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Returned, Order ID.

