table Products_Master
	lineageTag: c4b7d04f-5137-4153-98ad-227f8cdd912d

	column Product_ID
		dataType: string
		lineageTag: aa3b411d-ed22-4435-bead-2613a0e2ab59
		summarizeBy: none
		sourceColumn: Product_ID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: be54c34b-bf67-41cf-b744-106c1a3777f3
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 347b293c-62c0-4461-8bd3-6bad65884713
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub_Category
		dataType: string
		lineageTag: e1258b2f-2cd3-425f-94fa-26f24f46c0b4
		summarizeBy: none
		sourceColumn: Sub_Category

		annotation SummarizationSetBy = Automatic

	column Unit_Cost
		dataType: double
		formatString: #,0.00
		lineageTag: 66162094-747a-44d1-b02f-d94df72063ff
		summarizeBy: sum
		sourceColumn: Unit_Cost

		annotation SummarizationSetBy = Automatic

	column Unit_Price
		dataType: double
		formatString: #,0.00
		lineageTag: 55137882-cce9-4e2b-b9f8-42c3e15d690f
		summarizeBy: sum
		sourceColumn: Unit_Price

		annotation SummarizationSetBy = Automatic

	column Supplier
		dataType: string
		lineageTag: 8eb20ff1-630c-4da4-940d-a73255df9085
		summarizeBy: none
		sourceColumn: Supplier

		annotation SummarizationSetBy = Automatic

	column Weight_kg
		dataType: double
		formatString: #,0.00
		lineageTag: 4c261c79-9920-4356-9f9d-798f970fd77d
		summarizeBy: sum
		sourceColumn: Weight_kg

		annotation SummarizationSetBy = Automatic

	partition 'Products_Master-0895af0d-f0cf-4046-9b68-b8f7e590407d' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: textscan
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Product_ID", "Product_Name", "Category", "Sub_Category", "Unit_Cost", "Unit_Price", "Supplier", "Weight_kg"},
				            {
				                {"Sample 1", "Sample 2", "Sample 3", "Sample 4", 5, 6, "Sample 7", 8},
				                {"Sample 2", "Sample 3", "Sample 4", "Sample 5", 6, 7, "Sample 8", 9}
				            }
				        )
				    otherwise
				        #table({"Product_ID", "Product_Name", "Category", "Sub_Category", "Unit_Cost", "Unit_Price", "Supplier", "Weight_kg"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Product_ID", "ProductID"}, {"Product_Name", "ProductName"}, {"Sub_Category", "SubCategory"}, {"Unit_Cost", "UnitCost"}, {"Unit_Price", "UnitPrice"}}),
				    #"Proper Cased" = Table.TransformColumns(#"Renamed Columns", {{"ProductName", Text.Proper}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Proper Cased", {{"Category", Text.Trim}}),
				    #"Replaced Nulls in Weight_kg" = Table.ReplaceValue(#"Trimmed Text", null, "0", Replacer.ReplaceValue, {"Weight_kg"}),
				    #"Added Margin" = Table.AddColumn(#"Replaced Nulls in Weight_kg", "Margin", each ([UnitPrice] - [UnitCost]) / [UnitPrice]),
				    Result = #"Added Margin"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns: Product_ID, Product_Name, Category, Sub_Category, Unit_Cost, Unit_Price, Supplier, Weight_kg.

