table Calendar
	lineageTag: fc20ab36-3c60-4414-a0c1-b4e23dfcb969

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: e65c741a-1979-4759-969b-c57081ffad29

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 4092ba42-713e-4d48-87ba-4e93cd545432

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: c706f485-4fc0-466a-86ba-871a8ede4a39

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5be70d17-093b-4bb7-bbd7-bfef663e3adf
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 12e138e7-baaf-4539-ad34-32217a460936
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 00602d40-e97c-4496-a680-222a2a6f4e26
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4ae7ed10-8c70-42f4-bd87-03abcbe61aa8
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 6c286668-5f11-460c-83b4-c33adabe4e1b
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 6647b8f0-36d9-4527-83ac-62e68ead40f4
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d29d7467-0b3c-4bee-a9c0-8a919e4fbb68
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 0834b1dc-6c7d-4033-8b9c-e22fe283003b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 43b60ffa-f0a1-4bce-a100-cf2d90ecbb0f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7448f52c-bd2d-44ae-94ac-d76b99efc18c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 26d2dc45-1efd-4f93-9a32-0cae5fd7f83d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 2b5a6b9d-522f-4031-b185-a19eabe47d92

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5b701256-ac74-41b4-90da-a6791e3d8a61


	partition 'Calendar-4548f9ba-401a-4e65-b501-fccf189ab436' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

