table Calendar
	lineageTag: b62b2aa2-d295-4367-b4d6-fedaf40084d3

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: a7d39512-2df7-42d0-a2c1-b9b316e89f49

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 2a47246e-da83-42ea-b59c-9c5d9d56ea10

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 6c5b6e08-2679-4fac-9aa6-c893d26ddc3d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f06bf82a-9560-4667-9a6c-2926ba964bc6
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9f19d12d-1b1e-4c83-b519-e3b65310065f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ff54156c-f484-4f6c-8347-26391b9d66fa
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 6112f299-c050-4af7-b2f7-4d9b68fe05c8
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0d0b2c65-63b1-4e68-b23f-15cad04bf827
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: be0d30e5-9646-4f84-98b0-eb6eebee86ee
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e0a05140-97d1-4332-bf90-8a7810937c78
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 96bf0bcc-3d08-452d-b63d-75e29848e219
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 57e8382a-6759-4e48-8782-043fc497be07

		level Year
			ordinal: 0
			column: Year
			lineageTag: c0206fc4-fa36-4cde-9764-9b9b73f2b72b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 6d93e3be-83dd-4754-b022-1aed7ae67bd5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 54f04430-7019-4403-935a-916445af7d32

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5e7bc715-3b62-4d98-9e39-43f10f2fac96


	partition 'Calendar-6503271e-ba3c-4534-8949-404925e29436' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

