table Calendar
	lineageTag: 21854627-293f-4d9e-bb44-769ab131d7b9

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 804e4471-6ae6-41f0-a646-09d1106091f1

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 95b53db8-2026-4284-b426-9ecea07083b4

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 2613e0c0-d26c-4cf8-8d94-5e5759c99dc7

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f8da1fe0-6403-4e17-a144-59476d5226a9
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b39ac2cf-ab6f-4cb4-8b52-6be5ddd97a63
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0d4ca0ec-ee2a-44b9-8102-ab60a7266c56
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 6258043d-78f1-4834-ba30-193e48b94e75
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 37026216-40c5-4bb4-bd70-2d36915c057b
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8fee2cb2-cc03-4865-b544-4788709c0960
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 8713afc9-b48b-4221-b2db-25cafb323e37
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 5decb2c3-62a2-430a-8a5b-732813d13d2a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 12f1758e-db3c-4d5d-8cb4-77e3269473ec

		level Year
			ordinal: 0
			column: Year
			lineageTag: 284eb389-6677-4fc0-b2a6-7f2978567fb2

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 74143303-1a02-4a22-bb83-8e274aee67d0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 516f1275-9495-422f-bd43-4f9990fff6f7

		level Day
			ordinal: 3
			column: Day
			lineageTag: 8ecfda1d-7c61-4011-8d77-b15aa499451e


	partition 'Calendar-5d05c730-4c11-43e5-9ee4-1075e4eb8a05' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

