table Calendar
	lineageTag: ab1b393c-c2bb-4654-ac56-45cebd27bd4d

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 10163cce-7d67-4df5-be71-70da630f5b16

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: fb3f4ba1-ef15-4d57-b6c0-07517a463f82

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 3326c916-cec0-4b16-aed4-b35c3c8f5bc2

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b88dd127-7839-44ff-a4d6-aa55e96908d1
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9a5ffe93-29d1-4974-98a5-1fcaa44fcdd7
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 6e6044cc-d899-49d2-a96b-02b872c0bb70
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b1cd0ef2-cdfd-470f-a130-2745e86aad53
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 06d4ef15-0ce7-49c3-aa16-390a298e424c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1c0914ec-64f3-411c-bef7-2f8ba4cbeadf
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 9aea5d4d-b794-4511-b964-edbde4799360
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 28d2387c-59da-4f57-9e62-a0c89941c373
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4b59fcd4-b792-499c-9189-94be94d25c9f

		level Year
			ordinal: 0
			column: Year
			lineageTag: f5d29b81-1fa1-4c2c-9013-4bc06a3bba58

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ece6307a-297f-415f-861b-d3c48bc004f9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3bdffe8b-f9cc-46a1-8aca-4f502e94b864

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6495ef4e-1834-4df8-8117-70d70d691bc4


	partition 'Calendar-11e47320-cb27-4c40-a098-2007e9205b71' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

