table Calendar
	lineageTag: 8cad0836-5138-410d-ae7d-390109dacf21

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ce7f3a0d-dec9-490e-8f62-3ca73d1e0518

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 646f29fe-1368-4a4e-af90-823ce98c87ab

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 78a930e3-5c3f-49fd-94e3-cd7c2dd37b70

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4da1c19b-7a18-435c-8617-bb67f90bf712
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e1598f0e-f18f-41a2-a47f-dcca42e90d8a
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f7857e91-51ca-4a1e-8f77-7a16f3cf4c86
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7ac85578-3153-40cb-948b-cf37659203f8
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 89ab591c-a76e-4e3c-a2ca-9fd20c9c7fc7
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e31ed593-e5c7-44c5-b062-90c346643d6a
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 22cfb2ce-464d-4c6e-a30e-b370e802a6ab
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ad2d6ebf-a39f-43b7-a03a-cd2de9e30da7
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c555e6ab-9fe0-482a-b248-15b32dc55246

		level Year
			ordinal: 0
			column: Year
			lineageTag: 93784d8c-2396-4b8b-b441-eb04f12c0216

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c0b81816-18e3-4268-996d-7acf4e3e3016

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8fd32d0e-eb5c-4242-a92f-d4c339ea6645

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1a551f75-e135-4db9-8054-90520d2002b0


	partition 'Calendar-1b67a97b-a5ea-4e15-8b22-13f858136ef8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

