table Calendar
	lineageTag: 5233387e-5c51-4598-8fbf-8148d5946f2e

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: fb116a06-fbac-41aa-be24-7a0d9269b97f

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: fa1b8118-3766-477c-bcd3-8b7384ad0a9f

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: be4a34a0-62b0-4530-9a48-3790206f8216

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 7c82053e-c243-4927-a551-f2b866f9e59e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f316998b-d6e7-438b-8da1-cf2d6b579990
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: abf31e17-2c22-462f-82a0-bd03cca5bd8a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2f6b419d-cd79-490c-8fab-a0f5ade0185f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e760088a-f18f-48c0-bd0a-1dc476852cdc
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bfd9cbbd-82e7-498a-98ca-0d504207dcbe
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d1450d35-cc8f-40f2-8b72-b61c0c6e08e1
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: bee361ec-cd6b-4b58-b2d3-c25e7a07ec26
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: cec093d9-42bc-4a6d-8cbd-3bbadc14a8f9

		level Year
			ordinal: 0
			column: Year
			lineageTag: e9d4cae1-3526-490e-ad98-592f8a878bf9

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f871798e-1c5d-4afe-bfd2-60a2fa2538f3

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 23c9ff97-6b6a-4aae-a852-67fbb2d32867

		level Day
			ordinal: 3
			column: Day
			lineageTag: 59193a74-7575-4e7f-ba02-7944a29d7a43


	partition 'Calendar-4ae69a71-d0e8-4349-8a34-271b504c6901' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

