table Calendar
	lineageTag: 27d96f82-d3ac-4d56-adc1-032d0fc7dd50

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: cc412067-25b2-4be2-a1d1-574d3275aa50

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 98c789e4-28c4-4d6e-ba03-9f1ec61ef007

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0f87be45-9a97-4ec5-9af2-c390fa3c6616

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 526ad944-9758-4784-82ec-44374fe16993
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: aa37d29b-3e4c-4bbf-9ad0-051387a95a75
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 9bc4f8a4-030a-49be-8b83-f00b4c57023e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: aee65f85-8837-4d9c-850f-70737da83bc9
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 81ab6bb9-935d-4f6e-87e7-2259aa87468e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 4b1bbd71-fd38-4e26-af18-efb35df6b261
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 1d77b9e4-7658-4d6e-8735-d90898703fa5
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: feda3a66-2d71-40de-98ad-ae9db12a3d04
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4573ff13-4ffb-47a9-938d-9283778b4163

		level Year
			ordinal: 0
			column: Year
			lineageTag: 94922620-eb02-483d-8794-e12ccb18c44f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: de16515d-2fa8-4ea4-96c4-26e99931bf82

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4ad9b7ca-3ca3-40d3-ae38-33d25c064e3e

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3d3fcec4-78df-4953-85be-1174b6528d6d


	partition 'Calendar-27273980-66ed-4f28-81d6-2302643e6e06' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

