table Calendar
	lineageTag: 3591c1ba-c419-4392-8ef6-ca200b0fe125

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9e4e00c6-4e1e-4154-8ac7-d244b98ad044

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 57ab2176-02db-455f-a9aa-110d3d19d08a

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 91e07204-d56c-4b14-9657-da01eeab661a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c9f1ad4f-8bc4-4c5b-bbda-572fc70331d1
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 558ca75e-224f-47ab-b5ab-99a8c3bb7005
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b6210408-bdf6-4bab-b070-a96f4e1abdbd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e0119467-08c0-458f-bd1a-27c452439b1f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4d42b0cb-645b-41fc-bac0-8c11eb4289ee
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bd03baa9-ed86-4282-b58e-d0827e346a23
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b2afec54-2c1c-4db4-a6fc-565d4fa70a78
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 58606d36-5aac-488a-81fd-ee9a98ae3cb1
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: d1582104-7a1b-400e-a360-41fa008c5156

		level Year
			ordinal: 0
			column: Year
			lineageTag: 584f44ee-426b-4493-ab8e-5f195bbafc84

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: fea8de8e-42fa-4e36-9d39-0638d2bf4f59

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 92fa966c-938e-403a-bedf-d2af8fb29133

		level Day
			ordinal: 3
			column: Day
			lineageTag: 964b90a9-015d-49c3-86ec-58584c271f01


	partition 'Calendar-775d7713-8e9f-4c3d-9a96-5f9fb3c87a57' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

