table Calendar
	lineageTag: 807d9a06-2457-4755-8256-e9000d1ef395

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9175386a-9e16-45a2-abd0-c377538114f4
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 58478bab-ceb8-4434-94c5-968c91f9d54c
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 46acb0a1-0eff-42e6-af4e-f9ce72821c6b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7690e45d-0169-4e36-ad59-064f85bd5c1b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 86abfda6-283e-4ecd-af75-f72764c9b0aa
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 91c2a540-40f3-4a95-a11d-21c8ad6da390
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 21cbe4be-829f-4358-a84d-12431d20de18
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9548be1e-ace9-447d-befc-037e79bade40
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 122d7f75-e0a2-41be-b932-765828369adc

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6e1b7823-4a21-4bf0-9e0b-8eaa06a77cbc

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 5b08397c-7eff-47c7-b319-7f44d78663ee

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: b21b870e-2866-48fb-bffa-c9aabdcaa77d

		level Day
			ordinal: 3
			column: Day
			lineageTag: d9159bfb-ca97-4c44-ae46-9cf899c8ed59


	partition 'Calendar-680d22ce-1efd-41da-baad-56913a0d3ea1' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

