table Calendar
	lineageTag: 480827e7-783e-411d-803e-9fcc21bfb16f

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 2fe396a2-ec7f-43a7-9a26-ccdb280b6e88

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 2a6afd42-c7d9-4203-a151-1b1263473f58

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: a43750aa-2a47-43c8-b2d1-81452deebb61

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ff712637-a9d7-4588-bf92-e70ca31446c9
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ca7d3ba8-7543-426e-840d-fab935809f70
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7897edfa-8766-4402-9c1c-b4c040858dd5
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 9757e7f5-846b-4c11-b219-3f17cc03add4
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 5869e536-8d1e-4a03-afae-ca6ea57cd221
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 4388c52d-79c1-44ff-b699-4a05c48efd03
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 5d063d53-9278-43a1-8c0e-31b4d6f21539
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2c77b944-6b8b-4e96-aeca-efe108b3aca0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 85d53b16-4432-4082-b6cd-9c70e93ae1ca

		level Year
			ordinal: 0
			column: Year
			lineageTag: e5023a15-a2be-44ab-a24a-149425eb3a0b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b8101a00-9af1-4123-84f4-e919a64917a5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 119429ca-a412-4f3d-89c3-b45be0ab41f6

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1137515e-e460-4e66-b773-79dcf0a222fa


	partition 'Calendar-efe83742-831a-4c9b-9240-979f5bb7dfd2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

