table Orders
	lineageTag: b7ddf3d5-8106-46a5-bf2f-f0351468eca6

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c96f91dc-250d-437f-89bc-e2e4ca5c7ccb

	measure 'Total Profit' = SUM('Orders'[Profit])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 41d4db90-7a58-4b0f-83d5-041add664af4

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 351489f0-5a6a-4ec8-a05d-bdf874cd6f98

	measure 'Number of Orders' = DISTINCTCOUNT('Orders'[Order ID])
		displayFolder: Measures
		lineageTag: 41b4ae05-7ea2-4a3f-8643-a45ee92c9aba

	column 'Row ID'
		dataType: int64
		lineageTag: 92eaadb3-7c28-4bf4-b753-642bae014585
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 6ba3780f-aaa3-449f-88bc-0160456693b4
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 19564a8d-ded9-436b-bf4b-c67cab218842
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4724f952-4752-4c82-ba53-39df5224b2f5
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: f4db3be8-92e0-4f1b-8340-2ed2838f2378
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: d931768a-893b-444a-9ca7-5f5beb836048
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 15572393-22bb-4f5c-9e56-fee44b7716c1
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 5f1000ef-55ec-4159-bb02-606cc3a2a195
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: e72b9ebe-ed1d-49cb-936f-e73054aec49e
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 15926d50-4d29-436a-b27b-83925b8675cf
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 539cda93-4ec6-4ff1-a45f-18d1f50723cb
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: 0dad1015-273c-4f97-a2c1-bb561ed72b32
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 7f5db31c-664c-407f-b153-363be277b093
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: b9b8985f-2142-4090-9e55-3112dc4ad3b3
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: a9132d0f-b750-4c3e-b3a8-7b5d3efa621c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 6c56e784-8c19-40a4-8116-9a93210e9a5e
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: a4481c4c-fc92-4984-be1c-1170584ad995
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 2698e55f-cb81-40e9-91c3-1d9527ddff1c
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 1cd0a3b6-ecc2-419b-bd78-562d3e717d89
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 68fee465-2086-4dda-a817-c65fb654beab
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 0e84dcbb-8ecb-4358-9ef4-30a10b9e60df
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	partition 'Orders-9eb239a7-c1a4-479d-b944-bd9f4dcffd3a' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country", "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"}, {}),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

