table People
	lineageTag: c8e8b046-00ab-4fb3-934e-127ce45e594b

	column 'Regional Manager'
		dataType: string
		lineageTag: 9e9c5ffd-56ce-4aaf-9221-00da6d662772
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 94ba9a2e-33d2-46da-a2b8-898179883ca1
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-fb0efba5-383f-4321-9bb0-d58e99bb698a' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"People Sheet" = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"People Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

