table Calendar
	lineageTag: a6b8b671-fb24-49d2-a96d-5351bb6c49fc

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6b729537-fdf5-46d7-9dbb-bf407f20a8cc
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: db82fe65-e2f3-46b4-9bd7-4638c9e1d05a
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 96e98d87-ecf1-4428-a2e8-0605c60c8d51
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 157881d0-bf92-4e94-9d84-130cc0d63827
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1d8a6c20-592d-46c1-88c4-884e0031314f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 25e4d07f-5dd3-4cfb-a8ff-f753d9ccd673
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e31dbf8a-8424-4e5b-9495-97d45c219ec6
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b4c642a1-4b72-42e7-8613-f643f49cb304
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5303e52f-cb61-4bef-9674-875377105a47

		level Year
			ordinal: 0
			column: Year
			lineageTag: 47f60780-17f4-4640-aa81-7717dc0874e6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 9eaffe21-0139-4177-8356-ab91bd699704

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4d824056-b79a-4731-bc9c-b4a1a7a00c89

		level Day
			ordinal: 3
			column: Day
			lineageTag: 71e422c9-86ea-41eb-81d7-93911eb3fdf1


	partition 'Calendar-5eacb714-2fbc-4426-ae13-f67084b44d26' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

