table Calendar
	lineageTag: b10fd1a9-695f-4b5a-bbd4-8f5516f58d69

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0caa4068-3fae-4b38-96f5-940ace43bf26
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d10f1c0b-473a-4252-90d6-a22b85843745
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b1090f67-263e-471e-ab41-3b8b2166b421
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: cbb978a6-229e-46cf-a10b-e56742968f19
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2a9c60f6-b706-4dc2-b1a5-fefbf8317704
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7dfc3401-18ba-4a88-af8d-362144b05776
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d081905e-32c1-4b8e-a96e-9b219e492948
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d3518557-a980-4ccf-9f40-d668645d5dbf
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 20d2354d-dfac-48fa-a0e9-14ae51de222a

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1694e49e-9dad-4eef-8a6b-6864a2dfe522

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 98b92f57-d633-4ed2-a597-5418388f6cd8

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ac6d71de-5ae6-4390-97af-d8f33484bbf9

		level Day
			ordinal: 3
			column: Day
			lineageTag: a8d3956c-e8df-4ddc-80ee-3451a497c8b9


	partition 'Calendar-ca160c4d-f30e-4150-827d-11146d73b5c0' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

