table Calendar
	lineageTag: a886248e-1f29-4b5f-8050-eca841624f06

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 54999bbd-fd7b-4277-8a8e-3b8267d9cbbb
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 6a0e11c4-ef78-439d-b578-302c3b795209
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1c998553-0045-49f0-a9a4-41b246735cca
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: cf8be42f-63c1-451a-9882-6fe18343fcbc
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 9c61daca-370c-4e26-863e-a2b5216d8b8a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: c1da6bb9-0047-4302-a058-e96494d0e77e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c394d8a0-b091-4fbb-8887-dc9febe9c273
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 1c834adb-aafb-4322-8f98-02e0ca32f3f1
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f27b25f0-ca3b-4b0c-8919-8fdb546e4e9f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6ac54c00-25c8-49fb-8efa-8ee8e8cf3982

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 56cedced-ea1b-4a06-b707-239000358e7d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: bf1c4d6f-63d8-4cec-846d-f4cbd9c317b3

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6ab7f690-9f84-4ea0-b464-7914e68c98cd


	partition 'Calendar-a18ce76a-015a-40be-9ffe-292e7a1cbb81' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

