table Calendar
	lineageTag: 07452a7e-e9e5-4689-861c-156d010d8faa

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 09859c65-1c32-4891-94a5-e23633df5d27
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b783d645-e7e3-49d7-810c-0fe4f9222904
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 83a8a333-9a5d-45a7-86a4-13384a165924
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 578221fe-92ae-4f37-8cc5-47ec62f758fb
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 78f4d9ec-a483-4341-93b3-a604ad26fc61
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b3785ead-9211-4207-b3a6-c9d0698f58e3
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 0078851a-63e5-4526-b32e-768a1b5006c4
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d00ebbe4-ff1a-4c76-b4d8-68ad86ab7ffd
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c166e206-5b5e-4ff7-bb9f-c7c69e3dfe91

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6c405c3c-3f9c-4559-a192-27e0063fe4fb

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: df71ca10-bf6d-4403-898e-5d7eb205b7a1

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8d9c3063-0e91-4ffa-ad89-b4343d47d579

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5de3bf24-c780-40c5-9361-a39c18967e69


	partition 'Calendar-b4a328c3-42ed-43b1-849c-7809924f6e03' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

