table Calendar
	lineageTag: 20d7bfab-6b70-4379-a58f-e01855971096

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 24a0d299-0fbb-483c-86a8-8e3c93313535
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5ee8db94-200f-4479-885a-c4084e8676a9
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: eac0f536-e7c4-494b-ae5e-625eb25e3b6c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ac2d7c82-5ca5-4adc-b13f-24af55e22ec2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: fa1a5107-f41c-4bf0-8f8a-518466bb3620
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1fbdb950-3648-47a7-b41d-092d73b03835
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 64bb89cd-df60-4fcd-a36e-c76a97fd0c46
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: eda8cc0b-bfb4-4b34-8c53-267a9c8a9a71
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4b91df7a-1a5a-49bc-89dc-21442eba94e2

		level Year
			ordinal: 0
			column: Year
			lineageTag: d4469595-2daa-437e-82be-1aa01e297f88

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: bdb0dd01-6030-4883-9fba-77b2c392a0f8

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 000b459a-3eff-4abe-92f0-664a14a47aa5

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4314d7ee-4481-4d70-90bd-9fc985785cd1


	partition 'Calendar-302bf7c0-0776-4b35-a50f-987395e46c53' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

