table Calendar
	lineageTag: f09656fb-3091-40aa-8180-e857884df04e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e6b75081-2c6c-426f-b344-84c7bf251a56
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9581366d-7b69-4679-b922-4f5f590f207f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: baaf2dc6-607a-4217-a203-902eeaec0bd2
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 0f8a0787-ee7b-4609-9fa0-83fc295c4916
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 7ca17cb7-7100-45eb-ac91-34eae0cd4e49
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 18b4893b-f94b-4682-a2c0-0cfe6a2711a2
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 860988d4-de0f-4e79-86ab-dd37267a0f00
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 91966bef-04b6-47d7-8448-c8d711c56bd6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ad7881ac-4004-43ea-96ee-dc87e952538a

		level Year
			ordinal: 0
			column: Year
			lineageTag: 9ccb21cd-3765-4635-9f57-6dc89cab70d5

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3fa0a921-0915-44c0-97ae-c89d9430f29e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 73f71122-524b-445e-9d5c-70d7211a31c0

		level Day
			ordinal: 3
			column: Day
			lineageTag: d050253f-9582-4811-97eb-e29c4b63a15b


	partition 'Calendar-f88a318c-1084-4b17-bd96-0e74e515a1e9' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

