table Calendar
	lineageTag: ea10d3f5-db6e-46c8-a0a2-429dc046cd7b

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 173493a3-728d-49dd-8dfc-3593e418d221

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ecb80ceb-71e6-4547-b973-e67a9bd4bd35

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 1dfe9735-4852-4e81-847f-de467f12631c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 55138558-ef3d-453d-b822-afdc15701904
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b6fba0ba-c06a-4afe-b673-67e84dcdb81d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 6fb164fa-43e4-41ea-9667-38308e6cab8d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2e7e87e9-c01b-4e88-8830-ed7dcdfd6ad0
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 802b2a16-2657-4b1b-9b82-86271e62e650
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0ac0cd2f-1de0-4124-ab49-a76bf4f55562
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: baf438ab-8aba-4929-acf4-5fbc6a4ea414
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7d651b1e-2fa9-4b7a-9219-6ff5939ddc76
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 34cc031e-c276-4a76-864a-e62f3a3f45c0

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4ae4fa64-ec00-4fba-8f2b-108adfba91b0

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e89d7ff5-5dee-41e0-a3c4-ce8424a76c5e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 08390aea-908b-4e2d-86ef-4dc2c1c7169e

		level Day
			ordinal: 3
			column: Day
			lineageTag: c70f54c8-c3ef-467a-985b-643215564df7


	partition 'Calendar-c0a2c3f0-1d0e-4bb7-9fd4-e60f5b41b4dd' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

