table Orders
	lineageTag: e0195ee4-da80-4a5e-9731-514f1bd1cb25

	measure 'Profit Ratio' = SUM('Orders'[Profit])/SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8d966f04-547d-4d6a-810e-6ac9fe1b7c47

	measure Manufacturer = 
		displayFolder: Dimensions
		lineageTag: dded6e2c-1ca4-4c6e-a28a-80622589057f

	column 'Row ID'
		dataType: int64
		lineageTag: be2dd102-c5a4-4e45-803c-7b42086c1d55
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 5c3c1ad2-a140-4ebb-80df-a4ff30b5ed98
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4022358c-4f69-4b08-bfe1-d77de960f2e8
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: ccad961d-d147-43e0-b964-286e7dc20241
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: ed77c804-5dee-4fdb-8525-63d729275b51
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 58209742-1bc2-4663-bf75-10e4ff88b130
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 75916d7c-f1a5-459d-942f-bd5b2491fc4e
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 2f8dce51-601b-4f70-817b-178b78c2d764
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: b36d4c22-5918-401b-9c3b-24d756c0430a
		summarizeBy: none
		sourceColumn: 'Country/Region'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 3185d3b9-1207-478a-9ac7-e6a331eeb055
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: e267fda2-e4e4-45e4-8670-786dedd37ab5
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: 8db7f4a0-26ad-4396-addd-4ca501f767e1
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4f9009cc-817a-483c-ae25-ebca28b00713
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 038054f6-a1c0-47b2-8c52-ca4c920bb9ae
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 5e7e6607-25e5-43bc-8e62-7f6c60664d36
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 14d85d20-6e29-4814-813a-e9b5574a7f36
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: ba9a9484-c83a-4436-8d85-7484ecb954c4
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 197619bc-351a-4ef0-bf2c-a28b6f60f7ba
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 8087701a-4125-4f49-bb31-e8b3226aedc8
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 8f8f42fd-4460-456a-a259-9bf37f22c268
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 4bc797bd-cd11-4441-9a79-e416fb78e077
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Profit (bin)' = 'Orders'[Profit]
		dataType: int64
		lineageTag: 339cd0ad-b35f-49cd-9c94-71f3743e6922
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Top Customers by Profit' = ""
		dataType: string
		lineageTag: cac0d0a6-b672-4e45-9d77-1f02c698156b
		summarizeBy: none
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column Manufacturer = 0
		dataType: double
		lineageTag: b3ad5ef2-20df-4070-987e-a958b319a7e2
		summarizeBy: none
		displayFolder: Bins

		annotation SummarizationSetBy = Automatic

	partition 'Orders-51942230-c47f-482b-848c-08c01814acf1' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country/Region", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

