table 'Top Customers'
	lineageTag: 60cf22cf-8acf-438f-af9b-e5077abbc0c6

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: c6eac267-07b8-4e25-8435-57620b095a99

	column Value
		dataType: int64
		lineageTag: 613d4b8b-1afe-459b-b91c-05950886837f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-ce2b17fd-e9ee-486e-ba4d-1c5997c2f661' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

