table 'Base Salary'
	lineageTag: 472810ce-b787-471b-9132-b2aa7047a8a5

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: 960ad2b9-cb4b-425a-a4f6-5ee5db84b1e0

	column Value
		dataType: int64
		lineageTag: 20de546e-389a-405c-baed-7315b6852e0b
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-e8b3c67c-edd1-4866-aca5-f23686332068' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

