table Calendar
	lineageTag: 6d53be2a-62a5-4876-aa26-92d04935d956

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f01882c6-96b6-44ee-a319-5f8d2c2d1b4c
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f7791d4f-2600-423e-be01-2ad5293fe54f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: cdbba61c-5ff1-4eea-a65f-7cc7732934be
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2b3470a6-b6ed-4482-8c6e-fe3a83097f3d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a7a9c3a2-f233-4cf1-8258-be3c05834efc
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7565fb1e-c21a-4f18-8b78-99afe502a26b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 8f2807d8-5d4d-45d8-8b0e-25e34c23b2e7
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e29a07cf-cfd8-4e15-9531-eaeb4d0737d7
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: d3ddd494-fc79-4d68-a0bf-f42c8d5f287b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4d42ea8f-e406-4c7e-826b-bd9bb0582d8c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ac74fc64-1993-48a9-ad57-b01e7bf375e9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 836643f3-7a25-4144-b682-7adbf743b64b

		level Day
			ordinal: 3
			column: Day
			lineageTag: 13aa1d15-a18c-4af4-93aa-00f3c01e1301


	partition 'Calendar-b42eed22-011a-4a08-a5cc-6c6f6ac35e1a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

