table 'Commission Rate'
	lineageTag: da28a5b3-d4aa-47cd-b032-3e06a82e658e

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: c412e0ec-d008-4d30-aca7-736dd2eb0702

	column Value
		dataType: double
		lineageTag: 9a1f1feb-6821-4642-adae-6c02eb9fe47f
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-93c7ab91-490a-4350-9007-26fd2c16f127' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

