table 'Business Unit'
	lineageTag: c7c42785-d9dc-473b-8771-aab87c6d2fac

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 5453daae-5f77-422b-afc6-b558ec564a8a

	column Value
		dataType: string
		lineageTag: 61cacf7a-41fb-4d99-ada5-28bdca641807
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-b48b1f3d-3bab-4179-9517-8eba62eaeaad' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

