table Calendar
	lineageTag: fad5066c-9b98-4f01-b95e-1c156d9eab14

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 14f13d08-508e-4303-b7bf-4220e97f9835

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 93bbbc74-47de-4bf9-acbe-fb913534ea8e

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: cee856c4-eaa3-4873-8c69-533950b13495

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c3172bee-2cc8-459a-93fb-e4852eeefff4
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9b391e8c-b774-44e0-aad6-af17e9aa674d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0ab45994-d866-4e78-8fea-acee4f8bba20
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 0ad370ee-7d86-469f-bdfb-2f4243bb1209
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2b6925b6-d4d6-47be-9f0c-204fc4758102
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0c8ef482-2eab-4073-b8b1-e3c92c1fcb78
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 71fdf261-aaa4-4baf-9ccd-096ec86b4dc3
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ee88b0ef-b9e7-413b-b8bd-5f9d13d061bf
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: a8d4d304-51c2-446a-bc87-29df08fa7ec7

		level Year
			ordinal: 0
			column: Year
			lineageTag: b67c435f-9587-4fa0-a63b-06a8aa0efaf6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e7f37b18-8a02-4a3c-ac5d-91bbc8c7af1d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e57bdcb1-af00-4da0-93e3-7d708bd80146

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3016bef9-3089-47b4-9ba6-aec17b79603c


	partition 'Calendar-6c957a45-846a-4e77-9cc0-bdd1e1d960fa' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

