table 'Fiscal Year'
	lineageTag: b0691617-3e45-4d14-b05e-4a477e173f2d

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 07291d96-01a7-44c6-a358-649c30334045

	column Value
		dataType: int64
		lineageTag: ea6ddf78-669e-4b00-9d08-c7d453eac7eb
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-c5216f7f-fe01-4f88-a9b1-ef398e1430ea' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

