table Calendar
	lineageTag: 1eb4271a-b545-47af-9e0c-f9608a17890f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 17eb7a37-bb92-44e8-b8c3-7d2d7553593a
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 80ba2c13-0d05-48dc-bead-4deed7482472
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 221fb562-4d20-430e-a709-8875ae1f4570
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 6907b794-e828-4a14-8a05-0aadc59f1bc1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 857a835b-a4f3-42ce-9b1d-b6c89deed67f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e40b69f5-160d-4ad1-957f-fdf99e7a1f71
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 62c45757-cb6a-4491-95d5-c61e29c6da76
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c0adf5de-dfad-49f1-9616-8c4b33d2430f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1e8e8df3-510c-46fc-b547-139aebf99ff0

		level Year
			ordinal: 0
			column: Year
			lineageTag: aa2de674-b74f-4039-9151-be44fed956e3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 844601e6-f588-419c-89a5-94edbc672c6d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 564384d0-550c-4f33-964e-8cbf88788f29

		level Day
			ordinal: 3
			column: Day
			lineageTag: 095b9d38-81db-4577-a136-4be089585a66


	partition 'Calendar-db6cd3ce-9255-4c43-a449-3ecb022f1f13' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

