table 'customer_feedback_data.json'
	lineageTag: 5d320639-9e50-4106-8af3-810dd848621b

	column 'Document Index (generated)'
		dataType: int64
		lineageTag: 0a7642df-ca39-425d-b03b-b82d5c62c718
		summarizeBy: sum
		sourceColumn: 'Document Index (generated)'

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: b4c57633-ea1a-4cca-92e8-7ecbbdfa6648
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: d141c099-11a8-46c8-b990-c1097f150ef6
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: string
		lineageTag: 1f2630fc-aa3e-4a85-b835-8ac17abb09d6
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: d835ff8c-186b-43a7-a6fe-53bd1852e8ca
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column feedback_score
		dataType: double
		formatString: #,0.00
		lineageTag: c713a17f-aaed-434b-b31e-03bc677d72da
		summarizeBy: sum
		sourceColumn: feedback_score

		annotation SummarizationSetBy = Automatic

	column feedback_text
		dataType: string
		lineageTag: 20ce3a9d-5ed1-47b9-9221-cdb59db046e0
		summarizeBy: none
		sourceColumn: feedback_text

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: c438e202-7f58-468a-9723-1433ea85030f
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column sentiment
		dataType: string
		lineageTag: 933f0d98-b231-434e-9c51-8687d231a81f
		summarizeBy: none
		sourceColumn: sentiment

		annotation SummarizationSetBy = Automatic

	column Promoter
		dataType: int64
		lineageTag: 5a150df5-29d0-44b9-aee9-e5bb83d95e7d
		summarizeBy: none
		sourceColumn: Promoter

		annotation SummarizationSetBy = Automatic

	column 'Action (Category)'
		dataType: string
		lineageTag: 27b2d29a-ea5e-4635-9837-da300cc19398
		summarizeBy: none
		sourceColumn: 'Action (Category)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Sentiment)'
		dataType: string
		lineageTag: 8e3c7725-769c-49b8-af29-8a3666e3fa3a
		summarizeBy: none
		sourceColumn: 'Action (Sentiment)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'customer_feedback_data.json-37550400-b18d-43c8-be81-a37bf034b13d' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: SEMISTRUCTPASSIVESTORE-DIRECT
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"},
				            {
				                {1, "Sample 2", "Sample 3", "Sample 4", "Sample 5", 6, "Sample 7", "Sample 8", "Sample 9"},
				                {2, "Sample 3", "Sample 4", "Sample 5", "Sample 6", 7, "Sample 8", "Sample 9", "Sample 10"}
				            }
				        )
				    otherwise
				        #table({"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"category", "Category"}, {"customer_id", "Customer Id"}, {"date", "Date"}, {"email", "Email"}, {"feedback_score", "Feedback Score"}, {"feedback_text", "Feedback Text"}, {"name", "Name"}, {"sentiment", "Sentiment"}}),
				    #"Added Promoter" = Table.AddColumn(#"Renamed Columns", "Promoter", each if [feedback_score]>=9 then 1 else 0, Int64.Type),
				    #"Added Action (Category)" = Table.AddColumn(#"Added Promoter", "Action (Category)", each Text.From([#"category"]), type text),
				    #"Added Action (Sentiment)" = Table.AddColumn(#"Added Action (Category)", "Action (Sentiment)", each Text.From([#"sentiment"]), type text),
				    Result = #"Added Action (Sentiment)"
				in
				    Result

	annotation PBI_ResultType = Table

