table 'customer_feedback_data.json'
	lineageTag: 553bdd70-8334-4647-8bf2-fba700d84a2a
	description: Contains 12 columns: Document Index (generated), category, customer_id, date, email, feedback_score, feedback_text, name, ... (12 columns total).

	column 'Document Index (generated)'
		dataType: int64
		lineageTag: 8024184c-42cc-4903-9b02-a1c7eb00defa
		summarizeBy: sum
		sourceColumn: 'Document Index (generated)'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 3f1f4f3a-c4a5-4b61-a807-bf4e37272eb4
		summarizeBy: none
		sourceColumn: category
		description: String column.

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: f419f89b-617e-4ea9-a311-2d6b7ec9e869
		summarizeBy: none
		sourceColumn: customer_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column date
		dataType: string
		lineageTag: 17c336c5-3125-49bd-9032-adf2e63492e7
		summarizeBy: none
		sourceColumn: date
		description: String column.

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: e68fcf7c-ca64-4c20-8034-0663e0cd69f8
		summarizeBy: none
		sourceColumn: email
		description: String column.

		annotation SummarizationSetBy = Automatic

	column feedback_score
		dataType: double
		formatString: #,0.00
		lineageTag: 7696e5c8-1b05-42e3-9c79-ad8b238ad2e7
		summarizeBy: sum
		sourceColumn: feedback_score
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column feedback_text
		dataType: string
		lineageTag: 7cab42ab-382b-4a4d-9c1e-6183cc332533
		summarizeBy: none
		sourceColumn: feedback_text
		description: String column.

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 8cd1844e-95f2-4aef-be08-c5e8660e603a
		summarizeBy: none
		sourceColumn: name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column sentiment
		dataType: string
		lineageTag: f9c10385-dc37-4714-b386-e1c5dd788f37
		summarizeBy: none
		sourceColumn: sentiment
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Promoter
		dataType: int64
		lineageTag: 3730990f-27db-46c5-a169-6ce83646b0fc
		summarizeBy: none
		sourceColumn: Promoter
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column 'Action (Category)'
		dataType: string
		lineageTag: cf6403fb-5b84-479b-82d0-bd4f22cb6f5b
		summarizeBy: none
		sourceColumn: 'Action (Category)'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Sentiment)'
		dataType: string
		lineageTag: 8d90a88b-048b-4362-b0a1-40d714d5f473
		summarizeBy: none
		sourceColumn: 'Action (Sentiment)'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'customer_feedback_data.json-57fa4c48-66e5-45b8-be88-31b7c536a16c' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: SEMISTRUCTPASSIVESTORE-DIRECT
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"},
				            {
				                {1, "Sample 2", "Sample 3", "Sample 4", "Sample 5", 6, "Sample 7", "Sample 8", "Sample 9"},
				                {2, "Sample 3", "Sample 4", "Sample 5", "Sample 6", 7, "Sample 8", "Sample 9", "Sample 10"}
				            }
				        )
				    otherwise
				        #table({"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"category", "Category"}, {"customer_id", "Customer Id"}, {"date", "Date"}, {"email", "Email"}, {"feedback_score", "Feedback Score"}, {"feedback_text", "Feedback Text"}, {"name", "Name"}, {"sentiment", "Sentiment"}}),
				    #"Added Promoter" = Table.AddColumn(#"Renamed Columns", "Promoter", each if [feedback_score]>=9 then 1 else 0, Int64.Type),
				    #"Added Action (Category)" = Table.AddColumn(#"Added Promoter", "Action (Category)", each Text.From([#"category"]), type text),
				    #"Added Action (Sentiment)" = Table.AddColumn(#"Added Action (Category)", "Action (Sentiment)", each Text.From([#"sentiment"]), type text),
				    Result = #"Added Action (Sentiment)"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: Document Index (generated), category, customer_id, date, email, feedback_score, feedback_text, name, ... (12 columns total).

