table 'customer_feedback_data.json'
	lineageTag: e7730acc-d486-493d-b98d-d709d299ac74

	column 'Document Index (generated)'
		dataType: int64
		lineageTag: 6422656b-2c31-4d98-8bc4-93b0bc10f223
		summarizeBy: sum
		sourceColumn: 'Document Index (generated)'

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 5cda4de6-660b-4cc8-ba4a-7cbc18db4fd8
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: c65df421-9edf-456b-8c58-4e644e6a3884
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: string
		lineageTag: eb384d44-bb9b-4ffd-8075-5e7137201738
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: e76279e3-c890-4986-9da5-8b573bfd4c5a
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column feedback_score
		dataType: double
		formatString: #,0.00
		lineageTag: 44f9298d-d4de-4afd-a3c0-cf70c7744f91
		summarizeBy: sum
		sourceColumn: feedback_score

		annotation SummarizationSetBy = Automatic

	column feedback_text
		dataType: string
		lineageTag: 04ce2ae1-80a5-43f3-a0b0-a67a0c74c83f
		summarizeBy: none
		sourceColumn: feedback_text

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: cfa968f4-f487-40c2-83ad-b1b942b0da07
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column sentiment
		dataType: string
		lineageTag: 682450ae-c516-445d-9e6c-88d67c0e0d3a
		summarizeBy: none
		sourceColumn: sentiment

		annotation SummarizationSetBy = Automatic

	column Promoter
		dataType: int64
		lineageTag: 8a947d52-2577-4b85-9294-9baa4281e902
		summarizeBy: none
		sourceColumn: Promoter

		annotation SummarizationSetBy = Automatic

	column 'Action (Category)'
		dataType: string
		lineageTag: 53603d61-e5e3-498f-b577-6f315ae0ee83
		summarizeBy: none
		sourceColumn: 'Action (Category)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Sentiment)'
		dataType: string
		lineageTag: 94cfb6ee-5e0c-4a6f-8645-150673bc0047
		summarizeBy: none
		sourceColumn: 'Action (Sentiment)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'customer_feedback_data.json-97366bd4-64f9-4791-87f4-2596d41ff6d8' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: SEMISTRUCTPASSIVESTORE-DIRECT
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"},
				            {
				                {1, "Sample 2", "Sample 3", "Sample 4", "Sample 5", 6, "Sample 7", "Sample 8", "Sample 9"},
				                {2, "Sample 3", "Sample 4", "Sample 5", "Sample 6", 7, "Sample 8", "Sample 9", "Sample 10"}
				            }
				        )
				    otherwise
				        #table({"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"category", "Category"}, {"customer_id", "Customer Id"}, {"date", "Date"}, {"email", "Email"}, {"feedback_score", "Feedback Score"}, {"feedback_text", "Feedback Text"}, {"name", "Name"}, {"sentiment", "Sentiment"}}),
				    #"Added Promoter" = Table.AddColumn(#"Renamed Columns", "Promoter", each if [feedback_score]>=9 then 1 else 0, Int64.Type),
				    #"Added Action (Category)" = Table.AddColumn(#"Added Promoter", "Action (Category)", each Text.From([#"category"]), type text),
				    #"Added Action (Sentiment)" = Table.AddColumn(#"Added Action (Category)", "Action (Sentiment)", each Text.From([#"sentiment"]), type text),
				    Result = #"Added Action (Sentiment)"
				in
				    Result

	annotation PBI_ResultType = Table

