table 'customer_feedback_data.json'
	lineageTag: 5bc6ffe2-8950-4e67-9f23-7f23faf9b30a

	column 'Document Index (generated)'
		dataType: int64
		lineageTag: bb33d09e-81a8-4ab2-a3ed-30c5428cbce3
		summarizeBy: sum
		sourceColumn: 'Document Index (generated)'

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 3a152ced-42ad-4d1a-89fa-45f0dea75d13
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: c69556b6-16ff-4947-9a75-53295c31eff5
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: string
		lineageTag: 103a53d7-96ee-48dd-ac5d-37b793c8945c
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: b4605177-e39b-40d8-8c62-27180d2a2697
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column feedback_score
		dataType: double
		formatString: #,0.00
		lineageTag: e76d3a0e-a800-4251-835a-6937b8fc4603
		summarizeBy: sum
		sourceColumn: feedback_score

		annotation SummarizationSetBy = Automatic

	column feedback_text
		dataType: string
		lineageTag: 2ebff76f-acea-4304-892a-d59fe7b63f7b
		summarizeBy: none
		sourceColumn: feedback_text

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 5240cb23-1ec4-470a-9031-84753f6eb935
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column sentiment
		dataType: string
		lineageTag: 962a64aa-335f-4405-a2e0-5362eb6c7ffe
		summarizeBy: none
		sourceColumn: sentiment

		annotation SummarizationSetBy = Automatic

	column Promoter
		dataType: int64
		lineageTag: 9c610618-2959-4b6e-92db-3b5f3f922b9b
		summarizeBy: none
		sourceColumn: Promoter

		annotation SummarizationSetBy = Automatic

	column 'Action (Category)'
		dataType: string
		lineageTag: 9f8ca54f-6e45-4808-8538-6fb12f6267c9
		summarizeBy: none
		sourceColumn: 'Action (Category)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Sentiment)'
		dataType: string
		lineageTag: 36071bbb-b51c-4391-b158-b09df1f478ed
		summarizeBy: none
		sourceColumn: 'Action (Sentiment)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'customer_feedback_data.json-338595a1-8ce2-4e70-9769-194c9ef0d419' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: SEMISTRUCTPASSIVESTORE-DIRECT
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"},
				            {
				                {1, "Sample 2", "Sample 3", "Sample 4", "Sample 5", 6, "Sample 7", "Sample 8", "Sample 9"},
				                {2, "Sample 3", "Sample 4", "Sample 5", "Sample 6", 7, "Sample 8", "Sample 9", "Sample 10"}
				            }
				        )
				    otherwise
				        #table({"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"category", "Category"}, {"customer_id", "Customer Id"}, {"date", "Date"}, {"email", "Email"}, {"feedback_score", "Feedback Score"}, {"feedback_text", "Feedback Text"}, {"name", "Name"}, {"sentiment", "Sentiment"}}),
				    #"Added Promoter" = Table.AddColumn(#"Renamed Columns", "Promoter", each if [feedback_score]>=9 then 1 else 0, Int64.Type),
				    #"Added Action (Category)" = Table.AddColumn(#"Added Promoter", "Action (Category)", each Text.From([#"category"]), type text),
				    #"Added Action (Sentiment)" = Table.AddColumn(#"Added Action (Category)", "Action (Sentiment)", each Text.From([#"sentiment"]), type text),
				    Result = #"Added Action (Sentiment)"
				in
				    Result

	annotation PBI_ResultType = Table

