table Extract
	lineageTag: 6d0614e0-16de-4424-b709-81dbde9d5ec3
	description: Contains 9 columns: Document Index (generated), category, customer_id, date, email, feedback_score, feedback_text, name, ... (9 columns total).

	column 'Document Index (generated)'
		dataType: int64
		lineageTag: 2c309d26-4b56-4695-8e0a-686c7e0a9b34
		summarizeBy: sum
		sourceColumn: 'Document Index (generated)'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 4466ef12-22d2-4f6e-aba1-af226277bfe2
		summarizeBy: none
		sourceColumn: category
		description: String column.

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: f294f63f-0bb6-40ab-a85f-3fc49d2ddae1
		summarizeBy: none
		sourceColumn: customer_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column date
		dataType: string
		lineageTag: d3515028-bd86-4498-9c8a-424b32be7340
		summarizeBy: none
		sourceColumn: date
		description: String column.

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 20e96dbb-fcfa-4e84-80e8-cf4db6faae60
		summarizeBy: none
		sourceColumn: email
		description: String column.

		annotation SummarizationSetBy = Automatic

	column feedback_score
		dataType: double
		formatString: #,0.00
		lineageTag: c523b4db-3b0d-490f-8089-e05f773ec0ef
		summarizeBy: sum
		sourceColumn: feedback_score
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column feedback_text
		dataType: string
		lineageTag: ec5af575-478d-4e74-8326-af764d634b7c
		summarizeBy: none
		sourceColumn: feedback_text
		description: String column.

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: a112bdad-6da9-4a67-82f2-468618948143
		summarizeBy: none
		sourceColumn: name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column sentiment
		dataType: string
		lineageTag: e00b2032-5c30-4e7f-a290-a829c2ffb018
		summarizeBy: none
		sourceColumn: sentiment
		description: String column.

		annotation SummarizationSetBy = Automatic

	partition 'Extract-6784ce8f-c41a-4b6b-a53b-d6634af963d0' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: SEMISTRUCTPASSIVESTORE-DIRECT
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"},
				            {
				                {1, "Sample 2", "Sample 3", "Sample 4", "Sample 5", 6, "Sample 7", "Sample 8", "Sample 9"},
				                {2, "Sample 3", "Sample 4", "Sample 5", "Sample 6", 7, "Sample 8", "Sample 9", "Sample 10"}
				            }
				        )
				    otherwise
				        #table({"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"category", "Category"}, {"customer_id", "Customer Id"}, {"date", "Date"}, {"email", "Email"}, {"feedback_score", "Feedback Score"}, {"feedback_text", "Feedback Text"}, {"name", "Name"}, {"sentiment", "Sentiment"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 9 columns: Document Index (generated), category, customer_id, date, email, feedback_score, feedback_text, name, ... (9 columns total).

