table Extract
	lineageTag: 43afb99e-7abd-4ade-8b6a-de1c7f72837d

	column 'Document Index (generated)'
		dataType: int64
		lineageTag: 31254a32-cd00-4680-8716-0ad5d07a2d0b
		summarizeBy: sum
		sourceColumn: 'Document Index (generated)'

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 616ec8f6-c934-4059-a065-59141349f351
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 02277867-82ec-4b36-8305-1be84d72669d
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: string
		lineageTag: b48e2b5c-a5e6-48c1-ae83-49f6d465fa2e
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 6f38e31f-6bf9-4adc-873a-ecd45fe78bd3
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column feedback_score
		dataType: double
		formatString: #,0.00
		lineageTag: 5d48e1cc-4417-4a84-8730-79a6de4dad58
		summarizeBy: sum
		sourceColumn: feedback_score

		annotation SummarizationSetBy = Automatic

	column feedback_text
		dataType: string
		lineageTag: 8a13a9b4-b1f9-41e6-9f84-ca25805c8821
		summarizeBy: none
		sourceColumn: feedback_text

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 921db670-1623-4ff0-b9a2-c055ac55f12f
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column sentiment
		dataType: string
		lineageTag: 8423d1b3-e5a3-418c-ba76-1f76fceb9994
		summarizeBy: none
		sourceColumn: sentiment

		annotation SummarizationSetBy = Automatic

	partition 'Extract-ede0dd06-a447-491f-8b87-a494edb6c4e4' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: SEMISTRUCTPASSIVESTORE-DIRECT
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"},
				            {
				                {1, "Sample 2", "Sample 3", "Sample 4", "Sample 5", 6, "Sample 7", "Sample 8", "Sample 9"},
				                {2, "Sample 3", "Sample 4", "Sample 5", "Sample 6", 7, "Sample 8", "Sample 9", "Sample 10"}
				            }
				        )
				    otherwise
				        #table({"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"category", "Category"}, {"customer_id", "Customer Id"}, {"date", "Date"}, {"email", "Email"}, {"feedback_score", "Feedback Score"}, {"feedback_text", "Feedback Text"}, {"name", "Name"}, {"sentiment", "Sentiment"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

