table Calendar
	lineageTag: 0a774953-44d1-45cb-8da8-8070d4343cd1

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d66f9ae3-a77c-4df8-81ff-f32ef94965a2

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6919a605-f0cd-4a12-935d-71aec7ea7069

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 912eb013-598a-4300-821e-c3606ecf0e60

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3ff4bd87-f7ee-4a0c-b047-fa05f6b2485d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c5f038ba-6a41-409e-a3eb-968bee5c93f5
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5ffd336d-2b41-46f4-bcac-caf4f0dd6716
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b17fcbe4-b120-42f4-96dc-bf8114bb3589
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 67b78d6d-6b4a-48e2-9082-591aaa102eba
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 79236788-faf4-46bf-b302-7119b35f8f0b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: fd451203-749c-46d4-b5bc-8bc82387eb01
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ce9b9354-197e-43a1-b30f-5445cd9b106a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 98455a34-aacc-448f-8c6d-2313207bb893

		level Year
			ordinal: 0
			column: Year
			lineageTag: a8e55d4b-e679-47a3-8936-d577a66e1278

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c639b929-1daf-43c5-b09a-991543026878

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 2c3e3035-1f55-40d0-b049-77cef2f658eb

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4caf21cf-7bab-49e0-872c-553c88c7d709


	partition 'Calendar-5c8d6687-849a-4b04-9a45-855a160894d4' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

