table Employees
	lineageTag: c9addbe7-766f-48f7-92f9-74c2f7b9d64d

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d3812de8-9017-4b18-9894-cddea6cf901e

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: afecf690-0007-49af-8f12-e90396b0a481

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: cc193ec3-deed-4894-9854-15bdf2cb1224

	column EmployeeID
		dataType: int64
		lineageTag: 1edcb46b-8aed-4e49-b5e2-a36b992e6db6
		summarizeBy: sum
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 666c03f6-a9c4-4de6-8268-cc7d8f37f47d
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 5d71df36-0a65-4479-a425-acb5bb48191d
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 2e13b3a7-e550-4937-b105-90c78e5f27f4
		summarizeBy: none
		sourceColumn: HireDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: d5e345ec-79a9-4b51-8ea6-9c29a8190a50
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 55b67e83-158b-4aff-a9a6-ac7c926090d7
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: c7e433ec-2361-4d96-ac55-37d618ee74b5
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 3a64c914-83ed-47a0-aaba-a3ccf4fc9f18
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: 0ff37d26-31ec-4ef2-8df7-5571def71b29
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: 6c544c0b-591e-42a6-b6f2-4c7d5b86b678
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: 3b5c3f50-a587-4e71-aa60-252f1deb3711
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category'
		dataType: string
		lineageTag: 6bddf775-dc80-4ed2-92e4-a52f2c0e2493
		summarizeBy: none
		sourceColumn: 'Tenure Category'

		annotation SummarizationSetBy = Automatic

	partition 'Employees-f57f8e7d-412f-4687-bce1-d2a5e69dc9a3' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("localhost", "HRDatabase")
				
				    otherwise
				
				        #table({"EmployeeID", "FirstName", "LastName", "HireDate", "Department", "JobTitle", "Salary", "Location", "Age", "YearsOfService", "PerformanceRating"}, {}),
				    #"Employees Table" = Source{[Schema="dbo", Item="Employees"]}[Data],
				    #"Added Tenure Category" = Table.AddColumn(#"Employees Table", "Tenure Category", each if [YearsOfService] < 2 then "New" else if [YearsOfService] < 5 then "Mid" else "Senior", type text),
				    Result = #"Added Tenure Category"
				in
				    Result

	annotation PBI_ResultType = Table

