table Calendar
	lineageTag: a042652f-25bb-4928-8a82-935b014678a9

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d92b46aa-3fc6-4375-b423-33a77f5d418f

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 0ea2b268-aef9-41f8-9a30-65669a4fc860

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 4fbeb237-a7fc-4152-9dca-3ac2347761d9

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8575eb6e-e3a8-4258-a743-f428a6bf6aa5
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 86788b3e-a7ff-47ca-a035-1ee165cab0e3
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c2c26978-b212-4154-b050-090a8057e6bb
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 75ff809c-9e14-416f-b460-0963cb20c25a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f83f5878-7bef-4e8c-ab20-e946be9958a6
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ab2f50f2-68ff-4c5a-99bb-3a04090d6dc9
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 234f4cab-4df8-4ad8-98ca-acf905b7c748
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 58fcae10-23c9-4981-9a58-f93750e2dc17
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9013c1a7-af4f-4727-aad3-a8fa22a2b4c8

		level Year
			ordinal: 0
			column: Year
			lineageTag: 0964f6cb-2e05-4ff0-a7a4-ea71e67546b9

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 77bd61d1-c92f-4723-8977-169cbb1bfce6

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1a4dcc51-4d05-42f9-9a1b-dc19ed1d77d5

		level Day
			ordinal: 3
			column: Day
			lineageTag: a1505565-7e4e-4131-bcb9-a7b759699ff5


	partition 'Calendar-69c7c8ea-347d-4412-a744-e43852adebd2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

