table Calendar
	lineageTag: f1f4bdcc-99b4-43f3-bb68-e12264c758fb

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6dd04bb7-f2c6-4a48-b54e-0ac74769364e

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: fcd2c536-4bb3-4776-bb54-08aa9eb3cb4e

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: b02d02e0-145e-4a2a-aab9-2623bfa888c5

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: da8d3b0e-5ef7-45b1-803c-87d4fe8472e7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 3666e65c-abc6-4631-a02b-2e159fd77182
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 2975c722-c187-4875-977e-844c4147c249
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b4c9cb6f-0b2e-4b1f-9805-2448777de469
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b7773008-ba23-49a9-981a-9b0eddfb8caf
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3a7907b1-3490-4d65-8f45-9bddb635d82e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d56d6d35-2cbe-4dfd-abce-372add2a9036
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a8e09988-50a0-405a-b6cb-1e91207294bd
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 13a24934-cf18-4718-9a3a-8b8e5416ccd0

		level Year
			ordinal: 0
			column: Year
			lineageTag: 377868a5-eae8-4b00-9e14-3088cb2e232d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 589edc38-aa20-42f9-8c8f-0659e17277d0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f711bde9-0ff3-4cd7-88f8-5f982356d59c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 8945dbd9-c149-45fe-a755-036fd99c4acc


	partition 'Calendar-be0c4a42-f041-44b5-b378-9bb04e7a853d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

