table Calendar
	lineageTag: 5423baaa-9a0a-468d-8fb8-ce1ddfaa54df

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 20ae9f16-8933-439f-bc9e-68a55766b145

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: f5460687-52a2-43fe-9c62-a8db3466dee9

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: f33cbd42-9b61-4738-b1a7-8f05b9a4d1ce

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f89f536c-aac6-4cd7-b9b2-2a62301c67bc
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 32c44a34-4b27-4a16-a3fc-a5ab5fb44a42
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 25b72bcf-d464-4ed9-a14d-73068c59acdd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 609cc966-8e61-414b-99fb-217dce45c8b6
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8d604b47-65f7-4746-875f-d2018f7ff3d8
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7f2a50a6-897c-4722-83a2-28d2306242d5
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 674e2f4b-eacd-492e-9b98-4bc04693be6d
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 6092ba7d-d62d-4f54-8f53-daea4773b34e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9c9d9cb6-cd11-4a73-8ccc-38ed2faa6289

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4bf8e6a8-51e7-4e97-b48c-0f371aff13bf

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d94a2479-9577-4b0b-8f11-bbd071f54a3c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e1363f49-5274-44f1-9d80-a37ff4489ae7

		level Day
			ordinal: 3
			column: Day
			lineageTag: a32ab9bb-021a-4614-86ea-af4c94ecc9d6


	partition 'Calendar-109a89ee-ee27-44ba-87ef-78ac6deca33f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

