table Calendar
	lineageTag: 474e3d33-6d7b-41f6-84c6-bf15e24eeb38

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: f560dd10-6398-4523-9231-eeb4d2a88ea9

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6c13e72c-6263-49c4-99dd-81df87948611

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0593743c-518a-4c56-a70e-c09622672e26

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c323f9bb-a655-4776-add6-aa6342d42bca
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 14036064-6d12-48f2-b872-1033315f84d3
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 90a8a806-57e6-4533-9b1a-92ee5a0328fc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d853216a-ce19-4dfd-8bc7-a57d9417bae4
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 9fbb5a8b-c9bb-4553-a8c7-e0293fa11e19
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d7641994-820c-4e5b-a66c-f7418f166468
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a911ee44-cb54-4a6d-9640-95b376a3259c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e6c299a3-78a9-4472-9160-e8d1ac19b749
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ca6d2223-0107-43e0-9658-c992249a0a1a

		level Year
			ordinal: 0
			column: Year
			lineageTag: 99fec02e-ae52-4fef-bfc3-5f337dba2cb5

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 909c75de-723e-4da3-b735-b11af9d218f4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f87e80ab-d260-44b0-9364-bc7cd6a1af78

		level Day
			ordinal: 3
			column: Day
			lineageTag: 40b132f6-78ee-47e9-8c35-1b6022171ef7


	partition 'Calendar-088d95bc-6de9-4c35-8e7d-891357670af8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

