table Campaigns
	lineageTag: ed979236-b340-463b-ac94-5479e6e4ac0c

	measure 'Non-Blank Leads' = COUNTA('Leads'[lead_name])
		displayFolder: Measures
		lineageTag: 920cceec-a15c-46dc-b654-07f3c84c1da7

	measure 'Budget Deal Correlation' = 0 /* CORR('Campaigns'[budget], 'Leads'[deal_value]): Pearson correlation — manual DAX needed */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8c115080-e6c2-41a8-bb8a-cd40419c99ae

	measure 'Spend Engagement Covar' = 0 /* COVAR('Campaigns'[spend], 'Leads'[engagement_score]): sample covariance — manual DAX needed */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 89f01ee3-60be-4a9f-afc6-039b456e7daf

	measure 'Avg Deal by Channel' = CALCULATE(AVERAGE('Leads'[deal_value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 301ecc94-8e9c-4eec-b6c7-71ce20428805

	measure 'Campaign ROI' = (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b16fb037-852f-4e92-9980-740c2457c165

	measure 'Cost Per Lead' = SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 4739d726-5167-4501-837c-ed3359d21e5c

	measure 'Window Best ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 32fd17ff-8a64-492b-b88d-2835b6c1e864

	measure 'Window Worst ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 84fc25b5-f6d3-4335-b4cd-b14286241029

	measure 'Cumulative Leads' = CALCULATE(DISTINCTCOUNT('Leads'[lead_id]))
		displayFolder: Measures
		lineageTag: 7267d790-2200-4dfa-a37a-6cad4021dfb7

	measure 'Conversion Rate' = SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a686ee07-e06c-4cdc-bcc0-69608873985a

	measure 'Target Channel' = "Email"
		lineageTag: 4459d520-8a6c-4753-8ee6-463554c1a015

	column campaign_id
		dataType: int64
		lineageTag: 62a60155-5ba0-4da1-a318-23a1d817c8a4
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 17f43b70-e050-4c8d-84a9-bd0b09129676
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 5ad03b47-e275-4a27-a734-7894ba4970ce
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 173ae5e6-f5ea-45ba-a75c-ae679649647f
		summarizeBy: none
		sourceColumn: start_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 049f7302-bcb5-4311-87b8-90ea6abb47fa
		summarizeBy: none
		sourceColumn: end_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: d91e331b-821c-4ca5-8c10-2d026c631de4
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: #,0.00
		lineageTag: 3a3c7ff1-be23-49ba-a0f1-582637fef520
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column target_audience
		dataType: string
		lineageTag: 178b0809-5a08-46bb-8d52-b009960f12a6
		summarizeBy: none
		sourceColumn: target_audience

		annotation SummarizationSetBy = Automatic

	column creative_url
		dataType: string
		lineageTag: 245f6974-5c8a-40a6-9adc-5ed2f0c38cac
		summarizeBy: none
		sourceColumn: creative_url

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 5e048e93-e430-41ab-89de-18585f699fd3
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: 852c14e3-6e33-4b07-aca0-0dfc5f33311c
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: 863b69d5-0ce5-4150-b6a3-73759a5375e3
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: d562f017-b276-416d-8a22-d094f9501c52
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: ea5d2b2a-12a8-4411-931d-0f41e14fb487
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column 'Email Domain' = MID(RELATED('Leads'[email]), FIND("@", RELATED('Leads'[email])) + 1, LEN(RELATED('Leads'[email])))
		dataType: string
		lineageTag: 569b53b0-9ad3-40fa-afe4-c65c263b66c5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'First Name' = LEFT(RELATED('Leads'[lead_name]), FIND(" ", RELATED('Leads'[lead_name])) - 1)
		dataType: string
		lineageTag: e317bb64-8286-4aa9-8169-5675928d5026
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last Name' = MID(RELATED('Leads'[lead_name]), FIND(" ", RELATED('Leads'[lead_name])) + 1, LEN(RELATED('Leads'[lead_name])))
		dataType: string
		lineageTag: 4adf9074-8c8f-4950-8d40-fe9c9956fd00
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Name Length' = LEN(RELATED('Leads'[lead_name]))
		dataType: int64
		lineageTag: 97356e20-6b77-495f-80cb-adbb47a42d65
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean Phone' = TRIM(SUBSTITUTE(SUBSTITUTE(RELATED('Leads'[phone]), "-", ""), " ", ""))
		dataType: string
		lineageTag: a5d2a2a4-6d7f-41d4-ab05-d08f45e17932
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Phone Last 4' = RIGHT(RELATED('Leads'[phone]), 4)
		dataType: string
		lineageTag: e0c8f13b-a980-46e1-84ae-93ff126a2acc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Code' = UPPER(LEFT('Campaigns'[channel], 3)) & "-" & FORMAT('Campaigns'[campaign_id], "0") & REPT(" ", 5 - LEN(FORMAT('Campaigns'[campaign_id], "0")))
		dataType: string
		lineageTag: 51ee8434-7d10-4a0d-a4ad-44c53f4467bd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Enterprise' = CONTAINSSTRING('Campaigns'[target_audience], "Enterprise")
		dataType: boolean
		lineageTag: 0941ee17-84b2-4e04-9e68-ff5223d5f14d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Has Valid UTM' = CONTAINSSTRING('Campaigns'[utm_campaign], "^'Campaigns'[a-z0-9_-]+$")
		dataType: boolean
		lineageTag: 3c353485-8e58-4077-9534-37acd0061011
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean URL' = SUBSTITUTE('Campaigns'[creative_url], "https?://", "")
		dataType: string
		lineageTag: 8afef405-70e3-41be-aad8-26ba53f8a2aa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Year' = DATE(YEAR('Campaigns'[start_date]), 1, 1)
		dataType: dateTime
		lineageTag: 39071db3-0960-4c2b-bf8a-c75331296113
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Start Month' = MONTH('Campaigns'[start_date])
		dataType: int64
		lineageTag: 002972ac-94ae-48e2-a536-d8f14315a663
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT('Campaigns'[start_date], "MMMM")
		dataType: string
		lineageTag: 783b7912-8b29-4b5a-9b50-7598577c48b6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Days' = DATEDIFF('Campaigns'[start_date], 'Campaigns'[end_date], DAY)
		dataType: int64
		lineageTag: 04ed4bc2-60b9-4cc6-acf2-2ff4bfe678a6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Budget Band' = INT('Campaigns'[budget] / 1000) * 1000
		dataType: int64
		lineageTag: 8318db23-257c-46fa-a0fc-b0c0faa2b4b9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns-ad83912e-4db2-4d35-bb13-8a39923ef565' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				    #"Campaigns Table" = Source{[Schema="marketing_db", Item="Campaigns"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Campaigns Table", {{"campaign_id", "Campaign ID"}, {"campaign_name", "Campaign Name"}, {"channel", "Channel"}, {"start_date", "Start Date"}, {"end_date", "End Date"}, {"budget", "Budget"}, {"spend", "Spend"}, {"target_audience", "Target Audience"}, {"creative_url", "Creative URL"}, {"utm_source", "UTM Source"}, {"utm_medium", "UTM Medium"}, {"utm_campaign", "UTM Campaign"}, {"region", "Region"}, {"status", "Status"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

