table Campaigns
	lineageTag: 218a57ff-4f79-4b28-af00-971c33028ebe

	measure 'Non-Blank Leads' = COUNTA('Leads'[lead_name])
		displayFolder: Measures
		lineageTag: 50d5064c-a435-4f21-ac20-32268f72355f

	measure 'Budget Deal Correlation' = VAR _MeanX = AVERAGEX(ALL('Table'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Table'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Table'), ('Campaigns'[budget] - _MeanX) * ('Leads'[deal_value] - _MeanY)) VAR _StdX = SQRT(SUMX(ALL('Table'), ('Campaigns'[budget] - _MeanX) ^ 2)) VAR _StdY = SQRT(SUMX(ALL('Table'), ('Leads'[deal_value] - _MeanY) ^ 2)) RETURN DIVIDE(_Cov, _StdX * _StdY, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f6e07b3a-6d06-4229-965c-0e7dddc040ba

	measure 'Spend Engagement Covar' = VAR _MeanX = AVERAGEX(ALL('Table'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Table'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Table')) RETURN DIVIDE(SUMX(ALL('Table'), ('Campaigns'[spend] - _MeanX) * ('Leads'[engagement_score] - _MeanY)), _N - 1, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b42e5aa5-ed12-4961-946d-5bc0943a02e6

	measure 'Avg Deal by Channel' = CALCULATE(AVERAGE('Leads'[deal_value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 70169cc5-8737-4ef2-ace4-056323cbc42a

	measure 'Campaign ROI' = (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: cdd674ca-4654-47c9-b2a6-0852c7fe4a62

	measure 'Cost Per Lead' = SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0d3d01a4-ddcb-4d0a-ad8e-1852109ed2ba

	measure 'Window Best ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 746b7758-e1ae-4f59-adf0-3dee92726c8f

	measure 'Window Worst ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c4dd0cde-f0f2-4e92-8829-5baee81bd445

	measure 'Cumulative Leads' = CALCULATE(DISTINCTCOUNT('Leads'[lead_id]))
		displayFolder: Measures
		lineageTag: 49dbe545-3337-4094-8638-76485dfdfdc4

	measure 'Conversion Rate' = SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 448af8ee-479c-4f9b-b21b-fdd96fe1303f

	measure 'Target Channel' = "Email"
		lineageTag: 1d3a24ab-1608-4715-a7ac-bffc458f267a

	column campaign_id
		dataType: int64
		lineageTag: 16b94ade-488d-4726-8005-afd8fa391519
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: e95584cb-f5fc-4cd6-bdf2-79de45474382
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: a12dfa00-da1c-444c-b320-8c9b00423c33
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 04e0bd85-04a2-414a-b208-ec8095c4051f
		summarizeBy: none
		sourceColumn: start_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 59c59b38-a977-47aa-bf52-2069045e7fa4
		summarizeBy: none
		sourceColumn: end_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: 8b135e48-c135-4f5d-9828-cabf3b6fd7f1
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: #,0.00
		lineageTag: 658188ab-0296-46d9-9efd-03cea2b8d5a1
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column target_audience
		dataType: string
		lineageTag: 48624a25-fca0-4322-8355-9f2c945f4656
		summarizeBy: none
		sourceColumn: target_audience

		annotation SummarizationSetBy = Automatic

	column creative_url
		dataType: string
		lineageTag: c4584799-4b97-455b-834b-5dbf24673fce
		summarizeBy: none
		sourceColumn: creative_url

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: c18e87f7-caea-4ca8-be3e-42492a649e78
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: d3a8df25-dac4-4398-b5e4-f7c6ebb1dd60
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: 2a360ca3-4bec-43e8-ab7b-74dc40df56b0
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: f6e17edd-b1ad-474a-8e1e-67f14abe9357
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: d910b40f-ffe0-4040-9910-7c15c36beb2d
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column 'Email Domain' = MID(RELATED('Leads'[email]), FIND("@", RELATED('Leads'[email])) + 1, LEN(RELATED('Leads'[email])))
		dataType: string
		lineageTag: c27cf841-350b-4eb0-ad2a-fc233e692239
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'First Name' = LEFT(RELATED('Leads'[lead_name]), FIND(" ", RELATED('Leads'[lead_name])) - 1)
		dataType: string
		lineageTag: ea8af5f5-31b0-479a-a4cf-df506a9d3400
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last Name' = MID(RELATED('Leads'[lead_name]), FIND(" ", RELATED('Leads'[lead_name])) + 1, LEN(RELATED('Leads'[lead_name])))
		dataType: string
		lineageTag: 3b794e77-1b8b-4677-ac72-dc0aef4cf08a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Name Length' = LEN(RELATED('Leads'[lead_name]))
		dataType: int64
		lineageTag: 0e2e4391-e72a-4783-b46a-339e8435d2ce
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean Phone' = TRIM(SUBSTITUTE(SUBSTITUTE(RELATED('Leads'[phone]), "-", ""), " ", ""))
		dataType: string
		lineageTag: c03cacf2-61ec-40fa-a04a-b46f3c117318
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Phone Last 4' = RIGHT(RELATED('Leads'[phone]), 4)
		dataType: string
		lineageTag: 5cd4d066-d9ab-4f84-b202-0b6d524316a8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Code' = UPPER(LEFT('Campaigns'[channel], 3)) & "-" & FORMAT('Campaigns'[campaign_id], "0") & REPT(" ", 5 - LEN(FORMAT('Campaigns'[campaign_id], "0")))
		dataType: string
		lineageTag: 09e8bf0d-f719-4b89-b4d6-7733fefa8410
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Enterprise' = CONTAINSSTRING('Campaigns'[target_audience], "Enterprise")
		dataType: boolean
		lineageTag: 4e00f8c8-10bb-469b-bd7e-e168e76436f0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Has Valid UTM' = CONTAINSSTRING('Campaigns'[utm_campaign], "^'Campaigns'[a-z0-9_-]+$")
		dataType: boolean
		lineageTag: 834ae1a6-1cf2-46ec-9837-abb12e971da1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean URL' = SUBSTITUTE('Campaigns'[creative_url], "https?://", "")
		dataType: string
		lineageTag: b5c3fb4a-4ab1-4bbf-983b-695b7bc2085a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Year' = DATE(YEAR('Campaigns'[start_date]), 1, 1)
		dataType: dateTime
		lineageTag: e3a0408d-c4d2-47a2-9901-788f05d972f0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Start Month' = MONTH('Campaigns'[start_date])
		dataType: int64
		lineageTag: 4b9a04d2-c03e-452d-93d7-a316d622c748
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT('Campaigns'[start_date], "MMMM")
		dataType: string
		lineageTag: 9833d292-c6a1-4677-accc-6b10ee542bf9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Days' = DATEDIFF('Campaigns'[start_date], 'Campaigns'[end_date], DAY)
		dataType: int64
		lineageTag: 5f2295be-bde8-4d39-a2e7-8f08f887f19e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Budget Band' = INT('Campaigns'[budget] / 1000) * 1000
		dataType: int64
		lineageTag: bd63448c-5e15-4e9c-b30a-1fb54b6a468f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns-e5928e3c-7473-4887-b042-031b5b525b17' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				    #"Campaigns Table" = Source{[Schema="marketing_db", Item="Campaigns"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Campaigns Table", {{"campaign_id", "Campaign ID"}, {"campaign_name", "Campaign Name"}, {"channel", "Channel"}, {"start_date", "Start Date"}, {"end_date", "End Date"}, {"budget", "Budget"}, {"spend", "Spend"}, {"target_audience", "Target Audience"}, {"creative_url", "Creative URL"}, {"utm_source", "UTM Source"}, {"utm_medium", "UTM Medium"}, {"utm_campaign", "UTM Campaign"}, {"region", "Region"}, {"status", "Status"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

