table Campaigns
	lineageTag: a02649c4-ea7d-4013-b137-b57605833180

	measure 'Non-Blank Leads' = COUNTA('Leads'[lead_name])
		displayFolder: Measures
		lineageTag: e1c4264e-4f88-4058-bd90-a96a0b512727

	measure 'Budget Deal Correlation' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) * ('Leads'[deal_value] - _MeanY)) VAR _StdX = SQRT(SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) ^ 2)) VAR _StdY = SQRT(SUMX(ALL('Campaigns'), ('Leads'[deal_value] - _MeanY) ^ 2)) RETURN DIVIDE(_Cov, _StdX * _StdY, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ac768b82-534a-4018-9b93-7e2e0d5b3b7a

	measure 'Spend Engagement Covar' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Campaigns')) RETURN DIVIDE(SUMX(ALL('Campaigns'), ('Campaigns'[spend] - _MeanX) * ('Leads'[engagement_score] - _MeanY)), _N - 1, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6e3b4b2c-4644-4b8c-989a-9811ec9f436d

	measure 'Avg Deal by Channel' = CALCULATE(AVERAGE('Leads'[deal_value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9d7646c5-0c30-4b46-9345-07707c3559df

	measure 'Campaign ROI' = (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: fa05ace5-f1d3-4f8a-a25a-72e57c8bcc0b

	measure 'Cost Per Lead' = SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9e53f38c-c3a5-4afc-9ef8-22492b8e18f8

	measure 'Window Best ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9dbe4f4d-7b27-4ea4-b9e0-68ac109ebab4

	measure 'Window Worst ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9fbb3abf-a7dc-4cff-83c8-6d031419d4fb

	measure 'Cumulative Leads' = CALCULATE(DISTINCTCOUNT('Leads'[lead_id]))
		displayFolder: Measures
		lineageTag: 63367f5e-fa52-46e3-a530-15b2c8854e6e

	measure 'Conversion Rate' = SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8167a677-f5bd-4c0a-938e-8b26909236d6

	measure 'Target Channel' = "Email"
		lineageTag: 13f1b67a-63cf-4e70-b980-29cb3edd84e9

	column campaign_id
		dataType: int64
		lineageTag: 66df8885-b022-488b-9e62-57ed3369761e
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 1a80a3f3-3201-4fdd-a352-5c225ac38d29
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: fd986080-9d46-4f33-a0b0-15845704fec1
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e33b0010-017b-4eb7-b854-fb0e430ae26f
		summarizeBy: none
		sourceColumn: start_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 63ffc4c8-9b3e-4616-879a-213be668b0b7
		summarizeBy: none
		sourceColumn: end_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: b40dca65-0cc5-45b4-b44d-658ddd5298f3
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: #,0.00
		lineageTag: 6173d4a8-1a9c-4dc4-a315-f87f1f964a0f
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column target_audience
		dataType: string
		lineageTag: 8896cebe-b361-4a92-ac12-2907a6bc6ad4
		summarizeBy: none
		sourceColumn: target_audience

		annotation SummarizationSetBy = Automatic

	column creative_url
		dataType: string
		lineageTag: cc353a6e-1145-44d4-837d-63fd82298cb3
		summarizeBy: none
		sourceColumn: creative_url

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 16c8b3bd-b343-404a-9a89-196a860e606d
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: 11fffdde-a02a-43fe-a729-0d2e10d499d1
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: b35d81f2-65f4-461b-9933-71bb9a0f0622
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 1b76f845-9029-4b0f-8ec1-b8dd66acbe5e
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 89427123-9ae6-469a-ab0b-1d73e86d6d4b
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column 'Email Domain' = MID(RELATED('Leads'[email]), FIND("@", RELATED('Leads'[email])) + 1, LEN(RELATED('Leads'[email])))
		dataType: string
		lineageTag: 44c46fc4-fadd-412a-a570-8b5567cd99b5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'First Name' = LEFT(RELATED('Leads'[lead_name]), FIND(" ", RELATED('Leads'[lead_name])) - 1)
		dataType: string
		lineageTag: 3af65467-227a-4e3b-9a21-5ecdb2da609d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last Name' = MID(RELATED('Leads'[lead_name]), FIND(" ", RELATED('Leads'[lead_name])) + 1, LEN(RELATED('Leads'[lead_name])))
		dataType: string
		lineageTag: bb9c0d3f-19f5-4e8d-b7f5-12aa9a6b5ea2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Name Length' = LEN(RELATED('Leads'[lead_name]))
		dataType: int64
		lineageTag: a004a80f-cb45-406a-9abb-6698bc6b3d06
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean Phone' = TRIM(SUBSTITUTE(SUBSTITUTE(RELATED('Leads'[phone]), "-", ""), " ", ""))
		dataType: string
		lineageTag: 96361327-4a39-4d6f-a7a6-bdeb89ea720f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Phone Last 4' = RIGHT(RELATED('Leads'[phone]), 4)
		dataType: string
		lineageTag: fad9ceac-dc49-4f95-8da7-675158b66dac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Code' = UPPER(LEFT('Campaigns'[channel], 3)) & "-" & FORMAT('Campaigns'[campaign_id], "0") & REPT(" ", 5 - LEN(FORMAT('Campaigns'[campaign_id], "0")))
		dataType: string
		lineageTag: 8738be2a-0c4b-45fd-b90f-7a9bc96dc2cd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Enterprise'
		dataType: boolean
		lineageTag: 04ac55e0-5f29-47b8-80a0-006df69fcc4c
		summarizeBy: none
		sourceColumn: 'Is Enterprise'

		annotation SummarizationSetBy = Automatic

	column 'Has Valid UTM' = /* REGEXP_MATCH: complex regex "^'Campaigns'[a-z0-9_-]+$" — verify manually */ CONTAINSSTRING('Campaigns'[utm_campaign], "^'Campaigns'[a-z0-9_-]+$")
		dataType: boolean
		lineageTag: d50e877f-1974-482c-96cb-52c94bd9a3f9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean URL' = /* REGEXP_REPLACE("https?://"): complex regex — verify manually */ SUBSTITUTE('Campaigns'[creative_url], "https?://", "")
		dataType: string
		lineageTag: f5f7ba91-7a5b-4949-9024-e08aa2e32f7c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Year' = DATE(YEAR('Campaigns'[start_date]), 1, 1)
		dataType: dateTime
		lineageTag: 61d5fb17-0ed6-4288-8538-266e9167dec4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Start Month'
		dataType: int64
		lineageTag: d98c1511-4cf8-4df8-8844-7349b0f39132
		summarizeBy: none
		sourceColumn: 'Start Month'

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT('Campaigns'[start_date], "MMMM")
		dataType: string
		lineageTag: dae4689c-71ef-41bc-80e2-2986965bc91f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Days' = DATEDIFF('Campaigns'[start_date], 'Campaigns'[end_date], DAY)
		dataType: int64
		lineageTag: 883aaa35-0f3f-4bd9-b8cc-c1ad8625e36d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Budget Band' = INT('Campaigns'[budget] / 1000) * 1000
		dataType: int64
		lineageTag: 15f86890-e903-45f1-b244-54251fb6dcf9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns-a78d833c-e1fa-4bde-a078-7dd3e53e0da5' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				    #"Campaigns Table" = Source{[Schema="marketing_db", Item="Campaigns"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Campaigns Table", {{"campaign_id", "Campaign ID"}, {"campaign_name", "Campaign Name"}, {"channel", "Channel"}, {"start_date", "Start Date"}, {"end_date", "End Date"}, {"budget", "Budget"}, {"spend", "Spend"}, {"target_audience", "Target Audience"}, {"creative_url", "Creative URL"}, {"utm_source", "UTM Source"}, {"utm_medium", "UTM Medium"}, {"utm_campaign", "UTM Campaign"}, {"region", "Region"}, {"status", "Status"}}),
				    #"Added Is Enterprise" = Table.AddColumn(#"Renamed Columns", "Is Enterprise", each Text.Contains([target_audience], "Enterprise"), type logical),
				    #"Added Start Month" = Table.AddColumn(#"Added Is Enterprise", "Start Month", each Date.Month([start_date]), Int64.Type),
				    Result = #"Added Start Month"
				in
				    Result

	annotation PBI_ResultType = Table

