table Campaigns
	lineageTag: d073548f-83d6-45c3-bc2a-d6c2b38b591c

	measure 'Non-Blank Leads' = COUNTA('Leads'[lead_name])
		displayFolder: Measures
		lineageTag: b1f5cf70-c504-4866-b159-b95fa2118efa

	measure 'Budget Deal Correlation' = VAR _MeanX = AVERAGEX(ALL('Table'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Table'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Table'), ('Campaigns'[budget] - _MeanX) * ('Leads'[deal_value] - _MeanY)) VAR _StdX = SQRT(SUMX(ALL('Table'), ('Campaigns'[budget] - _MeanX) ^ 2)) VAR _StdY = SQRT(SUMX(ALL('Table'), ('Leads'[deal_value] - _MeanY) ^ 2)) RETURN DIVIDE(_Cov, _StdX * _StdY, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: eac40f32-a9a6-4426-a8b1-c8e8c914d717

	measure 'Spend Engagement Covar' = VAR _MeanX = AVERAGEX(ALL('Table'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Table'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Table')) RETURN DIVIDE(SUMX(ALL('Table'), ('Campaigns'[spend] - _MeanX) * ('Leads'[engagement_score] - _MeanY)), _N - 1, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2b46136c-48cd-4408-8627-a85ba9dd01a4

	measure 'Avg Deal by Channel' = CALCULATE(AVERAGE('Leads'[deal_value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d4b6e754-5417-41ee-9d25-8539f2d66bc4

	measure 'Campaign ROI' = (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ab4c3b30-d0f3-4df4-afe1-ef29d0c168f4

	measure 'Cost Per Lead' = SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8451b2ac-15c4-430c-bfc8-6dcc9dd02142

	measure 'Window Best ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 748fb31b-3dc5-4772-b3e5-2436f72ade88

	measure 'Window Worst ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 30bda0ca-7b27-44cc-a6e0-7ffdb4f932c4

	measure 'Cumulative Leads' = CALCULATE(DISTINCTCOUNT('Leads'[lead_id]))
		displayFolder: Measures
		lineageTag: 21356130-9c94-46cb-b45f-10302242ddde

	measure 'Conversion Rate' = SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 41e2a2d3-c6fe-4cd3-b719-c6daa4526f2e

	measure 'Target Channel' = "Email"
		lineageTag: 2dbae67e-88ae-4869-a95d-5bd8e1d88bbf

	column campaign_id
		dataType: int64
		lineageTag: ba8b9f3e-b8e0-4732-8648-bf26655606bd
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 4233e111-1b46-4471-9666-96e464a69fe4
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: af9f63d0-5bd7-4a7f-acff-8e1fa45e0602
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 25cdc0d5-f648-4571-a321-73a5b506c473
		summarizeBy: none
		sourceColumn: start_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c144b02-89e5-4925-b9ae-3ac4f7338216
		summarizeBy: none
		sourceColumn: end_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: 5348e2e1-cda2-46d7-9256-120b33a8aec2
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: #,0.00
		lineageTag: 2ce6c361-4473-4cc2-98b3-ccbaf13ebafe
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column target_audience
		dataType: string
		lineageTag: bae3dfcf-c1e1-408c-aab9-507280a3d1fe
		summarizeBy: none
		sourceColumn: target_audience

		annotation SummarizationSetBy = Automatic

	column creative_url
		dataType: string
		lineageTag: f4144812-16ba-4c06-b10c-b66bf5c5d093
		summarizeBy: none
		sourceColumn: creative_url

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 7c1e4062-51e2-4594-9786-5f798191f032
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: fae6e745-cefc-4989-a32a-260290650689
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: 48c4b819-df50-4e58-87c4-8f52eb4fcbbd
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: bcc9fcea-4bb8-4a18-bd90-798e0c95a0bb
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 720d25bc-fb7f-4972-9b54-6545a3812f83
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column 'Email Domain' = MID(RELATED('Leads'[email]), FIND("@", RELATED('Leads'[email])) + 1, LEN(RELATED('Leads'[email])))
		dataType: string
		lineageTag: 9839078b-8f34-40cd-a601-3cd35614cc22
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'First Name' = LEFT(RELATED('Leads'[lead_name]), FIND(" ", RELATED('Leads'[lead_name])) - 1)
		dataType: string
		lineageTag: 88b0a358-1bb3-4669-ac9c-f9ee9648a671
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last Name' = MID(RELATED('Leads'[lead_name]), FIND(" ", RELATED('Leads'[lead_name])) + 1, LEN(RELATED('Leads'[lead_name])))
		dataType: string
		lineageTag: 5bf54e2a-0f11-4ffa-91a9-43c89d89d98e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Name Length' = LEN(RELATED('Leads'[lead_name]))
		dataType: int64
		lineageTag: 85a6d74c-0899-433e-aae9-a4171462ac67
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean Phone' = TRIM(SUBSTITUTE(SUBSTITUTE(RELATED('Leads'[phone]), "-", ""), " ", ""))
		dataType: string
		lineageTag: 451667ce-5d82-45c6-90bf-3d04f76665d5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Phone Last 4' = RIGHT(RELATED('Leads'[phone]), 4)
		dataType: string
		lineageTag: e59bdc51-2030-49a2-9591-490bcfe21a40
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Code' = UPPER(LEFT('Campaigns'[channel], 3)) & "-" & FORMAT('Campaigns'[campaign_id], "0") & REPT(" ", 5 - LEN(FORMAT('Campaigns'[campaign_id], "0")))
		dataType: string
		lineageTag: e92f52fd-0909-4469-94ef-016d98b7e46f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Enterprise' = CONTAINSSTRING('Campaigns'[target_audience], "Enterprise")
		dataType: boolean
		lineageTag: 7235de4f-b9e0-4360-9d93-14bec28affad
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Has Valid UTM' = CONTAINSSTRING('Campaigns'[utm_campaign], "^'Campaigns'[a-z0-9_-]+$")
		dataType: boolean
		lineageTag: a4fc226c-1c70-432e-8cfa-eb32e485a905
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean URL' = SUBSTITUTE('Campaigns'[creative_url], "https?://", "")
		dataType: string
		lineageTag: a836fe79-3b08-4069-9798-7f4adda18eb0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Year' = DATE(YEAR('Campaigns'[start_date]), 1, 1)
		dataType: dateTime
		lineageTag: 222d22a1-b4f3-4f86-9b28-ad1839ac10eb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Start Month' = MONTH('Campaigns'[start_date])
		dataType: int64
		lineageTag: e1742caa-906d-4dae-a305-e1253af4c934
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT('Campaigns'[start_date], "MMMM")
		dataType: string
		lineageTag: b0a686a8-ab23-4b66-bc1b-e6847318d1ec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Days' = DATEDIFF('Campaigns'[start_date], 'Campaigns'[end_date], DAY)
		dataType: int64
		lineageTag: bab6b3e6-ca36-4404-afef-292219389899
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Budget Band' = INT('Campaigns'[budget] / 1000) * 1000
		dataType: int64
		lineageTag: e9f2f1ba-8614-4f8a-b93c-b2cc6f1e7a3f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns-cee5f874-2e89-4474-9954-e85bb6f7faf9' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				    #"Campaigns Table" = Source{[Schema="marketing_db", Item="Campaigns"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Campaigns Table", {{"campaign_id", "Campaign ID"}, {"campaign_name", "Campaign Name"}, {"channel", "Channel"}, {"start_date", "Start Date"}, {"end_date", "End Date"}, {"budget", "Budget"}, {"spend", "Spend"}, {"target_audience", "Target Audience"}, {"creative_url", "Creative URL"}, {"utm_source", "UTM Source"}, {"utm_medium", "UTM Medium"}, {"utm_campaign", "UTM Campaign"}, {"region", "Region"}, {"status", "Status"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

