table Leads
	lineageTag: 1efd338a-03b9-4505-b4ef-f709fb983b1e

	column lead_id
		dataType: int64
		lineageTag: ba9b9898-935d-45b1-afed-ca4f02699dfd
		summarizeBy: sum
		sourceColumn: lead_id

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		lineageTag: 79459457-8292-4b3f-ae61-d263fccf5dac
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column lead_name
		dataType: string
		lineageTag: f04d19d6-29f4-4b81-aa3a-f9f9f7e8c913
		summarizeBy: none
		sourceColumn: lead_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 676cc8d8-3797-49e0-b8ab-b7dd76aa3cc0
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: d0bb1f41-737d-410c-9d92-fcb06551e478
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 575f7178-1ecc-421d-88be-9fe5918d93ee
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: c0821298-d9c6-443e-8e45-4049d2fc4be3
		summarizeBy: none
		sourceColumn: job_title

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3610fa60-583e-4d6f-bf6f-d01d7e1a2e3d
		summarizeBy: none
		sourceColumn: created_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column deal_value
		dataType: double
		formatString: #,0.00
		lineageTag: 4255b621-0b4f-4185-9471-61cf73c6a42f
		summarizeBy: sum
		sourceColumn: deal_value

		annotation SummarizationSetBy = Automatic

	column lead_source
		dataType: string
		lineageTag: 11e5af5a-b6a1-440a-af1e-e62fdb8c749f
		summarizeBy: none
		sourceColumn: lead_source

		annotation SummarizationSetBy = Automatic

	column lead_status
		dataType: string
		lineageTag: 4aeb0de5-66c0-48d3-900d-4ebacea19119
		summarizeBy: none
		sourceColumn: lead_status

		annotation SummarizationSetBy = Automatic

	column engagement_score
		dataType: double
		formatString: #,0.00
		lineageTag: 8f62a7f0-7961-4aed-bbc5-277eb1e0a649
		summarizeBy: sum
		sourceColumn: engagement_score

		annotation SummarizationSetBy = Automatic

	partition 'Leads-f4f9b254-369e-493b-a2b0-c69784307239' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				    #"Leads Table" = Source{[Schema="marketing_db", Item="Leads"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Leads Table", {{"lead_id", "Lead ID"}, {"campaign_id", "Campaign ID"}, {"lead_name", "Lead Name"}, {"email", "Email"}, {"phone", "Phone"}, {"company", "Company"}, {"job_title", "Job Title"}, {"created_date", "Created Date"}, {"deal_value", "Deal Value"}, {"lead_source", "Lead Source"}, {"lead_status", "Lead Status"}, {"engagement_score", "Engagement Score"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

