table 'Min Budget'
	lineageTag: fcbc4f47-a423-4f8d-94af-2dbf4b209184

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 21ff58ca-393b-4797-b9f6-a7efc6742dfc

	column Value
		dataType: double
		lineageTag: 56259ee4-91aa-4565-9005-82cff35bef32
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-97f90eec-a0c2-49fe-a355-4b4ac722e365' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

