table 'Min Budget'
	lineageTag: cb48fc88-3b03-4a15-9ade-ac5acf77200f

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: ccdf8a2e-25da-426e-8a3f-3f658697933c

	column Value
		dataType: double
		lineageTag: 5534b8c9-fe67-47eb-af52-0f437ff9ab7f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-d2d315a1-b2e5-4b00-b1b2-8beedebe0b48' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

