table 'Min Budget'
	lineageTag: 9a0ea434-a1c9-42dd-acc5-d1ff61a6dbae

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: a4691546-2c1b-45fe-a367-fed22a0bb59e

	column Value
		dataType: double
		lineageTag: 211a596d-ecba-40ef-80bd-fe41d83df2e5
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-a27b5838-9f24-4bbb-94bf-a8fb04e4aee7' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

