table 'Min Budget'
	lineageTag: 857e0cf9-d859-4413-8394-17901cab8022

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 8b111ac2-fc7a-4d91-a3ab-f566b1f076d1

	column Value
		dataType: double
		lineageTag: 97675ae3-31b4-417c-8b00-13dfb25f99fb
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-181867a3-9880-4aa2-bb4f-4a9cbb4f3876' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

