table 'Min Budget'
	lineageTag: 1aea4755-aeb7-49ea-9af5-6c3b31788402

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: b4a5d6b1-ff14-460e-b733-b649028dd397

	column Value
		dataType: double
		lineageTag: 70810df4-7cde-4b40-b1f8-191f1cf51111
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-efc3238b-de2d-4e61-9874-a381e8a0075d' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

