table Calendar
	lineageTag: 69eedf14-face-4fed-b33d-4c288d4bb6eb

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: da92d751-36c1-4f67-8be2-ea5778249c06

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ce96bbbc-7c60-4a32-be7f-ae1c7829e438

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0c3506dd-34f1-4eb1-9e24-60da5d6580f5

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 867ed10c-9472-4daf-81bb-551d6f80a537
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 706e6f9e-7967-4fc7-a59f-550ee0c7a3c3
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ad9cb85a-d529-4804-b858-842c9839c1a7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e40efe7e-4543-4c28-8ac8-82e6d69df1d0
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 5f12284c-c3d6-4378-9a0a-2f5a42cf8b40
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7aa5f0d7-3c37-422a-9ffc-cb50084c8c98
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d285b359-1453-4e18-8245-477dafc2786f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 88717645-1f4e-40da-8bb1-750fbcaa8000
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 53b43a8b-7280-48e9-997b-8235bb40ddae

		level Year
			ordinal: 0
			column: Year
			lineageTag: ca78e01d-b736-4c33-91b4-494c2666da11

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 5cf15649-fe36-463b-9cb4-81ae3d5c0340

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0003ca99-394a-4cea-8cf5-e3ddd5d0f9d7

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4c048e43-1c71-420e-90c4-2d436cf13e14


	partition 'Calendar-38d34db1-3565-488f-b806-accdb27e58bc' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

