table xy
	lineageTag: 1f321c51-c348-449f-b0d1-6a4a6ad12dcc

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 0d01c3d6-7af9-4fb9-9768-ef01cbd2d690

	column a
		dataType: string
		lineageTag: 553c3b84-1dc9-4f06-81ef-57fc839b80d5
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 2b26b1d3-e38f-45c6-ada2-1e6018762a79
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 7379b57f-2cbc-4ac1-9471-9cf8e0acbb20
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-934969bb-eca0-439e-8d64-694a0b37b81e' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: Unknown
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"a", "x", "y"},
				            {
				                {"Sample 1", 2, 3},
				                {"Sample 2", 3, 4}
				            }
				        )
				    otherwise
				        #table({"a", "x", "y"}, {})  // Empty table on error,
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

