table 'Business Unit'
	lineageTag: 54c084ed-6a1e-44b0-89da-60597378d60f
	description: Contains 1 columns and 1 measures: Value.

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		description: DAX: SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: a5b4f509-dc77-437c-bf67-21ba5bfe3c1b

	column Value
		dataType: string
		lineageTag: 45e65339-815e-4afd-a14d-70ce3a769845
		summarizeBy: none
		sourceColumn: Value
		description: String column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-6a478f34-9fc1-4ab7-86e3-24d24773a99e' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

