table 'Business Unit'
	lineageTag: a8321d56-62f5-4253-816c-ecff5abeda7a

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: f3df6483-9c17-45ec-92bd-bdff88cb9098

	column Value
		dataType: string
		lineageTag: 969414be-3acd-4da6-a638-540bc4312691
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-7d6f0d19-7560-4b10-ad0f-fc9b89a8c6a4' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

