table 'Business Unit'
	lineageTag: e36e8fb2-1afd-416b-939c-062571c66993

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: cc27a2fe-9a48-4def-8129-fd87f64d600c

	column Value
		dataType: string
		lineageTag: 7c5e31c1-3247-4305-94f1-2c1d5e7cf049
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-c056ca56-0dbc-490b-b65b-b7a40dc26ce0' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

