table 'Business Unit'
	lineageTag: 28495639-7d39-473b-a02a-ec85522a9065

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: fe7aa90d-1d70-4d4a-ae40-6827c78edf07
		annotation Copilot_Description = DAX: SELECTEDVALUE('Business Unit'[Value], "All")

	column Value
		dataType: string
		lineageTag: 9dd601da-ae0e-477a-a999-6c0aac5642db
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-1af753ef-3722-437b-9afb-40c8b55dd838' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

