table 'Business Unit'
	lineageTag: f0f17c8e-1f7e-4049-b50a-ee5ce1b119b3

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: b8e14356-18d4-4134-9673-f1880721ba08

	column Value
		dataType: string
		lineageTag: 18d0cd41-3e0a-4d30-993d-cbc34b707756
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-52af20f6-e647-4b99-b9e7-77f7818993e6' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

