table 'Business Unit'
	lineageTag: b022f78b-eaa6-479d-9d98-972f60ad5bda

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: afa4c61a-d787-4e5d-a5b0-e282b81b81ac

	column Value
		dataType: string
		lineageTag: 7b844cc0-1682-4426-a665-204b8eeab4b3
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-01f46699-5ccb-45de-b9ae-72bc707cbc15' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

