table 'Business Unit'
	lineageTag: 558e6c8f-fa8b-4094-83f1-6e14741285a3

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: e500a820-8653-4ced-881a-e219b8f8ec83

	column Value
		dataType: string
		lineageTag: aa40eff9-16a5-4dff-8dc5-f1d28b55471b
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-3de5208a-a688-4ccd-80d3-dd7d4a821079' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

