table Calendar
	lineageTag: 1c141864-fdc7-4139-b5c0-2f996d6cd2e4

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1f81b5f0-c57a-4fc7-b3f9-590c60910dc9

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 50b6ca2d-8cd2-4617-94e3-747523c62486

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 6d5ab4d7-4e0a-41bb-9de2-0d882d6353da

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d4d98761-1759-43a4-83fc-4aee67795f93
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 8b98a45d-62b4-4468-be34-811cc6170b99
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e4d70283-d54b-47d1-ad4c-d61674b88495
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: aa8227f5-6adb-4ace-8d9b-fd45f8feb0b1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 671cb966-eb87-490a-aa91-8a384e1ecfb0
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0032b919-1cef-4842-ad74-5bb1f9bda875
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 17cc3262-57dc-4d9e-b633-cc0838cc13cf
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 186d2183-b750-4b4d-8326-a92e02913a8c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6dc5a77b-84bd-43aa-9e13-7fe82206fc9d

		level Year
			ordinal: 0
			column: Year
			lineageTag: 55a254dd-9a9e-440a-9ec0-277457c973ac

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 399b102a-d1cb-462c-ba44-c3d913f7e0e0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 279f8d97-ebec-41fe-9036-6ff4a5f01e26

		level Day
			ordinal: 3
			column: Day
			lineageTag: 777516b3-dff2-4acb-80f9-cf7b0080e51d


	partition 'Calendar-5c91b095-c225-4fe8-94aa-3b9b4c22dc58' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

