table Calendar
	lineageTag: c0fae007-a33c-4798-b676-1d45ac0e5838

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1c5ae646-3e2b-4616-bef4-c3ffc6cb47dd

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: efe10c6c-3d47-49ca-b2e3-2a8468b90ef7

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: edcacda2-9f44-4479-a30c-be51348b9044

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a903f577-22a6-4864-87b1-f0423ae8abef
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 846a59a6-6572-4107-88d7-1f2bbf7631d7
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dd41d154-2994-4680-afa8-1d080127f547
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: da0c67f4-7258-4364-8c68-4254829e2881
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: cee57a82-fc89-4a33-bf58-c2529cdcb5dd
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 422fd792-8e39-4037-8656-0458aa7a5962
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a77fcf1c-8469-4d62-bfb8-2e48946e128e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 6f945aa6-97c7-4548-9236-684c592ba7e3
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 0f4738ec-356b-4fce-9f33-67dacc2ae968

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4bf0027e-2b91-4e12-b5ee-3c5dcc319982

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 361c70c2-354f-40bb-a252-afb4b4baf92c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c79a438c-7a4b-4174-b436-8c7be35f3293

		level Day
			ordinal: 3
			column: Day
			lineageTag: ca6e447b-dfd4-420a-82bb-6e3e8b4e302a


	partition 'Calendar-3ce91b52-8ab2-40c3-8513-023c18ee088e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

