table Calendar
	lineageTag: a940fa43-bfeb-4dbd-ad31-3aaef14fc5d4

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5e2d95ba-feb2-47cc-ba91-5ed2f0c0d13d

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: be9c1272-8e5c-4df4-95e8-7ddf62b08738

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 7837594b-2aaf-4736-bb56-d072e6f7306c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b1ceace0-9234-4dc6-abfe-ae9275b33763
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9521f61a-d2f3-4426-a013-80076774330c
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c8908b49-dada-4f7c-b38b-7674250dc968
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5aedfad6-d6c9-40b2-9a28-b8e02bd45d6e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ee56b107-f7c2-42f2-a8b2-10331132a38f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: c69f8a9f-a39b-401e-850a-1b0502a441bb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 9285c671-aadb-4bb5-bb89-00859277a200
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 3e6dd78a-7d07-4f36-824b-65efc91391e9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: eda854d0-de2c-4db1-9d61-20ea3f2df699

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7fd17448-66f9-4332-ac75-24f590b83111

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 476d786d-62a3-4c4a-b565-782310a86f15

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 77128643-01a1-4d8e-a073-1ff8f963a7ad

		level Day
			ordinal: 3
			column: Day
			lineageTag: bb8ee467-9d33-4989-8db8-29d0ead555a9


	partition 'Calendar-8a67080b-64b5-4f60-a3e3-97cfe3dd95b3' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

