table Calendar
	lineageTag: ec58d46c-85c6-42f8-a912-17e2de24fe56

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b3cf7c38-e2d4-44e5-a75b-3579141ac9f6

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 230393af-91b3-4e41-b208-0ad16aad4bfb

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 94543602-918f-4ec8-98b5-b243fd36bd0c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0dbab19d-44e4-49de-9ef9-23723e219870
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 62a06186-b7fb-469a-893a-5ad4d0a2cf98
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 840d54e8-c134-4f24-a568-4a3b115429cf
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b12b80f5-18ae-4ade-9c77-851f7b5d9bca
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e22e0cad-6c61-43f8-bd31-88583c5d3885
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 179d8c36-85dd-46d8-92b9-524d603d1d46
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4b4d6bb7-a7fb-481c-877c-b849a5624306
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 67ac00db-16ed-4410-ace1-b054d0aac5fb
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 70b4e80f-2d8f-44ad-85d2-1afa016249cf

		level Year
			ordinal: 0
			column: Year
			lineageTag: c21be664-3b78-4c1f-a56a-7d669c7fcb28

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 08e6773e-ea00-4d2e-9d3f-7222f9fc90b4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3da5f9fc-d610-4cf3-a8ad-64e4fb6a2b49

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4b71e3e3-c009-4695-bf67-f4cdab00a64c


	partition 'Calendar-f4e2da64-7a1c-4372-b707-d3c421146d2f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

