table Calendar
	lineageTag: 8dd9c81d-a8c9-4155-9f08-27dfe18e5338

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: fa09c5b7-0366-4d46-845e-13fe55bfc1ed

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 36ffa571-7088-4ee4-942f-b6d8695fcbf2

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 56542719-8442-4372-a014-00617caeff4d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fa60c7ea-1ad9-4820-947f-077db8ef3ed3
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 6424c2bc-58c3-4e7e-8462-0831457fba4e
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1c117fef-0591-41d4-ad66-00490b1eb760
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 672af793-29de-401d-8c6b-3ee7dc5ea05d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 5db925f9-d208-4de5-8def-be22962d4361
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b9c1d87d-effd-4923-bdac-54f2ba319a79
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f1dba332-1c50-4f0a-97db-71a80badf8e8
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 82204bab-b4fa-4c0e-823e-7ae6fd018e02
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4fd34b02-c7e8-458e-b558-b4687626ec66

		level Year
			ordinal: 0
			column: Year
			lineageTag: d22842ca-6f5b-4597-a997-5a535f11d7e3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ac32be74-dd92-4183-8df0-054df60b5494

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c56f3886-f0fc-4c10-8579-dfdce536f98f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7799c319-e582-4d4e-a489-dec594c8d944


	partition 'Calendar-12eca1fc-f958-49fe-a122-9effaaec1001' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

