table 'Fiscal Year'
	lineageTag: eaae5128-b9aa-4590-9bfb-99fe37fb334e

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 4e91af90-b75e-4f86-8b59-517b367f68a3
		annotation Copilot_Description = DAX: SELECTEDVALUE('Fiscal Year'[Value], 2024)

	column Value
		dataType: int64
		lineageTag: 156d4369-c16f-4d99-9859-f85c22e3127b
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-e75dec35-6752-4c5f-b697-02647e091940' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

