table 'Fiscal Year'
	lineageTag: bb42eded-735e-428c-b152-6b184a57dc65

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: a7ad29b5-d623-45c0-a35a-5ca510bdd20e

	column Value
		dataType: int64
		lineageTag: e795c202-50da-4e1a-9db0-d21f5da2a08f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-f685dbd2-365a-4908-a103-15a0d6c7d47f' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

