table 'Fiscal Year'
	lineageTag: 9fc29ee2-924f-4179-af8f-6c05cfc63a58

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 137537ec-0ffc-4399-838c-3b14434f6e45

	column Value
		dataType: int64
		lineageTag: 851f2229-ba99-4a88-ac5a-7edb8d66aff0
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-4cacf51c-a7f0-4fb4-b643-06f65446219a' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

