table 'Fiscal Year'
	lineageTag: 52a4274c-7912-44fe-b1c9-e7fa3e8fae1c

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 7fa142ed-9071-4286-a52f-7f7f9317463e

	column Value
		dataType: int64
		lineageTag: d143d20f-52c9-47a2-8050-a6f4f43ee7c7
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-008f1d9f-d928-4192-8f60-246a22ddb0d5' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

