table 'Fiscal Year'
	lineageTag: 7ce8c9bc-fbcf-48d0-adf8-51193c3e07a9

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 9f4e6ca2-7587-4104-b3ec-28c62533741d

	column Value
		dataType: int64
		lineageTag: 58031fb2-32dc-4aff-aa67-e1a92714d621
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-a3ab9483-a1f4-4be8-9825-fdf9a1b61d4c' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

