table 'Fiscal Year'
	lineageTag: cb9bb0b1-d8a5-42f0-80e1-d84e3669fd6e

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 4d7ae3aa-e5bf-4b21-b859-0b5f06bcfc0d

	column Value
		dataType: int64
		lineageTag: 86a49df2-f666-4f4f-ad2f-e68a9f409292
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-61acef89-093d-4247-a6f0-66b461e5a3e8' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

