table transactions
	lineageTag: f852830a-084c-4330-885a-999050a4231d

	measure Revenue = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ebb225a9-dafc-4feb-977d-dd0f96c1d2bd

	measure Expenses = SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6cbda446-647d-475a-b8af-8df9ae35caa2

	measure 'Net Income' = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 54dc1635-4b4f-479e-92e1-a3c030e7fac8

	measure 'Profit Margin %' = ([Revenue] - [Expenses]) / [Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: fd5cba93-fb38-4c54-bb34-794ea11edbc9

	measure 'YTD Revenue' = CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: eb3ef9b2-97ed-44f8-93c0-ea3a0584b180

	measure 'Budget Variance' = SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: da28c42e-3d4a-4a74-8ccb-b8cce8ad6db7

	column transaction_id
		dataType: int64
		lineageTag: 9ca70650-a1d0-4844-85a4-02e5811c42ae
		summarizeBy: sum
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 01a813bb-7b59-4e14-a221-fe7e8d341f51
		summarizeBy: none
		sourceColumn: transaction_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: df5fcb4a-97a8-467d-88d3-b9d052fc2821
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 574e125b-508f-4a8c-ac14-53f00778d431
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0.00
		lineageTag: a552b752-f931-4c90-9d91-b47f56fa3901
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: c28adfdd-5e47-4f3c-bab8-878c50a685c3
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: 7b35eca5-af3c-4a9a-aacd-bea18e6fc173
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column cost_center
		dataType: string
		lineageTag: 0e8e35a0-0e1d-4dfa-933f-334544716d8c
		summarizeBy: none
		sourceColumn: cost_center

		annotation SummarizationSetBy = Automatic

	partition 'transactions-c8dc5c55-583c-42b6-953f-9c8ab53bfbf6' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.company.com:5432", "finance"),
				
				            _nav = _src{[Schema="public", Item="transactions"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"transaction_id", "transaction_date", "account", "category", "amount", "type", "business_unit", "cost_center"}, {}),
				    Result = Source
				in
				    Result

	annotation PBI_ResultType = Table

