table transactions
	lineageTag: 18d3ce36-21b1-4962-bfa7-e214afa3464e

	measure Revenue = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d6260372-a623-424f-885c-1acb1d2886f1

	measure Expenses = SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: df5dba3e-2fab-4818-a322-13147dcae9af

	measure 'Net Income' = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d709315a-b7bf-46b8-95b5-2244c59c0b9d

	measure 'Profit Margin %' = ([Revenue] - [Expenses]) / [Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 09a64a99-beda-4d39-b56d-d6a5a11ac2b9

	measure 'YTD Revenue' = CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: cb0e74a8-1994-4f66-907d-6a95a7163784

	measure 'Budget Variance' = SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 161d9065-b25f-4f2d-9b30-9d3bb4e2fdd3

	column transaction_id
		dataType: int64
		lineageTag: 7fc04545-657c-48f8-a44b-162add8cba10
		summarizeBy: sum
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b1e412ab-1dfc-4d96-ab7e-8df6319f9b5b
		summarizeBy: none
		sourceColumn: transaction_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: 5338e54c-9d9d-4eb1-b470-dafadf9deca3
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 9e79004b-4c7b-47ca-bca4-b52834d38405
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0.00
		lineageTag: 0e18a1d8-9897-4946-8e74-37f279c1138f
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 3116f5dd-d6f3-4f05-82bd-40cf220c09dc
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: d9311d68-768c-4b94-97b6-36b20c65f020
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column cost_center
		dataType: string
		lineageTag: 5a95d863-6547-4f20-88e2-32a16e74fa34
		summarizeBy: none
		sourceColumn: cost_center

		annotation SummarizationSetBy = Automatic

	partition 'transactions-de3b555f-3ba3-4e17-b2b3-823bb45861b6' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("db.company.com:5432", "finance")
				
				    otherwise
				
				        #table({"transaction_id", "transaction_date", "account", "category", "amount", "type", "business_unit", "cost_center"}, {}),
				    #"transactions Table" = Source{[Schema="public", Item="transactions"]}[Data],
				    Result = #"transactions Table"
				in
				    Result

	annotation PBI_ResultType = Table

