table 'Alert Threshold'
	lineageTag: 904250f7-2313-4364-a609-0092ff700b3e

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 97539e2e-c6f3-4792-8e2a-ffb81f4e4feb

	column Value
		dataType: double
		lineageTag: 2ea82c1f-e38c-4e74-bfb9-219285c9a692
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-4ffb3c94-c111-40d5-b252-7c5691e9ad57' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

