table 'Alert Threshold'
	lineageTag: 65da06d5-e988-4ad2-af3b-c0526a3f76f7
	description: Contains 1 columns and 1 measures: Value.

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		description: DAX: SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 2b2860d1-bbbc-4444-956f-b41ffce95b0a

	column Value
		dataType: double
		lineageTag: d5f104ac-43e2-4bcc-b199-bc4cc9c5c329
		summarizeBy: none
		sourceColumn: Value
		description: Double column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-471d68d4-259a-4b71-9575-0703ec1fb212' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

