table 'Alert Threshold'
	lineageTag: 56876534-0e6d-4b51-abb8-652988425999

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 9e48597b-878a-46c1-9a35-8ba7f0aeadea

	column Value
		dataType: double
		lineageTag: b82e46ad-3d2d-48f8-9fab-561165f3bcf2
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-57fff5e0-0d93-4d1d-8a29-a55554261e32' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

