table 'Alert Threshold'
	lineageTag: 18629de9-47af-4bd6-8ace-53a42b96a377

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 957f445f-20c2-43d3-b2a3-2b21e6a0bfb8

	column Value
		dataType: double
		lineageTag: c2149c89-c3a8-414d-bd03-45af899b136b
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-9323cf1f-a17a-4866-baa2-08c3175fd4b9' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

