table 'Alert Threshold'
	lineageTag: ea66e7d5-f8cc-4ba3-9c40-2a64f8648230

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 1e00c098-1805-4089-84a0-99a073950874

	column Value
		dataType: double
		lineageTag: 9a674658-bb92-4e75-809e-401aef025d5a
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-9f54b53f-ca62-4507-8d1f-31c1fa9f3b18' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

