table 'Alert Threshold'
	lineageTag: 29453dfe-1806-4b34-bb50-65fbcc3a2639

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: fac47198-b472-4fcf-8a74-4207aa817bec

	column Value
		dataType: double
		lineageTag: 20b51ae9-9736-4bb0-a94f-4ac25e998b11
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-664d651f-a51c-4d19-8944-61447f864536' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

