table 'Alert Threshold'
	lineageTag: 243c1df0-1f38-47b7-89e7-e65e2e50db33

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: e5595bf7-08d7-484b-ae41-7b477e2bbf2d
		annotation Copilot_Description = DAX: SELECTEDVALUE('Alert Threshold'[Value], 100)

	column Value
		dataType: double
		lineageTag: 5be79df6-a6b4-445e-a9d7-c23d889b83a7
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-4e5ef63f-74e1-406d-a222-0cf26ab31cf4' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

