table 'Alert Threshold'
	lineageTag: e489c178-037d-4b78-80b5-5b220df295be

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: d32b3ff9-8a20-4229-9e55-b1ac5c887ffb

	column Value
		dataType: double
		lineageTag: 90d63496-86be-48c3-a024-af10832050e0
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-f2292c59-b2a0-4919-b3d8-d8abf170254a' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

