table 'Alert Threshold'
	lineageTag: b597ff7b-1899-4a1d-a92e-eedae9e6cdb0
	description: Contains 1 columns and 1 measures: Value.

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		description: DAX: SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 2f8ebc43-b3da-4054-871c-c16e48f686f2

	column Value
		dataType: double
		lineageTag: e517102e-6b80-477c-a643-4285dc80fd4c
		summarizeBy: none
		sourceColumn: Value
		description: Double column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-4ecff4e7-ee23-440c-ad30-c71ad5fa5efa' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

