table 'Alert Threshold'
	lineageTag: 94c35f13-26a9-415c-9d66-fb53dcf0b9cd

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 923f7079-2e0c-4b02-a11b-00535547b7d5

	column Value
		dataType: double
		lineageTag: 68be8605-6ef1-4a61-9639-645b52d53f34
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-cd281fb7-adc9-4fad-9051-42e19b095978' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

