table Calendar
	lineageTag: a4c9279c-6f52-45d4-b543-60c9a19a4582

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 733df826-9489-4012-a1e9-d7500b8ad153
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: fe34240b-2592-48c0-b236-fe881aeeb90b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8a2bb50f-d2cf-4fdd-b392-4fc9d29b862a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 27abe4f7-554c-4d88-9caa-67638e0a302a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 3971f34c-6e2e-4881-821d-606551e785c7
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0fb8f75d-605e-4f95-8969-1899f2ca59fb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 428f0796-e1c1-4f2c-ab7c-c89aba411c6e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e1c8f990-944d-4686-a5df-89d8982f9549
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ab5cd545-2705-4ea3-b24d-26ca49a343fe

		level Year
			ordinal: 0
			column: Year
			lineageTag: d76200fd-7753-4c3e-b067-af19e6b48d05

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 68284f48-c764-499d-984a-451746fdfc6c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 67836b62-a3b3-4f16-8ff9-bfa6c4cad3ae

		level Day
			ordinal: 3
			column: Day
			lineageTag: 2c49af98-1db1-4a2d-a15a-4bb719b64858


	partition 'Calendar-bd45ed49-61dc-43e0-8655-98a7b4a285f4' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

