table Calendar
	lineageTag: 653cf06b-4c05-459c-a343-a6079e31bbf8

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1e367767-90f5-4e47-97c2-f0bd5885b6fb
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 7877cba3-fded-4304-8085-c67c30e07407
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 791a11e1-56dd-4956-8af9-f9cf00fb3a99
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: fea58947-a0a6-45d5-8c8d-211e6734b954
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 6f04f262-8b8c-40f1-b11c-33ca6e2b6c89
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d9b6dcc9-0681-4f5e-ab73-70a8f829172b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 9eb68348-fc56-4634-ac7c-0c913de7d268
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d9776aac-138f-4a00-a471-5f2883ca797a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 759e188d-961e-4271-beeb-970d33622434

		level Year
			ordinal: 0
			column: Year
			lineageTag: a0fa54a0-d527-4da5-9c88-372cf11d4c1a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 54068a25-05db-4aae-9a17-807f2603a7ba

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 781d4504-bc12-45eb-9224-43738e28862f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4d0f0a87-3289-4540-8604-3b1c0d1abd43


	partition 'Calendar-3469b1cb-bba5-467c-a980-93784ef0adab' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

