table Calendar
	lineageTag: e07834c6-3184-4b35-80ea-27768438be1d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bd010204-10ea-4cc7-b063-61340bd203ae
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 8e426f08-6a77-45d3-960c-b1ceb67f5906
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e89c9736-e301-49d8-aec1-72eb1885e8fa
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ba8bd100-46ad-4a47-9be2-c2b60cdca40f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 77e34823-8b64-4e4d-bbcc-3e771b3fc9c3
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f2cdf072-9b6d-4879-b8d7-635a045740d8
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c0399a40-1580-48f2-9390-2acffc28b0fa
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 4d9a913d-3bb4-4ed6-bd82-02b10f58ee89
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ea656760-00b8-45fe-b3e4-a2ae6573f819

		level Year
			ordinal: 0
			column: Year
			lineageTag: 3912f658-f16b-4c65-b47b-80360e15bbcb

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f7684cbe-1147-4cf5-99d7-cc6fb0a49b72

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6f85e13d-bdd1-4a23-8c69-a09d737078db

		level Day
			ordinal: 3
			column: Day
			lineageTag: 107d9e22-9289-4bd6-89d2-abe502a6efe6


	partition 'Calendar-ca96d693-19ec-4ea7-be5a-0cda0b9cf3ac' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

