table Calendar
	lineageTag: 50393bfa-bbe1-4865-88af-0791acaf736e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 131389af-3fd4-438c-a13e-00f761e5d997
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 63481b3f-80eb-4c0f-b484-dbf5f986d69b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 91804e62-849f-42bd-a927-4a192cbbc6ed
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 595a6df3-1ade-47c6-80fa-414986421a06
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0f8e3668-4295-4aea-aac1-5d6156c51f1d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3ffa37f2-48d0-4b11-9972-df8b0613d0b0
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 3022a926-858d-47da-ae05-4b7dcf2d4d66
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 46eefd59-bc6f-4c3e-83ad-90e3e08b2204
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: afd06297-526a-4c98-be47-a3bb21742f15

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4c3b8817-40b5-47ce-b749-268c961d2361

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 53499680-dc1d-4363-8882-4a8d37479544

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 5a20b3d0-6078-4376-b7e5-2396dd88ebdf

		level Day
			ordinal: 3
			column: Day
			lineageTag: 66a5b4b4-d858-4d02-af95-dc20d98dc3e9


	partition 'Calendar-13a1711e-7ab9-4302-9bf0-462052520009' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

