table Calendar
	lineageTag: 1ec240c8-4ed7-4eea-a1f6-6dd82b85d4d0

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c5fec97b-c530-45e4-b5e2-3aaefee070f4
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 32be1d31-e7a3-41fc-ab36-9a421bf42c6a
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 651863bf-ef41-42a7-9a69-f98df9d4b862
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b4aebad8-e24a-4293-95d8-c586384cecb1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 41bcfaa1-93c8-41d2-afd7-728f63c30af4
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ea7596ae-b3b0-44e3-b9b0-1bb7c1944fef
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 8bcffd5c-1f63-40d7-85df-7330bd68914a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f5f86510-f751-4e90-8df4-2b8e80442620
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3f231e88-4777-4c44-a262-f58508a48ecd

		level Year
			ordinal: 0
			column: Year
			lineageTag: 145203eb-eafd-463a-9035-3b4bb3bb142a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d132363c-647b-4dfc-84ee-2fa44471ce4d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e76d90ea-8b6d-449e-a58a-d6719f524505

		level Day
			ordinal: 3
			column: Day
			lineageTag: 8656dd91-32bd-4f72-8462-0e5e85e1170b


	partition 'Calendar-129854ec-3384-4c22-9dac-dbbd9cb178fd' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

