table Calendar
	lineageTag: 3946d188-6900-4faf-849d-398f880d269b

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 7cbae7d7-43da-4d38-8080-fb92987e64cc
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a5708128-8e36-4449-9b93-29ef08f17666
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 08276ae0-2552-4a2d-a684-75e7b0ef8f53
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5c923176-981e-4c9a-8467-06d5e8839f6e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 7cca073e-6936-4216-9dbb-7f1f5607f154
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 96c93a97-359c-464c-8543-0be7059a908f
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b4d94229-26be-455b-acb9-a1de17c3bbdc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 5a3ae08d-5173-466d-ba48-fd0116bcfff2
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 39bdbd95-db9c-4fe5-8615-0930d27e643f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 08735398-cad8-4ee3-acd7-a733e40b36f8

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 8b01d2dd-e7d6-4334-a2e4-f5f7c9398122

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6ec6162a-707c-4362-bc46-864368d3afbd

		level Day
			ordinal: 3
			column: Day
			lineageTag: d33c2578-896e-47fa-b81b-0ec1d47b41a1


	partition 'Calendar-85ccef3d-9e89-45ff-b166-bb7ec51d6a1d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

