table Calendar
	lineageTag: 8fcf6d5d-e829-43d0-b07d-34b0dad8ef93

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0b418ff1-0a3b-4fde-8a81-cf7342c1ff8d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ab8e88eb-26fa-4543-b8e1-118d9b72935e
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8c182d37-44b1-40b4-973f-4c44c94e6d95
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 91273def-e009-462b-a15c-09e1ae6928d2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 218d2eb0-50d8-4437-8767-b4ae4d9ea251
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e1042ecc-a5ac-48ae-9a53-e5e4d63a034a
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b257b182-cc50-4c94-bdcf-bd93a8483b89
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e38173a1-9bfd-4857-8551-2c88ca579eab
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7fa3cb65-8607-48b7-a17a-7047386507ca

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4292c81d-77d5-4282-9a0f-e24c7ceeb578

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ec936388-72ee-4fe8-b89c-f26fe8490539

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ac7a1f8f-cadf-45b9-b7d8-c4a8048a8527

		level Day
			ordinal: 3
			column: Day
			lineageTag: 2d529ab5-f3f7-4036-9a02-0999cacb83e3


	partition 'Calendar-91d5978b-a899-45cd-b695-b6f230eb52b8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

