table Machines
	lineageTag: f9486e7f-7e1f-4209-88ea-26369ae04fde
	description: Contains 7 columns: machine_id, machine_name, machine_type, install_date, location, line_id, rated_capacity.

	column machine_id
		dataType: int64
		lineageTag: d8f9245a-0f5a-4cb5-a8b1-8529cafb4f17
		summarizeBy: sum
		sourceColumn: machine_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_name
		dataType: string
		lineageTag: 97f28943-c761-4a22-b046-4e56b9038314
		summarizeBy: none
		sourceColumn: machine_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column machine_type
		dataType: string
		lineageTag: 11077306-0b35-4a48-942d-1bf0526a1185
		summarizeBy: none
		sourceColumn: machine_type
		description: String column.

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7b724399-19dd-48ef-9fc0-8200755f7186
		summarizeBy: none
		sourceColumn: install_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 0e0eb00f-0f4e-481c-8e4a-0dee8c5c6398
		summarizeBy: none
		sourceColumn: location
		description: String column.

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: string
		lineageTag: c09d2dec-2630-49fc-a8ec-dd8d358e383f
		summarizeBy: none
		sourceColumn: line_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column rated_capacity
		dataType: double
		formatString: #,0.00
		lineageTag: cc7f90dc-7d4c-4556-aeac-1b110ab6eb11
		summarizeBy: sum
		sourceColumn: rated_capacity
		description: Double column.

		annotation SummarizationSetBy = Automatic

	partition 'Machines-11ca0c6a-643c-43f8-9289-b90cc33d07c6' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Machines"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"machine_id", "machine_name", "machine_type", "install_date", "location", "line_id", "rated_capacity"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"machine_id", "Machine ID"}, {"machine_name", "Machine Name"}, {"machine_type", "Machine Type"}, {"install_date", "Install Date"}, {"location", "Location"}, {"line_id", "Line ID"}, {"rated_capacity", "Rated Capacity"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns: machine_id, machine_name, machine_type, install_date, location, line_id, rated_capacity.

