table Machines
	lineageTag: 666eaf29-c4fd-4719-b510-a3667df2a451

	column machine_id
		dataType: int64
		lineageTag: 37f0652d-2930-4a0d-a298-ebf1ee7ebcff
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column machine_name
		dataType: string
		lineageTag: 6eaf18f0-f805-4edf-9497-b295ba6c21fb
		summarizeBy: none
		sourceColumn: machine_name

		annotation SummarizationSetBy = Automatic

	column machine_type
		dataType: string
		lineageTag: e3bd39e1-2a75-4a47-8b15-92fa12f0c603
		summarizeBy: none
		sourceColumn: machine_type

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 254997e0-1472-42ce-a314-51d29d1c949a
		summarizeBy: none
		sourceColumn: install_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 4d62804b-bb75-4c3e-8dba-ae1dbdf27b53
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: string
		lineageTag: e0418ff1-b620-4e82-8864-fc2468bb0b24
		summarizeBy: none
		sourceColumn: line_id

		annotation SummarizationSetBy = Automatic

	column rated_capacity
		dataType: double
		formatString: #,0.00
		lineageTag: 0a4b9c48-dabe-4c31-b94e-c633a6ae5f26
		summarizeBy: sum
		sourceColumn: rated_capacity

		annotation SummarizationSetBy = Automatic

	partition 'Machines-6eca43c2-0720-4b6e-bd9f-30fecc1c4e93' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Machines"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"machine_id", "machine_name", "machine_type", "install_date", "location", "line_id", "rated_capacity"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"machine_id", "Machine ID"}, {"machine_name", "Machine Name"}, {"machine_type", "Machine Type"}, {"install_date", "Install Date"}, {"location", "Location"}, {"line_id", "Line ID"}, {"rated_capacity", "Rated Capacity"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

