table Machines
	lineageTag: b2c6a034-2e75-404f-86dc-fc85bf9b5c08
	description: Contains 7 columns: machine_id, machine_name, machine_type, install_date, location, line_id, rated_capacity.

	column machine_id
		dataType: int64
		lineageTag: c631c1cf-c13d-41bf-9d7b-49176c45c1c6
		summarizeBy: sum
		sourceColumn: machine_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_name
		dataType: string
		lineageTag: b456afea-e0e5-4b5d-a63a-48791b042858
		summarizeBy: none
		sourceColumn: machine_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column machine_type
		dataType: string
		lineageTag: 4221fc43-9e16-43e9-a821-c40835eb8bf0
		summarizeBy: none
		sourceColumn: machine_type
		description: String column.

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		formatString: General Date
		lineageTag: cc560c32-4403-48e0-8368-50e95118e502
		summarizeBy: none
		sourceColumn: install_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: c495f55a-29c2-4f60-9e60-2bd39cbd2316
		summarizeBy: none
		sourceColumn: location
		description: String column.

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: string
		lineageTag: 6c4a797f-590e-4177-9c94-8f9af8ce05d6
		summarizeBy: none
		sourceColumn: line_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column rated_capacity
		dataType: double
		formatString: #,0.00
		lineageTag: 2c59903a-3b75-4953-ac0c-b349ae71b8ca
		summarizeBy: sum
		sourceColumn: rated_capacity
		description: Double column.

		annotation SummarizationSetBy = Automatic

	partition 'Machines-305c3a6e-c31b-41a6-88c4-3cf9c982748e' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Machines"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"machine_id", "machine_name", "machine_type", "install_date", "location", "line_id", "rated_capacity"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"machine_id", "Machine ID"}, {"machine_name", "Machine Name"}, {"machine_type", "Machine Type"}, {"install_date", "Install Date"}, {"location", "Location"}, {"line_id", "Line ID"}, {"rated_capacity", "Rated Capacity"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns: machine_id, machine_name, machine_type, install_date, location, line_id, rated_capacity.

