table Maintenance
	lineageTag: f36d3b21-7a8a-44da-acfb-b83c8808947c

	column maint_id
		dataType: int64
		lineageTag: ae371344-7efc-4f1c-9897-2efc739ec814
		summarizeBy: sum
		sourceColumn: maint_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 32502a28-fff3-426f-9230-d31b8b79d7a5
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: fe4df680-bd19-4da7-a7b9-c7d91ee3caeb
		summarizeBy: none
		sourceColumn: maint_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: b8c4c20a-af95-40fc-aeab-a9568f0d73d5
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 299a4d06-2175-414d-858f-41c77bcff1eb
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: 9c03a6aa-b45c-4b11-b01b-2c576383c04d
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: 6267cadd-ef54-40d4-87d0-f56f84659681
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: cecdf1e9-a7ec-4f4c-a9b5-0592705964b9
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-ca6722ee-6f8e-4f89-ac73-f5974fed545f' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Maintenance"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"maint_id", "machine_id", "maint_date", "maint_type", "maint_cost", "downtime_hours", "technician", "description"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns: maint_id, machine_id, maint_date, maint_type, maint_cost, downtime_hours, technician, description.

