table Maintenance
	lineageTag: 1a724868-d3c2-4bc2-898e-dec211c0a90b

	column maint_id
		dataType: int64
		lineageTag: 279b5c4e-608a-4f21-8fcc-35a1a59bc087
		summarizeBy: sum
		sourceColumn: maint_id

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: d75c08a5-aff7-4be7-9a26-bb41ad7c6cd4
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c43db3a-93a2-4955-9d3c-82553493b585
		summarizeBy: none
		sourceColumn: maint_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: b3da5ab6-0802-4912-81fc-26f63b6cbb15
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 972b4f00-9ffb-4ffd-baec-ef1f64d5f389
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: d73c1f9d-27b9-489b-a800-6d749dacc4e5
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: 28a25521-3469-434a-97cd-b1746262c922
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 4863ec71-465a-4b29-9360-16acaa140136
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-003dc10e-a10f-49fe-af9f-ae182615b565' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        Oracle.Database("mfg-oracle.corp.local:1521/MFGDB")
				
				    otherwise
				
				        #table({"maint_id", "machine_id", "maint_date", "maint_type", "maint_cost", "downtime_hours", "technician", "description"}, {}),
				    #"Maintenance Table" = Source{[Schema="DBO", Item="Maintenance"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Maintenance Table", {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

