table Maintenance
	lineageTag: 05ad68f9-7c74-4c0c-82d8-6658eeb27a0b
	description: Contains 8 columns: maint_id, machine_id, maint_date, maint_type, maint_cost, downtime_hours, technician, description.

	column maint_id
		dataType: int64
		lineageTag: d2e107ec-e69f-4af0-b0fc-4701edb2cf5a
		summarizeBy: sum
		sourceColumn: maint_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 3000fb82-a31d-43fe-98a8-41ca1340fbf8
		summarizeBy: sum
		sourceColumn: machine_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: be6e9551-54bd-4cf9-acf8-0ea28b562d70
		summarizeBy: none
		sourceColumn: maint_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: dafd71e6-6bd3-4f40-b8bc-a623531c0130
		summarizeBy: none
		sourceColumn: maint_type
		description: String column.

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 8253343d-844d-4632-ae2a-202285b47d74
		summarizeBy: sum
		sourceColumn: maint_cost
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: 4b97e1de-ed59-46a8-9694-c7172312338c
		summarizeBy: sum
		sourceColumn: downtime_hours
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: d6d24cbf-e6d4-4e95-8aef-f51b18763bd6
		summarizeBy: none
		sourceColumn: technician
		description: String column.

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 0739f64b-79e0-4232-9843-9ce381f2375e
		summarizeBy: none
		sourceColumn: description
		description: String column.

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-1be6684d-d0e7-4f99-b679-7bfc91710f7b' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Maintenance"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"maint_id", "machine_id", "maint_date", "maint_type", "maint_cost", "downtime_hours", "technician", "description"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns: maint_id, machine_id, maint_date, maint_type, maint_cost, downtime_hours, technician, description.

