table Maintenance
	lineageTag: 25e9e524-80b8-41f0-8bb3-cb396e2d2fd9

	column maint_id
		dataType: int64
		lineageTag: 862c03c9-6a25-44df-88cf-46d52c2dd10f
		summarizeBy: sum
		sourceColumn: maint_id

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 1135f6ed-58cb-40b8-b048-a022ace716f6
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 27fb2565-726a-4184-a0c5-790a75939933
		summarizeBy: none
		sourceColumn: maint_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: aa980577-1516-47dc-a43e-cc886b577aa4
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 6a01a2b1-1ff9-4a96-bf8a-c2b6a1cd9bf0
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: 952dd553-9e5d-491b-a455-8d465822bcdf
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: edf8e8de-e924-4527-b52c-73b1000e3640
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: de2d41b7-b551-49f8-9f1d-e75dfc204ebb
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-26f098b7-db9f-4ff6-a334-e03ecffed8cb' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        Oracle.Database("mfg-oracle.corp.local:1521/MFGDB")
				
				    otherwise
				
				        #table({"maint_id", "machine_id", "maint_date", "maint_type", "maint_cost", "downtime_hours", "technician", "description"}, {}),
				    #"Maintenance Table" = Source{[Schema="DBO", Item="Maintenance"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Maintenance Table", {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

