table Maintenance
	lineageTag: 39132bfa-256a-4a5d-93c6-c98ab1e639b1
	description: Contains 8 columns: maint_id, machine_id, maint_date, maint_type, maint_cost, downtime_hours, technician, description.

	column maint_id
		dataType: int64
		lineageTag: 29498897-0a80-454b-8f9d-438db9ff008c
		summarizeBy: sum
		sourceColumn: maint_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 75153f90-f09e-4879-bf53-6d9276571df5
		summarizeBy: sum
		sourceColumn: machine_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b24483f8-960b-434a-9dbf-2d13700bd47b
		summarizeBy: none
		sourceColumn: maint_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: 9f20d8ab-1317-44f2-bf36-74d662845331
		summarizeBy: none
		sourceColumn: maint_type
		description: String column.

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 42ece377-9d10-4ef2-a4ac-ac631dde801c
		summarizeBy: sum
		sourceColumn: maint_cost
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: a7403a15-eed9-435e-81da-fb75cf61ef41
		summarizeBy: sum
		sourceColumn: downtime_hours
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: f8dd3d20-8898-4f8b-9911-b14d5cd4ab75
		summarizeBy: none
		sourceColumn: technician
		description: String column.

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 2d73d4da-a3e1-4052-a9cd-a2daff95d8be
		summarizeBy: none
		sourceColumn: description
		description: String column.

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-953067a8-bb67-44cc-9e5d-e10f2fa1e3cf' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Maintenance"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"maint_id", "machine_id", "maint_date", "maint_type", "maint_cost", "downtime_hours", "technician", "description"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns: maint_id, machine_id, maint_date, maint_type, maint_cost, downtime_hours, technician, description.

