table Sensors
	lineageTag: 95e1b060-1ab3-4bb7-a246-c6f41187a360
	description: Contains 26 columns and 13 measures: reading_id, reading_time, machine_id, sensor_type, value, threshold_min, threshold_max, unit, ... (26 columns total).

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: MEDIAN([value]) | DAX: MEDIAN('Sensors'[value])
		lineageTag: 97b0341f-8d10-4b46-82d5-9ed4e3385c9c

	measure 'P95 Value' = PERCENTILE.INC('Sensors'[value], 0.95)
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: PERCENTILE([value], 0.95) | DAX: PERCENTILE.INC('Sensors'[value], 0.95)
		lineageTag: 049f9a30-36e7-4423-91d0-51d602f15776

	measure 'Value Variance' = VAR.S('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: VAR([value]) | DAX: VAR.S('Sensors'[value])
		lineageTag: 3e36e934-d429-4684-a482-d35cdf91cb1d

	measure 'Value Variance Pop' = VAR.P('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: VARP([value]) | DAX: VAR.P('Sensors'[value])
		lineageTag: 98ee4a2c-00a9-4aad-8052-b5e0502fa0fa

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {INCLUDE [sensor_type], [machine_id] : AVG([value])} | DAX: CALCULATE(AVERAGE('Sensors'[value]))
		lineageTag: cf57eb04-84ea-4693-8ced-21c0c0cf2af3

	measure 'Running Avg Value' = CALCULATE(AVERAGE('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_AVG: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_AVG(AVG([value])) | DAX: CALCULATE(AVERAGE('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_AVG: converted to cumulative — v...
		lineageTag: 9890a638-fd29-4b91-9ec4-0911f9cb8cfc

	measure 'Running Count' = CALCULATE(COUNT('Sensors'[reading_id]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_COUNT: converted to cumulative — verify window scope */
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_COUNT(COUNT([reading_id])) | DAX: CALCULATE(COUNT('Sensors'[reading_id]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_COUNT: converted to cumulativ...
		lineageTag: 8463ae76-9020-4656-b5dc-301585deb88e

	measure 'Running Max Value' = CALCULATE(MAX('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MAX: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_MAX(MAX([value])) | DAX: CALCULATE(MAX('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MAX: converted to cumulative — verif...
		lineageTag: 2e767a0f-ee3f-4f0e-83b5-f8a9ebec74f3

	measure 'Running Min Value' = CALCULATE(MIN('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MIN: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_MIN(MIN([value])) | DAX: CALCULATE(MIN('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MIN: converted to cumulative — verif...
		lineageTag: 7f68923e-944a-4b1b-83ce-c1b748208b75

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		description: Migrated from Tableau: RANK_DENSE(SUM([value])) | DAX: RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		lineageTag: d7b6c97a-10b3-4d67-b2f4-3d0a10323617

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		description: Migrated from Tableau: RANK_UNIQUE(AVG([value])) | DAX: RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		lineageTag: d25a42e8-6029-4426-abd0-18d39c55aad8

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: WINDOW_SUM(SUM([value])) | DAX: CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		lineageTag: cdafea92-d15c-49f7-bbe7-0b1d821e3799

	measure 'Time Granularity' = "Hour"
		description: DAX: "Hour"
		lineageTag: 797c37a7-0a51-4a6a-ba3b-03848dce27d4

	column reading_id
		dataType: int64
		lineageTag: a69501f2-c3f0-4dc0-a5c8-63c775d66685
		summarizeBy: sum
		sourceColumn: reading_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 01a2a3d0-8313-4820-8886-bfe4aee7fc4a
		summarizeBy: none
		sourceColumn: reading_time
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 93e4eeb7-6255-4a4e-b68a-b9ff321f1570
		summarizeBy: sum
		sourceColumn: machine_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: 1b9cf47a-cbe8-4212-9caa-bfe103a105d3
		summarizeBy: none
		sourceColumn: sensor_type
		description: String column.

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 2d56ebe7-039d-4093-aafc-0ab73d4c9e27
		summarizeBy: sum
		sourceColumn: value
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: 54a89a74-fe25-4139-b535-3c9160eb7e71
		summarizeBy: sum
		sourceColumn: threshold_min
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: 59d27b7b-8445-4479-9802-a88d6d4abe16
		summarizeBy: sum
		sourceColumn: threshold_max
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: c7f50859-ef54-4de3-832c-2132c89b292e
		summarizeBy: none
		sourceColumn: unit
		description: String column.

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: 3476b178-38d2-4b42-b9d0-8fe069bd56a9
		summarizeBy: sum
		sourceColumn: quality_score
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: 16212506-d4b2-4739-94fa-5a1f8048fc3f
		summarizeBy: none
		sourceColumn: plant_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: f8c8717b-1576-4c80-8bac-f827338a74c1
		summarizeBy: sum
		sourceColumn: delta_value
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: 6b9d1ba2-64a8-48c0-bae4-42f933ecacbd
		summarizeBy: sum
		sourceColumn: angle_degrees
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: bad69754-1111-4c79-a524-c168efb21644
		summarizeBy: sum
		sourceColumn: power_watts
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation'
		dataType: double
		formatString: #,0.00
		lineageTag: 0ee4ac1c-e606-4b01-9122-cbeebe574e85
		summarizeBy: none
		sourceColumn: 'Abs Deviation'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: 4b237618-fc06-4ede-b219-646b3b7f842e
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Floor Value'
		dataType: double
		formatString: #,0.00
		lineageTag: e074ffde-9e01-4586-a033-c95ee5a1813c
		summarizeBy: none
		sourceColumn: 'Floor Value'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value'
		dataType: double
		formatString: #,0.00
		lineageTag: d35ac0f8-2c34-42a2-846f-1b6314abe101
		summarizeBy: none
		sourceColumn: 'Rounded Value'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: ecfd1bf9-cc93-4a49-a8cb-1bd37a3994aa
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: 58cb695d-a9e7-4675-8f46-25b445f8d25b
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 15620d5d-b596-4e41-b30c-25508f38e956
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 5b754bfd-fb87-49fd-b606-29b4b4c6cd84
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: aa4ed1b6-d71d-46c6-affd-b1595bfa2b1c
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Reading Month'
		dataType: dateTime
		lineageTag: 19a8128a-1a7f-428f-a21d-a3496f704489
		summarizeBy: none
		sourceColumn: 'Reading Month'
		description: Datetime column.

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		lineageTag: dee279c3-1b6c-4531-81a8-62c1afaf99c2
		summarizeBy: none
		description: Calculated column (DateTime).

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: 81567aec-fa07-4d0b-8659-007cde529db0
		summarizeBy: none
		description: Calculated column (Int64).

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: 0d1f1e12-8318-408c-ab63-15dc03b65cd8
		summarizeBy: none
		description: Calculated column (Int64).

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-26e92506-8392-4268-9e54-8b166a8cb8fd' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Sensors"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"reading_id", "reading_time", "machine_id", "sensor_type", "value", "threshold_min", "threshold_max", "unit", "quality_score", "plant_id", "delta_value", "angle_degrees", "power_watts"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    #"Added Abs Deviation" = Table.AddColumn(#"Renamed Columns", "Abs Deviation", each Number.Abs([value] - ([threshold_min] + [threshold_max]) / 2), type number),
				    #"Added Floor Value" = Table.AddColumn(#"Added Abs Deviation", "Floor Value", each Number.RoundDown([value] / 1) * 1, type number),
				    #"Added Rounded Value" = Table.AddColumn(#"Added Floor Value", "Rounded Value", each Number.Round([value], 2), type number),
				    #"Added Reading Month" = Table.AddColumn(#"Added Rounded Value", "Reading Month", each #date(Date.Year([reading_time]), Date.Month([reading_time]), 1), type datetime),
				    Result = #"Added Reading Month"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 26 columns and 13 measures: reading_id, reading_time, machine_id, sensor_type, value, threshold_min, threshold_max, unit, ... (26 columns total).

