table Sensors
	lineageTag: 8570203a-3c42-4497-a257-483eec538f5c
	description: Contains 26 columns and 13 measures: reading_id, reading_time, machine_id, sensor_type, value, threshold_min, threshold_max, unit, ... (26 columns total).

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: MEDIAN([value]) | DAX: MEDIAN('Sensors'[value])
		lineageTag: 558c15be-0e51-4e56-a8f7-c3f8def86367

	measure 'P95 Value' = PERCENTILE.INC('Sensors'[value], 0.95)
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: PERCENTILE([value], 0.95) | DAX: PERCENTILE.INC('Sensors'[value], 0.95)
		lineageTag: 988ea782-bb3a-4664-8100-ab4fdcbbf9ae

	measure 'Value Variance' = VAR.S('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: VAR([value]) | DAX: VAR.S('Sensors'[value])
		lineageTag: 5b51e90b-ad62-4d38-82dd-7645a95b77e5

	measure 'Value Variance Pop' = VAR.P('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: VARP([value]) | DAX: VAR.P('Sensors'[value])
		lineageTag: a938fae0-e0f8-4da5-83b6-19d5dda65d18

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {INCLUDE [sensor_type], [machine_id] : AVG([value])} | DAX: CALCULATE(AVERAGE('Sensors'[value]))
		lineageTag: 800f6944-506a-43d4-8e96-f8e8e817dddd

	measure 'Running Avg Value' = CALCULATE(AVERAGE('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_AVG: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_AVG(AVG([value])) | DAX: CALCULATE(AVERAGE('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_AVG: converted to cumulative — v...
		lineageTag: 4f4456db-9c6f-4e18-91aa-5f540ff9d8b3

	measure 'Running Count' = CALCULATE(COUNT('Sensors'[reading_id]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_COUNT: converted to cumulative — verify window scope */
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_COUNT(COUNT([reading_id])) | DAX: CALCULATE(COUNT('Sensors'[reading_id]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_COUNT: converted to cumulativ...
		lineageTag: 203631f6-371a-4cc8-b823-fdd0149fe722

	measure 'Running Max Value' = CALCULATE(MAX('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MAX: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_MAX(MAX([value])) | DAX: CALCULATE(MAX('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MAX: converted to cumulative — verif...
		lineageTag: 1acb5780-999b-4566-a6ca-b188f39bc578

	measure 'Running Min Value' = CALCULATE(MIN('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MIN: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_MIN(MIN([value])) | DAX: CALCULATE(MIN('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MIN: converted to cumulative — verif...
		lineageTag: f04c19a1-602f-4866-aa00-3df8a72e6b51

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		description: Migrated from Tableau: RANK_DENSE(SUM([value])) | DAX: RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		lineageTag: 52d3fda9-86d6-4438-8969-3c7a89a0fb34

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		description: Migrated from Tableau: RANK_UNIQUE(AVG([value])) | DAX: RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		lineageTag: 19951435-2050-4494-8392-e3261058b8c4

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: WINDOW_SUM(SUM([value])) | DAX: CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		lineageTag: ccca8022-be93-47c1-b306-98b30b56680a

	measure 'Time Granularity' = "Hour"
		description: DAX: "Hour"
		lineageTag: f7e07cb6-2b40-4923-a5f1-46b7a667cd8a

	column reading_id
		dataType: int64
		lineageTag: 3bf42ca0-e40e-4f58-bdfe-c11b0ce4dfeb
		summarizeBy: sum
		sourceColumn: reading_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 74220c71-fc4b-43ee-86d0-0b7259b453d6
		summarizeBy: none
		sourceColumn: reading_time
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 43a6b934-31a3-496b-8716-a1acae0e4c58
		summarizeBy: sum
		sourceColumn: machine_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: cff14906-0753-4157-b892-cfa18b807fce
		summarizeBy: none
		sourceColumn: sensor_type
		description: String column.

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: ce5aab93-c197-43fa-92ba-97ddff7dbf56
		summarizeBy: sum
		sourceColumn: value
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: 6dc4707a-3f2c-4c39-beba-34f77a73deeb
		summarizeBy: sum
		sourceColumn: threshold_min
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: bf9d9109-a8c6-4253-9796-4f0af35c25ff
		summarizeBy: sum
		sourceColumn: threshold_max
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: e1664c46-0f88-4075-aeb4-de0314d8e02e
		summarizeBy: none
		sourceColumn: unit
		description: String column.

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: 79948247-97d3-4880-8c99-f9fe6408104f
		summarizeBy: sum
		sourceColumn: quality_score
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: b53fd297-8cc0-45af-aaec-1eae83932f32
		summarizeBy: none
		sourceColumn: plant_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: 311f61b4-5b90-4f80-b918-b11c94d4f24b
		summarizeBy: sum
		sourceColumn: delta_value
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: c3c4d171-faf8-4a36-8465-7d2712d583c1
		summarizeBy: sum
		sourceColumn: angle_degrees
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: 67fe8e08-4bd4-4985-807f-3bdb8013caa6
		summarizeBy: sum
		sourceColumn: power_watts
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation'
		dataType: double
		formatString: #,0.00
		lineageTag: 8025d39d-0495-406f-ad0b-e3aced9103a7
		summarizeBy: none
		sourceColumn: 'Abs Deviation'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: 07795d03-99aa-4ad7-aaff-cd80b92cb27d
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Floor Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 1682f45a-46f8-40c6-ad5c-431b9a52bf53
		summarizeBy: none
		sourceColumn: 'Floor Value'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 036d6aa8-297d-4498-8cd2-24dc5bb94ce7
		summarizeBy: none
		sourceColumn: 'Rounded Value'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: 8813a7d0-c324-467e-8045-2c5d96bfe41f
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: f8789acc-bcd9-4862-99f8-923d87e8eca7
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: f944f903-a584-4ccf-bf72-8a2367788ff6
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: fd0fed5d-3c6e-448f-9333-f135c7b36436
		summarizeBy: none
		description: Calculated column (Double).

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: a30f2313-ff02-48d3-90fc-cc7f01546c4d
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Reading Month'
		dataType: dateTime
		lineageTag: e195ba41-ba4f-4016-8b73-8855dc18c21b
		summarizeBy: none
		sourceColumn: 'Reading Month'
		description: Datetime column.

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		lineageTag: 5a0a8e9b-c6e8-4198-8d13-1e1efa1713f4
		summarizeBy: none
		description: Calculated column (DateTime).

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: 069a80df-f8d2-4d73-8767-1c9cd889488c
		summarizeBy: none
		description: Calculated column (Int64).

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: 04081389-f34e-46a1-aa46-d6343439b127
		summarizeBy: none
		description: Calculated column (Int64).

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-d5afb30c-7ae1-427f-9aa8-658b494280e2' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Sensors"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"reading_id", "reading_time", "machine_id", "sensor_type", "value", "threshold_min", "threshold_max", "unit", "quality_score", "plant_id", "delta_value", "angle_degrees", "power_watts"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    #"Added Abs Deviation" = Table.AddColumn(#"Renamed Columns", "Abs Deviation", each Number.Abs([value] - ([threshold_min] + [threshold_max]) / 2), type number),
				    #"Added Floor Value" = Table.AddColumn(#"Added Abs Deviation", "Floor Value", each Number.RoundDown([value] / 1) * 1, type number),
				    #"Added Rounded Value" = Table.AddColumn(#"Added Floor Value", "Rounded Value", each Number.Round([value], 2), type number),
				    #"Added Reading Month" = Table.AddColumn(#"Added Rounded Value", "Reading Month", each #date(Date.Year([reading_time]), Date.Month([reading_time]), 1), type datetime),
				    Result = #"Added Reading Month"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 26 columns and 13 measures: reading_id, reading_time, machine_id, sensor_type, value, threshold_min, threshold_max, unit, ... (26 columns total).

