table Sensors
	lineageTag: ebcc64e4-fb8c-4842-be0d-94238d5ad00e

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 5dbc6dd3-a345-4ff8-83be-dc119f474b6b
		annotation Copilot_Description = Migrated from Tableau: MEDIAN([value]) | DAX: MEDIAN('Sensors'[value])

	measure 'P95 Value' = PERCENTILE.INC('Sensors'[value], 0.95)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 237584cd-8934-4a79-9823-988230bb86d4
		annotation Copilot_Description = Migrated from Tableau: PERCENTILE([value], 0.95) | DAX: PERCENTILE.INC('Sensors'[value], 0.95)

	measure 'Value Variance' = VAR.S('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 59d1057a-5e3b-42a8-a26b-3eb8b1315bc9
		annotation Copilot_Description = Migrated from Tableau: VAR([value]) | DAX: VAR.S('Sensors'[value])

	measure 'Value Variance Pop' = VAR.P('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: fab54a82-edd7-4932-82e3-8aaa8f1ddee2
		annotation Copilot_Description = Migrated from Tableau: VARP([value]) | DAX: VAR.P('Sensors'[value])

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2366790f-b37c-4400-a2f8-9f1253f50489
		annotation Copilot_Description = Migrated from Tableau: {INCLUDE [sensor_type], [machine_id] : AVG([value])} | DAX: CALCULATE(AVERAGE('Sensors'[value]))

	measure 'Running Avg Value' = CALCULATE(AVERAGE('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_AVG: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 57de0a1f-d86f-4c19-95aa-87e340824e6f
		annotation Copilot_Description = Migrated from Tableau: RUNNING_AVG(AVG([value])) | DAX: CALCULATE(AVERAGE('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_AVG: converted to cumulative — v...

	measure 'Running Count' = CALCULATE(COUNT('Sensors'[reading_id]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_COUNT: converted to cumulative — verify window scope */
		displayFolder: Measures
		lineageTag: ffb1e0da-cbbd-4e64-8d52-0b3cb6e77f0e
		annotation Copilot_Description = Migrated from Tableau: RUNNING_COUNT(COUNT([reading_id])) | DAX: CALCULATE(COUNT('Sensors'[reading_id]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_COUNT: converted to cumulativ...

	measure 'Running Max Value' = CALCULATE(MAX('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MAX: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3f9e716b-338b-4d05-ae9e-7615f895132d
		annotation Copilot_Description = Migrated from Tableau: RUNNING_MAX(MAX([value])) | DAX: CALCULATE(MAX('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MAX: converted to cumulative — verif...

	measure 'Running Min Value' = CALCULATE(MIN('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MIN: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0311ba5d-6f8a-40b3-995b-2687bd1a2c08
		annotation Copilot_Description = Migrated from Tableau: RUNNING_MIN(MIN([value])) | DAX: CALCULATE(MIN('Sensors'[value]), FILTER(ALLSELECTED('Sensors'), TRUE())) /* RUNNING_MIN: converted to cumulative — verif...

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: 5cf12be8-f3c2-47e4-8fd6-32febd46fa12
		annotation Copilot_Description = Migrated from Tableau: RANK_DENSE(SUM([value])) | DAX: RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		lineageTag: e260b594-ab4f-4ec5-9f43-64058df043f5
		annotation Copilot_Description = Migrated from Tableau: RANK_UNIQUE(AVG([value])) | DAX: RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ca9b18a0-f369-4c7e-b817-a690420a626d
		annotation Copilot_Description = Migrated from Tableau: WINDOW_SUM(SUM([value])) | DAX: CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))

	measure 'Time Granularity' = "Hour"
		lineageTag: 207ac075-8a61-4f76-8845-fc919c97214a
		annotation Copilot_Description = DAX: "Hour"

	column reading_id
		dataType: int64
		lineageTag: ab062c3b-053c-4ed8-b19f-320db8da1de3
		summarizeBy: sum
		sourceColumn: reading_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 6b376ab0-f1ee-4570-af6f-c556f6897c2a
		summarizeBy: none
		sourceColumn: reading_time
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 79bdd3d8-e300-4cdf-ae36-7fafe8c16afb
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: 74618cf5-8f3b-4bb9-8127-7f12879a3ff5
		summarizeBy: none
		sourceColumn: sensor_type

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 066fb1cf-1a46-4488-b5f2-c105e7e41a25
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: 79a0bbf6-ee48-4e60-ad65-9c42014c1942
		summarizeBy: sum
		sourceColumn: threshold_min

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: de2e05a8-a7ff-444e-bf6c-59f14ffa0a9a
		summarizeBy: sum
		sourceColumn: threshold_max

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 6b19f88d-7c26-4ecf-8bd4-70133fea68c8
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: efdac12b-86af-44f3-8ddb-d7c526f0c8fe
		summarizeBy: sum
		sourceColumn: quality_score

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: dd0b316e-5404-4ba0-aa56-2dc62e9e274e
		summarizeBy: none
		sourceColumn: plant_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: 0e87e375-693d-4ff4-9750-c1c0efcee673
		summarizeBy: sum
		sourceColumn: delta_value

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: 538fd924-c632-49e8-a5a2-6fddc03acd80
		summarizeBy: sum
		sourceColumn: angle_degrees

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: 4d1647a4-671b-4c01-8dca-029d289c5732
		summarizeBy: sum
		sourceColumn: power_watts

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation'
		dataType: double
		formatString: #,0.00
		lineageTag: 27f2cee3-9ca0-437c-bcfa-5d167401ef3f
		summarizeBy: none
		sourceColumn: 'Abs Deviation'

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: 1dbbcfb7-0839-4517-865b-b82a7767dbde
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Floor Value'
		dataType: double
		formatString: #,0.00
		lineageTag: fdda2b45-70d1-4335-87b2-095017131736
		summarizeBy: none
		sourceColumn: 'Floor Value'

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 187c9102-5bef-4184-8117-4f05b99b007f
		summarizeBy: none
		sourceColumn: 'Rounded Value'

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: 8bd85e95-6a5f-43e1-84d2-3a8683605512
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: 8d2c9ff7-e63e-458b-93a8-d6b904ed3393
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: b0ece3d6-42d5-4c13-bece-849490fb54c9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 559f4742-7666-49ce-be1f-f566fdfe14fd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: 9089a0ea-6af0-4286-aa5b-ad9734d23ae8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Month'
		dataType: dateTime
		lineageTag: 9df663e5-ab13-4ed3-8675-11a10db6bbef
		summarizeBy: none
		sourceColumn: 'Reading Month'

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		lineageTag: 6054b538-ac9a-44b2-b6f3-ad3850d35005
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: 8cf6c414-a93f-4496-9f75-62a1b2c591bf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: ec08cb94-c0b5-4e48-94d3-09b3ece49a47
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-6298b247-7646-4329-b500-4a1acd5cae5b' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Sensors"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"reading_id", "reading_time", "machine_id", "sensor_type", "value", "threshold_min", "threshold_max", "unit", "quality_score", "plant_id", "delta_value", "angle_degrees", "power_watts"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    #"Added Abs Deviation" = Table.AddColumn(#"Renamed Columns", "Abs Deviation", each Number.Abs([value] - ([threshold_min] + [threshold_max]) / 2), type number),
				    #"Added Floor Value" = Table.AddColumn(#"Added Abs Deviation", "Floor Value", each Number.RoundDown([value] / 1) * 1, type number),
				    #"Added Rounded Value" = Table.AddColumn(#"Added Floor Value", "Rounded Value", each Number.Round([value], 2), type number),
				    #"Added Reading Month" = Table.AddColumn(#"Added Rounded Value", "Reading Month", each #date(Date.Year([reading_time]), Date.Month([reading_time]), 1), type datetime),
				    Result = #"Added Reading Month"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 26 columns and 13 measures: reading_id, reading_time, machine_id, sensor_type, value, threshold_min, threshold_max, unit, ... (26 columns total).

