table Calendar
	lineageTag: 5f43f808-7ca0-49a6-b0b2-1cdfa783769b

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: dd4a70b8-b09a-45b5-90e6-4fcabf96df2d

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7a73fdf4-dc1d-49df-8800-603dc944b4f1

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 6862f59d-dd65-4908-8a39-151ac95db111

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2d971d22-1ab1-4db2-b134-61cf982e52a1
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f152c740-4509-4e51-9111-bfdb41e86508
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ef8308e3-ee5b-41cb-b139-55a9a59b7dba
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2c883757-0b90-43fa-988e-636494993100
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 47d01c4b-b135-4b36-aa92-0d50d49f6da0
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a4829cac-5ebf-4c4a-bd3b-33c4a7f25eff
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a9ffdb05-7e58-446f-bafb-f6965bb42b64
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: acf14ee5-e9b0-48cb-a965-1b314984f658
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 08900ce1-76e9-49ca-90eb-e91492e670fd

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1ce6910c-3623-4e00-9b2a-198ba3e264e0

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 68db58de-9fe1-4c0c-88bd-0071bcf0dbbd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6dd8ac89-3735-4a31-b738-59d2a79a7449

		level Day
			ordinal: 3
			column: Day
			lineageTag: aefda472-2f0a-4738-914d-e4a1070363a2


	partition 'Calendar-83585bda-9f3f-456e-adbf-1533eb6d4d53' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

