table Leads
	lineageTag: c8e0583f-faec-4afb-b6ab-47c32c9adee1

	column lead_id
		dataType: int64
		lineageTag: c895b598-8e23-44fa-8a3c-d65dae16da81
		summarizeBy: sum
		sourceColumn: lead_id

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		lineageTag: 46633f72-7033-44ea-887e-77690592c7d7
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column lead_name
		dataType: string
		lineageTag: f2e279ab-8c4b-47cc-a84c-418dee057c74
		summarizeBy: none
		sourceColumn: lead_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 23586bab-1788-4735-9e11-520684b7652a
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: c77f73a2-3be9-44e5-9097-a02275ea6bb2
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: a66ea97e-b521-4e0b-839f-372ee8ab0e36
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: fb212b03-6014-48e7-85e7-8af79d3b0138
		summarizeBy: none
		sourceColumn: job_title

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 68d4874c-e6b8-4873-b72e-23731f8f9fee
		summarizeBy: none
		sourceColumn: created_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column deal_value
		dataType: double
		formatString: #,0.00
		lineageTag: e918424a-f3e9-4b02-b877-96b17916993f
		summarizeBy: sum
		sourceColumn: deal_value

		annotation SummarizationSetBy = Automatic

	column lead_source
		dataType: string
		lineageTag: 4cea73d0-e169-449b-88cf-2133efcc73b2
		summarizeBy: none
		sourceColumn: lead_source

		annotation SummarizationSetBy = Automatic

	column lead_status
		dataType: string
		lineageTag: 81aa3b4c-8779-4115-8714-d8f3bf0543fa
		summarizeBy: none
		sourceColumn: lead_status

		annotation SummarizationSetBy = Automatic

	column engagement_score
		dataType: double
		formatString: #,0.00
		lineageTag: 8caf5552-b805-4825-9149-23410bc74bb8
		summarizeBy: sum
		sourceColumn: engagement_score

		annotation SummarizationSetBy = Automatic

	partition 'Leads-d234eb89-9284-4966-9062-8e9395d26ef3' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				    #"Leads Table" = Source{[Schema="marketing_db", Item="Leads"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Leads Table", {{"lead_id", "Lead ID"}, {"campaign_id", "Campaign ID"}, {"lead_name", "Lead Name"}, {"email", "Email"}, {"phone", "Phone"}, {"company", "Company"}, {"job_title", "Job Title"}, {"created_date", "Created Date"}, {"deal_value", "Deal Value"}, {"lead_source", "Lead Source"}, {"lead_status", "Lead Status"}, {"engagement_score", "Engagement Score"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

