table 'Min Budget'
	lineageTag: e42c924e-b302-4f6c-abbe-1f0756103b28

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 3894713f-7a6a-41df-95e2-ecbff596b8b5

	column Value
		dataType: double
		lineageTag: b8d454de-0e8f-43cd-8fdf-337901c8d5ef
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-ae045d49-e4df-4885-a736-db0384f1687f' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

