table Calendar
	lineageTag: 723b227c-c4a9-47e3-8853-eb576bd92ea7

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 57dddde2-a02f-44ab-8afb-05845e88aca0

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8b86dc83-7689-40c0-8b9f-c1d39dd7160f

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: e2a18e93-c529-4fd8-a5da-42510d5c435e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1ad1fda9-2c5d-4f5a-b641-6b6534f5d509
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e329969c-fa11-4412-889b-92da70b2341a
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1c511867-16e3-4e64-a456-138645b0fedb
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: fa0236fd-5dc9-4a65-95d6-5a7d3d8a1fd6
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 9b9584b0-923d-4555-8a6e-c0337cefa72d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 929d0537-b9db-4828-8984-800b59428b75
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 56662f02-c3aa-4fb5-82c8-9a921147e6f0
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 62b83b61-0c5e-4db3-9331-e16ff865ee17
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 2c9ac6cc-9a2c-4a21-b372-a455bf8f4b6e

		level Year
			ordinal: 0
			column: Year
			lineageTag: d82140ee-0992-4ff1-b512-406cd4ebd98f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3856a1dc-351a-402d-9bf7-86c0f3902c02

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 338845b3-e649-4530-a960-a74f2065d422

		level Day
			ordinal: 3
			column: Day
			lineageTag: fc830154-7ae5-471f-a045-e73678d52176


	partition 'Calendar-4d16d213-dddd-41cc-9719-a191b2fa4f10' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

