table Calendar
	lineageTag: d33cec87-9672-43ea-9d3f-62db3b50f3c2

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 84a6f442-3ac3-4a04-9e59-5678e2d94ba0

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9e26f7a3-6866-41fb-bae4-faa502fe91c4

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0135fb50-ac16-47cf-bd9c-9beb13e925a2

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 263e3f03-91cb-415f-a21e-f32d2b9cbf72
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c48ecc49-4c68-4675-926d-5c0335e373e1
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b9be7db2-a292-4688-92f2-823eca01cd1e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4d19f37c-aa29-4115-abfd-65840b07dfb0
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: af483b91-0362-45bd-81cf-498089cb56e5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 30bb9acb-faaa-483d-a5ad-a4a8ac282f7b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: cd32b3ad-8404-491d-af05-31b6bee4195e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7913cf60-5e92-45c7-87de-5e9963f2ecde
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 80845a88-f19d-4ee0-aa68-d59a849d33de

		level Year
			ordinal: 0
			column: Year
			lineageTag: d5874baf-4dd0-4340-a01b-bdef9ad12a55

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c754a2d2-ce60-4c75-9786-d9abedd1b614

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0fef0e34-4bca-4d4e-bf28-edfaee42db33

		level Day
			ordinal: 3
			column: Day
			lineageTag: 28c0ba1b-b653-477b-87f6-54ed34953af5


	partition 'Calendar-f15d3c8b-9806-45bc-bdc9-c3c5ddf6c397' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

