table Calendar
	lineageTag: b4f16186-57bb-4204-95dc-9d891c4c2a60

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d3c12751-f70b-4d88-8b5e-4adfd5dc697e

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 04dfc830-4b02-4684-b4cd-d1bf603d87e5

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 448aa942-a35f-4663-afd5-1776a43e3e5f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d367dee0-d5ca-4739-9c74-19a3e2dd7138
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 83828c87-706d-4e48-bf02-ac8cc26b76b0
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7297ec85-94d9-4882-9aee-a1b230cfe47d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 9d49f445-dbb8-4be9-baf8-80b6b88e5201
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f34c6cee-1770-4b8e-b816-71c1612d4789
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 21079443-7f2e-4ab5-9d14-2c61402de3a3
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4615fe8f-2362-485d-9c45-b4f6f3cfe1f0
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e28f520b-a844-499f-96cf-66cb26f90f8c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: cc98cd1c-8d82-46b1-bd80-444514d9b0f3

		level Year
			ordinal: 0
			column: Year
			lineageTag: 72a5ab85-9c55-4076-95bd-b8cc9af77eb8

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: aeedabf2-32da-41ca-9dd7-2b383d295f2d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 93f24f33-d40c-4875-9fa9-28c6562143ba

		level Day
			ordinal: 3
			column: Day
			lineageTag: e3e9e81b-7825-4bb6-b365-c55ed83d4226


	partition 'Calendar-cf88c861-515c-41c3-8a04-0cf918464dd4' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

