table Calendar
	lineageTag: 40f41650-0322-45ef-81dc-40bc5577697e

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8a2fe09c-f2a9-48f3-a9e3-95e0da966e44

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 39dae396-fa03-48a1-a4f3-cfe3198eec73

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 17100150-5e1e-4928-8383-dee613aafd6f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1ed7e9e6-c741-4493-a653-b595dff7f22f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1c0c8331-9ec3-4462-8551-3c52d4903263
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 069da363-e057-4b2e-ab82-51fd239e0934
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 37bf13a0-9d19-4f5b-9f0a-cffd92a75870
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c85f4678-6c04-4c80-aae4-9866ad51a13c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f60383ee-07d0-4bbf-84a6-2a0629834ea4
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 268e8928-6b87-449b-be75-de437a3205bd
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ddf5469a-a6c3-43d6-8118-e6d538ce517c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7e5bddd0-c0fb-4d35-87cd-3d42be6108e7

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1f292541-a453-4dd6-8532-c38a500f6cb8

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 91281dee-73a7-4822-a176-10406526660f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f4fddcf8-6616-46f1-bbba-7d678117e447

		level Day
			ordinal: 3
			column: Day
			lineageTag: 921cb05e-04c3-433b-a333-56887d252f2a


	partition 'Calendar-eb8ed1bd-6746-4c8a-8b03-9ddca04fcfeb' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

