table Calendar
	lineageTag: 58c7cec6-aef9-492f-968a-2cf6095e86a8

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 4127fd1e-3197-412a-9210-a9a3e747bdf3

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 412861c7-c230-4a29-b1a4-613d39c1c18f

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 6e2967ca-4ec4-4a9d-86df-adc12eb16862

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9e600928-4a87-495a-8bc7-fde7519bd8db
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 20b2538f-86a9-41a1-b1ab-965da1208b76
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e6e8bb06-d060-47ce-a17d-a73897653655
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 56db3c06-3552-4e49-b755-9d2261206173
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 928ed74e-e538-41d1-9178-e7cfe78a707a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 63ac7fd2-a546-4a3a-97fb-2bacd43eed18
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4bcb26c6-15dd-4cfd-8143-526a2fac9e35
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 18e0b3ca-4d48-47db-982e-dc76b80e928b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 366da0ba-9881-443c-929e-1952bacd0a10

		level Year
			ordinal: 0
			column: Year
			lineageTag: 222b1e85-fc33-4106-93e7-7dd0de30c232

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 9021dfa9-f159-42b9-aef6-f040bd9237c5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1853b565-a86d-41f9-9716-46635af43c21

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9abab8b3-c34c-4bc3-89c1-cf25146c59a2


	partition 'Calendar-27cdaf1f-70a5-44fd-aa75-7842596b44fb' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

