table Returns
	lineageTag: cb981fc3-0d6d-4559-9745-6f6fac8ca558

	column Returned
		dataType: string
		lineageTag: 8372c7b0-394d-40a8-98e7-fa2474585705
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: a07f8e3f-6d5f-4c90-83f3-88855b97a671
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Returns-b68f1c9e-032e-4442-937e-226a2f2877c5' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				    #"Returns Sheet" = Source{[Item="Returns",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Returns Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

