table Calendar
	lineageTag: cc58d984-1c15-4cab-9f47-b00bc89261c5

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c8bc1279-9c21-433f-8874-547c44844c61

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: dd5245d0-91d5-4549-b968-3b06073b1ef7

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: efffeb07-3378-489c-9ab5-7a03194d0bc4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c2aded2e-cbe8-4079-bdf6-05e186156e83
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0663af20-4a54-431a-ae24-8ac6e5acfca1
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c6b51c8f-f01f-4b3d-b5f4-8de6bb170c6b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 45485e12-cb17-4e99-ad9a-282c79a0fcfe
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ec743ece-c66c-4c84-9db4-defa306e5281
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b5dd3aa3-a6f0-4916-8437-4379465f06a8
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 92bc956d-f4b1-47fc-802d-6ef62712d871
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 0bd46b26-5cd5-4190-89fc-2b2ca1973b7c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 88536977-29b8-4046-a2cb-1786678a5c48

		level Year
			ordinal: 0
			column: Year
			lineageTag: a016cc99-cfb4-47cb-9943-fc2042db4b18

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: edf5f447-c5c8-43ed-ae0d-b3f1dbbcbfae

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7ff78914-b703-40e8-820f-c7928720fab1

		level Day
			ordinal: 3
			column: Day
			lineageTag: f4340dad-dad4-46d9-8642-884ce2f155ab


	partition 'Calendar-79112798-515a-4a8d-8fe7-156c539d7304' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

