table Extract
	lineageTag: 1ba0fa07-5d67-48c7-a4db-83a069317033

	measure 'GDP % of Total' = AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c5f51085-ef9d-4047-9e1d-c6c29514608d

	measure 'GDP per capita (weighted)' = SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b2b945d7-8aea-4947-a127-549f113cb673

	measure 'Rate spread (difference)' = AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 293a926c-968a-4c75-a767-871650d71dc8

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 974ca855-f76e-4d72-81bf-c176633e2a90

	column 'Country / Region'
		dataType: string
		lineageTag: 07a46432-fc3d-4b66-8cc3-6f7959dfe9a4
		summarizeBy: none
		sourceColumn: 'Country / Region'
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7905bdfd-2729-4995-812c-83c1e7258393
		summarizeBy: none
		sourceColumn: Date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'F: Deposit interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: 343273f4-cdf7-41c1-84d6-05a50ed60abd
		summarizeBy: sum
		sourceColumn: 'F: Deposit interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.00B;("$"#,#0,,.00B)
		lineageTag: 03824c5f-bd39-44f7-b0a7-31a7709c4d63
		summarizeBy: sum
		sourceColumn: 'F: GDP (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP per capita (curr $)'
		dataType: double
		formatString: c"$"#,#0,.0K;("$"#,#0,.0K)
		lineageTag: c5978d52-270b-44d7-8dc1-21d1420bcdff
		summarizeBy: sum
		sourceColumn: 'F: GDP per capita (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: Lending interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: 27f49e75-1c82-478e-a5a3-abe86ff26332
		summarizeBy: sum
		sourceColumn: 'F: Lending interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp (% GDP)'
		dataType: double
		formatString: #,0.00
		lineageTag: 24991596-8cb7-4fe1-ae23-a685f5a289a7
		summarizeBy: sum
		sourceColumn: 'H: Health exp (% GDP)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp/cap (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.0B;("$"#,#0,,.0B)
		lineageTag: 036a35ea-9721-46f7-9e81-6885c75657b1
		summarizeBy: sum
		sourceColumn: 'H: Health exp/cap (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'H: Life exp (years)'
		dataType: double
		formatString: n#,0;-#,0
		lineageTag: cb88d846-a0a6-4f36-8355-27c3e5f11dc4
		summarizeBy: sum
		sourceColumn: 'H: Life exp (years)'

		annotation SummarizationSetBy = Automatic

	column 'P: Population (count)'
		dataType: double
		formatString: #,0.00
		lineageTag: 07a62f32-858e-449a-b6a0-b07a95de4bd3
		summarizeBy: sum
		sourceColumn: 'P: Population (count)'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: fcaefa97-9c16-4422-a79e-eb2751f3f980
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Subregion
		dataType: string
		lineageTag: 1254b89b-e555-4419-aa85-d63bfbcb339c
		summarizeBy: none
		sourceColumn: Subregion
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Action (Country Name)' = 'Extract'[Country / Region]
		dataType: string
		lineageTag: 7ce5e6c7-6091-4e58-9364-6f719c5f55fb
		summarizeBy: none
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Date (year))' = 'Extract'[Date]
		dataType: string
		lineageTag: 1fcccc87-e4f7-4373-9104-23db66f23bdd
		summarizeBy: none
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)' = 'Extract'[Region]
		dataType: string
		lineageTag: 1b749dff-c1c4-477b-8534-1b31945042a0
		summarizeBy: none
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Date (year)))' = 'Extract'[yr:Date:ok]
		dataType: string
		lineageTag: 3a67ce83-66ff-4733-af83-68d11c50e001
		summarizeBy: none
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Exclusions (Country Name,YEAR(Date (year)))' = 'Extract'[Country / Region] & " | " & 'Extract'[tyr:Date:qk]
		dataType: string
		lineageTag: b3faa1b8-da5a-45ef-b037-d2dc211d0cec
		summarizeBy: none
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Extract-48ab89c1-b41b-4b76-a381-2ad64e8d5fe6' = m
		mode: import
		source =
				let
				    // TODO: Configure the source for DATAENGINE
				    // Connection type not automatically supported
				    Source = #table(
				        {"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "P: Population (count)", "Region", "Subregion"},
				        {
				            {"Sample 1", 2, 3, 4, 5, 6, 7, 8, 9, 10, "Sample 11", "Sample 12"},
				            {"Sample 2", 3, 4, 5, 6, 7, 8, 9, 10, 11, "Sample 12", "Sample 13"}
				        }
				    ),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date (year)"}, {"F: Deposit interest rate (%)", "Deposit interest rate (%)"}, {"F: GDP (curr $)", "GDP (curr $)"}, {"F: GDP per capita (curr $)", "GDP per capita (curr $)"}, {"F: Lending interest rate (%)", "Lending interest rate (%)"}, {"H: Health exp (% GDP)", "Health exp (% GDP)"}, {"H: Health exp/cap (curr $)", "Health exp/cap (curr $)"}, {"H: Life exp (years)", "Life exp (years)"}, {"P: Population (count)", "Population (count)"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

