table xy
	lineageTag: dbb5cfe7-b663-4a8c-a785-f44684b92857

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 24b3645c-c8c2-421c-97e6-aa87974c947f

	column a
		dataType: string
		lineageTag: 5afa3570-4121-4a71-a0d3-ce0d69126b1b
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 8014fb73-3135-4530-8113-64f16da93007
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: e6dd0ff3-c6f3-4484-a3cc-94c17acbc9f4
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-a8d4d4f7-9bd0-46c2-92ca-8dd137622e91' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

