table Calendar
	lineageTag: a917e9fb-92c0-4d62-9ad1-98a956d73f2c

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 94460d0b-b76a-495c-844d-9fbdc8a88435

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 62d75f2f-9240-428a-b096-e4a6e30db2f3

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 2dc899f6-cc62-440f-862e-9082ee06ca4e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 86b9a361-6a01-4a7c-ad9c-dd7d62a7d04e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 7ac44cf8-696c-431d-a92f-a593d4105f08
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 9ad3d936-0aec-4015-a1f4-624fe064d78c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b9901536-24d6-4d06-922b-8a81d6cd1e02
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f74cc603-a9db-4a5f-8e34-27424266d45c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 090d12ff-9a0c-47da-bc87-b15e44a4425a
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f7196468-6709-424c-9b06-3233554e88c7
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2f760e4a-0f60-4688-b945-66031600f39f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1098cf46-86a1-4499-ac49-35116162e40b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6f4d8ce7-dcc2-4ca9-b138-1795f0d74cdd

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 4ae33b71-0911-45b1-9e63-6420fdfef4dd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7a767bbb-0601-4353-b0dc-27598ecafd2f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 597ea3c8-abf7-4941-b3bf-53970215e2d6


	partition 'Calendar-cd8662c9-79b5-43c8-9410-2d22cd850ca2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

