table Calendar
	lineageTag: d3d3473e-94f3-427b-888a-b49172c64ac6

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ad5f7d01-d14d-44a8-8c5d-ecc2d2d45f18

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b1ca1f5c-e7a1-4237-b7bb-ce6e8f677cb0

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: f10c78e9-6676-4ac9-939a-b038e014ac80

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1d351375-7e5c-4480-b85f-a3f6da4c7a45
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 8e0f71cc-beb9-4edf-947c-e602a233572f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 14dfe61d-2f94-4a05-8c7c-62429e7ebe7f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 8453e7a1-62e5-4b08-9d99-1af012fca30b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a405abc0-1334-45a3-8966-70892adef3db
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 14f348a0-1458-4eaf-b11b-2b5b0d4273aa
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 124ca8b2-46f6-4f0e-9db5-b601e2b6f2d5
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 84c58165-e637-4e3c-9f6f-6d368ba26b23
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8714f8a1-3caf-4353-8ebd-e0876c238d75

		level Year
			ordinal: 0
			column: Year
			lineageTag: 52e3289e-3f2b-4de7-94a2-8faf62ddc4c3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 32b2c5e1-0596-4b9e-9bc9-891928df40ce

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 37fe9d6b-b062-41bb-a48e-d58591d5e551

		level Day
			ordinal: 3
			column: Day
			lineageTag: d1af9ed1-a57d-4428-97de-bde920816776


	partition 'Calendar-cd8e5b5f-a5b0-47ae-999b-4bffd9ea144c' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

