table Calendar
	lineageTag: 3fbfb823-4318-464c-ba05-1bef150d0706

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 4f333c86-6eb5-42bd-b5b8-793aaa28ee98

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ec7b4be0-e088-4df7-a091-7092dcedc1e4

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: c6a0073b-a12a-412b-8e92-28e63a58d5f2

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4b58af0b-a972-48ed-839f-b7fbb7376b4a
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a60a3065-2e28-4527-a054-134471c2e35f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 96f06a34-ae53-4830-850b-623e31e6c1b2
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f6074ea7-b705-4d5f-b61e-ad01bedc6ecd
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 29ed7a82-dbff-4749-b91a-77c05bb6d669
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 429f97cd-fbb1-460f-9586-47ef717129b7
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 00462455-06a5-4c78-b5c4-78ae7a8f9504
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 17d136dd-b65c-417d-9be6-6dd52c983d24
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 11e24186-e01e-4766-8deb-0b99a6f1c1d4

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4006a608-94ee-490f-b08c-9981c640ac58

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 75fe7844-417a-40cd-b4a4-b260953fbee2

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a4257b7c-dc4f-4d9a-8d71-1fbb85ee30f2

		level Day
			ordinal: 3
			column: Day
			lineageTag: 736278a2-fc0b-4dc3-8441-14457ac4bcd7


	partition 'Calendar-9871fa5f-7ca1-4283-9f10-7c942416fe46' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

