table Calendar
	lineageTag: 6de95dee-9f72-4f82-af41-3a317001bba3

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9c04dfba-f51d-49af-962a-0483faa0ad57

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 217236a9-3d0c-4b3d-ba42-8a16cfec6c78

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0b5285cb-45ab-4cbd-9581-55f3f66e6240

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 69f3f2ca-3f7b-41ce-831b-8a2c274c92a1
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 251cf062-20a3-4755-a220-52733a4f7509
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 68b9f974-4269-4518-aa61-d209c9f09b3f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f2fd83d8-79bd-4ac0-b238-64b61986c949
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 07edecdf-c490-45bf-9efb-9a5ee3e81ca5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 54f5a7ff-d265-4f41-b8ac-fbec0908cc9e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4b6c74ae-36d3-4375-b7e9-575478d569fa
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 8e603bae-f786-4796-8bf1-6a384e24755e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 32f3ae0d-f8f5-416b-bbc5-873faf650a52

		level Year
			ordinal: 0
			column: Year
			lineageTag: e14ff8d5-83b5-4bb5-839f-9e62817429be

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 257e4ae8-1c28-4188-a991-48d4f0d22da9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 50b8d84d-0e65-4d3c-8bfa-a5fbd217fcec

		level Day
			ordinal: 3
			column: Day
			lineageTag: 95365dc1-138b-4a49-8da7-5de2a18a88c8


	partition 'Calendar-2b017619-0d28-474d-8c44-cdd455c78335' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

