table Extract
	lineageTag: 0a883809-3250-4de6-ac58-a902d510c732

	measure 'GDP % of Total' = AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e2f1850e-068f-43be-88ef-1f8d33a277f1

	measure 'GDP per capita (weighted)' = SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7683c726-0422-4f76-9029-9b08a991bb71

	measure 'Rate spread (difference)' = AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 95285dee-52cc-4e1d-8a12-e09c7433be5b

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: fdcbed08-fc0d-4dda-bb0a-0f0a62ca93a2

	column 'Country / Region'
		dataType: string
		lineageTag: 97d04bd6-0039-4936-bad6-80d53c2b86c5
		summarizeBy: none
		sourceColumn: 'Country / Region'
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 708dc2f6-7ffe-4d7c-b58a-03f2ee3b3afc
		summarizeBy: none
		sourceColumn: Date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'F: Deposit interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: d84e87b1-5221-48e6-9e58-aa516b42dd53
		summarizeBy: sum
		sourceColumn: 'F: Deposit interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.00B;("$"#,#0,,.00B)
		lineageTag: 80f53f7a-5533-4a65-88af-60218b73f64b
		summarizeBy: sum
		sourceColumn: 'F: GDP (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP per capita (curr $)'
		dataType: double
		formatString: c"$"#,#0,.0K;("$"#,#0,.0K)
		lineageTag: 7eac5c9c-3d2f-484d-86d6-5b45528d7c11
		summarizeBy: sum
		sourceColumn: 'F: GDP per capita (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: Lending interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: 083263d1-4b2d-4ea3-9d89-4d0fbe83195f
		summarizeBy: sum
		sourceColumn: 'F: Lending interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp (% GDP)'
		dataType: double
		formatString: #,0.00
		lineageTag: 45b58a48-5202-4272-bf32-cab7f5d9ad9f
		summarizeBy: sum
		sourceColumn: 'H: Health exp (% GDP)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp/cap (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.0B;("$"#,#0,,.0B)
		lineageTag: 4f7619b8-5c58-472f-9b13-73e1e54952d3
		summarizeBy: sum
		sourceColumn: 'H: Health exp/cap (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'H: Life exp (years)'
		dataType: double
		formatString: n#,0;-#,0
		lineageTag: 0811b8c9-a58a-4674-a258-8d1484fed52f
		summarizeBy: sum
		sourceColumn: 'H: Life exp (years)'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 148cac1d-42da-4a51-bb04-c1b50cf556f3
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'P: Population (count)'
		dataType: double
		formatString: #,0.00
		lineageTag: d2051594-ac44-41a2-901e-8582872f44f1
		summarizeBy: sum
		sourceColumn: 'P: Population (count)'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 13a1a104-8330-4191-84df-a0ef70564d35
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Subregion
		dataType: string
		lineageTag: 23eaffd4-2e81-403f-ac8f-c4d0c959d12d
		summarizeBy: none
		sourceColumn: Subregion
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Action (Country Name)'
		dataType: string
		lineageTag: c88a45d1-b711-4816-a1bf-ab380e872f02
		summarizeBy: none
		sourceColumn: 'Action (Country Name)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Date (year))'
		dataType: string
		lineageTag: 8def8254-f5d0-4478-b4d0-af3c924dfdca
		summarizeBy: none
		sourceColumn: 'Action (Date (year))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: 1f99c5f0-b147-4b51-b0c2-d0d78a7b93ab
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Date (year)))'
		dataType: string
		lineageTag: 90a4ce7c-c969-4589-9aaf-0f34d62507b4
		summarizeBy: none
		sourceColumn: 'Action (YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Exclusions (Country Name,YEAR(Date (year)))'
		dataType: string
		lineageTag: 05898804-187e-48ab-a0cb-c28ef00e47c5
		summarizeBy: none
		sourceColumn: 'Exclusions (Country Name,YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Extract-a4f33954-3f07-4ef2-8cce-587e7e6e5357' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"},
				            {
				                {"Sample 1", 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, "Sample 12", "Sample 13"},
				                {"Sample 2", 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "Sample 13", "Sample 14"}
				            }
				        )
				    otherwise
				        #table({"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"}, {})  // Empty table on error,
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date (year)"}, {"F: Deposit interest rate (%)", "Deposit interest rate (%)"}, {"F: GDP (curr $)", "GDP (curr $)"}, {"F: GDP per capita (curr $)", "GDP per capita (curr $)"}, {"F: Lending interest rate (%)", "Lending interest rate (%)"}, {"H: Health exp (% GDP)", "Health exp (% GDP)"}, {"H: Health exp/cap (curr $)", "Health exp/cap (curr $)"}, {"H: Life exp (years)", "Life exp (years)"}, {"P: Population (count)", "Population (count)"}}),
				    #"Added Action (Country Name)" = Table.AddColumn(#"Renamed Columns", "Action (Country Name)", each [Country / Region], type text),
				    #"Added Action (Date (year))" = Table.AddColumn(#"Added Action (Country Name)", "Action (Date (year))", each [Date], type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Action (Date (year))", "Action (Region)", each [Region], type text),
				    #"Added Action (YEAR(Date (year)))" = Table.AddColumn(#"Added Action (Region)", "Action (YEAR(Date (year)))", each [Date], type text),
				    #"Added Exclusions (Country Name,YEAR(Date (year)))" = Table.AddColumn(#"Added Action (YEAR(Date (year)))", "Exclusions (Country Name,YEAR(Date (year)))", each [Country / Region] & " | " & [Date], type text),
				    Result = #"Added Exclusions (Country Name,YEAR(Date (year)))"
				in
				    Result

	annotation PBI_ResultType = Table

