table 'Target Margin'
	lineageTag: 441250f9-eea8-441f-94f9-c0b7c11b2f0b

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: bdd8cf7b-646e-46f6-8de6-f8209222e757
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin'[Value], 0.2)

	column Value
		dataType: double
		lineageTag: 2e759704-6956-48b7-84db-2c307095b3f7
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-824621ad-c430-4723-a502-bc72a59e4cb4' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

