table Calendar
	lineageTag: 80572e16-1276-4f2d-9183-7a952d7a4c89

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 203a200f-2297-4d20-93da-b65a0c17737a

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1010181e-acaf-4873-aa68-0b1729b4fe44

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: a28c760c-812e-40fb-b07f-2c9ac3a4bc10

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 09cc3301-b756-484c-bfdd-38a1f418cf5b
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: fa3a3774-671d-40ef-b202-e6eb548805f6
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8cb557e2-5187-4928-9c07-430d4aacef25
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e05584c9-953f-4e4c-a6a1-dea84ae8c721
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d65ac711-e345-4837-a3c5-3fdf7bf32a29
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 64a592a8-6424-4414-b9a0-0db297e2da4f
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f8b2b8c5-bce3-47f3-b573-adbdf535f60a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 4f50bf42-25ab-47cc-b716-ab834f76cac1
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b05e12c9-5db1-44c5-8a61-75ff9dd7a9b3

		level Year
			ordinal: 0
			column: Year
			lineageTag: ea1d111e-8cf0-4ef0-99a5-a897ba30053f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 0b95e85c-daca-44ae-b098-7c1214406ca3

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: df593b5c-d1e4-46ac-870a-e216fe0f681d

		level Day
			ordinal: 3
			column: Day
			lineageTag: 59a54ccb-3310-4f2e-a111-7d6c087d890c


	partition 'Calendar-02851008-a14c-4eb7-9347-f3d9d91c41f7' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

