table Calendar
	lineageTag: 13d11782-a1f3-429b-a217-03955b2eaed8

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6f011171-5fa8-490a-84b7-5290b919f09d

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1d10a9c6-580f-40f5-b17c-33f92325e0fa

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: e6fcd402-d759-469b-b523-9188b146c118

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0d8b0887-de6b-409a-8896-9a5d10931c63
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 14de9277-d851-474f-97bd-3850b55cc1db
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 68b99d40-16a7-48ac-8b9e-93996d7fbf06
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e5d8546a-4ff1-485d-ac29-1b4a12310057
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 29f2ffb1-d59e-4f94-80e2-c80beb9d5253
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a93dde5c-29d0-466d-af8f-f182a5f47613
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 0cdff842-b543-42f5-9112-1018f37210fc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 579d730c-cf97-45cc-96d5-a096e945a663
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b6f59d61-0fa0-43c9-8109-e405272ac1ca

		level Year
			ordinal: 0
			column: Year
			lineageTag: 0e964614-1312-4357-8261-a370680b19a2

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 729d0300-3cc4-462f-9048-4a272635954b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 84a06e62-8b80-4197-9fc2-4e17e715985f

		level Day
			ordinal: 3
			column: Day
			lineageTag: ae480c70-5344-4dc9-ae28-0b4d232b2679


	partition 'Calendar-bc2ee44a-0ff7-4f69-b51f-58e3b4fdb61d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

