table Calendar
	lineageTag: c1ee2d49-c09d-4256-9a19-04671830da4f

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7b06d9e7-af4f-4cf5-ad89-041d1193d107

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: bb650b23-ceab-4f6a-a455-26b9c702a81d

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 76139eb5-395a-4051-b001-005d44821b94

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 66313915-c2ac-4538-ba7e-16792b271996
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 91cc6be9-4273-4395-9f5c-516b5d12cee4
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8305d0bf-d624-4a24-8f1e-6e5f2a8c7300
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2b227ee7-3058-452a-83a0-60a8725993f6
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 189d0ee8-8b9f-4e9d-b565-efcea5d6c092
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 56211e06-777c-4463-a9f1-062123ca6318
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 46b9970f-1fcf-45f7-936e-10195fbcf1f2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 36c0a0c7-c15a-42cb-bc6b-8b4e58178d1d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b7b81846-6782-48db-98d7-3cfe85e070dd

		level Year
			ordinal: 0
			column: Year
			lineageTag: c37ababd-c18c-4d3a-9d42-f888b7a54275

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 1963e9ac-6e32-419e-9308-318483269dd9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c796f59e-7244-4773-95fa-09a685f4b0f4

		level Day
			ordinal: 3
			column: Day
			lineageTag: 70fe670b-2d90-4866-8a0d-38a1280b76c1


	partition 'Calendar-5ce58bb4-2961-4e53-9035-dd2d7fea9877' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

