table Employees
	lineageTag: d7bf66d5-3689-42a3-9dce-670a1463ec5c

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2a6528df-0eff-4f4d-ad1a-f3e526b37a62

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: f552b110-f01f-4aad-8935-ac23470dcfd4

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 42b37972-4eb0-41f8-b179-e99f6f8a0ff2

	column EmployeeID
		dataType: int64
		lineageTag: 812c58d6-04d8-4883-8e72-de705bc5c92e
		summarizeBy: sum
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 06f80500-fcb3-462f-8bfd-6566528c9a0b
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: bbd12d04-f587-4477-a6d6-abd3ff6b7502
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 8309d977-6505-4b6d-99d2-c0c0a19366e5
		summarizeBy: none
		sourceColumn: HireDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 259a2891-67ef-44f3-89b9-ed5fed4d8ce3
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 0c2d0fc6-0114-4af8-9610-73949712e366
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: e9b44cff-c2f5-41b3-a01d-175409d1fd41
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: e6667cc3-3381-432c-9cd8-83b3cc9e428a
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: b3581cab-a2df-4ce5-b210-d3fabb8cc50b
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: a2decc62-015d-4544-a96c-9c3c4c46f905
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: 4752f371-7222-473d-8a68-bf3ebdb94d4e
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category' = IF('Employees'[YearsOfService] < 2, "New", IF('Employees'[YearsOfService] < 5, "Mid", "Senior"))
		dataType: string
		lineageTag: 1bfbc677-3542-40fe-8369-f32ab6a42f97
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Employees-64f84355-eb34-4206-9eaa-f4f8e7646eaa' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("localhost", "HRDatabase"),
				    #"Employees Table" = Source{[Schema="dbo", Item="Employees"]}[Data],
				    Result = #"Employees Table"
				in
				    Result

	annotation PBI_ResultType = Table

