table Calendar
	lineageTag: 3fba8a86-cf88-4862-a021-35494cba1252

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e311e0f7-90e2-4465-ab74-48deecd0b075
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: af2ba793-8bc6-4a68-b171-fbb96e4a6133
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: df03d21c-e62a-48cd-b29c-cecc86a6656e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: bf46f9d5-4bca-45c0-bd74-b4f60ee23939
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b54831d7-296e-42bb-8064-e369e4152e2b
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d11e68d5-fdac-4bff-abab-7b3d3f0da652
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4658a93d-6bb2-4276-b5f0-3e90a04f2cd0
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 34d59a13-44cb-48ea-9ea9-e555e6a608d8
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 2a47eea3-947f-4755-9e67-ebebaac434ed

		level Year
			ordinal: 0
			column: Year
			lineageTag: a3c8ed46-ead2-4120-978f-8fbf2ede21af

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 0bebf500-bc4e-4aa8-a87e-20dde346d144

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1d1b0cf3-3cec-4189-a529-13b32ea67f0e

		level Day
			ordinal: 3
			column: Day
			lineageTag: c9efb59c-2d6a-4a16-b350-e72f1e77a327


	partition 'Calendar-5dc7de05-109f-4096-ac7b-578405ce66e2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

