table Calendar
	lineageTag: 5d8349fc-23ad-4159-9d95-d9ba59d2497d

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: dc0fc479-e86f-409b-abbf-466b042e9605

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 019a1544-a9b7-48be-a0c2-a07799513c1c

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 9d1a07c5-a2cc-4134-8f0a-fe6a214dc6db

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: dc1c5a71-5fd7-466c-add8-74dda591124b
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 10e3cb80-ff5e-4ca4-9113-dd29d2b66c6b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f115244a-ed4b-4f5b-a699-5f96183f0400
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f0792f30-c28c-4018-98a5-34d139ae7a19
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 509b3e86-d6f6-47af-9752-35bb39f950b1
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3b679623-b75b-469f-9c0f-a5fabd475811
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 74a0060c-ff7a-44f1-894a-3e667b9f8908
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 049914b7-7b6e-40a9-928c-7c3f689f79c5
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3538628d-717e-4bf3-9b38-eefcf2ec52ed

		level Year
			ordinal: 0
			column: Year
			lineageTag: 29c9b973-b0c7-489b-9057-170b702d88ad

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 1a766f5a-c13a-4f57-be7a-cc6b9e5a38f4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 50bc334f-0899-475a-95be-7820e3670ad5

		level Day
			ordinal: 3
			column: Day
			lineageTag: ccc57649-9db8-409f-b845-cb15a94f3050


	partition 'Calendar-4853cfd7-f5bb-440e-9167-c17f258c69f1' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

