table Calendar
	lineageTag: 368b581a-6318-4b90-ab28-26149941f73c

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 49568c65-41bf-41f6-bdb4-c0c01a371e0f

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 00f34ba4-9347-49eb-9e23-4a5627c6ba28

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: bc1cbff5-fb85-4802-8d31-dde62e5ca68e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bef1b7d1-96fc-46c1-bfa2-5f72cc49f50f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 128dba13-a6eb-43da-bd74-6e2590b625a2
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b627060e-c520-4e72-ab8d-c52d59a94996
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: da23a5e9-3cb6-4ba8-966d-989965f134da
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 6e16b3bc-f633-454a-b48a-c84c1f3798ef
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1153d53f-7749-4676-8bde-0d579d1dc451
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7be24b17-5703-40bc-a279-39418572d50c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ebef8f95-63fd-4f05-9a0c-4e76d1c8fe1c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b2ce42bd-964c-45df-94b9-dea495db6cc6

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6ae16ba8-7c98-458f-88c8-aa57ce127290

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3dbd461d-dc17-4dbe-b3ec-207ae5be0d7b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 99a83ba4-2395-4179-b880-4453bc4731c6

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7b2efc8d-6844-4ff8-9be6-c01366180030


	partition 'Calendar-164fe582-da24-4ec0-a428-923d9051d6d8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

