table Calendar
	lineageTag: cc80da6a-523f-4725-b19b-5697c73a7488

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 81ee9909-fd8d-42cc-a358-970ab73cb112

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 01ec24b4-6f79-4b5f-8342-09d3b20184b1

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: def5ab12-2f93-43d9-9dd0-1836235bc04a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 669116a4-6b1d-4736-86eb-bef56f523150
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 4660964b-833b-4266-8e9a-bae94fbf0a8d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1294a33b-0a02-492b-8c73-b395c3b551a9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a139c545-2a2f-44c2-87a1-0a237a6281e5
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d3510d62-7f3d-4fca-9d90-3afe1dbfbde8
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 11bb674d-c536-4982-b879-991ac1833e6d
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: aed1f4db-f633-4751-8ec6-5700239a9387
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 933b069c-d4bd-460a-81f5-bcc48322cae6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 92ead191-dbd4-4207-9819-c8a4569e72c1

		level Year
			ordinal: 0
			column: Year
			lineageTag: 55177ee4-940f-4452-b1bd-6fc8e5414db8

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 96567dac-7ddb-432e-8896-b9c17da8665a

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ccaaab5a-2396-49a3-9a9f-7439b79badef

		level Day
			ordinal: 3
			column: Day
			lineageTag: 355b9aaa-dde1-4f23-8873-9e7b43b89a93


	partition 'Calendar-bf09564c-b2ba-4446-9b85-de5fcb4b3a85' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

