table Calendar
	lineageTag: fc35f5c1-2288-4f35-9d73-8c6409768c5e

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 19d22e48-f63f-4375-96a2-b71a3b4279ea

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d6cb6830-ac2f-408b-bc80-84d15b5a6a33

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: aaf3047e-26f9-42f7-a83a-cb58d4ea350b

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d5af2b10-a8c2-40f7-b199-3564de114086
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 43717ead-20c2-42b1-82cd-9572bf74a170
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5dcab8ad-456d-4efe-92df-d8826ab76595
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 456cfb6d-4a25-4a3d-8275-3b28e9e362da
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 409720ec-b48a-45a7-808d-b03972423269
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8f970f82-0ad8-43ed-90e0-f375ab3f1161
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 9ee932cb-8b61-4b95-ac6f-2054939f1119
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 858f67bb-9925-48a4-8417-4e06cd6d7843
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: a33c7df4-47ba-405a-ae58-f86453ecc5be

		level Year
			ordinal: 0
			column: Year
			lineageTag: 90b636eb-1d74-4f6f-8711-7fb060ee28eb

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 4e4dcc2d-b77e-442f-9d51-6a4642188a02

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 06ad4d78-447d-46a1-af82-542023c5caec

		level Day
			ordinal: 3
			column: Day
			lineageTag: 98080752-c6c3-44b5-b35c-f4b5896ec904


	partition 'Calendar-6799946d-0856-4e24-8b2f-98a4f21b96b2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

