table Calendar
	lineageTag: 24e919dc-edc1-4cc3-900f-3fc3ec8b2d49

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 84d6991f-9f0b-4f58-a014-3e93f320b2d8
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0f82c8ec-6b57-430e-be3f-92cd180164f9
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 343204d8-b796-443f-9a9d-60db3e17f379
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 3e3ead46-d28d-4fac-b206-5cf0d12fb5d5
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 99708a26-aa8a-41ef-82c3-833e17ff3b58
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1084e3b8-51bc-44a1-8b35-60b8ae54d0d1
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e90cce35-85b8-4d73-b4bf-23dea313de9f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 48a7651c-ac89-4dd2-bd31-c5d62867d977
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7fe40108-c8fb-4710-903f-10cd076152e3

		level Year
			ordinal: 0
			column: Year
			lineageTag: f6db2f25-4ea7-431e-966b-4d531a6ea36e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ec0d4ca1-8561-4475-aee0-6a997f0938f5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: d52e280b-2602-40e9-af0a-8821dbe7e0ac

		level Day
			ordinal: 3
			column: Day
			lineageTag: d4eade0d-a62d-4944-bc02-80ea9d5ea66d


	partition 'Calendar-1c117a93-9b9c-4d8a-9c34-defe529dba34' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

