table TestData
	lineageTag: 2c392af1-b69b-4360-9298-680ebdd35902
	description: Contains 41 columns and 1 measures: Account Account Name, Account Number, Account Number Burst Out Account, Acct Name, Burst Out, Burst Out Join, Burst Out Set list, Burst Out View, ... (41 columns total).

	measure 'Number of Records' = COUNTROWS('TestData')
		displayFolder: Measures
		description: DAX: COUNTROWS('TestData')
		lineageTag: ba31a25b-0a0b-4cc7-bf4c-2ac8a3ded682

	column 'Account Account Name'
		dataType: string
		lineageTag: 9d4bb4c7-a778-4c37-a887-f3ecc9c78599
		summarizeBy: none
		sourceColumn: 'Account Account Name'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Account Number'
		dataType: double
		formatString: #,0.00
		lineageTag: d9a2889f-795a-48df-8139-5ac0415b1df4
		summarizeBy: sum
		sourceColumn: 'Account Number'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Account Number Burst Out Account'
		dataType: string
		lineageTag: dcd26ab8-fdf9-4bb0-876c-3e9a592da740
		summarizeBy: none
		sourceColumn: 'Account Number Burst Out Account'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Acct Name'
		dataType: string
		lineageTag: d2a02946-a7ab-436c-aa07-f89260f35548
		summarizeBy: none
		sourceColumn: 'Acct Name'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Burst Out'
		dataType: string
		lineageTag: 6c4cc1a8-c46d-40b1-85dd-f99940edc1b4
		summarizeBy: none
		sourceColumn: 'Burst Out'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Join'
		dataType: string
		lineageTag: fe1a4577-f223-45e6-bcc2-9bef2f88ae84
		summarizeBy: none
		sourceColumn: 'Burst Out Join'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Set list'
		dataType: double
		formatString: #,0.00
		lineageTag: 918ad629-df78-4071-a530-5fe8dec63447
		summarizeBy: sum
		sourceColumn: 'Burst Out Set list'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Burst Out View'
		dataType: double
		formatString: #,0.00
		lineageTag: 5d0a2bbb-45d0-4411-97dd-af1f5b8d8d7c
		summarizeBy: sum
		sourceColumn: 'Burst Out View'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Count JE Number'
		dataType: double
		formatString: #,0.00
		lineageTag: c467159f-4667-4b13-8008-4f61fe2d7273
		summarizeBy: sum
		sourceColumn: 'Count JE Number'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Entity ID'
		dataType: string
		lineageTag: 02b1c247-2b06-45de-b532-76cfe9797a2a
		summarizeBy: none
		sourceColumn: 'Entity ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Filter
		dataType: double
		formatString: #,0.00
		lineageTag: 1aefdf88-3608-4e26-be48-7755e9c2c235
		summarizeBy: sum
		sourceColumn: Filter
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: 9c2a8720-b498-4186-b3dc-958a316bfcb5
		summarizeBy: none
		sourceColumn: 'Fiscal Year'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: boolean
		lineageTag: 6b36f95e-047b-4992-a883-5849b396cb4e
		summarizeBy: none
		sourceColumn: Flag
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column Flag__copy_
		dataType: boolean
		lineageTag: 720995fd-a911-4db2-ad97-d9d287cff203
		summarizeBy: none
		sourceColumn: Flag__copy_
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column 'FS Line'
		dataType: double
		formatString: #,0.00
		lineageTag: a492ddf0-fa8b-4d75-8099-d3d1a02896d7
		summarizeBy: sum
		sourceColumn: 'FS Line'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'FS Line Burst Out Account'
		dataType: string
		lineageTag: 0614f5cd-32b0-4d77-b3c9-6996746c76c2
		summarizeBy: none
		sourceColumn: 'FS Line Burst Out Account'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Group By'
		dataType: double
		formatString: #,0.00
		lineageTag: 8bff3809-20ad-48ed-a3bb-d73ffa0b0e0c
		summarizeBy: sum
		sourceColumn: 'Group By'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: 6cc2de1c-9e6c-428e-b030-c4205212c4d7
		summarizeBy: none
		sourceColumn: Image
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Note Line'
		dataType: double
		formatString: #,0.00
		lineageTag: aa546807-f19d-444b-8302-3b4dce3bfa58
		summarizeBy: sum
		sourceColumn: 'Note Line'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Note Line Burst Out Account'
		dataType: string
		lineageTag: 0362f9f6-22c1-4853-b920-3614fc49f776
		summarizeBy: none
		sourceColumn: 'Note Line Burst Out Account'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Selection
		dataType: double
		formatString: #,0.00
		lineageTag: 57cdcf0b-d7b0-41df-98f8-b74914361810
		summarizeBy: sum
		sourceColumn: Selection
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column SHOW
		dataType: string
		lineageTag: b40d16b4-bac7-4e3f-a122-2518e03a133e
		summarizeBy: none
		sourceColumn: SHOW
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Show Cycle Based'
		dataType: string
		lineageTag: 9d258863-c35b-4043-a452-32bced651c47
		summarizeBy: none
		sourceColumn: 'Show Cycle Based'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Sub Class'
		dataType: double
		formatString: #,0.00
		lineageTag: 96f8e597-9cb7-41da-ad87-525f619a136b
		summarizeBy: sum
		sourceColumn: 'Sub Class'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'SubClass Burst Out Account'
		dataType: string
		lineageTag: c002cdce-52f5-40e6-a20e-bdd5f24f33fd
		summarizeBy: none
		sourceColumn: 'SubClass Burst Out Account'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 96f89797-15c1-4875-9ff1-ac8f3dd04785
		summarizeBy: none
		sourceColumn: Type
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: string
		lineageTag: 305e55c3-b090-41c5-b1ef-874ea1f73527
		summarizeBy: none
		sourceColumn: Amount
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Amount1
		dataType: string
		lineageTag: 64b98573-36d5-49d0-8f27-12c9f0e035a5
		summarizeBy: none
		sourceColumn: Amount1
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Count of Amount Calculation'
		dataType: double
		formatString: #,0.00
		lineageTag: 30e680cf-67b3-49b9-b150-a096c8825f33
		summarizeBy: sum
		sourceColumn: 'Count of Amount Calculation'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: double
		formatString: #,0.00
		lineageTag: 114f8495-cf72-4070-83a3-eff33f1039e8
		summarizeBy: sum
		sourceColumn: 'Number of Records'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Number of Records1'
		dataType: double
		formatString: #,0.00
		lineageTag: ca8c3fbf-73d3-45e4-8ccc-49da370d0123
		summarizeBy: sum
		sourceColumn: 'Number of Records1'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Select Burst Out'
		dataType: double
		formatString: #,0.00
		lineageTag: 130d60bb-91d4-428e-ac8d-0bdfeda81e92
		summarizeBy: sum
		sourceColumn: 'Select Burst Out'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Select Transaction Analysis view'
		dataType: double
		formatString: #,0.00
		lineageTag: 62134f2b-ce4c-4aea-b011-dcaf70a64b36
		summarizeBy: sum
		sourceColumn: 'Select Transaction Analysis view'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Sum Cy'
		dataType: double
		formatString: #,0.00
		lineageTag: 642ff9f7-ff2c-436d-8e89-3a7de03289b3
		summarizeBy: sum
		sourceColumn: 'Sum Cy'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Sum Py1'
		dataType: double
		formatString: #,0.00
		lineageTag: b39b5539-2b5e-4209-aa83-7178b46ea636
		summarizeBy: sum
		sourceColumn: 'Sum Py1'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Sum Py2'
		dataType: double
		formatString: #,0.00
		lineageTag: 2a686646-bc83-48ee-bac3-e9f109bf2326
		summarizeBy: sum
		sourceColumn: 'Sum Py2'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Sum Py3'
		dataType: double
		formatString: #,0.00
		lineageTag: 47c24690-d680-4210-b50c-2282f473a232
		summarizeBy: sum
		sourceColumn: 'Sum Py3'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Sum Py4'
		dataType: double
		formatString: #,0.00
		lineageTag: b4c6d518-a0ab-492f-bb92-aceb4f027044
		summarizeBy: sum
		sourceColumn: 'Sum Py4'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Total Credits'
		dataType: double
		formatString: #,0.00
		lineageTag: b6a74b43-4b22-454d-b1a4-f7d5ce066ac5
		summarizeBy: sum
		sourceColumn: 'Total Credits'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Total Debits'
		dataType: double
		formatString: #,0.00
		lineageTag: b1845595-3ab4-408d-a07b-7039f9eb12f4
		summarizeBy: sum
		sourceColumn: 'Total Debits'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column BurstoutSet
		dataType: string
		lineageTag: 8c6ead13-bf3c-4291-8cb7-665899ae5873
		summarizeBy: none
		sourceColumn: BurstoutSet
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'TestData-4d1cd8f7-eca7-44e4-b5b8-9ad2b56f0c64' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("b5dpm3ihhu.database.windows.net", "EmptyDB"),
				
				            _nav = _src{[Schema="dbo", Item="TestData"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Account Account Name", "Account Number", "Account Number Burst Out Account", "Acct Name", "Burst Out", "Burst Out Join", "Burst Out Set list", "Burst Out View", "Count JE Number", "Entity ID", "Filter", "Fiscal Year", "Flag", "Flag__copy_", "FS Line", "FS Line Burst Out Account", "Group By", "Image", "Note Line", "Note Line Burst Out Account", "Selection", "show", "Show Cycle Based", "Sub Class", "SubClass Burst Out Account", "Type", "Amount", "Amount1", "Count of Amount Calculation", "Number of Records", "Number of Records1", "Select Burst Out", "Select Transaction Analysis view", "Sum Cy", "Sum Py1", "Sum Py2", "Sum Py3", "Sum Py4", "Total Credits", "Total Debits"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"show", "Show"}}),
				    #"Added SHOW" = Table.AddColumn(#"Renamed Columns", "SHOW", each if [BurstoutSet] then "Selected" else "Not Selected", type text),
				    #"Added BurstoutSet" = Table.AddColumn(#"Added SHOW", "BurstoutSet", each "", type text),
				    Result = #"Added BurstoutSet"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 41 columns and 1 measures: Account Account Name, Account Number, Account Number Burst Out Account, Acct Name, Burst Out, Burst Out Join, Burst Out Set list, Burst Out View, ... (41 columns total).

