table TestData
	lineageTag: 6395fa47-a0e8-4c4f-859a-bec4c92eaa8a

	column 'Account Account Name'
		dataType: string
		lineageTag: dba6baf4-ec5b-4ddc-82bf-63978fd64759
		summarizeBy: none
		sourceColumn: 'Account Account Name'

		annotation SummarizationSetBy = Automatic

	column 'Account Number'
		dataType: double
		formatString: #,0.00
		lineageTag: 24b78390-fd37-4324-b507-0ea4e937b1aa
		summarizeBy: sum
		sourceColumn: 'Account Number'

		annotation SummarizationSetBy = Automatic

	column 'Account Number Burst Out Account'
		dataType: string
		lineageTag: 3dd77e82-c349-41af-94ec-1a6309009acd
		summarizeBy: none
		sourceColumn: 'Account Number Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Acct Name'
		dataType: string
		lineageTag: b6a0706b-88c7-46b0-a2f8-ec9916ae22cc
		summarizeBy: none
		sourceColumn: 'Acct Name'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out'
		dataType: string
		lineageTag: 0273ce3c-ff4d-4a2b-bbeb-09cfd50b8d50
		summarizeBy: none
		sourceColumn: 'Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Join'
		dataType: string
		lineageTag: 185de12a-eaba-40a3-8e2c-fe657c20f437
		summarizeBy: none
		sourceColumn: 'Burst Out Join'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Set list'
		dataType: double
		formatString: #,0.00
		lineageTag: 3b83e391-14b3-499d-b1a9-4fc61b06dc76
		summarizeBy: sum
		sourceColumn: 'Burst Out Set list'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out View'
		dataType: double
		formatString: #,0.00
		lineageTag: 56006e3d-8b58-4eac-8773-d74e7eb21348
		summarizeBy: sum
		sourceColumn: 'Burst Out View'

		annotation SummarizationSetBy = Automatic

	column 'Count JE Number'
		dataType: double
		formatString: #,0.00
		lineageTag: a6adeee3-da37-4094-9661-4fbefe8532cd
		summarizeBy: sum
		sourceColumn: 'Count JE Number'

		annotation SummarizationSetBy = Automatic

	column 'Entity ID'
		dataType: string
		lineageTag: 65dbbee7-99f6-4e14-92e5-47f1a0b23f3b
		summarizeBy: none
		sourceColumn: 'Entity ID'

		annotation SummarizationSetBy = Automatic

	column Filter
		dataType: double
		formatString: #,0.00
		lineageTag: ecf8c05a-f99b-4010-91cf-de47e6a88463
		summarizeBy: sum
		sourceColumn: Filter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: c0e37910-7a94-48ce-be0d-8310ca8fc34f
		summarizeBy: none
		sourceColumn: 'Fiscal Year'

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: boolean
		lineageTag: 51f3c045-240b-4c66-a05f-1419116331d0
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column Flag__copy_
		dataType: boolean
		lineageTag: 82f05e59-7271-45a2-8205-7d0d75d22858
		summarizeBy: none
		sourceColumn: Flag__copy_

		annotation SummarizationSetBy = Automatic

	column 'FS Line'
		dataType: double
		formatString: #,0.00
		lineageTag: 75351e9a-6f91-4362-b001-b0600526c5a1
		summarizeBy: sum
		sourceColumn: 'FS Line'

		annotation SummarizationSetBy = Automatic

	column 'FS Line Burst Out Account'
		dataType: string
		lineageTag: 31cdf9fb-2616-46c5-9c3b-a78c4e44c521
		summarizeBy: none
		sourceColumn: 'FS Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Group By'
		dataType: double
		formatString: #,0.00
		lineageTag: 888543e9-ffdb-45dd-98b1-0c1c1e5bec17
		summarizeBy: sum
		sourceColumn: 'Group By'

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: d8c4cbc0-bba4-44be-8341-209ecd4bbe73
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	column 'Note Line'
		dataType: double
		formatString: #,0.00
		lineageTag: 766857eb-7efe-4051-a819-fcb4911dfe05
		summarizeBy: sum
		sourceColumn: 'Note Line'

		annotation SummarizationSetBy = Automatic

	column 'Note Line Burst Out Account'
		dataType: string
		lineageTag: 0a72d3c0-cc05-44cc-b6c8-16d79453f3c6
		summarizeBy: none
		sourceColumn: 'Note Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Selection
		dataType: double
		formatString: #,0.00
		lineageTag: 883888b5-e20d-4c1b-9cbc-4a42008f9603
		summarizeBy: sum
		sourceColumn: Selection

		annotation SummarizationSetBy = Automatic

	column show
		dataType: string
		lineageTag: fc196a1e-4a80-4caf-b1ee-b38954506041
		summarizeBy: none
		sourceColumn: show

		annotation SummarizationSetBy = Automatic

	column 'Show Cycle Based'
		dataType: string
		lineageTag: 656b8a1c-d5ca-413c-9efc-022f5eaee5e2
		summarizeBy: none
		sourceColumn: 'Show Cycle Based'

		annotation SummarizationSetBy = Automatic

	column 'Sub Class'
		dataType: double
		formatString: #,0.00
		lineageTag: 43351f50-671d-4e7f-94a1-b393c1a3b8e8
		summarizeBy: sum
		sourceColumn: 'Sub Class'

		annotation SummarizationSetBy = Automatic

	column 'SubClass Burst Out Account'
		dataType: string
		lineageTag: 4f98df43-a707-4930-aa8b-90f665eff973
		summarizeBy: none
		sourceColumn: 'SubClass Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 07ace31a-031d-4569-9557-3f41d18753bb
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: string
		lineageTag: 9152f05d-4e50-4fb1-9524-b7c673e9bda7
		summarizeBy: none
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Amount1
		dataType: string
		lineageTag: 9d359768-8230-4d7b-9fa8-2a7987684e23
		summarizeBy: none
		sourceColumn: Amount1

		annotation SummarizationSetBy = Automatic

	column 'Count of Amount Calculation'
		dataType: double
		formatString: #,0.00
		lineageTag: 6710e4fd-8127-4e70-adb2-44585049832a
		summarizeBy: sum
		sourceColumn: 'Count of Amount Calculation'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: double
		formatString: #,0.00
		lineageTag: 5312b5b2-e2b2-44a7-a919-869f58229cea
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records1'
		dataType: double
		formatString: #,0.00
		lineageTag: 172e3534-ce14-4576-a745-a51ab258c807
		summarizeBy: sum
		sourceColumn: 'Number of Records1'

		annotation SummarizationSetBy = Automatic

	column 'Select Burst Out'
		dataType: double
		formatString: #,0.00
		lineageTag: a9692e05-9fea-45dd-a00c-0211ebf234bc
		summarizeBy: sum
		sourceColumn: 'Select Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Select Transaction Analysis view'
		dataType: double
		formatString: #,0.00
		lineageTag: 2444399b-3b57-4763-8a3e-f48ba6d83501
		summarizeBy: sum
		sourceColumn: 'Select Transaction Analysis view'

		annotation SummarizationSetBy = Automatic

	column 'Sum Cy'
		dataType: double
		formatString: #,0.00
		lineageTag: 628849d3-941e-462c-b7b4-fa2412cd5859
		summarizeBy: sum
		sourceColumn: 'Sum Cy'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py1'
		dataType: double
		formatString: #,0.00
		lineageTag: 982c8524-3795-47c7-8671-b6d71156744e
		summarizeBy: sum
		sourceColumn: 'Sum Py1'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py2'
		dataType: double
		formatString: #,0.00
		lineageTag: 86a0cf4d-fcf1-4258-acb8-11025b1f50b7
		summarizeBy: sum
		sourceColumn: 'Sum Py2'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py3'
		dataType: double
		formatString: #,0.00
		lineageTag: 1050e913-bf0a-4b71-a3a7-d5921016b051
		summarizeBy: sum
		sourceColumn: 'Sum Py3'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py4'
		dataType: double
		formatString: #,0.00
		lineageTag: 6164bf5a-bacb-4b83-a517-ff11a034a0ab
		summarizeBy: sum
		sourceColumn: 'Sum Py4'

		annotation SummarizationSetBy = Automatic

	column 'Total Credits'
		dataType: double
		formatString: #,0.00
		lineageTag: 3230a83a-5b8a-4f91-a1b8-54cc6a898c8f
		summarizeBy: sum
		sourceColumn: 'Total Credits'

		annotation SummarizationSetBy = Automatic

	column 'Total Debits'
		dataType: double
		formatString: #,0.00
		lineageTag: 0b02c5a8-b319-4e26-8bf5-05591d3e3b69
		summarizeBy: sum
		sourceColumn: 'Total Debits'

		annotation SummarizationSetBy = Automatic

	column SHOW
		dataType: string
		lineageTag: 45c5f783-e2e6-43ee-8749-d7f93a2f34cc
		summarizeBy: none
		sourceColumn: SHOW

		annotation SummarizationSetBy = Automatic

	column BurstoutSet
		dataType: string
		lineageTag: 8e6514ef-88d4-460e-a7be-90c71835b2cb
		summarizeBy: none
		sourceColumn: BurstoutSet
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'TestData-56c44261-3a9c-45e4-ad09-94557166d899' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("b5dpm3ihhu.database.windows.net", "EmptyDB")
				
				    otherwise
				
				        #table({"Account Account Name", "Account Number", "Account Number Burst Out Account", "Acct Name", "Burst Out", "Burst Out Join", "Burst Out Set list", "Burst Out View", "Count JE Number", "Entity ID", "Filter", "Fiscal Year", "Flag", "Flag__copy_", "FS Line", "FS Line Burst Out Account", "Group By", "Image", "Note Line", "Note Line Burst Out Account", "Selection", "show", "Show Cycle Based", "Sub Class", "SubClass Burst Out Account", "Type", "Amount", "Amount1", "Count of Amount Calculation", "Number of Records", "Number of Records1", "Select Burst Out", "Select Transaction Analysis view", "Sum Cy", "Sum Py1", "Sum Py2", "Sum Py3", "Sum Py4", "Total Credits", "Total Debits"}, {}),
				    #"TestData Table" = Source{[Schema="dbo", Item="TestData"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"TestData Table", {{"show", "Show"}}),
				    #"Added SHOW" = Table.AddColumn(#"Renamed Columns", "SHOW", each if [BurstoutSet] then "Selected" else "Not Selected", type text),
				    #"Added BurstoutSet" = Table.AddColumn(#"Added SHOW", "BurstoutSet", each "", type text),
				    Result = #"Added BurstoutSet"
				in
				    Result

	annotation PBI_ResultType = Table

