table TestData
	lineageTag: e5ceab6a-804d-4af7-8445-dff9554995ba

	measure 'Number of Records' = COUNTROWS('TestData')
		displayFolder: Measures
		lineageTag: 5005194b-0dde-41da-87ce-cac51bab02f6

	column 'Account Account Name'
		dataType: string
		lineageTag: 6fd4adbc-5563-45af-80bb-2558c74aec75
		summarizeBy: none
		sourceColumn: 'Account Account Name'

		annotation SummarizationSetBy = Automatic

	column 'Account Number'
		dataType: double
		formatString: #,0.00
		lineageTag: 82662e6a-8600-43ac-8547-eda054502690
		summarizeBy: sum
		sourceColumn: 'Account Number'

		annotation SummarizationSetBy = Automatic

	column 'Account Number Burst Out Account'
		dataType: string
		lineageTag: 0f9955d4-5220-44a4-9b2b-22d56e07223c
		summarizeBy: none
		sourceColumn: 'Account Number Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Acct Name'
		dataType: string
		lineageTag: bdbde181-4511-4e9d-a1e4-dae714411cbc
		summarizeBy: none
		sourceColumn: 'Acct Name'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out'
		dataType: string
		lineageTag: 59e935c7-35a2-4129-8d31-917dc47eba35
		summarizeBy: none
		sourceColumn: 'Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Join'
		dataType: string
		lineageTag: 60c9410e-66a0-4bac-b0d9-fa5a0c9b2c5c
		summarizeBy: none
		sourceColumn: 'Burst Out Join'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Set list'
		dataType: double
		formatString: #,0.00
		lineageTag: cb4d497e-df9c-47a2-82f0-fd253fa7804e
		summarizeBy: sum
		sourceColumn: 'Burst Out Set list'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out View'
		dataType: double
		formatString: #,0.00
		lineageTag: d080f1c7-459d-4712-8071-43a743017ee4
		summarizeBy: sum
		sourceColumn: 'Burst Out View'

		annotation SummarizationSetBy = Automatic

	column 'Count JE Number'
		dataType: double
		formatString: #,0.00
		lineageTag: 48c4b39b-30cc-4a91-94d8-6a61fd924786
		summarizeBy: sum
		sourceColumn: 'Count JE Number'

		annotation SummarizationSetBy = Automatic

	column 'Entity ID'
		dataType: string
		lineageTag: aebe0219-d4c5-4428-8562-cd65c5474055
		summarizeBy: none
		sourceColumn: 'Entity ID'

		annotation SummarizationSetBy = Automatic

	column Filter
		dataType: double
		formatString: #,0.00
		lineageTag: 7105c41b-fdaf-4990-a86b-374333793805
		summarizeBy: sum
		sourceColumn: Filter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: 952ec6a7-a2ff-4eb8-b4ec-3bbe59b11bf5
		summarizeBy: none
		sourceColumn: 'Fiscal Year'

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: boolean
		lineageTag: 68c9bbcf-76c7-4006-86d3-35989142ee34
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column Flag__copy_
		dataType: boolean
		lineageTag: c1c70247-65c3-403f-b31c-ae86a359933f
		summarizeBy: none
		sourceColumn: Flag__copy_

		annotation SummarizationSetBy = Automatic

	column 'FS Line'
		dataType: double
		formatString: #,0.00
		lineageTag: fd5c26fb-3017-4f39-bb3e-3a1261d5f5b1
		summarizeBy: sum
		sourceColumn: 'FS Line'

		annotation SummarizationSetBy = Automatic

	column 'FS Line Burst Out Account'
		dataType: string
		lineageTag: e1c9f5ae-0df1-44de-8e5f-6f076ff71ea2
		summarizeBy: none
		sourceColumn: 'FS Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Group By'
		dataType: double
		formatString: #,0.00
		lineageTag: 65205861-ccf1-405e-8bb4-219447143205
		summarizeBy: sum
		sourceColumn: 'Group By'

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: e59587a5-7bc0-4ed1-bc28-8e28e7c6b4fb
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	column 'Note Line'
		dataType: double
		formatString: #,0.00
		lineageTag: 0a3dec90-f533-4623-89a0-d2140d21104f
		summarizeBy: sum
		sourceColumn: 'Note Line'

		annotation SummarizationSetBy = Automatic

	column 'Note Line Burst Out Account'
		dataType: string
		lineageTag: 426dc7eb-01c2-4fe7-a16a-a2d9038aef05
		summarizeBy: none
		sourceColumn: 'Note Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Selection
		dataType: double
		formatString: #,0.00
		lineageTag: d8dda844-2fa1-4293-9b20-401925cbf646
		summarizeBy: sum
		sourceColumn: Selection

		annotation SummarizationSetBy = Automatic

	column show
		dataType: string
		lineageTag: ac17d385-bee7-4992-bb91-001bdf9b4ade
		summarizeBy: none
		sourceColumn: show

		annotation SummarizationSetBy = Automatic

	column 'Show Cycle Based'
		dataType: string
		lineageTag: b4530030-1366-4763-ab47-52c8908e370f
		summarizeBy: none
		sourceColumn: 'Show Cycle Based'

		annotation SummarizationSetBy = Automatic

	column 'Sub Class'
		dataType: double
		formatString: #,0.00
		lineageTag: 4bff8d6b-5d5b-49cb-9213-2a7a12a69de2
		summarizeBy: sum
		sourceColumn: 'Sub Class'

		annotation SummarizationSetBy = Automatic

	column 'SubClass Burst Out Account'
		dataType: string
		lineageTag: e7b00b11-c5aa-470a-973a-4a2a226284e5
		summarizeBy: none
		sourceColumn: 'SubClass Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: b443fb9d-093a-472b-8c65-83940081f46b
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: string
		lineageTag: 65e7e1bc-4ba4-4366-beb8-a6746a6074e2
		summarizeBy: none
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Amount1
		dataType: string
		lineageTag: a7534659-86ff-4d25-b196-15fb388f1b34
		summarizeBy: none
		sourceColumn: Amount1

		annotation SummarizationSetBy = Automatic

	column 'Count of Amount Calculation'
		dataType: double
		formatString: #,0.00
		lineageTag: 989fbc79-d9bd-4b41-96d3-ce93b1726593
		summarizeBy: sum
		sourceColumn: 'Count of Amount Calculation'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: double
		formatString: #,0.00
		lineageTag: 8b5525f3-ba5e-48c5-af72-b229d217acbe
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records1'
		dataType: double
		formatString: #,0.00
		lineageTag: abad2782-4928-4250-9518-8597dd87d1ba
		summarizeBy: sum
		sourceColumn: 'Number of Records1'

		annotation SummarizationSetBy = Automatic

	column 'Select Burst Out'
		dataType: double
		formatString: #,0.00
		lineageTag: ed97ac50-e544-4865-9d49-6e2d4c58c8ef
		summarizeBy: sum
		sourceColumn: 'Select Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Select Transaction Analysis view'
		dataType: double
		formatString: #,0.00
		lineageTag: 89de42fa-a0f0-4d85-bb24-be70edf80f5d
		summarizeBy: sum
		sourceColumn: 'Select Transaction Analysis view'

		annotation SummarizationSetBy = Automatic

	column 'Sum Cy'
		dataType: double
		formatString: #,0.00
		lineageTag: 4b8c0a8c-8b1c-4ab4-bb2d-60f6399b4814
		summarizeBy: sum
		sourceColumn: 'Sum Cy'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py1'
		dataType: double
		formatString: #,0.00
		lineageTag: fab6dec5-ad63-4354-9a7e-1267b00b1138
		summarizeBy: sum
		sourceColumn: 'Sum Py1'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py2'
		dataType: double
		formatString: #,0.00
		lineageTag: 81559edd-4c0d-44e1-9264-9bbec893a144
		summarizeBy: sum
		sourceColumn: 'Sum Py2'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py3'
		dataType: double
		formatString: #,0.00
		lineageTag: e42a9d63-9fb5-4c63-93bf-72428f51e554
		summarizeBy: sum
		sourceColumn: 'Sum Py3'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py4'
		dataType: double
		formatString: #,0.00
		lineageTag: ca04dec2-bf0e-47d8-991c-d3bb722fce78
		summarizeBy: sum
		sourceColumn: 'Sum Py4'

		annotation SummarizationSetBy = Automatic

	column 'Total Credits'
		dataType: double
		formatString: #,0.00
		lineageTag: e010934c-626c-4997-9f6d-346e3f96a7eb
		summarizeBy: sum
		sourceColumn: 'Total Credits'

		annotation SummarizationSetBy = Automatic

	column 'Total Debits'
		dataType: double
		formatString: #,0.00
		lineageTag: 4c659e35-4dbf-41a2-98cd-da4acf496ce2
		summarizeBy: sum
		sourceColumn: 'Total Debits'

		annotation SummarizationSetBy = Automatic

	column SHOW
		dataType: string
		lineageTag: 624eec00-0cb2-4fd0-ae4f-90e96f19c468
		summarizeBy: none
		sourceColumn: SHOW

		annotation SummarizationSetBy = Automatic

	column BurstoutSet
		dataType: string
		lineageTag: caa82aa8-77f2-4a99-88ab-8134fa0250cf
		summarizeBy: none
		sourceColumn: BurstoutSet
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'TestData-669870b0-a929-4931-9301-4d09ccc4456e' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("b5dpm3ihhu.database.windows.net", "EmptyDB")
				
				    otherwise
				
				        #table({"Account Account Name", "Account Number", "Account Number Burst Out Account", "Acct Name", "Burst Out", "Burst Out Join", "Burst Out Set list", "Burst Out View", "Count JE Number", "Entity ID", "Filter", "Fiscal Year", "Flag", "Flag__copy_", "FS Line", "FS Line Burst Out Account", "Group By", "Image", "Note Line", "Note Line Burst Out Account", "Selection", "show", "Show Cycle Based", "Sub Class", "SubClass Burst Out Account", "Type", "Amount", "Amount1", "Count of Amount Calculation", "Number of Records", "Number of Records1", "Select Burst Out", "Select Transaction Analysis view", "Sum Cy", "Sum Py1", "Sum Py2", "Sum Py3", "Sum Py4", "Total Credits", "Total Debits"}, {}),
				    #"TestData Table" = Source{[Schema="dbo", Item="TestData"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"TestData Table", {{"show", "Show"}}),
				    #"Added SHOW" = Table.AddColumn(#"Renamed Columns", "SHOW", each if [BurstoutSet] then "Selected" else "Not Selected", type text),
				    #"Added BurstoutSet" = Table.AddColumn(#"Added SHOW", "BurstoutSet", each "", type text),
				    Result = #"Added BurstoutSet"
				in
				    Result

	annotation PBI_ResultType = Table

