table TestData
	lineageTag: 46887d63-6023-4245-8ae0-2ea7b2383fc2

	measure 'Number of Records' = COUNTROWS('TestData')
		displayFolder: Measures
		lineageTag: b464f86a-7e4a-4ef8-a663-1e119506ad07

	column 'Account Account Name'
		dataType: string
		lineageTag: f5626f35-912b-40c2-9b9b-f25f67cf688c
		summarizeBy: none
		sourceColumn: 'Account Account Name'

		annotation SummarizationSetBy = Automatic

	column 'Account Number'
		dataType: double
		formatString: #,0.00
		lineageTag: 00a3d7c1-d567-4a93-8f82-a4494fb647f2
		summarizeBy: sum
		sourceColumn: 'Account Number'

		annotation SummarizationSetBy = Automatic

	column 'Account Number Burst Out Account'
		dataType: string
		lineageTag: 15a73235-9f18-40d6-bcd5-40e0e094176b
		summarizeBy: none
		sourceColumn: 'Account Number Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Acct Name'
		dataType: string
		lineageTag: 0539de5b-e9d9-4c28-820c-37bcc1d39004
		summarizeBy: none
		sourceColumn: 'Acct Name'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out'
		dataType: string
		lineageTag: 557b108d-d54e-45c4-8d40-0448ad515da7
		summarizeBy: none
		sourceColumn: 'Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Join'
		dataType: string
		lineageTag: 0b41e898-2b65-4dee-a0d7-b17d98c101b3
		summarizeBy: none
		sourceColumn: 'Burst Out Join'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Set list'
		dataType: double
		formatString: #,0.00
		lineageTag: e73f50b6-f4cb-4950-b06b-9336488ef1ec
		summarizeBy: sum
		sourceColumn: 'Burst Out Set list'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out View'
		dataType: double
		formatString: #,0.00
		lineageTag: 3cb394ee-ee4f-4bbe-b031-6257ce97057c
		summarizeBy: sum
		sourceColumn: 'Burst Out View'

		annotation SummarizationSetBy = Automatic

	column 'Count JE Number'
		dataType: double
		formatString: #,0.00
		lineageTag: 85945722-520d-4c5e-ac94-d9b9ee82c2c8
		summarizeBy: sum
		sourceColumn: 'Count JE Number'

		annotation SummarizationSetBy = Automatic

	column 'Entity ID'
		dataType: string
		lineageTag: fcd797b7-317f-4221-a0ed-5ce52aeb5dd4
		summarizeBy: none
		sourceColumn: 'Entity ID'

		annotation SummarizationSetBy = Automatic

	column Filter
		dataType: double
		formatString: #,0.00
		lineageTag: 551e4843-51ce-4100-b66d-c594e1a001ad
		summarizeBy: sum
		sourceColumn: Filter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: e6eb7875-337f-4934-a828-01955b697d1a
		summarizeBy: none
		sourceColumn: 'Fiscal Year'

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: boolean
		lineageTag: fb4fd590-47fa-4ce7-9c45-730eadd5140d
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column Flag__copy_
		dataType: boolean
		lineageTag: 4d41cc4a-3ebf-4e28-94e7-953c92dd8e41
		summarizeBy: none
		sourceColumn: Flag__copy_

		annotation SummarizationSetBy = Automatic

	column 'FS Line'
		dataType: double
		formatString: #,0.00
		lineageTag: b01b58a5-cadf-4b6f-90bc-32652a6edf12
		summarizeBy: sum
		sourceColumn: 'FS Line'

		annotation SummarizationSetBy = Automatic

	column 'FS Line Burst Out Account'
		dataType: string
		lineageTag: e22c6aa1-ac05-49d8-8893-6d976d5d089c
		summarizeBy: none
		sourceColumn: 'FS Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Group By'
		dataType: double
		formatString: #,0.00
		lineageTag: f6da20c5-2fa4-44df-b53e-10ed77f7939a
		summarizeBy: sum
		sourceColumn: 'Group By'

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: 410bb64a-3190-4b07-a33d-7f795a1b51da
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	column 'Note Line'
		dataType: double
		formatString: #,0.00
		lineageTag: 48ca110d-d62b-4b2a-9e4f-872f61b6cd97
		summarizeBy: sum
		sourceColumn: 'Note Line'

		annotation SummarizationSetBy = Automatic

	column 'Note Line Burst Out Account'
		dataType: string
		lineageTag: 708d9b89-2676-4f9d-8171-415d8cc8378c
		summarizeBy: none
		sourceColumn: 'Note Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Selection
		dataType: double
		formatString: #,0.00
		lineageTag: e4034d53-268f-45a2-b639-c05cde4b9b5b
		summarizeBy: sum
		sourceColumn: Selection

		annotation SummarizationSetBy = Automatic

	column SHOW
		dataType: string
		lineageTag: 04ab1683-21c8-4376-8385-cdd65b41a25d
		summarizeBy: none
		sourceColumn: SHOW

		annotation SummarizationSetBy = Automatic

	column 'Show Cycle Based'
		dataType: string
		lineageTag: 1f9a18a5-4df8-4839-a30c-bcdcfb5d8ef0
		summarizeBy: none
		sourceColumn: 'Show Cycle Based'

		annotation SummarizationSetBy = Automatic

	column 'Sub Class'
		dataType: double
		formatString: #,0.00
		lineageTag: 0ecda21b-ca5c-488f-b98f-dfbe9184cb5f
		summarizeBy: sum
		sourceColumn: 'Sub Class'

		annotation SummarizationSetBy = Automatic

	column 'SubClass Burst Out Account'
		dataType: string
		lineageTag: 8340e138-087a-426a-ae41-6848e4a49c16
		summarizeBy: none
		sourceColumn: 'SubClass Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 789ea52a-3ff9-42ee-8021-d8a71d9d2047
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: string
		lineageTag: 2160799c-c044-47aa-bec0-c65dbba1b7d0
		summarizeBy: none
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Amount1
		dataType: string
		lineageTag: bd0867e8-9712-41c7-b244-3233201e43e4
		summarizeBy: none
		sourceColumn: Amount1

		annotation SummarizationSetBy = Automatic

	column 'Count of Amount Calculation'
		dataType: double
		formatString: #,0.00
		lineageTag: 83a2c423-4f33-4f01-a59a-550c90e7adfb
		summarizeBy: sum
		sourceColumn: 'Count of Amount Calculation'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: double
		formatString: #,0.00
		lineageTag: 83cc22da-4e44-44a8-9ff8-4e9ce5080910
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records1'
		dataType: double
		formatString: #,0.00
		lineageTag: 7d705fa1-43f6-41ac-b81d-f15b73a9283d
		summarizeBy: sum
		sourceColumn: 'Number of Records1'

		annotation SummarizationSetBy = Automatic

	column 'Select Burst Out'
		dataType: double
		formatString: #,0.00
		lineageTag: 12ff68e5-cff5-4a2e-ab36-0e0fea451f77
		summarizeBy: sum
		sourceColumn: 'Select Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Select Transaction Analysis view'
		dataType: double
		formatString: #,0.00
		lineageTag: 1af53b7b-fd28-4e15-867c-4aa5e82e7a6f
		summarizeBy: sum
		sourceColumn: 'Select Transaction Analysis view'

		annotation SummarizationSetBy = Automatic

	column 'Sum Cy'
		dataType: double
		formatString: #,0.00
		lineageTag: acf4d718-1978-48aa-8735-fd21a5936364
		summarizeBy: sum
		sourceColumn: 'Sum Cy'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py1'
		dataType: double
		formatString: #,0.00
		lineageTag: 10e9032f-9f5e-4958-9518-7e608b7d6f79
		summarizeBy: sum
		sourceColumn: 'Sum Py1'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py2'
		dataType: double
		formatString: #,0.00
		lineageTag: ab93bd4a-6209-4e2c-b22f-7aee2fb07b5a
		summarizeBy: sum
		sourceColumn: 'Sum Py2'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py3'
		dataType: double
		formatString: #,0.00
		lineageTag: 427d891f-1c20-4e79-98fa-28f374ff9f23
		summarizeBy: sum
		sourceColumn: 'Sum Py3'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py4'
		dataType: double
		formatString: #,0.00
		lineageTag: 4471fd6b-6b2d-4a58-9511-ebdf4972f07e
		summarizeBy: sum
		sourceColumn: 'Sum Py4'

		annotation SummarizationSetBy = Automatic

	column 'Total Credits'
		dataType: double
		formatString: #,0.00
		lineageTag: 5df29a64-d81c-4031-b641-d0934fadbe2d
		summarizeBy: sum
		sourceColumn: 'Total Credits'

		annotation SummarizationSetBy = Automatic

	column 'Total Debits'
		dataType: double
		formatString: #,0.00
		lineageTag: ad57e4cb-f6d8-4311-90e2-7797ab81db18
		summarizeBy: sum
		sourceColumn: 'Total Debits'

		annotation SummarizationSetBy = Automatic

	column BurstoutSet
		dataType: string
		lineageTag: ac90ae9d-1235-435d-bbbd-e1dd84e4c75c
		summarizeBy: none
		sourceColumn: BurstoutSet
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'TestData-40497159-1e8e-416c-aabb-8d1552d088cc' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("b5dpm3ihhu.database.windows.net", "EmptyDB")
				
				    otherwise
				
				        #table({"Account Account Name", "Account Number", "Account Number Burst Out Account", "Acct Name", "Burst Out", "Burst Out Join", "Burst Out Set list", "Burst Out View", "Count JE Number", "Entity ID", "Filter", "Fiscal Year", "Flag", "Flag__copy_", "FS Line", "FS Line Burst Out Account", "Group By", "Image", "Note Line", "Note Line Burst Out Account", "Selection", "show", "Show Cycle Based", "Sub Class", "SubClass Burst Out Account", "Type", "Amount", "Amount1", "Count of Amount Calculation", "Number of Records", "Number of Records1", "Select Burst Out", "Select Transaction Analysis view", "Sum Cy", "Sum Py1", "Sum Py2", "Sum Py3", "Sum Py4", "Total Credits", "Total Debits"}, {}),
				    #"TestData Table" = Source{[Schema="dbo", Item="TestData"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"TestData Table", {{"show", "Show"}}),
				    #"Added SHOW" = Table.AddColumn(#"Renamed Columns", "SHOW", each if [BurstoutSet] then "Selected" else "Not Selected", type text),
				    #"Added BurstoutSet" = Table.AddColumn(#"Added SHOW", "BurstoutSet", each "", type text),
				    Result = #"Added BurstoutSet"
				in
				    Result

	annotation PBI_ResultType = Table

