table 'Business Unit'
	lineageTag: c03fd15f-43ea-4c09-940f-52b940989fd0

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 829edd72-ed54-410b-9561-1e8f08d330ef

	column Value
		dataType: string
		lineageTag: 31c38a1b-4c59-49ee-a0d0-ca23617a9c8b
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-49ed6b32-eaa3-4ed1-8a1a-5ffef36bdf1f' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

