table 'Business Unit'
	lineageTag: 3ee04f2c-a9f9-4f4f-a6dc-856cbf0cf9c7

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: d475fad5-c3a1-49c9-950e-74ae48798bb9

	column Value
		dataType: string
		lineageTag: 5d2f49ce-c47a-4afd-bf1a-66c3b697bdee
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-7a20a280-ddcf-4d0d-8001-4b01d2c1ec6c' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

