table Calendar
	lineageTag: 6aa35d1d-b9e4-4c42-b288-c80229638a96

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 28e2ac60-8fa1-4784-a5d6-9b90c0a3acbd

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 255addba-65a9-4304-88ca-032f8adf7465

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 1c5ef5be-e786-4696-b956-bfdbee5a69f3

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c67f8032-7370-4847-aed3-bcdb45a73939
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 25048cfc-5661-49f4-80ed-148b15ee2e27
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dd4db67a-d7dc-48fa-a178-44c417c59a07
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 280a0b37-759a-4c58-82d6-09f8ff69560e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2699aaf0-18b2-484f-86db-2494e3a939b6
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 82f6a3e0-c7c4-45c6-bfc4-bb022e717c2c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 5c71737a-8dde-4833-b13f-ff6e9ae9846c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 72802a27-6057-4635-be2a-0083eb0709a1
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f83ca1ed-b626-4fa1-af31-474eb9b742cb

		level Year
			ordinal: 0
			column: Year
			lineageTag: f7d1fd94-433d-4ee4-a96c-35a8365fd08b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 65fab3d5-798a-4866-bfbf-86b029b612a4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 55b631d0-c8f3-4328-9f3c-a257cab733eb

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1bd23dbe-8105-4244-98de-9ab7fad8483b


	partition 'Calendar-7de97a20-0607-4da6-b58e-af90a2c7fee1' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

