table Calendar
	lineageTag: 77bd53d2-4b34-4b07-b794-b784e00a6a85

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: aa451a83-0fa4-40a1-a2ef-8886f1c446b7

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 16b2b893-019e-4407-b776-293ed5f39e44

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: eb67f542-eb33-4f81-93a3-8558d56b1ae4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ce0614c6-7fa6-40d0-9652-0829ece23a6f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 68b0efaa-be93-4cc2-861c-b9eb77a27d8a
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7091ae07-243f-4f25-a5fc-200bbcef775c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 05f1010f-5b1c-4ec6-840e-47d1fa2d3afa
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0a928e30-214f-44cb-b498-8a320893f31c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7ed9ecde-beda-4bfa-90c5-50ab85736477
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: bfafb2b3-a730-4029-a72b-d82d9abcccf2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 39937369-ca6d-480c-8af1-4fa6950cd0a1
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8ff901eb-c177-4138-b87d-8ae8942a8101

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6608b7b3-8f69-4d3f-af75-733fc6b478ae

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 7dd8bca0-d635-46b4-8445-8900a220044b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: db7893d9-5bdc-464f-a5ae-889d246a3767

		level Day
			ordinal: 3
			column: Day
			lineageTag: bdb993f3-eb0b-41d4-9794-6f3c33213157


	partition 'Calendar-eae64410-3329-4802-b306-baddedbdd6a5' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

