table 'Fiscal Year'
	lineageTag: 6544e103-a64c-44a3-b611-d68594c23099

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 153de802-386d-4f66-a4f2-cce7164a209f

	column Value
		dataType: int64
		lineageTag: c0ffb2bf-3cd1-41da-926f-db1019107910
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-66ae98aa-237a-48f3-b622-25fc6cb48722' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

