table 'Min Budget'
	lineageTag: 096ac305-336c-4c9d-a716-17f87115e6d2

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 5ae5dfc1-b177-43c1-aafe-9a41900be96f
		annotation Copilot_Description = DAX: SELECTEDVALUE('Min Budget'[Value], 5000)

	column Value
		dataType: double
		lineageTag: 356a34c2-214f-411c-96f1-0b6ec0e15ece
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-c0ef1c61-5983-49fc-82b1-7cb2df60ad38' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

