table Calendar
	lineageTag: a8315c3e-64bf-47c6-9fb3-c80ac93d8c56

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8115f9de-32e8-4dc0-af81-01882969107c

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 3e6485a3-c2f4-42c4-b17d-c1ede89818dd

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 260c2f3e-966d-45cc-972a-6affa708bd7e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b02375e2-91b7-4a73-994b-feccafd44558
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 96f1490f-3809-4a9c-ad11-1d7038e980d3
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4fd25cbc-6230-4e75-ac8e-e07f98efb313
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 937fb13c-f70e-437f-993c-dd76f3efe6b4
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c94db596-b08b-4ce5-9bc4-598230d3390c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7e4a3421-d60b-4a57-86ea-21a74da824a0
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: deba0fbf-4bc1-4e15-962f-2d4a3dc55f60
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f7815088-5339-42a9-959b-d14fd32edd17
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7d9d95ae-74e2-475e-b926-349b53f13582

		level Year
			ordinal: 0
			column: Year
			lineageTag: c55261e9-11e8-48f9-b6de-7870c9cfb9fb

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f4f4778e-a2af-452c-8e8f-d1f8b52776bc

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 21e8b121-06dc-4b99-bf99-733f5703c544

		level Day
			ordinal: 3
			column: Day
			lineageTag: aab837d1-1381-4bdb-b080-0a68baf97eb7


	partition 'Calendar-b0687bfa-77b4-4b6e-a511-3da84fcbdf97' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

