table Calendar
	lineageTag: 6ac90532-33ca-467a-9f38-a085f6d5f9c5

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 452530d1-ef87-45a3-839f-6792509e345d

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 78cbfd8f-469f-4fbc-bb59-8e71a9b2c6ca

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0dc1d287-7a90-4291-a308-531854feb89c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 72325431-4a56-44f8-8c38-52a38ee4b17b
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 4e4b268b-079c-482f-b9d8-d5f27a87274e
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: da92d054-6a8a-4b54-be39-e42f5947f564
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 88275ca9-c368-40dc-a7f3-ef366bcbfb7d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 531bf0b6-14d2-4a4c-8552-512e4ed7d603
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 628a9634-e2f4-478d-bfcc-b7aa3d493a9c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 39cebfce-9464-44c5-a5b6-8e4455a93acb
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d833edf7-a460-476e-a389-0d99102bebab
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 00432d9f-44bb-47e2-8c2e-2ed7b46c591f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 53483f41-aff7-4a32-91ea-acfe892f7ed2

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 17fe8c8b-8b06-4150-aa3b-6814b7ca0d33

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e72c2f6c-b4f9-4641-a7db-77c368518583

		level Day
			ordinal: 3
			column: Day
			lineageTag: 01cf9b27-d05f-4526-81a7-4b6492baec4e


	partition 'Calendar-71df3f6b-24ea-4610-9bf3-cd9c25a19cbc' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

