table Calendar
	lineageTag: e21ea446-2120-41e5-b47e-af28d4e8d788

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 28c36d4a-0ed6-4b40-a832-1d4d5942cd79

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1cb5c915-a094-45c7-8938-93d638baf353

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 01ac6fc4-b8ac-4313-b305-60db9c2ae193

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d67c5a89-400d-4053-9a43-c41b39507b9f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a900148e-31f9-4d8d-a53b-0ccccaedde82
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 971c3eb4-55b3-416f-99e8-951934d5a9e1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 168d3ff1-9e7e-421d-a5a3-564ff8574d4b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 75fa2680-cb9d-4204-9a50-bd9b972b8016
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ac66ebb7-a0db-44dc-a4a1-d0e5e73010b1
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 76b23399-25b6-43b1-ae2f-dea0bd8eb804
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d231b967-f72c-4680-8250-f0945261e9b6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 324e84ce-2357-40f8-9757-7de9fd4becfb

		level Year
			ordinal: 0
			column: Year
			lineageTag: 8cff0757-0318-49d5-8d9b-b62d7119b9ec

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f2c198a9-99d1-45a8-ae55-abeb7f429b41

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8d64a68c-dfcf-4d9b-87a5-86103d8cb0f5

		level Day
			ordinal: 3
			column: Day
			lineageTag: eb20e7af-d193-43eb-aa9c-965d43996feb


	partition 'Calendar-23ac8877-8eb7-4faa-85f1-7322d6a064e3' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

