table Calendar
	lineageTag: 107d4458-85a8-4753-a945-ddd9b41221f4

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 25db053f-b154-4ffd-938d-8b78a291d5d3

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: e020e842-03ce-47d9-9fa4-09423ebe91a7

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: b4ededd2-44d0-4938-b1c3-1434d5dcd928

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a6bea0b3-d00c-4636-95eb-420e45c8e755
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ac9c921b-afae-4c01-9404-90618b980237
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 530c64d2-cc5d-4b65-8568-ce5b68781ebc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b33fc6ce-a196-4f8a-af79-65ece96e4f9a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 17c0ef28-f252-4864-ab27-150a9238b836
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 5dd43ae5-ff2c-4622-a695-84c226f027a6
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: bbe19227-df55-4180-aed4-a723ffa24cc0
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: af07579e-6f31-4e85-918f-3cecb971a17b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: d993d084-6b40-43c0-82cc-74cb93da64ae

		level Year
			ordinal: 0
			column: Year
			lineageTag: 8d28904b-1446-4fa0-a274-66690781013e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3eb643d7-a0be-455f-b816-18b94bd2f72d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: abd44786-6f03-4e09-8f9c-664b51851774

		level Day
			ordinal: 3
			column: Day
			lineageTag: 48b7906e-d9db-4f6b-90ad-bb92327eb0a0


	partition 'Calendar-58d15606-870b-4db3-bb37-37dc3c982191' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

