table Calendar
	lineageTag: 1a9347b2-9e49-4375-b6de-fe64b55263b3
	description: Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		description: DAX: TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		lineageTag: 892a1679-82dd-46d8-8b8a-af620a5bfcef

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		description: DAX: CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		lineageTag: f2ab61c2-80cc-459d-b764-4b864559c6b0

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		description: DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		lineageTag: 18b119f8-165e-4253-80cc-df70db8377cc

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 68e6483d-e838-4678-9fcd-1eacaf81fc8d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime. (table key).

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: caf470be-6b56-4c42-9079-0f372519f321
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years
		description: Int64 column. categorized as Years.

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 44f14ad2-bb0f-4b64-9de1-40972082929e
		summarizeBy: none
		sourceColumn: Quarter
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f84b909c-b428-4cb7-a1e1-0a6a575da526
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months
		description: Int64 column. categorized as Months.

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0015ec74-9610-4e5f-a8c0-af8c1183a1fd
		summarizeBy: none
		sourceColumn: MonthName
		description: String column.
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f6ab807d-dda9-47bd-8bc1-35beb9282e30
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days
		description: Int64 column. categorized as Days.

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 23042e9e-9c9a-46de-b322-e3cebbc50eb1
		summarizeBy: none
		sourceColumn: DayOfWeek
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b97b7a44-d691-462f-9b5a-0794138bdd4f
		summarizeBy: none
		sourceColumn: DayName
		description: String column.
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e93bb04b-736e-4dd8-924a-9b245c885efd

		level Year
			ordinal: 0
			column: Year
			lineageTag: 01bf1df9-b8a2-4360-a07b-89d14ff61e3d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: cd0df5dc-32f2-4368-81a1-c88c2cdf371d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 896c3f09-ea7e-41e9-bc3a-e1bb3e57aa7f

		level Day
			ordinal: 3
			column: Day
			lineageTag: adc142da-475e-439a-8dc3-efb16827262b


	partition 'Calendar-f93e273f-6fc8-470f-9ab3-e1b55927a9c2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

