table Calendar
	lineageTag: e46eae05-b42b-4157-ac42-a0b949b509ea

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 94dd8604-c24d-47a3-b668-7db22ed8fac6

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ece6a9e2-36ca-4fd3-af1d-c6a72618cc61

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: b8a11ef7-0169-4595-b3af-c037cc14ea44

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a6f13cfa-8133-4b14-aceb-b0dff5fc830e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2c7a550a-0f34-4b23-923a-57374b903f42
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 01e9c3f0-7715-41d4-a677-d252cd24ff2b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7aa8645e-6f4f-4872-ace0-d0c0667adf10
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 07e8829a-c29c-43a1-8542-9b04dd657c75
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 6c35b58c-ac4e-495e-8750-1511c63112c2
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 8de0bf55-1b12-450f-80a7-d541a42b5056
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 784d76d5-3961-4f0a-86c6-1353808de161
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 13df84ff-a463-4758-9cb0-4b5c27120cac

		level Year
			ordinal: 0
			column: Year
			lineageTag: 0cd4fe95-ea99-454e-80f1-a32cc39cf494

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 8cee3312-4919-49fa-b281-55fb1dc7dee0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ef1edc44-67a8-4808-9db0-c9c75a45f520

		level Day
			ordinal: 3
			column: Day
			lineageTag: ba68111e-9485-43ee-a83a-b234540c3ac1


	partition 'Calendar-0cd7bbad-ddbb-4222-bfd2-59c16c11d9bd' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

