table Calendar
	lineageTag: 16449765-221c-4551-aab2-06456cbf0e8c

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6a84dd85-5c46-4967-a223-3e1aaf0a2448

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 028240a5-46ef-433d-91d7-17c323d84cdf

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 59bc69be-d520-4c43-98af-e1669a67cecb

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1aa41a90-f29a-407e-b3cf-a6168b2bc200
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 80d74dea-f1ea-406e-ba19-5ffdd965f38e
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 2a22995c-33e1-4a37-a0af-9dce658a45eb
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 3e2c92a6-f25b-46dd-918e-2f7156ef69cd
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 87a82dc1-0cbd-4e26-9166-a6b8a32dec44
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8b07aff1-1565-4d76-8d2f-9cfa8fab65de
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 14b98743-77d8-403e-ac93-de8801c4e540
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 5060ddaf-5fec-40ee-9bf9-f44ae8a3e4c9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3ef240e8-a073-4e35-a70b-b6525ddd1f3f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 0947b440-0e35-4ab6-8040-6f8379a89c00

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 9e208564-883c-4e18-94f7-8c984cf39346

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 38e28a47-03a8-49b9-8473-ea2c31be2943

		level Day
			ordinal: 3
			column: Day
			lineageTag: d81aee19-6b5f-4b8e-8908-e0f8190da889


	partition 'Calendar-a1067a45-f618-4b0f-9dd2-2054711e31ba' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

