table Calendar
	lineageTag: 405115dd-43b4-473f-9049-03b8e32760f0

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9ea885a7-215c-4c03-9280-f3375819a8ed

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: fba622cb-c70c-45fd-b6bd-2bfd8a86dc6e

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ed0b82bb-13dd-4870-9e1b-17b2f3d77f8c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4b680eca-8be9-4f76-b472-0500dae6131f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 720c58c0-a1a7-4e4e-9b74-29f4742f3722
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f7bbff24-7653-47c8-929c-042b1415a33a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ca69b0d7-ed5c-4c17-a4b4-df8ceb5b9e35
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e16f7f90-8fd4-47ce-abf3-685d7820776f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d7a4f425-ce23-4165-9135-fdf3e8566b7d
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ac4de17a-373a-462c-8e61-e2594bdd6f90
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 164e30a4-a5dd-42cd-8744-405e7d5ecd93
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4a4fbb5e-c7d7-464c-ac2b-be912f8e81b2

		level Year
			ordinal: 0
			column: Year
			lineageTag: 03d7eae2-fd7b-4a71-96c7-4f1b87b30b55

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f8a17dfb-d0d9-41d4-bcc3-a2aaa67d86a3

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 2906ba12-75a7-4da1-b650-74779ccdea99

		level Day
			ordinal: 3
			column: Day
			lineageTag: f6af2d0d-cbb3-46da-8197-efd6f4e1c703


	partition 'Calendar-93e6de99-ad0c-42d2-8d7b-ea735aa0b243' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

