table Calendar
	lineageTag: 81046ade-7d9a-4a44-8a27-abcd7166549c

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 64b4a7ef-1ae8-43f1-9b1b-5c1e6999b97e

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 34bf9d97-c766-4b74-b5c2-67389c554aae

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 902f5675-0914-40fd-8849-3ce0725b1d20

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 57162047-6619-43da-9c36-65c53781cb66
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 602339a6-bafd-413c-9452-b2ed50eca53d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d5e6a689-f120-44d8-b1ae-78c68548cef8
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ea03a5ee-ed8d-4b67-a11a-a52c30eda35b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 9773bbb8-9966-4abe-bdf3-211b45a3a2cc
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 6e6cb8f4-d5a9-4d40-99c1-1d657c469a08
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d858b847-04a0-4581-954a-9375139ccdb5
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b1f5a9fb-0388-4f0a-9909-6f6350ac111e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b684ec14-d78f-4620-8a83-a4308759e06c

		level Year
			ordinal: 0
			column: Year
			lineageTag: e8452d96-a6d9-41ad-84b2-479dce1c794d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e97f7f4e-dbf3-48d7-b143-f553d77b0b1d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: bf917598-35b2-4c3a-9b0f-4a68a7db5b5c

		level Day
			ordinal: 3
			column: Day
			lineageTag: d760602e-5cd1-428b-b2c0-df19e3f517bd


	partition 'Calendar-52488d4f-5b38-4eac-9b5d-db1bd4c294e3' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

