table Extract
	lineageTag: bf3bd9e9-6015-4919-9e33-de318a6d4dba

	measure 'GDP % of Total' = AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 4728633b-39ca-4d15-bd40-a9e7dbd29fce

	measure 'GDP per capita (weighted)' = SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 69694838-1cf0-4b8d-b5c8-cd1ebf7ce74b

	measure 'Rate spread (difference)' = AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 966b655b-f482-4b3c-8569-10f703a7a6d9

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 25b72e0c-1c82-4d3f-a767-2aebb98151f7

	column 'Country / Region'
		dataType: string
		lineageTag: 9432a941-2d46-4577-88b2-5e0803816202
		summarizeBy: none
		sourceColumn: 'Country / Region'
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1858232d-f8bf-4c76-b3a7-ef75aa5c9926
		summarizeBy: none
		sourceColumn: Date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'F: Deposit interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: d681ad18-ce3e-4e5f-b93b-812646215c74
		summarizeBy: sum
		sourceColumn: 'F: Deposit interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.00B;("$"#,#0,,.00B)
		lineageTag: 5eda040e-1ea8-4b61-8b8f-21e8fbbadb48
		summarizeBy: sum
		sourceColumn: 'F: GDP (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP per capita (curr $)'
		dataType: double
		formatString: c"$"#,#0,.0K;("$"#,#0,.0K)
		lineageTag: 0f3357dd-54ec-41ce-84c6-e35e45c0ecf3
		summarizeBy: sum
		sourceColumn: 'F: GDP per capita (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: Lending interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: f334e9da-0d49-4aa8-b073-bca81df37e38
		summarizeBy: sum
		sourceColumn: 'F: Lending interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp (% GDP)'
		dataType: double
		formatString: #,0.00
		lineageTag: a1102876-bf35-4033-8784-9cf0a3b8d517
		summarizeBy: sum
		sourceColumn: 'H: Health exp (% GDP)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp/cap (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.0B;("$"#,#0,,.0B)
		lineageTag: 4b8989a9-f663-47c9-883f-d6dfce134534
		summarizeBy: sum
		sourceColumn: 'H: Health exp/cap (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'H: Life exp (years)'
		dataType: double
		formatString: n#,0;-#,0
		lineageTag: fc1568fd-1d0a-471d-8006-0206ed55c939
		summarizeBy: sum
		sourceColumn: 'H: Life exp (years)'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 29cd11b0-38f5-41aa-ad0b-b62dca0fd5a5
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'P: Population (count)'
		dataType: double
		formatString: #,0.00
		lineageTag: 7929cf1f-ac9c-4e52-89ed-51df3384e27b
		summarizeBy: sum
		sourceColumn: 'P: Population (count)'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: e8e17f3c-ac8c-4c8c-8b8f-1492b6f58dd3
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Subregion
		dataType: string
		lineageTag: fe96e018-8aad-45aa-8163-b40c91f85cd8
		summarizeBy: none
		sourceColumn: Subregion
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Action (Country Name)'
		dataType: string
		lineageTag: 7650da3a-8598-421d-a9c6-961bca149818
		summarizeBy: none
		sourceColumn: 'Action (Country Name)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Date (year))'
		dataType: string
		lineageTag: 6cd49612-7446-4b8c-ad62-ac5aee047d8a
		summarizeBy: none
		sourceColumn: 'Action (Date (year))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: 7e581ab3-1844-4ae9-8c7d-002d03ff8593
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Date (year)))'
		dataType: string
		lineageTag: 2665fb1c-d22b-48ad-9cfe-3e9681dd8f87
		summarizeBy: none
		sourceColumn: 'Action (YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Exclusions (Country Name,YEAR(Date (year)))'
		dataType: string
		lineageTag: b279799a-60b8-448e-85c2-924bf24b57e4
		summarizeBy: none
		sourceColumn: 'Exclusions (Country Name,YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Extract-09f5e399-b47e-41cd-959a-bc79a6756819' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"},
				            {
				                {"Sample 1", 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, "Sample 12", "Sample 13"},
				                {"Sample 2", 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "Sample 13", "Sample 14"}
				            }
				        )
				    otherwise
				        #table({"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date (year)"}, {"F: Deposit interest rate (%)", "Deposit interest rate (%)"}, {"F: GDP (curr $)", "GDP (curr $)"}, {"F: GDP per capita (curr $)", "GDP per capita (curr $)"}, {"F: Lending interest rate (%)", "Lending interest rate (%)"}, {"H: Health exp (% GDP)", "Health exp (% GDP)"}, {"H: Health exp/cap (curr $)", "Health exp/cap (curr $)"}, {"H: Life exp (years)", "Life exp (years)"}, {"P: Population (count)", "Population (count)"}}),
				    #"Added Action (Country Name)" = Table.AddColumn(#"Renamed Columns", "Action (Country Name)", each Text.From([#"Country / Region"]), type text),
				    #"Added Action (Date (year))" = Table.AddColumn(#"Added Action (Country Name)", "Action (Date (year))", each Text.From([#"Date"]), type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Action (Date (year))", "Action (Region)", each Text.From([#"Region"]), type text),
				    #"Added Action (YEAR(Date (year)))" = Table.AddColumn(#"Added Action (Region)", "Action (YEAR(Date (year)))", each Text.From(Date.Year([#"Date"])), type text),
				    #"Added Exclusions (Country Name,YEAR(Date (year)))" = Table.AddColumn(#"Added Action (YEAR(Date (year)))", "Exclusions (Country Name,YEAR(Date (year)))", each Text.From([#"Country / Region"]) & " | " & Text.From(Date.Year([#"Date"])), type text),
				    Result = #"Added Exclusions (Country Name,YEAR(Date (year)))"
				in
				    Result

	annotation PBI_ResultType = Table

