table Extract
	lineageTag: bee96717-85fd-477a-9663-e54cecf7045d
	description: Contains 18 columns and 4 measures: Country / Region, Date, F: Deposit interest rate (%), F: GDP (curr $), F: GDP per capita (curr $), F: Lending interest rate (%), H: Health exp (% GDP), H: Health exp/cap (curr $), ... (18 columns total).

	measure 'GDP % of Total' = AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]), ALL('Extract'))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: AVG([F: GDP per capita (curr $)]) / TOTAL(AVG([F: GDP per capita (curr $)])) | DAX: AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]), ALL('Extract'...
		lineageTag: ca00e03b-91bc-4dda-97df-9d4ef64b3a21

	measure 'GDP per capita (weighted)' = SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([F: GDP (curr $)]) / SUM([P: Population (count)]) | DAX: SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])
		lineageTag: 233bcf3d-3352-4abd-b49d-1d7d307e4c64

	measure 'Rate spread (difference)' = AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: AVG([F: Lending interest rate (%)])-AVG([F: Deposit interest rate (%)]) | DAX: AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])
		lineageTag: 86125bbb-6886-47e6-83ae-40cc8c32d68c

	measure '[Number of Records]' = 1
		displayFolder: Measures
		description: Migrated from Tableau: 1 | DAX: 1
		lineageTag: d601d653-9a95-4bc2-b772-c59328b6f8a3

	column 'Country / Region'
		dataType: string
		lineageTag: 0bfcfe89-cb2c-4276-9410-066c0af9b1eb
		summarizeBy: none
		sourceColumn: 'Country / Region'
		dataCategory: Country
		description: String column. categorized as Country.

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3e2d8c49-9069-4c81-99ea-1c603b124276
		summarizeBy: none
		sourceColumn: Date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column 'F: Deposit interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: e50f1ca3-5eeb-4240-9789-c0cc5860c6a7
		summarizeBy: sum
		sourceColumn: 'F: Deposit interest rate (%)'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'F: GDP (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.00B;("$"#,#0,,.00B)
		lineageTag: 38ad149f-2121-45fd-9c7a-0795a525fafc
		summarizeBy: sum
		sourceColumn: 'F: GDP (curr $)'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'F: GDP per capita (curr $)'
		dataType: double
		formatString: c"$"#,#0,.0K;("$"#,#0,.0K)
		lineageTag: 2d0699ba-d708-4873-a799-8aa317f8dc06
		summarizeBy: sum
		sourceColumn: 'F: GDP per capita (curr $)'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'F: Lending interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: d1d4ea03-e034-41b7-bd07-23925a546ce8
		summarizeBy: sum
		sourceColumn: 'F: Lending interest rate (%)'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp (% GDP)'
		dataType: double
		formatString: #,0.00
		lineageTag: eca2e653-63fa-41ff-8f5f-95d0655b7478
		summarizeBy: sum
		sourceColumn: 'H: Health exp (% GDP)'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp/cap (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.0B;("$"#,#0,,.0B)
		lineageTag: a22de592-45f7-4d1d-b266-ee8b57df9d88
		summarizeBy: sum
		sourceColumn: 'H: Health exp/cap (curr $)'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'H: Life exp (years)'
		dataType: double
		formatString: n#,0;-#,0
		lineageTag: 8229b4d9-8153-4d09-b09c-ed4093371255
		summarizeBy: sum
		sourceColumn: 'H: Life exp (years)'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: c4e85a8b-3438-4ed1-baf3-c8a658085cfe
		summarizeBy: sum
		sourceColumn: 'Number of Records'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column 'P: Population (count)'
		dataType: double
		formatString: #,0.00
		lineageTag: a5dfdeed-3148-46ed-978a-8cfb9927e126
		summarizeBy: sum
		sourceColumn: 'P: Population (count)'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: ff220e6e-70ba-4d21-856b-7c1e59eaa3d7
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column Subregion
		dataType: string
		lineageTag: 88c7ee39-9ef6-433a-add6-fa69b6a59717
		summarizeBy: none
		sourceColumn: Subregion
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column 'Action (Country Name)'
		dataType: string
		lineageTag: 850e38be-cafd-4fb0-83a8-253997389e8d
		summarizeBy: none
		sourceColumn: 'Action (Country Name)'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Date (year))'
		dataType: string
		lineageTag: e800e56b-87d3-49da-b35f-30f942de4c2d
		summarizeBy: none
		sourceColumn: 'Action (Date (year))'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: 93794e89-fcaa-45ad-b6c3-63607fe6b55b
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Date (year)))'
		dataType: string
		lineageTag: 592dd2ac-b2a2-4718-a438-bd3c281bd97a
		summarizeBy: none
		sourceColumn: 'Action (YEAR(Date (year)))'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Exclusions (Country Name,YEAR(Date (year)))'
		dataType: string
		lineageTag: 0135e8f7-7e28-4a80-a6ed-79fd0fbe4f60
		summarizeBy: none
		sourceColumn: 'Exclusions (Country Name,YEAR(Date (year)))'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Extract-71214218-9ef2-4744-ad9b-5401af571dba' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"},
				            {
				                {"Sample 1", 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, "Sample 12", "Sample 13"},
				                {"Sample 2", 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "Sample 13", "Sample 14"}
				            }
				        )
				    otherwise
				        #table({"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date (year)"}, {"F: Deposit interest rate (%)", "Deposit interest rate (%)"}, {"F: GDP (curr $)", "GDP (curr $)"}, {"F: GDP per capita (curr $)", "GDP per capita (curr $)"}, {"F: Lending interest rate (%)", "Lending interest rate (%)"}, {"H: Health exp (% GDP)", "Health exp (% GDP)"}, {"H: Health exp/cap (curr $)", "Health exp/cap (curr $)"}, {"H: Life exp (years)", "Life exp (years)"}, {"P: Population (count)", "Population (count)"}}),
				    #"Added Action (Country Name)" = Table.AddColumn(#"Renamed Columns", "Action (Country Name)", each Text.From([#"Country / Region"]), type text),
				    #"Added Action (Date (year))" = Table.AddColumn(#"Added Action (Country Name)", "Action (Date (year))", each Text.From([#"Date"]), type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Action (Date (year))", "Action (Region)", each Text.From([#"Region"]), type text),
				    #"Added Action (YEAR(Date (year)))" = Table.AddColumn(#"Added Action (Region)", "Action (YEAR(Date (year)))", each Text.From(Date.Year([#"Date"])), type text),
				    #"Added Exclusions (Country Name,YEAR(Date (year)))" = Table.AddColumn(#"Added Action (YEAR(Date (year)))", "Exclusions (Country Name,YEAR(Date (year)))", each Text.From([#"Country / Region"]) & " | " & Text.From(Date.Year([#"Date"])), type text),
				    Result = #"Added Exclusions (Country Name,YEAR(Date (year)))"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 18 columns and 4 measures: Country / Region, Date, F: Deposit interest rate (%), F: GDP (curr $), F: GDP per capita (curr $), F: Lending interest rate (%), H: Health exp (% GDP), H: Health exp/cap (curr $), ... (18 columns total).

