table Calendar
	lineageTag: 14fd609c-ec70-4428-9a87-8984886ad3a8

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2f1e60f6-081b-45c0-bd3b-c12ac3ed4956
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 13a61177-0d1a-4acd-9417-e078e74ec79d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1f3b4b02-44c8-441c-b78d-edde06eecb51
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 50092557-9e45-40f9-8b48-27ff9b8d1167
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b8f90a68-3bf5-4759-923d-da384f0c5976
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0554b9e1-8ac7-4ee1-ba49-a1600a993c9e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: aaaabaa1-37f2-467c-9b8e-d2033607d4c2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 84a60c90-8ea4-4e45-ac46-bc97ceaafe7e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: bb38896f-78f4-4852-97e8-09bf007c9efe

		level Year
			ordinal: 0
			column: Year
			lineageTag: 078f4c83-f81d-4b95-8ad8-42585203fa0f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 296c4e93-c8ef-4de5-abe7-6c05c4f601c1

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 14ce4823-ff13-4413-9d5b-bcdfb70a360e

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1aca41e7-20c5-4ff0-9e9f-d33b19f0d64b


	partition 'Calendar-8ff6c044-925c-47d8-900c-15101a467d7d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

