table Calendar
	lineageTag: 213d6570-682e-48d0-ba05-6ea1b3d24b2f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8a99a342-3026-4665-9e20-06f60d87b8c2
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 779670ea-cd9e-48dc-b5b6-396113f15cf9
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 41bf69dc-7dc4-462d-b852-a78e9b045838
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5912c500-a741-4a7a-9502-46a8d966b7c4
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 65e04b63-8b44-4fb3-80d3-3c9d5cb40a6c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 5c131116-e4b0-4e7d-8231-c3f63486b6e5
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 42019aaf-56cc-482f-b4b5-b36f6af8253a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2a929202-bb48-4bed-8e0d-fb3d3115c539
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 46583e83-8566-4a94-bcc9-b95db1e01ce0

		level Year
			ordinal: 0
			column: Year
			lineageTag: 21121510-9c45-4b70-a145-086396e98667

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 38cb705b-18c1-4a20-9937-f7fa5e7eaf55

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a40daa38-a5bd-4ab0-9d3e-689dffdbf9cd

		level Day
			ordinal: 3
			column: Day
			lineageTag: 25742f08-0083-4872-ad7a-e6a13fcf39b4


	partition 'Calendar-17e289bd-7f29-4375-9d3c-92da6549b293' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

