table Calendar
	lineageTag: 5c301e80-00cb-4458-9e4e-3720438c98a3

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6ad2ccb5-d820-4de9-84a8-af14bf5e0141
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 986e80ff-2880-4c6b-bdad-c2b28e897256
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ffb77796-d497-4ed5-a201-3558666973a3
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c7544d19-b500-4e08-a304-64c647fccaa8
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d5ef8c64-623b-4bc2-a76e-13c15c627cdc
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f5bdc3fb-cfe5-4065-a496-067af9e5e745
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 18b43e44-17fa-4d35-a99a-8acf60fe2122
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 972305ac-649d-4e48-b20e-37c6b55dc01f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3a790306-e108-4b16-b26c-45755aa46156

		level Year
			ordinal: 0
			column: Year
			lineageTag: cd12ac5e-3648-42c0-8777-99b167eebe24

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 989a669e-acc9-4b39-beb4-31c9cdccf9fd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: dd3fa0d6-5a00-4f24-97fd-4bdad7d59f2a

		level Day
			ordinal: 3
			column: Day
			lineageTag: 75c6e5e4-bac3-4c2e-8a6d-e2b2ca06551d


	partition 'Calendar-122d172a-2c28-47b1-9250-96f34db10df4' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

