table Calendar
	lineageTag: 1667cb8a-d47f-4aa4-9dfc-c77db9165c43

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 7980a8c3-ed80-4f68-9ec4-eaa4be103611
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 31fc9835-88c5-46c3-bc5c-cf2abb6b6b81
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c91012f5-b50c-4926-baf9-45edf638e546
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4a80c0ce-2030-4345-ac17-0fdd79d82725
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4605e2de-c2ba-44db-b087-ccc1d4dd948b
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 94e716d5-2c1c-43c2-9d2f-215c139ac8db
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c363cc4c-274c-4902-9e16-2c8a34c2f15c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2476201d-22d7-44db-be16-d08cd22fa8ab
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 14bda73f-49e3-4be7-9e65-573e1de6b153

		level Year
			ordinal: 0
			column: Year
			lineageTag: 636aaabe-ffb6-4691-aa95-fc3c6f22012e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 2b78f315-191b-4371-b3d9-1bca7d29cc06

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ba797303-831b-4913-884f-78512f022f34

		level Day
			ordinal: 3
			column: Day
			lineageTag: cc2179d4-55ff-4c06-8f7c-06c6eb35b46a


	partition 'Calendar-c8af50e5-919c-442e-b569-b33a6de3d1b0' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

