table Calendar
	lineageTag: 40e17f88-3ba5-40aa-87ca-edf792f82ffd

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ffb5a8d5-3bdb-4001-8602-e0bf3f644317
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1edd1926-a928-4305-ab5b-1cac4f326477
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 49113ca8-2e65-4c83-88e6-293e24f16636
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f8d300b5-e3f3-46f7-bd6f-56ef2d1242f5
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b8611c0a-368b-463c-afeb-0b79be894a20
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: dc1fc953-9e9a-4708-b4e2-d6f11b1180c5
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 6e80fe25-7525-4c15-9931-26a124378d19
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 40487ffc-a9b3-43f2-8935-7add01452493
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6c845ea5-0294-4327-b3c0-c38e03705c87

		level Year
			ordinal: 0
			column: Year
			lineageTag: 2c19011c-a74e-4a35-986c-64cb5b7e36a1

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: a606520e-2bf0-43c8-8ea0-9240180a7c68

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 157a181c-b674-48aa-800d-e4cf6cd34ba3

		level Day
			ordinal: 3
			column: Day
			lineageTag: 290fad3c-61bb-4990-9436-e6cedd1a02ec


	partition 'Calendar-c6ee29a9-65f2-4e50-af48-c8b568d5c885' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

