table Clients
	lineageTag: d52afaf6-e222-4466-ad04-7bbd780834f6

	column client_id
		dataType: int64
		lineageTag: c284b75c-64af-4035-8f9c-42d0377a3b67
		summarizeBy: sum
		sourceColumn: client_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_client
		dataType: string
		lineageTag: b5f87ff5-18ae-4ecf-b5b1-7d10b5914eca
		summarizeBy: none
		sourceColumn: nom_client

		annotation SummarizationSetBy = Automatic

	column prenom_client
		dataType: string
		lineageTag: c63c13c2-13f9-4310-9391-68c3b9d343c2
		summarizeBy: none
		sourceColumn: prenom_client

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: af98e599-3c57-4553-8dff-f6b83abcf729
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 4c0f73b1-abb1-45b4-bbe8-7cb36fd8b6f1
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column type_client
		dataType: string
		lineageTag: 5fa770eb-a825-44e1-af30-ba1945b5b8a4
		summarizeBy: none
		sourceColumn: type_client

		annotation SummarizationSetBy = Automatic

	column date_inscription
		dataType: dateTime
		formatString: General Date
		lineageTag: cb2792b7-1508-4d0f-8c5d-cd37decdc4f9
		summarizeBy: none
		sourceColumn: date_inscription
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Clients-abdfc1b4-83fd-4f6d-9c8a-c0f98b1a0b27' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Clients"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"client_id", "nom_client", "prenom_client", "email", "segment", "type_client", "date_inscription"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"client_id", "ID Client"}, {"nom_client", "Nom du Client"}, {"prenom_client", "Prénom du Client"}, {"email", "Email"}, {"segment", "Segment"}, {"type_client", "Type de Client"}, {"date_inscription", "Date d'Inscription"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns: client_id, nom_client, prenom_client, email, segment, type_client, date_inscription.

