table Clients
	lineageTag: bea1bb47-0931-4b87-bc7c-bc670579cb79
	description: Contains 7 columns: client_id, nom_client, prenom_client, email, segment, type_client, date_inscription.

	column client_id
		dataType: int64
		lineageTag: 68d91267-c153-4247-b54f-3fa2f7761191
		summarizeBy: sum
		sourceColumn: client_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_client
		dataType: string
		lineageTag: 66be0d78-fa22-497f-b7e2-3dfd26b5ece8
		summarizeBy: none
		sourceColumn: nom_client
		description: String column.

		annotation SummarizationSetBy = Automatic

	column prenom_client
		dataType: string
		lineageTag: 942ee802-1cd9-438e-b83e-cbaa1638ae74
		summarizeBy: none
		sourceColumn: prenom_client
		description: String column.

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 80dfd666-f8d0-42d1-a83a-c928676b6f16
		summarizeBy: none
		sourceColumn: email
		description: String column.

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 55265627-ce8a-418d-9573-a81ee3979e54
		summarizeBy: none
		sourceColumn: segment
		description: String column.

		annotation SummarizationSetBy = Automatic

	column type_client
		dataType: string
		lineageTag: eaea96e2-e46c-4d2b-9bc4-1333f22385f1
		summarizeBy: none
		sourceColumn: type_client
		description: String column.

		annotation SummarizationSetBy = Automatic

	column date_inscription
		dataType: dateTime
		formatString: General Date
		lineageTag: 480ea507-ad20-4e60-99a0-221458a9d4f7
		summarizeBy: none
		sourceColumn: date_inscription
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	partition 'Clients-178a3c16-1ef5-4b78-b632-7f1dcdfd4229' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Clients"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"client_id", "nom_client", "prenom_client", "email", "segment", "type_client", "date_inscription"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"client_id", "ID Client"}, {"nom_client", "Nom du Client"}, {"prenom_client", "Prénom du Client"}, {"email", "Email"}, {"segment", "Segment"}, {"type_client", "Type de Client"}, {"date_inscription", "Date d'Inscription"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns: client_id, nom_client, prenom_client, email, segment, type_client, date_inscription.

