table Clients
	lineageTag: 6f8883d8-7313-4a68-a084-3ba14cafa2ef
	description: Contains 7 columns: client_id, nom_client, prenom_client, email, segment, type_client, date_inscription.

	column client_id
		dataType: int64
		lineageTag: 50429d56-bb42-40be-ab38-a237d57e73d5
		summarizeBy: sum
		sourceColumn: client_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_client
		dataType: string
		lineageTag: fe43c2ec-28e6-4287-a7ed-980024f1c09d
		summarizeBy: none
		sourceColumn: nom_client
		description: String column.

		annotation SummarizationSetBy = Automatic

	column prenom_client
		dataType: string
		lineageTag: 7bf9c351-8b97-4967-a3fc-d498b6e50754
		summarizeBy: none
		sourceColumn: prenom_client
		description: String column.

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 24f9a062-7c0d-4fbd-b904-ae06e9a64c71
		summarizeBy: none
		sourceColumn: email
		description: String column.

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 0b3677e3-70fb-4bbc-a33d-af43d368be46
		summarizeBy: none
		sourceColumn: segment
		description: String column.

		annotation SummarizationSetBy = Automatic

	column type_client
		dataType: string
		lineageTag: 12c1ee3c-e8cd-42f2-bff2-3aa7f6959c47
		summarizeBy: none
		sourceColumn: type_client
		description: String column.

		annotation SummarizationSetBy = Automatic

	column date_inscription
		dataType: dateTime
		formatString: General Date
		lineageTag: 538961a8-51ca-43c6-95ac-9a8b044138e3
		summarizeBy: none
		sourceColumn: date_inscription
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	partition 'Clients-a543bcf6-657a-4722-9a18-fb3dfd4f4b64' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Clients"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"client_id", "nom_client", "prenom_client", "email", "segment", "type_client", "date_inscription"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"client_id", "ID Client"}, {"nom_client", "Nom du Client"}, {"prenom_client", "Prénom du Client"}, {"email", "Email"}, {"segment", "Segment"}, {"type_client", "Type de Client"}, {"date_inscription", "Date d'Inscription"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns: client_id, nom_client, prenom_client, email, segment, type_client, date_inscription.

