table Commandes
	lineageTag: 4441bc77-4857-47d9-8314-cc3c85761468

	measure 'Chiffre d''Affaires Brut' = SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 08286ae7-4594-42a3-88b6-ae62b74798a3
		annotation Copilot_Description = Migrated from Tableau: SUM([quantite] * [prix_unitaire]) | DAX: SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire])

	measure 'Chiffre d''Affaires Net' = SUMX('Commandes', IF('Commandes'[statut] <> "Annulée", 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * (1 - 'Commandes'[remise]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: dcf87f50-6961-4f85-9f19-d1013192a3e6
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [statut] != "Annulée" THEN [quantite] * [prix_unitaire] * (1 - [remise]) ELSE 0 END) | DAX: SUMX('Commandes', IF('Commandes'[statut] <> "Annulée", 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * (1 - 'Comman...

	measure 'Marge Brute' = SUMX('Commandes', IF('Commandes'[statut] <> "Annulée", ('Commandes'[quantite] * 'Commandes'[prix_unitaire] * (1 - 'Commandes'[remise])) - ('Commandes'[quantite] * 'Produits'[cout_achat]) - 'Commandes'[frais_port], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 85ab47e1-5e0d-4d07-8a41-23f8507c7c36
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [statut] != "Annulée" THEN ([quantite] * [prix_unitaire] * (1 - [remise])) - ([quantite] * [cout_achat]) - [frais_port] ELSE 0 END) | DAX: SUMX('Commandes', IF('Commandes'[statut] <> "Annulée", ('Commandes'[quantite] * 'Commandes'[prix_unitaire] * (1 - 'Comma...

	measure 'Taux de Marge (%)' = IF(ISBLANK([Marge Brute] / [Chiffre d"Affaires Net]), 0, [Marge Brute] / [Chiffre d"Affaires Net])
		formatString: #,0.00
		displayFolder: Measures
		isHidden
		lineageTag: 44933e82-cb1a-4ce8-b656-0bacc08fca62
		annotation Copilot_Description = Migrated from Tableau: ZN([Calc_Marge] / [Calc_CA_Net]) | DAX: IF(ISBLANK([Marge Brute] / [Chiffre d"Affaires Net]), 0, [Marge Brute] / [Chiffre d"Affaires Net])

	measure 'Montant Remises' = SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * 'Commandes'[remise])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e7f717fc-34e3-4856-ad89-a5ac82506fb7
		annotation Copilot_Description = Migrated from Tableau: SUM([quantite] * [prix_unitaire] * [remise]) | DAX: SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * 'Commandes'[remise])

	measure 'Nombre de Commandes' = DISTINCTCOUNT('Commandes'[commande_id])
		displayFolder: Measures
		lineageTag: 4f3865e2-fce8-4eca-b4cf-fbf15f4a0069
		annotation Copilot_Description = Migrated from Tableau: COUNTD([commande_id]) | DAX: DISTINCTCOUNT('Commandes'[commande_id])

	measure 'Clients Uniques' = DISTINCTCOUNT('Commandes'[client_id])
		displayFolder: Measures
		lineageTag: a1b2b75d-79f2-45d7-b67e-fe48f4f882a8
		annotation Copilot_Description = Migrated from Tableau: COUNTD([client_id]) | DAX: DISTINCTCOUNT('Commandes'[client_id])

	measure 'Panier Moyen' = [Chiffre d'Affaires Net] / [Nombre de Commandes]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 00bda470-bdbd-4754-b933-0e732781ef5c
		annotation Copilot_Description = Migrated from Tableau: [Calc_CA_Net] / [Calc_NbCommandes] | DAX: [Chiffre d'Affaires Net] / [Nombre de Commandes]

	measure 'CA par Client' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), ALLEXCEPT('Commandes', 'Commandes'[client_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 22b7255b-7514-4f5b-9c94-3a4de021c8e1
		annotation Copilot_Description = Migrated from Tableau: {FIXED [client_id] : SUM([quantite] * [prix_unitaire])} | DAX: CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), ALLEXCEPT('Commandes', 'Commandes'[clie...

	measure 'CA Régional par Catégorie' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Commandes'[region]), REMOVEFILTERS('Produits'[categorie]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e4d09c84-358c-4bb9-96ac-4ae79cbc28d4
		annotation Copilot_Description = Migrated from Tableau: {FIXED [region], [categorie] : SUM([quantite] * [prix_unitaire])} | DAX: CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Commandes'[region]), REM...

	measure 'CA hors Produit' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Produits'[nom_produit]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1232978e-b723-4588-8626-713fc2887d70
		annotation Copilot_Description = Migrated from Tableau: {EXCLUDE [nom_produit] : SUM([quantite] * [prix_unitaire])} | DAX: CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Produits'[nom_produit]))

	measure 'Classification Client' = IF([CA par Client] > 50000, "Platine", IF([CA par Client] > 20000, "||", IF([CA par Client] > 5000, "Argent", "Bronze")))
		displayFolder: Dimensions
		lineageTag: 59fbce34-1cb5-4f5a-989e-8b05f6758536
		annotation Copilot_Description = Migrated from Tableau: IF [Calc_CAParClient] > 50000 THEN "Platine" ELSEIF [Calc_CAParClient] > 20000 THEN "Or" ELSEIF [Calc_CAParClient] > 5000 THEN "Argent" ELSE "Bronze" END | DAX: IF([CA par Client] > 50000, "Platine", IF([CA par Client] > 20000, "||", IF([CA par Client] > 5000, "Argent", "Bronze"))...

	measure 'Cumul Mobile CA' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), FILTER(ALLSELECTED('Commandes'), TRUE())) /* RUNNING_SUM: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9b8235d0-0c8a-444f-89bd-c3924097a256
		annotation Copilot_Description = Migrated from Tableau: RUNNING_SUM(SUM([quantite] * [prix_unitaire])) | DAX: CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), FILTER(ALLSELECTED('Commandes'), TRUE()...

	measure 'Moyenne Mobile 3M' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), WINDOW(-2, REL, 0, REL, ORDERBY('Commandes'[commande_id], ASC)), ALL('Commandes')) /* WINDOW.AVG: frame 'Commandes'[-2,0] */
		formatString: #,0.00
		displayFolder: Measures
		isHidden
		lineageTag: 556ed77d-30b3-4e45-a55f-df7ca040f32f
		annotation Copilot_Description = Migrated from Tableau: WINDOW_AVG(SUM([quantite] * [prix_unitaire]), -2, 0) | DAX: CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), WINDOW(-2, REL, 0, REL, ORDERBY('Comman...

	measure 'Classement CA' = RANKX(ALL('Commandes'), SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]))
		displayFolder: Measures
		lineageTag: 0263272b-74d1-4b2f-9b2d-3a9833f5bfbb
		annotation Copilot_Description = Migrated from Tableau: RANK(SUM([quantite] * [prix_unitaire])) | DAX: RANKX(ALL('Commandes'), SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]))

	measure 'CA Année en Cours' = CALCULATE(SUMX('Commandes', IF(YEAR('Commandes'[date_commande]) = YEAR(TODAY()), 'Commandes'[quantite] * 'Commandes'[prix_unitaire], 0)), ALL('Commandes'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 829bfd1f-abe2-4645-8f01-75df4ad3734b
		annotation Copilot_Description = Migrated from Tableau: {FIXED : SUM(IF YEAR([date_commande]) = YEAR(TODAY()) THEN [quantite] * [prix_unitaire] ELSE 0 END)} | DAX: CALCULATE(SUMX('Commandes', IF(YEAR('Commandes'[date_commande]) = YEAR(TODAY()), 'Commandes'[quantite] * 'Commandes'[pri...

	measure 'Période d''Analyse' = "Année"
		lineageTag: ac658527-e352-4fbc-8565-b0fd8031b629
		annotation Copilot_Description = DAX: "Année"

	column commande_id
		dataType: int64
		lineageTag: b4a013d1-fb82-4a8e-990a-f95d1fa448f5
		summarizeBy: sum
		sourceColumn: commande_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column date_commande
		dataType: dateTime
		formatString: General Date
		lineageTag: ced8828b-cc15-418d-bfc2-8e0361f6f9a4
		summarizeBy: none
		sourceColumn: date_commande
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column date_livraison
		dataType: dateTime
		formatString: General Date
		lineageTag: 53d45c88-efa1-4643-80a3-fddf6a8f0b3d
		summarizeBy: none
		sourceColumn: date_livraison
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: int64
		lineageTag: bf1e9d71-7559-4a19-b292-87591b06c6e5
		summarizeBy: sum
		sourceColumn: client_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column produit_id
		dataType: int64
		lineageTag: 80623c82-b2cb-44cd-9dc5-14b7d6bbc778
		summarizeBy: sum
		sourceColumn: produit_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: c6a68fe1-dcbe-42fe-8454-4e06e236b089
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column departement
		dataType: string
		lineageTag: 3c35244b-54ad-4725-8d4e-3669f943cd45
		summarizeBy: none
		sourceColumn: departement

		annotation SummarizationSetBy = Automatic

	column ville
		dataType: string
		lineageTag: 58d6d0e9-cb56-4272-a5dd-5f026163d1c7
		summarizeBy: none
		sourceColumn: ville
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column code_postal
		dataType: string
		lineageTag: 616f16f4-db4b-467c-84ca-d282cbc2e9d5
		summarizeBy: none
		sourceColumn: code_postal
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column quantite
		dataType: double
		formatString: #,0.00
		lineageTag: 99da92cb-a87c-4db5-8eba-b03a5fa43585
		summarizeBy: sum
		sourceColumn: quantite

		annotation SummarizationSetBy = Automatic

	column prix_unitaire
		dataType: double
		formatString: #,0.00
		lineageTag: a5398939-967d-4578-9e81-3247fe1f3652
		summarizeBy: sum
		sourceColumn: prix_unitaire

		annotation SummarizationSetBy = Automatic

	column remise
		dataType: double
		formatString: #,0.00
		lineageTag: 80461260-c6be-43f7-b92d-b79ca6ace9eb
		summarizeBy: sum
		sourceColumn: remise

		annotation SummarizationSetBy = Automatic

	column frais_port
		dataType: double
		formatString: #,0.00
		lineageTag: d7591fef-824e-4a84-a373-7cd406fa60e9
		summarizeBy: sum
		sourceColumn: frais_port

		annotation SummarizationSetBy = Automatic

	column mode_paiement
		dataType: string
		lineageTag: a77b6966-83ea-4c01-8257-d56d7db06214
		summarizeBy: none
		sourceColumn: mode_paiement

		annotation SummarizationSetBy = Automatic

	column statut
		dataType: string
		lineageTag: dc99a923-1743-4571-9b2e-c011a64367cb
		summarizeBy: none
		sourceColumn: statut

		annotation SummarizationSetBy = Automatic

	column commercial
		dataType: string
		lineageTag: 7616dc81-08e1-4604-8443-c40b7598a24e
		summarizeBy: none
		sourceColumn: commercial

		annotation SummarizationSetBy = Automatic

	column 'Délai de Livraison'
		dataType: int64
		lineageTag: 0690f8a2-6278-4ad4-8416-ebd88a61b5a9
		summarizeBy: none
		sourceColumn: 'Délai de Livraison'

		annotation SummarizationSetBy = Automatic

	column 'Ancienneté Client' = DATEDIFF(LOOKUPVALUE(Clients[date_inscription], Clients[client_id], Commandes[client_id]), TODAY(), DAY)
		dataType: int64
		lineageTag: 20ae5c0d-83f7-491d-b1ac-c1725d8f170e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Nom Complet' = LOOKUPVALUE(Clients[prenom_client], Clients[client_id], Commandes[client_id]) & " " & UPPER(LOOKUPVALUE(Clients[nom_client], Clients[client_id], Commandes[client_id]))
		dataType: string
		lineageTag: efa6597d-1bde-4678-926f-bb662ff69a0f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Localisation
		dataType: string
		lineageTag: 33a21cd7-5ebd-47b0-b2b8-b6403cf1a5db
		summarizeBy: none
		sourceColumn: Localisation

		annotation SummarizationSetBy = Automatic

	column 'Catégorie de Remise' = IF(ISBLANK('Commandes'[remise]) || 'Commandes'[remise] = 0, "Aucune Remise", IF('Commandes'[remise] < 0.1, "Faible (<10%)", IF('Commandes'[remise] < 0.25, "Moyenne (10-25%)", "Forte (>25%)")))
		dataType: string
		lineageTag: c5d88233-1f43-4dd7-8a83-2545facc8661
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Trimestre = "T" & FORMAT(QUARTER('Commandes'[date_commande]), "0") & " " & FORMAT(YEAR('Commandes'[date_commande]), "0")
		dataType: string
		lineageTag: af5ca21c-c853-4d17-ac8f-e278ac344997
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Commandes-a7aa0a88-52ed-4993-a622-37f93c45e8f9' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Commandes"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"commande_id", "date_commande", "date_livraison", "client_id", "produit_id", "region", "departement", "ville", "code_postal", "quantite", "prix_unitaire", "remise", "frais_port", "mode_paiement", "statut", "commercial"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"commande_id", "N° Commande"}, {"date_commande", "Date de Commande"}, {"date_livraison", "Date de Livraison"}, {"client_id", "ID Client"}, {"produit_id", "ID Produit"}, {"region", "Région"}, {"departement", "Département"}, {"ville", "Ville"}, {"code_postal", "Code Postal"}, {"quantite", "Quantité"}, {"prix_unitaire", "Prix Unitaire"}, {"remise", "Remise"}, {"frais_port", "Frais de Port"}, {"mode_paiement", "Mode de Paiement"}, {"statut", "Statut"}, {"commercial", "Commercial"}}),
				    #"Added Délai de Livraison" = Table.AddColumn(#"Renamed Columns", "Délai de Livraison", each Duration.Days([date_livraison] - [date_commande]), Int64.Type),
				    #"Added Localisation" = Table.AddColumn(#"Added Délai de Livraison", "Localisation", each [ville] & " (" & [departement] & ") - " & [region], type text),
				    Result = #"Added Localisation"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 22 columns and 17 measures: commande_id, date_commande, date_livraison, client_id, produit_id, region, departement, ville, ... (22 columns total).

