table Commandes
	lineageTag: 4fe38ed2-6f12-443b-92ec-c756f483ba49

	measure 'Chiffre d''Affaires Brut' = SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: bdd903f5-976a-42a7-b609-cea4ba2a0640

	measure 'Chiffre d''Affaires Net' = SUMX('Commandes', IF('Commandes'[statut] <> "Annulée", 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * (1 - 'Commandes'[remise]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 392d08c3-c81b-4b01-b5ae-6378cab1ae3d

	measure 'Marge Brute' = SUMX('Commandes', IF('Commandes'[statut] <> "Annulée", ('Commandes'[quantite] * 'Commandes'[prix_unitaire] * (1 - 'Commandes'[remise])) - ('Commandes'[quantite] * 'Produits'[cout_achat]) - 'Commandes'[frais_port], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 70b44034-1a83-4f67-a50e-ff9fce2388ea

	measure 'Taux de Marge (%)' = IF(ISBLANK([Marge Brute] / [Chiffre d"Affaires Net]), 0, [Marge Brute] / [Chiffre d"Affaires Net])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1e45a034-6ba6-4dd0-84e1-f0254b549f6c

	measure 'Montant Remises' = SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * 'Commandes'[remise])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f96faa14-95b1-4bec-be69-5d4c747d263e

	measure 'Nombre de Commandes' = DISTINCTCOUNT('Commandes'[commande_id])
		displayFolder: Measures
		lineageTag: 71519681-5906-4549-86a8-e9cc53ed5954

	measure 'Clients Uniques' = DISTINCTCOUNT('Commandes'[client_id])
		displayFolder: Measures
		lineageTag: 53faba88-6e45-44d7-9eba-17fef79a8b40

	measure 'Panier Moyen' = [Chiffre d'Affaires Net] / [Nombre de Commandes]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2c359eee-19c0-4d7b-9998-0d83f14936ec

	measure 'CA par Client' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), ALLEXCEPT('Commandes', 'Commandes'[client_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 091b8d4d-39bd-4ccc-ae0f-019f7c833a73

	measure 'CA Régional par Catégorie' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Commandes'[region]), REMOVEFILTERS('Produits'[categorie]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7064019b-a41d-47fd-82f3-5eb3c7d65d5a

	measure 'CA hors Produit' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Produits'[nom_produit]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8214d5fe-50f7-4806-9387-4b89e91adb84

	measure 'Classification Client' = IF([CA par Client] > 50000, "Platine", IF([CA par Client] > 20000, "||", IF([CA par Client] > 5000, "Argent", "Bronze")))
		displayFolder: Dimensions
		lineageTag: 8195abe3-c390-483b-9288-b1dbd58cd831

	measure 'Cumul Mobile CA' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), FILTER(ALLSELECTED('Commandes'), TRUE())) /* RUNNING_SUM: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 372e6b27-3461-4a94-acc8-c3934b2f143e

	measure 'Moyenne Mobile 3M' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), WINDOW(-2, REL, 0, REL, ORDERBY('Commandes'[commande_id], ASC)), ALL('Commandes')) /* WINDOW.AVG: frame 'Commandes'[-2,0] */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ce6e5812-cd4b-4de1-b36e-7ce1df15b451

	measure 'Classement CA' = RANKX(ALL('Commandes'), SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]))
		displayFolder: Measures
		lineageTag: 533bb63e-7b03-46c3-a6ff-16f3e65deadb

	measure 'CA Année en Cours' = CALCULATE(SUMX('Commandes', IF(YEAR('Commandes'[date_commande]) = YEAR(TODAY()), 'Commandes'[quantite] * 'Commandes'[prix_unitaire], 0)), ALL('Commandes'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8430dfc4-b92f-4090-840b-89688ffbf7d9

	measure 'Période d''Analyse' = "Année"
		lineageTag: 10b27c69-0a55-44a0-94c0-a6582fe44b7a

	column commande_id
		dataType: int64
		lineageTag: 007e3d90-4995-465c-87e7-8912ed2f9129
		summarizeBy: sum
		sourceColumn: commande_id

		annotation SummarizationSetBy = Automatic

	column date_commande
		dataType: dateTime
		formatString: General Date
		lineageTag: d5d7274f-75b0-4238-9a11-0439626b4fb8
		summarizeBy: none
		sourceColumn: date_commande
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column date_livraison
		dataType: dateTime
		formatString: General Date
		lineageTag: edd5d95d-47e8-448e-8538-ea4696370c77
		summarizeBy: none
		sourceColumn: date_livraison
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: int64
		lineageTag: bb1706c7-efbb-45a5-9f0d-42b5d0fb371f
		summarizeBy: sum
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column produit_id
		dataType: int64
		lineageTag: 3ee5694a-8728-495e-bbd7-aeae8c3fd277
		summarizeBy: sum
		sourceColumn: produit_id

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 6510eca5-2efa-495c-9bb4-de710e643c28
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column departement
		dataType: string
		lineageTag: ad41bed6-9d8a-4405-8de9-e4a7b32f87db
		summarizeBy: none
		sourceColumn: departement

		annotation SummarizationSetBy = Automatic

	column ville
		dataType: string
		lineageTag: 7c93d5eb-3ca4-48c9-a0c0-1a2902f88ede
		summarizeBy: none
		sourceColumn: ville
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column code_postal
		dataType: string
		lineageTag: ddd76285-ef2b-419b-a9d6-2f834c9f221c
		summarizeBy: none
		sourceColumn: code_postal
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column quantite
		dataType: double
		formatString: #,0.00
		lineageTag: 772c997e-2269-466e-a888-a64d9606fcb4
		summarizeBy: sum
		sourceColumn: quantite

		annotation SummarizationSetBy = Automatic

	column prix_unitaire
		dataType: double
		formatString: #,0.00
		lineageTag: c0a297dc-5c34-4704-a0d7-6e183a81e6ca
		summarizeBy: sum
		sourceColumn: prix_unitaire

		annotation SummarizationSetBy = Automatic

	column remise
		dataType: double
		formatString: #,0.00
		lineageTag: 68ebe3ca-2e3f-4c20-a0c8-48f84eff9e1c
		summarizeBy: sum
		sourceColumn: remise

		annotation SummarizationSetBy = Automatic

	column frais_port
		dataType: double
		formatString: #,0.00
		lineageTag: 54841257-5e56-4a16-bf0e-414503b9d6ca
		summarizeBy: sum
		sourceColumn: frais_port

		annotation SummarizationSetBy = Automatic

	column mode_paiement
		dataType: string
		lineageTag: a69725ee-7a84-48d3-82aa-f03bf137c901
		summarizeBy: none
		sourceColumn: mode_paiement

		annotation SummarizationSetBy = Automatic

	column statut
		dataType: string
		lineageTag: 65892ef0-f50d-402a-9210-31d759bebf45
		summarizeBy: none
		sourceColumn: statut

		annotation SummarizationSetBy = Automatic

	column commercial
		dataType: string
		lineageTag: c7a8fbd5-41b4-42d6-a54a-f4ca8d9a0893
		summarizeBy: none
		sourceColumn: commercial

		annotation SummarizationSetBy = Automatic

	column 'Délai de Livraison'
		dataType: int64
		lineageTag: fe5effb1-63a1-48a0-86be-ed0e3c083296
		summarizeBy: none
		sourceColumn: 'Délai de Livraison'

		annotation SummarizationSetBy = Automatic

	column 'Ancienneté Client' = DATEDIFF(LOOKUPVALUE(Clients[date_inscription], Clients[client_id], Commandes[client_id]), TODAY(), DAY)
		dataType: int64
		lineageTag: 1f90b925-2615-4802-86b2-f4a4c217ef18
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Nom Complet' = LOOKUPVALUE(Clients[prenom_client], Clients[client_id], Commandes[client_id]) & " " & UPPER(LOOKUPVALUE(Clients[nom_client], Clients[client_id], Commandes[client_id]))
		dataType: string
		lineageTag: 0ef89b8a-a485-4898-bd1c-cd709ebefdcc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Localisation
		dataType: string
		lineageTag: d0b9132e-aa5e-4e29-a2cc-4b961732afd8
		summarizeBy: none
		sourceColumn: Localisation

		annotation SummarizationSetBy = Automatic

	column 'Catégorie de Remise' = IF(ISBLANK('Commandes'[remise]) || 'Commandes'[remise] = 0, "Aucune Remise", IF('Commandes'[remise] < 0.1, "Faible (<10%)", IF('Commandes'[remise] < 0.25, "Moyenne (10-25%)", "Forte (>25%)")))
		dataType: string
		lineageTag: 105722c3-deb4-468d-a738-a2b2e148e937
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Trimestre = "T" & FORMAT(QUARTER('Commandes'[date_commande]), "0") & " " & FORMAT(YEAR('Commandes'[date_commande]), "0")
		dataType: string
		lineageTag: 1499e221-d63f-4eee-8592-9de14b0510e8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Commandes-65bd3446-d982-435a-bcb9-426e90d2e786' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Commandes"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"commande_id", "date_commande", "date_livraison", "client_id", "produit_id", "region", "departement", "ville", "code_postal", "quantite", "prix_unitaire", "remise", "frais_port", "mode_paiement", "statut", "commercial"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"commande_id", "N° Commande"}, {"date_commande", "Date de Commande"}, {"date_livraison", "Date de Livraison"}, {"client_id", "ID Client"}, {"produit_id", "ID Produit"}, {"region", "Région"}, {"departement", "Département"}, {"ville", "Ville"}, {"code_postal", "Code Postal"}, {"quantite", "Quantité"}, {"prix_unitaire", "Prix Unitaire"}, {"remise", "Remise"}, {"frais_port", "Frais de Port"}, {"mode_paiement", "Mode de Paiement"}, {"statut", "Statut"}, {"commercial", "Commercial"}}),
				    #"Added Délai de Livraison" = Table.AddColumn(#"Renamed Columns", "Délai de Livraison", each Duration.Days([date_livraison] - [date_commande]), Int64.Type),
				    #"Added Localisation" = Table.AddColumn(#"Added Délai de Livraison", "Localisation", each [ville] & " (" & [departement] & ") - " & [region], type text),
				    Result = #"Added Localisation"
				in
				    Result

	annotation PBI_ResultType = Table

