table 'Objectif Marge'
	lineageTag: c1cf6ea6-0b7e-4d3e-878f-8bff706bbd7c

	measure 'Objectif Marge' = SELECTEDVALUE('Objectif Marge'[Value], 0.15)
		lineageTag: f05056fe-9956-447a-8156-bdc4a53be671

	column Value
		dataType: double
		lineageTag: 46963222-8191-4d5a-be00-3296596747a9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Objectif Marge-440569bb-5914-4c29-9385-83d7900bfc8d' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

