table 'Objectif Marge'
	lineageTag: 498b5fbe-fe4c-444a-a83b-0825d5ecb4c0

	measure 'Objectif Marge' = SELECTEDVALUE('Objectif Marge'[Value], 0.15)
		lineageTag: 7c33272d-8d1b-48d6-9099-9eaede5209d5
		annotation Copilot_Description = DAX: SELECTEDVALUE('Objectif Marge'[Value], 0.15)

	column Value
		dataType: double
		lineageTag: 0b3348a8-d74f-479d-8d70-d0a88a56a904
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Objectif Marge-0b1eb8d8-b8f2-4ec0-a9d2-a0300104e643' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

