table 'Objectif Marge'
	lineageTag: 664b9c55-d906-4be8-a17c-b7e6368213b3
	description: Contains 1 columns and 1 measures: Value.

	measure 'Objectif Marge' = SELECTEDVALUE('Objectif Marge'[Value], 0.15)
		description: DAX: SELECTEDVALUE('Objectif Marge'[Value], 0.15)
		lineageTag: 543f0cba-0fcb-4346-8698-c99bdb6e5ba5

	column Value
		dataType: double
		lineageTag: aed24828-ac8e-495f-9f1e-8360b411d353
		summarizeBy: none
		sourceColumn: Value
		description: Double column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Objectif Marge-73b107f4-a18a-4baa-92b5-147c214558ea' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

