table 'Objectif Marge'
	lineageTag: 64ef4350-b49c-4561-bc55-5de3cc563926

	measure 'Objectif Marge' = SELECTEDVALUE('Objectif Marge'[Value], 0.15)
		lineageTag: 0f20925e-9b16-4e4a-ad73-e2510c5c8803
		annotation Copilot_Description = DAX: SELECTEDVALUE('Objectif Marge'[Value], 0.15)

	column Value
		dataType: double
		lineageTag: f5992483-f033-4933-a9d2-be464a08fd80
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Objectif Marge-cf7f74d0-3d35-4acd-b541-d6fe04815d49' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

