table Produits
	lineageTag: 97cd91ad-0b38-4728-a330-6f9db2c696e0
	description: Contains 6 columns: produit_id, nom_produit, categorie, sous_categorie, marque, cout_achat.

	column produit_id
		dataType: int64
		lineageTag: c29a0684-3e6e-4b3a-8956-90eaf4e3b317
		summarizeBy: sum
		sourceColumn: produit_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_produit
		dataType: string
		lineageTag: 86787bae-b241-4932-8d6d-a9172bf78de1
		summarizeBy: none
		sourceColumn: nom_produit
		description: String column.

		annotation SummarizationSetBy = Automatic

	column categorie
		dataType: string
		lineageTag: d9082248-a79a-431f-bbb1-57741343ce47
		summarizeBy: none
		sourceColumn: categorie
		description: String column.

		annotation SummarizationSetBy = Automatic

	column sous_categorie
		dataType: string
		lineageTag: 5f6b8551-708c-4677-9e52-5c427482063c
		summarizeBy: none
		sourceColumn: sous_categorie
		description: String column.

		annotation SummarizationSetBy = Automatic

	column marque
		dataType: string
		lineageTag: 3afd559f-d546-4a38-8b7c-98ca232d13a6
		summarizeBy: none
		sourceColumn: marque
		description: String column.

		annotation SummarizationSetBy = Automatic

	column cout_achat
		dataType: double
		formatString: #,0.00
		lineageTag: 1a7209a9-c36a-45af-8071-cbf6225b900b
		summarizeBy: sum
		sourceColumn: cout_achat
		description: Double column.

		annotation SummarizationSetBy = Automatic

	partition 'Produits-d7bc43c1-3e44-41f1-a51c-92cdc890d9e2' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Produits"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"produit_id", "nom_produit", "categorie", "sous_categorie", "marque", "cout_achat"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"produit_id", "ID Produit"}, {"nom_produit", "Nom du Produit"}, {"categorie", "Catégorie"}, {"sous_categorie", "Sous-Catégorie"}, {"marque", "Marque"}, {"cout_achat", "Coût d'Achat"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 6 columns: produit_id, nom_produit, categorie, sous_categorie, marque, cout_achat.

