table Produits
	lineageTag: a76094a4-c2be-4535-acce-e1c1280684b9

	column produit_id
		dataType: int64
		lineageTag: 324d45aa-5d8f-4c22-8f94-ad1ecb062160
		summarizeBy: sum
		sourceColumn: produit_id

		annotation SummarizationSetBy = Automatic

	column nom_produit
		dataType: string
		lineageTag: fdfc3baa-b18a-424c-8041-0bf1e7e31fb0
		summarizeBy: none
		sourceColumn: nom_produit

		annotation SummarizationSetBy = Automatic

	column categorie
		dataType: string
		lineageTag: faac0763-affa-4639-921d-f2a7f61c892e
		summarizeBy: none
		sourceColumn: categorie

		annotation SummarizationSetBy = Automatic

	column sous_categorie
		dataType: string
		lineageTag: 96841969-09b0-453b-93fd-81755f720310
		summarizeBy: none
		sourceColumn: sous_categorie

		annotation SummarizationSetBy = Automatic

	column marque
		dataType: string
		lineageTag: 52b7445f-d725-4efc-a40a-3f0ea1e3fbbb
		summarizeBy: none
		sourceColumn: marque

		annotation SummarizationSetBy = Automatic

	column cout_achat
		dataType: double
		formatString: #,0.00
		lineageTag: a45ca606-1aff-4217-b620-959475d035b2
		summarizeBy: sum
		sourceColumn: cout_achat

		annotation SummarizationSetBy = Automatic

	partition 'Produits-41e09dd9-4794-42e1-9508-e88bb76a02a7' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Produits"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"produit_id", "nom_produit", "categorie", "sous_categorie", "marque", "cout_achat"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"produit_id", "ID Produit"}, {"nom_produit", "Nom du Produit"}, {"categorie", "Catégorie"}, {"sous_categorie", "Sous-Catégorie"}, {"marque", "Marque"}, {"cout_achat", "Coût d'Achat"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

