table Produits
	lineageTag: fc9f810e-962f-44c5-bfc9-5138beb59324
	description: Contains 6 columns: produit_id, nom_produit, categorie, sous_categorie, marque, cout_achat.

	column produit_id
		dataType: int64
		lineageTag: 32e1a96f-29c7-4563-a8ca-fa90a391d48a
		summarizeBy: sum
		sourceColumn: produit_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_produit
		dataType: string
		lineageTag: 383a01e8-d0cf-406f-813b-f4149387be2f
		summarizeBy: none
		sourceColumn: nom_produit
		description: String column.

		annotation SummarizationSetBy = Automatic

	column categorie
		dataType: string
		lineageTag: 5b3289e3-753f-4d94-927d-416df4d3c56b
		summarizeBy: none
		sourceColumn: categorie
		description: String column.

		annotation SummarizationSetBy = Automatic

	column sous_categorie
		dataType: string
		lineageTag: 8a6dafe2-89eb-4899-a48d-6f0dbd5eae06
		summarizeBy: none
		sourceColumn: sous_categorie
		description: String column.

		annotation SummarizationSetBy = Automatic

	column marque
		dataType: string
		lineageTag: a5ed10d7-9c54-487b-852a-985943480212
		summarizeBy: none
		sourceColumn: marque
		description: String column.

		annotation SummarizationSetBy = Automatic

	column cout_achat
		dataType: double
		formatString: #,0.00
		lineageTag: 194a64f4-3d93-40f7-97fc-dfa6d766d6dc
		summarizeBy: sum
		sourceColumn: cout_achat
		description: Double column.

		annotation SummarizationSetBy = Automatic

	partition 'Produits-bfa89445-6e83-4a17-b7ae-681f64641f61' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Produits"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"produit_id", "nom_produit", "categorie", "sous_categorie", "marque", "cout_achat"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"produit_id", "ID Produit"}, {"nom_produit", "Nom du Produit"}, {"categorie", "Catégorie"}, {"sous_categorie", "Sous-Catégorie"}, {"marque", "Marque"}, {"cout_achat", "Coût d'Achat"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 6 columns: produit_id, nom_produit, categorie, sous_categorie, marque, cout_achat.

