table Produits
	lineageTag: f7b83e26-02ee-4f3e-9e5b-1582121e10d6

	column produit_id
		dataType: int64
		lineageTag: 442741ab-de29-4493-ae43-fe2a847909c2
		summarizeBy: sum
		sourceColumn: produit_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_produit
		dataType: string
		lineageTag: 1dccfcfe-2594-4eda-992a-ce67f1f28bda
		summarizeBy: none
		sourceColumn: nom_produit

		annotation SummarizationSetBy = Automatic

	column categorie
		dataType: string
		lineageTag: 80151852-6abf-4e9c-8c4b-c72769440abe
		summarizeBy: none
		sourceColumn: categorie

		annotation SummarizationSetBy = Automatic

	column sous_categorie
		dataType: string
		lineageTag: 8bbd96a4-f5c8-4310-991e-0f62da40d783
		summarizeBy: none
		sourceColumn: sous_categorie

		annotation SummarizationSetBy = Automatic

	column marque
		dataType: string
		lineageTag: 44005a09-4c36-4d41-a3a0-c9903003f981
		summarizeBy: none
		sourceColumn: marque

		annotation SummarizationSetBy = Automatic

	column cout_achat
		dataType: double
		formatString: #,0.00
		lineageTag: fb601b1d-0c62-4b95-890d-253211183cc4
		summarizeBy: sum
		sourceColumn: cout_achat

		annotation SummarizationSetBy = Automatic

	partition 'Produits-d65e9c46-4a94-40cc-bfcd-6b9803ee2c33' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Produits"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"produit_id", "nom_produit", "categorie", "sous_categorie", "marque", "cout_achat"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"produit_id", "ID Produit"}, {"nom_produit", "Nom du Produit"}, {"categorie", "Catégorie"}, {"sous_categorie", "Sous-Catégorie"}, {"marque", "Marque"}, {"cout_achat", "Coût d'Achat"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 6 columns: produit_id, nom_produit, categorie, sous_categorie, marque, cout_achat.

