table 'Top N Produits'
	lineageTag: dbfbb974-839b-4132-852b-73ee064d7aa0
	description: Contains 1 columns and 1 measures: Value.

	measure 'Top N Produits' = SELECTEDVALUE('Top N Produits'[Value], 10)
		description: DAX: SELECTEDVALUE('Top N Produits'[Value], 10)
		lineageTag: 99ebab5d-0924-4552-bbf5-89e5cee86b0d

	column Value
		dataType: int64
		lineageTag: e52fb832-84e4-474b-a9b9-48c2f94fff98
		summarizeBy: none
		sourceColumn: Value
		description: Int64 column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Produits-5abebcae-4dd2-4481-896c-f5e69e6368a7' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

