table 'Top N Produits'
	lineageTag: 7f76a7ca-0932-4e53-b2af-a7996e3a015d

	measure 'Top N Produits' = SELECTEDVALUE('Top N Produits'[Value], 10)
		lineageTag: a898d07a-7c0b-45f6-91da-ef9c426eafaf

	column Value
		dataType: int64
		lineageTag: eaa02c40-e434-4a39-a7e4-5c91fcda6142
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N Produits-47bbe2d7-3a37-4a85-801d-2c4b1cb53867' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

