table 'Top N Produits'
	lineageTag: 3a14986c-0926-4735-8585-bb894eec9a2f

	measure 'Top N Produits' = SELECTEDVALUE('Top N Produits'[Value], 10)
		lineageTag: 2781a7e3-224d-4802-b670-4164e2e16766
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N Produits'[Value], 10)

	column Value
		dataType: int64
		lineageTag: 16e0808d-03a4-4536-89aa-5d748759a57e
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Produits-542316d4-05ec-4c11-84e7-0e59eb55ac8c' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

