table 'Top N Produits'
	lineageTag: 20f0e3a6-5e3a-44d3-ac3a-b52f13053908

	measure 'Top N Produits' = SELECTEDVALUE('Top N Produits'[Value], 10)
		lineageTag: 046b3060-6a21-40ab-9b0a-a1007743f9ac
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N Produits'[Value], 10)

	column Value
		dataType: int64
		lineageTag: ac026fb4-cf5c-485f-90f0-228662c5d22d
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Produits-cb2630a3-0c7e-4998-a5de-aef5439726bc' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

