"""Post-migration automation — RLS PowerShell scripts and credential templates.

Sprint 119 — Automate manual post-migration steps.

Functions:
    generate_rls_powershell: Generate PowerShell script to assign Azure AD
        groups/users to Power BI RLS roles.
    generate_credential_template: Generate a user-friendly JSON template
        with placeholder credentials for each datasource connection.
"""

import json
import logging
import os
import re

logger = logging.getLogger(__name__)


# ── RLS PowerShell script generation ──────────────────────────────────────────

def generate_rls_powershell(roles, output_path, dataset_name="MyDataset"):
    """Generate a PowerShell script to assign Azure AD members to PBI RLS roles.

    The script uses the Power BI REST API (via MicrosoftPowerBIMgmt module)
    to add security members to each RLS role in the published dataset.

    Args:
        roles: list of role dicts from TMDL/BIM, each with 'name' and
            optionally 'members' (list of Tableau usernames) and
            'tablePermissions'.
        output_path: File path to write the .ps1 script.
        dataset_name: Display name of the dataset in Power BI Service.

    Returns:
        str: Path to the generated .ps1 file, or None on error.
    """
    if not roles:
        return None

    lines = [
        "# ══════════════════════════════════════════════════════════════",
        f"# RLS Role Assignment Script — {dataset_name}",
        "# Generated by Tableau-to-Power-BI Migration Tool",
        "# ══════════════════════════════════════════════════════════════",
        "#",
        "# Prerequisites:",
        "#   Install-Module -Name MicrosoftPowerBIMgmt -Scope CurrentUser",
        "#   Connect-PowerBIServiceAccount",
        "#",
        "# Usage:",
        "#   1. Update $WorkspaceId and $DatasetId below",
        "#   2. Update the email addresses for each role",
        "#   3. Run: .\\assign_rls_roles.ps1",
        "# ══════════════════════════════════════════════════════════════",
        "",
        "# --- Configuration ---",
        '$WorkspaceId = "YOUR_WORKSPACE_ID"   # Replace with your workspace GUID',
        '$DatasetId   = "YOUR_DATASET_ID"     # Replace with your dataset GUID',
        "",
        "# Connect to Power BI Service (interactive login)",
        "Connect-PowerBIServiceAccount",
        "",
    ]

    for role in roles:
        role_name = role.get('name', 'UnknownRole')
        members = role.get('members', [])
        # Sanitize role name for PowerShell variable
        safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', role_name)

        lines.append(f"# ── Role: {role_name} ──")

        if members:
            # Include original Tableau usernames as comments
            lines.append(f"# Original Tableau users: {', '.join(members[:10])}")
            if len(members) > 10:
                lines.append(f"#   ... and {len(members) - 10} more")

        lines.append(f'$Role_{safe_name}_Members = @(')
        if members:
            for member in members:
                # Convert Tableau username to Azure AD UPN placeholder
                email = member if '@' in member else f"{member}@yourdomain.com"
                lines.append(f'    "{email}"')
        else:
            lines.append(f'    "user@yourdomain.com"     # TODO: Add Azure AD members')
        lines.append(")")
        lines.append("")
        lines.append(f'foreach ($member in $Role_{safe_name}_Members) {{')
        lines.append("    try {")
        lines.append(f'        $body = @{{ emailAddress = $member }} | ConvertTo-Json')
        lines.append(f'        $url = "groups/$WorkspaceId/datasets/$DatasetId/users"')
        lines.append(f'        Invoke-PowerBIRestMethod -Url $url -Method Post -Body $body')
        lines.append(f'        Write-Host "  Added $member to role {role_name}" -ForegroundColor Green')
        lines.append("    } catch {")
        lines.append(f'        Write-Host "  Failed to add $member to role {role_name}: $_" -ForegroundColor Red')
        lines.append("    }")
        lines.append("}")
        lines.append("")

    lines.append('Write-Host ""')
    lines.append('Write-Host "RLS role assignment complete." -ForegroundColor Cyan')

    try:
        os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')
        logger.info("RLS PowerShell script written: %s", output_path)
        return output_path
    except OSError as exc:
        logger.warning("Failed to write RLS script: %s", exc)
        return None


# ── Credential template generation ────────────────────────────────────────────

def generate_credential_template(datasources, output_path):
    """Generate a JSON credential template with placeholders for each datasource.

    Creates a user-friendly file with connection details extracted from the
    Tableau workbook, with placeholder values for sensitive fields (password,
    OAuth tokens, service account keys).

    Args:
        datasources: list of datasource dicts from extraction (each has
            'connection' with server, port, database, authentication, etc.).
        output_path: File path to write the template JSON.

    Returns:
        str: Path to the generated file, or None on error.
    """
    if not datasources:
        return None

    template = {
        "_comment": "Credential template for Power BI datasource connections. "
                    "Fill in the placeholder values and use with gateway configuration.",
        "connections": [],
    }

    seen = set()
    for ds in datasources:
        conn = ds.get('connection', {})
        if not conn:
            # Try connection_map for multi-connection datasources
            conn_map = ds.get('connection_map', {})
            if conn_map:
                for cname, cinfo in conn_map.items():
                    _add_credential_entry(template['connections'], cinfo, cname, seen)
                continue
            continue
        _add_credential_entry(template['connections'], conn, ds.get('name', ''), seen)

    if not template['connections']:
        return None

    try:
        os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(template, f, indent=2, ensure_ascii=False)
        logger.info("Credential template written: %s", output_path)
        return output_path
    except OSError as exc:
        logger.warning("Failed to write credential template: %s", exc)
        return None


def _add_credential_entry(connections_list, conn, name, seen):
    """Build a single credential entry from a connection dict."""
    server = conn.get('server', conn.get('host', ''))
    database = conn.get('dbname', conn.get('database', ''))
    conn_type = conn.get('class', conn.get('type', 'unknown'))
    port = conn.get('port', '')

    # Deduplicate by server+database
    key = f"{conn_type}:{server}:{database}"
    if key in seen:
        return
    seen.add(key)

    entry = {
        "name": name,
        "type": conn_type,
        "server": server or "YOUR_SERVER",
        "port": port or "",
        "database": database or "YOUR_DATABASE",
        "authentication": conn.get('authentication', 'sql'),
        "username": "YOUR_USERNAME",
        "password": "YOUR_PASSWORD",
        "_note": "Replace placeholder values with actual credentials. "
                 "For OAuth, use the oauth_token field instead of username/password.",
    }

    # Add OAuth fields for cloud connectors
    if conn_type in ('bigquery', 'snowflake', 'databricks', 'google_sheets',
                      'salesforce', 'redshift', 'azure_sql_dw'):
        entry['oauth_token'] = "YOUR_OAUTH_TOKEN"
        entry['oauth_refresh_token'] = "YOUR_REFRESH_TOKEN"

    # Add service account for GCP
    if conn_type in ('bigquery', 'google_sheets'):
        entry['service_account_key_path'] = "path/to/service-account.json"

    connections_list.append(entry)
