table Calendar
	lineageTag: a120b02f-854d-418b-9c13-88d699445823

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 36a44c6c-672a-4587-a2ca-ffac42628c08

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6e1fb4f7-76f5-4f84-8576-0e4af495952e

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 96bf17ba-8c5c-4e34-89aa-32a730c5d38b

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 92ece695-bc04-4b4c-97f4-7a7641d8725a
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b2751b6c-d0be-4326-acf5-3e43d76bc96d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e7c7d0ca-1be0-4de8-a083-4e73bf77fc43
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a214ab2a-fc8f-496a-bd1d-6fd168a993d7
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: aa9b624d-9c64-4978-a6aa-4f4d4667d906
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f1818b1a-ed43-4e12-b42f-a59c78cc6e20
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 775a63f8-6533-4846-b3aa-3973fe5c3e65
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2111d888-44e2-4bce-bf29-b4e6bf429d29
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: d329a427-e1a0-46ab-8c01-dd4cb14cf15e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6fe0ee1a-9732-4ad3-8ed1-e66c5478a8fe

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d21e1007-6fe6-4185-8ccd-b82892399d47

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9ee082f5-a326-46c4-9106-63b784cf22f0

		level Day
			ordinal: 3
			column: Day
			lineageTag: 2e29777f-7523-4fd7-a8be-2736b616ae63


	partition 'Calendar-5625e06f-1535-43f3-99c8-3ad5314b8c89' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

