table Calendar
	lineageTag: e6f882de-3223-4f72-bdfa-cc5f93a353ea

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d2985d31-0652-4587-b256-956a3e491da6

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 55c2da6b-1f26-43eb-982d-8804c9817ac6

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 97d4811a-8819-49fd-b717-2bf7a09bd947

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1b6d80c6-b8ee-4ba1-86b3-a74fe790ae61
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b13a6c50-1736-4e1e-943c-51315acf7e9b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 07203956-e1eb-4817-8e76-ea18266d8fdf
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2e7c95e7-9e33-4749-b1e3-b9a61dbaaef1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ebbe8ff1-ec65-4fa9-961f-af2f744d4888
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ac40660c-84e5-4af1-98f0-2d468f73e5e1
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 673bf6e8-c08e-4dfe-a998-af3156d2ad65
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 42e547bf-fe74-449c-8bce-e5771897ff87
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 770132ec-d624-4f55-8e55-841f8c1491fd

		level Year
			ordinal: 0
			column: Year
			lineageTag: f5dec9a4-8241-47be-b009-432007029cb4

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 87bbab28-7440-4f20-bfa3-0b1237e2c00f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 30aaef24-0f1c-46b1-8013-15fa312a2177

		level Day
			ordinal: 3
			column: Day
			lineageTag: c67486f8-ac15-478d-80e2-f69eebf0bcd5


	partition 'Calendar-3b12f1e8-256d-457d-a205-ad23c5c9dfec' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

