table Calendar
	lineageTag: 8ccf4cf1-0810-4d27-990e-8a1a92195f97
	description: Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		description: DAX: TOTALYTD([Total Sales], 'Calendar'[Date])
		lineageTag: 4b9f9a00-04a3-42c9-bb39-310e5df0ee3b

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		description: DAX: CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		lineageTag: 6750ea91-7765-41ab-8dfc-3e1c5c357efd

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		description: DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		lineageTag: 98b900c3-7a0f-454d-b634-9a5d073e7682

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6804858d-b041-49c4-b7fb-d63b1a93b3f5
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime. (table key).

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 8eee52d1-ae8d-4edc-b819-c80a17818ed2
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years
		description: Int64 column. categorized as Years.

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e382ff29-41f4-45fc-bdb9-e59b8d41da5f
		summarizeBy: none
		sourceColumn: Quarter
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5ea30f02-9886-47fe-b23e-4bd98c7f6787
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months
		description: Int64 column. categorized as Months.

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f31e6338-d1ae-4242-8172-32358fe4052c
		summarizeBy: none
		sourceColumn: MonthName
		description: String column.
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d8382324-09af-4b48-8ee1-e54c6d105ee0
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days
		description: Int64 column. categorized as Days.

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 069cdd17-8538-443a-8e78-7b27e1e89e56
		summarizeBy: none
		sourceColumn: DayOfWeek
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 1f729a76-8a3d-411c-917b-0de8e1b0f0b1
		summarizeBy: none
		sourceColumn: DayName
		description: String column.
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c0d74ddd-9b80-44b4-bf61-9aca56834492

		level Year
			ordinal: 0
			column: Year
			lineageTag: 2de07333-de6d-470a-bff9-dc004c8bdc81

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 111a98ec-c426-40c0-af41-ad0732006ec8

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 73f5be55-3b83-46c3-94c5-7d32711a204a

		level Day
			ordinal: 3
			column: Day
			lineageTag: e663a9d5-4a51-4dff-95d1-9c88c70eaaa6


	partition 'Calendar-70e05ffb-9971-4ecc-b2da-4d6ecd21598f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

