table Calendar
	lineageTag: 38deb5b0-dc45-4c55-a4f0-e14d14b4c96f

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: f85e4dc1-b87b-419c-b831-d6a3f92a2ae5

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 2d711c00-a61d-4f25-b859-63140d1a7026

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 85a01bc7-8ea8-4ae8-b2a9-00bd4ac2a8c8

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4f9fc267-9702-44fd-8969-7f893d084651
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 75db7d79-e841-4d05-85f6-57f243d911e4
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ca4dc67d-b2e9-435a-bf91-ee228570c7cc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 71a62476-cb35-4507-8fb2-69c5913e8660
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0ff80de4-6a7c-4a5a-af0c-1295a2e6efc7
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 2a5693a4-fb1d-46ce-b2fb-e19c63807eb9
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b546b65b-71d9-4aa8-8f7d-e604dc66478e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7acbb172-6307-4e42-a544-f32f4b1db1aa
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e6332d65-e6fe-4b2c-93bf-1587f59f3707

		level Year
			ordinal: 0
			column: Year
			lineageTag: ebd0471d-8c4c-4af0-ae6e-642e11d99a64

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 95f394c6-5e73-45e5-9512-6bc4064767ad

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 348cd5e3-f2cd-4358-9073-dc52554ae69c

		level Day
			ordinal: 3
			column: Day
			lineageTag: c09d6f33-f5f7-4873-a36f-3575e816fa65


	partition 'Calendar-8045a33a-ea0e-40c0-9426-fea084ea4399' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

