table Calendar
	lineageTag: ad3d2e73-e65d-4238-957f-33ac3e6ca03d

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c67e9bac-73e2-4779-816d-f01730bb0c4f

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8c7b8aa1-5733-4653-a267-baf157ce5f32

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ebb26001-6e1b-4ab5-9cca-7df9f385b319

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d7c3d892-8ff0-4624-a092-1349cb901616
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ec3b0a5a-0d68-40a9-ba9c-48346be27b1c
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5353d2b0-012c-427a-ab4d-81ed6aa1c51b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d3f876ef-7446-4e52-a4c2-75839fb9b519
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 60b46a11-531a-45c3-88a1-cd77aca15280
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: c6b0d687-00e6-4c14-a20d-6f4a617b20e7
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 85586698-cfea-4474-bed9-fb177c8931e4
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c21330ed-2c04-4529-a446-de69d1af687b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9e492c2f-27b4-4874-8775-6b06bdab9ff7

		level Year
			ordinal: 0
			column: Year
			lineageTag: db8dd920-1ca8-480f-b219-5e155c7a8b1a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 1a22fc84-c1c6-4295-972c-e3ea3d7a330e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 12766b07-cf3f-46ac-bb10-aa0b88a24be0

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4602e93d-c7a1-4ef1-b2b9-2c5807218236


	partition 'Calendar-394c6362-69c3-4046-b624-6bfeeb36f7b7' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

