table Calendar
	lineageTag: 7b64d4ba-97fc-49c0-a11c-64762d1af150

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6200e8bf-0ed0-48a3-9b2d-12ed98f49463

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 73f1838c-1897-4869-add2-2e60bcb3ca46

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: a0d185f9-346a-4305-9ba8-548f6833014c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6e19a187-7501-4fdd-b8ba-cf5bc7416606
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 4106cdce-fb8e-44bd-8cb7-54e9fe8bb167
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 90a8bc03-c25d-4eba-a4d1-e6a40210c198
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e0bc0240-1679-4040-842a-dedf7dcccbbd
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c6225619-3c56-4c43-bbaf-2edca58b7001
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 4a568367-4a70-469c-8ca1-5e27ac9bc7ee
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d7456f9a-f392-46b9-91ed-7626dd37b11a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d5231e64-f0a8-4576-8e45-86342f5244ec
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: cfab3810-ed95-4974-acf0-099e8f8f6234

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4a0b918d-7f00-4cd6-a8be-178b4a6106de

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: fab7e40b-3eb8-43a7-a905-9e006196c33d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: cbd8b369-0a1c-4181-af36-087fd32409f0

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4fe17395-a1c3-4c62-a362-e0550b4e97d6


	partition 'Calendar-f839370c-5786-4def-a95d-3af4788e21c8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

