table Calendar
	lineageTag: 9e424570-2be3-4c52-8a82-cb7b81f78001

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 88c06355-da0d-4d0b-bdf0-1a0044f5c9d7

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c8dd2c48-6216-494f-8181-46bc4920fdce

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 0c62f186-7414-4412-a6ec-85091335d48b

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 46de5aaa-bf21-45df-ab4f-f1d29bd538ff
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c65fd57f-0c00-4082-ad60-54f741ad2c33
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0cbfa5b1-f484-463c-ae62-aedc37702b49
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e1be5dba-a934-455b-9da7-cfce829bb303
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 955ededf-e675-486b-bd9e-45852aa021aa
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 15741169-1c63-4355-b381-fcf04e526f83
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 75d4db4f-cf69-4152-b73f-51f109a29c26
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2be6a3fe-90ac-4745-b149-3516da8b6cac
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 39d253dd-68d0-446c-9f05-d7ab9734a9fe

		level Year
			ordinal: 0
			column: Year
			lineageTag: 54524911-0dc3-44b4-87ee-528ae540d694

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 9c43b23d-a39c-4e75-b1a7-bb3d24eeeda8

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: cff5b295-6f0d-4634-9ff1-f28f72dabb71

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9c431665-096b-4f8b-8bf5-c03c2e617baa


	partition 'Calendar-1af8613c-e595-48eb-a85c-aeee1ed73ba9' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

