table Calendar
	lineageTag: b8dadff5-107e-4075-9aad-4e870fb1e4e8
	description: Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		description: DAX: TOTALYTD([Total Sales], 'Calendar'[Date])
		lineageTag: cae56929-5195-4aa8-8ef2-7649311cc8f0

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		description: DAX: CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		lineageTag: 8eac5509-ee2c-4618-8fce-4221b24e674a

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		description: DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		lineageTag: eb0c1f6f-db69-48dc-89d4-86ff087a1116

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a1bc1417-fd60-4774-9eed-331b7637c3c4
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime. (table key).

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 991852f2-6dc0-4b15-b75e-0b4b9c612f7b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years
		description: Int64 column. categorized as Years.

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b1605d0b-4e36-47a7-ada3-fc1c7b300d95
		summarizeBy: none
		sourceColumn: Quarter
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e2038cd7-f6c2-49f6-91c0-2366e51bc49a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months
		description: Int64 column. categorized as Months.

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 15f3d492-a738-4840-a3fe-27bee84211ff
		summarizeBy: none
		sourceColumn: MonthName
		description: String column.
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: cca07811-65e6-48e6-865b-5412d4a7d755
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days
		description: Int64 column. categorized as Days.

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ee95cc2e-1e4e-4d73-9d97-161f3cb13b93
		summarizeBy: none
		sourceColumn: DayOfWeek
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 5db72202-7b24-4476-8182-f8aaba77b713
		summarizeBy: none
		sourceColumn: DayName
		description: String column.
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: a897802d-e4db-4e21-b210-8bbd594fde04

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7b8f09e6-c6f6-4ba6-a1e1-cc69a08d8cf7

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f387e25c-eeff-4cc3-97f9-d073c81908ed

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c3a1930c-d833-485a-b5e5-e7c238474ae0

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3c2dc4f0-8980-4d0a-ac92-17b807801ddb


	partition 'Calendar-02c958f6-f277-4208-9d10-41348e0e9426' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

