table Calendar
	lineageTag: c5facc07-e697-413d-a1d0-8c0644a2782a

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 89b802c7-74f9-4fa5-9945-0829a5721dbb

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 338d717a-da29-4170-8b9c-7dd672114405

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: e811a64b-1852-44b5-bdf1-b489d2a40e6a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bf03ac65-7bfc-45b7-8582-366ca7832563
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 517f4393-4e92-4416-83be-c22abe6038a7
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e6fa7b04-8806-4fe7-8739-a353182e2ca1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2be391f8-3a45-4d42-aa98-602bdaacf50a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 35f3f7eb-3c11-4498-8a95-7b712e5e4206
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 73f32d7b-843b-4beb-87ea-4955695a9ae7
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 379b8c6c-6128-43f1-b2d6-a96e882a3af4
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: feaee952-ea45-40a1-87af-d424558ed531
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e5cf4954-fb32-43b6-a5c4-a4f9011cda89

		level Year
			ordinal: 0
			column: Year
			lineageTag: f7242106-45b6-4575-894b-2dc849725228

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 90a8bf48-1281-4cb6-af87-d438d1bcd4a6

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: b0fe5c80-0579-4424-a73c-8201f15bbe1b

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4d417d54-5272-4bde-9d22-c8cf163d9816


	partition 'Calendar-73a2666c-dd03-42a7-9168-43afc8e4952e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

