table Orders
	lineageTag: c7ec0b27-b089-4819-a32a-4eb6fea4bf08

	measure 'Is Current User' = 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 6a77fb4a-6217-4df0-abe7-a67302f8b502
		annotation Copilot_Description = Migrated from Tableau: [CustomerEmail] = USERNAME() | DAX: 'Orders'[CustomerEmail] = USERPRINCIPALNAME()

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 8f1c1229-1f7f-462a-ad57-8c980395c3db
		annotation Copilot_Description = Migrated from Tableau: ISMEMBEROF("Managers") OR ISMEMBEROF("Executives") | DAX: TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS rol...

	measure 'Region Match' = 'Regions'[RegionManager] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 45eaa777-9711-4c5a-a245-c8c26df38411
		annotation Copilot_Description = Migrated from Tableau: [RegionManager] = FULLNAME() | DAX: 'Regions'[RegionManager] = USERPRINCIPALNAME()

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1cc5eff3-fbe4-4dc6-9477-4ada5f705dda
		annotation Copilot_Description = Migrated from Tableau: SUM([Sales]) | DAX: SUM('Orders'[Sales])

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 71453b4a-60e6-46d1-979c-1dfc80f3b1df
		annotation Copilot_Description = Migrated from Tableau: SUM([Profit]) / SUM([Sales]) | DAX: SUM('Orders'[Profit]) / SUM('Orders'[Sales])

	column OrderID
		dataType: int64
		lineageTag: 5f96c0d9-a243-4446-9024-d6835cc6b790
		summarizeBy: sum
		sourceColumn: OrderID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 71355eab-302a-46a4-b487-9d4e8ef054ef
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 1f4395f8-e1f4-499c-b4a4-75a83e2aa1a4
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 3a7ae352-9e39-4cf6-b840-280e24470e4b
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column CustomerEmail
		dataType: string
		lineageTag: a6da919b-dabf-4e6b-9179-1a1c4c49ec43
		summarizeBy: none
		sourceColumn: CustomerEmail

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 675be457-2bc2-41d7-bdcc-a65a7f61357b
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 3968d226-686b-4080-9a1f-7b35f25292b3
		summarizeBy: none
		sourceColumn: OrderDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Orders-eff7de1b-4d63-49bb-a551-3778aea6aefa' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "SalesDB"),
				
				            _nav = _src{[Schema="dbo", Item="Orders"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"OrderID", "Region", "Sales", "Profit", "CustomerEmail", "Category", "OrderDate"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"OrderID", "Order ID"}, {"CustomerEmail", "Customer Email"}, {"OrderDate", "Order Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns and 5 measures: OrderID, Region, Sales, Profit, CustomerEmail, Category, OrderDate.

