table Orders
	lineageTag: cacbdcd5-ad7c-44a0-8900-ddbdad334005

	measure 'Is Current User' = 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 8add1679-3dc2-4f2b-a7f9-cf1ffd3e6565

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 14d42ef9-db13-4c33-adf5-bd088d509bc7

	measure 'Region Match' = 'Regions'[RegionManager] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: aec6b8a7-92c8-4c30-a01c-f4bf796fe3c0

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a8ae40c1-4fe1-478e-affc-db0ab479fe37

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c0f32a08-132c-4626-b062-b0052aa569ca

	column OrderID
		dataType: int64
		lineageTag: f422aa5e-8c50-4ade-86e2-42e46f3ed9ca
		summarizeBy: sum
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 8be37701-eb95-40f6-aa86-eda572908f2e
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 42f72728-b683-4ef8-a0bf-0d2d57e54e6b
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: b15ffc73-bd12-4757-b51f-2223f12b9441
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column CustomerEmail
		dataType: string
		lineageTag: dbdc7a87-dcb9-471e-b0ae-0915b4de9b6c
		summarizeBy: none
		sourceColumn: CustomerEmail

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 69d2d0f8-60a1-42ad-87a5-d70408a4b9a0
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: afb76d10-0448-4ad0-a739-f941a005c893
		summarizeBy: none
		sourceColumn: OrderDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Orders-b9729d71-a6ee-44e7-994d-63e87159decf' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("localhost", "SalesDB")
				
				    otherwise
				
				        #table({"OrderID", "Region", "Sales", "Profit", "CustomerEmail", "Category", "OrderDate"}, {}),
				    #"Orders Table" = Source{[Schema="dbo", Item="Orders"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Orders Table", {{"OrderID", "Order ID"}, {"CustomerEmail", "Customer Email"}, {"OrderDate", "Order Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

