table Orders
	lineageTag: d090c890-1c4f-4881-b91d-823c2a31b883
	description: Contains 7 columns and 5 measures: OrderID, Region, Sales, Profit, CustomerEmail, Category, OrderDate.

	measure 'Is Current User' = 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		description: Migrated from Tableau: [CustomerEmail] = USERNAME() | DAX: 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		lineageTag: b8b3970a-be2d-42ec-99c5-0061eb7b704e

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		description: Migrated from Tableau: ISMEMBEROF("Managers") OR ISMEMBEROF("Executives") | DAX: TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS rol...
		lineageTag: e97053f0-d9b8-482a-96db-31f9dfc07689

	measure 'Region Match' = 'Regions'[RegionManager] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		description: Migrated from Tableau: [RegionManager] = FULLNAME() | DAX: 'Regions'[RegionManager] = USERPRINCIPALNAME()
		lineageTag: c69fbb3d-9b99-4e55-959e-9625dc81c2f5

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([Sales]) | DAX: SUM('Orders'[Sales])
		lineageTag: d0826955-81a0-4371-b55b-081b1cf6afd0

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([Profit]) / SUM([Sales]) | DAX: SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		lineageTag: 94db55c9-521d-445d-afd9-2f04083ccaef

	column OrderID
		dataType: int64
		lineageTag: c19fae55-aecc-47f4-98c2-20258642f0bf
		summarizeBy: sum
		sourceColumn: OrderID
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 47b93028-a1f4-46b9-b789-24e0b0771af0
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: b462433b-eed8-4c74-bf1e-7450d3c44b49
		summarizeBy: sum
		sourceColumn: Sales
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 232ac17d-3633-48ac-8756-7b07209cde8a
		summarizeBy: sum
		sourceColumn: Profit
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column CustomerEmail
		dataType: string
		lineageTag: 3cf1434d-7412-4cae-b80d-93d3ae4deaf9
		summarizeBy: none
		sourceColumn: CustomerEmail
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: af0d0044-b5a6-4b6a-a3e3-2267a8d9debf
		summarizeBy: none
		sourceColumn: Category
		description: String column.

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: d09a45d6-1301-4326-8f36-b6d403895e14
		summarizeBy: none
		sourceColumn: OrderDate
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	partition 'Orders-2182c111-5610-42c3-a1b0-a66d193226df' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "SalesDB"),
				
				            _nav = _src{[Schema="dbo", Item="Orders"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"OrderID", "Region", "Sales", "Profit", "CustomerEmail", "Category", "OrderDate"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"OrderID", "Order ID"}, {"CustomerEmail", "Customer Email"}, {"OrderDate", "Order Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns and 5 measures: OrderID, Region, Sales, Profit, CustomerEmail, Category, OrderDate.

