table Orders
	lineageTag: 2685ecad-3f26-450c-868f-319071e8ec7e
	description: Contains 7 columns and 5 measures: OrderID, Region, Sales, Profit, CustomerEmail, Category, OrderDate.

	measure 'Is Current User' = 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		description: Migrated from Tableau: [CustomerEmail] = USERNAME() | DAX: 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		lineageTag: d58cc4de-2ac2-4a5b-987e-2f4bbb474207

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		description: Migrated from Tableau: ISMEMBEROF("Managers") OR ISMEMBEROF("Executives") | DAX: TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS rol...
		lineageTag: 7ed597fb-b9a0-4a3e-a96b-e63ed4eee487

	measure 'Region Match' = 'Regions'[RegionManager] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		description: Migrated from Tableau: [RegionManager] = FULLNAME() | DAX: 'Regions'[RegionManager] = USERPRINCIPALNAME()
		lineageTag: 2040956c-75ba-40c7-b481-df01be35b9cc

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([Sales]) | DAX: SUM('Orders'[Sales])
		lineageTag: f2c199de-df3f-4e4f-a745-115ef5411634

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([Profit]) / SUM([Sales]) | DAX: SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		lineageTag: 04db43a8-cfb7-4ece-9853-314d80a21b77

	column OrderID
		dataType: int64
		lineageTag: 8b0f1ddf-2af1-41ff-902f-4e09d73416df
		summarizeBy: sum
		sourceColumn: OrderID
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 012beb0c-c815-49e3-a51a-81e22446fb6d
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 15f0f0e7-12ca-41e2-a010-6f74e5021479
		summarizeBy: sum
		sourceColumn: Sales
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 37b333fa-6598-4779-862b-11fc02afd056
		summarizeBy: sum
		sourceColumn: Profit
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column CustomerEmail
		dataType: string
		lineageTag: e70b656f-2af2-4f13-9807-cab6cc274a8b
		summarizeBy: none
		sourceColumn: CustomerEmail
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 13075a0e-6136-4c5d-8c80-df57f7ce40c4
		summarizeBy: none
		sourceColumn: Category
		description: String column.

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: fe0ee36c-3770-4138-8717-801e3f69eb47
		summarizeBy: none
		sourceColumn: OrderDate
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	partition 'Orders-9b7741ec-31e4-4bae-85b9-c085bea082ec' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "SalesDB"),
				
				            _nav = _src{[Schema="dbo", Item="Orders"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"OrderID", "Region", "Sales", "Profit", "CustomerEmail", "Category", "OrderDate"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"OrderID", "Order ID"}, {"CustomerEmail", "Customer Email"}, {"OrderDate", "Order Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns and 5 measures: OrderID, Region, Sales, Profit, CustomerEmail, Category, OrderDate.

