table Orders
	lineageTag: 01363dcc-2543-4656-b08e-20b80f31b42f

	measure 'Is Current User' = 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 12b11327-3f36-4f3b-8546-91f83481cb0e

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: a32e00ef-3f6a-4ba6-a97f-6dfd899678da

	measure 'Region Match' = 'Regions'[RegionManager] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 9ade6e84-8923-4668-9f3c-7887ac767c10

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7fd49ce0-9a8f-4d20-b968-a672c0e403b0

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: cf8e1ce9-5534-468e-80ba-c65d56e478ee

	column OrderID
		dataType: int64
		lineageTag: cf8d311f-8e07-42a9-a108-6bd9f98d166f
		summarizeBy: sum
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 5c59a0ea-4d9e-4ce2-852a-9402dff3249c
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 26b2ca19-a81d-4447-a267-63c5aee5e610
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 0230c955-c6c5-4dfa-bb82-12387e53b910
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column CustomerEmail
		dataType: string
		lineageTag: c23324a5-a9d8-438d-84d6-af7da7be1796
		summarizeBy: none
		sourceColumn: CustomerEmail

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 6b8f7075-77d6-4306-b2bc-698795b5dd98
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d88f43d-7d73-4e03-bd02-032db5543abc
		summarizeBy: none
		sourceColumn: OrderDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Orders-f43ab5dc-e515-469f-9924-adbef7a6110b' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("localhost", "SalesDB")
				
				    otherwise
				
				        #table({"OrderID", "Region", "Sales", "Profit", "CustomerEmail", "Category", "OrderDate"}, {}),
				    #"Orders Table" = Source{[Schema="dbo", Item="Orders"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Orders Table", {{"OrderID", "Order ID"}, {"CustomerEmail", "Customer Email"}, {"OrderDate", "Order Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

