table Regions
	lineageTag: bb876021-0ff1-4622-87e3-848809de9a33

	column RegionName
		dataType: string
		lineageTag: e06f0ac3-7fe5-4b21-abde-575ebcf4912b
		summarizeBy: none
		sourceColumn: RegionName
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: 12a12f6f-e677-4045-84a0-5b0a73b0061e
		summarizeBy: none
		sourceColumn: RegionManager
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'Regions-c117a86a-63ea-4f54-a9f1-051de4f8c486' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "SalesDB"),
				
				            _nav = _src{[Schema="dbo", Item="Regions"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"RegionName", "RegionManager"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"RegionName", "Region Name"}, {"RegionManager", "Region Manager"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: RegionName, RegionManager.

