table Regions
	lineageTag: 3a972a8c-99cb-42c4-8e5d-5e46f9684577

	column RegionName
		dataType: string
		lineageTag: 3dd984f5-78d4-4148-bd2d-a253419d10a8
		summarizeBy: none
		sourceColumn: RegionName
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: 2a633bd7-527f-4288-8ab6-62bcc6206b91
		summarizeBy: none
		sourceColumn: RegionManager
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'Regions-d0b7fca1-2209-4e0f-a89a-ca3f298ba190' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("localhost", "SalesDB")
				
				    otherwise
				
				        #table({"RegionName", "RegionManager"}, {}),
				    #"Regions Table" = Source{[Schema="dbo", Item="Regions"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Regions Table", {{"RegionName", "Region Name"}, {"RegionManager", "Region Manager"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

