table Regions
	lineageTag: 4f13048c-bb25-485b-bfa1-6c0daed5c3a2

	column RegionName
		dataType: string
		lineageTag: 96c59426-742d-4cd9-a8b7-240f65aa0b07
		summarizeBy: none
		sourceColumn: RegionName
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: 30a494aa-1a92-44d5-8077-7d6c9fa440b4
		summarizeBy: none
		sourceColumn: RegionManager
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'Regions-aeda8873-2c57-476f-8e5b-67f6db71f7c3' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("localhost", "SalesDB")
				
				    otherwise
				
				        #table({"RegionName", "RegionManager"}, {}),
				    #"Regions Table" = Source{[Schema="dbo", Item="Regions"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Regions Table", {{"RegionName", "Region Name"}, {"RegionManager", "Region Manager"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

