table Regions
	lineageTag: fdb7a429-a18d-4b17-9544-812c2dbcb907
	description: Contains 2 columns: RegionName, RegionManager.

	column RegionName
		dataType: string
		lineageTag: e3e1d5be-e878-488b-9e68-43939fd5dee0
		summarizeBy: none
		sourceColumn: RegionName
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: ea89de19-c156-4d49-8f33-9d8e82e930d0
		summarizeBy: none
		sourceColumn: RegionManager
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	partition 'Regions-90059c66-feb1-4e79-b5c3-5882617eaebf' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "SalesDB"),
				
				            _nav = _src{[Schema="dbo", Item="Regions"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"RegionName", "RegionManager"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"RegionName", "Region Name"}, {"RegionManager", "Region Manager"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: RegionName, RegionManager.

