table Regions
	lineageTag: 87796e49-f0a8-41bb-adea-9c8ea3bcdfb0
	description: Contains 2 columns: RegionName, RegionManager.

	column RegionName
		dataType: string
		lineageTag: e15d0fa8-cc61-4a02-b3f0-c5ef85ede1fe
		summarizeBy: none
		sourceColumn: RegionName
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: 33638930-8bba-47ae-b82c-8f0dbd3a970b
		summarizeBy: none
		sourceColumn: RegionManager
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	partition 'Regions-493e6b81-5c10-4d8f-945d-b2c1d33d05c0' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "SalesDB"),
				
				            _nav = _src{[Schema="dbo", Item="Regions"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"RegionName", "RegionManager"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"RegionName", "Region Name"}, {"RegionManager", "Region Manager"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: RegionName, RegionManager.

