table 'Churn Rate'
	lineageTag: 6ec87160-6a4d-4b15-879d-14aeeb77dfbd

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: c7c9a0f4-218d-40aa-90a2-d32763147a20

	column Value
		dataType: double
		lineageTag: 7424e7c9-fb49-40ae-ac25-7a3d83c8411f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-a5b0abf6-a982-4811-9d17-9197530bcb21' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

