table 'New Business Growth'
	lineageTag: b1bb70ee-3b51-4d8b-ba2f-f30af5ad236c

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: df693086-c7e1-4ad4-930d-65f8671c0b1b

	column Value
		dataType: double
		lineageTag: 7042743d-a6c0-445f-8599-b3edda2febe8
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-96851b9f-cfa4-44e2-8d79-88576344b08a' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

