table xy
	lineageTag: eb670e25-311d-4557-9e66-ba1d313b454a

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 875950a9-b8e1-422f-a37e-2d1654926da2

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: c6c22cb0-392a-4735-bc9a-75ddfa07bc2a

	column a
		dataType: string
		lineageTag: 34c5bd6e-f8d3-448f-a9bc-e086373ce48d
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 6d7296aa-5ee5-40cf-b66f-8d6ffffb1520
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 8306d8cc-9227-4c93-8695-63e84be9ee79
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-87f3a84e-11ac-406c-a693-eeba33dcc3d8' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

