table xy
	lineageTag: 6f77d2e0-2a6c-4186-81de-e71e08cd1946

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: ba175584-9e05-4ca7-aa3c-3bf3314fc630

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: 41f6aa81-05d4-4e47-a9f3-d60202e90086

	column a
		dataType: string
		lineageTag: 6d0f70a3-bf20-43cc-b0b3-485dd52c2801
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 9b2539f1-1dad-404c-ba27-95b4004e2b4c
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: d30dde24-d3b8-4e49-901e-dc9a85a2c369
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-2f9f45b8-891d-42e2-8be9-49f238be9d80' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

