table xy
	lineageTag: c7f2cdb9-65e9-44c0-be02-6e163ceeaa1e

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: f060ff9b-8f42-461e-b915-699a841629bc

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: 69cca50e-06f4-468b-a886-7a9dbc04e485

	column a
		dataType: string
		lineageTag: edb1cb81-21d8-4960-a8e4-2aa998874d45
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: ecf273c1-2672-48fc-9f5f-4c33f23f5040
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 0b438634-d7c1-46ab-9787-32a15c35f428
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-93390f57-68c1-4e2e-bde0-cf7676c3a5bb' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

