table xy
	lineageTag: 34a78e3a-677d-459d-a84f-f6e39a3b4deb

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 9130e5c6-84b6-424b-8532-5797adb25fb2

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: f431db3b-dd61-4bb2-be7b-593c3993b304

	column a
		dataType: string
		lineageTag: 07ca2f1c-a9c5-4b68-a1fa-f56dfcfb7588
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: c9effc1e-9a22-480f-82d3-7eaf2089cbd2
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 4b485609-19d8-4783-9d73-250ddfc08fc4
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-f961e66c-7569-4ee1-8443-94cf63569258' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

