table xy
	lineageTag: 9db15137-3b6f-42f2-b2de-6cc3168a2ac7

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: c296a4b4-2bd6-4a50-8305-0a2d827fcc95

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: d3f8833e-eb06-4901-b726-4470517d9443

	column a
		dataType: string
		lineageTag: a4e9572b-795b-4695-8a9e-3bc63195bf03
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: c0162460-ecbc-497b-b626-1ecbb4249fc0
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: a092eed1-5034-4286-a83b-4c346d0d983c
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-9e4bf8df-4ae5-4f40-8a44-6b98b8f0776e' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: Unknown
				    // Replace the sample table below with the actual source expression.
				    Source = try
				
				        try
				        #table(
				            {"a", "x", "y"},
				            {
				                {"Sample 1", 2, 3},
				                {"Sample 2", 3, 4}
				            }
				        )
				    otherwise
				        #table({"a", "x", "y"}, {})
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

