table xy
	lineageTag: 932bfa6a-4b0f-48c1-9b48-879de43451a8

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: a0f34c28-b41f-4459-a9e7-84069f3f5a5f

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: a0912849-2688-40fa-b501-a727bdddc8d1

	column a
		dataType: string
		lineageTag: e1d3c355-5962-4d92-a96a-23d72dd1e3aa
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: d203eecf-2376-44b2-a54f-8e386dc9d87c
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 766396aa-3e9a-40d8-bdaa-e51c906d4415
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-f41e7a92-728a-414d-a2b5-0f0cdd75269c' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

