table xy
	lineageTag: a7645bcb-0135-480b-bf66-2230afd91942
	description: Contains 3 columns and 2 measures: a, x, y.

	measure '[Number of Records]' = 1
		displayFolder: Measures
		description: Migrated from Tableau: 1 | DAX: 1
		lineageTag: 0525a41b-1580-4ad9-b085-6ed2c10ad23b

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		description: Migrated from Tableau: SUM([x]) + SUM([y]) | DAX: SUM('xy'[x]) + SUM('xy'[y])
		lineageTag: c55897d4-3239-4bd3-b2aa-fce88928a8a4

	column a
		dataType: string
		lineageTag: 0bc58e3f-e08f-4f61-b217-c3e262eeb323
		summarizeBy: none
		sourceColumn: a
		description: String column.

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 52fc07ad-e763-4e3b-84dc-04aeeb5d36b5
		summarizeBy: sum
		sourceColumn: x
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: b6d51262-74e5-49fa-abcd-509358aff06f
		summarizeBy: sum
		sourceColumn: y
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	partition 'xy-4b7db2a8-8bf6-42db-b615-f60594d73130' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 3 columns and 2 measures: a, x, y.

