table xy
	lineageTag: ac7fc550-4a44-4e46-bd56-19d4169649df

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: f70bebef-01b2-4563-8ff5-5cacd0e9fce7

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: 4e4f9bcc-ac30-489e-80c2-35b5eb49b2f6

	column a
		dataType: string
		lineageTag: f7ff3faf-8d35-486e-b1da-db3905e339b9
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 2b63908f-c537-49c2-b2b7-07d427d4fc3f
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 57b66804-53f3-4169-91aa-92f26b235d74
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-529a5a12-9141-4d76-8269-a7430d89680d' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

