table xy
	lineageTag: fa50c09a-587b-4178-b741-f6c389591cd0

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: deaa3b3d-0bef-4016-8162-480ba7419529

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: dd48418d-8251-4b4f-86ba-2ca4751b41f2

	column a
		dataType: string
		lineageTag: 7542aade-b455-423e-8161-23dee31a53fc
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 1828413f-2035-47be-a65b-6a3a61202140
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 372fa2c0-4b05-48e5-bf9d-21b804145a53
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-b1192380-c041-42ef-a347-ac0ef997110f' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

