table xy
	lineageTag: 24a31535-70ec-476f-9705-f7e075236e24

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: dc381eb1-18dc-40ca-9814-11444deb35ec

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: ee4b2f40-6a59-44a2-8a90-c648b79d76c1

	column a
		dataType: string
		lineageTag: a199bdbc-28eb-4eda-a6d9-5022df308687
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 84826607-5ae5-4802-a48b-35f2e3e54c8e
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: c87a2ffb-7ee7-437d-8731-eefc41c72c69
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-1546dde4-84cc-43c3-88d4-f6ccc94b334f' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 3 columns and 2 measures: a, x, y.

