table Calendar
	lineageTag: da7641d3-080f-402d-9095-cda36c98015a

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: cebb60c0-9ff3-4561-a2a2-2bc66084ea50

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 76261a07-abc6-4466-aa37-f69171766ac3

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 19a07bbf-4b3c-4ab6-9938-ee5d486f227c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3f10d8d3-e8bf-48a8-b35f-125b0252d008
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1826222f-179f-47e5-9ad6-a5adeb92c1ce
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c9335c6c-785b-4a22-a39d-8c8ab5d2a831
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ab6b8126-2de2-406d-962f-155c3883f774
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: cf6c08e6-1483-445a-b0e0-e7243c14c076
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bb1791f4-2215-4115-b260-f77504a3e636
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c7b02a56-7704-4594-acfc-f874caef9c25
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ddbbe18c-9cad-4262-955b-30c2204885f6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5436f0d4-710d-44cf-b34f-724348fc5f9c

		level Year
			ordinal: 0
			column: Year
			lineageTag: e64020da-e27e-4dc8-8141-c5d64150e8db

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 535df377-3b88-4b79-b479-bad3ada3332a

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 31e2917f-04e3-4374-b7b9-438c763b024d

		level Day
			ordinal: 3
			column: Day
			lineageTag: f5ce95ec-b7d4-452e-a7a0-2e6b62a70b06


	partition 'Calendar-e3dfc918-6e1a-4e85-bab8-4bfa95e316f2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

