table Calendar
	lineageTag: 66da8495-6519-4cb7-9bbb-3864eb8572e1

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7f9b2300-ac23-4c73-8fe1-24aa9e8c158e

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b53fd443-5dd5-46c5-8636-0f8618bdcd2b

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 45ff5a1a-2f8a-4b92-9b12-e2b159bb4d4c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: aa95e0cb-1e4a-4b70-b081-a059acd7b517
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 632f4ca5-0508-41cd-bf86-b682f47d2d69
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 04d60c5e-1266-4752-a32f-138cbff71fd0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: baf46b61-426d-4a39-94b7-39962461be13
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 3515044d-8316-403a-8071-f6e4f761aa1f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 6ed4b3d2-f0bb-41ae-9b11-5f3a95a45f34
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c1f6e7ec-22ee-4f8a-8777-d4867e0645c8
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: df9f93cf-3a37-4fa5-ad48-b867f49e44c8
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4b42cd7b-e2ce-4d53-a8c2-558ad89cd953

		level Year
			ordinal: 0
			column: Year
			lineageTag: dd31dd65-08c2-4448-a9cf-40e34c713c5c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 7c1e3626-e00f-4dcb-b1c9-42ecbfc101fb

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 2b58c7f3-721e-4a5a-ace0-d90e05f4e191

		level Day
			ordinal: 3
			column: Day
			lineageTag: 179e1887-acd5-4dcc-bd73-33740a0c1e46


	partition 'Calendar-0bd651ae-405e-44d0-8538-501ea79a27c2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

