table Calendar
	lineageTag: 5a72dee7-25f7-428a-a357-be0772d500a3

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6b0a07c7-e460-4ddb-a6ed-d8e238c3ba5f

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 013a2da5-fac3-43f8-a8b6-71ed380f9ce1

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 43f45bdf-e462-4d3e-ba0e-111d6ac63bb6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a3d1023d-8a37-42b9-bc44-b18b14bee1c0
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 34300827-13b4-43f7-8b34-a33bf7cde9a8
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b822c91f-1192-427c-8b2a-c6c3090868b0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a2c5f3b8-57a1-495a-8dbc-e15e9795bb59
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 9452808b-018f-4d27-a6d7-b11a05e21fbb
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 71169481-fc1d-4b8f-9a48-8646fb732440
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ed725212-11ec-4e2c-8f4c-7b7c09a9530f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 789b8756-d9f9-490b-90c2-3554b6c8ccdf
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 28738197-1e4c-40e2-8d05-3d2eb232ecc1

		level Year
			ordinal: 0
			column: Year
			lineageTag: 46ce07ec-888e-4bcd-9544-7d0f73b67154

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 4a55e9b7-9f4d-4fa5-a8f6-c5f65b83bb8d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4e5b72ef-98db-486a-b249-af3346e31e69

		level Day
			ordinal: 3
			column: Day
			lineageTag: 046114d0-3ebb-4140-b6d7-3248d4f5a1f6


	partition 'Calendar-44410416-7c33-4e99-9bd1-f21ff7973098' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

