table Calendar
	lineageTag: 6a2b8f93-3d21-4f2e-a082-590c7890e749

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 972b17a6-d93c-4842-9a6b-33bf2f36f847

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 51eb6e90-1d84-4873-a0d2-7ec7673604fe

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 7c9e6ce2-e3f4-477c-a9a4-68e0b06ce0d6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ddec163b-b0ee-44b5-981a-60945036327d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0bf003b8-3a11-4866-9e09-f8b9ee6ffb0f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: cd41a5e7-934e-48c2-897e-2deb9693df0c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: e9887ddc-b53e-47ef-870c-7dad8b066029
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8500eb73-c0e6-403f-9758-31bcae74d6de
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bcaa6547-656f-443f-8d6f-306daaeae772
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7a3763b6-4c5b-4c88-bcfc-46bbbd11263b
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 354b5782-059b-4f2a-bf2c-67796e05b104
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4b3eb0a3-8cf9-4818-8ec7-461ff470c1fe

		level Year
			ordinal: 0
			column: Year
			lineageTag: b253a6bc-2637-49fb-ac1f-4ff5a72a1bde

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 658e91a9-2091-42af-9d8a-705cd11002f9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7fd5a452-c778-4d37-882e-88641cfa5b70

		level Day
			ordinal: 3
			column: Day
			lineageTag: a43462d9-c002-4028-9edc-325f5e43841a


	partition 'Calendar-7b62161b-f376-48d4-90ae-ec2fa3fda713' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

