table Calendar
	lineageTag: dd7d1daa-9737-4286-86e6-5f0d1f921a9b

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 998db04a-5936-48a3-99ab-c0b0c3a4a770

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ccace479-3c8c-42e4-b4a8-786ff175c2d3

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 4fbf6f1a-78dd-4747-a727-0adcd9d2c7a8

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f96d1d8c-3bf9-4770-aa09-f135be97d108
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2f16ffea-a877-4755-8112-74c59abe4158
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 22fbdc7a-a0f9-4494-aba4-5e2a41dfd81e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 555430f4-33fd-483c-9248-32d0a06cac2e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 70723184-6eb6-4319-a1e6-5c662e51243e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 624854bd-29bd-466a-b0bc-bce24130e090
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4c49cf61-7143-4d30-976b-0c4e744e6f2a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a7ba71f9-2cdc-49d4-8b40-4868b6f2b0b4
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 155eeb8e-8adc-42ff-ab61-d0a85715ed8f

		level Year
			ordinal: 0
			column: Year
			lineageTag: b54715ee-9d94-4f10-b0ca-6763d41beb11

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 308bd043-879b-44d9-840d-dacc06ff3cfa

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6692b499-35ff-43e9-b87b-112b05bebf46

		level Day
			ordinal: 3
			column: Day
			lineageTag: 31da8974-43f1-489f-a666-d5a81e41daa1


	partition 'Calendar-501dca27-ba52-4f17-82e9-c4d256dc5939' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

