table Calendar
	lineageTag: bba1daf1-f0cb-406a-9bb4-0def88d602e0

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b504e86b-4db1-4fcd-84dc-7bb04ffd9796

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 4537d650-6f12-4f14-965a-5b1d78b63115

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: bb4d68cf-578a-4bdb-afa7-fa19de28ae34

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 82121846-c527-4df6-9c56-96aecc157cab
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 8b9e9251-0403-4bf0-aa92-b9de5dea00ed
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b0b9f26b-edcd-4889-93f6-8366ce754fcc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4513bc96-a959-41b6-83db-ec5f6c33b691
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 3babd77e-ca5c-4eb0-a437-eb6def2d1cdf
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 289c5013-2a24-4240-b957-83e334975495
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 9ff1fa2b-d344-4f33-8391-9e3033f0dbba
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a243ebdf-7a03-41a9-aa76-c09d7318939e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 612cc16c-f8f2-4748-8f3a-cec03a5111b7

		level Year
			ordinal: 0
			column: Year
			lineageTag: 905dae8b-46ae-43c5-95ec-8d70b5886020

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b5ad710f-cb57-498a-9653-efba2eb77488

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ad97e82f-fca0-4f14-a52d-408d6a8a97fe

		level Day
			ordinal: 3
			column: Day
			lineageTag: 19cf0247-9e15-48c1-9275-db5fb740754e


	partition 'Calendar-666bcb31-fd6f-4dc5-b5cc-d390b9cdb710' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

