table sessions
	lineageTag: deb0d3ff-98fc-4ecc-aa66-c41df0e387ec

	measure 'Total Sessions' = COUNT('sessions'[session_id])
		displayFolder: Measures
		lineageTag: a43a92e1-c620-4780-9d72-ea09d09e86d0

	measure 'Unique Visitors' = DISTINCTCOUNT('sessions'[user_id])
		displayFolder: Measures
		lineageTag: a96d9dcc-3700-4bf9-82b6-064a0fa5e968

	measure 'Conversion Rate' = SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 396a236d-9c04-45b9-9ae6-228909ad1e0e

	measure 'Avg Session Duration' = AVERAGE('sessions'[session_duration])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8068988a-fb72-418c-969a-3630dcfafe66

	measure 'Total Revenue' = SUM('sessions'[revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: afda1271-35b3-4375-a6e2-d2fcb9ef2008

	measure 'Revenue per Session' = SUM('sessions'[revenue]) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3791da81-e612-42f6-9841-dcb532a3ecb2

	measure 'Revenue by Channel' = CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 37ef3838-06e3-431d-9ca6-ef9e88926a7b

	column session_id
		dataType: string
		lineageTag: b2e240ec-bea5-43fb-b07c-ad63cc2ccc9c
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column session_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 19fac9ff-4672-4091-ba7e-fa6f9a57b51d
		summarizeBy: none
		sourceColumn: session_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: 424dcb8d-6fba-4908-95e6-db439bbb0bd5
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 9ded7b7f-e393-42b8-9f5d-67ce4faa351e
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: 570a7b6e-adc9-49ca-ab08-1fd67576757a
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: f4a91c31-485a-4266-a6dd-d7f51978b856
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column page_views
		dataType: int64
		lineageTag: cf592ee5-c951-4fc0-a8b2-833865ae6918
		summarizeBy: sum
		sourceColumn: page_views

		annotation SummarizationSetBy = Automatic

	column session_duration
		dataType: double
		formatString: #,0.00
		lineageTag: 342b1758-350d-40fa-a84b-886080646077
		summarizeBy: sum
		sourceColumn: session_duration

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: boolean
		lineageTag: 590c5061-d3a4-4250-a8e7-e945a4564874
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: b9c5d808-ccee-4e69-83f8-530801eef711
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column 'Channel Category'
		dataType: string
		lineageTag: 83221363-1732-4c1d-b609-0b54a5c4db97
		summarizeBy: none
		sourceColumn: 'Channel Category'

		annotation SummarizationSetBy = Automatic

	column 'Engagement Level'
		dataType: string
		lineageTag: 7b47c063-ceee-467b-9839-e881267880a9
		summarizeBy: none
		sourceColumn: 'Engagement Level'

		annotation SummarizationSetBy = Automatic

	column 'Days Since Signup' = DATEDIFF(LOOKUPVALUE(users[signup_date], users[user_id], sessions[user_id]), TODAY(), DAY)
		dataType: int64
		lineageTag: e07c603d-bc08-4c52-9a06-0ba91b49a722
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'sessions-81fecc1f-446f-4635-83ae-1ba18345a6db' = m
		mode: import
		source =
				let
				    // Source Google BigQuery: my-analytics-project.web_data
				    Source = try
				
				        let
				
				            _src = GoogleBigQuery.Database([BillingProject="my-analytics-project"]),
				
				            _nav = _src{[Name="web_data"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"session_id", "session_date", "user_id", "channel", "device_type", "country", "page_views", "session_duration", "converted", "revenue"}, {}),
				    #"sessions Table" = Source{[Name="sessions"]}[Data],
				    #"Added Channel Category" = Table.AddColumn(#"sessions Table", "Channel Category", each if [channel] = "Organic Search"  or  [channel] = "Paid Search" then "Search" else if [channel] = "Social"  or  [channel] = "Referral" then "Social/Referral" else if [channel] = "Direct" then "Direct" else "Other", type text),
				    #"Added Engagement Level" = Table.AddColumn(#"Added Channel Category", "Engagement Level", each if [page_views] >= 10 then "High" else if [page_views] >= 5 then "Medium" else "Low", type text),
				    Result = #"Added Engagement Level"
				in
				    Result

	annotation PBI_ResultType = Table

