table sessions
	lineageTag: f90edcfb-d5fe-40dc-8b8a-50896870675a

	measure 'Total Sessions' = COUNT('sessions'[session_id])
		displayFolder: Measures
		lineageTag: 97ddc1ab-e6ce-4502-889a-c6788902c90d

	measure 'Unique Visitors' = DISTINCTCOUNT('sessions'[user_id])
		displayFolder: Measures
		lineageTag: 9d2aa825-db4a-4ce8-a27d-48e9e89fb6f9

	measure 'Conversion Rate' = SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3683ee35-9ba1-4946-8476-d71f7d395f43

	measure 'Avg Session Duration' = AVERAGE('sessions'[session_duration])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e4e996e9-a80d-42bf-98ae-e280f0484a4b

	measure 'Total Revenue' = SUM('sessions'[revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: dcc1d19a-109e-4de0-837a-f3253ce0e5c5

	measure 'Revenue per Session' = SUM('sessions'[revenue]) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e7d524b7-ae10-4af6-bec3-c480b7ba0b93

	measure 'Revenue by Channel' = CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2381fab5-b32a-437a-bdbd-ee1f6c82eec8

	column session_id
		dataType: string
		lineageTag: baa8064c-7c19-427b-a3dc-18333d6cc22f
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column session_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 712a4b73-1c0e-442f-bcaa-50abc93709f8
		summarizeBy: none
		sourceColumn: session_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: fa736114-9825-496b-894c-7f32c0aa15e4
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 380fcd34-0627-4871-b9f1-83815466ad04
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: 032eeeb9-e00b-4e54-8f20-75e1b8ecbd03
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 81dabc35-2a9c-4d6d-bde3-d9f860146367
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column page_views
		dataType: int64
		lineageTag: 6fdc475c-f7fb-484d-8547-c49e93c02de4
		summarizeBy: sum
		sourceColumn: page_views

		annotation SummarizationSetBy = Automatic

	column session_duration
		dataType: double
		formatString: #,0.00
		lineageTag: ba327cd2-c19c-440b-833a-81cac8d389ba
		summarizeBy: sum
		sourceColumn: session_duration

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: boolean
		lineageTag: e8cd97d7-065e-4e2d-8da0-6126797ca70e
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: 147a2fc9-3649-4b8d-a7b1-dfb665bd53b9
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column 'Channel Category'
		dataType: string
		lineageTag: f245cf3b-4011-4d22-91e8-7105839dccf9
		summarizeBy: none
		sourceColumn: 'Channel Category'

		annotation SummarizationSetBy = Automatic

	column 'Engagement Level'
		dataType: string
		lineageTag: a01ca471-4f9f-4420-8053-1bca7dd051b7
		summarizeBy: none
		sourceColumn: 'Engagement Level'

		annotation SummarizationSetBy = Automatic

	column 'Days Since Signup' = DATEDIFF(LOOKUPVALUE(users[signup_date], users[user_id], sessions[user_id]), TODAY(), DAY)
		dataType: int64
		lineageTag: ee841b9b-c180-497e-8e5f-3f75e0e7b27b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'sessions-827dacb7-82ff-4af3-b8da-2e2e0aeaed68' = m
		mode: import
		source =
				let
				    // Source Google BigQuery: my-analytics-project.web_data
				    Source = try
				
				        GoogleBigQuery.Database([BillingProject="my-analytics-project"])
				
				    otherwise
				
				        #table({"session_id", "session_date", "user_id", "channel", "device_type", "country", "page_views", "session_duration", "converted", "revenue"}, {}),
				    #"web_data" = Source{[Name="web_data"]}[Data],
				    #"sessions Table" = #"web_data"{[Name="sessions"]}[Data],
				    #"Added Channel Category" = Table.AddColumn(#"sessions Table", "Channel Category", each if [channel] = "Organic Search"  or  [channel] = "Paid Search" then "Search" else if [channel] = "Social"  or  [channel] = "Referral" then "Social/Referral" else if [channel] = "Direct" then "Direct" else "Other", type text),
				    #"Added Engagement Level" = Table.AddColumn(#"Added Channel Category", "Engagement Level", each if [page_views] >= 10 then "High" else if [page_views] >= 5 then "Medium" else "Low", type text),
				    Result = #"Added Engagement Level"
				in
				    Result

	annotation PBI_ResultType = Table

