table sessions
	lineageTag: 4f0c5b41-4af4-497f-b64b-b54e73539a80

	measure 'Total Sessions' = COUNT('sessions'[session_id])
		displayFolder: Measures
		lineageTag: 32f7841e-5cd6-48f6-b1cd-c6504687d85b
		annotation Copilot_Description = Migrated from Tableau: COUNT([session_id]) | DAX: COUNT('sessions'[session_id])

	measure 'Unique Visitors' = DISTINCTCOUNT('sessions'[user_id])
		displayFolder: Measures
		lineageTag: 78d25093-8ac5-4990-ac69-7207e9267d46
		annotation Copilot_Description = Migrated from Tableau: COUNTD([user_id]) | DAX: DISTINCTCOUNT('sessions'[user_id])

	measure 'Conversion Rate' = SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6390fe2c-8375-4314-bb8a-fc0c86487a94
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [converted] THEN 1 ELSE 0 END) / COUNT([session_id]) | DAX: SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])

	measure 'Avg Session Duration' = AVERAGE('sessions'[session_duration])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: aac30e44-dadf-4a8a-86e6-4407352e19c6
		annotation Copilot_Description = Migrated from Tableau: AVG([session_duration]) | DAX: AVERAGE('sessions'[session_duration])

	measure 'Total Revenue' = SUM('sessions'[revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 69c6d8a0-d77a-4828-9ec1-35c183c61749
		annotation Copilot_Description = Migrated from Tableau: SUM([revenue]) | DAX: SUM('sessions'[revenue])

	measure 'Revenue per Session' = SUM('sessions'[revenue]) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 81ba0067-45f7-49c7-9909-4096420c6364
		annotation Copilot_Description = Migrated from Tableau: SUM([revenue]) / COUNT([session_id]) | DAX: SUM('sessions'[revenue]) / COUNT('sessions'[session_id])

	measure 'Revenue by Channel' = CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7175d461-fdc9-4ba6-a1b7-f08d88131084
		annotation Copilot_Description = Migrated from Tableau: {FIXED [channel] : SUM([revenue])} | DAX: CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))

	column session_id
		dataType: string
		lineageTag: cfa50f10-666a-4bde-be14-32bf734841ad
		summarizeBy: none
		sourceColumn: session_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column session_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 922f7fc7-d7ab-45d0-aab0-56c44fcfd0d0
		summarizeBy: none
		sourceColumn: session_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: 487d926c-c618-435c-aa88-14a8b07ae732
		summarizeBy: none
		sourceColumn: user_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: f97c6b6c-c0d6-4a32-b334-860190b0957c
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: d6fff250-09ef-42f7-88d5-89aa91687a57
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 91fabe57-78f5-4ebb-8b37-7a3edd6dee94
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column page_views
		dataType: int64
		lineageTag: ae5ed8bd-aeb6-49f0-8ed6-f06880e31d4c
		summarizeBy: sum
		sourceColumn: page_views

		annotation SummarizationSetBy = Automatic

	column session_duration
		dataType: double
		formatString: #,0.00
		lineageTag: 4397197f-267e-4ea2-95da-4079f7c71602
		summarizeBy: sum
		sourceColumn: session_duration

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: boolean
		lineageTag: dacda8c4-533b-4624-af47-85b6ad549acf
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: bf2f9293-6520-452b-9827-238992885a08
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column 'Channel Category'
		dataType: string
		lineageTag: fbdbde2a-8e07-471d-9cff-668b055baa64
		summarizeBy: none
		sourceColumn: 'Channel Category'

		annotation SummarizationSetBy = Automatic

	column 'Engagement Level'
		dataType: string
		lineageTag: e8946e39-5936-4d6d-ae89-ab6447a50d5c
		summarizeBy: none
		sourceColumn: 'Engagement Level'

		annotation SummarizationSetBy = Automatic

	column 'Days Since Signup' = DATEDIFF(LOOKUPVALUE(users[signup_date], users[user_id], sessions[user_id]), TODAY(), DAY)
		dataType: int64
		lineageTag: 7b6b8d5e-b28d-40fd-9eee-5c1c37f43080
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'sessions-de85aae8-6e84-4d1c-8461-5f15d9d79b11' = m
		mode: import
		source =
				let
				    // Source Google BigQuery: my-analytics-project.web_data
				    Source = try
				
				        let
				
				            _src = GoogleBigQuery.Database([BillingProject="my-analytics-project"]),
				
				            _nav = _src{[Name="web_data"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"session_id", "session_date", "user_id", "channel", "device_type", "country", "page_views", "session_duration", "converted", "revenue"}, {}),
				    #"sessions Table" = Source{[Name="sessions"]}[Data],
				    #"Added Channel Category" = Table.AddColumn(#"sessions Table", "Channel Category", each if [channel] = "Organic Search"  or  [channel] = "Paid Search" then "Search" else if [channel] = "Social"  or  [channel] = "Referral" then "Social/Referral" else if [channel] = "Direct" then "Direct" else "Other", type text),
				    #"Added Engagement Level" = Table.AddColumn(#"Added Channel Category", "Engagement Level", each if [page_views] >= 10 then "High" else if [page_views] >= 5 then "Medium" else "Low", type text),
				    Result = #"Added Engagement Level"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 13 columns and 7 measures: session_id, session_date, user_id, channel, device_type, country, page_views, session_duration, ... (13 columns total).

