table sessions
	lineageTag: c96194ca-3aea-4271-b8a9-36ffbc733697

	measure 'Total Sessions' = COUNT('sessions'[session_id])
		displayFolder: Measures
		lineageTag: 152b0736-9aea-443b-8438-8b9e704f11d0

	measure 'Unique Visitors' = DISTINCTCOUNT('sessions'[user_id])
		displayFolder: Measures
		lineageTag: 2fd1dd29-1fbe-411d-b8ad-6d6ff989ea16

	measure 'Conversion Rate' = SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 5fa8bea3-bd5b-46a1-8c85-3324d835ef04

	measure 'Avg Session Duration' = AVERAGE('sessions'[session_duration])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: eded615d-63a4-452c-b4f6-c842a384a291

	measure 'Total Revenue' = SUM('sessions'[revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 314aa9c2-e128-4d6d-b85d-5031ffd123b2

	measure 'Revenue per Session' = SUM('sessions'[revenue]) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 5c344ddb-d712-4139-b102-045f33c01b7a

	measure 'Revenue by Channel' = CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 86c54968-3dad-4379-bee5-4e00299613e9

	column session_id
		dataType: string
		lineageTag: 896c06cf-c601-4cf3-94ca-3cb82651ee6f
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column session_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 92d22dd5-a42b-4c26-9a29-a8da4954184f
		summarizeBy: none
		sourceColumn: session_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: d28154b4-92be-4a8e-a285-ab987d03da61
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 50070ef5-f6d2-4214-abc6-b6e0114ea0c8
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: 9d659de4-4b11-4dc3-9e19-b0d2c0719245
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 7b512bea-1f9b-4be2-84ad-9df1f22f639c
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column page_views
		dataType: int64
		lineageTag: 7d913769-d511-4da8-ba48-3fdd0b097c8b
		summarizeBy: sum
		sourceColumn: page_views

		annotation SummarizationSetBy = Automatic

	column session_duration
		dataType: double
		formatString: #,0.00
		lineageTag: fe56402c-c61b-458d-acf6-43dd72ef1a96
		summarizeBy: sum
		sourceColumn: session_duration

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: boolean
		lineageTag: 5bfba2da-6946-4e1e-a777-b398afc5f092
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: 823ed5d8-4447-48ad-8fb6-6b14c032bbe1
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column 'Channel Category'
		dataType: string
		lineageTag: f095aa22-c139-4086-9cf2-afb11a7f40ee
		summarizeBy: none
		sourceColumn: 'Channel Category'

		annotation SummarizationSetBy = Automatic

	column 'Engagement Level'
		dataType: string
		lineageTag: 50ee232f-7600-4405-aeba-a59fca816f4d
		summarizeBy: none
		sourceColumn: 'Engagement Level'

		annotation SummarizationSetBy = Automatic

	column 'Days Since Signup' = DATEDIFF(LOOKUPVALUE(users[signup_date], users[user_id], sessions[user_id]), TODAY(), DAY)
		dataType: int64
		lineageTag: 87f69c2b-073f-40c0-a634-494742e11626
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'sessions-594acfe4-033b-4178-ac51-030ef6185b9a' = m
		mode: import
		source =
				let
				    // Source Google BigQuery: my-analytics-project.web_data
				    Source = try
				
				        GoogleBigQuery.Database([BillingProject="my-analytics-project"])
				
				    otherwise
				
				        #table({"session_id", "session_date", "user_id", "channel", "device_type", "country", "page_views", "session_duration", "converted", "revenue"}, {}),
				    #"web_data" = Source{[Name="web_data"]}[Data],
				    #"sessions Table" = #"web_data"{[Name="sessions"]}[Data],
				    #"Added Channel Category" = Table.AddColumn(#"sessions Table", "Channel Category", each if [channel] = "Organic Search"  or  [channel] = "Paid Search" then "Search" else if [channel] = "Social"  or  [channel] = "Referral" then "Social/Referral" else if [channel] = "Direct" then "Direct" else "Other", type text),
				    #"Added Engagement Level" = Table.AddColumn(#"Added Channel Category", "Engagement Level", each if [page_views] >= 10 then "High" else if [page_views] >= 5 then "Medium" else "Low", type text),
				    Result = #"Added Engagement Level"
				in
				    Result

	annotation PBI_ResultType = Table

