table xy
	lineageTag: a147ce5b-5790-47c8-826b-941f2c0c458e

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 4ec40330-b4ce-42ad-b5bd-41fb9bd7af9c

	column a
		dataType: string
		lineageTag: 6798ee22-8b16-4042-8855-4261d29b350a
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column 'Today''s Date'
		dataType: string
		lineageTag: c7d77e68-fce1-4ead-b2c1-ae3e1fb36468
		summarizeBy: none
		sourceColumn: 'Today''s Date'

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: aa9981f1-ffd0-4f9c-ab61-5a87c86d47bf
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 778e7f69-6ea2-4bcb-9e60-aef24e70a342
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-571c6b4a-c642-4de4-8ae5-1eb59291bc1e' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "Today's Date", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 4 columns and 1 measures: a, Today's Date, x, y.

