table Calendar
	lineageTag: 2d97c2c7-a6f0-46a4-8859-001b1b4c34be

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ff22ea27-2f4f-4509-ae91-71f6f5528755
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 6746e8d5-c7d8-42d8-80b4-871b3dcd5a9b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0d925a2b-b347-483b-ada1-4981bd057b11
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ebfe95b9-2a7a-4184-96b9-5006873ca08d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0e99acf9-1c80-4c26-9775-09b57a124c5e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 5bdfcc54-f624-4f8e-88f3-74bec0aa684b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: af4fd377-20fc-4bcc-ac34-52ff0c2efd5d
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: cd0e2b31-bf3b-42e4-9ddb-6034f77a3216
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: dace6ee4-c895-40b4-9d34-d0a4bd35113c

		level Year
			ordinal: 0
			column: Year
			lineageTag: 9da30893-2d66-49e3-8536-25a4c0c579ec

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ed1e0f78-80af-4aa3-b680-3ed296922972

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: fea93ada-31b9-4d4f-ad2d-be042fe5b5e5

		level Day
			ordinal: 3
			column: Day
			lineageTag: 32f0e9fa-84c5-4c24-86fb-00eab68031cb


	partition 'Calendar-25a81ff9-e6bb-4d61-8363-7d93c9137b98' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

