table 'Top N'
	lineageTag: 0e5b77f7-c874-4886-87ae-01862a203326

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 198eb6ca-0af4-466e-80d4-bd066e0e9f06

	column Value
		dataType: int64
		lineageTag: 99e80b98-ea39-4946-8902-474f0132357e
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-1f1410e2-f7f7-4c5b-b29e-46a17dde08d2' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

