table Calendar
	lineageTag: 77b97249-5145-4bd3-b5b8-9f4fd8946f68

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c83c5651-6a13-436e-bb6d-21c3d56e9cb9
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 32a9e2ad-29ef-422a-9498-9bd7868808ce
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dccc4149-5157-4bdd-8e34-8c0ba82f88e4
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: bc7a1670-4a35-423d-bb1b-1a96585dee2c
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e6b5de0b-708e-4ccb-962e-8206e8ee927b
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8cb7d087-6efb-4f1b-8160-5f019996ece8
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d9608281-ed7b-4050-a3a4-72073aae2234
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 62b369bc-a8ae-47dc-9ef1-a335e9cb75c4
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4e6c7ce1-fa4b-4942-ac71-416bf2e31cf6

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1c7a781b-2803-4e7a-a575-7293f8622358

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 433efdae-f1d9-4a15-bd14-3be70804ddd8

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: be93debf-d553-48ad-9a56-f4d5de5214e1

		level Day
			ordinal: 3
			column: Day
			lineageTag: ff95372b-4597-4642-b38a-bac23815d8e9


	partition 'Calendar-972e7af1-6d01-46e1-8869-b57291c0cb1b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

