table 'Target Margin'
	lineageTag: ec6372ea-0657-49f4-bcce-f344b089965a

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 008ea97f-11ea-45cc-9bb9-5e3da9db98da

	column Value
		dataType: double
		lineageTag: 064c2488-edc8-4578-ab33-9faee9a4a987
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-26e1d609-15ef-4ac6-a4d8-858676198b13' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

