table xy
	lineageTag: 148ce5fa-4b4a-4af3-b04d-f39a35775f66

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 5ff1c96f-2934-49d2-9989-7e7629fde012

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: 7c0b7bcb-ffd5-4ad4-a141-2d37d7762834

	column a
		dataType: string
		lineageTag: 9205da37-c2cd-4d40-bb0e-02342cd37f67
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: f1d90ad3-658b-43c3-abe0-c58f15fce82b
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 862aaae0-2d2a-45a1-9e97-d682482be61e
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-2fc194c0-4cec-49e1-b986-1cab2dd79171' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"xy Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

