table dim_product
	lineageTag: 41b79756-d547-418c-8d29-31166e4ecdcf

	column product_key
		dataType: int64
		lineageTag: d3765a7f-bf6b-4cec-90e2-92a7f947fbbf
		summarizeBy: sum
		sourceColumn: product_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: ab1ee99e-2ae8-4817-baad-522634f5eaa4
		summarizeBy: none
		sourceColumn: product_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 83ba9ae1-791a-45bf-b98f-4e4bd418fffe
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 0b328846-7b40-492e-9608-0eed274ea7e2
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		lineageTag: b0360505-98ff-48c1-a68e-6bd1513fda09
		summarizeBy: none
		sourceColumn: subcategory

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: 10a1348c-907e-40f6-8789-d483799f6d12
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column supplier
		dataType: string
		lineageTag: 255d865c-237e-4df8-8415-9ada3e9304bf
		summarizeBy: none
		sourceColumn: supplier

		annotation SummarizationSetBy = Automatic

	column weight_kg
		dataType: double
		formatString: #,0.00
		lineageTag: ebf03b32-c56e-4bba-b7f8-f1382cec4efc
		summarizeBy: sum
		sourceColumn: weight_kg

		annotation SummarizationSetBy = Automatic

	column is_perishable
		dataType: boolean
		lineageTag: 4b5a4752-3fbd-4359-b317-8b02179c265b
		summarizeBy: none
		sourceColumn: is_perishable

		annotation SummarizationSetBy = Automatic

	column launch_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 48ee8891-417d-4a62-a46a-96c3524c18df
		summarizeBy: none
		sourceColumn: launch_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'dim_product-ce9a16c0-6ea0-4e4a-9a8f-6966a297a519' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"product_key", "product_id", "product_name", "category", "subcategory", "brand", "supplier", "weight_kg", "is_perishable", "launch_date"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_product Table" = #"SALES"{[Name="dim_product"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_product Table", {{"product_id", "Product ID"}, {"product_name", "Product Name"}, {"category", "Category"}, {"subcategory", "Subcategory"}, {"brand", "Brand"}, {"supplier", "Supplier"}, {"weight_kg", "Weight (kg)"}, {"is_perishable", "Perishable?"}, {"launch_date", "Launch Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 10 columns: product_key, product_id, product_name, category, subcategory, brand, supplier, weight_kg, ... (10 columns total).

