table dim_customer
	lineageTag: b5401b9f-375e-44f7-96be-0b0eaa8dd8cd
	description: Contains 12 columns: customer_key, customer_id, customer_name, email, phone, segment, industry, company_size, ... (12 columns total).

	column customer_key
		dataType: int64
		lineageTag: 467f6db1-208a-4e40-b68d-54dc65ec313f
		summarizeBy: sum
		sourceColumn: customer_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 8eebf0a1-bcda-4aeb-8d4d-7bebee9a7cc4
		summarizeBy: none
		sourceColumn: customer_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: a56ba574-35ba-4b66-bda8-640b70a671f9
		summarizeBy: none
		sourceColumn: customer_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: dad8aabf-1920-4286-9cf0-4cd165a43a62
		summarizeBy: none
		sourceColumn: email
		description: String column.

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 6896c089-c5b1-4fc1-9e97-047b2adde8c5
		summarizeBy: none
		sourceColumn: phone
		description: String column.

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 10113f01-84d2-4e2e-ac87-8c2b72d421b2
		summarizeBy: none
		sourceColumn: segment
		description: String column.

		annotation SummarizationSetBy = Automatic

	column industry
		dataType: string
		lineageTag: c8e61e4a-6344-466a-b71f-2fe99e1958d6
		summarizeBy: none
		sourceColumn: industry
		description: String column.

		annotation SummarizationSetBy = Automatic

	column company_size
		dataType: string
		lineageTag: 9eb8b8e5-183a-4dcf-9cb2-b6943f6162a1
		summarizeBy: none
		sourceColumn: company_size
		description: String column.

		annotation SummarizationSetBy = Automatic

	column first_order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 52b0c43d-c46c-436d-87a1-0212b582b876
		summarizeBy: none
		sourceColumn: first_order_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: double
		formatString: #,0.00
		lineageTag: f90c4ce0-7984-4ab8-9e83-31edfb5cfb5d
		summarizeBy: sum
		sourceColumn: credit_limit
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column account_manager
		dataType: string
		lineageTag: 059c80d2-79ce-4f6f-a462-3d092a2effb3
		summarizeBy: none
		sourceColumn: account_manager
		description: String column.

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		lineageTag: 20420c67-5ead-4fb1-8336-12dcc9e0f122
		summarizeBy: none
		sourceColumn: is_active
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	partition 'dim_customer-edd72960-2174-4d94-9304-27c317f83dbd' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"customer_key", "customer_id", "customer_name", "email", "phone", "segment", "industry", "company_size", "first_order_date", "credit_limit", "account_manager", "is_active"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_customer Table" = #"SALES"{[Name="dim_customer"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_customer Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"email", "Email"}, {"phone", "Phone"}, {"segment", "Segment"}, {"industry", "Industry"}, {"company_size", "Company Size"}, {"first_order_date", "First Order"}, {"credit_limit", "Credit Limit"}, {"account_manager", "Account Manager"}, {"is_active", "Active?"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: customer_key, customer_id, customer_name, email, phone, segment, industry, company_size, ... (12 columns total).

