table dim_date
	lineageTag: 6ccd396a-7680-4efa-a8e7-f1381c637c45
	description: Contains 12 columns: date_key, full_date, year, quarter, month_num, month_name, week_num, day_name, ... (12 columns total).

	column date_key
		dataType: int64
		lineageTag: e5193dca-d071-4471-8d74-0ed4021ae5e9
		summarizeBy: sum
		sourceColumn: date_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8dccf462-718e-4fc7-97fc-1bd408199275
		summarizeBy: none
		sourceColumn: full_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		lineageTag: 32c51442-0105-49b2-a590-1b9425edefe9
		summarizeBy: sum
		sourceColumn: year
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		lineageTag: 5f5a4c51-be41-4cef-a814-a59bf3dbf53c
		summarizeBy: sum
		sourceColumn: quarter
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column month_num
		dataType: int64
		lineageTag: 82e0640c-537d-4c69-b750-324f4a132085
		summarizeBy: sum
		sourceColumn: month_num
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: d0a6a1af-79ce-4d28-ab1d-31f9460b1066
		summarizeBy: none
		sourceColumn: month_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column week_num
		dataType: int64
		lineageTag: 198ea93e-4ba3-4712-8af3-596579d6651b
		summarizeBy: sum
		sourceColumn: week_num
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: d1920e62-56e5-41cb-b219-d423758c0e49
		summarizeBy: none
		sourceColumn: day_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		lineageTag: 39aa6843-7e28-499e-b43b-9dd49c7640ae
		summarizeBy: none
		sourceColumn: is_weekend
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		lineageTag: 89bb7284-ecae-4e18-ac30-2d38c0447bef
		summarizeBy: none
		sourceColumn: is_holiday
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: string
		lineageTag: db71bcfb-d8ab-46e0-ac22-c8cfb055618a
		summarizeBy: none
		sourceColumn: fiscal_quarter
		description: String column.

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		lineageTag: 803fa900-c1c0-4da7-9d29-58e23030c9da
		summarizeBy: sum
		sourceColumn: fiscal_year
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	partition 'dim_date-aa57e3d4-2a9c-4a36-bd72-9f7d8f148f89' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"date_key", "full_date", "year", "quarter", "month_num", "month_name", "week_num", "day_name", "is_weekend", "is_holiday", "fiscal_quarter", "fiscal_year"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_date Table" = #"SALES"{[Name="dim_date"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_date Table", {{"full_date", "Full Date"}, {"year", "Year"}, {"quarter", "Quarter"}, {"month_num", "Month"}, {"month_name", "Month Name"}, {"week_num", "Week"}, {"day_name", "Day Name"}, {"is_weekend", "Weekend?"}, {"is_holiday", "Holiday?"}, {"fiscal_quarter", "Fiscal Quarter"}, {"fiscal_year", "Fiscal Year"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: date_key, full_date, year, quarter, month_num, month_name, week_num, day_name, ... (12 columns total).

