table dim_product
	lineageTag: 4786e9b4-03ab-4aef-bebc-b2027ae9a16c

	column product_key
		dataType: int64
		lineageTag: 1d992ff7-1412-4695-964e-72f5d3460701
		summarizeBy: sum
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 9fdc11cb-1809-4c2e-ae1a-d0a60c3ea80b
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: c400b771-fb8f-4f08-866f-1e5fe04c1d0f
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 4ac23346-81a5-4f4f-9d68-be851893489d
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		lineageTag: 3da75759-5b92-45d3-b1d6-ddd4bf897841
		summarizeBy: none
		sourceColumn: subcategory

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: db6fdb37-c87d-4af1-89f4-ac07c14462ba
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column supplier
		dataType: string
		lineageTag: 8e3875fc-8025-453c-8120-7cc9b1494211
		summarizeBy: none
		sourceColumn: supplier

		annotation SummarizationSetBy = Automatic

	column weight_kg
		dataType: double
		formatString: #,0.00
		lineageTag: 6d3362ce-8e45-458b-ba21-02fd2259eabc
		summarizeBy: sum
		sourceColumn: weight_kg

		annotation SummarizationSetBy = Automatic

	column is_perishable
		dataType: boolean
		lineageTag: 473cf03d-fb1a-4141-8d14-7c24edd4090a
		summarizeBy: none
		sourceColumn: is_perishable

		annotation SummarizationSetBy = Automatic

	column launch_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 87b42e68-dc8f-4211-9a0f-887760e03a52
		summarizeBy: none
		sourceColumn: launch_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'dim_product-7ba04fbf-a8d4-461a-9a79-7c0717534149' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"product_key", "product_id", "product_name", "category", "subcategory", "brand", "supplier", "weight_kg", "is_perishable", "launch_date"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_product Table" = #"SALES"{[Name="dim_product"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_product Table", {{"product_id", "Product ID"}, {"product_name", "Product Name"}, {"category", "Category"}, {"subcategory", "Subcategory"}, {"brand", "Brand"}, {"supplier", "Supplier"}, {"weight_kg", "Weight (kg)"}, {"is_perishable", "Perishable?"}, {"launch_date", "Launch Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

