table dim_product
	lineageTag: 5dd7494f-f64c-4ad8-a529-9b3a076a4438
	description: Contains 10 columns: product_key, product_id, product_name, category, subcategory, brand, supplier, weight_kg, ... (10 columns total).

	column product_key
		dataType: int64
		lineageTag: 6c64663b-6f34-4230-a5f9-94095282d017
		summarizeBy: sum
		sourceColumn: product_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 583dd240-8070-40d8-82df-3ea74bda44f7
		summarizeBy: none
		sourceColumn: product_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: d2ce851c-1d07-4704-85dc-965366b3a2b3
		summarizeBy: none
		sourceColumn: product_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 7145ad53-ad25-4cac-ba1a-e1512d5cef9f
		summarizeBy: none
		sourceColumn: category
		description: String column.

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		lineageTag: 8f4e4dfd-660a-4f92-9185-844a24396bbf
		summarizeBy: none
		sourceColumn: subcategory
		description: String column.

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: df6dca44-758b-47a4-9dff-d7af66f22e8c
		summarizeBy: none
		sourceColumn: brand
		description: String column.

		annotation SummarizationSetBy = Automatic

	column supplier
		dataType: string
		lineageTag: 920fdd12-cca1-4c0f-be17-9537f0835100
		summarizeBy: none
		sourceColumn: supplier
		description: String column.

		annotation SummarizationSetBy = Automatic

	column weight_kg
		dataType: double
		formatString: #,0.00
		lineageTag: c7d97721-1034-4680-aeb2-85fec3cf2d68
		summarizeBy: sum
		sourceColumn: weight_kg
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column is_perishable
		dataType: boolean
		lineageTag: 970db83c-48b1-4984-a3e0-e754d8cc8d11
		summarizeBy: none
		sourceColumn: is_perishable
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column launch_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 268f7eb7-0eae-4cd0-a51b-82eab12ef5ef
		summarizeBy: none
		sourceColumn: launch_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	partition 'dim_product-ae974926-18c1-4b8e-948f-56ec5fe525fd' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"product_key", "product_id", "product_name", "category", "subcategory", "brand", "supplier", "weight_kg", "is_perishable", "launch_date"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_product Table" = #"SALES"{[Name="dim_product"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_product Table", {{"product_id", "Product ID"}, {"product_name", "Product Name"}, {"category", "Category"}, {"subcategory", "Subcategory"}, {"brand", "Brand"}, {"supplier", "Supplier"}, {"weight_kg", "Weight (kg)"}, {"is_perishable", "Perishable?"}, {"launch_date", "Launch Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 10 columns: product_key, product_id, product_name, category, subcategory, brand, supplier, weight_kg, ... (10 columns total).

