table dim_product
	lineageTag: 39233dcd-9ecd-46e3-95ef-9c7ea663e54a
	description: Contains 10 columns: product_key, product_id, product_name, category, subcategory, brand, supplier, weight_kg, ... (10 columns total).

	column product_key
		dataType: int64
		lineageTag: 644fbdb4-fb70-4f0d-87f8-ddde871e9250
		summarizeBy: sum
		sourceColumn: product_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: cedefc3c-a53d-4abb-bc2f-6915c3dab2ae
		summarizeBy: none
		sourceColumn: product_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 65069836-0ece-4e0c-94dd-132adeb947f7
		summarizeBy: none
		sourceColumn: product_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 5e3ff88d-0ec7-42af-8b14-91d9178e6d32
		summarizeBy: none
		sourceColumn: category
		description: String column.

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		lineageTag: 4394ce56-fd9e-4730-affd-6c4522831532
		summarizeBy: none
		sourceColumn: subcategory
		description: String column.

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: d3115736-bc48-4feb-8395-5bbf75f26d54
		summarizeBy: none
		sourceColumn: brand
		description: String column.

		annotation SummarizationSetBy = Automatic

	column supplier
		dataType: string
		lineageTag: 153f19f1-a27a-499b-bfac-5e7b527b1a98
		summarizeBy: none
		sourceColumn: supplier
		description: String column.

		annotation SummarizationSetBy = Automatic

	column weight_kg
		dataType: double
		formatString: #,0.00
		lineageTag: 1a918ef9-7cc1-43e1-9831-5f13fe061f0c
		summarizeBy: sum
		sourceColumn: weight_kg
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column is_perishable
		dataType: boolean
		lineageTag: 596c933e-4003-4186-a9ad-05787e0450d2
		summarizeBy: none
		sourceColumn: is_perishable
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column launch_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4a53b5c7-dfa6-4478-b94d-1cf51d1b717f
		summarizeBy: none
		sourceColumn: launch_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	partition 'dim_product-1debf048-86c8-4610-812d-7d92f27aa673' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"product_key", "product_id", "product_name", "category", "subcategory", "brand", "supplier", "weight_kg", "is_perishable", "launch_date"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_product Table" = #"SALES"{[Name="dim_product"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_product Table", {{"product_id", "Product ID"}, {"product_name", "Product Name"}, {"category", "Category"}, {"subcategory", "Subcategory"}, {"brand", "Brand"}, {"supplier", "Supplier"}, {"weight_kg", "Weight (kg)"}, {"is_perishable", "Perishable?"}, {"launch_date", "Launch Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 10 columns: product_key, product_id, product_name, category, subcategory, brand, supplier, weight_kg, ... (10 columns total).

