table dim_customer
	lineageTag: bc333dc2-8e75-4961-8392-e80411315367

	column customer_key
		dataType: int64
		lineageTag: c6e247b0-c2bd-4e9f-a459-6e7866eadf83
		summarizeBy: sum
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 7bd45a8e-f850-4a62-9b62-0627e03687c0
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 00f051bf-4238-461e-bcbc-d04e61726684
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 83e8d8cd-2ef2-4dfc-ba4b-33761f13bf01
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 9f170116-c52c-4c80-893c-a89e0447b24c
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 453a6da6-36b7-4499-be60-9bc6b05d2d7f
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column industry
		dataType: string
		lineageTag: ee191d25-b0ed-407a-abb8-17d3b7e32dea
		summarizeBy: none
		sourceColumn: industry

		annotation SummarizationSetBy = Automatic

	column company_size
		dataType: string
		lineageTag: 0dac2639-8029-4c2f-9268-42b62a041635
		summarizeBy: none
		sourceColumn: company_size

		annotation SummarizationSetBy = Automatic

	column first_order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: ae4eee8a-cb86-412d-b110-360020fea8d4
		summarizeBy: none
		sourceColumn: first_order_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: double
		formatString: #,0.00
		lineageTag: 049cbebe-f337-4935-8143-2cb247375d04
		summarizeBy: sum
		sourceColumn: credit_limit

		annotation SummarizationSetBy = Automatic

	column account_manager
		dataType: string
		lineageTag: d6ca903a-4d7b-484e-8cbd-d7c1c2f32885
		summarizeBy: none
		sourceColumn: account_manager

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		lineageTag: f51c7661-6a16-42fa-a2bd-b8cc25ff4884
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	partition 'dim_customer-b46e1e45-4ea9-4945-8788-5d6362c35f7e' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"customer_key", "customer_id", "customer_name", "email", "phone", "segment", "industry", "company_size", "first_order_date", "credit_limit", "account_manager", "is_active"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_customer Table" = #"SALES"{[Name="dim_customer"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_customer Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"email", "Email"}, {"phone", "Phone"}, {"segment", "Segment"}, {"industry", "Industry"}, {"company_size", "Company Size"}, {"first_order_date", "First Order"}, {"credit_limit", "Credit Limit"}, {"account_manager", "Account Manager"}, {"is_active", "Active?"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

