table dim_customer
	lineageTag: a7252255-357a-47ff-9423-201c05a3bee7

	column customer_key
		dataType: int64
		lineageTag: e3391049-4f8a-439f-b27d-357c930da9bd
		summarizeBy: sum
		sourceColumn: customer_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 9b6e8db7-83b0-4983-835d-39a2d8a65431
		summarizeBy: none
		sourceColumn: customer_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 857b142f-0082-4062-aed0-669309a2da67
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: bdec573c-3360-4995-8b6f-93e400ecc539
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 86331a6d-0fcb-497b-a14f-09e7f596cf81
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: bb7e9973-be4f-42b7-9648-4f9c1bbab5e4
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column industry
		dataType: string
		lineageTag: 83a0b961-fd98-4531-afb8-34b0bf728465
		summarizeBy: none
		sourceColumn: industry

		annotation SummarizationSetBy = Automatic

	column company_size
		dataType: string
		lineageTag: 10731c94-97bc-4d83-8e63-eaccfcffa69d
		summarizeBy: none
		sourceColumn: company_size

		annotation SummarizationSetBy = Automatic

	column first_order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3b14afe3-8d40-4c7e-ac87-0b250af0f047
		summarizeBy: none
		sourceColumn: first_order_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: double
		formatString: #,0.00
		lineageTag: 2e1a916f-d36a-44cc-bbbb-459693956a71
		summarizeBy: sum
		sourceColumn: credit_limit

		annotation SummarizationSetBy = Automatic

	column account_manager
		dataType: string
		lineageTag: 042c9d9f-75ae-40af-931e-a8385c31360a
		summarizeBy: none
		sourceColumn: account_manager

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		lineageTag: fcd79a4a-4685-479c-9237-e4f225c3dd7e
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	partition 'dim_customer-02e0f659-82f7-4034-99cc-b77a9a83da7e' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"customer_key", "customer_id", "customer_name", "email", "phone", "segment", "industry", "company_size", "first_order_date", "credit_limit", "account_manager", "is_active"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_customer Table" = #"SALES"{[Name="dim_customer"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_customer Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"email", "Email"}, {"phone", "Phone"}, {"segment", "Segment"}, {"industry", "Industry"}, {"company_size", "Company Size"}, {"first_order_date", "First Order"}, {"credit_limit", "Credit Limit"}, {"account_manager", "Account Manager"}, {"is_active", "Active?"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: customer_key, customer_id, customer_name, email, phone, segment, industry, company_size, ... (12 columns total).

