table dim_date
	lineageTag: a0db92ca-80dd-4add-9046-2dda232a4e3d
	description: Contains 12 columns: date_key, full_date, year, quarter, month_num, month_name, week_num, day_name, ... (12 columns total).

	column date_key
		dataType: int64
		lineageTag: fdac95ab-fed7-4246-ad03-148d64e92bbd
		summarizeBy: sum
		sourceColumn: date_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 37dcb841-7099-4234-a44b-9f28a4298823
		summarizeBy: none
		sourceColumn: full_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		lineageTag: 2ab0e86e-ea77-492f-bf91-85de557f991b
		summarizeBy: sum
		sourceColumn: year
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		lineageTag: e3632333-57db-4208-bd8c-bc6ebcaebd4b
		summarizeBy: sum
		sourceColumn: quarter
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column month_num
		dataType: int64
		lineageTag: bad5fbec-cca7-40a8-868d-2c2c1914c833
		summarizeBy: sum
		sourceColumn: month_num
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: d84a2b4a-2213-46f4-a8b1-63321eecec8e
		summarizeBy: none
		sourceColumn: month_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column week_num
		dataType: int64
		lineageTag: 4ff998fc-3690-4d93-97e2-4e36fe2e1270
		summarizeBy: sum
		sourceColumn: week_num
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: da7ee6dd-a967-49a9-9032-75a810c0c170
		summarizeBy: none
		sourceColumn: day_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		lineageTag: b423a822-743a-4f80-828c-934d8b8ceace
		summarizeBy: none
		sourceColumn: is_weekend
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		lineageTag: a02ea15e-b85b-4a8c-bc16-b5b713b6337e
		summarizeBy: none
		sourceColumn: is_holiday
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: string
		lineageTag: affd7531-5970-4684-9c62-7e48404f8992
		summarizeBy: none
		sourceColumn: fiscal_quarter
		description: String column.

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		lineageTag: 15bf43da-2941-4fec-9c6d-b20d24cdda6c
		summarizeBy: sum
		sourceColumn: fiscal_year
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	partition 'dim_date-16cd825b-42c9-4f6f-af7b-6e5b49e33bb0' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"date_key", "full_date", "year", "quarter", "month_num", "month_name", "week_num", "day_name", "is_weekend", "is_holiday", "fiscal_quarter", "fiscal_year"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_date Table" = #"SALES"{[Name="dim_date"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_date Table", {{"full_date", "Full Date"}, {"year", "Year"}, {"quarter", "Quarter"}, {"month_num", "Month"}, {"month_name", "Month Name"}, {"week_num", "Week"}, {"day_name", "Day Name"}, {"is_weekend", "Weekend?"}, {"is_holiday", "Holiday?"}, {"fiscal_quarter", "Fiscal Quarter"}, {"fiscal_year", "Fiscal Year"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: date_key, full_date, year, quarter, month_num, month_name, week_num, day_name, ... (12 columns total).

