table dim_date
	lineageTag: e5cfec4d-07f9-432f-8548-e76413e6f223

	column date_key
		dataType: int64
		lineageTag: 8faabc66-551e-4358-9e41-694d7414634f
		summarizeBy: sum
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a7663325-06fa-4d57-b0b7-74dc86576ffc
		summarizeBy: none
		sourceColumn: full_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		lineageTag: 096ba2f0-3b16-412e-8fd3-64d3d43d8024
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		lineageTag: 2ea1f9a2-3e9a-4035-a6de-d78496a40d0c
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month_num
		dataType: int64
		lineageTag: feaa26cc-3716-4be9-afa5-2d76aa32935a
		summarizeBy: sum
		sourceColumn: month_num

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 8401e51d-143f-4191-adfa-4b033bf7d485
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column week_num
		dataType: int64
		lineageTag: 5a17794d-28d4-4d6b-912d-98dd3cd78af5
		summarizeBy: sum
		sourceColumn: week_num

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: cb334e52-d301-41b2-8269-f8be8e5ae168
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		lineageTag: 953058e6-c8a8-4a6a-8f26-0dba47a77992
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		lineageTag: 2676d8a9-5be9-4519-b927-ed3c4086132a
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: string
		lineageTag: 13fc0c97-39a5-47a7-ab29-937badb3665e
		summarizeBy: none
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		lineageTag: bbd2b24f-7a85-4cc3-b5ac-f3d5712b71d5
		summarizeBy: sum
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	partition 'dim_date-fcc38d1c-68f5-46bf-aeab-ecd77d9ab428' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH")
				
				    otherwise
				
				        #table({"date_key", "full_date", "year", "quarter", "month_num", "month_name", "week_num", "day_name", "is_weekend", "is_holiday", "fiscal_quarter", "fiscal_year"}, {}),
				    #"ENTERPRISE_DW" = Source{[Name="ENTERPRISE_DW"]}[Data],
				    #"SALES" = #"ENTERPRISE_DW"{[Name="SALES"]}[Data],
				    #"dim_date Table" = #"SALES"{[Name="dim_date"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_date Table", {{"full_date", "Full Date"}, {"year", "Year"}, {"quarter", "Quarter"}, {"month_num", "Month"}, {"month_name", "Month Name"}, {"week_num", "Week"}, {"day_name", "Day Name"}, {"is_weekend", "Weekend?"}, {"is_holiday", "Holiday?"}, {"fiscal_quarter", "Fiscal Quarter"}, {"fiscal_year", "Fiscal Year"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

