table dim_customer
	lineageTag: 249d5268-2d8f-4226-b7aa-f63d3c8c778b
	description: Contains 12 columns: customer_key, customer_id, customer_name, email, phone, segment, industry, company_size, ... (12 columns total).

	column customer_key
		dataType: int64
		lineageTag: 4f069562-0e96-4867-b086-3a7ea6089492
		summarizeBy: sum
		sourceColumn: customer_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 877da1f2-495b-4461-85ba-dd05453ed4a9
		summarizeBy: none
		sourceColumn: customer_id
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: fa03d850-9f46-42fd-8181-5da2cb916b01
		summarizeBy: none
		sourceColumn: customer_name
		description: String column.

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 071d4b2d-675a-4236-a327-a81040005d75
		summarizeBy: none
		sourceColumn: email
		description: String column.

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 25b0ef5b-ce4b-4ad2-81c9-6cb73fda692c
		summarizeBy: none
		sourceColumn: phone
		description: String column.

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 688cf74d-ceef-45e1-be7b-3920a5031c92
		summarizeBy: none
		sourceColumn: segment
		description: String column.

		annotation SummarizationSetBy = Automatic

	column industry
		dataType: string
		lineageTag: 70d4606c-505e-46e3-946a-c151b01c376f
		summarizeBy: none
		sourceColumn: industry
		description: String column.

		annotation SummarizationSetBy = Automatic

	column company_size
		dataType: string
		lineageTag: 1023c66f-9492-4b42-9358-65cbd86df7c6
		summarizeBy: none
		sourceColumn: company_size
		description: String column.

		annotation SummarizationSetBy = Automatic

	column first_order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8b82d448-9e49-4052-9a5e-7537a9ca2947
		summarizeBy: none
		sourceColumn: first_order_date
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: double
		formatString: #,0.00
		lineageTag: 185881fa-d9c2-4d31-a166-32fef493148d
		summarizeBy: sum
		sourceColumn: credit_limit
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column account_manager
		dataType: string
		lineageTag: 8296ffd5-e9a9-4f70-a247-acfab56d808d
		summarizeBy: none
		sourceColumn: account_manager
		description: String column.

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		lineageTag: 179edda9-1a75-4155-a78b-a2c672806680
		summarizeBy: none
		sourceColumn: is_active
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	partition 'dim_customer-d316cd2b-5255-4170-871d-e79840526bdb' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"customer_key", "customer_id", "customer_name", "email", "phone", "segment", "industry", "company_size", "first_order_date", "credit_limit", "account_manager", "is_active"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_customer Table" = #"SALES"{[Name="dim_customer"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_customer Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"email", "Email"}, {"phone", "Phone"}, {"segment", "Segment"}, {"industry", "Industry"}, {"company_size", "Company Size"}, {"first_order_date", "First Order"}, {"credit_limit", "Credit Limit"}, {"account_manager", "Account Manager"}, {"is_active", "Active?"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: customer_key, customer_id, customer_name, email, phone, segment, industry, company_size, ... (12 columns total).

