table fact_sales
	lineageTag: de5e4e93-f446-44e8-bf2a-6a4ee417f496
	description: Contains 30 columns and 31 measures: sale_id, date_key, customer_key, product_key, store_key, channel, region, territory, ... (30 columns total).

	measure 'Gross Revenue' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([quantity] * [unit_price]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])
		lineageTag: 705c4e63-4bb1-428e-af63-6957a3f148fb

	measure 'Net Revenue' = SUMX('fact_sales', IF('fact_sales'[order_status] <> "Cancelled" && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]), 0))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM(IF [order_status] != "Cancelled" AND [is_returned] = FALSE THEN [quantity] * [unit_price] * (1 - [discount_pct]) ELSE 0 END) | DAX: SUMX('fact_sales', IF('fact_sales'[order_status] <> "Cancelled" && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quant...
		lineageTag: f307799a-2eba-4556-8135-43ef429742fc

	measure COGS = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_cost])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([quantity] * [unit_cost]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_cost])
		lineageTag: 6af4238d-7dfc-4159-8ed0-50b19a6d8123

	measure 'Gross Profit' = [Net Revenue] - [COGS] - SUM('fact_sales'[shipping_cost])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: [C_NetRev] - [C_COGS] - SUM([shipping_cost]) | DAX: [Net Revenue] - [COGS] - SUM('fact_sales'[shipping_cost])
		lineageTag: 77bd4982-af60-4b6e-8f1e-22e362f68caa

	measure 'Gross Margin %' = IF(ISBLANK([Gross Profit] / [Net Revenue]), 0, [Gross Profit] / [Net Revenue])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: ZN([C_GrossProfit] / [C_NetRev]) | DAX: IF(ISBLANK([Gross Profit] / [Net Revenue]), 0, [Gross Profit] / [Net Revenue])
		lineageTag: bccd46e5-e32a-4782-81b2-72cab1a16bbd

	measure 'Tax Amount' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]) * 'fact_sales'[tax_rate])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM([quantity] * [unit_price] * (1 - [discount_pct]) * [tax_rate]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]) * 'fact_sales'[t...
		lineageTag: fc2127c7-62b4-4858-983a-61724574b122

	measure 'Total Revenue incl Tax' = [Net Revenue] + [Tax Amount]
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: [C_NetRev] + [C_TaxAmt] | DAX: [Net Revenue] + [Tax Amount]
		lineageTag: 1e1be7da-c0e7-4162-9768-69243da55bc7

	measure 'Return Rate' = SUMX('fact_sales', IF('fact_sales'[is_returned] = TRUE, 1, 0)) / COUNT('fact_sales'[sale_id])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: SUM(IF [is_returned] = TRUE THEN 1 ELSE 0 END) / COUNT([sale_id]) | DAX: SUMX('fact_sales', IF('fact_sales'[is_returned] = TRUE, 1, 0)) / COUNT('fact_sales'[sale_id])
		lineageTag: 759a0f4b-b92a-4e39-a49d-4dc66996a7f8

	measure 'Revenue per Customer' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_customer', 'dim_customer'[customer_id]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {FIXED [customer_id] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_customer', 'dim_customer...
		lineageTag: 11446161-e3f8-4bb4-8053-a44cd2f13e14

	measure 'Revenue per Product' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_product', 'dim_product'[product_id]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {FIXED [product_id] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_product', 'dim_product'[...
		lineageTag: 01eb8a19-ba7b-42ae-a5c9-90ea5be8f738

	measure 'Revenue by Region-Channel' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('fact_sales', 'fact_sales'[region], 'fact_sales'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {FIXED [region], [channel] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('fact_sales', 'fact_sales'[re...
		lineageTag: ef223cda-cc7d-40ee-9cdf-a9520b73536f

	measure 'Revenue excl Territory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), REMOVEFILTERS('fact_sales'[territory]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {EXCLUDE [territory] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), REMOVEFILTERS('fact_sales'[territory]))
		lineageTag: 8cb9051d-a690-4701-95d3-a9519460a516

	measure 'Revenue incl Subcategory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {INCLUDE [subcategory] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		lineageTag: 7cacd9d1-12df-40d2-89a9-8520c15ff0b7

	measure 'Running Total Revenue' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), FILTER(ALLSELECTED('fact_sales'), TRUE())) /* RUNNING_SUM: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_SUM(SUM([quantity] * [unit_price])) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), FILTER(ALLSELECTED('fact_sales'), TRUE(...
		lineageTag: b97f257f-0a9b-4702-b822-36ab6296a499

	measure 'Running Avg Revenue' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), FILTER(ALLSELECTED('fact_sales'), TRUE())) /* RUNNING_AVG: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_AVG(SUM([quantity] * [unit_price])) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), FILTER(ALLSELECTED('fact_sales'), TRUE(...
		lineageTag: 678c1506-cbd7-4311-bbfd-68af9acc4814

	measure 'Running Count' = CALCULATE(SUM('fact_sales'[quantity]), FILTER(ALLSELECTED('fact_sales'), TRUE())) /* RUNNING_COUNT: converted to cumulative — verify window scope */
		displayFolder: Measures
		description: Migrated from Tableau: RUNNING_COUNT(SUM([quantity])) | DAX: CALCULATE(SUM('fact_sales'[quantity]), FILTER(ALLSELECTED('fact_sales'), TRUE())) /* RUNNING_COUNT: converted to cumulat...
		lineageTag: b18692ac-051d-430f-ab8e-dcf1ef4f1765

	measure 'Revenue Rank' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		displayFolder: Measures
		description: Migrated from Tableau: RANK(SUM([quantity] * [unit_price])) | DAX: RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		lineageTag: e1702af0-76a0-40b9-b94e-7227c6892220

	measure 'Revenue Rank Dense' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]),, ASC, DENSE)
		displayFolder: Measures
		description: Migrated from Tableau: RANK_DENSE(SUM([quantity] * [unit_price])) | DAX: RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]),, ASC, DENSE)
		lineageTag: cf81888a-470e-4921-8bc5-c7718904a435

	measure 'Moving Avg 3-Period' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), WINDOW(-2, REL, 0, REL, ORDERBY('fact_sales'[sale_id], ASC)), ALL('fact_sales')) /* WINDOW.AVG: frame 'fact_sales'[-2,0] */
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: WINDOW_AVG(SUM([quantity] * [unit_price]), -2, 0) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), WINDOW(-2, REL, 0, REL, ORDERBY('fact_s...
		isHidden
		lineageTag: 1efd4953-bb4e-430a-95c0-2df70009caf4

	measure 'Window Max Revenue' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: WINDOW_MAX(SUM([quantity] * [unit_price])) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALL('fact_sales'))
		lineageTag: 80c805e6-eb35-415c-8936-f9d257270555

	measure 'Revenue StdDev' = STDEVX.S('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: STDEV(SUM([quantity] * [unit_price])) | DAX: STDEVX.S('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])
		lineageTag: c2842477-7ec2-4d88-bf1a-ba128a622965

	measure 'Order Count' = DISTINCTCOUNT('fact_sales'[sale_id])
		displayFolder: Measures
		description: Migrated from Tableau: COUNTD([sale_id]) | DAX: DISTINCTCOUNT('fact_sales'[sale_id])
		lineageTag: 38843a45-66c5-4e05-8130-e267d445e788

	measure 'Unique Customers' = DISTINCTCOUNT('dim_customer'[customer_id])
		displayFolder: Measures
		description: Migrated from Tableau: COUNTD([customer_id]) | DAX: DISTINCTCOUNT('dim_customer'[customer_id])
		lineageTag: 1b1e5208-c810-45f2-9d67-56b6410f7079

	measure 'Unique Products Sold' = DISTINCTCOUNT('dim_product'[product_id])
		displayFolder: Measures
		description: Migrated from Tableau: COUNTD([product_id]) | DAX: DISTINCTCOUNT('dim_product'[product_id])
		lineageTag: 05117c3d-664f-40a0-9f22-e8c55653135f

	measure 'Customer Tier' = IF([Revenue per Customer] > 100000, "Enterprise", IF([Revenue per Customer] > 50000, "Mid-Market", IF([Revenue per Customer] > 10000, "SMB", "Startup")))
		displayFolder: Dimensions
		description: Migrated from Tableau: IF [C_RevPerCust] > 100000 THEN "Enterprise" ELSEIF [C_RevPerCust] > 50000 THEN "Mid-Market" ELSEIF [C_RevPerCust] > 10000 THEN "SMB" ELSE "Startup" END | DAX: IF([Revenue per Customer] > 100000, "Enterprise", IF([Revenue per Customer] > 50000, "Mid-Market", IF([Revenue per Custo...
		lineageTag: a9f44beb-1280-48f6-9e26-b50b79dee6de

	measure 'YTD Revenue' = CALCULATE(SUMX('fact_sales', IF('dim_date'[year] = YEAR(TODAY()) && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price], 0)), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: {FIXED : SUM(IF [year] = YEAR(TODAY()) AND [is_returned] = FALSE THEN [quantity] * [unit_price] ELSE 0 END)} | DAX: CALCULATE(SUMX('fact_sales', IF('dim_date'[year] = YEAR(TODAY()) && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quan...
		lineageTag: 3cb54a17-a877-46a6-8e1a-1c193277d76f

	measure 'Is My Account' = 'dim_customer'[email] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		description: Migrated from Tableau: [email] = USERNAME() | DAX: 'dim_customer'[email] = USERPRINCIPALNAME()
		lineageTag: 8695224a-2ee7-43d5-9c6e-271335dff563

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Regional Managers"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		description: Migrated from Tableau: ISMEMBEROF("Regional Managers") | DAX: TRUE() /* ISMEMBEROF("Regional Managers"): implement via RLS role */
		lineageTag: 382a11c1-44dc-4037-8862-845c80e575b2

	measure 'Analysis Start Date' = DATE(2024, 1, 1)
		description: DAX: DATE(2024, 1, 1)
		lineageTag: 5348f35c-e0ad-4f8e-b14a-8b8fcb292ae5

	measure 'Metric Selector' = "Revenue"
		description: DAX: "Revenue"
		lineageTag: 2287bf05-a81c-4118-926f-4db0ca2df370

	measure 'Display Currency' = "USD"
		description: DAX: "USD"
		lineageTag: 709d36ba-a55b-4cc6-a72d-20c2b16360d0

	column sale_id
		dataType: int64
		lineageTag: c8a1cd92-a3e6-4226-a459-9de1f73f9188
		summarizeBy: sum
		sourceColumn: sale_id
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		lineageTag: 2a21c871-3403-452d-92bf-73dd9c1096dc
		summarizeBy: sum
		sourceColumn: date_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: int64
		lineageTag: 7dbb943f-aad8-44ff-b0cc-1c83c8fed114
		summarizeBy: sum
		sourceColumn: customer_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		lineageTag: afab4ea1-3122-45e4-b600-09b1abbfb480
		summarizeBy: sum
		sourceColumn: product_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: int64
		lineageTag: 46707008-2575-4fc6-bca4-f5c788ac2743
		summarizeBy: sum
		sourceColumn: store_key
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 59948763-b899-43e2-a316-17ace1c08952
		summarizeBy: none
		sourceColumn: channel
		description: String column.

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: ea0dcd13-3b8a-4538-8262-a3c16a64c3db
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: 8a07d1ca-479a-48ad-a96a-a544335ff0bb
		summarizeBy: none
		sourceColumn: territory
		description: String column.

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 8e827428-231c-4c3a-9a69-0da79bd9399c
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country
		description: String column. categorized as Country.

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 0a5779e4-f6f3-4d1e-b24f-1297c594900f
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 8c3edfd5-1de9-4604-86b2-1a98ff7a9842
		summarizeBy: none
		sourceColumn: city
		dataCategory: City
		description: String column. categorized as City.

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: 527eac51-1095-475b-95eb-b24b72bc1c39
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode
		description: String column. categorized as PostalCode.

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: 949a885a-1b79-498b-80f1-bbd326e39828
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude
		description: Double column. categorized as Latitude.

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: 0231f224-06f5-4043-b543-e10ac7db0cbf
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude
		description: Double column. categorized as Longitude.

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		formatString: #,0.00
		lineageTag: 04617f9e-bb8e-4b94-91ad-f9f072adaac1
		summarizeBy: sum
		sourceColumn: quantity
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		lineageTag: aed90757-4661-416a-ab39-05fbbf762a90
		summarizeBy: sum
		sourceColumn: unit_price
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column unit_cost
		dataType: double
		formatString: #,0.00
		lineageTag: ca402608-7b50-4f72-abd1-6dd24aa79952
		summarizeBy: sum
		sourceColumn: unit_cost
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column discount_pct
		dataType: double
		formatString: #,0.00
		lineageTag: 4f11dc12-885c-4902-a37d-85fcb6551cb7
		summarizeBy: sum
		sourceColumn: discount_pct
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column tax_rate
		dataType: double
		formatString: #,0.00
		lineageTag: 2ef54d0a-8c32-456a-b734-4a3ecfb1467a
		summarizeBy: sum
		sourceColumn: tax_rate
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column shipping_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 81001cce-076c-4dd7-b7d7-516c98128cc8
		summarizeBy: sum
		sourceColumn: shipping_cost
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column currency_code
		dataType: string
		lineageTag: bd710499-188e-4283-8cf1-c8ddbdb8d517
		summarizeBy: none
		sourceColumn: currency_code
		description: String column.

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: d3a325f4-e4d7-43c2-8028-01fea740d1f8
		summarizeBy: none
		sourceColumn: order_status
		description: String column.

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: 04d04034-7030-4e16-a86b-fbcdc3486b42
		summarizeBy: none
		sourceColumn: payment_method
		description: String column.

		annotation SummarizationSetBy = Automatic

	column sales_rep
		dataType: string
		lineageTag: 161cb7f5-1364-47c5-bad2-1e3016ab6cce
		summarizeBy: none
		sourceColumn: sales_rep
		description: String column.

		annotation SummarizationSetBy = Automatic

	column promotion_code
		dataType: string
		lineageTag: acc392f8-c8d6-40f6-a8bd-f823ee9022c8
		summarizeBy: none
		sourceColumn: promotion_code
		description: String column.

		annotation SummarizationSetBy = Automatic

	column is_returned
		dataType: boolean
		lineageTag: f724bc2c-26d0-453c-bec8-e4331a08d2ae
		summarizeBy: none
		sourceColumn: is_returned
		description: Boolean column.

		annotation SummarizationSetBy = Automatic

	column 'Days Since First Order' = DATEDIFF(LOOKUPVALUE(dim_customer[first_order_date], dim_customer[customer_key], fact_sales[customer_key]), TODAY(), DAY)
		dataType: int64
		lineageTag: 78f98d13-f7f1-42ae-87b4-43f7cc6b73d7
		summarizeBy: none
		description: Calculated column (Int64).

		annotation SummarizationSetBy = Automatic

	column 'Full Location' = UPPER('fact_sales'[city]) & ", " & 'fact_sales'[state] & " (" & 'fact_sales'[country] & ")"
		dataType: string
		lineageTag: 92d80515-2164-4d37-a854-a252255b6173
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Discount Category' = IF(ISBLANK('fact_sales'[discount_pct]) || 'fact_sales'[discount_pct] = 0, "None", IF('fact_sales'[discount_pct] < 0.1, "Low", IF('fact_sales'[discount_pct] < 0.25, "Medium", IF('fact_sales'[discount_pct] < 0.5, "High", "Extreme"))))
		dataType: string
		lineageTag: 080d53e6-b12f-41f5-8c18-9ec36f41df7a
		summarizeBy: none
		description: Calculated column (String).

		annotation SummarizationSetBy = Automatic

	column 'Safe Discount'
		dataType: double
		formatString: #,0.00
		lineageTag: 411623ad-c1ac-4400-91fa-d20c4cf9d73e
		summarizeBy: none
		sourceColumn: 'Safe Discount'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	partition 'fact_sales-ca0117a6-49c5-479f-b61c-111ae586a13c' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"sale_id", "date_key", "customer_key", "product_key", "store_key", "channel", "region", "territory", "country", "state", "city", "postal_code", "latitude", "longitude", "quantity", "unit_price", "unit_cost", "discount_pct", "tax_rate", "shipping_cost", "currency_code", "order_status", "payment_method", "sales_rep", "promotion_code", "is_returned"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"fact_sales Table" = #"SALES"{[Name="fact_sales"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"fact_sales Table", {{"sale_id", "Sale ID"}, {"channel", "Channel"}, {"region", "Region"}, {"territory", "Territory"}, {"country", "Country"}, {"state", "State"}, {"city", "City"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"unit_cost", "Unit Cost"}, {"discount_pct", "Discount %"}, {"tax_rate", "Tax Rate"}, {"shipping_cost", "Shipping Cost"}, {"currency_code", "Currency"}, {"order_status", "Order Status"}, {"payment_method", "Payment Method"}, {"sales_rep", "Sales Rep"}, {"promotion_code", "Promotion Code"}, {"is_returned", "Returned?"}}),
				    #"Added Safe Discount" = Table.AddColumn(#"Renamed Columns", "Safe Discount", each if ([discount_pct] = null) then 0 else [discount_pct], type number),
				    Result = #"Added Safe Discount"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 30 columns and 31 measures: sale_id, date_key, customer_key, product_key, store_key, channel, region, territory, ... (30 columns total).

