table fact_sales
	lineageTag: a5c595f8-dd26-4e3e-831f-c7f9fce63d86

	measure 'Gross Revenue' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0e8bee04-50d6-4244-b7d0-4e62bf7fd591

	measure 'Net Revenue' = SUMX('fact_sales', IF('fact_sales'[order_status] <> "Cancelled" && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 21943497-bab1-4dd8-8248-beab9a216f82

	measure COGS = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_cost])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9dc92c3a-ca9a-4a43-9e31-22c0a94bc586

	measure 'Gross Profit' = [Net Revenue] - [COGS] - SUM('fact_sales'[shipping_cost])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f8d696b4-ada3-44d1-9676-cbd41006fa84

	measure 'Gross Margin %' = IF(ISBLANK([Gross Profit] / [Net Revenue]), 0, [Gross Profit] / [Net Revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9ebf786b-2315-40ed-a4d2-45cbfcf1ff0e

	measure 'Tax Amount' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]) * 'fact_sales'[tax_rate])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 263824b2-b1e4-4524-9b5f-33f49095c38b

	measure 'Total Revenue incl Tax' = [Net Revenue] + [Tax Amount]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7465d9a7-0fc7-49a3-a847-638da9255058

	measure 'Return Rate' = SUMX('fact_sales', IF('fact_sales'[is_returned] = TRUE, 1, 0)) / COUNT('fact_sales'[sale_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6017624a-f4f2-4b29-8077-df1fd6df1353

	measure 'Revenue per Customer' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_customer', 'dim_customer'[customer_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 200e6027-8660-4959-8bf5-e0dac1f9e889

	measure 'Revenue per Product' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_product', 'dim_product'[product_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9ee6b285-42fc-49f8-8fcf-71b02360859f

	measure 'Revenue by Region-Channel' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('fact_sales', 'fact_sales'[region], 'fact_sales'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: dce078d6-cbe2-4f7d-84f7-9bc7275dab00

	measure 'Revenue excl Territory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), REMOVEFILTERS('fact_sales'[territory]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a737bf7d-e40f-417c-945b-ea600f3fc6a4

	measure 'Revenue incl Subcategory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d4875b3f-4e88-48dc-9c72-a59b83cce9be

	measure 'Running Total Revenue' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), FILTER(ALLSELECTED('fact_sales'), TRUE())) /* RUNNING_SUM: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 5a64a347-f005-414f-ae31-cf4815e8ad0d

	measure 'Running Avg Revenue' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), FILTER(ALLSELECTED('fact_sales'), TRUE())) /* RUNNING_AVG: converted to cumulative — verify window scope */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2142d535-8dba-4df1-9793-ec300e0f5be5

	measure 'Running Count' = CALCULATE(SUM('fact_sales'[quantity]), FILTER(ALLSELECTED('fact_sales'), TRUE())) /* RUNNING_COUNT: converted to cumulative — verify window scope */
		displayFolder: Measures
		lineageTag: c1064216-8237-4ab9-89e2-51d5334bc852

	measure 'Revenue Rank' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		displayFolder: Measures
		lineageTag: 81aac0d2-ff9d-4246-aa4b-fe8172d3509d

	measure 'Revenue Rank Dense' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: 09ebe1f3-123b-4655-a8b6-6cc3b632a418

	measure 'Moving Avg 3-Period' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), WINDOW(-2, REL, 0, REL, ORDERBY('fact_sales'[sale_id], ASC)), ALL('fact_sales')) /* WINDOW.AVG: frame 'fact_sales'[-2,0] */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 55a233f8-53ae-47ed-b0a8-e421a802c040

	measure 'Window Max Revenue' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1ae0bd1d-9d9b-4b77-8003-3c3ac7adfd3a

	measure 'Revenue StdDev' = STDEVX.S('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 783b6294-0d0f-440f-9717-31fbce5fa71f

	measure 'Order Count' = DISTINCTCOUNT('fact_sales'[sale_id])
		displayFolder: Measures
		lineageTag: ac39a882-921a-4aca-91f1-d9158aee744c

	measure 'Unique Customers' = DISTINCTCOUNT('dim_customer'[customer_id])
		displayFolder: Measures
		lineageTag: d3e2c421-9b09-491d-9de8-9e5ef3894360

	measure 'Unique Products Sold' = DISTINCTCOUNT('dim_product'[product_id])
		displayFolder: Measures
		lineageTag: f550995c-480b-44b9-ac25-ddabaf7f5719

	measure 'Customer Tier' = IF([Revenue per Customer] > 100000, "Enterprise", IF([Revenue per Customer] > 50000, "Mid-Market", IF([Revenue per Customer] > 10000, "SMB", "Startup")))
		displayFolder: Dimensions
		lineageTag: 34c2c9d6-5368-49d6-a7f3-1bda4fbd0f22

	measure 'YTD Revenue' = CALCULATE(SUMX('fact_sales', IF('dim_date'[year] = YEAR(TODAY()) && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price], 0)), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d29fdd45-9523-4043-b56e-d5f141a98b87

	measure 'Is My Account' = 'dim_customer'[email] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 64702727-a31f-45c6-b914-20603dea85b0

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Regional Managers"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: bada5a11-c8c8-47f6-8b37-dc42b77b6d5c

	measure 'Analysis Start Date' = DATE(2024, 1, 1)
		lineageTag: 37c9e044-f78a-423c-a50a-5de3e55c008b

	measure 'Metric Selector' = "Revenue"
		lineageTag: 2d78fa3c-0666-45c8-8f46-150bedb8541e

	measure 'Display Currency' = "USD"
		lineageTag: 62fa30a9-d2d9-46fe-9f05-3e92a13db218

	column sale_id
		dataType: int64
		lineageTag: 82fd644f-8b46-41ba-ba24-9940ee469b4e
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		lineageTag: b8997278-e9d7-4cdc-8d0e-fc7dbb5f5b7e
		summarizeBy: sum
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: int64
		lineageTag: ac511e4f-7016-47b1-a596-5c1dc662e3a8
		summarizeBy: sum
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		lineageTag: 72ac99e3-db9f-455f-be50-7c0129fa9415
		summarizeBy: sum
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: int64
		lineageTag: c65affdf-fc69-4128-be9e-4771921296b5
		summarizeBy: sum
		sourceColumn: store_key

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 8b51a1d4-b410-45e5-aa52-08847edc9f11
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: b2748e25-ef22-483c-81ee-c3521e193708
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: dd60c855-9d73-47e9-91f8-04517e793697
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 257e9c6f-550c-43b4-abd1-31543372d84e
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: c8e6182e-82c8-43db-8fb7-ac13eec6e750
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 44ceae15-71a5-4782-9212-c985742293e1
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: fc02e28a-d555-4f5b-89bb-293e0e5d2261
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: 9921caba-eaf4-4943-b243-81f93155d11d
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: 9bfd785f-2486-4214-8d59-2b5dba911044
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		formatString: #,0.00
		lineageTag: 0e667f26-2a12-4fba-9307-81db04f77e9b
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		lineageTag: e8104a53-28a0-4fca-8d90-f9ef3b29ef08
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column unit_cost
		dataType: double
		formatString: #,0.00
		lineageTag: cf10ebf3-8f6b-4eea-86d4-bf4905994c6e
		summarizeBy: sum
		sourceColumn: unit_cost

		annotation SummarizationSetBy = Automatic

	column discount_pct
		dataType: double
		formatString: #,0.00
		lineageTag: 70d1b68c-2700-4c9d-b1af-bba075f10097
		summarizeBy: sum
		sourceColumn: discount_pct

		annotation SummarizationSetBy = Automatic

	column tax_rate
		dataType: double
		formatString: #,0.00
		lineageTag: dd0a4136-59b7-4b0c-b8b8-7da0254bd144
		summarizeBy: sum
		sourceColumn: tax_rate

		annotation SummarizationSetBy = Automatic

	column shipping_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 6b2bf424-68ad-4047-ab39-668906da369a
		summarizeBy: sum
		sourceColumn: shipping_cost

		annotation SummarizationSetBy = Automatic

	column currency_code
		dataType: string
		lineageTag: ae072139-5bf5-4e8c-949a-342e8f9c800a
		summarizeBy: none
		sourceColumn: currency_code

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: d2056842-d4e7-4c97-9611-c9f11470974d
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: 10c71b0e-b33d-4737-ae5a-366403c87833
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	column sales_rep
		dataType: string
		lineageTag: b9cf7a75-936b-4c78-a68c-a44f00c504dc
		summarizeBy: none
		sourceColumn: sales_rep

		annotation SummarizationSetBy = Automatic

	column promotion_code
		dataType: string
		lineageTag: 2c8bb331-7451-47a1-8e07-f5912e7b2553
		summarizeBy: none
		sourceColumn: promotion_code

		annotation SummarizationSetBy = Automatic

	column is_returned
		dataType: boolean
		lineageTag: 5c496298-07f4-47d6-a0f1-cdcc80032396
		summarizeBy: none
		sourceColumn: is_returned

		annotation SummarizationSetBy = Automatic

	column 'Days Since First Order' = DATEDIFF(LOOKUPVALUE(dim_customer[first_order_date], dim_customer[customer_key], fact_sales[customer_key]), TODAY(), DAY)
		dataType: int64
		lineageTag: a1d5d464-7e2f-409a-8fcf-b4cdae019598
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Full Location' = UPPER('fact_sales'[city]) & ", " & 'fact_sales'[state] & " (" & 'fact_sales'[country] & ")"
		dataType: string
		lineageTag: 94c60163-46ed-4554-ae71-a6409e14785e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Discount Category' = IF(ISBLANK('fact_sales'[discount_pct]) || 'fact_sales'[discount_pct] = 0, "None", IF('fact_sales'[discount_pct] < 0.1, "Low", IF('fact_sales'[discount_pct] < 0.25, "Medium", IF('fact_sales'[discount_pct] < 0.5, "High", "Extreme"))))
		dataType: string
		lineageTag: 626815ba-e030-4b02-9299-34370cd0206c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Safe Discount'
		dataType: double
		formatString: #,0.00
		lineageTag: 1aaf523c-a2c0-42c4-a4ce-f50b625b209a
		summarizeBy: none
		sourceColumn: 'Safe Discount'

		annotation SummarizationSetBy = Automatic

	partition 'fact_sales-5fc85fa2-69a1-4db4-851c-331f403d59c5' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"sale_id", "date_key", "customer_key", "product_key", "store_key", "channel", "region", "territory", "country", "state", "city", "postal_code", "latitude", "longitude", "quantity", "unit_price", "unit_cost", "discount_pct", "tax_rate", "shipping_cost", "currency_code", "order_status", "payment_method", "sales_rep", "promotion_code", "is_returned"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"fact_sales Table" = #"SALES"{[Name="fact_sales"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"fact_sales Table", {{"sale_id", "Sale ID"}, {"channel", "Channel"}, {"region", "Region"}, {"territory", "Territory"}, {"country", "Country"}, {"state", "State"}, {"city", "City"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"unit_cost", "Unit Cost"}, {"discount_pct", "Discount %"}, {"tax_rate", "Tax Rate"}, {"shipping_cost", "Shipping Cost"}, {"currency_code", "Currency"}, {"order_status", "Order Status"}, {"payment_method", "Payment Method"}, {"sales_rep", "Sales Rep"}, {"promotion_code", "Promotion Code"}, {"is_returned", "Returned?"}}),
				    #"Added Safe Discount" = Table.AddColumn(#"Renamed Columns", "Safe Discount", each if ([discount_pct] = null) then 0 else [discount_pct], type number),
				    Result = #"Added Safe Discount"
				in
				    Result

	annotation PBI_ResultType = Table

