table 'Target Margin %'
	lineageTag: d11ed138-7ea0-4275-9f5d-6e7d1a6346d5

	measure 'Target Margin %' = SELECTEDVALUE('Target Margin %'[Value], 0.20)
		lineageTag: 46bae666-04a0-431d-94b7-8a4777dd78b1
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin %'[Value], 0.20)

	column Value
		dataType: double
		lineageTag: 6030ccb0-1277-4801-82bb-95faee32946e
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin %-873a565b-01e9-4543-812c-f3d5905817a8' = calculated
		mode: import
		source = GENERATESERIES(0.00, 0.60, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

