table 'Target Margin %'
	lineageTag: bd28e12f-c7de-4e07-ab3f-6fb87dc3eeef
	description: Contains 1 columns and 1 measures: Value.

	measure 'Target Margin %' = SELECTEDVALUE('Target Margin %'[Value], 0.20)
		description: DAX: SELECTEDVALUE('Target Margin %'[Value], 0.20)
		lineageTag: 624a523c-d41e-45ec-b6b3-604562f1c9c1

	column Value
		dataType: double
		lineageTag: 1eb18bb5-2e04-4103-bb0e-08fe7971080c
		summarizeBy: none
		sourceColumn: Value
		description: Double column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin %-c4151b24-2a58-451b-b842-0c0fbb6cfca1' = calculated
		mode: import
		source = GENERATESERIES(0.00, 0.60, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

