table 'Target Margin %'
	lineageTag: cd36720f-e91c-431f-9e9e-70b3c469fa29
	description: Contains 1 columns and 1 measures: Value.

	measure 'Target Margin %' = SELECTEDVALUE('Target Margin %'[Value], 0.20)
		description: DAX: SELECTEDVALUE('Target Margin %'[Value], 0.20)
		lineageTag: 79206404-3b6f-472a-9753-88a03dee8277

	column Value
		dataType: double
		lineageTag: 5e849f20-d576-46c6-8a99-1945c6481176
		summarizeBy: none
		sourceColumn: Value
		description: Double column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin %-0f8cc9f8-3521-44e3-9e7b-be49e9fe7adc' = calculated
		mode: import
		source = GENERATESERIES(0.00, 0.60, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

