table 'Target Margin %'
	lineageTag: f6836136-4ece-461d-94bb-95896ab21a96

	measure 'Target Margin %' = SELECTEDVALUE('Target Margin %'[Value], 0.20)
		lineageTag: 9784f314-97ff-43b5-8d92-af687e71fb7a

	column Value
		dataType: double
		lineageTag: 8bfaed91-ee80-4832-a5e3-b9f6916535b6
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin %-64ae9fa9-179d-4195-97ae-eb0add47390a' = calculated
		mode: import
		source = GENERATESERIES(0.00, 0.60, 0.01)

	annotation PBI_ResultType = Table

