table 'Target Margin %'
	lineageTag: e0ec097d-2adc-42c9-b086-33feffb588cb

	measure 'Target Margin %' = SELECTEDVALUE('Target Margin %'[Value], 0.20)
		lineageTag: 31e85d47-02ef-45d0-9026-09433896e53c

	column Value
		dataType: double
		lineageTag: 585c25b4-107f-4f97-9859-01c5fc9a95ac
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin %-0895a703-b0ac-44a8-b595-5763f17f2d8f' = calculated
		mode: import
		source = GENERATESERIES(0.00, 0.60, 0.01)

	annotation PBI_ResultType = Table

