table 'Top N Items'
	lineageTag: 5bf9559c-a2d8-4513-8829-a9dc23e16794

	measure 'Top N Items' = SELECTEDVALUE('Top N Items'[Value], 15)
		lineageTag: 4f0614de-e18b-4690-8f8c-bc3ec96cd45b

	column Value
		dataType: int64
		lineageTag: acef1b5d-1e68-4ff1-8c4f-c64ebfa11aaf
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N Items-c68786d7-d47a-4c97-a915-d8c92a0d0713' = calculated
		mode: import
		source = GENERATESERIES(1, 100, 1)

	annotation PBI_ResultType = Table

