table 'Top N Items'
	lineageTag: ccfd722b-37d8-4067-88a6-5625f6cac6a7
	description: Contains 1 columns and 1 measures: Value.

	measure 'Top N Items' = SELECTEDVALUE('Top N Items'[Value], 15)
		description: DAX: SELECTEDVALUE('Top N Items'[Value], 15)
		lineageTag: c7650a5e-ee83-44e9-a903-a5eaab81c562

	column Value
		dataType: int64
		lineageTag: 0883a99e-794b-401e-aafa-d4ee52fa12e6
		summarizeBy: none
		sourceColumn: Value
		description: Int64 column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Items-7d89fecc-fa4c-4fb0-b232-38bc1f4a7f13' = calculated
		mode: import
		source = GENERATESERIES(1, 100, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

