table 'Top N Items'
	lineageTag: 0001c729-bfab-4796-868d-37fbb6ddac4a
	description: Contains 1 columns and 1 measures: Value.

	measure 'Top N Items' = SELECTEDVALUE('Top N Items'[Value], 15)
		description: DAX: SELECTEDVALUE('Top N Items'[Value], 15)
		lineageTag: 471dd43d-b4f3-4c7c-ac56-c1c730a9ac19

	column Value
		dataType: int64
		lineageTag: 282c0641-e1e7-4814-bcf6-c1a17fad937a
		summarizeBy: none
		sourceColumn: Value
		description: Int64 column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Items-109ee8b1-99c8-47d4-b3c4-94b08a287852' = calculated
		mode: import
		source = GENERATESERIES(1, 100, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

