table 'Top N Items'
	lineageTag: 4c07d6a7-c760-41ca-8ce9-44469bebc0d1

	measure 'Top N Items' = SELECTEDVALUE('Top N Items'[Value], 15)
		lineageTag: 2dc11c48-5c52-4497-8c62-ef4597114df4
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N Items'[Value], 15)

	column Value
		dataType: int64
		lineageTag: 847e690e-6a43-43f3-94b9-274c6745771f
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Items-bca6874c-80e3-4af0-8e76-948f8382b6ec' = calculated
		mode: import
		source = GENERATESERIES(1, 100, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

