table 'Top N Items'
	lineageTag: 5a8d29c9-19be-4d8e-b831-0c208473d51a

	measure 'Top N Items' = SELECTEDVALUE('Top N Items'[Value], 15)
		lineageTag: 674fbf93-d58a-4bbf-b12c-23d9f4faef83

	column Value
		dataType: int64
		lineageTag: 2f124d97-12e9-4e22-9bc7-fbffd9405c3d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N Items-9d7153b0-59ff-4d75-a178-dac2c73af738' = calculated
		mode: import
		source = GENERATESERIES(1, 100, 1)

	annotation PBI_ResultType = Table

