table 'Top N Items'
	lineageTag: c13c93e2-0844-421e-af2d-f85bf61ab909

	measure 'Top N Items' = SELECTEDVALUE('Top N Items'[Value], 15)
		lineageTag: 095e9af7-3680-41a8-aad0-0a38fc2a6cfd

	column Value
		dataType: int64
		lineageTag: e9314071-35e0-488a-aab6-941f53c10e2a
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N Items-ef34280c-83e4-4b72-b5e4-3b144903f6d1' = calculated
		mode: import
		source = GENERATESERIES(1, 100, 1)

	annotation PBI_ResultType = Table

