table Calendar
	lineageTag: f0d65c3c-946f-43d2-9ce9-a8ceafb377d7

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: e7943e2b-0bb6-4943-8acc-50e98306d9a2

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ba99a790-196f-44fd-9fe8-75a729c2547f

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 727e9a2e-b37b-4053-90a9-cee19b296d0a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fe43701d-958c-40e6-8eb1-5d63941b3c27
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1a832ffc-96e0-435e-8340-7d7d6825481f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 87d2623d-cdf7-4f39-a60f-672af229f9d8
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a98aa942-407f-499a-967d-bcd4fcd8a022
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 3bfc5bbe-5812-447b-afa3-f8e6d0742a75
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e7462406-1834-4b6d-b2ad-fb2129761e05
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e48461e4-a36d-4fc6-a910-342398c58f7a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9f4d3371-095f-437c-b098-142413f21343
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: fa880e64-a0a8-43eb-a569-3c054f12f90c

		level Year
			ordinal: 0
			column: Year
			lineageTag: 821fb6b0-5799-46f6-9d7e-23c5271e7b32

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: cfbf8c24-4572-46da-a14c-1e09aa05e1c9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3d26a865-8497-47be-b720-891e8717b68c

		level Day
			ordinal: 3
			column: Day
			lineageTag: de1afcdb-c892-4734-a25c-ee68d6133034


	partition 'Calendar-020e0ab4-82ee-4aa9-b284-1d8e0607f505' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

