table Calendar
	lineageTag: df0bc869-6115-4256-9728-0426e45f7a4f

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 576ee611-4160-432f-8f61-ea7befec25e8

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7e668438-7843-4158-b526-ac6388481fdf

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 891e01c6-675e-4cb9-8750-268c5ef70113

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e63a03e8-043a-437e-9ee8-c7bed97e698f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 4c8e6912-bceb-4340-bc2b-4e5b1908dbc2
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f58068c7-0fbc-438a-bcf5-272afdbadbbe
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 47da0249-c348-4627-b8d9-4e75baeccc08
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 98919b19-e8af-4b95-b535-fc4f0c761b07
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 5f0681a4-a109-4684-a831-ec589f667fc8
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 8b2469ee-f5c3-4e34-9dd9-9e98bef2525a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ba116975-4fd3-4dae-b1bb-e96e73b9a223
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 15d27477-f07f-4c9d-a163-6d685d68c133

		level Year
			ordinal: 0
			column: Year
			lineageTag: df8b2020-8fc5-480f-aa8d-25a6636db15c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 607cf188-6268-4574-b09c-7a399eb2436e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: af43d809-b3da-4215-b0e4-b38afa32c4c0

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6e3ed403-3e16-4750-8235-038b2fc0589f


	partition 'Calendar-f685f5c5-7116-422e-b061-2fe6e4df4f85' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

