table Calendar
	lineageTag: 2e0399c1-e789-487e-8dff-2969bbee7019

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 425511e2-d07b-41ab-b0fa-ce90291f3ce1

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 47fc9eea-72a8-46dd-9824-26cbdde6b5c2

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: d33bb863-e552-4b15-8d75-d2aa61a26b54

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4f57458c-03d6-4e2e-8677-6dc4664a9dfc
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9cb3d754-4b78-4107-8e7b-ec5829e5fc65
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: bb58b448-3295-4ae9-abb0-2a7581d7f0ab
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 746bebb3-8855-44d9-9d88-428760f8f693
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0580c448-475c-4075-aedd-597c165d8382
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 6f1bedba-779c-425e-93e1-3c0b69544bfc
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 138175f1-aee6-4569-a974-7d6c5075c27c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: db41a007-5c41-4780-8795-1f6165ae2786
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 25191d87-a855-4fa2-889e-46bd68616f9e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 65299b7b-067e-4265-b7c7-ff7be8df0e57

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 4a6951c1-8643-40f2-9ea9-c7b6e7ea2b93

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e97f5020-6b89-40f4-ace3-db985fc73f2e

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1a665882-afe2-4a9f-93fc-622b9f6a4740


	partition 'Calendar-0b158f73-9a4f-4977-ae77-21c1e80aad8c' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

