table Calendar
	lineageTag: 8941a1ea-8812-41c6-983f-008ac88986cd

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: df9d2ece-67c0-43f6-a627-7e63d2edda80

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: f59ab109-0aca-4532-a2c6-ca7f65580e5d

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 683b8fc6-e83c-4d88-b20d-6173c41e3f94

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4fa470ae-fb0f-42ff-b6b7-0fd14995ef34
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: cca660b4-ee28-41ac-9044-95022bdfb4c1
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: fcf44033-9535-4702-88d1-9f759c777631
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d62ebba1-6490-4473-aad8-f932d50fd5f2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 10d90b67-18ef-480d-a2ba-c8c4838a558d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ad73cbab-ace7-4ede-a2ef-8f98ccc341e4
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: fe9111c9-6945-4dda-8f00-a20dcadcf3bd
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 36831426-5410-41b7-8087-eaa6a8f2a7eb
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4c39b377-1ece-41eb-bd4c-c464c4d26bbc

		level Year
			ordinal: 0
			column: Year
			lineageTag: 25a90434-02b7-447a-89b5-bea3c54a7b42

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e9c26746-74f4-45ed-9026-3405029f1660

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1fd984e1-10a9-4f65-a7ac-ec1abdf371d3

		level Day
			ordinal: 3
			column: Day
			lineageTag: edbae454-7a49-49ae-9f6b-6630773ecf9f


	partition 'Calendar-62a68647-e6a3-4204-86c3-dfb044573251' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

