table Orders
	lineageTag: af2f10d8-1625-4e6a-ab56-3028df431b71

	measure 'Is Current User' = 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: daa507e0-4e6c-41e1-a78e-a964e60506c6

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: a87eb5d3-0673-45c9-970b-2c454faad0f7

	measure 'Region Match' = 'Regions'[RegionManager] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 74ea03a5-8f33-4510-9f66-e039eec54213

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 055e3d73-2300-443a-a70c-d096e994fdd7

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c0d48ef8-3f67-41f3-a1c4-2e30c3b0b35b

	column OrderID
		dataType: int64
		lineageTag: 4be0bb02-3e44-41ec-b89d-c23d538fe446
		summarizeBy: sum
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: ac302f4a-21f9-42aa-b4ce-bbc2f23c1f92
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: c669c8c7-a15d-4abe-a1d4-e5ca35602802
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 459a2055-f0f4-4cdb-9616-8e1630676bda
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column CustomerEmail
		dataType: string
		lineageTag: 3604aad2-02e9-4ff7-bd95-8a154564a6fc
		summarizeBy: none
		sourceColumn: CustomerEmail

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c59a41d9-2919-40b6-9b0a-4defd1fdcd1e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 790fcd4a-b45f-4b25-94af-30cf5c65169d
		summarizeBy: none
		sourceColumn: OrderDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Orders-de6ef609-f46d-4a81-881a-f56f443d0c24' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("localhost", "SalesDB"),
				    #"Orders Table" = Source{[Schema="dbo", Item="Orders"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Orders Table", {{"OrderID", "Order ID"}, {"CustomerEmail", "Customer Email"}, {"OrderDate", "Order Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

