table Calendar
	lineageTag: e7655486-9cf9-412a-970f-09a668af49de

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b322fb13-6bbf-443a-bfe9-09613e121b54
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 66ec3307-5766-44a8-b7cb-4fcd3e896cf6
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e6869560-5026-4bf7-a42a-2e124fb55c01
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: de620777-316e-4b25-8c30-63b1a6d2e2e8
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 74609c5a-3949-459d-a1ed-e7a2ad06aecd
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 21489a36-bf55-4158-8aaa-fa0705f5f95c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 8a7bc46a-4ef9-48e2-b721-4111c8516c40
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: bde6462d-c82a-44cd-a527-a7d6a643a804
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5815f1dd-008b-420c-afb8-765277ee157d

		level Year
			ordinal: 0
			column: Year
			lineageTag: 65f3c573-bad3-4bbd-a1db-2a052442be6b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3bf92f3b-88aa-4a62-b1d7-27c0faf10da5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c9147546-84f3-4899-a136-1da43a47e8e7

		level Day
			ordinal: 3
			column: Day
			lineageTag: d465d41c-451b-44cd-9e8a-4228ab1d0e69


	partition 'Calendar-14cab28d-eafc-43be-b36a-ca5947a60962' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

