table Calendar
	lineageTag: 0c3f0397-9125-4c21-b5e7-449165de0433

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a2238297-2967-4d66-8c35-0ddaa3da7ed9
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: da433ba6-0fcd-4aaa-8b11-d1ae6288e4a4
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1f0e9b35-f91c-4bb4-b670-909e722856c7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 47a2f591-1c18-4e1f-bee3-bbed904a60f2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 80b07119-90ef-4071-8821-414e9561c880
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bce228b2-16ef-48a6-907a-04b153599b09
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a155361b-d7b9-4510-8555-c05f81fc8b89
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 881a6f6e-c68c-444b-b757-1ad7fe67569a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e2a0a35c-ef43-4862-be4b-5e58a6f11275

		level Year
			ordinal: 0
			column: Year
			lineageTag: 06fb4796-06dd-4189-97b1-2df6cc2dfa08

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c5eedd4f-5cd0-4092-a1bb-d21a5e3921b2

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c27bc751-e0fd-4f63-810d-e19ff06d9475

		level Day
			ordinal: 3
			column: Day
			lineageTag: d9b58bf8-5b21-48c6-94ed-a99ea7db8c6e


	partition 'Calendar-170dacd7-b53d-4e05-97b5-48e9f1568a66' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

