table Calendar
	lineageTag: c7a8db8a-0d29-491d-99d2-fefa12efb1b2

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d062b94d-21dc-4abb-98f1-191971ed205e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e71a53b3-ff09-4312-b80a-670ca042b027
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ceb1df21-b036-40a0-a508-0c4eb8701071
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 110d50bf-060b-40c1-8acb-946c50b8ae86
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1f177b42-9bee-421f-a136-d8aa0a3931f1
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 69adb234-01b7-4d8c-a1af-3f72110fee34
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 925a6447-c20b-468d-85cd-2e53adb8c452
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e462d1c1-44fa-4c9e-9624-a427c3fa9a2f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5791de0c-15de-4aa0-a6a9-5a25e7475a4c

		level Year
			ordinal: 0
			column: Year
			lineageTag: 41266cea-4593-4f9b-99fc-5b2c5d69bf94

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: af1b2385-e8b5-45cd-be14-370070054757

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9294dc7c-9fba-45c2-9976-ba2bf7f530f6

		level Day
			ordinal: 3
			column: Day
			lineageTag: d0d1abd9-c912-43f2-9229-88ac05019950


	partition 'Calendar-ee8ca009-c5a0-46f6-a1ab-8c1a501f4616' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

