table Calendar
	lineageTag: a8acf658-48c6-4c72-8165-d0fec33093fc

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9f4bfb96-c3d9-4104-a6d3-5f4894be3d4e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 16936520-b047-49eb-ae87-569b2dd2ab19
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d669a2e6-f0ea-4eca-af8d-3fd3613f3ab0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c9545fd7-e99e-4f34-8348-89a42c19fbff
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 473956e8-7f44-4dff-ab15-472f053c5e3a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 826f3c6f-3903-439f-ab40-30db3c281f3f
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 090a4ec1-375c-4b0a-b9e6-6897471726fc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 21832c71-62d8-4386-9b24-6e6ee5ba4d92
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c7b4716c-32ab-44b8-a23f-e4ed79a71251

		level Year
			ordinal: 0
			column: Year
			lineageTag: 57f8eb7b-95ee-46ab-8cea-61d2b9abf97f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 14653280-74bd-4398-89db-746136d5aa64

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9c7d0552-95f7-4bcf-84b3-86b85fa601f7

		level Day
			ordinal: 3
			column: Day
			lineageTag: 59822157-fe57-41c5-9a15-e1704533d8a9


	partition 'Calendar-d1854d38-f16d-4f31-90ce-352a41a5ab97' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

