table Calendar
	lineageTag: 288a6270-3007-487f-ae76-76c34f89e6cb

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c8548775-4c49-406d-84cb-5bdd7e396e7e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e7921283-7fb0-4a77-9bfb-e4d27fa8c7f4
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: bf53b426-4b5f-4cf1-b66e-5ac212f8ad7c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 94150321-8b8e-4ec5-9fc5-78077c94d3b1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 67f10bf5-ad9b-445c-9b38-b44fd1e9e4ba
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1a870538-3fb6-4668-bc9a-a7b3a1b4c04d
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 647c8178-d23f-4328-87df-6ee4db311cd9
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 6aa54dfd-4472-465c-bccf-07814245d13d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b75713b7-46a8-4ff8-9379-1ffb204895ef

		level Year
			ordinal: 0
			column: Year
			lineageTag: c2401c95-eb46-4a1d-b6fe-c761958dd593

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: de7281df-0f6a-4475-9829-796a75f96cd9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 908a3005-b599-42b1-a69b-ef9a9b8a22c3

		level Day
			ordinal: 3
			column: Day
			lineageTag: 830d7012-2581-4115-bac3-e85e7b4d795f


	partition 'Calendar-54bf9aa1-708c-48f0-a1b9-dd184e6a4284' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

