table Calendar
	lineageTag: 34ea93ff-937e-4d6b-95d6-4c8c6249b814

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fd06bc84-38ea-499d-b3d4-448bb828545d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 423883f8-6bdc-4017-a13b-dac42ec865f3
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ed4bc25c-46ab-4174-adde-83a2ed0e74f2
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d5178452-025d-403e-b1f7-85b9fbcae959
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1189c7a0-7235-4a4a-8ca9-7f6e0e28a2c9
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 212256ac-7573-4f7a-bf42-e4c53aed5bd6
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 9b4e44e4-af35-4875-b7b5-b9b936c58b5e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: bf778048-b555-4b03-930c-37b4b10658c4
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 796545c9-840b-4493-b49b-17f339ebe053

		level Year
			ordinal: 0
			column: Year
			lineageTag: 66f5f464-9398-4eb8-a676-8369a6bd0fc6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: fa0086ce-6617-49b8-896a-f2fa92ce3d7d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8e8f4792-e7a0-4ab3-9998-dd72e2af747c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 0c8f5c66-f44e-4597-9a7d-030722a30da3


	partition 'Calendar-2479af64-ef14-4c80-be08-eade5da26a00' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

