table Calendar
	lineageTag: 82fa4d40-7f11-4463-a810-c95b54146a8a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a78d71fa-22b1-436e-a41e-1048e5243b00
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2ff6d182-e039-47bf-8211-e2feae92e7d6
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 72468a59-714f-404f-98d7-fcd0df37ad9c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 1e17c1aa-8c64-4b24-bd63-db8de6884f70
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f3f87e33-afd3-4501-a418-f23a7ada4442
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 2f46ed86-87fd-4156-accb-2d4b4a850ca5
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 13bd5dfa-5e4b-453e-baf7-ad5e318f99d8
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 62dc7650-f9fa-48ff-bf21-a9eead9f0fc5
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1048fe6f-33e5-44b6-88c7-9d86bb962602

		level Year
			ordinal: 0
			column: Year
			lineageTag: 972a64c8-364a-436a-8cc3-e27eddbdcb50

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: bd142578-09f5-45f7-b7a5-11c1bdc1354e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4f6dd71e-2330-4588-b3fe-62578cef19a6

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4e7e3acb-0ea3-4248-959d-bff592837bd1


	partition 'Calendar-bdbfb393-5af3-4914-9cfa-274ad1744fa5' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

