table Calendar
	lineageTag: 7b8681be-1ed7-41c0-a6f6-4e6f680a5b70

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a172f5a6-ebcd-4d01-bd63-f51a27cd7b0a
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b51bebf3-8ed7-4fba-bc65-7b42d882cdc2
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e7dbf0c2-e17d-4c18-8d6d-1a19797bf91c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: bb170147-0e54-4ad3-9081-ae82f94048fd
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a2d0c554-f1ed-4041-aea4-2f7cdfc797f5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3c6698ae-8c8a-4f51-aada-0a56138cd829
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 998732dc-340d-4ecc-b0b8-f2710091a5f1
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: de2936ab-b177-4fed-9911-1f6dc56ddc58
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: cf0470ba-3077-481a-96a4-c7c6e7a1f8da

		level Year
			ordinal: 0
			column: Year
			lineageTag: 8931f525-d1de-485e-ba40-a0286385bfb7

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: a1ad6648-f78f-46f2-919c-89ac19ba2b03

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1d501295-ccf1-4a14-97d8-5a0ab34c8231

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3f4390dc-da61-4994-8acf-09f84ef7ad46


	partition 'Calendar-962cb5bb-c84e-4ed0-b071-20c98c06005f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

