table Calendar
	lineageTag: 78a93a72-dbac-400c-a0fe-1aea8fe37645

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 958404fc-efa5-4f6c-875c-4f0b4932dbfb
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 3908bfef-bffc-44ae-be2c-d93d0b1ac73b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dda551e4-b167-47ab-a443-09ad72fa5401
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 0844b7fe-06fa-4fa6-86e1-5127a8e3bb45
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 23cb4577-d971-48dd-b060-c36973aec5a8
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e2b23f75-ea97-44c4-a9cd-9856faa7ea8e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4fa9939a-694c-484e-98f7-fe09d5903967
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2a91f578-e122-4ebd-ab98-12238e50b20f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6c9a9660-e9ac-45f8-b2a7-3ebefbb94592

		level Year
			ordinal: 0
			column: Year
			lineageTag: 8b0a5c4e-ee5e-49d8-8b2c-c8682d647f2a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c7103c64-de02-4de5-9e84-1762d6ac7f34

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8351eac9-a99e-4a7e-9a2d-ad0a982848a4

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3c4079d3-bbd3-427e-9a02-5a42520b8215


	partition 'Calendar-25e9e989-b51a-4a86-9ada-42da51dbe451' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

