table Calendar
	lineageTag: 4d9994d5-3491-4eee-8e8a-1424dee1acc4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 10c9a60c-c596-42a9-8e21-5cd9a456dd18
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 83348a47-d7d7-446d-ba34-b1aee0567019
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4fe32e87-eec1-46be-b186-b7f510a4162a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2821768a-4497-4843-901d-77f975eba34e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: bd6a4ff6-827b-4c37-a063-32d049a46bb5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f8ab1f7a-cf50-4959-aa7e-458b25cd9369
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e7f32f67-442f-4a7c-9948-143c2c6714cf
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 936a6095-c6a6-497b-a805-052a41809a5f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: bed179c8-a9ad-4678-9423-4491b383d361

		level Year
			ordinal: 0
			column: Year
			lineageTag: 93c2cd4b-9c54-4a93-b04e-80f84a3a68a7

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 0ac984c3-21d3-4d39-a38b-486737d9754e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: fb81ea11-73d0-4373-b1ff-80639e7e71f7

		level Day
			ordinal: 3
			column: Day
			lineageTag: c742c9ea-8dfc-4005-8a25-9893a7f13a0a


	partition 'Calendar-90fad7ce-4f68-4235-ab4d-906d8e063362' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

