table Calendar
	lineageTag: 47aed5e5-1a4a-4044-ae43-2aab899412e0

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ff5739eb-8136-44ce-b11f-d193b7a5ac84
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b96cab9a-3833-49ed-8287-a9fe3f2c72eb
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7e971d4a-0c31-491d-8e26-1dab5f2e3bf7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 97bf3ac8-65e9-4bac-ac1a-2d44b5df6e65
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 781704b9-1434-46a9-916f-2b1f999db4a2
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1aac4699-6d05-4969-b4fa-48831d90b9f2
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 592da9da-b7ad-44c4-80e0-1583f9b8038f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: fb80b99d-2265-40ad-8430-bb31ae577d26
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7fd51cb0-13e5-42fc-af9f-6d1e7a549e79

		level Year
			ordinal: 0
			column: Year
			lineageTag: ee96c240-c1df-4cd9-a3b9-6616cc46f812

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 1a432b31-b8f2-47da-913d-c53027917d46

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7065599c-3c7b-460d-a22c-e35908de958f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 87318053-c9a1-4310-a753-868168c3c1d3


	partition 'Calendar-61d88205-c5ff-4778-ac05-0f741875daa0' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

