table Extract
	lineageTag: 5a00730a-aa78-46a0-af90-5434861598f5
	description: Contains 23 columns: Row ID, Order ID, Order Date, Order Priority, Order Quantity, Sales, Discount, Ship Mode, ... (23 columns total).

	column 'Row ID'
		dataType: int64
		lineageTag: 261be027-8aad-48dc-93f1-f4264ab329db
		summarizeBy: sum
		sourceColumn: 'Row ID'
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: int64
		lineageTag: b1205676-12b5-4946-a3f9-be8f4cf86ec2
		summarizeBy: sum
		sourceColumn: 'Order ID'
		description: Int64 column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b750fd4d-f4a9-4800-8c7a-35a0025d73ab
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: 17a01bf3-94b5-4501-b99c-056a68336d99
		summarizeBy: none
		sourceColumn: 'Order Priority'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		lineageTag: 393ba99e-d387-4a49-9762-156f5c411985
		summarizeBy: sum
		sourceColumn: 'Order Quantity'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: fb63ffe8-6a5e-4164-8507-39be3c499594
		summarizeBy: sum
		sourceColumn: Sales
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 79a45737-1e02-4ce9-93be-2425c8bba109
		summarizeBy: sum
		sourceColumn: Discount
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 4aea5386-728a-4614-a886-7c09ff1c9c8c
		summarizeBy: none
		sourceColumn: 'Ship Mode'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 2cd3de22-23c0-474f-ac07-1582049f015a
		summarizeBy: sum
		sourceColumn: Profit
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: #,0.00
		lineageTag: 92e010b5-1e5b-4751-8803-1f82a7329e0a
		summarizeBy: sum
		sourceColumn: 'Unit Price'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: double
		formatString: #,0.00
		lineageTag: c7fba25a-a733-4d71-bd21-df289f0b82b0
		summarizeBy: sum
		sourceColumn: 'Shipping Cost'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 41b6e416-398d-453d-9133-255d4e976f27
		summarizeBy: none
		sourceColumn: 'Customer Name'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 814115f1-ac13-4d1a-b9a1-c44b6f2c96cf
		summarizeBy: none
		sourceColumn: City
		dataCategory: City
		description: String column. categorized as City.

		annotation SummarizationSetBy = Automatic

	column 'Zip Code'
		dataType: string
		lineageTag: bd6a21f8-ea2c-42f5-9cb6-c2baa154ac7d
		summarizeBy: none
		sourceColumn: 'Zip Code'
		dataCategory: PostalCode
		description: String column. categorized as PostalCode.

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 4d9dd86f-d4cb-4821-a3cc-f9b3eb385bd5
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: c3588ffc-7c4f-4f7a-9267-265beabf54d7
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince
		description: String column. categorized as StateOrProvince.

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 1fa48eee-0c62-4f69-acc2-bbbbfa5e456a
		summarizeBy: none
		sourceColumn: 'Customer Segment'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: 1d2f601d-2085-4a43-a823-0792f652a303
		summarizeBy: none
		sourceColumn: 'Product Category'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Category'
		dataType: string
		lineageTag: b5036cf8-a40b-455c-8d9a-0fcfac0d0a97
		summarizeBy: none
		sourceColumn: 'Product Sub-Category'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: a0223bf3-8f9a-4752-9af7-90abe324d1c8
		summarizeBy: none
		sourceColumn: 'Product Name'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Product Container'
		dataType: string
		lineageTag: 81692967-fbac-42e7-ae5a-6d601a61ecee
		summarizeBy: none
		sourceColumn: 'Product Container'
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Product Base Margin'
		dataType: double
		formatString: #,0.00
		lineageTag: 58c80b4d-9ac0-4f33-af8c-0bfe98cce54f
		summarizeBy: sum
		sourceColumn: 'Product Base Margin'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8679cb0e-2557-499d-9eca-9fa5f2f63590
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	partition 'Extract-418a0f38-52db-47f1-8711-0779640f9262' = m
		mode: import
		source =
				let
				    // Source Excel: Extract.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Extract.xlsx"), null, true),
				
				            _nav = _src{[Item="Extract",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Order Priority", "Order Quantity", "Sales", "Discount", "Ship Mode", "Profit", "Unit Price", "Shipping Cost", "Customer Name", "City", "Zip Code", "State", "Region", "Customer Segment", "Product Category", "Product Sub-Category", "Product Name", "Product Container", "Product Base Margin", "Ship Date"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", Int64.Type},
				        {"Order Date", type date},
				        {"Order Priority", type text},
				        {"Order Quantity", Int64.Type},
				        {"Sales", type number},
				        {"Discount", type number},
				        {"Ship Mode", type text},
				        {"Profit", type number},
				        {"Unit Price", type number},
				        {"Shipping Cost", type number},
				        {"Customer Name", type text},
				        {"City", type text},
				        {"Zip Code", type text},
				        {"State", type text},
				        {"Region", type text},
				        {"Customer Segment", type text},
				        {"Product Category", type text},
				        {"Product Sub-Category", type text},
				        {"Product Name", type text},
				        {"Product Container", type text},
				        {"Product Base Margin", type number},
				        {"Ship Date", type date}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 23 columns: Row ID, Order ID, Order Date, Order Priority, Order Quantity, Sales, Discount, Ship Mode, ... (23 columns total).

