table Extract
	lineageTag: da11ae5f-c920-4d8f-ac29-7d3bb2ddb6bb

	column 'Row ID'
		dataType: int64
		lineageTag: 37e0b62d-d56b-4cab-a838-e587d4017a05
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: int64
		lineageTag: abdfff43-ff23-4d0f-ab23-d7f653ab39b2
		summarizeBy: sum
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7ece3988-f096-4a2d-94cb-43133697ded7
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: 0f9d3b52-f567-483a-9430-646736602b25
		summarizeBy: none
		sourceColumn: 'Order Priority'

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		lineageTag: aa7d634f-3cba-4873-8f67-23413c3ce28b
		summarizeBy: sum
		sourceColumn: 'Order Quantity'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: d9ab0db1-ea55-4d38-9d48-5d94a2368b09
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 1c683ff0-d73d-4952-b2ec-e5d8c57e330f
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 27700791-0199-4483-b389-093eae747e51
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 6cf70078-223d-40e1-8dcb-11b94c5349e7
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: #,0.00
		lineageTag: c18caeb7-0137-457a-973e-4ab467193c20
		summarizeBy: sum
		sourceColumn: 'Unit Price'

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: double
		formatString: #,0.00
		lineageTag: 5956c1d3-3cd5-43ff-8d2f-3aabbd5a2863
		summarizeBy: sum
		sourceColumn: 'Shipping Cost'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 6b9a3a22-223a-4d60-b49b-79bb7d7a978e
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: ba9121ea-ee13-456e-a3b8-c3f7b502c5cd
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column 'Zip Code'
		dataType: string
		lineageTag: fdb15213-4f5f-4fbb-9a42-678159dee3ff
		summarizeBy: none
		sourceColumn: 'Zip Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: f61a9674-83e4-43c8-bdae-c56c1c764e29
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: d626cee2-7f10-46be-9917-0cea2458deef
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 39e2f0d0-7231-4965-9688-f4baab3ecc44
		summarizeBy: none
		sourceColumn: 'Customer Segment'

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: d42a2349-647a-4f7a-b756-514c228f8b64
		summarizeBy: none
		sourceColumn: 'Product Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Category'
		dataType: string
		lineageTag: 13dd135d-a358-4af6-b2b4-62a3434c4f61
		summarizeBy: none
		sourceColumn: 'Product Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: d3ee8744-97ad-40dd-8b9f-0e4aa048958b
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column 'Product Container'
		dataType: string
		lineageTag: 06f166f9-e731-493d-a540-16a7ca0db619
		summarizeBy: none
		sourceColumn: 'Product Container'

		annotation SummarizationSetBy = Automatic

	column 'Product Base Margin'
		dataType: double
		formatString: #,0.00
		lineageTag: 0aaa5e99-6385-4186-a187-2e1739586714
		summarizeBy: sum
		sourceColumn: 'Product Base Margin'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: f509daa6-d3d8-4e15-a3b7-2490dc918fed
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Extract-c2c799cb-bb5f-420f-b798-49adb933faba' = m
		mode: import
		source =
				let
				    // Source Excel: Extract.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Extract.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Order Priority", "Order Quantity", "Sales", "Discount", "Ship Mode", "Profit", "Unit Price", "Shipping Cost", "Customer Name", "City", "Zip Code", "State", "Region", "Customer Segment", "Product Category", "Product Sub-Category", "Product Name", "Product Container", "Product Base Margin", "Ship Date"}, {}),
				    #"Extract Sheet" = Source{[Item="Extract",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Extract Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", Int64.Type},
				        {"Order Date", type date},
				        {"Order Priority", type text},
				        {"Order Quantity", Int64.Type},
				        {"Sales", type number},
				        {"Discount", type number},
				        {"Ship Mode", type text},
				        {"Profit", type number},
				        {"Unit Price", type number},
				        {"Shipping Cost", type number},
				        {"Customer Name", type text},
				        {"City", type text},
				        {"Zip Code", type text},
				        {"State", type text},
				        {"Region", type text},
				        {"Customer Segment", type text},
				        {"Product Category", type text},
				        {"Product Sub-Category", type text},
				        {"Product Name", type text},
				        {"Product Container", type text},
				        {"Product Base Margin", type number},
				        {"Ship Date", type date}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

