table Orders
	lineageTag: 9b128c5a-9ab7-49e9-9ebb-2cc23d61162c

	column 'Row ID'
		dataType: int64
		lineageTag: c789b23c-aeb5-43e0-98d0-9d8ff0886e69
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: int64
		lineageTag: 5c0188d2-6449-4c60-8a17-c1b633bd52aa
		summarizeBy: sum
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 49905690-1280-40ca-aa26-4b1f9126f929
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: fc0351d0-54e8-439e-a9dd-509534b1022b
		summarizeBy: none
		sourceColumn: 'Order Priority'

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		lineageTag: 8fc38afd-29ad-4b8c-8828-70b5cb74eff7
		summarizeBy: sum
		sourceColumn: 'Order Quantity'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: c7215e27-50ff-48b9-9411-2a314264c0f0
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 1f9ca2c4-5a05-44d0-a188-98ffe6d1ee26
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 94dfcd37-973b-4b03-b10f-d7db3b4172e1
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 3574a9c4-13ed-471c-a6b7-1a363fba4aa0
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: #,0.00
		lineageTag: 2eed1a4f-3d11-4af6-aea8-a082bc45b390
		summarizeBy: sum
		sourceColumn: 'Unit Price'

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: double
		formatString: #,0.00
		lineageTag: 998376e4-7c5f-425a-83e6-c2198dcb2982
		summarizeBy: sum
		sourceColumn: 'Shipping Cost'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 9a5ca1f9-4bae-4bdc-a090-cf1303909321
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 2a473f25-6e87-4de9-a7fd-b0d144643641
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column 'Zip Code'
		dataType: string
		lineageTag: 976648e4-4b56-48c5-a9f0-397c84d7bc1f
		summarizeBy: none
		sourceColumn: 'Zip Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 61fe101d-4fcc-4700-ad36-db56b101f8a1
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3f877f7a-2551-49a6-ba2e-9f76b76b0978
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 065800d1-4504-4902-9122-474d019be4b1
		summarizeBy: none
		sourceColumn: 'Customer Segment'

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: 795dbe5f-f5dc-47ef-a6d6-6cc1af13ee13
		summarizeBy: none
		sourceColumn: 'Product Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Category'
		dataType: string
		lineageTag: 1125d24a-42ea-45a6-8062-185b956a67bb
		summarizeBy: none
		sourceColumn: 'Product Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 9a13126c-4352-4ac9-9425-d7ae3a9eaef2
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column 'Product Container'
		dataType: string
		lineageTag: 6fb589b2-7874-413c-951e-2519a5acd96b
		summarizeBy: none
		sourceColumn: 'Product Container'

		annotation SummarizationSetBy = Automatic

	column 'Product Base Margin'
		dataType: double
		formatString: #,0.00
		lineageTag: fba819dc-d570-48be-a100-a6d5e7fe76de
		summarizeBy: sum
		sourceColumn: 'Product Base Margin'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: a10a39c0-e317-4e32-9e7d-71db95a9136b
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Grouping Based on Unit Price'
		dataType: string
		lineageTag: f01b55c8-4cf5-429e-b830-55fd7bb9cde0
		summarizeBy: none
		sourceColumn: 'Grouping Based on Unit Price'

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: 665cc751-59a5-41c6-8d03-c52b4a8c0363
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Orders-00542537-05c4-4657-a087-a881d4d7336e' = m
		mode: import
		source =
				let
				    // Source Excel: Orders.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Orders.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Order Priority", "Order Quantity", "Sales", "Discount", "Ship Mode", "Profit", "Unit Price", "Shipping Cost", "Customer Name", "City", "Zip Code", "State", "Region", "Customer Segment", "Product Category", "Product Sub-Category", "Product Name", "Product Container", "Product Base Margin", "Ship Date"}, {}),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", Int64.Type},
				        {"Order Date", type date},
				        {"Order Priority", type text},
				        {"Order Quantity", Int64.Type},
				        {"Sales", type number},
				        {"Discount", type number},
				        {"Ship Mode", type text},
				        {"Profit", type number},
				        {"Unit Price", type number},
				        {"Shipping Cost", type number},
				        {"Customer Name", type text},
				        {"City", type text},
				        {"Zip Code", type text},
				        {"State", type text},
				        {"Region", type text},
				        {"Customer Segment", type text},
				        {"Product Category", type text},
				        {"Product Sub-Category", type text},
				        {"Product Name", type text},
				        {"Product Container", type text},
				        {"Product Base Margin", type number},
				        {"Ship Date", type date}
				    }),
				    #"Added Grouping Based on Unit Price" = Table.AddColumn(#"Changed Types", "Grouping Based on Unit Price", each if [Unit Price] <= 2500 then 'A' else if [Unit Price] <=5000 then 'B' else 'C', type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Grouping Based on Unit Price", "Action (Region)", each [Region], type text),
				    Result = #"Added Action (Region)"
				in
				    Result

	annotation PBI_ResultType = Table

