table Orders
	lineageTag: 50511d94-a432-4094-8cc7-1ed9d67e6346

	column 'Row ID'
		dataType: int64
		lineageTag: b6c38fd7-23cd-4916-b4da-1b43fc1e848a
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: int64
		lineageTag: ad25a1c9-383d-4d92-887d-cf0c9f2b804c
		summarizeBy: sum
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 090deb40-f571-4381-9fb5-f891e273c8ac
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: 50986fe7-a0b1-4dbf-95f1-34edcc98c093
		summarizeBy: none
		sourceColumn: 'Order Priority'

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		lineageTag: 9d208cfa-477d-46fe-b73a-5b60f877f814
		summarizeBy: sum
		sourceColumn: 'Order Quantity'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 36794f3e-830c-4fcf-9b12-5ba9f044d8eb
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 28ab0a72-58a7-4e17-903b-ce733ecd5112
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: ff5bde26-8f79-461d-ab25-7def9447b03e
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: ed78d4ae-c081-402b-9ac2-fe7ad18b9b86
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: #,0.00
		lineageTag: d86139d4-7cb1-40a1-910f-a25e02a9a01e
		summarizeBy: sum
		sourceColumn: 'Unit Price'

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: double
		formatString: #,0.00
		lineageTag: ccca36f9-aa28-4f19-9321-55816db2e720
		summarizeBy: sum
		sourceColumn: 'Shipping Cost'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 1dcdfa9b-f7d2-4752-b569-b1c7a46a6b1a
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: a4995b42-fb8d-4ec4-898b-d6566f7c5a48
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column 'Zip Code'
		dataType: string
		lineageTag: 2a66c158-b41b-4f26-b99c-83f2ad53784f
		summarizeBy: none
		sourceColumn: 'Zip Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: cf5a7da5-4cc1-48d3-bfc4-afb1de2c3e94
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 1e8cddaa-6bf6-4ae2-9588-dfeb59dba1c5
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 9222a305-5d9c-4475-8b6e-b37a5a814da8
		summarizeBy: none
		sourceColumn: 'Customer Segment'

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: 4b2471a9-b551-4f22-b85f-604535222bed
		summarizeBy: none
		sourceColumn: 'Product Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Category'
		dataType: string
		lineageTag: 5661830d-f541-44a5-9d5f-f4bf8ec69747
		summarizeBy: none
		sourceColumn: 'Product Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 84dde565-1acb-4297-bcb3-4a45fd663991
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column 'Product Container'
		dataType: string
		lineageTag: b59eccf9-162f-4460-8245-5f0a88aaca27
		summarizeBy: none
		sourceColumn: 'Product Container'

		annotation SummarizationSetBy = Automatic

	column 'Product Base Margin'
		dataType: double
		formatString: #,0.00
		lineageTag: 52d0ecf0-4ad9-4f1a-81f3-445828289b6a
		summarizeBy: sum
		sourceColumn: 'Product Base Margin'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 40ff855d-af54-438a-a8f7-949f4191c5d2
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Grouping Based on Unit Price'
		dataType: string
		lineageTag: 0aaa0954-33d1-4576-8462-dac9d975cb07
		summarizeBy: none
		sourceColumn: 'Grouping Based on Unit Price'

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: 0b5bd99a-7f66-4843-971b-c0d428f9dffa
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Orders-996f31c4-f0aa-4247-a2e0-a23b285e1f8f' = m
		mode: import
		source =
				let
				    // Source Excel: Orders.xlsx
				    Source = Excel.Workbook(File.Contents(DataFolder & "\Orders.xlsx"), null, true),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", Int64.Type},
				        {"Order Date", type date},
				        {"Order Priority", type text},
				        {"Order Quantity", Int64.Type},
				        {"Sales", type number},
				        {"Discount", type number},
				        {"Ship Mode", type text},
				        {"Profit", type number},
				        {"Unit Price", type number},
				        {"Shipping Cost", type number},
				        {"Customer Name", type text},
				        {"City", type text},
				        {"Zip Code", type text},
				        {"State", type text},
				        {"Region", type text},
				        {"Customer Segment", type text},
				        {"Product Category", type text},
				        {"Product Sub-Category", type text},
				        {"Product Name", type text},
				        {"Product Container", type text},
				        {"Product Base Margin", type number},
				        {"Ship Date", type date}
				    }),
				    #"Added Grouping Based on Unit Price" = Table.AddColumn(#"Changed Types", "Grouping Based on Unit Price", each if [Unit Price] <= 2500 then 'A' else if [Unit Price] <=5000 then 'B' else 'C', type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Grouping Based on Unit Price", "Action (Region)", each [Region], type text),
				    Result = #"Added Action (Region)"
				in
				    Result

	annotation PBI_ResultType = Table

