table 'Alert Threshold'
	lineageTag: 8be9f830-9ae4-406a-bd28-2aa90b67aa87

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: a5f42ba6-7782-42b4-bfd4-c6df75745c05

	column Value
		dataType: double
		lineageTag: fd63be52-2b4b-46f2-994f-d6dd64f5c556
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-b96c526a-9bd8-4064-910a-f2a57c0f3b86' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

