table Calendar
	lineageTag: 50131070-cdae-44d6-8cdf-51ff8c9f37ae

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 11ccfeb7-6129-4780-9119-cff7f7ad987f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c39ab8fc-38d5-4ff4-8a33-73ddecf6febb
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 861b34d2-4ab4-4f86-9b10-55ebf2d543f3
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: bbeeea86-4e41-4b1f-a52d-482f4bfc95f0
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0ded5bb1-42a4-402f-982e-db11a6f77172
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a99c67d7-c1d3-4db2-9951-4e836bc5de47
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 04d651bc-3231-4d42-88cd-3f221962a4f0
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: db4ec5be-7345-4989-8c64-1be3b7d38c1b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 0344f5e0-699e-48b1-ae8a-e827da67efa9

		level Year
			ordinal: 0
			column: Year
			lineageTag: ad5af7e2-8eca-437e-9ff9-1f997204fc37

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b641f9ce-2aab-4682-8415-abc73acc7bcf

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7e3785dd-e8c3-4de2-bd14-9df3cc91d0d4

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3e6c580d-c12c-4e84-8f36-6c47ad67b0b5


	partition 'Calendar-939eacdb-afdd-4ae4-ad0a-cb27fbd449e6' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

