table Calendar
	lineageTag: 9fde3583-78a8-4aba-95f2-124a865f0c1d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3fa55ae4-0e93-47ad-8799-1a3ffc6033b5
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 6567dc53-f9f4-4602-a591-d60052fb94ae
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 95b4a541-d9b3-4268-a8f4-a3e535b9931c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 674945f5-45a0-4f8a-ad4d-b332fbe475ca
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 188ad901-9a6b-4e83-89c5-a0ffea99f4f3
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d209d57d-6598-4e46-92df-b55d4b4997cb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 60505c08-4f6e-4e1d-8c01-3d854bdfe1c3
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 50a98f49-6d12-4ffa-b925-e9bcd021d4f5
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ca67ed27-1fcd-465e-b94b-7b839f4e6fbb

		level Year
			ordinal: 0
			column: Year
			lineageTag: ff1811f5-1448-4256-b7b4-951aac8f94f4

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: cc8a2b8e-961e-42df-9dd2-9a32f1050638

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6d623730-aa1f-43c5-9036-6595ab4707e2

		level Day
			ordinal: 3
			column: Day
			lineageTag: e9851585-4d5a-4eed-a45e-58c8845b310b


	partition 'Calendar-5493d1cf-c20b-4334-97a9-e2f1dc2f6e60' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

