table Calendar
	lineageTag: e9440a27-be70-4837-8682-3dab145080c1

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6ea41ed1-e3c1-435c-90bb-4da2bfeed3be

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 2d2736e6-e9a1-4b5e-aa67-192ff0ed521c

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 8c08007e-6999-4bf2-85cf-c62f9510f2c6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: decaef62-18a3-45ad-ac7b-bb714ee66a90
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 007a094e-b8a5-491f-9f51-02111dd16da6
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 62c7b26a-8a93-4778-af81-7f910b78dc3c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 8dbb4973-cc00-423c-98c8-f23510c319a0
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b6e44f8e-acb3-425f-9eab-177b217cf3c6
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8611f8b9-b7d9-47ef-ae41-5ce6d1ea4258
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ff07342e-ddec-4b1a-a366-eab9e1313591
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 003ecfd5-1fd6-4fde-8d63-cf7cd72ae178
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 726db629-0ec3-43ef-85bb-f722bdd13e67

		level Year
			ordinal: 0
			column: Year
			lineageTag: 601d6a97-a1c4-436f-904a-c91a65e593df

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: dcc99fb9-a5a0-4914-8254-b5f685cdd1c4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9f19899d-c0fe-481f-b84b-64c72a822582

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3b3ecdba-3fa9-4313-88ca-1887b026873e


	partition 'Calendar-d530967b-1820-45b1-bdff-b4bc4d20d9e2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

