table Calendar
	lineageTag: 425483af-1119-4656-8bbd-8d40269e43c4

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 50a714e5-d859-4bdc-9633-17293b4138bf

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1d90f20c-1a30-4afb-8d81-641d9118915e

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 1db3cec4-6c43-4f0f-9147-4b978e8c0a78

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4479c20a-7cf3-46df-83a4-23f709b08f2c
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a3711b8e-bd64-4be4-805d-d0fd77c05919
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 302fc49c-b09a-4d9b-9563-acc6288da9c7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c18693ac-81ae-4160-88dc-59aaf8f5089f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 080de04c-eae2-48c9-a804-c2b505027eeb
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f1b918d0-6053-4ac4-9eac-3df23b344b1f
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 1121996a-75aa-419b-a74b-7153b1cd0295
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c6c4c63b-98dc-4cc5-9514-a5769663cd44
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 94ebb682-7a79-4f69-a45e-6a8d33765b79

		level Year
			ordinal: 0
			column: Year
			lineageTag: afb1148a-03cc-4125-b5db-98c6ee4a8857

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d5ea5222-b442-4c70-b257-2249e22fbe41

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8de5975e-88f5-47bc-b6ce-e4bcc0c7a67f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5a64115f-f3d8-47dd-9618-6720dbc7f69a


	partition 'Calendar-8f6c4ec9-1676-4096-a71a-40c6977d0c9e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

