table Returns
	lineageTag: d4325d65-4caa-4724-b58a-5021c6576103

	column Returned
		dataType: string
		lineageTag: c53b9972-ee35-4e28-988e-c551566bf5c7
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 8d8607a8-ddc8-4bc5-b676-1ffc4277e61a
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Returns-51bad865-9057-40a1-9f71-01072c70a872' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="Returns",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

