table Calendar
	lineageTag: f7cf077a-9ba7-4832-a46b-f4fefae291df

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d86b246c-3bee-4f1f-8714-c669e050ad75

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d6e273c0-397a-4e85-b623-f4e44e5050cd

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 55b779a1-6004-4704-9635-046e16b8cdd4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 16924d1f-2514-4a80-bad7-049b7a5a5bf5
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1bdd50cb-62dc-463b-816f-82971f5ba305
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 313efb23-edd9-4798-a652-a17eae55b033
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a78aafa3-24f9-4f41-ad97-4fe990946446
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 9e685576-7f76-4db6-8771-73bca3ef592c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b60ecdd7-2338-4aea-bf8d-027418470085
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 21bc323b-9274-48f8-ba2a-e954771d0a53
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 18a30617-7eb1-4caa-9a52-ed5a6322bee1
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e181f304-40e4-4648-926c-8c05f94aad3b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 2111c361-fbd4-40ae-83a7-11dbfe01713b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 57a52d42-d028-4595-a832-2e02b4337bc2

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: bee3d04e-7de8-4086-b183-5b67a4544e11

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3dd7d6ef-62d0-461b-bbaf-7f4c2cc409fb


	partition 'Calendar-eed3c8ca-84d2-471e-b107-694b46d1e6c0' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

