table Calendar
	lineageTag: 48ea422e-ea69-4012-ae9e-19015d7a5a46

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: abb292ff-7833-4d5f-af8b-825eeb10d59a

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6fe98b7c-8b93-4da5-8b10-d4b31bc04d38

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 235423a4-59f0-4ca9-9983-8a1b1fcc482e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fecf59c1-0a65-4178-a3ac-75e48a4fc3f7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 063ad38e-a493-4dc0-8203-f9a50f378e48
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: bc61217c-cc77-44ce-a5db-dd64586e08d1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b2da255c-a3ff-48f6-b344-3211358f9965
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8fc85f7a-5bb7-4f2d-a660-77dfc98e81b3
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 10fce748-2f02-45de-bf7d-d94ed07bfa47
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2e7d2c66-8774-4c93-b904-6d888942f017
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 871582e0-2888-47e7-b110-dd036355209d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 01234905-5451-49da-b075-cea0cb1d1612

		level Year
			ordinal: 0
			column: Year
			lineageTag: 105e9505-733c-4bef-81ea-e0e296c481cd

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 84c28f99-7bac-4f97-9d83-0f4d7fc56b23

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: de3adf45-3ee8-49ef-ac92-c752f9c57928

		level Day
			ordinal: 3
			column: Day
			lineageTag: 2415d0a9-67df-405c-9457-ff7f7ad78fcb


	partition 'Calendar-a08132de-bfad-486d-8607-274d45252cc5' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

