table Calendar
	lineageTag: 66585a15-2c4a-4e4e-a352-c94f8dc7577b

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 38778f9b-26ee-4145-8aa6-af5fe578eb51

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5181eb2b-5212-4c26-8f66-e3eeabd79053

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 66b36cd3-0f3d-41c5-b0d7-b619976c9f8a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a3eebf12-dbd0-406a-8590-8d3b9b5b7d46
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 733b57b3-c462-47d6-8910-0785af5c1385
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 645d964e-473a-4abe-9524-6f57549a942d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ea446d42-c914-4dd5-aed1-99d099564482
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c4ddbad3-21a1-4027-b92b-9c1b3bfbea22
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 856a3e98-ae76-4742-aa5b-4beea5abab56
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 5d317ba6-129f-4b25-a1e5-128f2d351e11
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 348afa58-bd7d-42f1-bb55-d86a9adb139b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: abd8cbb7-ed1c-4360-b2b0-f56ccb5aee1b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 20ef1f64-c48a-46af-8ec7-e61919b98ed3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d9be5ace-e461-44d9-906e-93555c83f7b9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e89a5610-e7de-4971-a43a-2f25167d5e3d

		level Day
			ordinal: 3
			column: Day
			lineageTag: fb64ecaf-0ce2-46cd-8148-acf2577a231f


	partition 'Calendar-262212e0-95d6-4de4-b077-1c44bbedbbbe' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

