table Calendar
	lineageTag: 8649f288-006d-403f-8fef-ca035ac8a741

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 82c5aa11-d0f7-4c11-a9d6-f404995f8cf5

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 97b9f01b-2d4f-45a3-9113-67218b633212

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 9c1e254e-42f0-4ac0-83f2-12b6371c199c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2a1a9236-854d-478b-a6b2-f846d5294682
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 81f219b8-39f0-4f1c-ae49-109a573568bb
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dfd1e3af-8a93-4c90-a599-47352663d860
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 57b527e7-2160-4f49-a36d-4a2ff7009b7e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 92dd160b-ceda-4820-a201-c67c2d1e5cdf
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e2a10a8b-a9ae-4e4e-974c-851a05801c92
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 268de06e-b5b0-4232-a9c7-fd943fb87ac8
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 49996e73-b0a9-4dba-8809-4ba4b380e5fb
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5cb36709-bcb8-4062-8dcd-d47b6e75e34f

		level Year
			ordinal: 0
			column: Year
			lineageTag: de721e5c-8044-40dd-9a09-0a7070f958d8

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f1c690a2-49d7-4ca3-a1ee-d7a04053a1e9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9735b0b8-c514-4123-a61a-472ba6239b15

		level Day
			ordinal: 3
			column: Day
			lineageTag: ed6ae30b-0955-4579-9fcc-ee027e9934a6


	partition 'Calendar-5eed9cdb-8889-482a-8eff-c1a8b29223fc' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

