table Calendar
	lineageTag: 75d7eb67-4d7b-4c4c-931e-d78ed37fcf7e

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 2c4c7eef-f46c-412b-a717-e8608bd86945

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 71c4ba52-0d34-49e3-99a0-db7e8d0b3e41

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: a3a3f922-f119-4a86-a472-6410e7b99ba3

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 083b0df7-404a-4179-9ce0-caabf2975c46
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ae68d2df-d9c5-4482-a493-57773bc0368f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ebd5fa4b-83c2-4e96-bffe-43e655a72442
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a086d28d-f7be-49d7-9137-86966a8f3043
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b88a7b16-b09c-49c1-a2a2-bf6f77444eb7
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 4e87d472-e431-4b21-8284-cef84275f4bc
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f844d7ce-bcb7-4145-933c-92d7cf15a819
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c4a5ff38-64cd-4556-b404-f63ae9d5b7e5
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 01eab8ea-f766-4478-9459-0e9be8f53170

		level Year
			ordinal: 0
			column: Year
			lineageTag: e0463f2d-b2d7-4ee1-b022-307c3e9b9c56

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c1d52932-1764-4dc6-b936-d0e13ef1a8a0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9a849353-4843-41d4-b8a6-3ab1e30a0e23

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7c542d6e-4896-47af-807d-6955a207a0b2


	partition 'Calendar-49a5cafd-d92c-457b-82f9-6b90991ff70c' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

