table Calendar
	lineageTag: bc307c03-5152-4d25-8e72-9eb724ca7093

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7a1a5554-3cbf-448e-bd53-13e526a67b69

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: fd8cf098-21db-4dfb-bcd6-88b106e936de

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 7df9de3f-073c-455e-8f79-253e4168738a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 56eab43f-e8a6-406c-a94c-014171556719
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a0f008c4-2b0d-4625-bcee-ec224bdff3ba
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 66d2668e-ab2d-4618-99ad-c3bc1905aeb9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7e305524-5695-4e6f-80d8-794dd3c3beb8
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0317830b-d596-4bda-8383-946b8d6c12d6
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 88c689f9-9c17-4bc3-9cdf-b519972c48e7
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2e3e94b5-46eb-4e84-a513-ca212b426f92
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 76c670e5-c4bd-4c55-94d3-5a3401621379
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7ea5b68a-c94e-4efb-a2d9-b7a9abf0c52d

		level Year
			ordinal: 0
			column: Year
			lineageTag: d574372c-087b-4e40-9973-5f9160a84a4f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: a0b392e4-ad79-4349-aefd-660da10f8329

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 363cf735-65d9-482b-a3bb-34a616a2baf2

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4fc66def-c0b8-4e39-9597-47ede8e66d20


	partition 'Calendar-6453f77c-5e58-4c7e-90a1-f08104e41dbb' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

