table Calendar
	lineageTag: a5a82571-6da5-44fd-8408-5d2e732a3917

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ddfed790-5787-4c42-8e4b-ad6a62ede76f

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 3b59785f-679f-4d74-96cc-8833cdef7324

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: d7213b16-84d2-475f-8821-ea7580d389c4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8a9cfe97-4170-404d-93ec-6bad23a900b1
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d3387738-b918-4357-9053-2a84b02fa54d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7574a861-561c-4e5d-a7ee-17988caba71d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 68c44d31-1ec8-49be-b04e-d573b2189264
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e4f9e9ed-e8ab-4852-a0a1-97052e0e5564
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e857c28c-493b-4a94-afc9-ea41d84be41a
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 706189c5-e36e-4964-858a-133b8bb4baec
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d4478d3c-104f-4dc6-9511-acd17ccccb6a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ef5fbae1-3bf1-4434-95c2-e50c13139cf2

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6942492a-8575-4cad-b70a-4ed49d4a770f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ffbc6b7e-74b2-4736-94d9-5829c8c0a620

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 71d9ab5e-681b-4179-a7c1-735251b76d9f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 18980e72-b585-4c8e-89de-560b225472a5


	partition 'Calendar-1352ec7f-75ea-4042-b0bf-0c7107cd9555' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

