table Calendar
	lineageTag: 9f9faaa1-5528-4b98-a665-178987122c37

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: abb0f99c-5d90-4079-8d1b-23f5ec5e38a0

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 50cf08cc-5f8e-434b-bbe1-ab8efc128513

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: be896fc8-8751-4e85-8534-04659177e0fe

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9513a250-d81b-4bfc-b857-b44649108549
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9ac1dc83-4e50-4dbb-ab62-5b4c510322d0
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 3e4f1798-b391-4e8a-bf04-44baa5f9b247
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 09fd2430-42ef-4465-bbf6-6b695624700b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 9c7d72cc-3780-4503-95ff-ca201e2a623d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 68e94b78-0d8b-496c-984c-5bc50ad9f3da
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ccbc25a0-68db-48b8-8728-7a79057267fa
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a4b6bf97-e5be-43ae-98c7-7bd1d0eb6b9c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ab78e0b9-a5ce-4075-bcb2-84ebea89df52

		level Year
			ordinal: 0
			column: Year
			lineageTag: b76d20e2-e857-407e-8784-5325f659d131

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 9d9d33cf-45e6-443c-942f-870742f92741

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 2a41ed44-f8b7-40ab-8895-e47bab77e313

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3a1dd9b4-4409-4f45-81fb-3fdaf0811339


	partition 'Calendar-069804da-6079-4b91-93c3-b2a809285f5a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

