table sessions
	lineageTag: 201d9cdb-9765-469b-b9f7-f32aad196058

	measure 'Total Sessions' = COUNT('sessions'[session_id])
		displayFolder: Measures
		lineageTag: 9c520d61-9360-46a6-8bef-f9687db7af83

	measure 'Unique Visitors' = DISTINCTCOUNT('sessions'[user_id])
		displayFolder: Measures
		lineageTag: ca41f718-150a-4316-91c8-4bf721576683

	measure 'Conversion Rate' = SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 4498eae6-6873-439f-8d6d-9f234a22506c

	measure 'Avg Session Duration' = AVERAGE('sessions'[session_duration])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e20fa073-7eba-424a-9b02-d40ff14f491f

	measure 'Total Revenue' = SUM('sessions'[revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: eb61555b-1de0-4b93-b4ab-c8e33a6f24d4

	measure 'Revenue per Session' = SUM('sessions'[revenue]) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d915d135-8ee7-455e-ae1e-027e145af3d9

	measure 'Revenue by Channel' = CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ebac7f5f-e79d-416e-a805-c54296c235f4

	column session_id
		dataType: string
		lineageTag: 287af403-d842-4ca2-9c02-d92519248904
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column session_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c757971-ee2e-4668-b0d8-71dc10dd1cd2
		summarizeBy: none
		sourceColumn: session_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: c26d5fac-a870-4819-a267-2247c157b832
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 8be5210e-f8de-433f-9012-fde1561dd699
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: e5a828dd-71ce-4215-8452-e4d4bfe9c5de
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 82e54404-42ca-4542-830c-0e65287a31bd
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column page_views
		dataType: int64
		lineageTag: 0282b0a4-4ba4-4771-adf1-061e6a06f83b
		summarizeBy: sum
		sourceColumn: page_views

		annotation SummarizationSetBy = Automatic

	column session_duration
		dataType: double
		formatString: #,0.00
		lineageTag: 53f0e3f2-755f-497b-a7ef-d147e08b89c6
		summarizeBy: sum
		sourceColumn: session_duration

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: boolean
		lineageTag: 7225b260-c1b6-4afb-bcbd-b44fee49416e
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: 41c1a190-c428-41be-945e-4c87b8eff925
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column 'Channel Category' = IF('sessions'[channel] = "Organic Search" || 'sessions'[channel] = "Paid Search", "Search", IF('sessions'[channel] = "Social" || 'sessions'[channel] = "Referral", "Social/Referral", IF('sessions'[channel] = "Direct", "Direct", "Other")))
		dataType: string
		lineageTag: 3af952dd-9ea7-4550-bbe4-0be2d26b4d3e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Engagement Level' = IF('sessions'[page_views] >= 10, "High", IF('sessions'[page_views] >= 5, "Medium", "Low"))
		dataType: string
		lineageTag: a956b113-8ed4-4086-99a4-759ac18d6703
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Days Since Signup' = DATEDIFF(RELATED('users'[signup_date]), TODAY(), DAY)
		dataType: int64
		lineageTag: 65f328cc-2ca6-4843-a9dc-ebb4ee668f0a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'sessions-e70dc560-1db7-43d9-af80-f6c8aef6a061' = m
		mode: import
		source =
				let
				    // Source Google BigQuery: my-analytics-project.web_data
				    Source = GoogleBigQuery.Database([BillingProject="my-analytics-project"]),
				    #"web_data" = Source{[Name="web_data"]}[Data],
				    #"sessions Table" = #"web_data"{[Name="sessions"]}[Data],
				    Result = #"sessions Table"
				in
				    Result

	annotation PBI_ResultType = Table

