table Calendar
	lineageTag: 329f10b0-aba9-4735-987d-4071cfca8b8a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: df101de3-716b-4b0b-858e-9555aed8a6ec
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 6f60ea90-da34-4d15-8917-f0cedc4c5b91
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: bed8b5aa-018d-4dd9-ae0d-f81c94c979f5
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 1eee211b-36fa-4d4b-8d7e-b1c1e355135d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: fa425c05-ad56-4a3d-8e73-a970dd3d1c94
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d53ae97f-0ec9-42a2-9e4e-2c24a1967007
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2e45950b-030d-4678-a863-197b96dc195a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f96dc288-1d22-4ef4-bd8c-02048bf4079c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8e79a453-e647-4916-916e-ed131b3b1e59

		level Year
			ordinal: 0
			column: Year
			lineageTag: 781140e8-45ac-4005-9447-402dc0de04a6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c787623c-06c3-4e07-93e6-c1f193e56eb8

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a8e28642-da30-443a-b905-aba69afb5b06

		level Day
			ordinal: 3
			column: Day
			lineageTag: d0ad2aae-0f66-4c69-8c98-9a9cdeec5f20


	partition 'Calendar-b4717d91-8816-486f-973a-51b1be0869f7' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

