table Calendar
	lineageTag: 2c317267-3df2-4a5a-830d-8527cb903391

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 69133985-5634-4816-acba-a9287e6eb0dd
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e33039f9-a152-4310-b09d-41bb1821e3fd
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 82fa868a-1a9a-44e1-a7ff-b46440cdf1ad
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: afdc53d6-f2fc-4643-876a-fea165381360
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 43b5b275-50b0-4bfb-8064-fdf78c625762
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8aef5ef6-5032-450c-90f8-8e2d76b07138
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d4e83611-82f8-4eeb-a872-46733a586c30
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2003d824-99e5-49e4-91e6-d9f759268778
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9e2898eb-2af3-4371-8d12-ae363eefa0cb

		level Year
			ordinal: 0
			column: Year
			lineageTag: f7c48ad5-2aea-4dc6-b501-04edb47ae9b9

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: eb472fcb-5bb9-4c7f-9613-3b6b68513f94

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7b1bc001-9427-4a0a-a3c0-83e3c708f003

		level Day
			ordinal: 3
			column: Day
			lineageTag: eec5ae62-3ec7-4381-bc89-1f3b3552e7b7


	partition 'Calendar-eb264865-1d64-41eb-b292-dab86650d9e1' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

