table 'Target Margin'
	lineageTag: 6a74ecd6-7547-4710-b6ec-1e5985aa0271

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: ce65278a-3801-4cac-afdb-a195ef8d9693

	column Value
		dataType: double
		lineageTag: a933a06f-8ae7-4e6d-8e25-cd2d2554e835
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-74e2f3e8-d1e3-4e0d-b232-a17451a3bdb7' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

