table 'Target Margin'
	lineageTag: 5392e5ac-c1b5-48af-a1f8-beccde21a84b

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: f85e416e-0c55-43f0-b728-68dcd40255ef

	column Value
		dataType: double
		lineageTag: 70e8fe60-683d-4cf8-9737-e73d6fc26027
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-193eba7e-2795-4b72-91d3-91560f6f9592' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

