table 'Top N'
	lineageTag: 7ff676f6-9760-4311-ad53-97a4afab1522

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: f67582c9-3282-42d4-bab2-8bef0a62bb07

	column Value
		dataType: int64
		lineageTag: 9c849b9b-7a5f-42fb-bf6f-92eb53662ab9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-25a71efc-008d-40a7-a126-362b6a421c72' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

