table Orders_Clean
	lineageTag: 1cdc54fa-9537-4377-adb6-d008a9ba9f37

	column Order_ID
		dataType: string
		lineageTag: f31f47bd-619e-45bd-a127-9606bbfba0d1
		summarizeBy: none
		sourceColumn: Order_ID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Order_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: d780f931-6770-4535-91da-0faa7d45853f
		summarizeBy: none
		sourceColumn: Order_Date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Customer_ID
		dataType: string
		lineageTag: c8da62f8-e377-4611-a2f5-9ecd1d72c916
		summarizeBy: none
		sourceColumn: Customer_ID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: string
		lineageTag: 48a81d74-74f2-4c75-a6d8-497e2cf2a77d
		summarizeBy: none
		sourceColumn: Product_ID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: fbcad21d-e062-4381-8eab-77044973e875
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: afeab4dd-f481-4ee9-b6e1-7450d3de18cd
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 6a187e1c-ea27-4a0d-9e9b-d0d5ccd29d1a
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: dc6a1c6a-0d35-4c62-a959-54a0f6133b76
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 1ad862db-a882-4d9b-a0cf-8bd3eb356cf1
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column Ship_Mode
		dataType: string
		lineageTag: 7050111a-157a-4bee-9245-1e027c2c6cd5
		summarizeBy: none
		sourceColumn: Ship_Mode

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 4f875886-e42a-4dbd-9fc9-9ff8e4dc36b8
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column _temp_col
		dataType: string
		lineageTag: 0465d114-2b32-4ec4-8309-5e3b3c59fc5f
		summarizeBy: none
		sourceColumn: _temp_col

		annotation SummarizationSetBy = Automatic

	partition 'Orders_Clean-35de9121-fb9b-4db3-8db4-f81c995eb13f' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: textscan
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Order_ID", "Order_Date", "Customer_ID", "Product_ID", "Region", "Sales", "Quantity", "Discount", "Profit", "Ship_Mode", "Status", "_temp_col"},
				            {
				                {"Sample 1", 2, "Sample 3", "Sample 4", "Sample 5", 6, 7, 8, 9, "Sample 10", "Sample 11", "Sample 12"},
				                {"Sample 2", 3, "Sample 4", "Sample 5", "Sample 6", 7, 8, 9, 10, "Sample 11", "Sample 12", "Sample 13"}
				            }
				        )
				    otherwise
				        #table({"Order_ID", "Order_Date", "Customer_ID", "Product_ID", "Region", "Sales", "Quantity", "Discount", "Profit", "Ship_Mode", "Status", "_temp_col"}, {}),
				    #"Removed Columns" = Table.RemoveColumns(Source, {"_temp_col"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns", {{"Order_ID", "OrderID"}, {"Order_Date", "OrderDate"}, {"Customer_ID", "CustomerID"}, {"Product_ID", "ProductID"}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Renamed Columns", {{"Region", Text.Trim}}),
				    #"Filtered Rows" = Table.SelectRows(#"Trimmed Text", each [Status] <> "Cancelled"),
				    #"Removed Columns 2" = Table.RemoveColumns(#"Filtered Rows", {"Status"}),
				    #"Replaced Nulls in Discount" = Table.ReplaceValue(#"Removed Columns 2", null, "0", Replacer.ReplaceValue, {"Discount"}),
				    #"Added Revenue" = Table.AddColumn(#"Replaced Nulls in Discount", "Revenue", each [Sales] * (1 - [Discount])),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Revenue", {{"OrderDate", type date}}),
				    Result = #"Changed Type"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: Order_ID, Order_Date, Customer_ID, Product_ID, Region, Sales, Quantity, Discount, ... (12 columns total).

