table Calendar
	lineageTag: 71611f51-26d0-43b0-ba9c-1104a25dda42

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 10295ab9-e93d-4237-8c4c-47e1fe58eeda

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1898d6b7-6bce-4349-8611-decf668ad654

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 6944190d-35fc-4465-ac5b-e3acc6d0ca2d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: cef94557-ad34-419d-bbb3-1e8aa907c6e9
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b8222b53-428c-4484-af04-bd54a350007d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: acdaa0c4-d528-4d0c-9caf-91347aa1f5f4
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f2df6b43-4694-4614-bae9-b8bf074dd77a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 77daf337-931e-41e7-872f-ec32592c0da3
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0285be32-edf9-4365-bad6-29e14c8f470e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7ece858b-51f0-4073-92f1-51cc3f987102
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b2ba802f-48f8-48eb-a145-5ec7ca7ab658
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e4f9a342-ffd6-4a29-bb3a-2016b73b7289

		level Year
			ordinal: 0
			column: Year
			lineageTag: 25959623-0c07-436f-9bac-65a247dcdc57

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: db952d02-c530-4c0e-a924-7f4e5a2ac4f0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: d677d73b-e7d5-4132-a572-ea94c0be6f98

		level Day
			ordinal: 3
			column: Day
			lineageTag: 57f09909-528b-4f6f-9354-0aba52f37021


	partition 'Calendar-97fc6e37-daa8-4fad-ba67-998165a4b91f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

