table Calendar
	lineageTag: ebd9047b-f948-40e9-9260-1240f54d30e2

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ba3d8c55-997e-4ca1-a4f4-199e627d10be

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 43869031-2393-426d-a0d2-08405e50af26

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 6fce40c1-2167-4f85-8d78-34992cea745f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 67de71a1-f22e-4f28-972e-dc08d9d62545
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9f86ef80-42c6-4f8d-bab3-5c68416acd91
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: de0654ed-2687-46d2-9f0c-8ee4f09ff1d5
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 1dd515fb-ad91-4230-af3d-e6f7f5a4158d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d9a79bb8-7cd1-4b72-8366-b2aa89883308
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 22d02374-6da6-4855-9dec-e3a7905e17ab
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: dbe4dd21-46ad-47e7-a2df-ffe841b83107
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f0a4f5fb-ff3d-4f40-81c7-6e43fb722832
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: d0fe607b-8488-4f5b-9c0a-3f56fbc79db9

		level Year
			ordinal: 0
			column: Year
			lineageTag: 82aad43d-dc15-4e44-9624-671597d972cb

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 6fa48557-ad6d-4833-8497-8e491083b7ce

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 595f3712-c819-45d3-a7ea-0ad1c9aa29da

		level Day
			ordinal: 3
			column: Day
			lineageTag: ec7111fb-c51e-4a34-b542-7ab3868a2a28


	partition 'Calendar-4cd17bf8-8c87-4385-8d55-4bf3758566c8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

