table Calendar
	lineageTag: 3d5777da-fa6d-4965-9997-53a3b51a8b67

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1cbfd643-bf0e-44f7-b6a0-20d105ffe553

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6c7919e5-5640-4874-a935-78258767eec9

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ea16fecb-8c14-46fc-9d94-e8ab573b6bc6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3976eaaa-2502-4d9e-8695-817a9720e5b2
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f6f80112-cfe4-421b-b701-c6e2b941bfdf
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: a96534c8-422e-4370-8053-7810cb7b4f5c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 90d7c1e2-53d9-4cee-a1ae-f0ca87c90161
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 71367824-8739-4758-a6a6-40f01ee0cc25
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 14b30a11-5884-45e6-abfe-8ed17940ec5e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e4eb16d6-f34e-41f8-87c3-aabaa1cf6e9f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7040c205-637a-49f4-9c63-ff5e9095757c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 048f1c56-d1a3-4ad5-bbb4-5881880d2e2b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1048d170-6333-4a19-bba6-67f58fa3b126

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 79995772-8584-4d7b-8c38-27088a49488d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 665f2ce5-90a9-4f85-9ca2-f26ce073f588

		level Day
			ordinal: 3
			column: Day
			lineageTag: ed280ce1-2275-486e-89af-2acf88e7ddda


	partition 'Calendar-6489b24d-fa3b-4693-9eec-4e7dede068e5' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

