table Orders
	lineageTag: 106068f7-67c2-4c78-9bd5-5d7b5026f437

	measure 'Profit Ratio' = SUM('Orders'[Profit])/SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 555007b6-d98b-45a1-b061-3f82b57bcf7f

	column 'Row ID'
		dataType: int64
		lineageTag: f2f7fe8e-62a1-4758-8fb1-26b398d4032e
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 0f4e5be8-a035-4176-b398-bbac4a7f3f70
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: e75cbde7-4237-4ee8-91c1-7cfae03ef8dd
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: f0714fc7-1da4-488f-9f9d-76d900de6fa2
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: ba4e06c2-4318-459c-b79f-cdb9a5a6b140
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 1b58345d-f940-4d2c-82b9-4f872c20e92d
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 258751f3-dfdf-4ae2-901a-433f7922dc03
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 46210d4b-ea9d-4abe-a9a2-ba1a5f99773c
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 33143591-af51-4b29-829b-09ba8c9899b7
		summarizeBy: none
		sourceColumn: 'Country/Region'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 8b799ec1-4e9c-44ea-a46f-b87cda6fe530
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: e26bb301-c1ac-4f45-a8de-aa92e00abd86
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: bda9c751-58b3-4883-aded-c00579fcc6bf
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 74a39042-789e-413c-8b08-831ce3e8aec9
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: bacb8ee2-6145-4836-889a-710dd9a142c8
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 6db6ea9b-c4d8-4842-8372-00d1fe320618
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 105f95e5-8558-4db3-897f-c18f0c596926
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 4b936f32-70f8-4b99-bab2-1a0f45cfb37b
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 686e245e-c2e2-4378-a205-279200a42b5b
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 423f1d6d-2124-4fd7-918e-0f775c141952
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 35e83cba-a907-422c-8d17-531181a37a84
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 53843903-9c41-41e4-90a5-4a8d83d5a3ca
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Profit (bin)'
		dataType: int64
		lineageTag: c63ba08f-141f-4d00-9b1d-ec64337968f0
		summarizeBy: none
		sourceColumn: 'Profit (bin)'

		annotation SummarizationSetBy = Automatic

	column 'Top Customers by Profit'
		dataType: string
		lineageTag: 434bd5c8-d30e-47b4-b4e0-a9c40a614cd4
		summarizeBy: none
		sourceColumn: 'Top Customers by Profit'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: double
		lineageTag: a5dc5dee-5d15-4f2e-9765-8e07c4a5ba46
		summarizeBy: none
		sourceColumn: Manufacturer
		displayFolder: Bins

		annotation SummarizationSetBy = Automatic

	partition 'Orders-24845b6d-db26-4724-bd52-8ea5cf5e234a' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country/Region", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    #"Added Profit (bin)" = Table.AddColumn(#"Changed Types", "Profit (bin)", each [Profit], Int64.Type),
				    #"Added Top Customers by Profit" = Table.AddColumn(#"Added Profit (bin)", "Top Customers by Profit", each "", type text),
				    #"Added Manufacturer" = Table.AddColumn(#"Added Top Customers by Profit", "Manufacturer", each 0, type number),
				    Result = #"Added Manufacturer"
				in
				    Result

	annotation PBI_ResultType = Table

