table People
	lineageTag: e901ffa1-828d-4e48-a959-b20046410a69

	column 'Regional Manager'
		dataType: string
		lineageTag: c0f715db-3f65-4260-b5ca-9ee1874730ab
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: e1a8db14-1498-4f25-9571-5193fd7c83ee
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-92059ce8-cead-4bb9-8b45-841a5e773d3d' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true),
				    #"People Sheet" = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"People Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

