table People
	lineageTag: 987eb386-a46c-4de7-8685-04a83e9e6a6a

	column 'Regional Manager'
		dataType: string
		lineageTag: 25ef28f5-374b-4391-86b3-6de6f0acaa56
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 167f2f52-970b-4236-92aa-c2aab5e15b6a
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-b1346f43-71ae-498e-894d-cba58dd53806' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true),
				    #"People Sheet" = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"People Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

