table People
	lineageTag: f858dac9-4b32-4171-a6dd-ade3edfe1d4f

	column 'Regional Manager'
		dataType: string
		lineageTag: 59888813-c952-40b6-9d36-10e8e29f8599
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a159aa16-8600-4df7-8c29-134a15daf894
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-c2bccbba-14bd-45fa-92f8-bd56c92e514f' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true)
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"People Sheet" = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"People Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

