table 'Profit Bin Size'
	lineageTag: 8520478e-c9b4-4411-8793-7a457b5c6a87

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 4959c0d5-3f1e-4586-9490-14eb5d3bb926

	column Value
		dataType: int64
		lineageTag: 0cd6d6a7-d07f-47e5-aea1-7e44dfcb203d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-400489cc-c9c6-4b0b-a8ff-67a1d0b5accd' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

