table 'Profit Bin Size'
	lineageTag: b08886c7-6fc1-4a56-afb5-85a6afaa2236

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: dd41ea9a-18e0-48cd-8535-4a644d045435

	column Value
		dataType: int64
		lineageTag: ddeca6ab-bb55-44ee-bfe9-f8240167ac2b
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-ccebc822-0f34-4911-9815-0cb81cb0cebc' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

