table 'Profit Bin Size'
	lineageTag: 597b814b-7ee7-496b-8f55-90caed494970

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 74fd0669-447c-46d9-a00a-6dd264779fb9

	column Value
		dataType: int64
		lineageTag: e92eab44-97ba-45d5-932e-70b1047433fa
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-cbfd3e0f-2a48-4769-a562-73b5cf4c684d' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

