table 'Top Customers'
	lineageTag: 2ad1367e-be34-4503-9814-7439f4a002be

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 61088fe5-366f-44cf-b0f6-b0e128404683

	column Value
		dataType: int64
		lineageTag: 827257f6-7910-4a6e-815b-ab0b9d2e213c
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-ee1c779a-6164-4927-9d3a-323bb60f2570' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

