table 'Top Customers'
	lineageTag: 6195e9b9-303b-49ff-9b4c-678efcb70e1b

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 43a2d075-8175-4095-bdf1-cad4117b4695

	column Value
		dataType: int64
		lineageTag: 02466d78-9e34-4586-9819-457890f5e532
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-d017f147-1a0c-4500-b2fb-998625fb5740' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

