table 'Top Customers'
	lineageTag: 8465df6b-aa8b-43b4-a2c4-d9b908fb1795

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 94b149ef-5c02-4b98-9e17-971bc8d668e0

	column Value
		dataType: int64
		lineageTag: d2512255-f79b-4edf-b67f-71083ca245d8
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-d1a0cda1-067f-44d7-b2f2-9bd7ace0a3d0' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

