table Calendar
	lineageTag: da272494-5505-4acd-b2d0-4b91fec7900f

	measure 'Year To Date' = TOTALYTD([Total Revenue], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 878312ae-cb15-4d43-932b-7a660d8d0b1f

	measure 'Previous Year' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 58688329-fa5d-45c7-aee5-f26d923fb61f

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 43efe62b-05ca-4a52-908c-ede7e0cc6cc4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8aa49d28-9cd3-482c-ab38-091ef6015065
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f5243b7a-d106-4a48-ba01-9bc03f4be163
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c10fab2c-ee68-4520-949b-96478f500d88
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 59af8acc-7d86-400c-a9ae-74e043857457
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a12f7840-e7c0-4211-9f2a-20f8b7eff241
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e3ed8a68-6a8a-47c0-9c61-7494b72c4ddc
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: db2a220e-7692-4714-85be-65ec6d8c1da0
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 727ee8d1-f4ee-4edb-92fe-3ced8e71fbd8
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 13499cf0-0bbb-47a7-812e-9184eb6c985d

		level Year
			ordinal: 0
			column: Year
			lineageTag: f73398e0-f450-45ab-8eb9-af73f72ec9e9

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 81f02330-2427-4852-924d-0840d1212109

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c9b2b306-e6e8-4caf-9953-acee957ea50f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 36da96df-3be9-40c5-9631-2c428dc3b751


	partition 'Calendar-124f7309-4710-44e3-a2ac-c947eab037ce' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

