table Calendar
	lineageTag: ee434885-6d00-431e-8451-68861632a44a

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 601480c0-82fd-4829-8b85-323eba4d631e

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6b4d1206-2301-4cb5-99d1-ff519aa63639

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: f17c89ba-4d02-4933-9fc4-695591567618

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 079b5e05-0d9c-4148-8e65-7237f94c8e10
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 036de541-29b1-4ae7-a67b-6f47bee6b0c1
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4817e1b6-7b49-424d-bd20-76db117b82a6
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 6248ee69-21da-44f9-8e49-593afcb2603d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 168c0148-9931-4dde-af55-ff6a183aaca0
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3943f3f9-4a48-43ea-92ac-97e8577699fb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 0bf84384-d571-427c-a253-84d52dc5b52e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 261df35c-c88a-4b10-9012-e1f4a1cb4c3d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 57082bbb-7ab3-4bef-919f-112331acdf0a

		level Year
			ordinal: 0
			column: Year
			lineageTag: fffa74fd-03c8-472b-9bc0-e845696f7cdb

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 42e6ca66-1dfa-4a3f-af2d-97945c5285fb

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 43d584c6-fbf4-453d-8fbf-860b6cab19af

		level Day
			ordinal: 3
			column: Day
			lineageTag: cf2ae222-b505-431a-afcd-9ff8849475e2


	partition 'Calendar-469c7b40-a925-45e4-947b-2af8092fe02a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

