table 'Alert Threshold'
	lineageTag: 43dd604d-3549-42ce-9d1c-3eab21fcb8da

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 974e34b7-0e17-41e1-b3fc-e640fa02dc10

	column Value
		dataType: double
		lineageTag: e94b1973-2ccb-418f-80c0-49db15ebfb1c
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-6ac49017-abc1-4d1e-86c0-3ee0ed4c330f' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

