table Calendar
	lineageTag: c3fd205a-6753-4ccd-b52d-f9ccf93a07cd

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ca464a67-a63f-484b-a1a8-42fa31e2c877
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 17d932cb-8d64-469a-ae63-b838cdf7f9a4
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 686939c9-6ce5-4d5f-bd18-1bed4a3cd238
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 840a3bc2-6524-4bb5-860e-dd1226fc5ed3
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: cca1f72c-1289-4723-b634-fcbe6987538f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7c88f506-d39a-4f75-bb03-5ce128d7a2ba
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 98581cc0-ecbb-4bbe-a967-74560b329542
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 33fed6f6-dc60-4a0d-9e31-ba3ad5d1afdc
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 235ec512-8acc-4f7a-bd0c-4f7a36396926

		level Year
			ordinal: 0
			column: Year
			lineageTag: 326d26be-61dc-43eb-9c2e-c855845464fa

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 396ac5a3-c8f0-4b77-aeac-b96922fedb90

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f4752643-4646-4d6f-b816-e6d10a674898

		level Day
			ordinal: 3
			column: Day
			lineageTag: 7150f561-8bd2-4a2f-8ab4-edd1b6057b38


	partition 'Calendar-8d13b04c-5e9b-4f5a-bf5d-2b5f2b4157ef' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

