table Calendar
	lineageTag: 83399463-c64f-4c8d-a68c-e44e10a0f35b

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 72de18c6-8a7d-4df9-8491-f840a4f40823
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5f1952a3-3204-442b-956a-f2f463871c8f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 77c00b04-6f18-4b82-9773-484935411039
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 74fbf00c-d0fb-4823-abd6-308579c32580
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 277e7de5-cd22-4306-971e-e0930e4da4a5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 797bc9f0-f6d9-42e2-86e6-71dbe9210023
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 04238594-3247-4448-9e4a-efc27dbeff88
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: bc2c6fe2-df62-48fc-95f8-70209ec9e47e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1af3b7e4-e549-492a-aab1-84f670bbc651

		level Year
			ordinal: 0
			column: Year
			lineageTag: 47459fc0-7e72-4d44-85c8-b177dd324a78

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c0fb0ce9-0db2-463d-9ceb-08f11fe60b0a

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8f3ec927-a85a-42c1-83a6-ae5c9513a95d

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9e15b6d0-5ea8-45c0-bff3-bd90a709ea1f


	partition 'Calendar-b6051747-b122-482f-a0f9-144a5e1a9863' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

