table Machines
	lineageTag: 99f4c88a-47c8-40bc-b056-6955ea9702eb

	column machine_id
		dataType: int64
		lineageTag: b08494ca-b62f-428f-be50-debf41bd7d96
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column machine_name
		dataType: string
		lineageTag: bff2c7cf-3b4b-4791-8866-99c30e93b630
		summarizeBy: none
		sourceColumn: machine_name

		annotation SummarizationSetBy = Automatic

	column machine_type
		dataType: string
		lineageTag: c8fccd6f-f1c0-4345-a7cd-092d2781bf4e
		summarizeBy: none
		sourceColumn: machine_type

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d1fff252-f4f7-422d-a91d-1c5ea586bd7a
		summarizeBy: none
		sourceColumn: install_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 4335df21-e659-4a47-8d56-d9698a2598d8
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: string
		lineageTag: 0e7f9f1f-84db-41a4-91b4-21a64c7bff95
		summarizeBy: none
		sourceColumn: line_id

		annotation SummarizationSetBy = Automatic

	column rated_capacity
		dataType: double
		formatString: #,0.00
		lineageTag: 18bafab4-d55a-447e-949d-acf32244492e
		summarizeBy: sum
		sourceColumn: rated_capacity

		annotation SummarizationSetBy = Automatic

	partition 'Machines-5f8879c4-d1db-475d-91d9-d6cc4dd32450' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Machines Table" = Source{[Schema="DBO", Item="Machines"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Machines Table", {{"machine_id", "Machine ID"}, {"machine_name", "Machine Name"}, {"machine_type", "Machine Type"}, {"install_date", "Install Date"}, {"location", "Location"}, {"line_id", "Line ID"}, {"rated_capacity", "Rated Capacity"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

