table Sensors
	lineageTag: 963f73c0-83f3-46f3-b66b-adc3d4d57bfb

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 4b9d0481-b13d-417e-a7e0-1ac26ae72c04

	measure 'P95 Value' = PERCENTILE.INC('Sensors'[value], 0.95)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0e0651b3-5aac-4c76-ab97-dff6419b3e3c

	measure 'Value Variance' = VAR.S('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e3e8d653-6de0-41fc-839b-9b22768f62b7

	measure 'Value Variance Pop' = VAR.P('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a56dc2b1-0d17-4a38-89d2-dde8bfaff9f6

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 252dca44-adab-4025-b5fe-7e5b6b7d8420

	measure 'Running Avg Value' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 67b4b9d7-ec2c-4101-b06f-ba66d31f1116

	measure 'Running Count' = CALCULATE(COUNT('Sensors'[reading_id]))
		displayFolder: Measures
		lineageTag: 4e82c8f1-485d-4ff8-8ece-87af0d090b0d

	measure 'Running Max Value' = CALCULATE(MAX('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2700cbf4-5447-4367-8cb2-7f22da363ee2

	measure 'Running Min Value' = CALCULATE(MIN('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9c01d72b-fc43-486d-a26c-7a8a8c22110f

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: e7495dea-aa99-4733-bdab-1667fcce067e

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		lineageTag: 2211e9b1-0905-4213-aa9e-c746f9d9f19f

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 39b1e6d9-29a9-4ef8-bdc0-571f99bae64d

	measure 'Time Granularity' = "Hour"
		lineageTag: 507409f4-a66a-471e-b5f2-382783a5eb6c

	column reading_id
		dataType: int64
		lineageTag: d57946a6-5d13-40ac-bf5a-9679efb38421
		summarizeBy: sum
		sourceColumn: reading_id

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 897115d5-9e9b-41d8-bc81-c5533f993351
		summarizeBy: none
		sourceColumn: reading_time
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 68bebb5e-b13d-4d49-b5cb-35c4850727cb
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: fed3be0c-9d97-4031-91bc-fe411bb99c7c
		summarizeBy: none
		sourceColumn: sensor_type

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: aca86704-3fbe-4e13-8eca-44259ea1e6cd
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: b6645b62-a1df-47b6-8e0e-446e736bbf26
		summarizeBy: sum
		sourceColumn: threshold_min

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: ef8a82b6-7ac1-4f20-87ff-14941cc14aaf
		summarizeBy: sum
		sourceColumn: threshold_max

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: bcafb5ee-2c11-4761-840f-933ec6b2bb12
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: 447af408-da66-4567-ad40-948e8ee851e4
		summarizeBy: sum
		sourceColumn: quality_score

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: e8d97ce7-98a5-4e2d-a406-77eef989d669
		summarizeBy: none
		sourceColumn: plant_id

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: f6a6604b-bc32-4ee9-a7bd-77078e5b281d
		summarizeBy: sum
		sourceColumn: delta_value

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: 3d8b7623-0cbc-4d7a-9739-9b125f61b255
		summarizeBy: sum
		sourceColumn: angle_degrees

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: 209482c1-36a2-4041-a69e-cbb3451cf9db
		summarizeBy: sum
		sourceColumn: power_watts

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation' = ABS('Sensors'[value] - ('Sensors'[threshold_min] + 'Sensors'[threshold_max]) / 2)
		dataType: double
		formatString: #,0.00
		lineageTag: 302b9283-5446-4c85-93c4-f24473bbefaf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: c07f65fa-6c87-4e32-8fd2-310143900890
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Floor Value' = FLOOR('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: 23b7de6d-8ff1-428e-9312-17227d4f084d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value' = ROUND('Sensors'[value], 2)
		dataType: double
		formatString: #,0.00
		lineageTag: 4a5210d1-70d0-4a92-b499-b5120b1743d8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: 0a90a0dc-fc3b-40db-b6f4-a88efa58a5d1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: 857922b9-71a7-4147-8bf8-90a8c3db1e09
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 49ef6622-c2ee-4574-b07e-0c9b146bd3be
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: d6f1a38d-034a-46d4-b14a-78d0ac78a8a4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: adea237e-6cb3-4512-b45d-39a1a43db77d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Month' = DATE(YEAR('Sensors'[reading_time]), MONTH('Sensors'[reading_time]), 1)
		dataType: dateTime
		lineageTag: a7b2933d-aa77-4309-93cf-f4214e912d63
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		lineageTag: abb8055c-bda3-4c42-bfcb-b774ba028a98
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: a7ba2545-e80d-4661-81f2-ca5736c0be0d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: f88ac51c-9c51-43ec-889b-0c4db00376df
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-eb093be1-72ce-469d-87ba-28793130aeed' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Sensors Table" = Source{[Schema="DBO", Item="Sensors"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Sensors Table", {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

