table Sensors
	lineageTag: 68fa7e18-3c9a-424e-abc8-6548efc14969

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 85bca3a6-f3cf-4c02-8b8b-401f209b900e

	measure 'P95 Value' = PERCENTILE.INC('Sensors'[value], 0.95)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 067a49b3-151d-49fc-9e2a-ff3df7298d32

	measure 'Value Variance' = VAR.S('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 38d57627-5058-406b-911f-3bba89523fa3

	measure 'Value Variance Pop' = VAR.P('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8439edcb-9c68-429b-acad-073791a144b4

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 61e7055f-ec83-424a-a536-af17aed3aec9

	measure 'Running Avg Value' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b5887399-e9cb-4793-b6aa-b45b529f005e

	measure 'Running Count' = CALCULATE(COUNT('Sensors'[reading_id]))
		displayFolder: Measures
		lineageTag: 51704b67-a579-42f7-9f10-7371300ba987

	measure 'Running Max Value' = CALCULATE(MAX('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 56e5e76b-321e-47d9-8a3c-cabbb12c666c

	measure 'Running Min Value' = CALCULATE(MIN('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3aec689e-f1ed-4b5b-8cc3-6ff8ce448302

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: 7a10b4cf-3bf3-444f-be90-4488848c22e8

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		lineageTag: e452d757-4328-48ce-8394-086ea48b31e7

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: bafe6a88-fb17-488b-b07c-381a59791166

	measure 'Time Granularity' = "Hour"
		lineageTag: 463febbe-d3fa-4e1c-b86d-3935d3c515a5

	column reading_id
		dataType: int64
		lineageTag: c79406c3-85e2-452f-ba13-b0cedb23d81b
		summarizeBy: sum
		sourceColumn: reading_id

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: a75a2088-ebf6-4f3f-9b2a-1df9203a83c6
		summarizeBy: none
		sourceColumn: reading_time
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 016f1dc9-1a1f-4d10-ab28-cf3ee7350a53
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: 6756e7a4-209e-4c6e-9bd0-c701246d6a26
		summarizeBy: none
		sourceColumn: sensor_type

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 3f7ccc21-bb93-4a8c-ad00-a3222a2d4a37
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: 07ede5fc-a3e2-4edc-a465-f834ac88c370
		summarizeBy: sum
		sourceColumn: threshold_min

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: 9d072748-dc8f-4496-862e-8c438aa2f369
		summarizeBy: sum
		sourceColumn: threshold_max

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 2a88ee35-9602-46d9-abaa-aaf57b4a5ee4
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: d06bfccb-2dae-429f-bf51-5daa61cd362e
		summarizeBy: sum
		sourceColumn: quality_score

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: 798078bb-36f2-4431-9698-671ad35e7da6
		summarizeBy: none
		sourceColumn: plant_id

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: 35634c70-94de-4216-b777-e86f75d6f450
		summarizeBy: sum
		sourceColumn: delta_value

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: fce597e8-f457-4f68-96a1-34d1c645496a
		summarizeBy: sum
		sourceColumn: angle_degrees

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: ca059691-ba64-4d1e-8be6-1cc7ff69f512
		summarizeBy: sum
		sourceColumn: power_watts

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation' = ABS('Sensors'[value] - ('Sensors'[threshold_min] + 'Sensors'[threshold_max]) / 2)
		dataType: double
		formatString: #,0.00
		lineageTag: 48988f67-b7f9-4344-b804-1f34d65767eb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: d6243a99-3792-45d5-967e-3012ecce9195
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Floor Value' = FLOOR('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: 46ea1191-424c-48d3-b5e5-a08760bf0b12
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value' = ROUND('Sensors'[value], 2)
		dataType: double
		formatString: #,0.00
		lineageTag: 2161aa13-9cc5-4674-98ff-db77c2135c0a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: 81e4eabb-2b36-4e0e-b4a0-773453440f75
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: 45d16c5d-4638-4c39-bc11-d80c673e5160
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: b8183005-7571-4998-b7ed-f90b6ca72dfb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: dea2006d-1665-4e91-978a-abb7e17cbe14
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: 033639ce-5f23-4552-a573-5cb4eb1b2d58
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Month' = DATE(YEAR('Sensors'[reading_time]), MONTH('Sensors'[reading_time]), 1)
		dataType: dateTime
		lineageTag: 7ee12444-6cfc-44e8-b0eb-74960ec00dd0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		lineageTag: 4028ab54-ea8f-436a-8ce6-d37bb7b35df8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: 9c5c375b-fc93-4186-a70f-9e9cd14e9261
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: ad70bb9e-ee90-46bf-8b4e-16ebf05d8b58
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-a643e587-4661-4501-b208-3ef459fe9f73' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Sensors Table" = Source{[Schema="DBO", Item="Sensors"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Sensors Table", {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

