table Calendar
	lineageTag: 03bf77e7-ab02-4d6f-a33c-ffd85bd8a7b1

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9a640ce0-3b63-4393-9fe8-89e3eab2b87b

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c05b2a35-5ad4-45ef-a582-955f6df6a686

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 083dfd24-4f64-4e15-b0a0-fb5ff4eba3a5

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 32be1361-18fc-404a-a06e-8be6e11837e7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ed5a4e25-7390-4c26-85de-496c5eb16cca
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 133e1d81-37cc-494a-b2b7-f2c3bb01699d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 6af06107-92fc-4738-81c4-b2d26a29e63e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 16821dc6-919c-4d62-aa3f-280af4a5ca86
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ca65c107-9128-45f6-b718-b270a4ce0423
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d63148b4-1972-4a1e-b342-a1ed9a58c08b
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 8c49eb26-c6e0-4c57-9104-ea1ef5f3f07a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 286d3d45-6816-4fcc-a29f-4b5a4601a0fb

		level Year
			ordinal: 0
			column: Year
			lineageTag: 0f4e5d9c-8352-492d-b26e-dfdde672d121

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e11bb6be-77a9-4e64-9cb3-30bc93073ca1

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 253508a7-79f8-4a1e-946e-4da77befab81

		level Day
			ordinal: 3
			column: Day
			lineageTag: a71559e7-a6fd-43f4-9f78-98fb90dd4272


	partition 'Calendar-8a5e1cfa-f54d-4feb-9560-4e0de4d272c0' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

