table Calendar
	lineageTag: d69cf92f-207a-4ea2-ab7c-2ebc91e4ff9d

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 59550b55-fae3-4144-9fc3-323a55b61c6a

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: e9a7ef31-5132-4840-a5db-d48a2cb19de7

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: cac02d5d-25c1-4987-a764-18e33531c809

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 82dcbbb5-b402-40d6-93df-dba1dde47058
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 99390a27-1a18-4271-b6d4-2d3b17560297
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4b20c619-08d9-4f52-9292-d0accc4c27cf
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a8aeafb6-49d7-48a4-a0a2-78f9a1b2f5b2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: eaf373db-bf2b-4742-ba43-8814a6fbd03e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3322969d-1cca-4730-8480-680702fb83c9
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f1f9da08-bd2e-4098-836c-3f3c95881229
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: fa44056d-7790-402c-b563-3e7b6d077743
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: faae7c8b-70e9-4d28-a5da-9d76b2e410e8

		level Year
			ordinal: 0
			column: Year
			lineageTag: 57777f85-5306-4152-a1d2-49eb5021360d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ae7424fd-1126-4bbf-8fd5-1917f83c5bfd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: bc7bb2d4-bc1e-4615-8966-7010a89090fd

		level Day
			ordinal: 3
			column: Day
			lineageTag: 3c354037-89e4-42b3-bacb-008f9d23dff0


	partition 'Calendar-490a7624-2f87-4331-9957-d1a07bc1720f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

