table Calendar
	lineageTag: afea18fd-1f22-4dd1-b8e4-6f8c309104bd

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: df672f1f-bb1a-402b-acf3-a59946e92aa0
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a81df252-6ab6-48e3-93d3-57244609ab68
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d79eabb7-f7ca-4ec7-a213-8f4ee177e520
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b04aff86-fb22-40e5-ad25-489a5a7b638e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 24e5f665-a9e1-4355-acd8-f6c5254416df
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ebafc188-4e44-42f0-baaf-e6001a770f8d
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e6f4be22-8b31-4d67-b9e7-b4c47e297449
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 92b25736-02ed-4be8-bd44-92deda15516b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f3b948e6-e6de-4c3f-ad24-d5217957fc0b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 1509c285-c879-458f-ac3a-cfc0f3fe661e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 5ddd4b80-5371-4e91-9bb9-509cbea78aeb

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f3e31e60-06fa-4837-9848-642fe70a80e0

		level Day
			ordinal: 3
			column: Day
			lineageTag: aac57fa4-faac-450b-bafe-de48daaab79e


	partition 'Calendar-a87e8747-f8cc-46c0-9cbe-0a2ea907b585' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

