table Calendar
	lineageTag: faf7b2bb-d204-4fea-b8f6-da45ae005fb0

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d4ce5ea4-c1fd-4c25-a3b6-7761ce1b8d65
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 111a6c12-49e3-48b9-8436-8c0855ea3589
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: a033ce9c-0b60-469d-b1c2-f00ee6221ed9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 35d1a0a4-cf11-4a61-a496-e824b0fd5161
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d789f2ee-c478-4d72-8531-c92be39700ec
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d4ebe2cc-84e3-474a-bd8f-78a2fb53f010
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b9db73dc-dbfc-43a9-9ed7-3aa9d474a08d
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e741f31a-e8bd-4166-a678-c46cfb9f1e13
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7a1617e8-8888-40dc-9565-6a21029e5ad3

		level Year
			ordinal: 0
			column: Year
			lineageTag: 278da773-7c28-4048-bcca-ddae8026ed13

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 302e2d77-bc7f-4556-a546-33bf70c73eaf

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 15bdbbb4-e30b-4ce7-bf62-b895e5f6245e

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1ac195c2-f4e0-4e49-a6df-acc9b43ac846


	partition 'Calendar-b4bd8205-5d94-41f5-9bc3-36941d1c1f43' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

