table Calendar
	lineageTag: c9488de8-11a0-4ad4-bf14-ed076fc5d493

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0856c975-1e8c-4ff2-a7b0-4095f7943730
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 3185ac8c-35ee-40bd-9842-0848f29051db
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b452f54a-1483-4b3b-884f-d0f77b625b5f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 34683fa8-a6ae-42c5-b327-032b53a7f710
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e545ec87-cad4-407f-abc0-0c910e61d575
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: fbb54308-6987-432a-9a22-1bafad18d8ea
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 3796458a-1ab4-44f3-b603-3ab7fe443402
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b4ad7b9d-df8a-4aa9-9b51-fd931e49d84d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 046892f1-52ac-4ea8-9105-07685fe2873d

		level Year
			ordinal: 0
			column: Year
			lineageTag: 0eba9ee8-e6b8-424c-8d9b-61003262f69e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 0d90218c-e468-4e3b-832d-200b9b21d4eb

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 839fb79a-7fa2-422c-8afb-b97561c7ec73

		level Day
			ordinal: 3
			column: Day
			lineageTag: 03f3f69e-5614-452f-aabf-7689704de07d


	partition 'Calendar-5671365a-76c8-4679-8430-5c6fc0436463' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

