table Calendar
	lineageTag: 55320132-34be-4f7f-870f-a1510cc89827

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b1fa2b3e-722e-4ad6-b3c4-f75832f25858
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a3dc9ce5-ec41-453c-9876-2cf8fddcdfcd
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 2d95395f-04bf-4cb8-8ccd-3e12508b28e6
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5d8b3950-1092-488a-80af-5b2f474c458e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a4973331-4bdb-45dd-8b0c-737d35a98dea
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 456f33d5-07d3-424b-a411-7c47584d3f27
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 17f7147c-847a-438a-b916-5690174a94ce
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7a027728-cbb0-4ceb-b1cc-a3438147d70a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 801a0bf8-7b09-4ff7-9b5e-f1d21acf2ac1

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7897c7c2-348b-4a2f-ad8b-5752bfce823d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 5948512c-f257-450a-a9e3-7d3f807e9927

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 06267ac8-5d8d-477d-a19b-07e436d30146

		level Day
			ordinal: 3
			column: Day
			lineageTag: ba93b5e0-3706-43c9-beab-eaa3ced4ba9d


	partition 'Calendar-2c8d0c7e-3ab0-4f5e-b49e-cef3ca8fb9f8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

