table Calendar
	lineageTag: e7e4ad82-4e24-4b95-8746-da8926164edb

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6626e230-b605-47a2-87ca-fb641d62ea8b
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 87a30868-865f-4138-8e2f-7b37e5de67b6
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c5513393-9bf5-4620-91b7-1ae3dcd47f5c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 302dce83-55b6-4f88-a655-9b0bfd598913
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c73f0986-ffd5-4d9c-8f6f-8f0af0f1dd4f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 78d53402-c6ff-41b0-aa9b-01d973a5ff3a
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 3390f87c-f6c7-401e-ac7d-f8c6573a314f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f481721e-4dc1-4c7a-848f-ec44b9069784
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1c4f84c0-afc9-487e-86cc-caa83c45c627

		level Year
			ordinal: 0
			column: Year
			lineageTag: a4b5a202-3a55-4cec-9d1a-44789d680155

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 5a153db8-7ec5-4a08-8b3b-95676f794d0a

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 58c52d1b-af56-4063-a186-14135ddde6f6

		level Day
			ordinal: 3
			column: Day
			lineageTag: 8e1d586b-6b1a-4578-99d5-81515587911b


	partition 'Calendar-6c7181a8-6ec8-4a9d-a090-7fc62c290d3a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

