table Calendar
	lineageTag: 77377282-eca7-4e73-ad8f-8703fdb30094

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 905d4fb6-5690-4e91-80e0-880bd14d16a6
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f5c76ca6-7725-40c7-a8a7-d7e090d35c2d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 897c5e67-6b30-496e-a458-f116e219d7db
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2c502bd5-b103-45b7-8ae1-35573c1c49d1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 21d2ebab-04d4-481b-8b36-14f0d04a68ba
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: c9ced8d4-f732-45be-bdf1-e22bde48aa3a
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b96a891b-395d-43b5-8dc6-f53c7b3121bd
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 26aca5ab-2b06-47e0-88c4-a3f5862ad081
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b2e35df7-dc77-411d-975a-aa6c7d9bebe5

		level Year
			ordinal: 0
			column: Year
			lineageTag: cb4351d2-a879-4047-a757-b192599c2217

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 89cb136f-6be9-4e38-8559-f8ba139b8c52

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 76cd1f19-a460-4eb0-9769-67acb560d678

		level Day
			ordinal: 3
			column: Day
			lineageTag: ba6b61c2-12ce-4fa3-a692-b99dbb82e815


	partition 'Calendar-2272bcbf-ddc4-45f2-95ad-69e96ae3ab93' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

