table Calendar
	lineageTag: b1c54ff3-52a9-4808-b50a-c60c7a394cdd

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5a7df30a-23e8-4f75-9859-7cc240dbb60d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e8b9a12b-dda4-4a20-8e33-80da98cfece8
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f6734d62-697e-44df-9ba8-2b991e7da72a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b5588222-277e-4282-80f0-09544fbfc17b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 6a9a4209-3d05-4aa3-8e82-a0d2e22fd66c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: cfcd6868-8088-403a-b01f-cb7292924271
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f8db7517-d581-4a47-a3cb-f7207c9b189c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 41b2d30a-24de-4ca3-baa9-c563efe8fc0c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9bf5b553-201e-4a1d-af8d-2a10552d392f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6afd3730-c9b5-4fbe-a138-1fc00b8179fc

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 659bf14a-4bd6-44d2-9efd-e968c623b4f0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 848ca255-4260-4bf8-b009-34b767e926a8

		level Day
			ordinal: 3
			column: Day
			lineageTag: ab30a479-956b-48dc-b040-ef41438485ce


	partition 'Calendar-1f81d7b1-0cd0-4e5d-967c-3306ca7ba058' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

