table Calendar
	lineageTag: 1ef95496-5d7c-4573-bebd-1ff1dc2e7da7

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3e9305b2-e3c8-44c6-ba60-4db70f3920c0
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 093f3b97-1808-4548-a7d7-457dcaddff8c
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e2cce166-3537-42d0-9f5f-536db3f5b289
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 9a80e072-eb73-4ef8-bc2f-395b8082f70a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 7727aded-1362-472f-b37d-a478bc437894
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 47932063-b76a-4553-9c7e-4922147d846b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 189c574b-1c4c-4371-a624-885471213811
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7124f377-04d5-420a-bb31-ed549b92cbcd
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 009664c6-8b86-49ea-a184-bba80063d5ed

		level Year
			ordinal: 0
			column: Year
			lineageTag: d410157b-2802-4edf-864e-c71593cd12a8

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 73350598-8e64-4136-aed5-18ab8206e08b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: b06b5c3b-e21b-4991-92d3-1e1463e44dfa

		level Day
			ordinal: 3
			column: Day
			lineageTag: 67d08abc-b012-4d90-8e91-16af67da2d58


	partition 'Calendar-8219dac4-cc60-4038-ad33-22ac49953c75' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

