table Customers
	lineageTag: defdc81a-1f78-4085-9022-70d34ceda064

	column customer_id
		dataType: int64
		lineageTag: 7eec2a12-6037-421c-9a7a-5c4ea1f4f96f
		summarizeBy: sum
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 73d4ba76-da75-40ee-81a8-69682ffa8341
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: c9aff212-fdca-4fae-b5b3-7a4733601490
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: c826ddaf-2061-456d-a3c5-2a60cefacc6c
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: f173b572-f70e-4e67-af4d-2e49221b769c
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: d13cc4c9-57c7-46bf-91da-9a0bf60bd77c
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: f8f3045a-987d-4f4c-bbb9-b016e543f1b6
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: 134f77fa-9b2f-47fe-8656-1c86702853b9
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: ab97f0d0-c2a0-4dff-a401-11c63da6faf5
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column customer_email
		dataType: string
		lineageTag: 3f023ee3-47e4-4b72-a52c-8933cb60e264
		summarizeBy: none
		sourceColumn: customer_email

		annotation SummarizationSetBy = Automatic

	column first_purchase_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4183054e-a40a-4b6f-b1a4-f8f3bef05230
		summarizeBy: none
		sourceColumn: first_purchase_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Customers-040d7b5d-154e-4545-b341-58643537feaf' = m
		mode: import
		source =
				let
				    // Source Snowflake: acme.snowflakecomputing.com
				    Source = try
				
				        Snowflake.Databases("acme.snowflakecomputing.com", "COMPUTE_WH")
				
				    otherwise
				
				        #table({"customer_id", "customer_name", "segment", "city", "state", "country", "postal_code", "latitude", "longitude", "customer_email", "first_purchase_date"}, {}),
				    #"ANALYTICS" = Source{[Name="ANALYTICS"]}[Data],
				    #"PUBLIC" = #"ANALYTICS"{[Name="PUBLIC"]}[Data],
				    #"Customers Table" = #"PUBLIC"{[Name="Customers"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Customers Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"segment", "Segment"}, {"city", "City"}, {"state", "State"}, {"country", "Country"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"customer_email", "Customer Email"}, {"first_purchase_date", "First Purchase Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

