table Customers
	lineageTag: ce72c3a4-ddbd-4425-9ff4-116834159f84

	column customer_id
		dataType: int64
		lineageTag: 1d736612-fa4a-41d4-9674-a49c3bdaa94b
		summarizeBy: sum
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: c3171a10-97d9-4a28-a940-0912ec5072ae
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 89b8dc36-b777-40a5-bd35-48c4f6af38b3
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 1b54afc7-456b-4b7d-8ca5-f26548744f5e
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 442a92af-3af8-4777-91af-3964de53cb07
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 49f18b6a-9113-4e93-9f19-97475f374074
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: 9eadd448-0bbd-4d4b-82ee-be218a006704
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: 5b604863-a4d0-4da9-b1a4-d7482cd86bc8
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: 643f12dd-78ec-4dbf-a845-e8e04bd21abb
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column customer_email
		dataType: string
		lineageTag: 21b7b8d9-8baa-40d5-adfc-ca6984eb129e
		summarizeBy: none
		sourceColumn: customer_email

		annotation SummarizationSetBy = Automatic

	column first_purchase_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e9a4820f-50ac-4802-8e42-447d32935914
		summarizeBy: none
		sourceColumn: first_purchase_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Customers-418eb7b6-9b14-4ae4-a224-f887c1334d97' = m
		mode: import
		source =
				let
				    // Source Snowflake: acme.snowflakecomputing.com
				    Source = try
				
				        Snowflake.Databases("acme.snowflakecomputing.com", "COMPUTE_WH")
				
				    otherwise
				
				        #table({"customer_id", "customer_name", "segment", "city", "state", "country", "postal_code", "latitude", "longitude", "customer_email", "first_purchase_date"}, {}),
				    #"ANALYTICS" = Source{[Name="ANALYTICS"]}[Data],
				    #"PUBLIC" = #"ANALYTICS"{[Name="PUBLIC"]}[Data],
				    #"Customers Table" = #"PUBLIC"{[Name="Customers"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Customers Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"segment", "Segment"}, {"city", "City"}, {"state", "State"}, {"country", "Country"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"customer_email", "Customer Email"}, {"first_purchase_date", "First Purchase Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

