table 'Target Margin'
	lineageTag: 692a0ead-4897-49de-90ac-012e889354f7

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 5eefc1d1-4ad8-48bf-ae5b-ecf434fda64c

	column Value
		dataType: double
		lineageTag: 688cd4da-fa65-4ec2-9d35-62f23b383dd3
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-0e107482-9854-4044-9674-5fb488e00cea' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

