table 'Target Margin'
	lineageTag: 5979a851-7f80-4ee1-bd6c-982345fa2722

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: b846c365-0f9b-4bbb-a7b0-0009eb2b073d

	column Value
		dataType: double
		lineageTag: 37e79112-cc23-45e3-a487-a7f02c2a6d84
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-5e069f38-60bd-4262-8b59-c5779e7a539c' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

