table 'Target Margin'
	lineageTag: f7fbe118-bc63-444a-b1ee-db12c6bab94f

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 270f6016-e44f-439c-bbb0-b74121372122
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin'[Value], 0.2)

	column Value
		dataType: double
		lineageTag: 1e9510d8-4f3b-47e1-acfd-17a6e0f4c9a1
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-be27a6c2-85a8-45d6-87b7-7687b2cfb332' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

