table 'Target Margin'
	lineageTag: 7a9205ce-e44c-4769-9e99-faa14613936a

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 7dccb716-daf6-42a0-ae0f-cf3ba9b5d715

	column Value
		dataType: double
		lineageTag: 54161050-ec7c-4780-84de-4f303fefbf22
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-b069b0d7-4371-485b-bc3d-45ba11c98013' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

