table 'Target Margin'
	lineageTag: 35d33f2b-70a0-4aa3-9005-ca1ec480ddaf

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: c0e8074d-e179-41e8-b763-a21511b7c7a8

	column Value
		dataType: double
		lineageTag: 13b523fd-877d-44da-80de-40985da69931
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-f616a296-f737-4232-8121-17d5a9169a32' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

