table 'Target Margin'
	lineageTag: 890b7567-e003-412c-ad23-7134bffb5cbc

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: e2d96182-ef3e-4a54-bd62-98ee3927803f

	column Value
		dataType: double
		lineageTag: fbddcf0e-c8b9-46b8-859d-7a19cf80edbd
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-de0091b1-38c7-4ddd-a5ec-a15b665043c1' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

