table 'Target Margin'
	lineageTag: 99af2879-4a49-4c89-8ce7-6447b22cf155

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 6b505ddf-4f9f-4ae0-a72f-b81a8c5fb12d

	column Value
		dataType: double
		lineageTag: 0333220e-1675-44e3-b575-989efdb4f350
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-a10e7b0c-f9b2-4cc5-8ce6-82d9b10aa40e' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

