table 'Target Margin'
	lineageTag: 8f25591b-cc18-453c-ad2a-fc508a6267dc

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 59d833fc-6aeb-4e0d-8a4f-34ea69ba657a

	column Value
		dataType: double
		lineageTag: 1abb9851-f3d6-4d89-b0af-aacb9708ef15
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-96bf7acd-edaf-4694-ac0d-2aac6101acfb' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

