table 'Target Margin'
	lineageTag: fa41838a-6d60-412a-a03f-3eac455a7632
	description: Contains 1 columns and 1 measures: Value.

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		description: DAX: SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: c0ae86f7-6932-413f-ac82-f93b23c9bd7d

	column Value
		dataType: double
		lineageTag: 51b9c93a-f291-4660-aa60-fafa7db7439f
		summarizeBy: none
		sourceColumn: Value
		description: Double column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-58bfb125-28bc-439c-8b85-e996f16e86bc' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

