table 'Top N'
	lineageTag: 1cbc01f1-b75b-4e98-a488-35efcee439e9
	description: Contains 1 columns and 1 measures: Value.

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		description: DAX: SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: e58f0fa7-db60-4f28-8a3d-c31ca09eb43a

	column Value
		dataType: int64
		lineageTag: aab8f205-3e05-485b-b11e-a84f449920a0
		summarizeBy: none
		sourceColumn: Value
		description: Int64 column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N-2ebfb9b5-4fcb-4071-a011-459610d87d26' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

