table 'Top N'
	lineageTag: 75e84266-afd3-469d-a063-7253ed70414e

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 17c340b6-9bb4-489a-98af-da61c13c7145

	column Value
		dataType: int64
		lineageTag: cb62b36c-26e7-4ad4-9310-c62209bccbea
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-7a42a049-f469-4dcc-998c-1f3347a47531' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

