table 'Top N'
	lineageTag: aeef78df-2565-4d4d-a95e-5450857dacba

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 43c1d874-d30c-4c9a-b10d-ad66c3f3bdb3

	column Value
		dataType: int64
		lineageTag: 3b5f4e20-991f-4044-a42c-5d78dc66cdad
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-8996f888-04cd-4da0-b8b0-47ef54d18a15' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

