table 'Top N'
	lineageTag: 5c4732d5-0fb1-4e80-9ebe-6472c23033b1

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: e28f091b-bccf-4874-b980-81425cdd8743

	column Value
		dataType: int64
		lineageTag: 3fee8d79-4b2f-452a-845c-bd267535d41d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-553f43c6-cfb3-4b13-bc6c-908dce15ef05' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

