table 'Top N'
	lineageTag: a5725e3b-b639-4482-988c-18a03abd17d0

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: a0f0b982-362a-4224-afcf-ff6c71f626ba

	column Value
		dataType: int64
		lineageTag: ad31f2a3-ccdc-4708-b8ff-119c1516908d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-5aed4d80-6f99-4959-b77f-49ea744bde6f' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

