table 'Top N'
	lineageTag: 5543e3ea-07cc-4b8f-8998-df3b3f0352c9

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 4558e560-e289-4469-b357-8272018d5320
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N'[Value], 10)

	column Value
		dataType: int64
		lineageTag: c3a32b95-0e94-43ec-8bcd-0f690ff26ac2
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N-43465bba-50c6-4877-a8d3-08236367edf5' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

