table 'Top N'
	lineageTag: a05926b3-76b8-4cd6-8bfe-489f1e2e3946

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 8c61fd55-384c-479f-81c9-bc8650f3566d

	column Value
		dataType: int64
		lineageTag: 24ff9906-223b-4e44-b36e-61ac593cfdaa
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top N-46ffb6b0-bbbc-45df-a0ac-05a3de64b14e' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table

