table 'Target Margin %'
	lineageTag: 9caa3197-6a66-434a-a494-319ce47f3a71

	measure 'Target Margin %' = SELECTEDVALUE('Target Margin %'[Value], 0.20)
		lineageTag: 412e5714-3c59-499b-bf6b-8b55506513ed
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin %'[Value], 0.20)

	column Value
		dataType: double
		lineageTag: a90e147d-67d2-40bd-b26d-0e734946d241
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin %-ecf4264a-d00e-45a9-8cb6-53faefafae00' = calculated
		mode: import
		source = GENERATESERIES(0.00, 0.60, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

