table Calendar
	lineageTag: 8c26fdb5-cb79-4cad-9be6-c618c9e06c58

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 27dfd006-714c-4c23-bc7e-fd9631e12374
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f1da98fb-dac1-4c83-99e5-b4cc1699d926
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e0fa9564-2b38-4295-9838-31d572711d83
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 9062080a-c98a-4e5a-bf90-5e8fa136e48c
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b00e29e5-2187-4a82-b482-20ad05da2cc5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 2f14c7a7-3cf4-462b-9f1d-a5330363f4f2
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 3d7f56b0-ebcb-431a-9621-92b9b4b03c89
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 0a999025-ba21-4038-8947-e822f2d39f21
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: be6d9555-3afb-4154-9cec-f3eb0a05b30b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 534981a2-a727-48ae-bd89-003e487b86e3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b7d71bd2-dd13-43a1-8885-7db40cb80007

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 369fa2de-95a4-4d1b-9f05-e1e6356e062a

		level Day
			ordinal: 3
			column: Day
			lineageTag: c8a3b0cf-c5ce-4b84-b073-a2c2627c82dd


	partition 'Calendar-c943dbd1-19f7-4f1f-ae8f-51717a617c7e' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

