table Calendar
	lineageTag: c3a60fdf-34c7-4d4e-bd79-6b6b48983c39

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 918bbc19-0383-4058-9cb9-413cfd69c0a9
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1a74ec97-0cf1-4e68-a083-d1ef615b84e0
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 75ddb7eb-40e1-4e65-a917-02786882ad35
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: fa6ebec1-b289-49fb-b9f1-96a0e6fd72fe
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ab6e9186-4e12-4dc0-98b7-bc6dd8f525eb
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 2e6ca590-a026-4d72-9e67-3bd12d4380c4
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 91410192-1d82-4cec-bd5a-8353eca988dd
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 087fcd3e-2f14-4fb8-9f81-4016cfa82c5d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 53046d9b-1350-41a6-b857-f233e42e0f5e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 602c27ad-aaa8-4ba8-9a3a-0e965ba47802

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 7e452c04-c91d-42ef-927e-a222ef17519e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8f88b263-4dd6-4c57-a346-b89d6224be4d

		level Day
			ordinal: 3
			column: Day
			lineageTag: de325470-b265-4046-af47-00c1a9f4ae59


	partition 'Calendar-278b1005-7a69-441c-b002-cd6457b551f8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

