table Calendar
	lineageTag: bb039ad3-3bb2-4c12-9f9f-0114703e577c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 04d3431b-f7c1-49bb-b099-ec636f641759
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d244fafb-ef63-4df1-9c24-d5ce87bf178d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dcf3104f-601f-4912-84e6-ab4252b7969b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7d636762-28ec-4c53-b01a-0360d2daa77f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8a430286-e8d6-4fea-ba50-a71863a9d7d8
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 71aaac61-7f63-46ab-a2aa-da822722ae0c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f3539a6c-3074-4f15-80f1-e475a338a2b5
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 2aab3425-0ed9-4030-90f7-a961f1b38e43
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e9df037d-fda3-487f-a3ab-a65ae94188ed

		level Year
			ordinal: 0
			column: Year
			lineageTag: 8be8d55d-407d-4cd8-9999-3b498b53580d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: cbee47c6-ebf7-496e-b77d-7f0ba5f9c2f8

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9c368002-73ac-4cab-a18a-03352d1a98d3

		level Day
			ordinal: 3
			column: Day
			lineageTag: 439267f3-9e79-4785-83c9-0cfe08fc7b71


	partition 'Calendar-6d0f35b0-6bb1-42a6-8a45-7c186e135dfc' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

