table Calendar
	lineageTag: e44a4f82-0c59-4428-8fda-2b1dc7ce9081

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 508d6a7e-fbec-4f3d-b076-b069039d1804
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b8e6ec84-0dc0-4878-9050-970b94740449
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b64cb5e7-248b-4c3e-9c55-c0f89e80b55f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: af3f61cf-6f80-4a41-a472-254ad17aeb27
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 998c1619-6342-4019-9e76-a61b2895bbb4
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0f228ad2-a64d-4703-b8be-4ea2d2ba64da
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 142995f1-31d4-4ce2-8ac4-e0ac5b91ab82
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: fc3a7b70-be78-4435-adb3-29a06cc5cfe3
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1a5fbc82-f62d-4a03-b09e-01bfa39d004a

		level Year
			ordinal: 0
			column: Year
			lineageTag: a6c08ac2-4f7b-4047-92b1-e96edd17bdeb

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 66dd6070-f98f-4cf7-bfb4-7272fd5257c0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: db903532-8d4c-458b-90c8-a3a89d4f9134

		level Day
			ordinal: 3
			column: Day
			lineageTag: 372f7b0a-99ff-4809-8ec1-6013e017f829


	partition 'Calendar-d3d28f79-81cf-4bcc-9883-2c100c5db447' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

