table Calendar
	lineageTag: b0446f3c-19f7-4f77-acc0-ec57ae37f661

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0301cc39-0b84-446e-a659-16021675b1d7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 23ff6932-709d-438d-ae75-278d2a68b606
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e77ff4fa-0243-40a5-9000-515a55856fdb
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7dc71c23-cbd8-4fcd-8eb0-2e6fc6e04b13
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 13202d06-bce9-41e1-b2f6-e9b47e3e5669
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 10798a63-6a13-4baa-8d25-8cdc6051bcd9
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 623dd97d-5038-452f-b61e-46f689dd665a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d9aca2ea-6ffc-4d21-8083-51021af431ff
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e9cb0fe2-c9a2-4034-9914-9c56ea8fe06d

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7c3a275e-e499-40cf-9952-49994d60f760

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 83561d39-ffc4-468e-b485-a10d96d76d93

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e7823b4e-423b-4b53-9903-0b0b13789aeb

		level Day
			ordinal: 3
			column: Day
			lineageTag: 03a6e85d-e16b-4e36-90a2-cd78c023d97b


	partition 'Calendar-24de0dc3-ff06-46a7-92ed-f92cdd829d1b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

