table Calendar
	lineageTag: d45d0f86-ac37-47af-9e4b-3f66b3618b06

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8c8bbb7f-72d7-4a08-9cbe-37b55566e597
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: db2ab322-8ec7-4901-8cf1-68df8f3c8a4b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 31bb9ff4-9fd5-4712-a522-b712add95a2a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 31521161-6c4f-48ba-8577-a05091211c45
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2f722b2d-3dd3-4fe6-b040-cd810fa3fc70
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a007804b-fae5-44ee-9434-2d737ad7feed
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 3c86f03c-9121-4962-b61f-16a403bd2824
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 1dbc0bde-e032-44ee-8c13-0430f28b2f7e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8b01ccca-5a08-4a6c-b4b9-26bbeeed5ffc

		level Year
			ordinal: 0
			column: Year
			lineageTag: 37099232-30bc-4826-aea8-0dfabc7c3e58

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 41b730d4-718e-4501-a5ee-56a1308b227f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 88d1b4a7-6ef7-4c27-9925-e0df5e16705d

		level Day
			ordinal: 3
			column: Day
			lineageTag: bee87485-533e-4bcf-9624-1ad601e73900


	partition 'Calendar-35e4ed1a-20cd-4e1c-afab-f3e854ff8834' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

