table Calendar
	lineageTag: 8c731d01-c88e-48bc-b7e2-5e5dff56f428

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 93dfc6ed-e0cc-4248-95dc-4fd723838c5e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 29daeabd-d678-4c48-b47f-5d9780e13cd9
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 891b9fbe-d9a2-4e0c-9989-3a92cf07a0bd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 699c87ca-0527-4236-9921-ab06ccfebc52
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a78422fd-5240-4d21-aafc-a9bf5e79d9f2
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 9311316a-6132-40ff-9321-6e8f2ad70d0d
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2145c6a0-9600-4e76-b9e7-dbd58da8c762
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a23c2dcf-756e-4166-9525-35cd883818f9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6f67f58e-a003-41bf-a2f9-e6c2609fe0b9

		level Year
			ordinal: 0
			column: Year
			lineageTag: 28fdf7ac-b2d4-4b35-b2b3-92b183a240e3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c8d64998-cef6-45f7-b3aa-65c9826a0dbb

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f379bb12-580e-4cf0-8dba-6686ad001512

		level Day
			ordinal: 3
			column: Day
			lineageTag: 8a219a7a-9ca1-4278-89fd-0cd43f3bff18


	partition 'Calendar-a9c6916f-5a42-46f4-8289-bd2277d09dcc' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

