table Calendar
	lineageTag: d1080773-17bd-4f16-bfcb-e7aa4084c604

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: cc77f745-6d2e-4155-b04b-1eaea9f0c77f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b79337a5-b8e4-4b12-af11-53f0323c895c
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f01cd868-5d00-4238-823e-d71eff268d77
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 1b976a4a-f5a8-4bd7-a9e0-aa23d1fc90b3
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2b40658b-2690-40a1-a790-1a81af6a8d3c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bdc4f232-9f04-4a23-8ce7-f13eaa93eb44
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: cdadd29f-8bdf-4bfa-b9e2-56f512f63199
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 50fc9660-2b4d-4e5e-bd4b-b82058a3ee55
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1b218a45-7a5b-410a-80d1-0b227c175642

		level Year
			ordinal: 0
			column: Year
			lineageTag: fa4c016b-7876-411a-9553-f34a36908d92

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d80066e2-e93b-441b-aac3-34755e505915

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8ce9b5ee-3d25-41b9-8488-26e7592d11e7

		level Day
			ordinal: 3
			column: Day
			lineageTag: d3271e99-aac5-4053-aebd-f2a6dd8c6e65


	partition 'Calendar-1be88d8c-c934-4741-8518-c862c4f098a4' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

