table Calendar
	lineageTag: 0775a035-258a-457d-bb91-b885b5225149

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4d3c10cf-a5f6-4c39-b332-661e7a9e625c
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: bfbb1e19-b52e-4029-ac0e-d91b4f207281
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: fefb78a5-4ac5-45f6-b700-66415dd7a645
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b9734229-763f-426b-8c80-b4ea6e7015c3
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 167577f9-113b-45bf-8635-21c383f4b561
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8550353d-4dd5-4145-9a89-1197bd02af9f
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7728b74a-0cbd-4be7-8d74-fed214bf29b2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d835212d-c6ff-4e14-92a3-fdf0c871f9bf
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: bf94b522-a6b7-4f08-8e85-156187cb3e3d

		level Year
			ordinal: 0
			column: Year
			lineageTag: 71320508-8eb3-46b6-b426-8c9cafb991dd

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3bba4a50-f333-4c55-a532-3da759653724

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1cf5f39d-00c5-45c9-b9e1-edab203ff7de

		level Day
			ordinal: 3
			column: Day
			lineageTag: 09cc2159-441d-495e-8944-392134d9a3dc


	partition 'Calendar-233d1a22-a3b4-4b7b-b0d0-51ad5bc0a973' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

