table Calendar
	lineageTag: 41f7281e-eb86-4235-8201-3165a39684d7

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 38a7bb52-fd1f-4563-8bd2-2ec6550eded5
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a3e83fb0-f2ca-41ee-8209-b6a057c00f77
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 13b1bdc7-4aca-4164-a820-25c95aacbe5b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: dc018d74-92b1-41ac-949b-9ec9a777af3b
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 414b62b7-fa3e-469b-baec-185f5e42a379
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b5e20cee-163e-4160-a0dc-e4a74812d98b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ef963612-17d6-4bd2-98a9-95021a03d686
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 5430f790-0c22-4525-9a3c-e92c1181f5d3
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5e0e1690-8f06-4524-8ed9-809e9625f806

		level Year
			ordinal: 0
			column: Year
			lineageTag: 02b4184b-af57-452f-9f32-5a1ed15f9721

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 20d33fed-d37f-4417-a870-b9664d8ac3dc

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4597511e-32e7-4749-8694-d2da128aefb8

		level Day
			ordinal: 3
			column: Day
			lineageTag: ab3b837b-a19c-4f8e-9e9a-c9dcf356c144


	partition 'Calendar-8d2c6e76-12db-4414-ad52-f0d04e946fd1' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

