table Rebounds
	lineageTag: 07dedeb3-4f90-404a-ac86-08b63ea1df6f

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 9aa34102-3018-4af6-9d30-14d200e780c6

	column Value
		dataType: double
		lineageTag: 42c1177d-e9d8-4d06-aed3-63f373f44b02
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-ba66e529-66c1-4c50-beb4-612a93378463' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

