table Rebounds
	lineageTag: a1b1684d-244a-48d0-8607-7dc11b38ec38

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 351dca84-51f6-4c93-bf34-ba592deb4280

	column Value
		dataType: double
		lineageTag: d80567b9-a414-4517-a4fd-27f2e6d79c49
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-ec91f3cf-3b00-42fc-99ec-95aa4e9b706e' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

