table Rebounds
	lineageTag: 0969bca4-8005-4bbb-b52a-2a04f537e362

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 813ae346-f9c4-4eb4-bafd-687e8e7f8770

	column Value
		dataType: double
		lineageTag: 70d6c8f6-a21b-45f1-b918-d417d319f1bd
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 4150a51a-506b-4de0-867c-5eeee8ac3f39
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-b9aa1357-b710-4675-a627-b26a3d918b21' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, "Name", STRING, {{1.0, "Average Deffensive Rebounds per Game"}, {2.0, "Average Offensive Rebounds per Game"}, {3.0, "Average Rebound per Game"}})

	annotation PBI_ResultType = Table

