table Rebounds
	lineageTag: 42e3c18f-5ebc-4d01-a7e1-3a04ed99390a

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 0e093c59-a74f-4e77-87ef-ed3dfcf865fe

	column Value
		dataType: double
		lineageTag: 644e2c06-9f99-4b61-8eeb-162ce7a0f5d7
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: b05c7f63-08b7-4189-879c-e19c562a7e97
		summarizeBy: none
		sourceColumn: Name
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-c36ef049-d2b1-4c29-9ffd-2723680df4c8' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, "Name", STRING, {{1.0, "Average Deffensive Rebounds per Game"}, {2.0, "Average Offensive Rebounds per Game"}, {3.0, "Average Rebound per Game"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns and 1 measures: Value, Name.

