table Rebounds
	lineageTag: a155cae1-d9c8-4098-a74b-5247712aa40c

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 0ab85b1a-1958-4ad2-a9e3-8cec17e34d6b

	column Value
		dataType: double
		lineageTag: f9a0569c-868c-4f92-9f8b-d7413353943e
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-f3c87922-4948-424a-bce1-45b0c09270c6' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

