table Rebounds
	lineageTag: 61293347-63df-4a9b-8b85-67aadf08c1db

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: f2c8c7a5-5ac4-4b21-961e-d081a55c79b4

	column Value
		dataType: double
		lineageTag: 4c7d3fd4-b21a-43c2-ae25-3de707442a0f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 7b528fd5-83f8-44a1-a583-79b879e9d1c6
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-1d7bcdd2-2ca3-4ad7-876a-572b90ee8e35' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, "Name", STRING, {{1.0, "Average Deffensive Rebounds per Game"}, {2.0, "Average Offensive Rebounds per Game"}, {3.0, "Average Rebound per Game"}})

	annotation PBI_ResultType = Table

