table Rebounds
	lineageTag: 665a45ac-0d4d-450d-b8bc-6a8171cde6b9

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 10f4b200-ac89-42e6-85d9-073d303178a6

	column Value
		dataType: double
		lineageTag: 9278dadd-2ec2-4d4d-928a-e36e47b479ab
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-46e59413-423a-468b-b308-5543d7297c28' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

