table Rebounds
	lineageTag: 5a3db240-3eba-4ed5-af7f-19a874b8b8e9

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 22b72acb-5d63-453f-9ca5-83948a6aac09

	column Value
		dataType: double
		lineageTag: 313d37a6-1b92-473b-8f6d-e170001b65f2
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-5ce5b3be-9f43-4b96-81db-1433fe11eac5' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

