table Rebounds
	lineageTag: f0242a3b-eaed-40ee-9a14-b60375410365

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 3fffb8e8-3c2c-45bf-96f0-b76b91b38cca

	column Value
		dataType: double
		lineageTag: 54a74f38-5155-49bf-af10-3415765db7b9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-e268ff37-066c-4603-9841-974578b7862d' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

