table Rebounds
	lineageTag: cd63b284-86fe-4c66-8c1c-4ed7cc061409

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: a46e6b95-aed3-4dcf-93e2-c06c38e86deb

	column Value
		dataType: double
		lineageTag: f5b1eea5-d1f3-4926-9c0d-79f4b21efd7e
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 45ad98a1-1961-47f7-9303-37c613792efb
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-ea7db66e-9d13-445e-bebc-2a6cd50c681f' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, "Name", STRING, {{1.0, "Average Deffensive Rebounds per Game"}, {2.0, "Average Offensive Rebounds per Game"}, {3.0, "Average Rebound per Game"}})

	annotation PBI_ResultType = Table

