table Sheet1
	lineageTag: cef71d92-27ab-4f61-8daa-b03511f4cd3e

	measure 'p. Rebounds' = SWITCH([Rebounds], 1, AVERAGE('Sheet1'[DEF]), 2, AVERAGE('Sheet1'[OFF]), 3, AVERAGE('Sheet1'[REB]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 20fccde2-7e72-4728-a065-2b45be579e0d

	measure 'min(1)' = MINX('Sheet1', 1)
		displayFolder: Measures
		lineageTag: b8ddef87-2853-4427-83c3-a9aca7279235

	column Player
		dataType: string
		lineageTag: 9293008a-4c8f-4a1f-a3bf-5e7fcb1f2799
		summarizeBy: none
		sourceColumn: Player

		annotation SummarizationSetBy = Automatic

	column YR
		dataType: int64
		lineageTag: 7123dd76-0efb-4868-b726-e2db970576ea
		summarizeBy: sum
		sourceColumn: YR

		annotation SummarizationSetBy = Automatic

	column TM
		dataType: string
		lineageTag: a8d6750c-6996-4905-9559-382251d2ff27
		summarizeBy: none
		sourceColumn: TM

		annotation SummarizationSetBy = Automatic

	column GP
		dataType: int64
		lineageTag: 196f419e-3b67-4374-9b97-91db3896a609
		summarizeBy: sum
		sourceColumn: GP

		annotation SummarizationSetBy = Automatic

	column MIN
		dataType: double
		formatString: #,0.00
		lineageTag: 62b59435-5a34-45a9-a260-534bdbc5257c
		summarizeBy: sum
		sourceColumn: MIN

		annotation SummarizationSetBy = Automatic

	column FGM
		dataType: double
		formatString: #,0.00
		lineageTag: 58cc85b8-f6b9-49fa-ac82-4cbcc5492594
		summarizeBy: sum
		sourceColumn: FGM

		annotation SummarizationSetBy = Automatic

	column FGA
		dataType: double
		formatString: #,0.00
		lineageTag: 79d94eff-8421-4a5d-a10f-9d140ff5e65c
		summarizeBy: sum
		sourceColumn: FGA

		annotation SummarizationSetBy = Automatic

	column 'FG%'
		dataType: double
		formatString: #,0.00
		lineageTag: 22b86bb9-bb5a-4dc6-bb01-bf5222434e3d
		summarizeBy: sum
		sourceColumn: 'FG%'

		annotation SummarizationSetBy = Automatic

	column '3PT%'
		dataType: double
		formatString: #,0.00
		lineageTag: cdc4cd5a-f8b7-4446-a7d3-d28f94649a65
		summarizeBy: sum
		sourceColumn: '3PT%'

		annotation SummarizationSetBy = Automatic

	column 'FT%'
		dataType: double
		formatString: #,0.00
		lineageTag: 83e2e126-65d1-4c56-9d39-0edc818de654
		summarizeBy: sum
		sourceColumn: 'FT%'

		annotation SummarizationSetBy = Automatic

	column OFF
		dataType: double
		formatString: #,0.00
		lineageTag: f1339265-8d96-41e0-81d4-89b5b2641405
		summarizeBy: sum
		sourceColumn: OFF

		annotation SummarizationSetBy = Automatic

	column DEF
		dataType: double
		formatString: #,0.00
		lineageTag: f80c44d8-814b-4379-b613-4a9d258cce34
		summarizeBy: sum
		sourceColumn: DEF

		annotation SummarizationSetBy = Automatic

	column REB
		dataType: double
		formatString: #,0.00
		lineageTag: 4fb723e1-8751-49ad-b159-881f64358543
		summarizeBy: sum
		sourceColumn: REB

		annotation SummarizationSetBy = Automatic

	column ASST
		dataType: double
		formatString: #,0.00
		lineageTag: 982a5cb5-cad1-42b1-a2a9-ffbb9cb9feb9
		summarizeBy: sum
		sourceColumn: ASST

		annotation SummarizationSetBy = Automatic

	column STL
		dataType: double
		formatString: #,0.00
		lineageTag: 02a92791-1e26-4353-9a42-f411937b213b
		summarizeBy: sum
		sourceColumn: STL

		annotation SummarizationSetBy = Automatic

	column BLK
		dataType: double
		formatString: #,0.00
		lineageTag: ef4d1cac-0cb1-458d-8c44-0ce53e05ae36
		summarizeBy: sum
		sourceColumn: BLK

		annotation SummarizationSetBy = Automatic

	column TO
		dataType: double
		formatString: #,0.00
		lineageTag: 040d9e71-e154-4d0b-8ca8-3a2f9358cfb1
		summarizeBy: sum
		sourceColumn: TO

		annotation SummarizationSetBy = Automatic

	column PF
		dataType: double
		formatString: #,0.00
		lineageTag: 5675969f-8d09-4ea6-b220-f8232e77f06c
		summarizeBy: sum
		sourceColumn: PF

		annotation SummarizationSetBy = Automatic

	column PTS
		dataType: double
		formatString: #,0.00
		lineageTag: ccf50a06-6dfe-45cb-afcb-cee97177933d
		summarizeBy: sum
		sourceColumn: PTS

		annotation SummarizationSetBy = Automatic

	column 'Action (Player)'
		dataType: string
		lineageTag: d7b878c6-6bd6-4423-8fbc-552264338d4a
		summarizeBy: none
		sourceColumn: 'Action (Player)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1-3b013e67-2b61-4d71-9349-1eeba060ec69' = m
		mode: import
		source =
				let
				    // Source Excel: Data/Datasets/nba_players.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Data\Datasets\nba_players.xlsx"), null, true),
				
				            _nav = _src{[Item="Sheet1",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Player", "YR", "TM", "GP", "MIN", "FGM", "FGA", "FG%", "3PT%", "FT%", "OFF", "DEF", "REB", "ASST", "STL", "BLK", "TO", "PF", "PTS"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Player", type text},
				        {"YR", Int64.Type},
				        {"TM", type text},
				        {"GP", Int64.Type},
				        {"MIN", type number},
				        {"FGM", type number},
				        {"FGA", type number},
				        {"FG%", type number},
				        {"3PT%", type number},
				        {"FT%", type number},
				        {"OFF", type number},
				        {"DEF", type number},
				        {"REB", type number},
				        {"ASST", type number},
				        {"STL", type number},
				        {"BLK", type number},
				        {"TO", type number},
				        {"PF", type number},
				        {"PTS", type number}
				    }),
				    #"Added Action (Player)" = Table.AddColumn(#"Changed Types", "Action (Player)", each Text.From([#"Player"]), type text),
				    Result = #"Added Action (Player)"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 20 columns and 2 measures: Player, YR, TM, GP, MIN, FGM, FGA, FG%, ... (20 columns total).

