table Sheet1
	lineageTag: fdcf0c47-44e8-40fd-b8b0-762a82349c02

	measure 'p. Rebounds' = SWITCH([Rebounds], 1, AVERAGE('Sheet1'[DEF]), 2, AVERAGE('Sheet1'[OFF]), 3, AVERAGE('Sheet1'[REB]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f3483c22-0bc4-4d2d-82f9-15c074162b0e

	measure 'min(1)' = MINX('Sheet1', 1)
		displayFolder: Measures
		lineageTag: 74e00220-fc0b-4489-a688-a10f385b10a8

	column Player
		dataType: string
		lineageTag: 88c55477-872c-43a5-81c7-ffe82a9f0098
		summarizeBy: none
		sourceColumn: Player

		annotation SummarizationSetBy = Automatic

	column YR
		dataType: int64
		lineageTag: 9b655ad1-97ba-4e97-9965-a5604f18290e
		summarizeBy: sum
		sourceColumn: YR

		annotation SummarizationSetBy = Automatic

	column TM
		dataType: string
		lineageTag: 68885932-83bc-4660-b8da-08c149c058fd
		summarizeBy: none
		sourceColumn: TM

		annotation SummarizationSetBy = Automatic

	column GP
		dataType: int64
		lineageTag: c8d78e86-064f-4e89-8764-842ecd3bb650
		summarizeBy: sum
		sourceColumn: GP

		annotation SummarizationSetBy = Automatic

	column MIN
		dataType: double
		formatString: #,0.00
		lineageTag: 7f30b502-5f21-481f-8c5e-e783993ca003
		summarizeBy: sum
		sourceColumn: MIN

		annotation SummarizationSetBy = Automatic

	column FGM
		dataType: double
		formatString: #,0.00
		lineageTag: c8922dc8-0c65-43f6-836a-3164e1d2c3e4
		summarizeBy: sum
		sourceColumn: FGM

		annotation SummarizationSetBy = Automatic

	column FGA
		dataType: double
		formatString: #,0.00
		lineageTag: 0234157f-12a7-4eb4-983f-70aab8f9de3e
		summarizeBy: sum
		sourceColumn: FGA

		annotation SummarizationSetBy = Automatic

	column 'FG%'
		dataType: double
		formatString: #,0.00
		lineageTag: 83f450d8-08b2-4582-bbe7-b8511245687b
		summarizeBy: sum
		sourceColumn: 'FG%'

		annotation SummarizationSetBy = Automatic

	column '3PT%'
		dataType: double
		formatString: #,0.00
		lineageTag: 0e1245f6-1498-4312-8677-a5bc88b9874e
		summarizeBy: sum
		sourceColumn: '3PT%'

		annotation SummarizationSetBy = Automatic

	column 'FT%'
		dataType: double
		formatString: #,0.00
		lineageTag: c65a5e1e-3c24-4c81-b046-52e0b58dab80
		summarizeBy: sum
		sourceColumn: 'FT%'

		annotation SummarizationSetBy = Automatic

	column OFF
		dataType: double
		formatString: #,0.00
		lineageTag: a2195757-be4c-4617-88cf-5c66199902c8
		summarizeBy: sum
		sourceColumn: OFF

		annotation SummarizationSetBy = Automatic

	column DEF
		dataType: double
		formatString: #,0.00
		lineageTag: 641b881e-76b5-41ae-b6a8-ba6e35d6c380
		summarizeBy: sum
		sourceColumn: DEF

		annotation SummarizationSetBy = Automatic

	column REB
		dataType: double
		formatString: #,0.00
		lineageTag: 79a4841f-b48a-42d8-9faa-61feae7c9012
		summarizeBy: sum
		sourceColumn: REB

		annotation SummarizationSetBy = Automatic

	column ASST
		dataType: double
		formatString: #,0.00
		lineageTag: 557df55f-8468-4dbe-8204-8eb37bf447ed
		summarizeBy: sum
		sourceColumn: ASST

		annotation SummarizationSetBy = Automatic

	column STL
		dataType: double
		formatString: #,0.00
		lineageTag: 3c74cf70-f0fa-4323-87dd-f581ca1b956e
		summarizeBy: sum
		sourceColumn: STL

		annotation SummarizationSetBy = Automatic

	column BLK
		dataType: double
		formatString: #,0.00
		lineageTag: 97eea1d0-1760-45bf-806f-5448bc9f68cb
		summarizeBy: sum
		sourceColumn: BLK

		annotation SummarizationSetBy = Automatic

	column TO
		dataType: double
		formatString: #,0.00
		lineageTag: ed3a6f04-d9d8-49b6-a253-bd523595f16f
		summarizeBy: sum
		sourceColumn: TO

		annotation SummarizationSetBy = Automatic

	column PF
		dataType: double
		formatString: #,0.00
		lineageTag: f9e6fa37-e796-49c7-943d-c3a86f7c7eeb
		summarizeBy: sum
		sourceColumn: PF

		annotation SummarizationSetBy = Automatic

	column PTS
		dataType: double
		formatString: #,0.00
		lineageTag: c346e70d-542c-4628-a308-f81f699ea2d0
		summarizeBy: sum
		sourceColumn: PTS

		annotation SummarizationSetBy = Automatic

	column 'Action (Player)'
		dataType: string
		lineageTag: 3178bcff-7174-42f1-85c4-dda7f8c7a05b
		summarizeBy: none
		sourceColumn: 'Action (Player)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1-7be0e81d-dd5a-4b48-9877-c65eaedc2a5d' = m
		mode: import
		source =
				let
				    // Source Excel: Data/Datasets/nba_players.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Data\Datasets\nba_players.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Player", "YR", "TM", "GP", "MIN", "FGM", "FGA", "FG%", "3PT%", "FT%", "OFF", "DEF", "REB", "ASST", "STL", "BLK", "TO", "PF", "PTS"}, {}),
				    #"Sheet1 Sheet" = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Sheet1 Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Player", type text},
				        {"YR", Int64.Type},
				        {"TM", type text},
				        {"GP", Int64.Type},
				        {"MIN", type number},
				        {"FGM", type number},
				        {"FGA", type number},
				        {"FG%", type number},
				        {"3PT%", type number},
				        {"FT%", type number},
				        {"OFF", type number},
				        {"DEF", type number},
				        {"REB", type number},
				        {"ASST", type number},
				        {"STL", type number},
				        {"BLK", type number},
				        {"TO", type number},
				        {"PF", type number},
				        {"PTS", type number}
				    }),
				    #"Added Action (Player)" = Table.AddColumn(#"Changed Types", "Action (Player)", each Text.From([#"Player"]), type text),
				    Result = #"Added Action (Player)"
				in
				    Result

	annotation PBI_ResultType = Table

