table Sheet1
	lineageTag: a2c37b87-d9e0-4e8c-bc59-672a939b2474
	description: Contains 20 columns and 2 measures: Player, YR, TM, GP, MIN, FGM, FGA, FG%, ... (20 columns total).

	measure 'p. Rebounds' = SWITCH([Rebounds], 1, AVERAGE('Sheet1'[DEF]), 2, AVERAGE('Sheet1'[OFF]), 3, AVERAGE('Sheet1'[REB]))
		formatString: #,0.00
		displayFolder: Measures
		description: Migrated from Tableau: CASE [Parameters].[Parameter 1] When 1 then avg([DEF]) When 2 then AVG([OFF]) When 3 then avg([REB]) END | DAX: SWITCH([Rebounds], 1, AVERAGE('Sheet1'[DEF]), 2, AVERAGE('Sheet1'[OFF]), 3, AVERAGE('Sheet1'[REB]))
		lineageTag: ff521959-7363-432e-93a9-5b1d942d59a3

	measure 'min(1)' = MINX('Sheet1', 1)
		displayFolder: Measures
		description: Migrated from Tableau: min(1) | DAX: MINX('Sheet1', 1)
		lineageTag: f75bfb59-a35a-4d8a-a770-26aaaf5dbbf6

	column Player
		dataType: string
		lineageTag: 2a8285da-cdfb-46d2-8274-eb505e07015b
		summarizeBy: none
		sourceColumn: Player
		description: String column.

		annotation SummarizationSetBy = Automatic

	column YR
		dataType: int64
		lineageTag: 1a910f48-915e-4188-be61-8baf5bfd8868
		summarizeBy: sum
		sourceColumn: YR
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column TM
		dataType: string
		lineageTag: 85853a58-3f25-4e67-a6c7-d167112d79f7
		summarizeBy: none
		sourceColumn: TM
		description: String column.

		annotation SummarizationSetBy = Automatic

	column GP
		dataType: int64
		lineageTag: e5f6812f-428b-4b8c-8b94-b70d2f584a47
		summarizeBy: sum
		sourceColumn: GP
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column MIN
		dataType: double
		formatString: #,0.00
		lineageTag: fb557438-3972-475b-8482-daa06df96abc
		summarizeBy: sum
		sourceColumn: MIN
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column FGM
		dataType: double
		formatString: #,0.00
		lineageTag: 6014d8da-1864-4a22-8a42-0577781501af
		summarizeBy: sum
		sourceColumn: FGM
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column FGA
		dataType: double
		formatString: #,0.00
		lineageTag: e9951aba-d1be-4870-acd8-bf8700c87399
		summarizeBy: sum
		sourceColumn: FGA
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'FG%'
		dataType: double
		formatString: #,0.00
		lineageTag: f22d6ec9-c8ba-4f4e-8ecc-09a9e6aee901
		summarizeBy: sum
		sourceColumn: 'FG%'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column '3PT%'
		dataType: double
		formatString: #,0.00
		lineageTag: ff9afd9f-381c-40b4-94fc-1a0df7038776
		summarizeBy: sum
		sourceColumn: '3PT%'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'FT%'
		dataType: double
		formatString: #,0.00
		lineageTag: 3aeff994-ef4a-4978-93c1-f91c5b383895
		summarizeBy: sum
		sourceColumn: 'FT%'
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column OFF
		dataType: double
		formatString: #,0.00
		lineageTag: 53e8ad9b-d488-4dfa-81ee-f87a295ebdaa
		summarizeBy: sum
		sourceColumn: OFF
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column DEF
		dataType: double
		formatString: #,0.00
		lineageTag: b823d797-ff3c-43e0-8d14-56d0a8378c92
		summarizeBy: sum
		sourceColumn: DEF
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column REB
		dataType: double
		formatString: #,0.00
		lineageTag: ab2b2a18-004f-4fe0-bbf8-c79382425e0a
		summarizeBy: sum
		sourceColumn: REB
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column ASST
		dataType: double
		formatString: #,0.00
		lineageTag: 07263f9f-ae43-4e78-a100-60519ed3e9cb
		summarizeBy: sum
		sourceColumn: ASST
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column STL
		dataType: double
		formatString: #,0.00
		lineageTag: ccaa80cb-d50a-4db9-9bfe-639ca6e1a09c
		summarizeBy: sum
		sourceColumn: STL
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column BLK
		dataType: double
		formatString: #,0.00
		lineageTag: 79f9f791-204a-414a-be48-6462e4f5cddc
		summarizeBy: sum
		sourceColumn: BLK
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column TO
		dataType: double
		formatString: #,0.00
		lineageTag: 72759c47-eb3a-4e6d-82c8-5327c3afce8b
		summarizeBy: sum
		sourceColumn: TO
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column PF
		dataType: double
		formatString: #,0.00
		lineageTag: 0e9dd567-c459-4367-bf49-955b4489dde8
		summarizeBy: sum
		sourceColumn: PF
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column PTS
		dataType: double
		formatString: #,0.00
		lineageTag: 381616a4-b54c-4c82-9ba0-412a81d12c27
		summarizeBy: sum
		sourceColumn: PTS
		description: Double column.

		annotation SummarizationSetBy = Automatic

	column 'Action (Player)'
		dataType: string
		lineageTag: fea8bb2a-255e-471c-89f2-cd18523fe856
		summarizeBy: none
		sourceColumn: 'Action (Player)'
		description: String column.
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1-4a3f3f79-db1e-4083-a2cb-b4b96d0428d0' = m
		mode: import
		source =
				let
				    // Source Excel: Data/Datasets/nba_players.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Data\Datasets\nba_players.xlsx"), null, true),
				
				            _nav = _src{[Item="Sheet1",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Player", "YR", "TM", "GP", "MIN", "FGM", "FGA", "FG%", "3PT%", "FT%", "OFF", "DEF", "REB", "ASST", "STL", "BLK", "TO", "PF", "PTS"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Player", type text},
				        {"YR", Int64.Type},
				        {"TM", type text},
				        {"GP", Int64.Type},
				        {"MIN", type number},
				        {"FGM", type number},
				        {"FGA", type number},
				        {"FG%", type number},
				        {"3PT%", type number},
				        {"FT%", type number},
				        {"OFF", type number},
				        {"DEF", type number},
				        {"REB", type number},
				        {"ASST", type number},
				        {"STL", type number},
				        {"BLK", type number},
				        {"TO", type number},
				        {"PF", type number},
				        {"PTS", type number}
				    }),
				    #"Added Action (Player)" = Table.AddColumn(#"Changed Types", "Action (Player)", each Text.From([#"Player"]), type text),
				    Result = #"Added Action (Player)"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 20 columns and 2 measures: Player, YR, TM, GP, MIN, FGM, FGA, FG%, ... (20 columns total).

