table Sheet1
	lineageTag: 191402fc-bab9-4d27-8726-c6a400cd4a85

	measure 'p. Rebounds' = SWITCH([Rebounds], 1, AVERAGE('Sheet1'[DEF]), 2, AVERAGE('Sheet1'[OFF]), 3, AVERAGE('Sheet1'[REB]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1e2fcfbe-a2ec-49e2-8068-2ca319bd82f0

	measure 'min(1)' = MINX('Sheet1', 1)
		displayFolder: Measures
		lineageTag: 23c90971-6f41-4a87-af83-5edf9c7aeb8e

	column Player
		dataType: string
		lineageTag: a9ffaf66-2e83-4702-a30a-1dec4ec8505a
		summarizeBy: none
		sourceColumn: Player

		annotation SummarizationSetBy = Automatic

	column YR
		dataType: int64
		lineageTag: ccbfd663-3763-41b6-9a4a-1b1cb00138d0
		summarizeBy: sum
		sourceColumn: YR

		annotation SummarizationSetBy = Automatic

	column TM
		dataType: string
		lineageTag: 4234fa0e-954d-485e-9c78-d556d057a118
		summarizeBy: none
		sourceColumn: TM

		annotation SummarizationSetBy = Automatic

	column GP
		dataType: int64
		lineageTag: 9198f49b-122f-498b-b4c7-ae2d483b27fd
		summarizeBy: sum
		sourceColumn: GP

		annotation SummarizationSetBy = Automatic

	column MIN
		dataType: double
		formatString: #,0.00
		lineageTag: 6e1004ec-d43d-46e2-966c-6b95d06354f6
		summarizeBy: sum
		sourceColumn: MIN

		annotation SummarizationSetBy = Automatic

	column FGM
		dataType: double
		formatString: #,0.00
		lineageTag: d258feae-e6ac-4de8-87d2-d936b6153ae2
		summarizeBy: sum
		sourceColumn: FGM

		annotation SummarizationSetBy = Automatic

	column FGA
		dataType: double
		formatString: #,0.00
		lineageTag: c4849d41-017b-4365-841d-975faa22919c
		summarizeBy: sum
		sourceColumn: FGA

		annotation SummarizationSetBy = Automatic

	column 'FG%'
		dataType: double
		formatString: #,0.00
		lineageTag: 01fd98bd-f25a-409f-bc66-4250d4bfb001
		summarizeBy: sum
		sourceColumn: 'FG%'

		annotation SummarizationSetBy = Automatic

	column '3PT%'
		dataType: double
		formatString: #,0.00
		lineageTag: 4bfd1ec4-da64-40a6-ba75-0c2febaeea8f
		summarizeBy: sum
		sourceColumn: '3PT%'

		annotation SummarizationSetBy = Automatic

	column 'FT%'
		dataType: double
		formatString: #,0.00
		lineageTag: 1111119f-e968-474e-b184-46da79b452c7
		summarizeBy: sum
		sourceColumn: 'FT%'

		annotation SummarizationSetBy = Automatic

	column OFF
		dataType: double
		formatString: #,0.00
		lineageTag: 06e3f2a4-fa97-40a3-bca3-46de29575c2b
		summarizeBy: sum
		sourceColumn: OFF

		annotation SummarizationSetBy = Automatic

	column DEF
		dataType: double
		formatString: #,0.00
		lineageTag: ba43ffbe-3b04-4a92-a641-911ba8f567c8
		summarizeBy: sum
		sourceColumn: DEF

		annotation SummarizationSetBy = Automatic

	column REB
		dataType: double
		formatString: #,0.00
		lineageTag: 34d0491d-96b2-444c-b6d9-50af8b8a9877
		summarizeBy: sum
		sourceColumn: REB

		annotation SummarizationSetBy = Automatic

	column ASST
		dataType: double
		formatString: #,0.00
		lineageTag: 73c554ca-9447-4176-8f6d-1005e32c553c
		summarizeBy: sum
		sourceColumn: ASST

		annotation SummarizationSetBy = Automatic

	column STL
		dataType: double
		formatString: #,0.00
		lineageTag: a9aba55b-a4e7-4ca1-947a-8c17b5bbfeb3
		summarizeBy: sum
		sourceColumn: STL

		annotation SummarizationSetBy = Automatic

	column BLK
		dataType: double
		formatString: #,0.00
		lineageTag: 5ece99b8-ac0b-497d-9e8f-f2cf0d98cfe0
		summarizeBy: sum
		sourceColumn: BLK

		annotation SummarizationSetBy = Automatic

	column TO
		dataType: double
		formatString: #,0.00
		lineageTag: 45d06371-023b-4afa-80ef-b00a06a2f175
		summarizeBy: sum
		sourceColumn: TO

		annotation SummarizationSetBy = Automatic

	column PF
		dataType: double
		formatString: #,0.00
		lineageTag: f0ac898f-459b-4b5d-8bfb-e885079738c3
		summarizeBy: sum
		sourceColumn: PF

		annotation SummarizationSetBy = Automatic

	column PTS
		dataType: double
		formatString: #,0.00
		lineageTag: 1ad0f313-1c45-46f5-8222-eaf914adb8b6
		summarizeBy: sum
		sourceColumn: PTS

		annotation SummarizationSetBy = Automatic

	column 'Action (Player)'
		dataType: string
		lineageTag: 094d79e7-1495-426d-90ef-f34d36fd30b0
		summarizeBy: none
		sourceColumn: 'Action (Player)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1-1a3e6eda-de87-4d34-891f-ea37cae82992' = m
		mode: import
		source =
				let
				    // Source Excel: Data/Datasets/nba_players.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Data\Datasets\nba_players.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Player", "YR", "TM", "GP", "MIN", "FGM", "FGA", "FG%", "3PT%", "FT%", "OFF", "DEF", "REB", "ASST", "STL", "BLK", "TO", "PF", "PTS"}, {}),
				    #"Sheet1 Sheet" = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Sheet1 Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Player", type text},
				        {"YR", Int64.Type},
				        {"TM", type text},
				        {"GP", Int64.Type},
				        {"MIN", type number},
				        {"FGM", type number},
				        {"FGA", type number},
				        {"FG%", type number},
				        {"3PT%", type number},
				        {"FT%", type number},
				        {"OFF", type number},
				        {"DEF", type number},
				        {"REB", type number},
				        {"ASST", type number},
				        {"STL", type number},
				        {"BLK", type number},
				        {"TO", type number},
				        {"PF", type number},
				        {"PTS", type number}
				    }),
				    #"Added Action (Player)" = Table.AddColumn(#"Changed Types", "Action (Player)", each Text.From([#"Player"]), type text),
				    Result = #"Added Action (Player)"
				in
				    Result

	annotation PBI_ResultType = Table

