table 'Base Salary'
	lineageTag: 8ed49e5e-4fa5-4765-836a-1c21ad1f60e1

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: 68c8278a-908b-47a7-a7a4-2788f75560e2

	column Value
		dataType: int64
		lineageTag: 83ac72e1-34b5-45e5-92af-0e413ee40be9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-c3202dc7-b688-48c7-8ac0-90cece74a3fa' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

