table Calendar
	lineageTag: 68a2c336-187d-417e-83df-627bd1e094d3

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 940c01d1-13a4-4a7f-9613-9ca024189135
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 24971b70-c99c-433d-896b-ea1dc9996ca0
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 31b0685e-bc90-4584-bb64-b308345d1f8e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 24bb203f-e0e3-48a8-8df4-2562342f8dad
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0798445e-7633-4748-878a-0cc4192e8e9d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 6276ad4f-f645-4029-9c17-aaeda3a0759f
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b1ac5ad9-0189-4047-8fa8-ac0e6ef33357
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 91779a2d-7bf5-4ee6-a255-cf541a0adf8a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 31372472-5138-4c69-b8d3-48d376dea755

		level Year
			ordinal: 0
			column: Year
			lineageTag: f8a76d59-6791-44d8-9ad0-73084169f5e0

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: efe56a78-1b81-471b-af9b-dec41f613a73

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 96b1ec20-7ca0-4efd-928f-c33e29a16e13

		level Day
			ordinal: 3
			column: Day
			lineageTag: 62e5766f-c40d-4ee8-875e-a9954892895b


	partition 'Calendar-9054d717-519c-4e6e-a743-d7fec9dcbe28' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

