table 'Business Unit'
	lineageTag: b9d2f3d8-f5b7-4477-83cf-863945a9e0c6

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 49cc15b0-3006-4ae9-8618-63559c90b3a1

	column Value
		dataType: string
		lineageTag: 2edafb45-b3b3-444e-86ba-f9f127bd6ed5
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-f9a521f4-62d8-4aeb-b35b-190b173fa8c2' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

