table 'Business Unit'
	lineageTag: f549e41e-8085-482f-aa98-c4346cc045ca

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 1eb74af8-8a21-4f21-8423-992cd5b4a945

	column Value
		dataType: string
		lineageTag: f28dcd58-cfb9-472b-93b2-02f6fee70247
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-dcde0433-2f9e-4b49-b3c5-724157540fac' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

