table 'Business Unit'
	lineageTag: c61378dc-3993-487e-b609-e832db9f43a3

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 0caa5e37-9673-4172-b27b-abe47d406f99

	column Value
		dataType: string
		lineageTag: ddb7cd15-30aa-43ab-8c8c-a1164c05bd27
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-5551c75e-15a4-4935-8441-1fb08a7f50d1' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

