table 'Business Unit'
	lineageTag: 7b9e04a4-eb98-4800-8f7b-0dad5943d221

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: fbb77768-c5cd-4c64-b19e-0125d5491049

	column Value
		dataType: string
		lineageTag: d2451faf-0906-4a31-b798-81415513ae23
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-e052a3fe-396b-4b50-bd29-ec7381d2b1c9' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

