table 'Business Unit'
	lineageTag: cfe1eb21-51bf-43db-83a6-14de896f4e78

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 6fd94f9c-e3fb-48a7-8f09-3f5b94c53401

	column Value
		dataType: string
		lineageTag: c1e713b3-af24-43bd-9ab4-5ae97daea3a8
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-3a4beb04-a9a5-4241-957a-6f0d053f4d44' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

