table 'Business Unit'
	lineageTag: dfd16100-56fe-4390-9a84-54a21e0033f4

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: c01a7812-543c-4511-a89e-fe58ab487471

	column Value
		dataType: string
		lineageTag: 49a953f5-9cc3-424f-b287-7d23370ce327
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-3fade116-666d-45e7-87bc-61ebdb1f5611' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table

