table Calendar
	lineageTag: a59caeca-f1f0-43af-8337-08deb9c3b344

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1ea24db8-f6dc-47e3-a338-4d951de1ee0e

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5b740a60-cc76-412f-8797-82d76e35fc8b

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: afe211e2-cf9c-4c07-8a82-65be2e01140e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 599a338f-b787-48b9-bf69-68ba6675f82e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: bd8c2b51-e994-4aa7-8908-5ab9b0b88481
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d202833a-77cb-4810-8f42-e992ed3c6ecf
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 768dfeb3-648a-4667-b627-6323240dc525
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 3e942cc2-e78b-489d-8e50-1dae01bb7316
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ecb8fad8-a254-490b-9330-8d2b8c26fd0b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 235b7928-b477-42cf-b9cc-0935f43886af
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 5034ea46-b615-419a-83ec-31aa6ef815ae
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f49fb656-1cc8-4527-8be3-7ddc85666e65

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7d792a4f-cd5a-470c-bdc7-f6abeb590d09

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 31d0c7b5-4ed2-4a4a-85a1-8969fb8e1a0e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 78c63c0a-4f56-4fc1-8f12-41458b4ddaba

		level Day
			ordinal: 3
			column: Day
			lineageTag: afdcb469-1e82-46eb-bbd4-9812901100bd


	partition 'Calendar-a8d9aafe-01dc-43b1-9898-cee460f68bdb' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

