table Calendar
	lineageTag: ebb93f31-39e1-404a-9d8e-f6abd7e2ea28

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ac76a369-cb92-4399-96f2-771e22906909

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: f38c564f-d4bc-4dbb-859c-b1fc0e7f9a1a

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 83a3f6f3-ae0d-4862-a0b9-01e2f0ff973e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3ea844b9-652a-48ef-bf42-5cb28d9880ca
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 903a842c-9d34-4147-af95-8b7372ad0070
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8c426011-4dba-4d83-a901-0b466e232ae6
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 17e39c4e-eac2-4d07-97bb-11e405bcb802
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: cb2279c4-b300-4f27-bdf9-3a5faf057c2c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e15a2920-6e8b-4c30-8738-db1a616143bf
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 6e67faf5-db2c-4fef-9867-3a2aad42c846
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f246ba42-5df5-4151-b4f5-a51af645de46
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e5ad9861-741c-4f1d-aaff-08a74d80c2ed

		level Year
			ordinal: 0
			column: Year
			lineageTag: 05253576-92cc-40ea-a35c-297186baca70

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 52a5afea-c7c0-4845-8bb8-10ec803c165c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7c1cf4f8-a115-4b1d-8906-63bf247e5b4f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 455693bf-a283-40ef-9621-9d59c6413272


	partition 'Calendar-95fbc272-a4ac-4d07-9836-96b741134d30' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

