table Calendar
	lineageTag: 2cc99f29-5941-4b98-9b01-483e40afe920

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 101fec6f-9643-4998-a42e-2b0d9881e20a

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c830b1db-b5a5-42b0-9e42-e7beedfad645

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 35be9692-55bf-48f2-8a51-1e7a9aad3b7f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 25d2542b-f470-4176-81f8-e0d103d02327
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 542c0bf4-c269-4567-93dc-fb3715d46d81
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5472060f-3e23-4d3d-a6a7-b8f7dd4f6565
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7f0e8dc0-a841-4bb1-8b9e-e38f81ff01a4
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ea421ca8-1e5e-4cc1-902b-65fea14402a4
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 25e22687-3857-4e58-9594-759435ba7841
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 63691a0b-80c2-49a2-9b4a-429450ecd612
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: aba3f7d9-c90a-4f2d-ba59-bf2989af1ac6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 19d5268d-340d-447f-88d8-6c064f4fc9ce

		level Year
			ordinal: 0
			column: Year
			lineageTag: 9304fc89-6b26-4671-8b36-162d0816e78c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 20be868a-85a5-4561-bc2d-9fb4ead0ef4f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6f9d4612-77ee-4f19-8358-263045a965d4

		level Day
			ordinal: 3
			column: Day
			lineageTag: 0810b242-46a0-48ec-9809-f8586036dfbd


	partition 'Calendar-b79ccb22-5b0e-4ace-a8be-d7c4aeccd7f9' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

