table Calendar
	lineageTag: e1314042-d6e0-4b1f-847a-853bf54c3066

	measure 'Year To Date' = TOTALYTD([Budget Variance], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: bb2dd7c9-996a-4f98-97e1-3e22fc07dd5f

	measure 'Previous Year' = CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b52ea9e3-d8d1-4f47-b201-b275eaeb9523

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ce0f08b3-f7d9-45fa-8129-a27c0734db45

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d35ab8f4-1d04-4633-af3b-9829bdcaaddd
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e1f14332-fcbe-450b-9fde-7579b9b67a69
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b3995e82-a993-428a-84dc-8c974b0c72a6
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5c6f3e95-10bc-4154-b31f-cb133abd700d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1026fdde-ea34-401f-a872-b3b6d2720c87
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a241f225-1a8b-4440-91b3-e0899aa585ae
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 7bfbf4a2-d0c4-4a25-a781-928c4af1f5dc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: af3feb64-efa9-42ea-be61-8cdf4276b11c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3510558e-3b83-46e6-b8e8-866abbf0f8d5

		level Year
			ordinal: 0
			column: Year
			lineageTag: e6dee1c7-c6ce-420f-bc72-bfdfcc01ecd2

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c0fb99a7-435d-4f6c-8fbc-45832f2de26a

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 18d109c0-d336-4f86-9054-079333240263

		level Day
			ordinal: 3
			column: Day
			lineageTag: 126b38c9-ecab-4358-b584-8f4fc178dd18


	partition 'Calendar-40854f7a-3e0e-437e-b1f7-2c5d3350aa4d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

