table 'Fiscal Year'
	lineageTag: 1815b952-cee8-4916-a137-64356b60789e

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: b443836d-4870-42de-bb53-9fbfac327dc4

	column Value
		dataType: int64
		lineageTag: b6e1d4ff-3e0f-43f5-91b4-8bd75fe99c75
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-6aa2ad0c-82d5-4002-83d5-1b81f4b177a0' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

