table 'Fiscal Year'
	lineageTag: 36d0e160-7d5b-4026-b055-edc0533f2d90

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: edc37ee2-e836-4a6c-a214-dd908cdb9aee

	column Value
		dataType: int64
		lineageTag: 4a0d48ad-3e9f-4573-82e7-fd696bfe0c72
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-8ccac226-93fe-4ffc-afae-3df99bec74b5' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

