table 'Fiscal Year'
	lineageTag: 7eaf7a2e-ad70-43ec-bb51-f664969a5b3d

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: d6c62d67-029b-4a78-810c-87e2000b75c2

	column Value
		dataType: int64
		lineageTag: 58995236-61bb-494e-82ab-229f0f1c3715
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-f06b523f-7616-46da-a76f-24597de70b4d' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

