table 'Fiscal Year'
	lineageTag: aa6771fd-526d-4ff4-8f47-9d0b0e19e06b

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: d2c6d3f5-3503-4064-8362-1fb12919b610

	column Value
		dataType: int64
		lineageTag: 941a6ce5-9f7e-4ada-9663-bda16eaa0406
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-869f801e-f97c-4148-be60-d30190e99cae' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

