table transactions
	lineageTag: d667ff75-0547-414b-8fa0-cd1e7eb7c89f

	measure Revenue = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8bb77eb3-e382-45c2-9298-d0355cb2ede1

	measure Expenses = SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 45ff7f14-b0ba-4f75-b5c3-de18c81db014

	measure 'Net Income' = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c22991f5-e751-4193-9f86-adc7e51653f0

	measure 'Profit Margin %' = ([Revenue] - [Expenses]) / [Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 07d356e0-f16f-45d5-965d-b10005f6d3ff

	measure 'YTD Revenue' = CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 97842c2d-30d3-4c1c-8baa-18e74460809f

	measure 'Budget Variance' = SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2ea35716-81da-47c8-a001-0c9245765079

	column transaction_id
		dataType: int64
		lineageTag: 078a2841-7361-4451-a9b8-cebfd9b94ebc
		summarizeBy: sum
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 57d7b011-b94d-4d9b-9208-b7b062be268a
		summarizeBy: none
		sourceColumn: transaction_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: 4199e46b-0ea0-4177-be95-456b6eab435c
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: b82dedbb-9611-4f2c-a9ef-f371da0e13b0
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0.00
		lineageTag: 09406738-6073-4c86-a355-70cf755cceaf
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: d33536d0-d4b2-4307-9a5e-afd409b55e14
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: 60d97645-5c57-44de-aeaf-2bafc5563bd7
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column cost_center
		dataType: string
		lineageTag: e3fae08a-628f-45b4-8716-b8817cb85ad3
		summarizeBy: none
		sourceColumn: cost_center

		annotation SummarizationSetBy = Automatic

	partition 'transactions-7368c988-ec0d-48ab-9c03-119df3967275' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = PostgreSQL.Database("db.company.com:5432", "finance"),
				    #"transactions Table" = Source{[Schema="public", Item="transactions"]}[Data],
				    Result = #"transactions Table"
				in
				    Result

	annotation PBI_ResultType = Table

