table transactions
	lineageTag: 8463257c-cbed-4946-86ab-b7458df83201

	measure Revenue = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7be67ce1-c1b0-4f4b-bc8d-78ad898ca6fb

	measure Expenses = SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e174490f-6b84-4f2b-9e79-57541df68f9b

	measure 'Net Income' = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c1c24849-bd44-4011-b677-ff4dab487e5d

	measure 'Profit Margin %' = ([Revenue] - [Expenses]) / [Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 04dd712c-ced4-48b5-8c73-b0afd2b48a76

	measure 'YTD Revenue' = CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 61b59c5c-9917-4319-856c-1f9d74cfd39f

	measure 'Budget Variance' = SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f396a047-0591-4f17-8025-6361de8c3ba0

	column transaction_id
		dataType: int64
		lineageTag: 7fcc5451-2350-42c8-80aa-46bacdece794
		summarizeBy: sum
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6f1f223d-5daf-4ec8-9a87-4362def740db
		summarizeBy: none
		sourceColumn: transaction_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: de487c98-95b2-4bbd-986e-bf85f80129e0
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 34b6bd01-5b5d-425a-974e-e54c599352e1
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0.00
		lineageTag: 64452f21-f9f6-4fda-a592-638ba7a5d970
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 56c2bc72-a0da-4062-a65a-722035d5cd4b
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: c504a157-eed8-43b9-b9a5-457864f3c1ac
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column cost_center
		dataType: string
		lineageTag: 8af372f2-07e0-45e0-9e58-c769db6e8cbb
		summarizeBy: none
		sourceColumn: cost_center

		annotation SummarizationSetBy = Automatic

	partition 'transactions-213f16e7-88d6-42ba-a1b7-62f8776eb30f' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = PostgreSQL.Database("db.company.com:5432", "finance"),
				    #"transactions Table" = Source{[Schema="public", Item="transactions"]}[Data],
				    Result = #"transactions Table"
				in
				    Result

	annotation PBI_ResultType = Table

