table transactions
	lineageTag: 1bafa5b0-dbff-4bdd-a372-da64115e2f2a

	measure Revenue = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 091fbf8a-8d75-4f40-a6c3-c8da30a5ff52

	measure Expenses = SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b8bb959a-0387-4e34-8c15-f5a0d5552a4a

	measure 'Net Income' = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3fd57da0-dbec-4de0-ba39-b9b403a3c0fd

	measure 'Profit Margin %' = ([Revenue] - [Expenses]) / [Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c012df7b-6aa3-41ae-b048-29b3912a0998

	measure 'YTD Revenue' = CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a84dcbc5-7d7f-41fa-9fe1-21670a707424

	measure 'Budget Variance' = SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8238ad34-832c-4b2f-928e-9c7f667759f7

	column transaction_id
		dataType: int64
		lineageTag: 0ff81a77-5ef7-40a4-b89f-b7136afcffc8
		summarizeBy: sum
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f4f2182e-b22d-452a-87e0-563dd79ca80d
		summarizeBy: none
		sourceColumn: transaction_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: 64d47c6a-783a-417e-b264-f38aae94baf9
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: a8435386-6aa1-4b0e-9918-9ee2d0837dfa
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0.00
		lineageTag: 9dfa5da3-07e9-4b27-a8dd-8eb37b95386d
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 3ffe1d5f-07d9-4f25-8e27-f9abe8f1bfa3
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: ea9eea22-7ed5-4046-ac56-cbf6cc5d0a58
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column cost_center
		dataType: string
		lineageTag: 001af7e9-5458-4084-8af1-8f4ef11037db
		summarizeBy: none
		sourceColumn: cost_center

		annotation SummarizationSetBy = Automatic

	partition 'transactions-14739106-2457-4434-a03e-1db4952731f8' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = PostgreSQL.Database("db.company.com:5432", "finance"),
				    #"transactions Table" = Source{[Schema="public", Item="transactions"]}[Data],
				    Result = #"transactions Table"
				in
				    Result

	annotation PBI_ResultType = Table

