table transactions
	lineageTag: d79c4176-2f36-41b7-91d3-8d495f7da540

	measure Revenue = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 4312cd48-b75f-4fdb-bee9-8182c62b61bb

	measure Expenses = SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: de6212a3-24e7-4d4b-a193-b708ccfc3ae7

	measure 'Net Income' = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 708ba506-011b-4f5e-8f89-0f446e1f59fd

	measure 'Profit Margin %' = ([Revenue] - [Expenses]) / [Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: bc84543c-1869-4f64-aec9-75af1cdb81f1

	measure 'YTD Revenue' = CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: cfb178cf-04f2-40c5-a11e-fe91cf454c6a

	measure 'Budget Variance' = SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3143bbb3-1e45-4f90-9054-dea5af8ecb68

	column transaction_id
		dataType: int64
		lineageTag: 22973c71-61aa-470f-b6ca-25dbcc2fa4e0
		summarizeBy: sum
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a14cf00f-bdb0-4b23-904d-9df80bcbeceb
		summarizeBy: none
		sourceColumn: transaction_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: f502911b-3991-43ad-a864-3b78c935bb6d
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 43ed3987-b80b-4890-b9b1-29fc49bd9d92
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0.00
		lineageTag: 15ae6f18-96d5-40b5-a38c-558f149d7828
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: e38d2391-5da1-40ca-87ca-bb409885b7fd
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: eb068119-772c-4209-8df9-96c1c8811101
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column cost_center
		dataType: string
		lineageTag: 14560528-791a-42ec-8cbc-f46421780bfe
		summarizeBy: none
		sourceColumn: cost_center

		annotation SummarizationSetBy = Automatic

	partition 'transactions-1727a3cd-1e2d-463e-9329-2ce5b9e9bd37' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = PostgreSQL.Database("db.company.com:5432", "finance"),
				    #"transactions Table" = Source{[Schema="public", Item="transactions"]}[Data],
				    Result = #"transactions Table"
				in
				    Result

	annotation PBI_ResultType = Table

