table xy
	lineageTag: 66e22965-6b50-41bd-ac26-1f981a64028c

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: b9d7ec53-2dda-41c0-ad83-05003f45724f

	column a
		dataType: string
		lineageTag: a91c1c0a-1069-4a82-9201-2758fa5a6052
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 9462ab9d-4b48-4709-819c-1daee1738491
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 94633207-86b6-406e-a7af-107436c146ee
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-5badda8f-ef27-497d-b7d0-b7256aa1643d' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: Unknown
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"a", "x", "y"},
				            {
				                {"Sample 1", 2, 3},
				                {"Sample 2", 3, 4}
				            }
				        )
				    otherwise
				        #table({"a", "x", "y"}, {})  // Empty table on error,
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

