table xy
	lineageTag: b5d67352-64d6-4593-948d-71b4e8d4ab10

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 706b46f9-4953-49b7-ada6-1de054667f58

	column a
		dataType: string
		lineageTag: 1c03e2e9-e620-4450-9c57-517611ba7fc3
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 690229f1-fc2d-45e2-98be-0096af439e99
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 86cd4b45-bc77-47f6-823d-4f561f29332f
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-3de76626-b680-48b3-952b-258fb752fadc' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: Unknown
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"a", "x", "y"},
				            {
				                {"Sample 1", 2, 3},
				                {"Sample 2", 3, 4}
				            }
				        )
				    otherwise
				        #table({"a", "x", "y"}, {})  // Empty table on error,
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

