table xy
	lineageTag: a2b5b24c-9f9e-422b-a8db-fe01916b9c0e

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: b2584897-4267-4a3e-b4c8-7a1d7e9036ff

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: 62e8eef1-93d9-4ae6-9ca7-38b14ea99bfe

	column a
		dataType: string
		lineageTag: 773b66ea-82f0-4a36-9017-89d9d9aa38db
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: b6c6d5c6-b0f5-46a9-9464-caf279c0b978
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 80232470-bf71-47a1-ac07-0975a4caa3ee
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-8f91095c-871c-4c3e-a86f-585257d5bbc7' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: Unknown
				    // Replace the sample table below with the actual source expression.
				    Source = try
				
				        try
				        #table(
				            {"a", "x", "y"},
				            {
				                {"Sample 1", 2, 3},
				                {"Sample 2", 3, 4}
				            }
				        )
				    otherwise
				        #table({"a", "x", "y"}, {})
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

