table Calendar
	lineageTag: 1b2e6663-bf9a-40d3-91c0-831acc440184

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 99bfe98d-7788-42b0-aad4-e4c7a9fdde01

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c33b3c32-b305-445c-a981-0d120c72060f

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ba5bbe6f-7546-4fbe-bd64-d4a9d7cf984a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 977fe788-9c25-4c6f-bb24-0e38f8c52dd1
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 94e519a5-72cf-4ad8-a842-b958634bebfe
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b0315ef0-a830-47e8-ba38-182030901b7a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: bba33c4a-b7be-4255-b4af-93a4f7cc0010
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 6b9b2483-f256-46d7-bfee-4250b21cf05d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: bdf879a6-8832-426e-bf23-eb466d64db81
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 82cd4bb2-a2d6-40e2-847a-99e0fa523ff4
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c94cbadc-2423-491d-aa5a-e520ee428143
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: edd65f2f-3239-4ad1-bd7c-4deebb12bcda

		level Year
			ordinal: 0
			column: Year
			lineageTag: 5a2b3b53-d9c9-4178-afbd-ab3cb1429d62

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f94c898b-a91b-466c-a9e2-6a909ccedb1c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 85acb211-4523-45ac-a3a7-56dcb160c95c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 24d91b9f-0393-49ad-aefc-8a5df66d10e7


	partition 'Calendar-9f11f821-d04d-421b-a7f7-78c453695bab' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

