table Maintenance
	lineageTag: 1a4e921b-7e1b-4028-a722-13fddab1319f

	column maint_id
		dataType: int64
		lineageTag: f5564c2a-f9a7-46b8-9712-c31f5643126f
		summarizeBy: sum
		sourceColumn: maint_id

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 30f135c6-663d-4f11-9564-d826a2dccb0d
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1f3bfbd9-931d-4e7d-a11d-af303ff8deeb
		summarizeBy: none
		sourceColumn: maint_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: 1413e635-2637-44e5-8024-589519f0cb45
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 762208b7-ef3c-4a7a-a97d-75f8a81f0581
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: bafebbe4-5020-4352-9a22-7f18706eeb81
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: 7c7b7f25-df15-4bc8-998b-d3f613ab8114
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 690900fe-7272-4a78-8710-ce89025e04ca
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-bc59d680-98d9-4a5c-ac62-de413c10adc4' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Maintenance Table" = Source{[Schema="DBO", Item="Maintenance"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Maintenance Table", {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

