table Sensors
	lineageTag: 7ddda9b4-6ce7-4969-aa70-df79ed3cbdd8

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 356cd8c0-ef13-42e9-932f-79cc9d9b5293

	measure 'P95 Value' = PERCENTILE.INC('Sensors'[value], 0.95)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e8478c07-d4a4-47ba-9a4a-5549b2b54cc2

	measure 'Value Variance' = VAR.S('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 38e80414-896b-4343-9a7f-27de3c022b89

	measure 'Value Variance Pop' = VAR.P('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 922c6f16-e903-465e-a681-54f123c35b1d

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ee271ae3-8896-4172-8eb6-7113c8a24765

	measure 'Running Avg Value' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d1a4dd1f-2991-45c1-8103-47e439e539f4

	measure 'Running Count' = CALCULATE(COUNT('Sensors'[reading_id]))
		displayFolder: Measures
		lineageTag: 1230c723-8373-4666-90d2-d3b6628d54b4

	measure 'Running Max Value' = CALCULATE(MAX('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9911471a-1896-4802-a47d-d3499002ae94

	measure 'Running Min Value' = CALCULATE(MIN('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 268d5adb-b65a-4ff3-a543-8cde1e41b9c4

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: 8b3da307-45d3-4a2d-9bb1-32caf1ff9563

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		lineageTag: eb96530d-bf43-4f19-8842-258454594664

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 47b95276-8d7e-47b1-823d-61a3415626fa

	measure 'Time Granularity' = "Hour"
		lineageTag: dde0232a-2513-44cc-9ace-89eee4cc1989

	column reading_id
		dataType: int64
		lineageTag: bd1770a2-04e1-42c4-9305-1af9d05f1417
		summarizeBy: sum
		sourceColumn: reading_id

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: a0929c35-0854-44bc-9a88-d4c849a67dc2
		summarizeBy: none
		sourceColumn: reading_time
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 4c92e7c3-dbe0-40a3-9fbc-d92334f14a04
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: 9899040c-a76d-406c-b420-c98bde837eec
		summarizeBy: none
		sourceColumn: sensor_type

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 600b0f37-69b7-4385-aa2f-cb584dc9cd81
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: a058baf5-713b-467e-ab04-67f6444d2409
		summarizeBy: sum
		sourceColumn: threshold_min

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: 5e39d114-6fd6-4f5b-81c9-290e5482764a
		summarizeBy: sum
		sourceColumn: threshold_max

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 813e03c6-e19c-421b-8a25-8d0350094271
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: 41cbfc1b-6972-4937-a03c-d7dcddde1225
		summarizeBy: sum
		sourceColumn: quality_score

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: af453aa0-576a-4c6b-9df4-88438e09f793
		summarizeBy: none
		sourceColumn: plant_id

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: ba6b116f-0508-4d4a-9763-00d73200267f
		summarizeBy: sum
		sourceColumn: delta_value

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: 7d49b177-f7ca-4973-956a-f2724944c87f
		summarizeBy: sum
		sourceColumn: angle_degrees

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: 4a041ab5-a62c-4d1f-b442-f463ad2d7c90
		summarizeBy: sum
		sourceColumn: power_watts

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation'
		dataType: double
		formatString: #,0.00
		lineageTag: 542de220-e5ac-428e-9e8f-a4c19e2bbffe
		summarizeBy: none
		sourceColumn: 'Abs Deviation'

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: f75b3a1a-6834-4efe-b5fe-c5194509e426
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Floor Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 831afc8b-5788-4a21-b33a-b1911a33c035
		summarizeBy: none
		sourceColumn: 'Floor Value'

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 5e630653-e8a9-41ba-a4a8-0c72454a133c
		summarizeBy: none
		sourceColumn: 'Rounded Value'

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: 74cfa967-117c-476d-b57e-e28a1e88d9be
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: e7d37cf0-ea6d-42b5-b2ab-d9763bc8895e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: e2b0f49b-dd01-4411-9077-8777288ae71b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 83f28906-935b-4cf3-9100-fd987fe64e67
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: 45972d72-3db7-4109-a63b-8fefb3626408
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Month' = DATE(YEAR('Sensors'[reading_time]), MONTH('Sensors'[reading_time]), 1)
		dataType: dateTime
		lineageTag: 14c1af14-b666-4e7c-ac5f-2419f325b24a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		lineageTag: f768d1c0-0315-45d8-ba78-26e1162f21d9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: 1a809e27-dccf-40f2-855f-ca9416d104fb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: 4acaf962-40c6-4048-9c21-c43c362ede0e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-66cefcb7-6893-4ed3-97c3-f7da79285da4' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Sensors Table" = Source{[Schema="DBO", Item="Sensors"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Sensors Table", {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    #"Added Abs Deviation" = Table.AddColumn(#"Renamed Columns", "Abs Deviation", each Number.Abs([value] - ([threshold_min] + [threshold_max]) / 2), type number),
				    #"Added Floor Value" = Table.AddColumn(#"Added Abs Deviation", "Floor Value", each Number.RoundDown([value] / 1) * 1, type number),
				    #"Added Rounded Value" = Table.AddColumn(#"Added Floor Value", "Rounded Value", each Number.Round([value], 2), type number),
				    Result = #"Added Rounded Value"
				in
				    Result

	annotation PBI_ResultType = Table

