table Calendar
	lineageTag: 84b66de7-651c-4d3e-ad1d-29cfa49d3a57

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 344a7af5-4718-4e2f-ae3b-af814e5d8ad1

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c1dc52ac-86e5-4ab1-bcfd-3a8e602c0c82

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 8416ce38-a359-4e8f-86b1-3b26a4ed0ea8

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 11b855ee-2aaa-45fd-98d9-5cfa2c2f8c6f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0123bd72-efad-482b-aa44-374ea2e5ca29
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e0919487-bc18-4702-8ac4-5bd7b03308e7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ea2fb8a2-1f60-42c3-95a6-b23056551d92
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8dcd3741-0e9a-40a3-8f19-65ccea55cd5d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1b28d7b8-9d0e-4cf1-aa97-7ea934416b3e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 0aff8c76-0dde-43b7-a83a-5f710a44d876
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 4e77e8b7-cb6e-4732-9d07-9d8593f37b1f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 21f50dc9-ce69-4fea-8edd-77cc81f5920d

		level Year
			ordinal: 0
			column: Year
			lineageTag: 098ada39-b2e1-4aaa-9ced-a90f2a560b4b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 91b5f603-dfd0-4814-a6b1-5f886dec604e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 560c588f-512b-477c-bfd5-208e404deb3e

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6fe34551-e354-4e53-960c-ee20e5f12183


	partition 'Calendar-b1f82c0d-42ee-4a9b-b730-58f71aed6e14' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

