table Calendar
	lineageTag: 3ab7a2f4-e895-40ae-bc49-4505cb23b5c9

	measure 'Year To Date' = TOTALYTD([Margin], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6b1722c2-8e29-4457-8bc7-d3bcb4951587

	measure 'Previous Year' = CALCULATE([Margin], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 895e9473-1baf-4564-858c-291e6e0e4ad7

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 1d5b4c88-6514-4ff2-a84b-5473b3157692

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1bbd667e-a735-4134-914b-6539afb66610
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ace825e4-ecbd-472b-9d38-0b55811cbc85
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: aeef1a68-749d-419d-b781-77742e897ef2
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f08ec4ad-2198-4924-9c56-9cbe108be1e9
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8209fa1b-2d64-48f0-b265-2fbf694d1bf3
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 6465446e-f369-47f3-ae52-785ae1706f7e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 5a5dde85-21e4-46d6-a73b-ce707c66c3ae
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 4fefa5e5-fc2f-4892-86e7-531938eb8df0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 01b4a932-f939-41bc-9f56-18bc585c6060

		level Year
			ordinal: 0
			column: Year
			lineageTag: d24dd603-1f82-4152-b69e-da497fe21d30

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b6c26f5d-3eb3-4868-aa01-fa3ec44afdb5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9c61727f-9135-4a26-966b-440cac11cad9

		level Day
			ordinal: 3
			column: Day
			lineageTag: 43fd6234-e1f2-4fb0-9bc2-3a59b8a0120b


	partition 'Calendar-4f4099e1-621d-4533-8599-60c314c8f789' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

