table Calendar
	lineageTag: b7f486d0-2a43-4253-882a-b0431861b34a

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d1145b10-6914-45b9-989e-771ee5c12d2d

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: a920f8b7-26cb-458b-b247-864ebdfc0db8

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 639862d0-2b91-4da9-98a1-35f422f8f776

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6c72f339-92c8-41f9-b0fa-4f55db4abc41
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 3cc261c4-08c4-40ff-9a7a-7130decaabf3
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 06a2277e-f993-4c35-8cdb-99ecfe48eecd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4ab8e150-ec9e-4166-9627-72b6b97db7f2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: fdc0ecff-f96e-4e17-956f-4c0de2c9f57b
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 76215e38-9e1d-4562-b526-8323552c48a4
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 08ed4a04-31b0-46fd-b1f8-acfd3fb1172f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b8b5e5c5-4239-4ab9-8274-ffe63cce944b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: d9133ed0-dda3-4f11-80b4-030ec8e96f77

		level Year
			ordinal: 0
			column: Year
			lineageTag: d78beae9-1248-4dfe-8950-31fd289cd71d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b9526cb2-a9fd-41f8-9586-99c4af8d7c2a

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: b8cb5bd7-baf2-4394-9f39-9127615bdeee

		level Day
			ordinal: 3
			column: Day
			lineageTag: 68a95064-e5ed-46e3-9f24-9bb2bc3c29f0


	partition 'Calendar-70d41d4e-55f8-405f-81d8-04a192bd5084' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

