table Calendar
	lineageTag: f203a4bf-edeb-453f-b57e-aed5b4b383f5

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 8dea5fd1-34cf-4833-a9e0-ae83fb901b10

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ddee6eff-f4bb-4927-97a8-fb005bf19b6a

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 517d6c12-6f49-462b-a201-5e32032f78d7

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 65ec2d5e-b1ed-4f16-99ec-5be2a7a9ae58
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a70e8445-0b31-4250-8b62-7561ac0bb703
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1cab4881-5f31-45ad-8bfa-f8e8f00dbb15
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 93ad4ed1-b3dc-48ac-9a01-5e1f60998f40
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 88a732db-836b-43d3-84a0-0359cfa97eb8
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 96f24241-a625-4782-993a-01ba43842d31
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c06ed9c8-c775-4ab7-b2ee-546edd1a738c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b20f9013-3187-4f38-a41e-5c27ff422dcb
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c970051c-263e-41aa-b5ee-61cb3a18ee7e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 931aefe9-8994-4b77-829f-7c0a16e7f460

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 2a452740-4da4-4d13-969f-149b19258f49

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ca1aa9a6-e49b-475f-8720-84cdd22b9e24

		level Day
			ordinal: 3
			column: Day
			lineageTag: 33c1a5de-b5ef-4d27-9882-6bf2e5ef404d


	partition 'Calendar-b3a48893-a4b5-4b01-a50d-ea6b05af9194' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

