table Calendar
	lineageTag: 83a5240e-7a7f-4886-a122-cc0ea7d6aacb

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 7514397f-133b-4882-a573-cae071140835

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9d974a10-4579-44dc-96da-81cf02d4dcc3

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 28c250c9-ed77-4275-b843-8cd198895f4d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f96859d8-7249-44b6-abf7-ca1aa92aa309
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a4be3d20-0149-44df-a145-49b00bfba2cb
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 63cb499c-dd54-4d7c-9b6f-3381a0507eab
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c679a7ef-1669-46d9-826f-a025454640b5
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 58852abf-8e9c-4e82-aff7-fc5f340d0ce8
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7e35fc39-045c-4341-a855-a560c94593f7
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a042cf50-2872-416f-97e6-410578862c07
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f88b7895-5020-4498-822f-25099e849ef2
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 819507ef-d0d1-49e4-9110-3fdfc52b42ae

		level Year
			ordinal: 0
			column: Year
			lineageTag: 60ec6192-5256-4dc0-bc5c-f0e9f285225a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: c85d6878-0f66-44dd-9918-f9d39fac345a

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 25e5f1ec-3d0c-4f70-9225-ed68384f8cc1

		level Day
			ordinal: 3
			column: Day
			lineageTag: 15648a3d-1ae4-45d8-85a4-44c7c21bde6e


	partition 'Calendar-7f75c7ab-254d-4901-ae24-e0d560268ea8' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

