table Calendar
	lineageTag: 5f52c983-c795-4be3-80a3-aa4a5b1e5c57

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: dbd72e0c-eb0e-4db7-a608-eb4035493054

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 0896927f-d3e0-416d-aa3d-840790f08fb8

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ff7d42f7-dbef-43a4-a9ca-5c268b79468a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9cc307a5-d74d-4c7b-b923-f5003180a226
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d6a15804-ce01-45f0-87c8-2cd872832f0b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f9b513a7-57f4-414d-a6ee-412b53776d45
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 965c2a47-914b-4af0-bfa0-d63e4925b8c2
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8b5ccda4-6347-46e7-8036-1199b59b014b
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 9dadcecf-4516-4d06-adef-7d4c1679c5a1
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 29f549c0-dc50-4325-b9b3-98fec821d3e8
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 98364071-1b76-422a-aafa-e0efe571fd23
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 0b9dc2a5-9c7a-4224-917a-5496f8cdca80

		level Year
			ordinal: 0
			column: Year
			lineageTag: 86005860-e122-4ae1-b506-393d207c72b8

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 93cdc618-daf7-4455-9231-85dcb291948c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 48dceedd-a139-4358-9e67-3d9a44739617

		level Day
			ordinal: 3
			column: Day
			lineageTag: bb2fe40e-53db-4e0a-a18b-38611d8c63a3


	partition 'Calendar-74e4a2c7-8798-4a77-9e51-bc4804d510d6' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

