table Calendar
	lineageTag: f0b7aebd-93ae-4ccd-a3db-71273b7f20de

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 75f4c4e1-c7a4-4789-9516-bfab256f4426

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ba082a7c-3ce0-4f8e-8df6-320a97664cba

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ffb00974-40d4-4a7e-aa0e-849ab99df985

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f5c94b2f-6b81-44f1-94da-900a3d95711d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d555c7de-43bd-43b9-9948-b06ee373a84f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 6696e25f-0512-42bf-9afb-09e27876ef40
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 8f19a06e-9f33-4ea6-94e4-7a0393341b04
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ee605dd8-b53a-4bc8-9d1d-7231b4a6eb62
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 85d3e409-46ed-459d-aa28-0c00f4b19426
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a05536ce-a4fe-480d-8941-ddd5fbe690bb
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 3070a413-3bc6-4be3-8fb4-415a770a9c99
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1dce5170-6189-4b72-82c9-0cdbb3d22ae5

		level Year
			ordinal: 0
			column: Year
			lineageTag: 80c2aff9-3823-4d69-b43a-66daca1a7657

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 4041a6e6-9c51-45ff-b048-36ba8f533dc9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6596f12c-8a76-49af-affc-3b3c0c7ef0a5

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9bacd3bc-ec07-4f0f-b6c6-0c4d9437f967


	partition 'Calendar-dac4ab02-172f-4e06-9f04-859423e6e5ea' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

