table Calendar
	lineageTag: 38a97330-cedf-4b0e-ba4c-9b416de15766

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ce541c0f-833e-40ca-8d3d-00fca7750fd9

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 6a4d8727-72de-40da-ba44-0806b152a724

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 24dea835-fb9f-49a9-8969-62d8b5084c7d

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6250bc0a-8ef1-4fc9-8293-9648ed4716af
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a255647f-ecb1-4b91-ab35-9be9d1dc20cb
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 493fb390-2a19-4801-bb5d-6a55e30c6686
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7d63c6c7-e297-4c46-9dcf-b34360d7b9f1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 13d51e3d-b466-4675-b9a4-e160f906f098
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f1054642-aeb2-41a6-ae83-c6b112026533
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a139ff75-f00b-4ce4-a13b-e6c91ae75648
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: baf5ec0b-5d00-45f4-8226-54a67608ac36
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: dc5567fd-72d6-4ad2-a370-664345bf884c

		level Year
			ordinal: 0
			column: Year
			lineageTag: 6ccc1f22-0cda-4dab-a254-125cd9443181

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 51e46e8c-2bf6-4a99-b8f0-4d295ff78c4e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4ef8af53-bcce-489e-9299-8e0ff615a060

		level Day
			ordinal: 3
			column: Day
			lineageTag: 992fba55-ff6f-406c-a830-dfa325ab7b62


	partition 'Calendar-9d2283e2-fdf7-4c32-a9f3-223d6b04e214' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

