table Calendar
	lineageTag: ea904d87-5f96-442b-8d91-09277ff1de46

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 33789281-6816-4d62-9f17-64fc344bb5df

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9a178dfe-09eb-4149-8b13-78b1453ad453

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 878d9208-6f81-4950-93f5-7ef9fe49b56f

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0536090e-a1d9-441a-a159-fd2fc6cb2ccb
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5a2de3ae-d2b1-4209-8b9e-5e26b4c5087b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 3d12316e-72db-472f-9556-c19752c7e5f2
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: bd6a2912-623a-4b04-b240-46c9ac1412cf
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 58314cd7-14b5-4d84-b7b9-491a811e7e9a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: dfaf6a20-49b0-4f89-9081-490f4dffafa1
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4af9aee4-91ce-45df-9b2c-a002bc01f63d
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f3612d38-318c-464a-8169-dda0a43ca0be
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 56c38ed8-a6b6-4e87-8e07-2bd469986fb8

		level Year
			ordinal: 0
			column: Year
			lineageTag: d3b26fa9-d84b-4c56-ae63-7b2f0d663222

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 89f56c25-f361-46dc-bf5d-9f169a529a6a

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ef99e125-5eb1-4081-943e-9a46a134f234

		level Day
			ordinal: 3
			column: Day
			lineageTag: 849fd0de-d99b-4e7d-9636-bbcbbd75798d


	partition 'Calendar-76cdf70c-b841-4195-a682-743316227b7a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

