table Calendar
	lineageTag: ebba018c-a030-4019-847a-9bdccbd5f219

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: a0f1e049-73e8-47d4-8941-88188820a44a

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b92e5084-8539-416c-a732-3a410dee0ba9

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: cda8ef13-c33b-4467-9334-0c3bdd1315c0

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d45b43e6-7f53-4465-8e3f-ddd7ab204d65
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 8f18cc87-83b8-4097-9fc8-0fbc65590f93
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 001c41ec-03dc-46ed-a551-4647803e2c89
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c56fb828-d622-4a9a-bfe4-ae408e48a72c
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 920e1dac-f2c8-49f0-8557-ee6c7fdc05c1
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 686151dd-902a-4279-8b10-f1598b97fa34
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f8ebfb7c-82a0-4a10-ab61-91699c38d29f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: cb9b511f-bb0c-4a4a-8879-0cdb068c6bab
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: bdf5466a-8f73-4234-a1ad-c0c9dbdc59df

		level Year
			ordinal: 0
			column: Year
			lineageTag: cf3a0e58-1b60-4f0b-8f56-93a2f1368b19

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 60dad135-d8cf-404a-b7ab-dfbc70abafbd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c0d723da-951b-4022-9e36-4c3da7e97f15

		level Day
			ordinal: 3
			column: Day
			lineageTag: 2baa03e3-d9b8-4ee9-a71f-40781f03806c


	partition 'Calendar-91456a72-00f0-414e-8c68-8933ffab3cdc' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

