table Calendar
	lineageTag: 1330df9d-ed02-49ff-8885-2536e1a5d72f

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5247c38b-1c78-48f1-83d0-b1aa6a3d1219

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: ef2412c7-4d7c-439e-8ab9-9510dc5517c9

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ac63dd36-d489-4452-a215-ee7395c8a17c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3a8a0a54-69c2-4e26-bfc4-7b9e99ea2f7f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c40d6ffc-de0f-4b7b-8900-b0ccd10cbcec
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 75c3a6e9-e368-4e2d-b96e-c564db2a3f70
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 9f326be9-6785-43ee-ad88-7b15be503e84
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e79b07bb-a46b-4960-b3d5-106492b6bfdd
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 80f0365b-5af6-4469-9e11-a91b64910bdb
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d2062a0c-cea7-4f70-9318-c91ea6f8e725
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: df83a5c0-5412-427d-af34-2f7189eb48a2
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 65e14ab8-c14b-4861-b261-a97fb5827d6e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 38beb877-e381-47a7-a034-6c98ad52d3ae

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 43f4694a-8e2c-4291-96a6-83a54098cd1b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: d7ab7863-78fe-40ff-a752-f9bfb7a4020d

		level Day
			ordinal: 3
			column: Day
			lineageTag: 159b90e9-c19e-4c50-9da1-ccef98af0e37


	partition 'Calendar-da55a334-007b-4a20-a949-840bc66938b7' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

