table Orders
	lineageTag: a61ee3e1-db43-4a5a-ba52-c9173ad4c6d9

	measure 'Profit Ratio' = SUM('Orders'[Profit])/SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: da0d6fce-39bb-4d69-9fb1-6d130198c9dc

	column 'Row ID'
		dataType: int64
		lineageTag: e3456e1b-0441-4d4d-8a14-ac0920e79ae9
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: e308feab-7b7f-4295-87f8-a168d7dc8bd0
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b88ba9c8-0682-4b90-9e0e-109c6b3e6222
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 20d01fdc-3980-44a1-8255-f25c8baddd40
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: b0333fda-0f50-4e08-a7e1-2695d6f1629b
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: ae856844-af1e-4289-9869-8db52c25dcf9
		summarizeBy: none
		sourceColumn: 'Customer ID'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: ee455cb6-2c98-49b0-84a6-f67f206b289b
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: cd92b744-1095-44a4-a504-97e4d3eafb00
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: 7e6e14a1-1de0-48f8-9fd8-2617006a26e2
		summarizeBy: none
		sourceColumn: 'Country/Region'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e5a8ad7d-be6f-4b30-af36-976cf1de616a
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 3067d4d1-30c4-4adb-a285-a719ef3ad066
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: 5f20ccba-1cb9-444a-83d0-46ab9d2929b4
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a6c21ae8-c703-44a4-a271-9e1b4910e47d
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: d23494b3-add8-4329-b710-5b47ffb669f6
		summarizeBy: none
		sourceColumn: 'Product ID'

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 45ad7ab2-a987-4b70-98ee-95706a887794
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 0de4c861-9e71-445f-b908-7c145c41732c
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 89505d3e-4e84-4e0c-a438-d6937c086057
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 253d7a7d-e46b-43c7-a24f-5af047409f27
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: cb85bb12-b473-43a7-8d34-73244221800c
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: da2045f3-b27d-46d3-9d9a-6cc6708979e3
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: acfbd65d-6eec-4770-a642-377faebde61f
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Profit (bin)'
		dataType: int64
		lineageTag: abfa7237-6779-4055-9d86-0e5c9379ba62
		summarizeBy: none
		sourceColumn: 'Profit (bin)'

		annotation SummarizationSetBy = Automatic

	column 'Top Customers by Profit'
		dataType: string
		lineageTag: 0f0384b4-1314-474f-8708-8b3936e0d90a
		summarizeBy: none
		sourceColumn: 'Top Customers by Profit'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: double
		lineageTag: 9aa27fad-295d-4d79-bce5-0c89daa52eb7
		summarizeBy: none
		sourceColumn: Manufacturer
		displayFolder: Bins

		annotation SummarizationSetBy = Automatic

	partition 'Orders-9a14a9d4-d884-4c89-b9b4-79a05eaee9da' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true)
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country/Region", "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"}, {}),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country/Region", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    #"Added Profit (bin)" = Table.AddColumn(#"Changed Types", "Profit (bin)", each [Profit], Int64.Type),
				    #"Added Top Customers by Profit" = Table.AddColumn(#"Added Profit (bin)", "Top Customers by Profit", each "", type text),
				    #"Added Manufacturer" = Table.AddColumn(#"Added Top Customers by Profit", "Manufacturer", each 0, type number),
				    Result = #"Added Manufacturer"
				in
				    Result

	annotation PBI_ResultType = Table

