table People
	lineageTag: aa248c97-c786-496d-84f0-22de034e6d68

	column 'Regional Manager'
		dataType: string
		lineageTag: 03fc8ac9-b961-4fb1-a6bf-0ea422362abe
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 011fa8fe-efa9-45a0-9411-e68e5d365ccd
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-85439c7f-bbc7-470a-a8de-846a6e909fe4' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true)
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"People Sheet" = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"People Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

