table 'Profit Bin Size'
	lineageTag: 17e62222-d369-4651-8f81-014d334a5e45

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: d2ea0c49-695d-4bfd-9399-63ef77cc2baf

	column Value
		dataType: int64
		lineageTag: 85670cf4-df9b-4697-a360-be5533f3f204
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-e650c2e4-e1e3-454a-a4d2-3d34a983cfaa' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

