table 'Profit Bin Size'
	lineageTag: b20866b1-7d79-4f76-ba46-145fcb025412

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 809baa20-1d9f-4252-b916-a4c4f986506a

	column Value
		dataType: int64
		lineageTag: 9cb36327-aae9-4121-8ebf-16e5665b2eb1
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-81cd46d7-96d4-4d12-bcc7-ac7c2d271aaa' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

