table 'Profit Bin Size'
	lineageTag: c520281d-f585-41ac-ba53-5a2050a4b4c1

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: f32ae253-f374-4c2b-bab6-e396821c800c

	column Value
		dataType: int64
		lineageTag: f197d681-89f6-4ba3-a92c-3cec54b94dd6
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-7bcafe7f-3fa1-45b8-9791-71e6305ad3f2' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

