table 'Profit Bin Size'
	lineageTag: d1a54c4c-96fa-47f0-9c54-ccff5855a26b

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 81c89367-c439-45b1-bd8f-9b8215203b89

	column Value
		dataType: int64
		lineageTag: db03456c-1f4a-4ff8-85e1-552b4c139327
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-88ee2a28-039d-4d9e-8b35-2cdb953a977b' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

