table 'Profit Bin Size'
	lineageTag: b16598aa-b090-4552-bfb0-8f2c06b39f47

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: d9240af0-3310-4ab2-a48c-7f92ba8af824

	column Value
		dataType: int64
		lineageTag: f14d89e4-2ebc-4aa8-ae06-bf6d219ed850
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-51da5656-bfee-49c3-a6d5-ac1bb2eec7f9' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

