table 'Profit Bin Size'
	lineageTag: e7648ca1-af6a-4741-9b01-aa475e8c23ae

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 595c491f-422c-4578-ade2-7364de33589f

	column Value
		dataType: int64
		lineageTag: 79a69a46-d823-43e1-b920-4f07f70b71d3
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-19bac2c0-9c5a-4d95-b80a-df238dd28a3a' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

