table 'Profit Bin Size'
	lineageTag: c82adb0b-5702-4e1e-aba0-d558aa13665a

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: df261149-35b3-4839-ace3-b212aeb96219

	column Value
		dataType: int64
		lineageTag: cba15f6f-6934-42e1-aa2a-954a0f0a8e69
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-1f90d341-a57f-43d2-a244-e8ec78735ed1' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

