table 'Profit Bin Size'
	lineageTag: bafd3fbc-c944-4cb1-b28d-771bc802ba84

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 5bccc6d4-82c2-4301-96bb-403c498c540f

	column Value
		dataType: int64
		lineageTag: ae45c6a8-907a-46f7-ba5d-92376627a31d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-8aadb987-ea38-459e-9217-3c0b1650c99f' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

