table 'Profit Bin Size'
	lineageTag: 624f65d7-a15d-4356-a6a7-c9fe964647ba

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 20500ca9-8f08-45fd-9af7-9bfede819290

	column Value
		dataType: int64
		lineageTag: 9801edef-ec29-4368-85b2-af0d85e2112b
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-0a5e7d27-5e79-4a72-ac2d-9faf814f58d9' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

