table 'Profit Bin Size'
	lineageTag: 99f81a48-a9d4-4dc0-ab5e-d11ebaf873d4
	description: Contains 1 columns and 1 measures: Value.

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		description: DAX: SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: de37c09c-405f-4ea1-b6d9-f5ab04e0bf67

	column Value
		dataType: int64
		lineageTag: 20e2eadb-9241-42ce-bf62-e05116e92c74
		summarizeBy: none
		sourceColumn: Value
		description: Int64 column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-bb53bea1-0d23-438e-9376-46b8c102a5ba' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

