table Returns
	lineageTag: 6234c242-37e5-416b-8804-cfd6ea019ccf

	column Returned
		dataType: string
		lineageTag: f1deb6a5-4bf9-484d-b93c-11fec13029bf
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 516e4d36-ddce-410e-ab2e-b22573ef7027
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Returns-56b48932-172a-49b9-a0ff-2a0c60d8fb28' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true),
				
				            _nav = _src{[Item="Returns",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

