table Returns
	lineageTag: 31f4a9b3-c7b4-4a0b-bc84-0aa08ec6128e

	column Returned
		dataType: string
		lineageTag: e6a22fe7-7999-43a0-9330-17fd353fd322
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 109a426a-ae87-43e6-9180-6f1fe8c8c55a
		summarizeBy: none
		sourceColumn: 'Order ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	partition 'Returns-15eb4af7-ebba-4100-9256-4759bf6722ff' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true),
				
				            _nav = _src{[Item="Returns",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Returned, Order ID.

