table Returns
	lineageTag: b30c4f1e-e08f-48ae-bb68-97cb1a489955

	column Returned
		dataType: string
		lineageTag: 2aae2209-4324-461a-923e-553c19ffb08f
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 6345b1ab-b31d-4a25-8b16-569d192c0a2e
		summarizeBy: none
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	partition 'Returns-bc8de6d8-236c-45f7-984b-125237036503' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true),
				    #"Returns Sheet" = Source{[Item="Returns",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Returns Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table

