table Returns
	lineageTag: b8446830-6159-48a0-b4c9-4c73c1bbe30c
	description: Contains 2 columns: Returned, Order ID.

	column Returned
		dataType: string
		lineageTag: b9eeb30e-bd48-4b4d-9208-e8498abb0f6a
		summarizeBy: none
		sourceColumn: Returned
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: b6f9d637-6c29-4e4a-81a3-2fdd9a2624a1
		summarizeBy: none
		sourceColumn: 'Order ID'
		description: String column.
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	partition 'Returns-62e203f3-5cbc-4120-a6d9-2d77a5364e13' = m
		mode: import
		source =
				let
				    // Source Excel: /Users/mkorotchenkov/Documents/My Tableau Repository/Datasources/2021.2/en_US-US/Sample - Superstore.xls
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\\Users\mkorotchenkov\Documents\My Tableau Repository\Datasources\2021.2\en_US-US\Sample - Superstore.xls"), null, true),
				
				            _nav = _src{[Item="Returns",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Returned, Order ID.

