table 'Top Customers'
	lineageTag: 39810181-0c43-430b-ba0b-bf0b0ba7046f

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: b8b45655-bd6e-4bc0-9252-641ceb055eb1

	column Value
		dataType: int64
		lineageTag: 6748791c-0a49-4e14-88c9-9c621eb15bc8
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-f9051fcc-17a1-44ae-a103-c7d8683287d6' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

