table 'Top Customers'
	lineageTag: 58c1e6ba-03f8-4de2-b710-df54a3fe8c3f

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 9c0deb84-d784-493f-ab45-543e3d47bc49

	column Value
		dataType: int64
		lineageTag: 624de085-e6bd-4e13-8ef9-6a069e1e9d71
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-8311ff50-b474-4196-8d00-d533a8c7a36b' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

