table 'Top Customers'
	lineageTag: 429af562-b660-48ef-9f9c-356f483fc7bb

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: da0a608a-57c1-4a4c-a5ad-2e1a9f801cd6

	column Value
		dataType: int64
		lineageTag: 0f9ed7c3-cacf-41e4-b29c-1303f8923d80
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-63dd6f00-ea99-41ab-b00e-309f3a3c5e23' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

