table 'Top Customers'
	lineageTag: d9438854-5424-4461-b169-38f0ba139924

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 752e2ae2-586b-42ce-864a-6f55bb207d0d

	column Value
		dataType: int64
		lineageTag: facd31a1-e317-4bcc-9b36-964eeb153a00
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-067d337e-0a52-49f4-9e56-b1603be9bf98' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

