table 'Top Customers'
	lineageTag: ab331ef9-bd8d-4367-ad36-171ac02e6981
	description: Contains 1 columns and 1 measures: Value.

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		description: DAX: SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 9308d2af-603f-4625-9ef8-ae8a2dcdb917

	column Value
		dataType: int64
		lineageTag: 547ef667-f72b-4617-810b-12bfd70c8b13
		summarizeBy: none
		sourceColumn: Value
		description: Int64 column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-539c87b6-f6a6-48b9-b0da-876d884588be' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

