table 'Top Customers'
	lineageTag: 30c71327-0667-42b8-8b8d-13193fcaaee5

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 7d869b06-5f66-4c3b-afd9-5e0703acb236

	column Value
		dataType: int64
		lineageTag: 2dc23d4e-9cd1-4396-878f-a7cbf0b80e2f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-b9d9b297-8288-4d87-9b5d-1174b734929c' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

