table 'Top Customers'
	lineageTag: ca81f642-f864-4ea7-b6fa-c1f89a7d8cee

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 0b7f7539-f62b-428e-92a4-997dd2be4980

	column Value
		dataType: int64
		lineageTag: d1de820b-e8bd-41a0-89bb-bfd1bf47b8ae
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-bd157d75-faf7-4050-95c9-a84ae999a63f' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

