table 'Top Customers'
	lineageTag: b337da97-5047-4551-9546-b716576e810f

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: b32865a1-9435-46da-bb20-aec9272ecb5a

	column Value
		dataType: int64
		lineageTag: 558b325b-14ec-4435-a6c8-1761b48a1691
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-be4c3799-e7f4-4034-a3c1-55ea43a923fe' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

