table 'Top Customers'
	lineageTag: 2426616d-5c80-47e0-aaee-4d4faa1333cf

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 5adea9cd-d0c1-4c19-b0ea-debda2fd27da

	column Value
		dataType: int64
		lineageTag: 6232a5ab-eda6-41be-8826-c3c716447446
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-0a19d6d9-8ba8-4b5c-8c41-2175eb3dfb54' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

