table 'Top Customers'
	lineageTag: b49a0953-bb31-4cdd-9e42-41a223233ec5

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 99dfb7fc-3a84-4e46-96a3-2a3bb52e2fb6

	column Value
		dataType: int64
		lineageTag: 988a6c73-78cf-44b4-a841-6a3fd1247747
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-6b0612e0-781a-4854-be0e-b2103ddcde1b' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

