table Calendar
	lineageTag: 47769110-7531-4819-9fee-403e3709342a

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: dae22f14-6398-4b27-b743-7190f6593743

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 28062434-b2e1-4e1b-afa7-5f49386a5b5b

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: a58cad18-6929-4fa8-bcd6-c77107bb1226

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8d1ef641-e9dc-4bf9-b251-6e4e7926d5e8
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2208d3a1-ea2e-4f3d-a4ec-0523725d9688
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b7e224b6-5abc-42a1-b453-d8c5b3f5ce67
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 23407987-c6af-46bb-b15d-a6fa03b70190
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e2db253c-8135-43a3-ae2c-e58c82fcc9cd
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 7b61c275-7471-4aa2-8b2c-7ba878b036b1
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 05c8d5a1-31f8-4603-86bd-4679a89fb70d
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 61a3fb8e-703b-4a05-ab2f-a995b0e525c7
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7cc17de0-94e5-41b6-8bd9-050a66ee6bc1

		level Year
			ordinal: 0
			column: Year
			lineageTag: d46a2662-f2d0-4188-8fdd-c4863ac0f3d0

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 81dc5e6f-438c-4281-8a41-a84c57b0bed3

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 47a01a3d-8c28-45e7-a388-0b07da484ca7

		level Day
			ordinal: 3
			column: Day
			lineageTag: ba2e06d3-905a-4a5c-83d1-9c9489f24fa3


	partition 'Calendar-bb9473a5-beec-4b77-92a7-904b11f2ee29' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

