table Calendar
	lineageTag: e4203788-59eb-40d4-b347-9c8b02a03130

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 41e552cd-d0db-4e7f-8ad5-3bb757919087

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 83d9815f-531c-47ac-81e3-2da539b6dfe9

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 7373979f-1f3e-4510-8fca-c0b22b717690

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e6a01d00-9416-41f6-9f55-588ce7daf991
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 8af239cc-3c9a-4a4b-8126-6f4d434bbe03
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 45021ac5-5852-49b6-83af-8b710f0b81e9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 56658dfe-381e-4cdc-bfd4-9be66c044d10
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f34c485f-5c6a-4918-ae50-01a7205fdc28
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: a5becac3-722f-452a-bf03-b3f0cbfdb9db
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: fffab92e-b801-4e27-a8c3-a1d42117c6cc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9153a5b1-18da-4b96-8805-70bf5177f9f6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6b7f473b-0197-4a9b-a3e5-85724810b90b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7711f3e8-eccf-451e-a7c0-e23bea0f7c88

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 07874a6a-1ffc-49aa-9997-6f636c377827

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: fbc618bc-a00c-47a7-9b31-1dc1e0d2c901

		level Day
			ordinal: 3
			column: Day
			lineageTag: c14b0b4e-bee2-4543-ab07-7fc9a4a0d92a


	partition 'Calendar-cf0e9037-3d80-4fac-bf40-8eedf35cbd57' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

