table 'Fiscal Year'
	lineageTag: 2fc58a0d-c3ae-4f29-8fdc-d04bed1291cf

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 9d344038-f612-441f-835d-51ce9657bbf9

	column Value
		dataType: int64
		lineageTag: 35cef5f1-2e80-4213-b208-3ff592ef9e8b
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-241306ef-92f2-4c74-b315-444ec48d6865' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table

