table 'Base Salary'
	lineageTag: c819d007-54a0-44d0-8ea7-14a55723d5aa

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: f96006bf-a8e2-4330-914a-45dabb4db09c

	column Value
		dataType: int64
		lineageTag: da0cc1d8-d877-454c-a869-d9d99d0818e2
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-78657b2d-49be-45e0-aaaf-07ca7b142bb6' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

