table 'Base Salary'
	lineageTag: cb8edf6d-eda4-4cb4-815f-723b2e1d770e

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: ddc11729-c72c-442b-a2ab-61f5165c034d

	column Value
		dataType: int64
		lineageTag: c84886b7-7b93-4131-a4ce-3955a6b8bb94
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-a9c22520-c92c-47f6-a87a-dbefd4002de5' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

