table 'Base Salary'
	lineageTag: 9c78e961-9511-4ac7-b28b-e97e68f9fcbc

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: d811ac8b-e0c7-448e-af17-06d0328d2fef

	column Value
		dataType: int64
		lineageTag: 47144218-c93b-43d9-b60b-ae10e41e3ac7
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-ad282249-b873-493d-8d03-db07cd933db4' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

