table 'Base Salary'
	lineageTag: 4d790e91-cff6-4e54-af2c-eb619d85b466
	description: Contains 1 columns and 1 measures: Value.

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		description: DAX: SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: d42ed0d8-546d-48d0-9d0e-88445803d12f

	column Value
		dataType: int64
		lineageTag: e045d0cf-6219-416f-8120-f7a0799e134b
		summarizeBy: none
		sourceColumn: Value
		description: Int64 column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-fe6979ad-304f-4a79-a7b6-7633df598c1c' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

