table 'Base Salary'
	lineageTag: 1a3084bc-3751-4a7e-a4f6-57604650edc9

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: 322176f9-ce9d-43d9-88d2-99460fdaf5f4

	column Value
		dataType: int64
		lineageTag: bd7bc9ae-71a4-4092-af4f-0fda62e0294c
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-5021a33c-ec0d-4bfe-bf90-ebb1cbc2ac1f' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

