table 'Base Salary'
	lineageTag: 32d2559b-5e60-4d17-a65c-63302ba5e220

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: aaeb003d-f169-4398-bedb-363d167358a6

	column Value
		dataType: int64
		lineageTag: 40b37a53-f4a9-4bbd-bad6-07349eeb29da
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-1be033d3-02a0-47c3-a6db-d43d47636bc1' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

