table 'Base Salary'
	lineageTag: 7b7a00fe-70fd-4e2d-84e4-bec46485893f

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: c85177af-a7ff-47d2-b36f-6290a5fda21d

	column Value
		dataType: int64
		lineageTag: 2db12b75-93d8-4079-9c82-182e0d8a5aa1
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-c650b078-19a5-47c3-aec0-1f0416627840' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

