table 'Base Salary'
	lineageTag: 7f65d73b-7dba-461f-80da-37e7322ae2d9

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: 9c55e11e-f11a-4ce0-a248-c517d8735061

	column Value
		dataType: int64
		lineageTag: f8601a18-c916-4990-99dc-284714f89860
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-87acac53-8027-42e9-9c25-95fa79df319b' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

