table 'Base Salary'
	lineageTag: 53260b4f-f502-44e3-a375-5495aae533c3

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: c6409e96-e12d-45f8-a7f8-04ec5a5d68c9

	column Value
		dataType: int64
		lineageTag: 73af976c-b87d-450c-84db-285471bac1fe
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-5eb1ff39-860f-43e7-8d2a-3103c04cba77' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

