table 'Base Salary'
	lineageTag: 23737aa7-671c-481b-a07b-a8c04a467e35

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: 55b43427-b378-411b-aab3-4fab01ae2450

	column Value
		dataType: int64
		lineageTag: e47a6bed-ffea-4e92-9dde-54e6ed192570
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-16463bdb-c6f7-4f28-929a-3141967cd507' = calculated
		mode: import
		source = GENERATESERIES(0, , 1000)

	annotation PBI_ResultType = Table

