table Calendar
	lineageTag: e39a4f2d-ea74-4b61-a5d0-947b02aacb34

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: da9a05fd-7c92-495d-9b40-3b2ee86e79c9
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 7d56ce8b-336f-4dfe-bdcb-efe08f2c9090
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 53e09f4d-bae8-4674-8d74-d39af428f334
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 03421afb-3585-45d6-81d3-5b5e59237ead
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: cdc9b4b2-632f-4cea-aca5-723e8d8e0345
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 4396977e-6ba4-465b-ab69-66876fa55958
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 8378bf80-9480-42ca-983d-8c76b68157d8
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d0ceb06d-45a4-4f5f-baf7-882eaba5d0a7
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 0d239d43-a177-4572-b3d0-607297ce1463

		level Year
			ordinal: 0
			column: Year
			lineageTag: a2bb60bd-d393-4647-80d0-4b739aa24fa6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 505029c0-b75c-4edd-8ec3-ad2d1c5e73cb

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e6533668-9717-476b-a04c-03d08977b8b7

		level Day
			ordinal: 3
			column: Day
			lineageTag: a96e7a7e-edcd-4e99-a068-63df9ac314a6


	partition 'Calendar-5fa4f317-9fd5-49a0-a38f-6f3637448e29' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

