table Calendar
	lineageTag: 5efe053b-512b-4aab-b933-259a7013ab64

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2f0f9d91-cc7a-4d21-8d66-867a05c3285f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d533ee25-1d56-4748-aec8-11700c967c49
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0223f56b-2a5a-4fb1-a22e-1af66ea6aa12
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 00940dc3-2bb1-4288-8272-876fb069453a
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e055848f-bf14-4ea7-850e-042a120f2f42
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b8dd4e74-1f12-46e0-bbff-937d5a10b181
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c99261b9-e03d-469a-8980-e3e7544ec19c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: faf0a195-ca44-4e12-ac6a-da177f52ab9f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c7e8a204-8604-4ad0-acf8-4c21a662f995

		level Year
			ordinal: 0
			column: Year
			lineageTag: 14300941-efc2-4cdb-99a0-ae7a85ca3990

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: da9f398d-6dea-4d20-8a57-9bcf699dfaaf

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: d9e91545-3db2-4aac-9d2f-07b2412cc48a

		level Day
			ordinal: 3
			column: Day
			lineageTag: 45dade0f-b044-49aa-bc65-62a1c09f0f85


	partition 'Calendar-bcab611e-7658-4b9e-9bb2-0440337c7344' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

