table Calendar
	lineageTag: 86d32f9b-f947-465b-97fc-94d8c0fed1b6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8d83097b-02d5-4b12-9a89-341e102ef687
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0660a672-51d2-4312-bde2-b8ab5067c505
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ea56cacd-b876-4c07-ae39-969c789856a7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c144aa83-fbdf-4057-8175-3e9f322dbc08
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b46a2c34-6849-43e0-8820-3ddce67f0441
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b713673d-04d1-41ac-8e10-33b61a5ae7fe
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ea2c0fc0-a3fb-47fd-993a-eef621ba72d5
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ccbcd7b7-b5c7-4944-a496-ad05295a2df6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: adef1b7d-3ad9-4980-9699-6c303d18d50a

		level Year
			ordinal: 0
			column: Year
			lineageTag: 2f806df8-3bad-4430-914c-3a43441a366b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 57cba883-5097-4c28-ba7a-7690d33cf695

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7f690adc-66ad-40dc-8d5e-bf80da1528f1

		level Day
			ordinal: 3
			column: Day
			lineageTag: befce53c-3a58-43af-9c7d-cf8dce8fd927


	partition 'Calendar-9bb0c399-743e-4184-83be-455de66dfd79' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

