table Calendar
	lineageTag: c5caea5e-167a-4a1f-b47a-79a2667e7411

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2e94d26a-9742-4bf4-bfb3-9115328360e7
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d11a7e8c-17e7-4c9c-b9bb-6e54c871ca0b
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 28ce5c6f-dc57-4853-bce8-fb58f25984fc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 0e417f24-40d3-4d30-9014-e8c6e281cbf9
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2770ec36-3f68-4a2f-96dc-f52ba46ea3ed
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0a1737d1-ae0b-443a-a5f9-d5f12da216a0
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: bfb5ab27-46e6-44da-af67-cc61021b6d0f
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 059023da-6135-4282-a9a2-703545615f82
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ae165278-8c38-4714-a788-9448dc667a1e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 765fbf30-b272-4065-b6d4-f67924cf41b5

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3b3b81b7-e61a-4666-9573-078345d8a25f

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 8b2f82f3-e937-40dd-8828-ff8a84ee90ce

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1d1cc97f-557f-4637-8794-326b3609361e


	partition 'Calendar-682affbf-3d01-4caa-9161-8265b61c0699' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

