table Calendar
	lineageTag: 2435e1e2-167a-4f59-8cea-7e43890275ce

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a4d96307-8b31-4274-b433-632d47aee45a
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2f9723f3-0747-4100-a459-a92327902568
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 05f96851-eec8-4b9d-8a80-a2b3ffcb924f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a7346c08-a621-430f-8b81-aaa6d4bfec9f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 744e3465-531c-41fa-a182-ca4202db8c17
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 39ebb6d3-6876-4fd6-9e06-ec24bb1c456b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 10442acd-ea22-42a6-99c6-7f91627fda6c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e10e931b-59cb-414f-99c7-4ab3c7029669
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8d99137e-b338-4795-a5ed-c8814c2bb116

		level Year
			ordinal: 0
			column: Year
			lineageTag: b197c394-4c29-4136-b98c-275da444a2a4

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 916949b7-e69e-4348-bc47-03b6a1b801e9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0492d26f-b76e-4890-9c6a-adcc3bb5bdab

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4b389f9b-ea21-473c-8197-da9e92ab064c


	partition 'Calendar-19eea743-598e-4367-af54-232bfbab9a36' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

