table Calendar
	lineageTag: 407cae34-460e-4780-b4a5-e1e127ba6cd3

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fbe7a0b1-98ba-450f-93fb-7740780c62e3
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b4a12c07-73ae-431a-a506-4b7aaffd48c7
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dfa45747-ccf7-42eb-9757-1e64c9c0ec30
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 101f364e-9c97-4ae1-927a-883c8155c649
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4317e84b-0ec0-4f93-a8d0-14587edae03f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b600daff-56ae-46cb-8407-12f8fa50b91b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: e97a488b-d4d3-414c-bf8e-6cef6016ec84
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b1a15a19-a4b9-447e-919f-9aa9c3c52d80
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b263d6fc-1f13-4135-b087-30017715117a

		level Year
			ordinal: 0
			column: Year
			lineageTag: ba2a34b5-0914-461e-a8a0-f240ebb0930a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: cba2201e-d2b6-4f01-a6a7-c89e102780b6

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 58ac0350-0bda-49da-9cff-544ce08b5d28

		level Day
			ordinal: 3
			column: Day
			lineageTag: e8c77693-b4d5-4f56-b82f-5b37eb7782b7


	partition 'Calendar-1e4186a5-8f1b-42b6-87ce-34d60a739b28' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

