table Calendar
	lineageTag: bb4e4234-2111-4a67-863f-fe68f7470bdb

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: cbe30547-f5c8-40ca-91c6-73161615bc16
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d84a1055-70da-4f64-9a64-8f13ea50b08d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d3cff81a-2f35-43c5-b761-2ec3cbf27003
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7c8d3c8a-dbf1-4273-9bb9-6627d4733152
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ad222ab1-bb28-4c08-b1d4-4570dce36936
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 99cc2145-f558-45b4-aa8a-fecaee26874c
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 0b57f810-98e4-4b4c-8288-7fdc609a3c23
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 20e2260b-19c4-4019-ac01-795f7432770c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 45932b7e-098d-40af-8375-b8b02f79fa85

		level Year
			ordinal: 0
			column: Year
			lineageTag: f13f21bb-ef9f-4a10-be83-f70bd72ab54e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 876a0981-66d8-43d2-a842-791bc2ff3f44

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e504e897-8d27-40b2-880b-fad418a592c1

		level Day
			ordinal: 3
			column: Day
			lineageTag: b27a9409-f19a-451f-bcdc-705b773ba26e


	partition 'Calendar-b60cc580-32bd-4315-81cd-1f560960a1ea' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

