table Calendar
	lineageTag: 575a875d-fb96-4ab9-9969-6687903a1a38

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f77929ed-f088-4ff1-b749-a568a55dce9d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 935d12ae-87b6-4680-9b4b-1ad72d2e88a2
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b1210028-b9f0-48ad-bf3d-a77a7e72a5ce
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4ae48ef2-a998-4bb9-b70d-7338bdd8523e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 6f4018f2-c999-4482-b634-83ece0267d2c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e5cdf776-54b9-45e7-95d1-05002a6a6a76
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f0f72792-a4a1-4559-a6e2-048d4ed9f6c6
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 492d7419-7f36-41aa-b4d5-474c43f310e0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3b7ab5a7-b903-4bc5-a5e0-c3a4f06f51d9

		level Year
			ordinal: 0
			column: Year
			lineageTag: ab7bdd6f-2e69-4d64-be86-1728f8c30388

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 63c7a25d-262e-4885-9b2c-af5889dedb8a

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4e9f086a-8415-4392-8bbb-56baecee2c2c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9e82ff94-d056-4860-bb02-5162c7317776


	partition 'Calendar-d3c83cff-5af1-4d0c-a730-bc406faaad02' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

