table Calendar
	lineageTag: 8274372b-5816-4d96-8eae-a41d875aa7e0

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 85f6f7e7-c4eb-499f-92b5-b03f17971b03
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a97e1352-d382-415b-838b-1a3cca42bae3
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 40a9f58b-3bca-4344-bdd3-98c5ed56adda
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 7e9152ca-0a2f-4dd8-a520-1cfd8c9be26e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1d2a5ab0-4555-44c8-bbf4-6635037c1182
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1d3ec1b7-34ab-4c77-9f17-94b85d7271f6
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c1cfc233-5d92-46e6-b2da-49ceca680c50
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 10f91328-a15b-43c6-9604-e56868b7dd50
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f51ddecc-43e1-49cf-9887-78b057bdacf5

		level Year
			ordinal: 0
			column: Year
			lineageTag: 2008052f-2f78-4b2b-befd-f2a6298e9c47

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 364a14f2-dda6-4775-802f-cd8b21e4e4fe

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: cba68615-e992-4d0f-92ce-4dc76d44eb86

		level Day
			ordinal: 3
			column: Day
			lineageTag: b3794e61-abcf-4586-8355-6f170dda2b20


	partition 'Calendar-0ecec7b9-457d-4e46-8188-66a14c684ba5' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

