table 'Churn Rate'
	lineageTag: 3bea77f5-5700-49ed-ad1f-f1f3cc858767

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: a54539ae-0fe7-4741-b567-b17b721a81cd

	column Value
		dataType: double
		lineageTag: 0649660b-0f1e-420b-a633-bbacba217b98
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-120c56f9-bb56-4388-b46d-e360f4dcf070' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

