table 'Churn Rate'
	lineageTag: 6e100ac2-bf8f-465d-97a8-d3eab4fca766

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: a16665e3-9869-4b73-978d-848af3f775a1

	column Value
		dataType: double
		lineageTag: a04f7a27-eb2f-456f-bb48-747fb8c7ccd9
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-3782755b-9942-429e-9fbe-d7f719e037bc' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

