table 'Churn Rate'
	lineageTag: 68c1bc6d-e9b0-4d0b-aa92-a7c7494b3e94

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: 32da5e32-b87a-494c-a86f-3e9dcc977cc9

	column Value
		dataType: double
		lineageTag: b8224a10-56e4-442c-b14e-04efb7c3d719
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-07b43a01-9f2f-4839-8f5d-cd69505ef58d' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

