table 'Churn Rate'
	lineageTag: 96ade2d6-315c-45f3-9721-ef3f4584c1d6

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: d999d649-a618-4805-88c3-b0a4f096ce86

	column Value
		dataType: double
		lineageTag: 449d0e6f-7f86-44fb-8740-0561a3cedd60
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-dd6e911e-45c6-4768-a913-3451017f8c65' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

