table 'Churn Rate'
	lineageTag: 1c4ff6ef-3f8b-43cd-8c15-da9376b28e09

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: 7c942f27-2d8f-4a36-b582-498a080998ec

	column Value
		dataType: double
		lineageTag: 44efbc81-40ee-4f7f-ac0a-fc08b35ec8dc
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-6006312c-420c-49e6-9e14-ffad6c0022ec' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

