table 'Churn Rate'
	lineageTag: 255a4618-52aa-4fc7-a747-c6f983d163f8

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: 8df4fa47-149e-4bfe-b34c-455eafa8c678

	column Value
		dataType: double
		lineageTag: fcc5e175-9a80-4a22-936a-8dfb3f435a20
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-01b381ae-a5a3-489e-967b-8afa87e44dfb' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

