table 'Churn Rate'
	lineageTag: cbfc9185-aab6-484f-959b-78558e727b17

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: 58d40bfe-16d0-4559-ba68-88b2cddcec65

	column Value
		dataType: double
		lineageTag: a5469ed3-1058-497a-be3a-09e75e8bd783
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-31954afd-ee48-4bd1-a832-9722aac738d1' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table

