table 'Commission Rate'
	lineageTag: 28a6e18f-e38d-475a-a408-2e4e6d208b55

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: 55a321c1-1ca2-4783-85c2-1661b986c2ef

	column Value
		dataType: double
		lineageTag: 5e31ac16-d1fb-4d34-9332-508f0b029192
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-95e032d2-4cf7-4ffb-9de2-dcd6858d7678' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

