table 'Commission Rate'
	lineageTag: 3457bb09-2f0e-43c0-8c2b-5300e709b188

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: 7771d2e7-6810-4c8f-a39a-0dfbbf4da255

	column Value
		dataType: double
		lineageTag: 6359fe5a-510c-4394-85f8-fd027f092bd9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-ec1a576c-78a1-4682-8fac-20e02832a651' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

