table 'Commission Rate'
	lineageTag: 73fab782-5e8c-4a08-a877-601bacd70a98

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: 0711e892-a4c7-4570-b8ac-b6512c62075d

	column Value
		dataType: double
		lineageTag: 991290ac-9556-4208-a430-429b980d995c
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-6f6f9452-2c9a-4606-b417-84cd7dd58837' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

