table 'Commission Rate'
	lineageTag: 79da5e42-bcdf-4fde-a6bc-b45332982b06

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: c1f57034-f054-4e9a-9ca1-b32f61c134e1

	column Value
		dataType: double
		lineageTag: 982c485a-4081-489f-9415-6ebe1c319155
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-354225de-47b4-4ca5-a3cc-16e2c5ab8951' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

