table 'Commission Rate'
	lineageTag: 413bcb31-7d06-46f4-959e-f7712841705e

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: 0fc918f9-11f2-47f7-a742-95e50d3635ff

	column Value
		dataType: double
		lineageTag: faba1301-27ed-4ee6-81f6-65cb1e5444cf
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-dc3ab98b-04d2-4cc9-b94f-466b5de5329f' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

