table 'Commission Rate'
	lineageTag: 2a612fe6-face-428f-a72e-c0ef487feda3

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: bcf7f7ea-6c7a-48f3-999a-304cb62c92c7

	column Value
		dataType: double
		lineageTag: c73b5869-955d-45ba-8ce3-dd7c8c4a93b4
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-c5fa1ca1-3b32-49c2-9f03-c65271462d53' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

