table 'Commission Rate'
	lineageTag: d5680a41-9646-4a6a-b0f4-dc4b341c7fd9

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: b60ddbdc-f127-4ca4-9a00-aed61d575b46

	column Value
		dataType: double
		lineageTag: a0215ce2-edb3-4755-9b0d-e2d274c17079
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-3291b27b-783b-4886-85a4-4eff87f12a87' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table

