table Extract
	lineageTag: 1f6d63c4-aec6-4916-8e9d-d3518c74330f

	measure 'Number of Records' = COUNTROWS('Extract')
		displayFolder: Measures
		lineageTag: 19a76d0f-b528-4d41-93be-05acd1161a2a

	column Category
		dataType: string
		lineageTag: 1339000a-9530-4713-809c-b3498c5984e4
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 0f2aba5e-7c91-4214-9b1f-4056c256c631
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: c238ef7c-6537-4da2-95c2-15579d99e298
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: c"$"#,#0;("$"#,#0)
		lineageTag: c7f2c6ef-e8b4-42d6-a48e-6932db58d714
		summarizeBy: sum
		sourceColumn: 'Sales Target'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 9b3b015b-b8e6-4b85-9d6b-8b33e76cde38
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'Extract-17d41a93-772c-4b82-a505-67876b4f3bc0' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Category", "Number of Records", "Order Date", "Sales Target", "Segment"},
				            {
				                {"Sample 1", 2, 3, 4, "Sample 5"},
				                {"Sample 2", 3, 4, 5, "Sample 6"}
				            }
				        )
				    otherwise
				        #table({"Category", "Number of Records", "Order Date", "Sales Target", "Segment"}, {})  // Empty table on error
				in
				    Source

	annotation PBI_ResultType = Table

