table Extract
	lineageTag: 726f3aab-5e2a-4f3c-a910-f37cd7afc1ce

	measure 'Number of Records' = COUNTROWS('Extract')
		displayFolder: Measures
		lineageTag: 081275b6-3f6f-4888-a3e2-32a64ece7c73

	column Category
		dataType: string
		lineageTag: 7c017bc3-1002-4633-adf6-72e8d1801794
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: c8463aeb-063b-4426-ad1a-19c59e364266
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 45ff8cf9-1f12-4d0a-bf25-7e1adbe21f0f
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: c"$"#,#0;("$"#,#0)
		lineageTag: 9e42a647-2bbf-4c34-a31c-3a6bb367ebc6
		summarizeBy: sum
		sourceColumn: 'Sales Target'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 8bd22a4b-c704-48aa-87a8-0aed2423897c
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'Extract-1cb3e341-8632-48e8-9f91-efb81f1e313d' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Category", "Number of Records", "Order Date", "Sales Target", "Segment"},
				            {
				                {"Sample 1", 2, 3, 4, "Sample 5"},
				                {"Sample 2", 3, 4, 5, "Sample 6"}
				            }
				        )
				    otherwise
				        #table({"Category", "Number of Records", "Order Date", "Sales Target", "Segment"}, {})  // Empty table on error
				in
				    Source

	annotation PBI_ResultType = Table

