table Extract
	lineageTag: d2a096dc-a426-4472-9ff1-336bbc2f0dc4
	description: Contains 5 columns and 1 measures: Category, Number of Records, Order Date, Sales Target, Segment.

	measure 'Number of Records' = COUNTROWS('Extract')
		displayFolder: Measures
		description: DAX: COUNTROWS('Extract')
		lineageTag: 821a3a03-ca7d-4b2f-a94d-13428a41209f

	column Category
		dataType: string
		lineageTag: 12612651-beb9-418a-93bd-48e22c8d4792
		summarizeBy: none
		sourceColumn: Category
		description: String column.

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: f867a326-a611-489f-af5d-a192fb4c2b60
		summarizeBy: sum
		sourceColumn: 'Number of Records'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: ce7f371b-6165-4ad2-9618-38da27866303
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime
		description: Datetime column. categorized as DateTime.

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: c"$"#,#0;("$"#,#0)
		lineageTag: 23cb939f-6fc0-4462-87c4-9f815a635b75
		summarizeBy: sum
		sourceColumn: 'Sales Target'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: c5aa0335-b73c-43ec-924b-785ade96aea7
		summarizeBy: none
		sourceColumn: Segment
		description: String column.

		annotation SummarizationSetBy = Automatic

	partition 'Extract-b8f81445-525c-4190-9925-86f0b68ec305' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Category", "Number of Records", "Order Date", "Sales Target", "Segment"},
				            {
				                {"Sample 1", 2, 3, 4, "Sample 5"},
				                {"Sample 2", 3, 4, 5, "Sample 6"}
				            }
				        )
				    otherwise
				        #table({"Category", "Number of Records", "Order Date", "Sales Target", "Segment"}, {})  // Empty table on error
				in
				    Source

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 5 columns and 1 measures: Category, Number of Records, Order Date, Sales Target, Segment.

