table Extract
	lineageTag: edefecaf-9800-4a4d-9651-e00e5347cc7c

	measure 'Number of Records' = COUNTROWS('Extract')
		displayFolder: Measures
		lineageTag: a00c22f9-ef31-4bf8-afba-99a827f43110

	column Category
		dataType: string
		lineageTag: f4a33063-ec38-4367-9548-949cfd1f5818
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: a51b77d2-2b2e-4044-81ec-c804f77aa8bb
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 74829901-62a2-48cf-8381-194eb8698a41
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: c"$"#,#0;("$"#,#0)
		lineageTag: f61c79a5-a404-4e77-a94f-4e816ea1c84f
		summarizeBy: sum
		sourceColumn: 'Sales Target'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 7a9ee77f-1690-411a-9ec8-94902cffb82d
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'Extract-95b66429-5db3-4bbd-b6ae-73956f0fb797' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Category", "Number of Records", "Order Date", "Sales Target", "Segment"},
				            {
				                {"Sample 1", 2, 3, 4, "Sample 5"},
				                {"Sample 2", 3, 4, 5, "Sample 6"}
				            }
				        )
				    otherwise
				        #table({"Category", "Number of Records", "Order Date", "Sales Target", "Segment"}, {})  // Empty table on error
				in
				    Source

	annotation PBI_ResultType = Table

