table Extract
	lineageTag: 884caea6-dcf0-417a-95c6-a8516f8bcfb1

	measure 'Number of Records' = COUNTROWS('Extract')
		displayFolder: Measures
		lineageTag: fddc44d4-84ae-4da5-a222-cdaeb66dc5c3

	column Category
		dataType: string
		lineageTag: 3e97d1f4-74e4-4ab6-92a5-a52c9f81217e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 19e4c1af-0b01-4eea-8e70-8ece25f45532
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0037af98-8531-4d9e-8dbd-b1a3bd099470
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: c"$"#,#0;("$"#,#0)
		lineageTag: 55a2a5c9-8a20-46ee-bd13-30d7491b4073
		summarizeBy: sum
		sourceColumn: 'Sales Target'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: ff47e460-4d5e-4b62-832f-55cc7a13a6c0
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'Extract-4ffc3c1c-04fc-4b45-b01c-5fd51f94768e' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Category", "Number of Records", "Order Date", "Sales Target", "Segment"},
				            {
				                {"Sample 1", 2, 3, 4, "Sample 5"},
				                {"Sample 2", 3, 4, 5, "Sample 6"}
				            }
				        )
				    otherwise
				        #table({"Category", "Number of Records", "Order Date", "Sales Target", "Segment"}, {})  // Empty table on error
				in
				    Source

	annotation PBI_ResultType = Table

