table Extract
	lineageTag: d261efea-9ce1-475a-9815-60738c33a688

	measure 'Number of Records' = COUNTROWS('Extract')
		displayFolder: Measures
		lineageTag: 68163e7c-c5ed-40b9-b58b-6b7a5220c293

	column Category
		dataType: string
		lineageTag: 022fe33a-6e6e-4e58-908e-97037f38bdef
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 9b67a8c9-b86c-4dea-8f8d-960ebef81e2b
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6449728b-faf7-4a6d-af89-f8ff94f1eb36
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: c"$"#,#0;("$"#,#0)
		lineageTag: a85c7876-b307-4dfc-be4e-4bcb3e276383
		summarizeBy: sum
		sourceColumn: 'Sales Target'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 2ffd7bf2-81c5-439c-9ffc-cf07c0e4d3f1
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'Extract-baabd63b-a7fe-484b-8f16-20532b3c3453' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Category", "Number of Records", "Order Date", "Sales Target", "Segment"},
				            {
				                {"Sample 1", 2, 3, 4, "Sample 5"},
				                {"Sample 2", 3, 4, 5, "Sample 6"}
				            }
				        )
				    otherwise
				        #table({"Category", "Number of Records", "Order Date", "Sales Target", "Segment"}, {})  // Empty table on error
				in
				    Source

	annotation PBI_ResultType = Table

