table Extract
	lineageTag: a48d8e45-ad50-40c8-9451-73db4652438f

	measure 'Number of Records' = COUNTROWS('Extract')
		displayFolder: Measures
		lineageTag: 56d9470b-5157-446c-af3d-37000fad7283

	column Category
		dataType: string
		lineageTag: baff9924-fa55-45a4-bc15-aa6429dcee1e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: ff9c50ee-2aa0-4e6e-9cae-48395401f6d2
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2385decc-4ba0-49ea-b127-9947331a9490
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: c"$"#,#0;("$"#,#0)
		lineageTag: 278b8edc-8a20-4633-ba3c-b8518e7e5974
		summarizeBy: sum
		sourceColumn: 'Sales Target'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 0fe59cf1-665b-432b-b3dc-844f40510905
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'Extract-5daf3c14-b8d3-4ddf-a0f3-8cf83adbc143' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Category", "Number of Records", "Order Date", "Sales Target", "Segment"},
				            {
				                {"Sample 1", 2, 3, 4, "Sample 5"},
				                {"Sample 2", 3, 4, 5, "Sample 6"}
				            }
				        )
				    otherwise
				        #table({"Category", "Number of Records", "Order Date", "Sales Target", "Segment"}, {})  // Empty table on error
				in
				    Source

	annotation PBI_ResultType = Table

