table Extract
	lineageTag: 6e8611d4-dca4-4f58-9007-42e6539806a0

	measure 'Number of Records' = COUNTROWS('Extract')
		displayFolder: Measures
		lineageTag: b3f69490-a54e-44d5-9b6a-1d33af2b1c23

	column Category
		dataType: string
		lineageTag: 38cb0f45-1acb-4de5-a810-8ce4df670a8f
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 97521165-94bd-45ea-9421-20664320964e
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4af4eed6-bac4-43ea-9e72-1284214c58fe
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: c"$"#,#0;("$"#,#0)
		lineageTag: 29069063-4187-4da9-b2ba-81730782f4de
		summarizeBy: sum
		sourceColumn: 'Sales Target'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 5fff351a-c0b0-44f9-854f-7c9de365b9e6
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'Extract-58939dfc-a6be-4840-b852-c64051f7f038' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Category", "Number of Records", "Order Date", "Sales Target", "Segment"},
				            {
				                {"Sample 1", 2, 3, 4, "Sample 5"},
				                {"Sample 2", 3, 4, 5, "Sample 6"}
				            }
				        )
				    otherwise
				        #table({"Category", "Number of Records", "Order Date", "Sales Target", "Segment"}, {})  // Empty table on error
				in
				    Source

	annotation PBI_ResultType = Table

