table 'New Business Growth'
	lineageTag: ac4581ff-4f71-43bf-9735-3cba9e3a1f54

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: 83d663fa-be14-415f-93b4-4c679bcc9e3a

	column Value
		dataType: double
		lineageTag: 78590d25-74f3-4e2d-8908-601bbb2ac2f2
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-248f9b1c-bb1c-4712-84b3-362df2b1081a' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

