table 'New Business Growth'
	lineageTag: 7103e89c-8558-4ac7-9baa-35ca23c9c698

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: fe0679f3-45c2-4e36-9aa3-f5a20a717f57

	column Value
		dataType: double
		lineageTag: 2b4afb8c-778b-4612-b939-7af0dc964f90
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-783061f9-83b6-4758-bbea-d06088226c57' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

