table 'New Quota'
	lineageTag: 6dbbcff2-cced-465a-85a3-1622e3594fb0

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: 46547790-9692-4bad-aed1-bfea815d3b50

	column Value
		dataType: int64
		lineageTag: 3bd8d839-7ca1-447a-8cfb-3bb26f8f37cc
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-814e1165-d333-46b3-9734-edf2fe4d2dbb' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

