table 'New Quota'
	lineageTag: cd622574-382d-46f7-a115-1cd5ced4cf63

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: 92eeb5a0-233b-46c4-b149-ee64b719aa36

	column Value
		dataType: int64
		lineageTag: d1b42eaf-ecc2-45f6-b639-136efe7a55dd
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-f55318d6-ede8-488f-aed8-90ed4b70e8e9' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

