table 'New Quota'
	lineageTag: 509ebf4a-5c9e-4ce8-8c62-3fcca41f2e21

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: ad79a553-014f-4c1a-bde1-228025324758

	column Value
		dataType: int64
		lineageTag: ceec592d-5c62-4f0a-ada2-189a0bc100f5
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-33a63d40-323e-4487-9202-1489aeda6245' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

