table 'New Quota'
	lineageTag: fe6cdd6f-d724-4c2e-bc4c-1a5e51dbfaf1

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: ba5cde8e-21a1-4b04-b3a8-44e8b807664b

	column Value
		dataType: int64
		lineageTag: 4453f280-ae40-444f-b309-fc783ae1176f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-4743b8fd-a284-45eb-8bce-ed247c1f2ea4' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

