table 'New Quota'
	lineageTag: ef204909-c417-4242-9e22-6ed841993ec9

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: 4f629ea2-29b0-4fe8-8027-dbf761a1e73c

	column Value
		dataType: int64
		lineageTag: 4301c88e-37ff-4837-811a-f4d166bff8cf
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-71d8f229-1feb-42f0-86b6-e81f422d30eb' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

