table 'New Quota'
	lineageTag: 8ffa4d19-2de8-4d72-b9a7-6a3e1adce640

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: dbd559f4-c4ab-4c3e-92fa-72ce9bc1af00

	column Value
		dataType: int64
		lineageTag: 038f8db9-bb6e-4db9-9b38-aaf59a1008a5
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-92a358b3-e618-483d-8678-19066fee6cb7' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

