table 'New Business Growth'
	lineageTag: 2d444c44-48b1-45e0-a651-4ddb9eeda63b

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: 27bfe5a6-6f94-4e27-8df4-f0cf77f46fcc

	column Value
		dataType: double
		lineageTag: 4de85a19-cb49-417c-b035-7987b35eedf7
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-a3e4c192-90c6-4cfd-9542-e86f8cba7278' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

