table 'New Quota'
	lineageTag: 578023e5-2ac5-467d-9049-a449cf844d0d

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: fe0eabe2-8603-4cab-b768-a541341c203e

	column Value
		dataType: int64
		lineageTag: f05761a9-ea6b-44a6-853c-a47af6ddf365
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-7e355c71-f901-4626-8032-8a44aa5405d0' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

