table 'New Business Growth'
	lineageTag: 8090aead-289c-4a3e-b6bb-c35f9aaca7d0

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: fd223426-834a-497d-8c69-6bf3b5f90237

	column Value
		dataType: double
		lineageTag: 820ddb25-41d9-4ffc-ad13-0b8d34d32101
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-d68606e6-45c4-4b74-9a26-3474e351cb66' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

