table 'New Business Growth'
	lineageTag: 3d1fb71f-6ca6-4d99-b8f9-527954b02053

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: 959bc2a8-2689-4283-a3c5-410de64a5c02

	column Value
		dataType: double
		lineageTag: dc28df79-0693-4aa6-a1a9-04b8abd9ea5c
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-5ccdd7b8-873b-4707-ac39-8f5f827b975a' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

