table 'New Quota'
	lineageTag: cf1b874c-89f1-4934-8d2d-e9185ff8e312

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: 80ce7bbc-dd59-496b-8809-5c1584cd18f4

	column Value
		dataType: int64
		lineageTag: 5f945af7-bf3a-437b-b388-1564f016a1a9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-89e037bc-ee3b-41d8-bf96-480f0b519ef1' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

