table 'New Quota'
	lineageTag: 064a4b11-e4f1-44b0-906e-ed0bc13ec80d

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: c1831f4a-12f0-4e0e-8d66-bdfa96e1513d

	column Value
		dataType: int64
		lineageTag: a901022e-0726-455e-ba62-2a45946df719
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-35c18f14-b988-4a7a-b583-665f33aa6aac' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

