table 'New Business Growth'
	lineageTag: 47f6890d-7562-4bf0-9a7c-6868af59e317

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: 035bb53a-f6df-40b2-8698-59db598b4343

	column Value
		dataType: double
		lineageTag: 50db736f-ef7b-4c07-a433-79e62231a9f9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-35404bed-6fb7-4590-bdd3-fcb5e805e37b' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

