table 'New Business Growth'
	lineageTag: 9a014e76-0cd2-49c7-9947-880a8820f237

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: 85a2d459-a9e7-496a-a1ae-de24b5b9ac21

	column Value
		dataType: double
		lineageTag: d017adeb-1474-41e4-a755-0d1adaf3b3f1
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-ff5cf501-f261-4be7-8376-889d133ce150' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table

