table 'New Quota'
	lineageTag: fcea7e71-755a-4c43-832a-4901c9e376d2

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: c95045dd-b8ff-4c1e-8810-d05e73ec23ef

	column Value
		dataType: int64
		lineageTag: 7fb54006-e75a-4136-9574-256daf4967c0
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-4e2d6b28-5bff-4759-8778-851a087b4465' = calculated
		mode: import
		source = GENERATESERIES(100000, , 25000)

	annotation PBI_ResultType = Table

