table 'Sort by'
	lineageTag: f4062e90-c46c-4abc-a12b-b368103693e1

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: 89046e95-f090-4c18-975a-797326e599e5

	column Value
		dataType: string
		lineageTag: 5ee88c89-f01c-4e6b-8ce3-52bdb0aef977
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-6065b126-e079-4b81-84a9-74ef61b4f165' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

