table 'Sort by'
	lineageTag: da505a8d-03d1-4975-95f3-b9ff17c9c8f0
	description: Contains 1 columns and 1 measures: Value.

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		description: DAX: SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: 7ab44aa7-9db8-4393-a311-cf56ffdd5076

	column Value
		dataType: string
		lineageTag: 64303aa2-b580-4aec-b6ee-5fa9523ed785
		summarizeBy: none
		sourceColumn: Value
		description: String column.
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-d23160c7-91eb-436b-b5ac-63badf3c4e28' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

