table 'Sort by'
	lineageTag: 90f02681-93c7-4dc2-9c65-d60a0ac892ed

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: 68a04a32-de14-43ca-ab5c-8c9bdd76c046

	column Value
		dataType: string
		lineageTag: 84e59f99-593a-4a63-ac72-639b12013e0a
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-b39244b0-bf34-42b9-8b84-5dace13bb97a' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

