table 'Sort by'
	lineageTag: d5dadeec-77a2-487b-8a37-5bca2d994ea7

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: 21753deb-d59f-49d3-90b1-4c76ea8e39e8

	column Value
		dataType: string
		lineageTag: d909e0cc-383e-4143-be0e-1db8a480d8ec
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-01450aed-8078-4a79-9a63-e2b7c2493cec' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

