table 'Sort by'
	lineageTag: c8001819-7599-4f04-b5d0-9d24cdc47981

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: 5a55b19d-d262-40eb-a56f-689627269c2f

	column Value
		dataType: string
		lineageTag: d679f9ad-cdac-4f1a-b38c-7ded985cff0f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-b0f8537c-c25a-4785-a720-86f8bd733576' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

