table 'Sort by'
	lineageTag: 8898ed14-34df-4014-afdc-1deaef80f816

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: db59c6f9-647a-4449-8d18-4f6615fbf7f7

	column Value
		dataType: string
		lineageTag: 3e2ef1ac-2985-4c07-8212-ccacb6267ff9
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-378af7ba-79fe-4225-88e5-6428d33bd364' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

