table 'Sort by'
	lineageTag: 0faa4eaf-c1c0-49e7-b715-aaef616402be

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: 8dcc3410-8668-4f95-986b-cfdf3d34d262

	column Value
		dataType: string
		lineageTag: 74117ad3-eaea-4811-92c1-85c4c8a5fc5c
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-b150a457-cd48-4726-9e61-0b4b1f6c747c' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

