table 'Sort by'
	lineageTag: f583111e-f45f-4f33-9d80-ef59436bdbd4

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: cd994aee-f2f3-4fc9-8d7a-0cc73f7b9334

	column Value
		dataType: string
		lineageTag: e223a050-c4fc-4ad4-88df-329ef434aeec
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-b44355cd-6e0d-46f4-8a9c-f3c77ec25437' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

