table 'Sort by'
	lineageTag: c43b5cce-b1f5-463f-a77b-3085cfeaf98a

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: aff8c23d-84d4-43ae-ae9b-c0240dd19406

	column Value
		dataType: string
		lineageTag: 04fa140e-eaac-4fca-be14-59ec19ec489f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-c10fbfac-af7f-402d-8f4a-920b22802bb1' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table

