table 'Sort by'
	lineageTag: f967d4c9-2435-4df3-9836-0d602a001569

	measure 'Sort by' = SELECTEDVALUE('Sort by'[Value], "Names")
		lineageTag: 9eb95c0f-e95a-4547-a8ad-965a7c400762

	column Value
		dataType: string
		lineageTag: 464aeae5-61cb-468f-ae00-0979431afe91
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Sort by-d6a87036-a7f2-47f3-87ff-a10f9482dd3f' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{""\% quota ascending""}, {""\% quota descending""}, {""Names""}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

