table Rebounds
	lineageTag: debe4866-e8ee-4e50-8324-bd65a8ed6433

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 7238b141-f37a-4989-90f7-255f0b0ed36e

	column Value
		dataType: double
		lineageTag: 5c23bdba-279e-470f-a7c5-506179f95607
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-afc5750e-92bd-4696-9824-be7282e540ce' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

