table Rebounds
	lineageTag: 65307e6f-a327-479a-9ab6-402b1bcfad18

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: d90a948d-5d6a-4bec-9460-939ca0b73920

	column Value
		dataType: double
		lineageTag: c9a4a48e-5d1e-4ac9-b078-228df5d13eb0
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-f4f92504-2a7e-4805-b502-d5d02557c431' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

