table Rebounds
	lineageTag: d664dc3b-9f0e-4ac6-8a0a-faf909732911

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: b282eb7d-2b3b-4ad7-9688-78058c726944

	column Value
		dataType: double
		lineageTag: c9b8084e-6595-4aae-a057-d4cf49ef7546
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-e22342e1-3915-464f-a303-e2dbd329c6c9' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

