table Rebounds
	lineageTag: eed7b123-9248-46a7-9f34-630c89692901

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: a8cb5388-ab64-4ab4-be03-e4db73f1d9bc

	column Value
		dataType: double
		lineageTag: 662508b5-4982-494b-b0ba-80aa696f2bed
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-f334a460-88f3-42ff-a056-ad793c1dffd9' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, {{1.0}, {2.0}, {3.0}})

	annotation PBI_ResultType = Table

