table TestData
	lineageTag: c346adc8-04dd-4abc-9f15-5dddaca82460

	column 'Account Account Name'
		dataType: string
		lineageTag: 09bcac63-37c3-45f4-b16b-467d3b9019fa
		summarizeBy: none
		sourceColumn: 'Account Account Name'

		annotation SummarizationSetBy = Automatic

	column 'Account Number'
		dataType: double
		formatString: #,0.00
		lineageTag: b5753d5b-a49e-4b12-90fc-31b50bf8ab38
		summarizeBy: sum
		sourceColumn: 'Account Number'

		annotation SummarizationSetBy = Automatic

	column 'Account Number Burst Out Account'
		dataType: string
		lineageTag: 08808ff9-e641-4f5e-a100-952a7fcc9f83
		summarizeBy: none
		sourceColumn: 'Account Number Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Acct Name'
		dataType: string
		lineageTag: e2b17d1a-9227-424d-b55d-b2883abb2f86
		summarizeBy: none
		sourceColumn: 'Acct Name'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out'
		dataType: string
		lineageTag: 66d7f121-28fb-445e-96e6-6937ae3514d1
		summarizeBy: none
		sourceColumn: 'Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Join'
		dataType: string
		lineageTag: b63e7294-a32d-4e23-9d04-270c7388f958
		summarizeBy: none
		sourceColumn: 'Burst Out Join'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Set list'
		dataType: double
		formatString: #,0.00
		lineageTag: 154217d7-dcee-47fe-bdbe-6813ae102cab
		summarizeBy: sum
		sourceColumn: 'Burst Out Set list'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out View'
		dataType: double
		formatString: #,0.00
		lineageTag: f4bde848-5f88-4fc7-9e13-ea5afad7cbe5
		summarizeBy: sum
		sourceColumn: 'Burst Out View'

		annotation SummarizationSetBy = Automatic

	column 'Count JE Number'
		dataType: double
		formatString: #,0.00
		lineageTag: 7de1c1e8-f108-44ab-b932-35c243b4379f
		summarizeBy: sum
		sourceColumn: 'Count JE Number'

		annotation SummarizationSetBy = Automatic

	column 'Entity ID'
		dataType: string
		lineageTag: 33372d37-a4f3-4458-90bc-4114163e2129
		summarizeBy: none
		sourceColumn: 'Entity ID'

		annotation SummarizationSetBy = Automatic

	column Filter
		dataType: double
		formatString: #,0.00
		lineageTag: 32144b0c-c53f-4539-b8e2-9d3adfe8109c
		summarizeBy: sum
		sourceColumn: Filter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: 5083c2e9-59b0-476d-8f04-0ce6bfce94f5
		summarizeBy: none
		sourceColumn: 'Fiscal Year'

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: boolean
		lineageTag: a305349a-f38c-4e55-b893-6a101ac73b1b
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column Flag__copy_
		dataType: boolean
		lineageTag: 3d6b07ac-0de6-4227-9db7-bec1131def7c
		summarizeBy: none
		sourceColumn: Flag__copy_

		annotation SummarizationSetBy = Automatic

	column 'FS Line'
		dataType: double
		formatString: #,0.00
		lineageTag: 5e905263-0cb1-4933-b2a4-0da7d04d764f
		summarizeBy: sum
		sourceColumn: 'FS Line'

		annotation SummarizationSetBy = Automatic

	column 'FS Line Burst Out Account'
		dataType: string
		lineageTag: 04ae5298-008b-407e-a47b-4fcf78823e20
		summarizeBy: none
		sourceColumn: 'FS Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Group By'
		dataType: double
		formatString: #,0.00
		lineageTag: fa65b8e6-4de3-45ab-a48a-75cd014fc905
		summarizeBy: sum
		sourceColumn: 'Group By'

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: b7bab43d-2152-415a-96dc-3e17c793c0f4
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	column 'Note Line'
		dataType: double
		formatString: #,0.00
		lineageTag: 5183ad7b-7ffc-48fe-aafa-86c4fefe35b2
		summarizeBy: sum
		sourceColumn: 'Note Line'

		annotation SummarizationSetBy = Automatic

	column 'Note Line Burst Out Account'
		dataType: string
		lineageTag: 3b7751bc-50ad-4fb4-8386-95eb486abce5
		summarizeBy: none
		sourceColumn: 'Note Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Selection
		dataType: double
		formatString: #,0.00
		lineageTag: f3483fd4-8320-40d5-adfe-a51b7cb15ad5
		summarizeBy: sum
		sourceColumn: Selection

		annotation SummarizationSetBy = Automatic

	column show
		dataType: string
		lineageTag: bb5cbc9c-8f5a-452f-b30a-0213ff0192f6
		summarizeBy: none
		sourceColumn: show

		annotation SummarizationSetBy = Automatic

	column 'Show Cycle Based'
		dataType: string
		lineageTag: 16b13379-d281-4e67-aed6-368a1bb81f63
		summarizeBy: none
		sourceColumn: 'Show Cycle Based'

		annotation SummarizationSetBy = Automatic

	column 'Sub Class'
		dataType: double
		formatString: #,0.00
		lineageTag: a0451810-0793-4fb9-a403-547f9a5e6375
		summarizeBy: sum
		sourceColumn: 'Sub Class'

		annotation SummarizationSetBy = Automatic

	column 'SubClass Burst Out Account'
		dataType: string
		lineageTag: 1e98f1d3-3023-431f-a9f5-391f3f5ec48e
		summarizeBy: none
		sourceColumn: 'SubClass Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: b0aee9fb-bc6d-4d59-9051-a5b0abef60aa
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: string
		lineageTag: 5fadb16b-e096-4047-a101-dfd82257a858
		summarizeBy: none
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Amount1
		dataType: string
		lineageTag: 848efbe8-bf7a-4e2e-83cc-c0f085636de2
		summarizeBy: none
		sourceColumn: Amount1

		annotation SummarizationSetBy = Automatic

	column 'Count of Amount Calculation'
		dataType: double
		formatString: #,0.00
		lineageTag: e69b85a5-c6fb-4a70-99d7-1d663d2bd373
		summarizeBy: sum
		sourceColumn: 'Count of Amount Calculation'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: double
		formatString: #,0.00
		lineageTag: 60d31d6c-fed4-48ec-9e85-47b63253bc76
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records1'
		dataType: double
		formatString: #,0.00
		lineageTag: a52656ac-6d9c-47a2-9899-b6b601e8f414
		summarizeBy: sum
		sourceColumn: 'Number of Records1'

		annotation SummarizationSetBy = Automatic

	column 'Select Burst Out'
		dataType: double
		formatString: #,0.00
		lineageTag: 20c820ec-50cf-45f2-a6e9-c1947320decd
		summarizeBy: sum
		sourceColumn: 'Select Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Select Transaction Analysis view'
		dataType: double
		formatString: #,0.00
		lineageTag: 7ab88462-46ab-4e18-931a-b791c31a156a
		summarizeBy: sum
		sourceColumn: 'Select Transaction Analysis view'

		annotation SummarizationSetBy = Automatic

	column 'Sum Cy'
		dataType: double
		formatString: #,0.00
		lineageTag: ed2ed6c6-69f2-4cf7-844d-3dd1e34accac
		summarizeBy: sum
		sourceColumn: 'Sum Cy'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py1'
		dataType: double
		formatString: #,0.00
		lineageTag: 386eb35a-76d0-4ffb-b2c0-4dadcbc466e2
		summarizeBy: sum
		sourceColumn: 'Sum Py1'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py2'
		dataType: double
		formatString: #,0.00
		lineageTag: 4397bc0a-9b16-42b1-b9d3-a443c1cc6c69
		summarizeBy: sum
		sourceColumn: 'Sum Py2'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py3'
		dataType: double
		formatString: #,0.00
		lineageTag: f03fe292-b4e3-4652-bc34-d29ab339fccf
		summarizeBy: sum
		sourceColumn: 'Sum Py3'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py4'
		dataType: double
		formatString: #,0.00
		lineageTag: 99cc33cc-d56a-4064-8ab5-936814bf5a23
		summarizeBy: sum
		sourceColumn: 'Sum Py4'

		annotation SummarizationSetBy = Automatic

	column 'Total Credits'
		dataType: double
		formatString: #,0.00
		lineageTag: a92b76d4-ef6c-41c0-88ef-39b9cf358525
		summarizeBy: sum
		sourceColumn: 'Total Credits'

		annotation SummarizationSetBy = Automatic

	column 'Total Debits'
		dataType: double
		formatString: #,0.00
		lineageTag: 1f1e2f14-dc04-4e29-8180-bdb275e93a0f
		summarizeBy: sum
		sourceColumn: 'Total Debits'

		annotation SummarizationSetBy = Automatic

	column SHOW
		dataType: string
		lineageTag: 4e0220d1-149a-4498-bf75-dd0b459bcb20
		summarizeBy: none
		sourceColumn: SHOW

		annotation SummarizationSetBy = Automatic

	column BurstoutSet
		dataType: string
		lineageTag: 52713a41-48aa-4ed6-b70e-3b40d6e314b1
		summarizeBy: none
		sourceColumn: BurstoutSet
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'TestData-07509d0d-6985-4a84-bac2-5bd2c0f529b3' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("b5dpm3ihhu.database.windows.net", "EmptyDB"),
				    #"TestData Table" = Source{[Schema="dbo", Item="TestData"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"TestData Table", {{"show", "Show"}}),
				    #"Added SHOW" = Table.AddColumn(#"Renamed Columns", "SHOW", each if [BurstoutSet] then "Selected" else "Not Selected", type text),
				    #"Added BurstoutSet" = Table.AddColumn(#"Added SHOW", "BurstoutSet", each "", type text),
				    Result = #"Added BurstoutSet"
				in
				    Result

	annotation PBI_ResultType = Table

