table Extract
	lineageTag: 2f79a09e-1bc7-4063-b020-83abd5f2c8e9

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 7cff1690-5a63-4755-b190-498bb333a10e

	column 'Number of Records'
		dataType: int64
		lineageTag: d2d1a6e8-f3a3-4442-a9ba-01fe00930bd6
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: 85d410c3-2ffc-4d24-9e27-ddaec83fbdae
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: a40c2677-067e-4f08-8c21-f5dea3cd4a76
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 23df5196-dcf0-4ec9-bea5-cc166d07e3c7
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-2f9fa249-37f5-4fa0-82fd-4911ec26ea07' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				
				            _nav = _src{[Schema="dbo", Item="Extract"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

