table Extract
	lineageTag: 5a4f3cfc-179b-40bb-8fc4-c1acd6d3e6d5

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 1dc24035-c367-4f87-918a-24fde1568e08

	column 'Number of Records'
		dataType: int64
		lineageTag: 80d4aa60-f673-4a78-8536-7cfaff014197
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: f06256e6-c89c-4c91-b82b-5648ae96165a
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: caa5f2a6-0df8-483c-8090-cf3ef33ae84d
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 0f473398-885a-404c-a222-1e071fe476a8
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-ce39f87a-4b67-423b-a51d-18f1fa0e60b3' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				
				            _nav = _src{[Schema="dbo", Item="Extract"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 4 columns and 1 measures: Number of Records, a, x, y.

