table Extract
	lineageTag: fa07873c-d740-42c4-a148-4feeb0930c30

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 697dc7c1-935d-4e59-8e6b-1354f3f621e6

	column 'Number of Records'
		dataType: int64
		lineageTag: 0daeb4de-0227-4a4a-97cc-1b2a12b880f3
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: 98f68c4b-2f79-4c5f-ad65-f7b0f0965b90
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: a18a8c70-d1f3-4350-95f4-e7b48c94b41c
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: dea6f7b4-9ab2-4455-983f-ea96c70732ce
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-1161322d-d3b1-40fc-9df4-948ec47d3833' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("mssql2012.test.tsi.lan", "TestV1")
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

