table Extract
	lineageTag: 9343bd0d-10a3-4785-8c8a-e40846671fd7

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 0e4c8dd1-1e5d-463b-8f89-cb3a4abd1292

	column 'Number of Records'
		dataType: int64
		lineageTag: 97399f1f-e6b0-453c-b92e-e394e1195434
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: d369c573-5f03-46ff-96e7-1f107f9300d1
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 332a9809-2a9b-4757-a5e7-5629440bffd7
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 6b377758-228b-4387-b4a7-8090badff544
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-530a1dad-bbd8-43b3-a8b4-f74613a59a87' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("mssql2012.test.tsi.lan", "TestV1")
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

