table Extract
	lineageTag: 3736adb7-9f90-4755-8c1f-dfed5e92d90e

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 89037626-8140-41ce-b3dd-6da98da75c0e

	column 'Number of Records'
		dataType: int64
		lineageTag: d46bb196-4757-41e8-9259-018318958bf2
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: b60d92ab-a795-40b7-b914-51291d993a7b
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 2cbcf9c2-a16c-436a-a048-7862159bba48
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 46ea8904-254e-4e22-86a9-f1ff208e3d1f
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-77e7f344-0ee2-47f3-bd35-1001737436ec' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("mssql2012.test.tsi.lan", "TestV1")
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

