table Extract
	lineageTag: 5da07c21-63cd-4b6d-ae55-96ebd81374d0

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 5b3e08d5-b9c2-41e5-bf5d-c04ed65941ab

	column 'Number of Records'
		dataType: int64
		lineageTag: 6b990dd1-5c27-4f6a-847f-92b65d5dcd9d
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: 7df050e7-4230-4208-8ccc-3aa72c4ad620
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: c19cedb7-94b4-4af6-a3d6-55840402b348
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: d4dc7529-626b-4377-a54a-f2e7ee11f180
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-d9b9f0cd-264e-45f6-8712-6a9ff2568e6b' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("mssql2012.test.tsi.lan", "TestV1")
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

