table Extract
	lineageTag: d1eb0eac-cf65-4a25-8fd7-e6a7056f5ec6

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 8449efd0-d80c-4150-946e-dde717d97415

	column 'Number of Records'
		dataType: int64
		lineageTag: cc506c7b-1a3c-4bc7-9851-d13fe2aa6c58
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: 25a7f0bf-ca2b-4fb2-97cf-aaea30564449
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: d593bb97-9896-4a0f-95bc-262d07633f45
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 67191be0-2d37-4e08-b4d2-45bf490cf8e2
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-e6e577af-e8ea-48d1-b3e9-7cd45f0cf26d' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				
				            _nav = _src{[Schema="dbo", Item="Extract"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

