table Extract
	lineageTag: ba41dd43-517c-410a-a88f-182fcb3d1729

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 20538e84-02ae-4263-9cbc-d7a6dd8a9fe4

	column 'Number of Records'
		dataType: int64
		lineageTag: 72791471-a0fd-420e-8f74-349b871bcddb
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: ac2875f1-a4e9-4042-b282-a93441e894e3
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: b0c86381-f78e-4b5c-bc29-a34fc9085791
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: a841d41a-e6af-4459-a738-7bf544633365
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-9ca9a197-9b7b-4b95-8d93-91e97cfaba6e' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("mssql2012.test.tsi.lan", "TestV1")
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

