table Extract
	lineageTag: d6619625-0c03-4896-a9ad-51b275a3fbe4
	description: Contains 4 columns and 1 measures: Number of Records, a, x, y.

	measure '[Number of Records]' = 1
		displayFolder: Measures
		description: Migrated from Tableau: 1 | DAX: 1
		lineageTag: bc2d358f-56ec-4447-981f-e7058258b720

	column 'Number of Records'
		dataType: int64
		lineageTag: a35cc45d-ea39-4d39-a757-689ebea932bf
		summarizeBy: sum
		sourceColumn: 'Number of Records'
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: c57e9bc3-2a34-4d1d-a2cd-00a4e50190f9
		summarizeBy: none
		sourceColumn: a
		description: String column.

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 62d1a11d-fcc6-4b47-86ba-3bc87a89f667
		summarizeBy: sum
		sourceColumn: x
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 2f987ea0-392e-4647-a0bb-252df27eb344
		summarizeBy: sum
		sourceColumn: y
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	partition 'Extract-9306d0ab-87b9-44d2-bba5-5f0914009912' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				
				            _nav = _src{[Schema="dbo", Item="Extract"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 4 columns and 1 measures: Number of Records, a, x, y.

