table Extract
	lineageTag: f1276794-431d-4ee5-9157-f99997433b56

	measure '[Number of Records]' = 1
		displayFolder: Measures
		lineageTag: 74418713-c44e-485e-bf5e-d16e8b8c04c5

	column 'Number of Records'
		dataType: int64
		lineageTag: 95674b8a-4efb-4a09-abfe-7400a5981d77
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: f2c39f17-9df9-45f3-af39-77b84779bff8
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 69c88a8e-4583-4e9d-a41c-70460c67b8f2
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 34ee8bdb-5a2e-4920-bed1-657fd771b641
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-41f7c0b6-4864-41bd-b668-4ed93c5b796e' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("mssql2012.test.tsi.lan", "TestV1")
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Extract Table" = Source{[Schema="dbo", Item="Extract"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Extract Table", {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

