table xy
	lineageTag: 84b8bc02-9db0-4ecf-bd2e-12c83c3d6e7a
	description: Contains 3 columns: a, x, y.

	column a
		dataType: string
		lineageTag: b49c4779-e8ec-4ccd-aa71-a95e6bcdbe6f
		summarizeBy: none
		sourceColumn: a
		description: String column.

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: f6b32daa-3cfe-49da-a86b-023e7da652b4
		summarizeBy: sum
		sourceColumn: x
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 3e6a2955-c7c0-417a-94b6-fec10e855517
		summarizeBy: sum
		sourceColumn: y
		description: Int64 column.

		annotation SummarizationSetBy = Automatic

	partition 'xy-b45f758c-c652-41b5-887a-af5a84f3cc05' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				
				            _nav = _src{[Schema="dbo", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 3 columns: a, x, y.

