table Calendar
	lineageTag: be4ad8a7-eeaf-4faf-945b-59ad166488e3

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e90a9c8d-65d1-46e3-9bbb-8b95465ed21e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5494815f-3aa1-421f-a7e1-ab15588c6022
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: db5db9cc-3170-4e06-8ce7-cf57e71c1976
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c6654da0-87b9-4f03-a17e-3a124722ae89
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ce471461-3928-498d-a93e-335f5722411e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 076e756f-7ed2-40e0-878e-988a075a0757
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f06aee72-5cd5-4339-8210-33460131e3f3
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 5b0ebd43-a30d-4f45-b2bf-a7a8f6372568
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9c0a077b-bcb5-458d-81e2-da61ec8ce09a

		level Year
			ordinal: 0
			column: Year
			lineageTag: 22f73b14-d5f3-4cde-b457-aee33b6d8e7d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 7ba7d946-4e25-4e76-8101-63403c0a55bd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 5bcf93d0-da78-4b7c-9232-b202f720a1a4

		level Day
			ordinal: 3
			column: Day
			lineageTag: cd2ca71d-7976-42e6-8cd8-cfa15a5d43e6


	partition 'Calendar-f72b999b-f1ab-4c8d-b10d-7d36b7a41150' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

