table Machines
	lineageTag: bfc8a675-911c-4fb1-b6e7-c7ec37fdd704

	column machine_id
		dataType: int64
		lineageTag: 6948ef11-5082-4bb6-b16d-139dae79ef33
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column machine_name
		dataType: string
		lineageTag: 63c94940-3724-4319-b510-015cfafb453d
		summarizeBy: none
		sourceColumn: machine_name

		annotation SummarizationSetBy = Automatic

	column machine_type
		dataType: string
		lineageTag: 297faa98-4cb4-4317-83bf-423704dfb120
		summarizeBy: none
		sourceColumn: machine_type

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4c97160a-53c9-432c-8c20-8a7f6fefd835
		summarizeBy: none
		sourceColumn: install_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: f29f816c-2028-4800-9dc1-561596a2f366
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: string
		lineageTag: 0a2db9de-f07d-49ff-a247-7a39bc682b07
		summarizeBy: none
		sourceColumn: line_id

		annotation SummarizationSetBy = Automatic

	column rated_capacity
		dataType: double
		formatString: #,0.00
		lineageTag: 8cc01a9e-f733-4bc5-a090-200444ce80cb
		summarizeBy: sum
		sourceColumn: rated_capacity

		annotation SummarizationSetBy = Automatic

	partition 'Machines-42d656b4-00f8-467c-9a47-9655479130d2' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        Oracle.Database("mfg-oracle.corp.local:1521/MFGDB")
				
				    otherwise
				
				        #table({"machine_id", "machine_name", "machine_type", "install_date", "location", "line_id", "rated_capacity"}, {}),
				    #"Machines Table" = Source{[Schema="DBO", Item="Machines"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Machines Table", {{"machine_id", "Machine ID"}, {"machine_name", "Machine Name"}, {"machine_type", "Machine Type"}, {"install_date", "Install Date"}, {"location", "Location"}, {"line_id", "Line ID"}, {"rated_capacity", "Rated Capacity"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

