table Calendar
	lineageTag: 7149f537-fe39-4809-802c-db5020a9badf

	measure 'Year To Date' = TOTALYTD([Cost Per Lead], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: de17a7ce-df7c-4e05-90a9-5a7c481497ef

	measure 'Previous Year' = CALCULATE([Cost Per Lead], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: bba8c8de-98ad-49e6-ad89-d8295836650e

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 45e6743f-fe12-4dc6-a510-5c07c6f1d0e2

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c6b96391-fc8b-47fb-ba01-0c3f6fee9142
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5727693b-2487-4deb-9075-338ef0294d9f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 2f9be535-eaae-4823-873f-b04fbeb6ed72
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 247e901f-3782-4404-ba97-9cf2a9d1b92e
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ccc85d5a-82d3-4d9b-9bf0-3257e148d1bc
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 991971bd-7ffd-452d-8f4c-2766aaa689ba
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4e927265-be79-47df-92af-b246fc36ecde
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b16db27f-12bf-420d-b24a-88d2fcbe4fdc
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 8b8cc400-5585-4929-966e-5c51a837e120

		level Year
			ordinal: 0
			column: Year
			lineageTag: 7a189ca8-4c16-40d5-b454-ddd7d3f114b5

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 51bee791-109b-4176-83aa-5754f18a035b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 480f4ecc-544b-49dd-913e-d51c5b00c65c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 970323a7-da20-4a6c-b962-ea8eef6d7a05


	partition 'Calendar-de969051-4e07-4d05-992b-694075262404' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

