table Leads
	lineageTag: e3c93188-b5e9-4eef-8612-112f07912820

	column lead_id
		dataType: int64
		lineageTag: aa9ecdbb-a740-4bb8-af00-546dbaf90be3
		summarizeBy: sum
		sourceColumn: lead_id

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		lineageTag: b09a51c9-9b2a-4420-86e1-2638d49dc05e
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column lead_name
		dataType: string
		lineageTag: 6c8f0f6e-75d2-4fd7-822c-5d6ed27682b9
		summarizeBy: none
		sourceColumn: lead_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: b4b092a8-cc68-49a7-a2ee-334af280a2a8
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: ade2c7ae-0d75-4562-9b97-ed9bd5a782f5
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 7b9c8477-9d16-42e7-917e-c7e0f73446ef
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: cf55b3cc-c294-4f1b-b301-ac4f032d70d3
		summarizeBy: none
		sourceColumn: job_title

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: General Date
		lineageTag: ab315542-560d-4c34-8cf7-837b1a6a6bb9
		summarizeBy: none
		sourceColumn: created_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column deal_value
		dataType: double
		formatString: #,0.00
		lineageTag: 04a20e9c-4d0c-446e-a28a-4013e3f19a9e
		summarizeBy: sum
		sourceColumn: deal_value

		annotation SummarizationSetBy = Automatic

	column lead_source
		dataType: string
		lineageTag: 6a52d05c-5707-4391-99b0-2fd91573dc9c
		summarizeBy: none
		sourceColumn: lead_source

		annotation SummarizationSetBy = Automatic

	column lead_status
		dataType: string
		lineageTag: 15f9c492-0f47-450b-80a8-67ce870a19ac
		summarizeBy: none
		sourceColumn: lead_status

		annotation SummarizationSetBy = Automatic

	column engagement_score
		dataType: double
		formatString: #,0.00
		lineageTag: fb74765a-8090-426f-9efd-c3e369e2f327
		summarizeBy: sum
		sourceColumn: engagement_score

		annotation SummarizationSetBy = Automatic

	partition 'Leads-6ad904e3-1e01-4889-899f-d9e766c6b779' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = try
				
				        MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db")
				
				    otherwise
				
				        #table({"lead_id", "campaign_id", "lead_name", "email", "phone", "company", "job_title", "created_date", "deal_value", "lead_source", "lead_status", "engagement_score"}, {}),
				    #"Leads Table" = Source{[Schema="marketing_db", Item="Leads"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Leads Table", {{"lead_id", "Lead ID"}, {"campaign_id", "Campaign ID"}, {"lead_name", "Lead Name"}, {"email", "Email"}, {"phone", "Phone"}, {"company", "Company"}, {"job_title", "Job Title"}, {"created_date", "Created Date"}, {"deal_value", "Deal Value"}, {"lead_source", "Lead Source"}, {"lead_status", "Lead Status"}, {"engagement_score", "Engagement Score"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

