table 'Min Budget'
	lineageTag: 53816ea9-8039-443d-a542-9a0efc6c7e2d

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: b6e48507-3dfb-44b6-b0fa-ed61e38e7c81

	column Value
		dataType: double
		lineageTag: f2074e20-c2a8-4f77-b59c-c99594c9c4f0
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-8191baca-9093-4c43-aed5-225a295ac72e' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table

