table Calendar
	lineageTag: 45518891-f6b8-4ffd-8a5f-c40cc28adb8f

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b4e16ea2-5009-4570-8a8c-207b1f8a46a4

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 4db22e83-9a5e-4885-9a90-3b795db3d8e4

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 2ef3f94c-8adc-492d-9ee7-45a37404da99

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: dc696785-bf3b-4ef4-84db-49152701e12e
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 838c5161-5b91-4237-b307-76ab46766b3a
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 185d4a90-72f5-4a3e-8460-8fdcd1ad578c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 66e7201a-8ccd-4928-b245-ddfd85c46a35
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b4fb3517-b050-4805-b683-f4bdcc51749a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 43f6699c-3e8e-451c-873a-f33f5bf95a2e
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a52be95f-d49a-4645-854b-285c44f283c6
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 0b20432b-c307-4dd2-8c61-0626da32b595
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 30518c59-a9b5-4df9-a4c6-2fc4e9d38729

		level Year
			ordinal: 0
			column: Year
			lineageTag: d1c0f340-82f7-4686-9eb3-baf0952c13e9

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 6bf70bca-cfa4-4aa0-83fb-b0e19b802176

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: e0293acd-06d4-4de3-9c53-72d2e9b31f04

		level Day
			ordinal: 3
			column: Day
			lineageTag: 2d38ea8c-cb67-407a-8832-eda28927a454


	partition 'Calendar-99743746-ba34-4897-9a2a-6dd22d253fcc' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

