table 'Profit Bin Size'
	lineageTag: 672917c3-d0f1-4b5d-9dea-a86b0049468b

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 72e6f8b3-8e33-4dbf-8fe3-33b32746be01

	column Value
		dataType: int64
		lineageTag: d5503621-2b21-4585-b90e-10603fb25692
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-d7049e59-7ef3-4455-9e28-5bc3ea85aa8f' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table

