table 'Top Customers'
	lineageTag: 31d2a9a8-de33-4806-9609-3b163ea08311

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: ab8338fa-ee3d-4fcd-a398-e2e067e7f02e

	column Value
		dataType: int64
		lineageTag: 83bc9f1d-935a-46b7-96eb-42cb5857f312
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-d086abbe-135e-41a6-a30a-4310171d57ac' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table

