table Calendar
	lineageTag: c3d460ea-d6f9-400d-a199-7b71d9d92af9

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 94126147-f12e-4bdc-94e5-ef87d8ff503b
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b8d49c8e-f55a-4688-ac5e-66292bfa6b6c
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8d4f23bd-825d-45b8-9f35-09ca145baa1b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a66afe7b-bac5-4f16-b03d-837e55b5e058
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 34e80226-b670-4257-8e6f-c51366e75936
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0b89d84a-0c37-4e3a-977c-9b2449ef616b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 08cacd69-bb1a-468c-b0a9-7e0967c866f9
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7320ec3d-14c9-4aae-b305-900630fe3644
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 0b8ada95-d0b7-4ae9-9081-7a6489ddfe65

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4586f329-5a87-4152-9bb8-f9e2d261e56d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: df4e133b-81da-44d0-9fa4-0eefca18b98c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ecb0e11e-b844-405c-a38d-7eb4e79df2cb

		level Day
			ordinal: 3
			column: Day
			lineageTag: 36f66f15-5bb0-4b43-b67d-c431144425e0


	partition 'Calendar-88608df8-9e9c-4228-8240-2754fa6f58ed' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

