table Calendar
	lineageTag: b39b72d0-33ae-4dfc-9e35-7d8ade7ff199

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6dcf3955-c641-45d2-8e8f-e2c8671d76bf
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b0cc83f2-16e7-40ad-a3c8-be2ea5eb2bbc
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: fbf69a53-e6b3-4c88-9d39-89d5581ed84a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5d7c0c52-d288-464c-97e8-1c4b46091047
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c63858eb-4072-4dc9-bae2-510ad04c75aa
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f8019542-e7cb-465f-938c-85f87ba5fff4
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: be0a9ecb-5a1f-4b3f-a57d-b6ede3467175
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 6b328428-99cc-451a-9269-945d22cd171c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 13d7c6b4-b81e-4497-bf88-95d20be637db

		level Year
			ordinal: 0
			column: Year
			lineageTag: fab41100-a43f-4128-972c-a1b6f489bc76

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f601f0bf-0496-490f-8a40-e8feca92d7cb

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: b0ec58a8-7130-4771-a5d1-f60d1c0705d6

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4de9e33a-cf46-4cf9-b708-06cf8674ba45


	partition 'Calendar-80d989ff-8e12-4e7e-bae8-f0616f881144' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

