table Calendar
	lineageTag: 7fc6b406-00aa-43a7-a332-47de82b6901c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5f44546c-5932-4636-a72c-862e22dc8806
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: fec7681e-a896-4aee-acad-ab6a55ef4e2a
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 07a19a93-f23e-4d89-82f6-b2fdddb0ee73
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 950fffe9-e9c0-4b2e-9ad4-12b1434ffd31
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a788ef8d-7a26-40db-ac25-ae121979eb5a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 01126328-77bd-417f-8940-14c691047af0
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 07054c81-8b25-4c0e-9fc5-02097dfabc69
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d3132017-2581-4e12-873a-f3115a51f97a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b1f11883-2333-46cd-8e64-1b9a205afc99

		level Year
			ordinal: 0
			column: Year
			lineageTag: fa939708-6423-4b79-bc63-29715f2b79d6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ee4a20ae-b5a7-49fa-86d4-1c0e80081b69

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 62337811-0fb1-427b-99b4-c4b1053083e6

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6b39830b-440f-4041-b553-31e31bfe0b28


	partition 'Calendar-46ce3730-9334-404c-81ca-e1f1d4dcf93f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

