table Calendar
	lineageTag: 8cdd8d27-1691-4646-9e78-774f22f18b05

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5ae6a985-a887-4d5b-b662-f6286efb1ebe
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 7f534503-8cc9-4435-b80b-e27d399735b5
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1ecd2008-2542-4092-b245-18c10e671393
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 6ab673fe-0ba7-438a-ae95-cce365393284
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: b427d61a-b910-4cb1-90c0-9a172467ec75
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e72ab07d-33a7-419a-8f09-145367e8b519
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2f327e34-b9d3-469b-9634-38e0cc70e7f2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 72afda94-a79e-4e14-a75f-ce9b501f1bd0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: a3e6cf6d-6838-4b2c-9bc2-e7a76cedf30a

		level Year
			ordinal: 0
			column: Year
			lineageTag: 54564b45-990d-4e8d-a032-4887e50cd23f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: aca11391-5d82-44ec-92bc-c3bce36cf4b5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 552cde04-6d3a-4d97-86aa-ee1429dd4214

		level Day
			ordinal: 3
			column: Day
			lineageTag: 905e5552-1f3f-4c4e-b9f5-d04bb6065ead


	partition 'Calendar-819d529a-946f-4383-915b-6a9d3ea8bcc1' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

