table Calendar
	lineageTag: 0da6fb8a-ea60-4ca0-8480-01b381c43835

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0e422847-2526-40b0-8f9a-30f3fab3e291
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9f8342ce-b393-4f22-8e98-a5aa81c0b0c3
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 86229261-e576-4c17-9ae9-a07e919f3f13
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c290ac55-1ca7-42c0-8b7a-e459020ce8b5
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a01f9f3e-cc00-470d-a7f3-80c8d0916d0e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: cd2c55fa-b845-4766-a483-08a8db6c37b9
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 1fca94c9-03c4-452b-b54b-403f7a8a8571
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f227afc5-0687-4dd2-9a65-028172e7f4cf
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f6a6d56e-fa96-435c-b872-704d1030565b

		level Year
			ordinal: 0
			column: Year
			lineageTag: 0ef96346-3227-4b46-84f1-1e3a08abe445

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 449dcc52-2552-48e6-8dc4-65370613e944

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: fcfd67b8-47c7-42d8-8b67-6bccd1180088

		level Day
			ordinal: 3
			column: Day
			lineageTag: 202b03fb-db19-40d4-a715-2de93ae5ea49


	partition 'Calendar-8bb2e55b-4a82-40d7-9024-419d7cefdd61' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

