table Calendar
	lineageTag: d37a59d2-6683-41f7-98e8-1058ab9e4a66

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b149703f-412c-490d-9a65-1a687e0d7d5f
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 708bf656-03e7-4faa-a3a8-220df1e2d559
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: dd9025c4-1a3d-4575-9c7c-eefc0a656d9e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5d0d1347-d183-4bf2-b822-367705141c65
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d6d8da5f-24d0-46bf-b6e6-d6b427a4b934
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f912349c-4d25-4242-8311-39d1cbb3959f
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 1091c6f4-429b-4dea-a711-97748ae612d8
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a49c24c1-fe38-4994-85f7-34e0d22959d6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 76c41c12-04e2-4bb6-8586-90afbba106b3

		level Year
			ordinal: 0
			column: Year
			lineageTag: fcbb0f44-8f20-45ce-aafe-3211723b8d22

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 31968bad-2b13-438e-bbe0-d7225d7b5db5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 63b0eac9-9d3f-4a98-b385-700891ee5c53

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1bf39fe2-408d-49c6-b8fa-95b4f8ebd53a


	partition 'Calendar-b701d2fa-9f10-463f-94f5-7c3f864f4493' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

