table Calendar
	lineageTag: 7a0ff4e1-5775-4776-bdf6-2453730053dd

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e3a41428-a024-435b-ad75-ea1fa5a1cda3
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 6708b32d-fb6e-4a45-a416-8e460adcd796
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 46ba51bd-584a-49d6-a219-bc8feb19fa7c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ff1035d3-1d75-4f7f-9f0a-05c3ff521268
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 598238c7-53e9-48a2-b086-6ff0e7915cb3
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 24c5dcda-d8dd-4029-98ce-e3299cb25497
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 555ca384-efdd-4fc1-bb59-b0623e6e1266
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: eaf9c812-7ce2-420c-874b-60702b6593fe
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 22de2cd2-4cc8-4b24-98d6-08b6bc8fc95e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 90f6e2f9-c748-447b-a80a-33a0cbfe7dd6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3ee41b43-1f0b-4d1e-a44b-b88c35bd5869

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f31b0b04-c03d-4652-9779-c29a035b6365

		level Day
			ordinal: 3
			column: Day
			lineageTag: e4196f66-e742-4e49-8a7c-70521e176711


	partition 'Calendar-4d50688c-b4e1-4c66-8467-209ee94b5f37' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

