table Calendar
	lineageTag: 6fdbe2e9-9e82-4702-babd-298fd5728c15

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 73054dd8-dcb4-4fd1-8e20-13951023cf47
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2a9a0b50-cab0-4b54-86df-41a3039d2614
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 116710b3-e4fc-4112-a38c-01f5e3dec126
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 62d888c4-6394-44be-bbcb-32b97be699e7
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 77f396de-e619-4be1-8b49-95f1fdb1777e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8db2f576-609d-4b88-9886-37b38675c884
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c33def17-9d79-4260-b907-df2411a53a54
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 96d6333c-c8de-4e11-9642-891a7e063743
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 753f5f60-e3ef-491c-9c61-44d0a8888fa7

		level Year
			ordinal: 0
			column: Year
			lineageTag: da8d168d-6162-417c-8288-9386e8c2715c

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 0bdd5bd9-1de4-487e-94dd-54baed66c00c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6d5903d8-2e4e-409f-9188-d06becf5bbc2

		level Day
			ordinal: 3
			column: Day
			lineageTag: 1cd5dd81-d735-4cd7-a9db-0468dd8c8924


	partition 'Calendar-8296ac55-ca41-44b3-a057-b504a086ef43' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

