table Orders
	lineageTag: 6a127749-d1a2-445a-a395-c397383a91be

	column 'Row ID'
		dataType: int64
		lineageTag: f084893c-7302-4f95-a556-89be1ac38863
		summarizeBy: sum
		sourceColumn: 'Row ID'

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: int64
		lineageTag: 5675a93b-c010-431a-b39a-b87f2e4237b7
		summarizeBy: sum
		sourceColumn: 'Order ID'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 094d0790-dad5-440f-9e3d-db46574785fb
		summarizeBy: none
		sourceColumn: 'Order Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: 7722d219-1ca1-487f-9189-6e199055e2d9
		summarizeBy: none
		sourceColumn: 'Order Priority'

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		lineageTag: f00d1624-a2c8-445c-a36b-0807db9e74ae
		summarizeBy: sum
		sourceColumn: 'Order Quantity'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 082401c8-d7d9-449e-9cc5-82b96223c648
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 186df440-962a-4f82-a4c5-4294080a9522
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 6df5f768-7068-487b-a84c-e83cf26adf48
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 936b5097-20c6-42cf-a30a-b6c63a164d2b
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: #,0.00
		lineageTag: 100f4c7f-ed73-4d6f-81fd-6480c5ac5375
		summarizeBy: sum
		sourceColumn: 'Unit Price'

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: double
		formatString: #,0.00
		lineageTag: 6de052c7-08db-402e-becb-a604e8a4231c
		summarizeBy: sum
		sourceColumn: 'Shipping Cost'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 1adeca0e-d6b0-454f-83f9-9ffad42c0e2b
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: c013f327-8eec-42f6-b3db-2c02d3416b83
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column 'Zip Code'
		dataType: string
		lineageTag: 15a46263-323d-4fe9-8917-7c0286cf3be0
		summarizeBy: none
		sourceColumn: 'Zip Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: a49eb66b-4406-488c-9027-ddc969753159
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 2791d75f-3573-4429-921b-7372c2f44e3e
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 9d74dc15-98c5-4df9-8e9d-23bb58940db8
		summarizeBy: none
		sourceColumn: 'Customer Segment'

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: d037d013-d978-4eee-8eb7-5a0313a99b8b
		summarizeBy: none
		sourceColumn: 'Product Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Category'
		dataType: string
		lineageTag: 12f46f87-18fa-4583-940f-12a49f59b851
		summarizeBy: none
		sourceColumn: 'Product Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 6f1046b4-efd4-4e39-be53-7018091bbcfc
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column 'Product Container'
		dataType: string
		lineageTag: ee4af859-5706-4b05-8e11-4fed7dcd0b67
		summarizeBy: none
		sourceColumn: 'Product Container'

		annotation SummarizationSetBy = Automatic

	column 'Product Base Margin'
		dataType: double
		formatString: #,0.00
		lineageTag: f0cfc0df-1a8d-4396-9c4c-925dda7855d9
		summarizeBy: sum
		sourceColumn: 'Product Base Margin'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 734e5d04-7616-4734-ae92-51daf641bfbf
		summarizeBy: none
		sourceColumn: 'Ship Date'
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column 'Grouping Based on Unit Price'
		dataType: string
		lineageTag: 00e98064-e055-4c70-ac4d-c33b28c08168
		summarizeBy: none
		sourceColumn: 'Grouping Based on Unit Price'

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: 32ac98a9-6e7f-4860-aaba-742848723865
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Orders-2249d920-fca0-4267-be43-42fcdd65c20a' = m
		mode: import
		source =
				let
				    // Source Excel: Orders.xlsx
				    Source = try
				
				        Excel.Workbook(File.Contents(DataFolder & "\Orders.xlsx"), null, true)
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Order Priority", "Order Quantity", "Sales", "Discount", "Ship Mode", "Profit", "Unit Price", "Shipping Cost", "Customer Name", "City", "Zip Code", "State", "Region", "Customer Segment", "Product Category", "Product Sub-Category", "Product Name", "Product Container", "Product Base Margin", "Ship Date"}, {}),
				    #"Orders Sheet" = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Orders Sheet", [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", Int64.Type},
				        {"Order Date", type date},
				        {"Order Priority", type text},
				        {"Order Quantity", Int64.Type},
				        {"Sales", type number},
				        {"Discount", type number},
				        {"Ship Mode", type text},
				        {"Profit", type number},
				        {"Unit Price", type number},
				        {"Shipping Cost", type number},
				        {"Customer Name", type text},
				        {"City", type text},
				        {"Zip Code", type text},
				        {"State", type text},
				        {"Region", type text},
				        {"Customer Segment", type text},
				        {"Product Category", type text},
				        {"Product Sub-Category", type text},
				        {"Product Name", type text},
				        {"Product Container", type text},
				        {"Product Base Margin", type number},
				        {"Ship Date", type date}
				    }),
				    #"Added Grouping Based on Unit Price" = Table.AddColumn(#"Changed Types", "Grouping Based on Unit Price", each if [Unit Price] <= 2500 then 'A' else if [Unit Price] <=5000 then 'B' else 'C', type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Grouping Based on Unit Price", "Action (Region)", each Text.From([#"Region"]), type text),
				    Result = #"Added Action (Region)"
				in
				    Result

	annotation PBI_ResultType = Table

