table Calendar
	lineageTag: dd6128d1-4256-474d-b898-47dec75bfccd

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fc8a1c94-b245-4f4a-95f3-71fdcdab8a84
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 26bb9cbc-8b31-4b40-bed8-a59e561d4650
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 73a72801-8e67-4a56-8d3b-b6ef3153ef80
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: fe7a1bdb-3d1a-4b33-8fc4-4decf93b0fa0
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 33c1cb8c-e352-4145-9499-a911d7bfeeaa
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8828ebb9-427a-43c3-8ce5-a32d59bf5bec
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 00529ef4-4e9b-470b-a088-9a8e6e0735b9
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 017b8d43-54af-4c12-a0a8-15db64e71d90
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 59710843-682d-4225-b8b7-ecd23db6b87c

		level Year
			ordinal: 0
			column: Year
			lineageTag: 2b790718-5c72-4045-8a45-2daf68bf7d6d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: e367c743-c6fd-4024-8e99-69e9d02ab5ae

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 2d84a804-4b7c-4097-9c8c-6d7c5f5b8742

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4c1b4820-e363-4331-ba63-bfaffb6c0f13


	partition 'Calendar-802a9310-ce93-4220-95b7-35977425231f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

