table 'Target Margin'
	lineageTag: 1a61816d-801e-45fc-941f-76ce8e73fe3d

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 06c8506f-470b-4950-a527-63906c5bbcfb

	column Value
		dataType: double
		lineageTag: c4c543c2-21e2-4ec6-a402-65e34d47e4b1
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-322a1d1d-5015-4468-871d-30b21851f047' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

