table xy
	lineageTag: e7683f28-de9a-44d4-8302-147bb7add4ab

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: 5290309a-bf84-4376-8bae-49569523db0b

	column a
		dataType: string
		lineageTag: ba3b8cc7-9e18-4367-853b-d255886ca68a
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: f7b1e147-23b4-45a3-b0ec-2bdea5262fc3
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 296de088-a708-4d09-a182-43121e28722a
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-5e8a2a7d-2c88-4e86-af74-3ba7b32cccf5' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1")
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"xy Table" = Source{[Schema="public", Item="xy"]}[Data],
				    Result = #"xy Table"
				in
				    Result

	annotation PBI_ResultType = Table

