table Calendar
	lineageTag: b2e5385c-6320-4fdb-8263-b1d8452fb894

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2748cfc2-298b-4647-9599-b93d59609cae
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: fa2d71d7-e86c-4510-8210-a686f81f12ba
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c38d6816-617f-49ad-b6f3-56bc4f0c101a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: f415afbc-16ad-476f-8783-345c1e00feab
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2c56041d-7612-4ea9-ae9a-bd59d5092613
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 547472be-5e09-445f-bcfb-4577f235cd54
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d65667ff-fbb1-4fb0-8128-96eefee7a271
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: fce56653-cef3-499d-a3e7-9891deb43b6c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: bd863201-6d15-4775-83be-6710b246dda9

		level Year
			ordinal: 0
			column: Year
			lineageTag: c2b0baad-de65-431a-9191-dd4a857893f6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: eddc5215-16b8-4a5c-8f91-0f4034a615be

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: cf013c2d-4027-4c29-87f4-6cb4ffa1474a

		level Day
			ordinal: 3
			column: Day
			lineageTag: 33e30506-3b27-4b9b-afcc-05ae31a77413


	partition 'Calendar-0468033b-5882-4feb-80e5-7b035d492f17' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

