table Calendar
	lineageTag: 6a85a0e9-9e13-478e-9794-1a7fa51c81ea

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 84adfb74-be1c-4d75-b3ea-75911484a4b6
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f49c50a5-cdef-4850-905f-00cf3b6d31ab
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d5d4febc-8545-4bce-9dde-271c8d445dc8
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 21adc2e7-0baa-416b-a690-c141c6c318a0
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8a044051-e69b-4941-99e5-f5d79103da5c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b3ecb2ee-7057-431d-8113-de780f6d5367
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: eb44727d-f67c-42f9-b2af-846a88c4f596
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 56261190-6caa-4eed-8e75-dbef4f9aff60
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 1d0fce8e-898c-4d93-8411-99e5e4d495a1

		level Year
			ordinal: 0
			column: Year
			lineageTag: d64cbd48-01c1-4404-b6c3-2f3f098abbd2

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 946d3e6a-37d2-439b-9396-fccf6c86ea57

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4392bf9d-22ce-48f5-8e01-fdd0edbc5892

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5ca72839-7e66-4b87-9906-da4cfd8e859b


	partition 'Calendar-618acbf2-7930-48d1-9f1f-f9f557760d83' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

