table Calendar
	lineageTag: 671e1358-86b1-44e9-aa30-7880fb5163bf

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 67f44323-1df5-4a4b-b9ef-601d1a950df6
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 6da0980d-9bc2-4900-a8f1-5d4cc5a5140e
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e1d055ab-3ba1-477d-8e62-7ff3b83d7a34
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: dbd9eebd-032f-4a06-9650-86f7ea26ed14
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e268115c-6d74-40be-93d3-af3f91485321
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b8a70156-78e2-4bb3-b40a-e38916469f19
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 283cedc2-57dd-48e5-8c35-86e273d47c80
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 633e83d2-1bd3-467b-ada9-2c5493cc7b90
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 034c68f9-9719-46e5-a8db-8323dba6b7ea

		level Year
			ordinal: 0
			column: Year
			lineageTag: 4a92074e-47c6-442d-ab89-592e965cdaa9

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 86136794-c4e8-4c0b-977e-69c37a1ca323

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 11b34269-0309-4b0d-87b3-a5ab416bb22e

		level Day
			ordinal: 3
			column: Day
			lineageTag: e47474b5-676e-414b-b60c-c5abcb21c412


	partition 'Calendar-ee35b869-3b80-404e-95e2-355e869eba77' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

