table Customers
	lineageTag: 7f4f4596-eb71-4a67-b955-2f15350e5465

	column customer_id
		dataType: int64
		lineageTag: 4e630d61-2c1a-4efd-9772-4b1a06cdeaf8
		summarizeBy: sum
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: f8237167-c69e-4984-8da0-2c8c42b39f8d
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 554a0d86-2794-47af-a0c6-7b64cc7cf582
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 01e6f8c5-e501-4c3d-bf3e-01ea513cdbcd
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: d606dffa-dc50-45c5-bf44-8d3bfc5a4589
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 744c6bd4-bc76-4399-88e2-42bb9b540cbb
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: 2519794e-66d2-40c2-9e05-a1641b011e26
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: da67066e-ba62-44fa-94f3-2b4f8f454708
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: 49d2fe80-58cf-454b-86cd-5c3b5150d93e
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column customer_email
		dataType: string
		lineageTag: 2c33f322-2a9f-43d8-9438-04a0a6961ba4
		summarizeBy: none
		sourceColumn: customer_email

		annotation SummarizationSetBy = Automatic

	column first_purchase_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4429add1-6de9-4827-b1db-e8ff557f1a4d
		summarizeBy: none
		sourceColumn: first_purchase_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Customers-bc7aa5f7-2954-4345-8daf-0c8ba99b5837' = m
		mode: import
		source =
				let
				    // Source Snowflake: acme.snowflakecomputing.com
				    Source = try
				
				        Snowflake.Databases("acme.snowflakecomputing.com", "COMPUTE_WH")
				
				    otherwise
				
				        #table({"customer_id", "customer_name", "segment", "city", "state", "country", "postal_code", "latitude", "longitude", "customer_email", "first_purchase_date"}, {}),
				    #"ANALYTICS" = Source{[Name="ANALYTICS"]}[Data],
				    #"PUBLIC" = #"ANALYTICS"{[Name="PUBLIC"]}[Data],
				    #"Customers Table" = #"PUBLIC"{[Name="Customers"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Customers Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"segment", "Segment"}, {"city", "City"}, {"state", "State"}, {"country", "Country"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"customer_email", "Customer Email"}, {"first_purchase_date", "First Purchase Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

