table 'Target Margin'
	lineageTag: cad32237-710f-4217-8c92-09db81df2b39

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 456bbed1-e9dd-4def-90b5-c15c3d383c59

	column Value
		dataType: double
		lineageTag: 75dbe3e8-1b20-4b01-88d8-c9638273268e
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-94f1a5b3-3c83-4fd0-95e7-bde6f68a3e40' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table

