table Calendar
	lineageTag: cfd7c218-c59b-4f24-b643-4eeb9f180b5c

	measure 'Year To Date' = TOTALYTD([Total Compensation], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 9d804e8b-82c3-4c89-b557-404dfeab94fe

	measure 'Previous Year' = CALCULATE([Total Compensation], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 0bc22b11-a2ae-4cf8-b197-4d678f5c059d

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 8c71e407-54d3-4c9e-a36c-e8bc946b69f7

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 51a08f74-73ad-4b74-95cb-96c293ffa166
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: f1cd8da3-d300-409e-ada0-8c1b137e3d9f
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 205fefec-4856-43dd-b5f0-e19c8239f765
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 0f40cce1-b0b9-45c8-b748-de8e1b3ad1e3
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 6f1b1176-284e-47aa-9bb5-6f4c3e6f73f0
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 54897ffb-d78a-4754-b361-0e0f49bb95c8
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: bfa4a4c4-a3c7-4c8d-ba96-2bbe9e6e0cd1
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c9913492-c4c3-46d4-b956-cb47d01b9432
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4785f49c-d278-4011-bd96-e690ff23ab82

		level Year
			ordinal: 0
			column: Year
			lineageTag: 3903bbcd-65fb-4739-bd6f-1b9b85149793

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 881adcd8-44a5-4771-a214-623ffb154e19

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 115cac08-c00f-4624-96f7-96b17eea6bd1

		level Day
			ordinal: 3
			column: Day
			lineageTag: b663b6c8-fa50-4300-868a-6293a13fc771


	partition 'Calendar-b0ed5377-ff8f-4436-9c08-d2a1ba692385' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

