table Calendar
	lineageTag: 1e13fda5-30b0-429b-a353-b65b11be7658

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c0d8e98d-19fb-4ddb-97a0-bcdbbdd0d197

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 06f4cc75-dd5f-446d-b7b7-0c19fc97bf15

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: bdc5d439-cae0-4b31-85e5-638bbe0b8c5e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4710bace-51cf-44c5-96ad-5ef8683d54bf
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 956eb304-5e96-4b06-906e-01debb543453
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d915701b-926d-42ad-b42a-fe07220b910a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: cd693d52-7ad4-4f3e-96b3-432e4f89d66c
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 198be7ca-b4d8-4b7b-9211-84e11b8b7a1a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ccd8549d-4f3f-4ebf-8e0b-69fd6083552d
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: befbda42-c06a-4b51-9f35-68c99444cc22
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 5ca1aa3e-1e7d-4b00-af8c-f0e8c36a2173
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 887ffb00-2291-4852-929e-7494724516e3

		level Year
			ordinal: 0
			column: Year
			lineageTag: 3165c3ae-2731-4c33-9199-d1be3e216552

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 8aaa1efb-5af9-495d-9762-5cf0029492ee

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3f12ce64-cfed-44f5-bded-4dfff71edf8a

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6ddf68fd-954b-4d70-a52d-95399742e142


	partition 'Calendar-3d4685e8-926f-4d8a-b15b-f1aa721a4c77' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

