table Orders
	lineageTag: b43a2620-44a5-42e0-87fd-3e059ed0c167

	measure 'Is Current User' = 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 443fdbee-e492-486d-9026-fd1134906ba7

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: b79da589-e1fc-4cff-9020-51ab65031146

	measure 'Region Match' = 'Regions'[RegionManager] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 425343c8-59c1-46b4-97af-fbaedb0602e3

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2d03eab9-e9b9-4ca2-84cd-138cc60ae66a

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: dbfd191c-b0ce-4bc5-8495-f28e63c332ee

	column OrderID
		dataType: int64
		lineageTag: ec9b56ca-df3d-47f4-90d3-ab9c70799832
		summarizeBy: sum
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 812a4957-e405-4c9c-9438-f3b3c42f658c
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 118a36b9-610c-4ccc-a7c5-e72460e54540
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 79b78a7a-3d20-4104-bbe1-962aa750a754
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column CustomerEmail
		dataType: string
		lineageTag: 43792cd0-dcf7-4aea-8528-22a90d46c54b
		summarizeBy: none
		sourceColumn: CustomerEmail

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 978ed0cf-8877-4790-8d48-0548a43e4dc5
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7587e0ba-9416-4fbb-a141-3036b426c2f0
		summarizeBy: none
		sourceColumn: OrderDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Orders-3cb0d3e4-7a4c-4e43-af1b-063c7f0a7d2b' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        Sql.Database("localhost", "SalesDB")
				
				    otherwise
				
				        #table({"OrderID", "Region", "Sales", "Profit", "CustomerEmail", "Category", "OrderDate"}, {}),
				    #"Orders Table" = Source{[Schema="dbo", Item="Orders"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Orders Table", {{"OrderID", "Order ID"}, {"CustomerEmail", "Customer Email"}, {"OrderDate", "Order Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

