table Calendar
	lineageTag: 9e198602-7975-4482-a621-f1460c05ffb1

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d24d0fb5-3840-4c1d-bdf2-a70f1f496148

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: e0b30f3a-309c-4ae0-9037-880fcafa5a34

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: da27427e-3c0a-4204-80fd-6111464e68c4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3228ff0b-5c90-41e5-92ff-08d8da4289f3
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: b85cb827-4c89-4fea-8cce-362d316d3219
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7dd31547-2789-4f71-bd02-a99e0218999c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: ca76b55c-86f2-425f-aa04-9ad3035d842f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 3de2dba4-2c66-4868-afe5-514a364814ee
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 1f6b6fdd-259e-40d9-b491-934705bd22ec
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 71ec8386-379c-4fe1-a242-023dd3678c92
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 9254eebf-d546-4071-b91e-1f7f217791ed
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4c8c791a-1acb-4db6-bf59-be9aa1fadb27

		level Year
			ordinal: 0
			column: Year
			lineageTag: a0ac9e2e-1e1b-40d5-b3f4-430e2a428dfe

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 6a8347ee-c705-4120-9db4-89e2e1c05cb1

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7ac0c022-9d05-4b86-931b-586d946dfde9

		level Day
			ordinal: 3
			column: Day
			lineageTag: 0de4bee4-1080-48ef-a768-bb91c9f30c1a


	partition 'Calendar-c242a560-994e-4d47-a2f8-107ac640ac24' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

