table Calendar
	lineageTag: 0563c8fa-7016-4cc4-abb1-d17b69394d6c

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 3f681669-bc06-4328-98f7-e6415ede2200

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 13c0760a-77f5-41e7-876b-749d66ebd5a8

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: b9722fe1-81b3-41ad-9e45-1d625ae1e18c

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f34cf624-c40e-4e75-9e25-40ddbab4006a
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a4d4ae76-43e7-4e52-a62a-a1ec689c2796
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d6fe2838-3a4e-4378-adb8-81c0fe2919fd
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4a0b6806-eb70-4fe3-8ef6-56fe8e499bd1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e78d2df2-7e81-4e0c-be5d-96914d4543eb
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 64c86f13-ef95-4b1f-bd8d-a85e56fb7a81
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 52ca72cc-a551-4a93-ace6-84bd2f8715f9
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 50e07434-199c-424d-9fd4-2ff888e0edfc
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: d5f26db3-25c1-439e-aee5-d01f888c15a9

		level Year
			ordinal: 0
			column: Year
			lineageTag: 5e3bd10f-8e04-4a69-a051-ba3cb2600ded

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: cea29951-7131-4623-8bfa-24db0db79311

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 54256a98-6f23-44fe-8318-33e327661991

		level Day
			ordinal: 3
			column: Day
			lineageTag: a9fe51cf-021c-4c90-a3a0-496ba1336d9b


	partition 'Calendar-6219f90e-07e7-4a5f-aabb-fee367f91ead' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

