table Calendar
	lineageTag: e9a4cdbd-96a2-4b3f-b59a-004396d36cf0

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5ff89407-7aae-46bc-b60e-6f53f1dc2ebd

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 335e1b03-652c-4c6d-819a-dedffe92f9ea

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 7c05209a-caed-47fc-b52f-a545003f50c4

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: cf516bc0-c9ed-4673-9cd8-c9eba117362c
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c0e4e094-14ac-466d-93f2-c7a411744646
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 27dd76ed-06d3-4ae1-9ea7-c63b07e87a78
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5d129f84-9d26-4e48-893f-972fcd5861a6
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 91146fd5-eec7-4b3f-ac91-6e0d2ebca36a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 76a8c6fe-d309-4e57-8594-dad88aa67c6b
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: d6b7b477-40e2-4e7a-8d1a-a69efdefcbed
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 4230cc5f-fd82-4099-9d90-e939e86597c9
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 86119b9f-ca0c-4924-86c3-95e57429af5d

		level Year
			ordinal: 0
			column: Year
			lineageTag: 8ddba47d-055b-4bae-ad5f-3bf927f0ea04

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b32af19e-b37c-4d0e-bbef-93e62a84a9d1

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a188b5b6-3680-484e-8cfc-e47e63845cca

		level Day
			ordinal: 3
			column: Day
			lineageTag: fa7d3773-3128-422d-9063-ea1e62553556


	partition 'Calendar-c9db2759-0334-4485-9b5b-b40c66893c1c' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

