table Orders
	lineageTag: a7e647c7-e567-49cb-9745-ae1f183fac08

	measure 'Is Current User' = 'Orders'[CustomerEmail] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 1e8775da-e59f-4152-ac99-92f5bc93fd7d

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Managers"): implement via RLS role */ || TRUE() /* ISMEMBEROF("Executives"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 6973792c-01c9-46e1-9131-dffa4c5583b6

	measure 'Region Match' = 'Regions'[RegionManager] = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 1c1df568-1718-4169-9949-9365e7e6ab23

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d31ddeee-6850-48b3-b9cd-5ef80fb5d175

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: aa5e222f-275c-42bf-a5a5-caba36e76054

	column OrderID
		dataType: int64
		lineageTag: f92f63a7-2cdd-479e-8f1d-a5d53602d5e4
		summarizeBy: sum
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 0f16fa97-b485-4f03-8c4e-4f4cd8ca8f09
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 3c7e52a6-4ee0-48bb-afda-e9d385f8ff8b
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 7021434b-7f10-4906-b4b1-c8b7a43a3cb5
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column CustomerEmail
		dataType: string
		lineageTag: b66a79d3-a038-42b9-9ac7-7deac7160323
		summarizeBy: none
		sourceColumn: CustomerEmail

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: f4c56bef-def0-41df-a2e1-c195028f90b3
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 5ae6ea6c-8d91-4db3-9a7a-e0a419c23f4a
		summarizeBy: none
		sourceColumn: OrderDate
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	partition 'Orders-21e6dc53-b890-48a3-8773-b4ecd6bc03cd' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("localhost", "SalesDB"),
				    #"Orders Table" = Source{[Schema="dbo", Item="Orders"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Orders Table", {{"OrderID", "Order ID"}, {"CustomerEmail", "Customer Email"}, {"OrderDate", "Order Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

