table Regions
	lineageTag: b5dccdfc-5792-42e5-bdd5-f64309ee4638

	column RegionName
		dataType: string
		lineageTag: 96847190-983b-443e-bd0a-5dc15f79fcc2
		summarizeBy: none
		sourceColumn: RegionName
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: c139432f-c607-4dbd-9d94-89a39e7e1a95
		summarizeBy: none
		sourceColumn: RegionManager
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'Regions-2ad866e0-1b80-4367-a25d-6a93af231aca' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("localhost", "SalesDB"),
				    #"Regions Table" = Source{[Schema="dbo", Item="Regions"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Regions Table", {{"RegionName", "Region Name"}, {"RegionManager", "Region Manager"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

