table Regions
	lineageTag: f158b2de-59ba-4b9c-9542-2667a922527a

	column RegionName
		dataType: string
		lineageTag: 71aeb316-d5ab-4190-b4f2-cda2e44ee6fd
		summarizeBy: none
		sourceColumn: RegionName
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: c750fbe9-cb59-4c0d-bbb5-b90db0562a11
		summarizeBy: none
		sourceColumn: RegionManager
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'Regions-1fca1274-da48-4a61-8cdb-a3f51b5b15e4' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = Sql.Database("localhost", "SalesDB"),
				    #"Regions Table" = Source{[Schema="dbo", Item="Regions"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Regions Table", {{"RegionName", "Region Name"}, {"RegionManager", "Region Manager"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

