table 'Alert Threshold'
	lineageTag: 1cc15bb7-7ac7-4df6-beb5-aaceb1f20b97

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 54331e3b-732a-41e0-ad28-e8b03129f8fa

	column Value
		dataType: double
		lineageTag: 1ae0d9e3-7011-4cf5-b230-c6a2d582f658
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-8198c67c-3efb-4b49-811a-67b5fdc82e8a' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

