table 'Alert Threshold'
	lineageTag: 4abb5ee8-cda3-418c-88bf-b2f04279af4f

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 263792c3-40c2-4237-9069-53b2cf10d21e

	column Value
		dataType: double
		lineageTag: ace65a4a-e346-4c6b-8810-57aaeb11527d
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-ea0a93a2-dc02-46ec-8387-fb0290dea69c' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

