table 'Alert Threshold'
	lineageTag: 5d12eb87-fbaf-4539-92ac-b6ba566df463

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: ce0e5919-da1d-4a79-8ced-ff6f98fc5a33

	column Value
		dataType: double
		lineageTag: 2a96a386-23dd-468f-b6ec-dfaa4e4f514a
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-8f039e11-b4be-47d4-9f53-c4995c3a3434' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

