table 'Alert Threshold'
	lineageTag: 76f116f4-17f1-4684-85b0-17ec712d17e4

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 1a900cde-5690-4bd2-844b-173521188484

	column Value
		dataType: double
		lineageTag: 7dccd662-81eb-4040-8635-6c23c53f8b95
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-9f872103-5ae5-4db3-9df1-37f3484585f9' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

