table 'Alert Threshold'
	lineageTag: 59282493-5347-4d4d-9322-1309816d6a27

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: 38e0a1ad-53cc-47b0-b118-fd4d6448861b

	column Value
		dataType: double
		lineageTag: e6506e89-71d5-4085-9681-f111852e3cc7
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-9d7a82f8-0d00-46ee-9ea5-e119f4a12933' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table

