table Calendar
	lineageTag: af84d027-d35b-4ab0-aba0-64acd69f6359

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f384b37b-25e4-4354-b378-7fc88ba51230
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1a3aa4f8-b3f5-429f-8bbe-ae96cd3a67ce
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7d8837f5-29d4-4ecb-b197-5d233c0b9455
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 1b03ac5c-602c-4759-aaee-9083908c2398
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 53175f15-13c8-4a79-a727-76fcf137820c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 3cb7554c-c438-4ae4-9d9d-2b1dda47503d
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: b87c7786-1609-444a-b41e-cc183692cdcd
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: a252e256-0a52-4607-933d-dc4669fa0951
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7780efb2-c706-420a-bd84-bc69ca6d2b86

		level Year
			ordinal: 0
			column: Year
			lineageTag: ef13bfa2-dfb5-44e8-a54a-f5750d6d6027

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: d3fbb3de-0e40-4387-939e-a18849db0ba9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a8094a17-d7da-4452-8b70-72ff450de4f3

		level Day
			ordinal: 3
			column: Day
			lineageTag: 99d19830-d88b-42ad-9e26-b304d34e7777


	partition 'Calendar-bd6e326b-f82a-4b38-ab09-cc213eb58574' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

