table Calendar
	lineageTag: 8d007423-4885-4929-b027-7b252a3c11ce

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 155f55f7-888b-4e7b-8092-1db3220e4145
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e140b21f-1dab-4639-aea2-5a7111fd4dd1
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 97a5a295-d699-40cc-bab3-a2440a96f877
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 05164805-045d-4123-9f7b-0f07079d4d20
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0c082a77-6a09-4864-9931-5d6cc5572b39
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0e7a402e-777f-4924-91b5-fec4effbbfcd
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 36b84f37-78a1-4b46-a221-5c133ce02bd9
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 40ed7d8b-62a2-435d-96ee-ae6c92b1356d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 3334af54-3d28-44b0-afa4-c7c75cd11b04

		level Year
			ordinal: 0
			column: Year
			lineageTag: a6f52954-8d4f-413e-b1e4-afd73d4a8d9b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 314ffef4-470a-4bd0-a338-f20854e44a91

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 5f204119-cee4-4a79-829a-9b071bb872c7

		level Day
			ordinal: 3
			column: Day
			lineageTag: 40872501-685c-47b3-876d-f9c7df481efd


	partition 'Calendar-18d94864-f373-4bd7-b8fc-8162ea3c3bf2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

