table Calendar
	lineageTag: 41fc2cfc-430e-40f4-9012-c4d2f3d40de9

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e8d35168-7f7f-48a8-bd1d-dea2574cf589
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1bbc73c1-760e-4f4c-b0ee-e0d7f1665a83
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d8e858d7-99ff-4f18-9219-011846f495a3
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 58f99423-dc20-4910-8eb0-0e3010640b9d
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: be106885-cac5-4e1f-b086-25e69f61c99c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ae723cb5-0e47-402b-a8b3-c47cc39af686
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c475c3f6-116c-4798-8e46-37cbbed932a1
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: ef181235-7f97-4b49-bba1-4607cc4cbb55
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 89d50409-c1bd-4a10-906a-2310557681c7

		level Year
			ordinal: 0
			column: Year
			lineageTag: cb93f3ea-aeb2-4573-bd57-6aaf73d43ac6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 099d5d99-34e2-4e8b-9eb7-334f12fa532e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: b37660ea-2924-436d-83ab-06996d2cc089

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9e1839df-f7f4-4ed1-b5e8-c307216ec811


	partition 'Calendar-f8c3d5a0-3844-42e4-a81f-6a6665f745c2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

