table Calendar
	lineageTag: deda4cd0-c8af-411c-97a2-27eee2c8dac0

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bffe24d1-ed4b-4882-825e-0b8c34585f4b
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 60d81d71-02ec-425d-bdf6-86d239466a05
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 198c4cc8-bf89-46ba-a967-22897e3eeaa9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 9af100e6-1199-4893-b150-f88dacfa743f
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c040179f-0ae6-4824-9b8c-2f0d1a8ae8c4
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 2e27185f-506f-48a6-8f56-1d9c87db20d6
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4ca30792-b986-437c-ba8a-68612a505f9b
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 063f23f2-ff17-4d70-8fbd-1c40af66a06a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 85befd01-1c03-4c57-b183-6943518798c4

		level Year
			ordinal: 0
			column: Year
			lineageTag: 62da95e8-c351-4526-89e0-4aba9693a33f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 3b84ab71-ce59-4f3c-9663-5e2e12c08655

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9aa32443-bab6-423b-ab91-cb63c9d0b41f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 850ad601-15c5-40c2-8ab1-f6afd99828e8


	partition 'Calendar-f2f7bb60-0859-4387-9019-63c399c745c6' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

