table Calendar
	lineageTag: 633df115-c50c-4e7a-876a-0e3177c21d55

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: dd4ce607-6bb5-4a75-bdce-33fbda328d2d
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9ec98c65-4298-43e9-b248-83343b63c50d
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b8b1af41-a2c4-4764-b0c6-383c9331e84f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: efa25047-8235-4ae8-a955-641c71e191a1
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4753e02a-e1b3-4afc-a683-1f04105ea6c6
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 468b5e3a-a1bf-43e2-93c0-905017c10612
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 298e18dd-9e7b-4722-8973-1f150be7dac2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 92c9861d-b06f-4d02-8851-149d612f58f0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5d527c95-e311-46d0-87a1-98535c8c504f

		level Year
			ordinal: 0
			column: Year
			lineageTag: e3d5f81e-5bb6-4917-b523-5e5de15eccfc

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: fa79d103-eec6-4a17-9366-13ac69277861

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a44cd3d8-49e9-45ef-b9c5-62cb2b18446c

		level Day
			ordinal: 3
			column: Day
			lineageTag: af846751-96dc-4f8d-a5dd-8629d79f0f75


	partition 'Calendar-b65c3408-790d-4ad6-8058-14d6bb7c1dc5' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

