table Calendar
	lineageTag: 23fbb495-98f4-452b-a1dc-56cc3b8bc9ed

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: aec3dff4-0a38-4d7f-a60f-bad341909524
		summarizeBy: none
		sourceColumn: Date
		isKey
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 7174d073-5fc5-4178-8c57-e7299d2f4ffd
		summarizeBy: none
		sourceColumn: Year
		dataCategory: Years

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5bd5dc2a-995a-449e-97b9-e5b223e062b3
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 78ccf4b4-7100-4a81-99fd-effff1d217a0
		summarizeBy: none
		sourceColumn: Month
		dataCategory: Months

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e8150ca3-581d-4cf0-87c5-09bc135dca45
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0a6fa821-3716-4004-b494-93e887bdfda3
		summarizeBy: none
		sourceColumn: Day
		dataCategory: Days

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 936878db-1143-49c8-aa73-66f07a5cc604
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 15f64501-a84d-4653-b0db-76dc8464b71c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c90ab67b-df11-4a31-b1f0-3f131dd72eb6

		level Year
			ordinal: 0
			column: Year
			lineageTag: 31875d4d-39e3-442c-b3ec-fc6ffe935c18

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 76e0dd95-ffef-4eda-8d86-fd9a2a3181b2

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: cbf96ff9-bf0d-45f0-9c08-9f4464e1c17f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 6ae5cae4-cbea-43e5-8acf-9cc9daafc23a


	partition 'Calendar-bbb2e2c8-6803-4d01-b2b6-1c8648556014' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date])),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table

