table Machines
	lineageTag: 7b5db62c-4145-4a8c-ab49-8fcd0e8f962d

	column machine_id
		dataType: int64
		lineageTag: 04d679a2-dac0-41c0-86dc-8f9a37ba21c5
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column machine_name
		dataType: string
		lineageTag: c571deda-2965-4073-b6f4-9cbdccc48f68
		summarizeBy: none
		sourceColumn: machine_name

		annotation SummarizationSetBy = Automatic

	column machine_type
		dataType: string
		lineageTag: c40dbcae-5bfc-45ab-8fc1-1935f3c43736
		summarizeBy: none
		sourceColumn: machine_type

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d627008d-24bc-4f93-9c99-536d0b084fb1
		summarizeBy: none
		sourceColumn: install_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 2b7b05d5-917f-471e-b383-1be4a9b6835e
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: string
		lineageTag: cfdc10c4-3ddc-4bba-acdb-0f849a107c11
		summarizeBy: none
		sourceColumn: line_id

		annotation SummarizationSetBy = Automatic

	column rated_capacity
		dataType: double
		formatString: #,0.00
		lineageTag: c3511b30-8c3a-4c9f-990f-db8585916017
		summarizeBy: sum
		sourceColumn: rated_capacity

		annotation SummarizationSetBy = Automatic

	partition 'Machines-ada10cdb-e378-406f-a678-998e74d13ed7' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Machines Table" = Source{[Schema="DBO", Item="Machines"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Machines Table", {{"machine_id", "Machine ID"}, {"machine_name", "Machine Name"}, {"machine_type", "Machine Type"}, {"install_date", "Install Date"}, {"location", "Location"}, {"line_id", "Line ID"}, {"rated_capacity", "Rated Capacity"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

