table Machines
	lineageTag: f63b334b-a713-42c8-8789-5d6abb86ecf2

	column machine_id
		dataType: int64
		lineageTag: 6efe6f5a-f48e-4aeb-bbdb-8f41b159bf7d
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column machine_name
		dataType: string
		lineageTag: 37f93788-3421-42a8-910d-91f255746447
		summarizeBy: none
		sourceColumn: machine_name

		annotation SummarizationSetBy = Automatic

	column machine_type
		dataType: string
		lineageTag: eafaba77-c1c5-4e1b-aff3-fcb4cb391fc3
		summarizeBy: none
		sourceColumn: machine_type

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1588d730-169a-4235-a47e-3f2afefcd273
		summarizeBy: none
		sourceColumn: install_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 52e8cab2-38e7-41ea-9138-91a7120c6955
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: string
		lineageTag: 4d60625e-2f5e-4fcd-b43c-c3c91ed941ed
		summarizeBy: none
		sourceColumn: line_id

		annotation SummarizationSetBy = Automatic

	column rated_capacity
		dataType: double
		formatString: #,0.00
		lineageTag: f280712d-5107-4757-b138-6ed9ed5b0c38
		summarizeBy: sum
		sourceColumn: rated_capacity

		annotation SummarizationSetBy = Automatic

	partition 'Machines-252b1c81-f6c4-42a6-9053-713c29f54986' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Machines Table" = Source{[Schema="DBO", Item="Machines"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Machines Table", {{"machine_id", "Machine ID"}, {"machine_name", "Machine Name"}, {"machine_type", "Machine Type"}, {"install_date", "Install Date"}, {"location", "Location"}, {"line_id", "Line ID"}, {"rated_capacity", "Rated Capacity"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

