table Maintenance
	lineageTag: ff6d44c0-e741-4d72-81c1-0cd51a2b8e6d

	column maint_id
		dataType: int64
		lineageTag: d2a8c1c3-d512-433a-a188-7723615b7bf4
		summarizeBy: sum
		sourceColumn: maint_id

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: a0cedb96-7b9b-40e2-bbd6-9cf17c6e0a53
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: aa5e07e5-a206-4a0d-8e47-0df238cfb85d
		summarizeBy: none
		sourceColumn: maint_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: 9cdaac39-4cc0-4127-96ec-54e14f7f40aa
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: f77090bc-c41a-46aa-9cef-933e632e9f55
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: a4a5083d-e944-4279-a47e-829cdb15e23b
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: e9a42773-a33e-442e-8cfc-32d62586ecbc
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: abd45d07-f43d-47a4-8872-322b9110f3ec
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-4a51eaff-ce2b-4632-9fbe-31f0228828ad' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Maintenance Table" = Source{[Schema="DBO", Item="Maintenance"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Maintenance Table", {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

