table Maintenance
	lineageTag: 917514d5-a295-4b60-984a-0fee4fdeef1a

	column maint_id
		dataType: int64
		lineageTag: 1d1380f2-e0a9-46e7-b37b-97eb3ce17339
		summarizeBy: sum
		sourceColumn: maint_id

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 0cbac4b9-506b-4340-b5f5-7fa3687d19dc
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 547d8065-4e91-4535-b256-83dcfdb7c135
		summarizeBy: none
		sourceColumn: maint_date
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: 7aceef23-eec9-4c9f-87a1-3b95b44326d7
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 79e25681-cbda-4eb6-bb3e-2d186aae2847
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: d1d809b3-7d97-4e50-9ee7-48c41bb4b540
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: 8bcc969e-69bd-4ca8-9f27-22ade41f95e6
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: f71d4b3e-6e98-40cf-961a-48dfaaeedc6d
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-80d92146-f47e-41a2-83de-d2a33dceaff8' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Maintenance Table" = Source{[Schema="DBO", Item="Maintenance"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Maintenance Table", {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

