table Sensors
	lineageTag: 2ad215a2-b8b8-4d1b-970b-54400cefef71

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ffcf4168-6d4f-44d5-a6d4-eac48d9bd079

	measure 'P95 Value' = PERCENTILE.INC('Sensors'[value], 0.95)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 944a4e64-1072-4bf3-8841-1cb3dd3accdd

	measure 'Value Variance' = VAR.S('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 748d60a3-6535-4675-8fce-4d4349e6b346

	measure 'Value Variance Pop' = VAR.P('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 680ee329-890e-4cec-85f5-eb5f82cd8c08

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 4e6c0a19-b4e8-4cf4-b2fb-f62f07f8ae9a

	measure 'Running Avg Value' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 722ca45c-52d7-4e9a-ae9c-29c6d8ea7958

	measure 'Running Count' = CALCULATE(COUNT('Sensors'[reading_id]))
		displayFolder: Measures
		lineageTag: fa1ecd6d-a71a-48d4-a181-777add8446e0

	measure 'Running Max Value' = CALCULATE(MAX('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9d853b39-4582-4a86-ab17-5cd271ed7cc2

	measure 'Running Min Value' = CALCULATE(MIN('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 17537ebe-7c24-4a26-bf12-27c9599526d3

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: c7527bd8-71b0-4b5a-a2c8-0046fece3d0c

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		lineageTag: 506031f4-4429-4deb-88e7-3d78520c6963

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3ab11a7b-8fff-4adc-8b37-a70a4da6f78e

	measure 'Time Granularity' = "Hour"
		lineageTag: 8f09fbb0-1b09-4d2b-b4b9-5ce25b79cd1e

	column reading_id
		dataType: int64
		lineageTag: 94b15e0e-d742-447f-b878-f1a36532b82a
		summarizeBy: sum
		sourceColumn: reading_id

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 67791397-cd6f-4f30-84fd-fcae875926aa
		summarizeBy: none
		sourceColumn: reading_time
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 981aa6af-2d9c-4547-873c-435d0bdba757
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: ffcf14ac-5b67-4704-85d5-58c3f9561fa1
		summarizeBy: none
		sourceColumn: sensor_type

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 85c9dc1e-19ee-4d04-8349-ebb5c30da35c
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: 7942a1e9-f716-4938-a3d1-b13eaafb1e28
		summarizeBy: sum
		sourceColumn: threshold_min

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: d281041d-3bba-486d-b104-9151dde12f08
		summarizeBy: sum
		sourceColumn: threshold_max

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 4eae588e-02ec-4c7a-a280-00a5a3ffdf51
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: 6818fc16-1bcd-48fb-96fe-debe7455b24b
		summarizeBy: sum
		sourceColumn: quality_score

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: fddcd89e-c06d-4ae1-8a02-8625200f40c6
		summarizeBy: none
		sourceColumn: plant_id

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: 2b99ad22-3f6d-42d8-a9b8-b688c67e3ba0
		summarizeBy: sum
		sourceColumn: delta_value

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: 66f1dc68-eb53-403f-a308-f07a9d80dc6f
		summarizeBy: sum
		sourceColumn: angle_degrees

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: 27e24606-2975-436c-bf7d-9f2c2f2cdb63
		summarizeBy: sum
		sourceColumn: power_watts

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation'
		dataType: double
		formatString: #,0.00
		lineageTag: 5442347b-fc66-4f29-b5d5-2cb198a2d61c
		summarizeBy: none
		sourceColumn: 'Abs Deviation'

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: 679601b0-f46f-4f2e-870e-31a39d49d274
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Floor Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 105aced0-17f0-40ca-b401-794ca1383598
		summarizeBy: none
		sourceColumn: 'Floor Value'

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 01647d46-7fa6-499e-bfc1-b5010025a879
		summarizeBy: none
		sourceColumn: 'Rounded Value'

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: 93f498d5-7672-4477-967e-8a35a9f6ce45
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: 015dd933-f4a1-4a83-b874-50cd94207ed2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 979522fc-c788-4c30-ba49-01191e16bfa5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 6e29f379-f18c-44bb-939d-6290ffb4bd41
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: 1da87f46-7fa4-44fe-85af-5197a65f26e2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Month' = DATE(YEAR('Sensors'[reading_time]), MONTH('Sensors'[reading_time]), 1)
		dataType: dateTime
		lineageTag: ed141ad6-675e-422a-a227-37a09614d059
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		lineageTag: 0d411adc-cc09-4afa-bc65-fb77996f3077
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: f65d4bf1-6226-4c08-abdc-cbf87c17d27f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: a43a1a18-9f79-4106-abf2-21f1e56e2782
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-6dde7463-cea9-465f-b086-0fa1cd1dec97' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Sensors Table" = Source{[Schema="DBO", Item="Sensors"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Sensors Table", {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    #"Added Abs Deviation" = Table.AddColumn(#"Renamed Columns", "Abs Deviation", each Number.Abs([value] - ([threshold_min] + [threshold_max]) / 2), type number),
				    #"Added Floor Value" = Table.AddColumn(#"Added Abs Deviation", "Floor Value", each Number.RoundDown([value] / 1) * 1, type number),
				    #"Added Rounded Value" = Table.AddColumn(#"Added Floor Value", "Rounded Value", each Number.Round([value], 2), type number),
				    Result = #"Added Rounded Value"
				in
				    Result

	annotation PBI_ResultType = Table

