table Sensors
	lineageTag: 2e656ccc-4275-4df0-89a6-b2cf4fb81d9d

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: dbdbba1d-c87d-4e54-a545-276b45838e6f

	measure 'P95 Value' = PERCENTILE.INC('Sensors'[value], 0.95)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6e4f3f23-20c9-4d78-a769-3c99f12b5a5b

	measure 'Value Variance' = VAR.S('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 5e25b219-4cd2-4917-b5f9-5f37b2f42492

	measure 'Value Variance Pop' = VAR.P('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b00be3a5-c3a3-49e8-8311-b1f7697b120e

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ba9609b2-eb45-4c0a-ab6b-9ffc88f2df30

	measure 'Running Avg Value' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1878cfb1-4297-47d6-af98-379ec9185105

	measure 'Running Count' = CALCULATE(COUNT('Sensors'[reading_id]))
		displayFolder: Measures
		lineageTag: 6a696903-4953-4530-8c31-f51e0bed4107

	measure 'Running Max Value' = CALCULATE(MAX('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 373c62f9-d846-43c9-960a-1d13e9fb048e

	measure 'Running Min Value' = CALCULATE(MIN('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a4b3eb01-1896-4552-a745-b7dab0b1c472

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: c959e158-0d66-4ecd-8201-de47a12e9986

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		lineageTag: 03129073-6093-43d8-b7a4-87d846058c21

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: cc6d73c1-e728-44f3-a99d-3ca98137bf79

	measure 'Time Granularity' = "Hour"
		lineageTag: 3a4abebd-9d5e-4232-bd7f-e39d8ba6d57f

	column reading_id
		dataType: int64
		lineageTag: 0aabce2b-09a1-4994-9e04-d0b4666f8277
		summarizeBy: sum
		sourceColumn: reading_id

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 55b48846-5029-49b5-88f5-95e0c135d219
		summarizeBy: none
		sourceColumn: reading_time
		dataCategory: DateTime

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 8a351b7f-7e6f-4f79-8b73-c24ab3562468
		summarizeBy: sum
		sourceColumn: machine_id

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: 4cc36333-6615-437a-8cd1-97064938d7ba
		summarizeBy: none
		sourceColumn: sensor_type

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 34596a21-fe0d-4e62-ba8a-a93378985dc1
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: 58397e74-8676-4c54-84f8-74a366375f36
		summarizeBy: sum
		sourceColumn: threshold_min

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: 01ff331a-4030-440b-93cd-fd4b30f0616a
		summarizeBy: sum
		sourceColumn: threshold_max

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: ea79eb3f-8149-403b-aea4-b09ab11a36ec
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: d6ac3fe2-6c4c-4ecc-8319-45455885a70f
		summarizeBy: sum
		sourceColumn: quality_score

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: f726af36-8f79-4976-aa5d-b58f7c141c65
		summarizeBy: none
		sourceColumn: plant_id

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: f5d415bb-7a66-4f88-a2c9-edebdde59b98
		summarizeBy: sum
		sourceColumn: delta_value

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: fd92fd00-3598-4839-b491-496d34c6a395
		summarizeBy: sum
		sourceColumn: angle_degrees

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: c1715736-e7d9-43a7-8b7e-ba9958010add
		summarizeBy: sum
		sourceColumn: power_watts

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation' = ABS('Sensors'[value] - ('Sensors'[threshold_min] + 'Sensors'[threshold_max]) / 2)
		dataType: double
		formatString: #,0.00
		lineageTag: 09d8f25b-b3b6-4b82-a2d6-22c7deb470f6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: d1f3cec3-d86d-4768-96fb-fff6c9d8fe03
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Floor Value' = FLOOR('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: 301b2d9d-3aa6-431b-9fa6-34ed44da3065
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value' = ROUND('Sensors'[value], 2)
		dataType: double
		formatString: #,0.00
		lineageTag: 73a3f6a6-b639-405f-90bd-49f3bef0e9b5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: fe814310-2b83-4158-b6e7-4e6d5583a9b1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: d94a7413-adb1-4f04-a437-1a1789e0278e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 700a58b5-329d-45e9-bf72-ae0e1e3ef485
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 3203e4e9-707b-4da3-bbd2-aa624022bf7a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: 87e752ce-49e7-44f6-8a02-9fc44d536bfa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Month' = DATE(YEAR('Sensors'[reading_time]), MONTH('Sensors'[reading_time]), 1)
		dataType: dateTime
		lineageTag: 820b1053-7b7a-4ca2-b7ac-b2874a5fe017
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		lineageTag: 3d45ecf3-3cb2-4586-9e34-a9ce0dd9d88c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: 67bae8fe-b385-41fa-bfdc-9a046458eb9b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: 0fa2f98f-df4d-454d-a63c-e41f8d4d0463
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-89219c66-d5c1-4ea0-85d7-a414fa5b30e0' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				    #"Sensors Table" = Source{[Schema="DBO", Item="Sensors"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Sensors Table", {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table

